### PR TITLE
allow mGCA const arguments to fall back to anon consts

### PR DESCRIPTION
**Pull request by khyperia**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/158617)*

makes good progress on https://github.com/rust-lang/project-const-generics/issues/108

`min_generic_const_args` (mGCA) is all about "is this const lowered to a const item with a body, or, is it "directly" represented and visible in the type system?"

Here's various answers to the question of "can we represent this const arg directly?" - if we answer "no", then we fall back to an anon const (or error, sometimes, depending on context)

on **stable**, the full list of things can be directly represented is (... it's just the one thing)

- paths to generic const parameters

on `main`, under mGCA, **before** this PR:

- absolutely everything, if something cannot be represented directly, compiler error
- `const { }` gives you an escape hatch to go back to being an anon const

on macro**ful** gca, the directly represented things will be:

- paths to const parameters
- `direct_const_arg!` macro

on macro**less** gca, the directly represented things will be:

- paths to const parameters
- `direct_const_arg!` macro (not *particularly* useful under macro**less** gca)
- struct expressions, arrays, blah blah
- currently, paths to *anything*, even if that produces a compiler error later down the line (potential followup work here...)

this PR implements macro**less** gca, with the intent of a quick follow-up introducing a "macroless gca" feature and transitioning `#[feature(min_generic_const_args)]` to be macro**ful** gca

Also of note is that this PR removes the logic to skip generating "fake" DefIds for directly represented AnonConsts under mGCA, we now always generate a DefId when encountering an AnonConst. This lines up with stable, which has a fake AnonConst DefId for a directly represented plain path generic parameter (i.e. the bullet point under the "stable" entry above).

r? @BoxyUwU

### CODE REVIEW

File: src/tools/rustfmt/src/types.rs [hunk 1]
```diff
@@ -1054,6 +1054,10 @@ impl Rewrite for ast::Ty {
                 result.push_str(&rewrite);
                 Ok(result)
             }
+            ast::TyKind::DirectConstArg(ref expr) => {
+                let expr = expr.rewrite_result(context, shape)?;
+                Ok(format!("core::direct_const_arg!({expr})"))
+            }
```
Comment (ytmimi) [inline src/tools/rustfmt/src/types.rs]: Just double checking that `core::direct_const_arg!` won't show up as a macro call in the AST. Might be better to just return `Err(RewriteError::Unknown)` or even `Ok(context.snippet(self.span).to_owned())` to return the span unchanged.

**Review by ytmimi — COMMENTED** [review]
Would be great to also add a simple rustfmt test case annotated with `#![feature(min_generic_const_args)]` so we know it's for an unstable feature.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/158617/51657149e91586571ff1c463bc58239daa1a88d2..f0b3a401358969a46cb4a21c232276d631cc4a49)*

File: src/tools/rustfmt/src/types.rs (hunk 1 above)
Comment (khyperia) [reply src/tools/rustfmt/src/types.rs]: ah, good point, I didn't quite realize how rustfmt works, thank you! could you please double-check what I just force-pushed to make sure it's what you were thinking of?

in particular, I'm not totally sure why `ast::ExprKind::Err(_) | ast::ExprKind::Dummy` return `Err(RewriteError::Unknown)`, but `ast::TyKind::Dummy | ast::TyKind::Err(_)` return `Ok(context.snippet(self.span).to_owned())`. I kept doing that for `DirectConstArg`, but, yeah.

File: compiler/rustc_parse/src/parser/item.rs [hunk 2]
```diff
@@ -1682,9 +1682,9 @@ impl<'a> Parser<'a> {
             if self.may_recover() { self.parse_where_clause()? } else { WhereClause::default() };
 
         let rhs = match (self.eat(exp!(Eq)), const_arg) {
-            (true, true) => ConstItemRhsKind::TypeConst {
-                rhs: Some(self.parse_expr_anon_const(|_, _| MgcaDisambiguation::Direct)?),
-            },
+            (true, true) => {
+                ConstItemRhsKind::TypeConst { rhs: Some(self.parse_expr_anon_const()?) }
```
Comment (BoxyUwU) [inline compiler/rustc_parse/src/parser/item.rs:1700]: we should track somewhere to stop parsing type const rhs' differently than normal const items I think :3 this goes hand in hand with i guess the stuff about lowering the rhs of type consts as if they were `direct`'d?

File: compiler/rustc_resolve/src/def_collector.rs [hunk 3]
```diff
@@ -425,26 +425,9 @@ impl<'a, 'ra, 'tcx> visit::Visitor<'a> for DefCollector<'a, 'ra, 'tcx> {
...
-        match constant.mgca_disambiguation {
-            MgcaDisambiguation::Direct => visit::walk_anon_const(self, constant),
-            MgcaDisambiguation::AnonConst => {
-                let parent = self
-                    .create_def(constant.id, None, DefKind::AnonConst, constant.value.span)
-                    .def_id();
-                self.with_parent(parent, |this| visit::walk_anon_const(this, constant));
-            }
-        };
+        let parent =
```
Comment (BoxyUwU) [inline compiler/rustc_resolve/src/def_collector.rs:428]: hurray less def collector and parsing jank :relieved:

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 4]
```diff
@@ -2628,26 +2647,33 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
     }
 
+    /// This function may only ever be called once with check_only=false, and when doing so, it only
+    /// ever returns Ok(Some(..)).
+    /// This function may be called multiple times with check_only=true, and when doing so, it
+    /// either returns Ok(None) if the expression can be lowered to a direct argument, or Err(()) if
+    /// it cannot.
     #[instrument(level = "debug", skip(self), ret)]
-    fn lower_expr_to_const_arg_direct(&mut self, expr: &Expr) -> hir::ConstArg<'hir> {
+    fn try_lower_expr_to_const_arg_direct(
```
Comment (BoxyUwU) [inline compiler/rustc_ast_lowering/src/lib.rs]: this fn is like slightly scuffed but I need to think a bit about why that is and what an alternative might be :3

**Review by BoxyUwU — COMMENTED** [review]
good stuffs

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/158617/17aa77551e89d5e80d4b506c9a32fc151264b8e4..4c7a81ed388532168a3beba388a455b26c2f8e6e)*

File: src/tools/rustfmt/src/types.rs (hunk 1 above)
Comment (BoxyUwU) [reply src/tools/rustfmt/src/types.rs]: i would expect this codepath to actually be unreachable. `direct_const_arg!` is a macro call in the AST and rustfmt will see the unexpanded AST so we'll never encounter a `DirectConstArg` expr/ty :thinking: does ICEing here cause any issues?

Comment (BoxyUwU) [reply src/tools/rustfmt/src/types.rs]: oh this is the:
> rustfmt tries to parse macro arguments when formatting macros, so it's not
> totally impossible for rustfmt to come across one of these nodes when formatting
> a file

thats funny

File: compiler/rustc_ast_lowering/src/lib.rs [hunk 5]
```diff
@@ -2658,26 +2684,61 @@ impl<'hir> LoweringContext<'_, 'hir> {
...
             }
-            ExprKind::Tup(exprs) => {
-                let exprs = self.arena.alloc_from_iter(exprs.iter().map(|expr| {
-                    let expr = self.lower_expr_to_const_arg_direct(&expr);
-                    &*self.arena.alloc(expr)
-                }));
+            ExprKind::Tup(exprs) if is_mgca => {
+                if check_only {
+                    for expr in exprs {
+                        let _ = self.try_lower_expr_to_const_arg_direct(expr, None, check_only)?;
```
Comment (BoxyUwU) [inline compiler/rustc_ast_lowering/src/lib.rs]: iirc the reason we recurse into tuple elements but not path arguments is that we can't support `(N, 1 + 1)` without `(N, const { 1 + 1 })` because we dont want to make a defid for all tuple element exprs in advance so that we can reuse the defid here

should write that down somewhere in here as the inconsistency between paths and other exprs feels slightly weird :3

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/158617/17aa77551e89d5e80d4b506c9a32fc151264b8e4..4c7a81ed388532168a3beba388a455b26c2f8e6e)*

File: compiler/rustc_parse/src/parser/item.rs (hunk 2 above)
Comment (khyperia) [reply compiler/rustc_parse/src/parser/item.rs:1700]: precisely and exactly. very much on my todo list for the followup I was talking about!

File: compiler/rustc_ast_lowering/src/lib.rs (hunk 4 above)
Comment (khyperia) [reply compiler/rustc_ast_lowering/src/lib.rs]: it's SO scuffed, and it's gonna get worse once we introduce macroful gca.

the main issue IMO is that we need a separate "check" and "actually do" phase, because we could fail several layers deep - e.g. we're inside a tuple, `((lowering, stuff), (and + then + we + error))`, if we have already lowered and allocated arena memory when lowering `(lowering, stuff)`, we cannot then bail out when we encounter the addition expr, because then all those generated IDs and arena memory and stuff would get unused.

File: compiler/rustc_ast_lowering/src/lib.rs (hunk 5 above)
Comment (khyperia) [reply compiler/rustc_ast_lowering/src/lib.rs]: yeah. if we generated defids for everything, we wouldn't need this weird separate "check" and "actually do" phases, because we could always bail to representing things as anon consts if we fail to lower some later tuple element after successfully lowering previous tuple elements, and `(N, 1 + 1)` would sorta implicitly have a `const { 1 + 1 }` block.

... but generating defids for everything is, Not Great

File: compiler/rustc_metadata/src/rmeta/encoder.rs [hunk 6]
```diff
@@ -1439,26 +1439,9 @@ impl<'a, 'tcx> EncodeContext<'a, 'tcx> {
...
-                        | hir::ConstArgKind::TupleCall(..)
-                        | hir::ConstArgKind::Tup(..)
-                        | hir::ConstArgKind::Path(..)
-                        | hir::ConstArgKind::Literal { .. }
-                        | hir::ConstArgKind::Infer(..) => true,
-                        hir::ConstArgKind::Anon(..) => false,
-                    },
-                    _ => false,
-                }
+                && matches!(tcx.hir_node_by_def_id(local_id), hir::Node::ConstArg(_))
```
Comment (BoxyUwU) [inline compiler/rustc_metadata/src/rmeta/encoder.rs:1443]: it would somewhat not surprise me if this causes ICEs, I would expect that if we have these defids in the parent tree then we actually do need to encode them 🤔 


*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/158617/e2b71ade2db4ea263ab0d561d889f3e3795a500d..68d2d7ee1feb3f3585bf1844667a45376d70a61f)*

File: tests/ui/const-generics/mgca/auxiliary/anon-const-def-id-on-const-arg-with-anon.rs [hunk 7]
```diff
@@ -0,0 +1,6 @@
+#![feature(min_generic_const_args)]
+#![allow(incomplete_features)]
+pub struct S<const N: usize>;
+pub fn f() -> S<{ const { 1 + 1 } }> {
```
Comment (BoxyUwU) [inline tests/ui/const-generics/mgca/auxiliary/anon-const-def-id-on-const-arg-with-anon.rs:9]: is this an anon const with a const block inside it? can we have comment about what we expect this to lower to :3 

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/158617/e2b71ade2db4ea263ab0d561d889f3e3795a500d..68d2d7ee1feb3f3585bf1844667a45376d70a61f)*

**Review by BoxyUwU — COMMENTED** [review]
can we get a test that using `direct_const_arg` without any feature enabled gives a feature gate error even when using it in const arg position, e.g. `fn foo<const N: usize>() -> [(); direct_const_arg!(N)]` should error

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/158617/e2b71ade2db4ea263ab0d561d889f3e3795a500d..68d2d7ee1feb3f3585bf1844667a45376d70a61f)*

File: compiler/rustc_builtin_macros/src/direct_const_arg.rs [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+    span: Span,
+    tts: TokenStream,
+) -> MacroExpanderResult<'cx> {
+    let mut parser = cx.new_parser_from_tts(tts);
+    let expr = match parser.parse_expr() {
+        Ok(parsed) => parsed,
+        Err(err) => {
+            return ExpandResult::Ready(DummyResult::any(span, err.emit()));
+        }
+    };
```
Comment (bit-aloo) [inline compiler/rustc_builtin_macros/src/direct_const_arg.rs]: I have this question, like do we expect the `direct_const_arg!` to contain multiple expressions?

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/158617/e2b71ade2db4ea263ab0d561d889f3e3795a500d..68d2d7ee1feb3f3585bf1844667a45376d70a61f)*

Comment (khyperia) [reply compiler/rustc_builtin_macros/src/direct_const_arg.rs]: good point! fixed now :3

**Comment by BoxyUwU** [comment]
r=me if CI passes

**Comment by JonathanBrouwer** [comment]
💔 I suspect this PR failed tests as part of a rollup
@bors r-

After fixing the problem, consider running a try job for the failed job before re-approving.

Link to failure: https://github.com/rust-lang/rust/pull/158906#issuecomment-4903846650

**Comment by khyperia** [comment]
Ah, yep, failed due to merge conflict with https://github.com/rust-lang/rust/pull/156968 which was also in the rollup. Fixing!

edit: actually wait, I suppose I'll need to wait for that one to merge first, to be able to fix the merge conflict

**Comment by JonathanBrouwer** [comment]
@bors r=BoxyUwU

The other pr had more problems so this one can go in the rollup then

**Comment by khyperia** [comment]
@bors r=BoxyUwU

third time's the charm?

File: tests/ui/const-generics/mgca/type-const-value-type-mismatch.next.stderr [hunk 9]
```diff
@@ -16,7 +16,7 @@ error[E0284]: type annotations needed
 LL |     fn arr() -> [u8; const { Self::LEN }] {}
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer the value of the constant `_`
    |
-   = note: cannot satisfy `<A as Array>::arr::{constant#0} == _`
+   = note: cannot satisfy `<A as Array>::arr::{constant#0}::{constant#0} == _`
```
Comment (bit-aloo) [inline tests/ui/const-generics/mgca/type-const-value-type-mismatch.next.stderr:19]: Curious on why this is duplicated? I will try to investigate more on this.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/158617/5e91de65d75d3c849c643f5079509b9e5985a5c0..67986afdaf544482bc89fc1be5de309d4dbbcf89)*

File: library/core/src/marker.rs [hunk 10]
```diff
@@ -1073,6 +1073,20 @@ pub const trait Destruct: PointeeSized {}
 #[rustc_dyn_incompatible_trait]
 pub trait Tuple {}
 
+/// Creates a new style directly represented const argument.
+/// ```ignore (cannot test this from within core yet)
+/// type const BAR<const N: usize>: usize = N;
+/// type const FOO<const N: usize>: usize = direct!(BAR::<N>);
```
Comment (bit-aloo) [inline library/core/src/marker.rs:1079]: nit:
```suggestion
/// type const FOO<const N: usize>: usize = direct_const_arg!(BAR::<N>);
```

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/158617/5e91de65d75d3c849c643f5079509b9e5985a5c0..67986afdaf544482bc89fc1be5de309d4dbbcf89)*

File: tests/ui/const-generics/mgca/type-const-value-type-mismatch.next.stderr (hunk 9 above)
Comment (khyperia) [reply tests/ui/const-generics/mgca/type-const-value-type-mismatch.next.stderr:19]: it is intentional! we now generate potentially "fake" DefIds for anon consts (see diff to `compiler/rustc_resolve/src/def_collector.rs`).

- if the anon const that the DefId was created for is actually used in `compiler/rustc_ast_lowering/src/lib.rs`, yippee, nice, use the DefId for the anon const.
- if it isn't, shoot, we need to shove the DefId somewhere, it's required to be used in the HIR output, uuuh, shove it on the ConstArg I guess (this is a "fake" DefId)

notably, the def_collector runs before we're able to know whether we're able to represent the syntax directly or not, so it cannot know whether to generate a DefId ahead of time or not.

this matches the behavior of stable, for min_const_generic simple paths to generic parameters (min_const_generic_args experimented with yeeting this fake DefId, but that turned out to not be viable in the long run, so this PR adds 'em back)

Comment (khyperia) [reply tests/ui/const-generics/mgca/type-const-value-type-mismatch.next.stderr:19]: in other words, for the syntax `[u8; const { Self::LEN }]` in the test file, there are now two constants:

- the automatically generated anon const ID (this is the new one). It is placed on a random ConstArg. Confusingly, this is a ConstArgKind::Anon(..), which holds...
- ... the inner `const{}` block, which has a DefId that is a `DefKind::InlineConst`

("confusingly" because you could also consider, say, `[u8; (2, const { 5 })]` - ignoring the nonsense type, the fake anon const ID would be placed on the ConstArgKind::Tuple. But because it's directly representing... another anon const... it's on ConstArgKind::Anon(..). See also the test I added `tests/ui/const-generics/mgca/serialized-direct-const-with-anon-const-body.rs` which has another comment describing this situation, an anon const directly inside of another anon const)

... I feel like I'm just being confusing now, sorry. Feel free to DM me on zulip if you're confused, haha

**Comment by bit-aloo** [comment]
I was thinking about this while reviewing the PR, and wanted to double-check one resolver path.

For `S<{ N }>`, the compiler knows from the syntax that this is a const argument. It is represented roughly as `GenericArg::Const(AnonConst { .. })`, so it naturally goes through the const-arg resolver path.

For `S<N>`, the compiler cannot know from parsing alone whether `N` is a type argument or a const argument. So it is initially represented more like `GenericArg::Type(TyKind::Path(...))`. Later, in `visit_generic_arg`, we have a special logic to check whether this path-like type argument is actually a trivial const argument. If it is, we resolves it through the const-arg path; otherwise it continues with normal `visit_ty`.

For `S<direct_const_arg!(N)>`, I think it also starts out as a type-looking generic argument, probably as a macro call in type position. After macro expansion, it becomes something like `GenericArg::Type(TyKind::DirectConstArg(expr))`. I wonder if we should handle `TyKind::DirectConstArg` in `visit_generic_arg`, next to the existing `TyKind::Path` disambiguation logic, and resolve its inner expression with `resolve_anon_const_manual`. Otherwise it seems like it may fall through to normal `visit_ty`.

Curious to know what you think about this?

**Comment by khyperia** [comment]
true! to be honest, I haven't thought that much about the resolver, but yeah, right now, TyKind::DirectConstArg is currently nameres'd as just a plain `visit::walk_ty(self, ty)`, no additional ribs. So we probably accept some things that we shouldn't, or resolve lifetimes wonkily due to the lack of a `LifetimeRibKind::elided(LifetimeRes::Infer)` that is typically on anon consts.

I might address this at the same time as addressing this https://github.com/rust-lang/rust/pull/158617#discussion_r3505927025 (make the rhs of type consts less special), that involves mucking around with nameres a decent amount and it might be easiest to deal with both cases at the same time.

**Comment by JonathanBrouwer** [comment]
@rust-timer build 34f29a2e47e12402689524fda62fbf97ef33f4cf
