### ISSUE TITLE
Cycle detected when using associated type bounds in super trait

### ISSUE THREAD

**Issue by tage64** [rust-lang/rust#65913]
I don't know if this is a bug or expected behaviour. But I'm encountering the following error when compiling the following code.
#![feature(associated_type_bounds)]

trait A {
    type T;
}

trait B: A<T: B> {}
error[E0391]: cycle detected when computing the supertraits of `B`
 --> src/main.rs:6:15
  |
6 | trait B: A<T: B> {}
  |               ^
  |
  = note: ...which again requires computing the supertraits of `B`, completing the cycle
note: cycle used when collecting item types in top-level module
 --> src/main.rs:6:1
  |
6 | trait B: A<T: B> {}
  | ^^^^^^^^^^^^^^^^
But if I merge the traits A and B into the trait C it works.
trait C {
    type T: C;
}
I think the first example should work as good as the second since the trait C is only split into two traits A and B with same functionality.

**Comment by Centril** [comment]
When we write:

```rust
trait B: A<T: B> {}
```

this is equivalent to:

```rust
trait B
where
    Self: A<T: B>
{}
```

which is equivalent to:

```rust
trait B
where
    Self: A,
    <Self as A>::T: B,
{}
```

This results in an error:

```rust
error[E0277]: the trait bound `<<Self as A>::T as A>::T: B` is not satisfied
```

One might think that this should compile because `<<Self as A>::T as A>::T: B` should flow from the mere fact that `Self::T: B` holds which should hold by `Self: B`. However, the compiler isn't smart enough to take these [implied bounds](https://github.com/rust-lang/rust/issues/44491) into account. When it comes to the special case of `type T: C;`, the compiler is able to do that however.

What is curious here is that rather than getting the error message about "not satisfied", we are getting a cycle error. cc @alexreg @nikomatsakis @tmandry

**Comment by eddyb** [comment]
I wonder if the supertraits query is including the associated type bound - AFAIK it should only include the bounds specified on `Self` itself, not associated types of `Self` or other types.

**Comment by jendrikw** [comment]
This issues still happens, are there any updates on fixes?

**Comment by compiler-errors** [comment]
As of #110512, this is no longer a cycle error, and the code above errors with:

```
error[E0277]: the trait bound `<<Self as A>::T as A>::T: B` is not satisfied
 --> /home/../test.rs:7:15
  |
7 | trait B: A<T: B> {}
  |               ^ the trait `B` is not implemented for `<<Self as A>::T as A>::T`
  |
note: required by a bound in `B`
 --> /home/../test.rs:7:15
  |
7 | trait B: A<T: B> {}
  |               ^ required by this bound in `B`
help: consider further restricting the associated type
  |
7 | trait B: A<T: B> where <<Self as A>::T as A>::T: B {}
  |                  +++++++++++++++++++++++++++++++++
```

The fact that this still errors is a somewhat unfortunate side-effect of https://github.com/rust-lang/rust/issues/65913#issuecomment-547390524, since the `<Self as A>::T: B` bound is not implied by the supertrait bounds. 

Fixing this in a way that doesn't cause the compiler to overflow generating an infinite nested set of `<<<<<<... as A>::T as A>::T as A>::T as A>::T as A>::T as A>::T: B` bounds is gonna be pretty difficult, though.

**Comment by fmease** [comment]
This now hangs on nightly (not only the sugared form but also the desugared one)

@rustbot label I-hang E-needs-mcve

**Comment by fmease** [comment]
Regressed in #112629 (git-revert: hang → errors).
@rustbot label -E-needs-bisection

**Comment by compiler-errors** [comment]
I don't believe this will ever be made to compile. A cycle error IMO is the correct state for this. Diagnostics could perhaps be improved, but they would need to explain some details about how supertrait bound elaboration works.
