### ISSUE TITLE
Rust 1.19 regression, treebitmap 0.2.2

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#42467]
https://github.com/hroi/treebitmap

```
commit 67b8a1d591dd13a26b36519a92f5215a53c5c02e
Author: Hroi Sigurdsson <hroi@asdf.dk>
Date:   Mon Jan 23 16:15:28 2017 +0100

    travis
```

```
brian@ip-10-145-43-250:/mnt2/dev⟫ rustc +nightly -Vv
rustc 1.19.0-nightly (0418fa9d3 2017-06-04)
binary: rustc
commit-hash: 0418fa9d382a47d782cc1e195c14573be9c32095
commit-date: 2017-06-04
host: x86_64-unknown-linux-gnu
release: 1.19.0-nightly
LLVM version: 4.0

```

```

brian@ip-10-145-43-250:~/dev/slate/treebitmap⟫ cargo +nightly test
   Compiling treebitmap v0.2.2 (file:///mnt2/dev/slate/treebitmap)
error[E0311]: the parameter type `T` may not live long enough
   --> src/tree_bitmap/mod.rs:479:9
    |
479 | impl<T> IntoIterator for TreeBitmap<T> {
    |         ^^^^^^^^^^^^
    |
    = help: consider adding an explicit lifetime bound for `T`
    = note: the parameter type `T` must be valid for the empty lifetime...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/tree_bitmap/mod.rs:479:9
    |
479 | impl<T> IntoIterator for TreeBitmap<T> {
    |         ^^^^^^^^^^^^

error[E0311]: the parameter type `T` may not live long enough
   --> src/tree_bitmap/mod.rs:479:9
    |
479 | impl<T> IntoIterator for TreeBitmap<T> {
    |         ^^^^^^^^^^^^
    |
    = help: consider adding an explicit lifetime bound for `T`
    = note: the parameter type `T` must be valid for the empty lifetime...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/tree_bitmap/mod.rs:479:9
    |
479 | impl<T> IntoIterator for TreeBitmap<T> {
    |         ^^^^^^^^^^^^

error[E0311]: the parameter type `T` may not live long enough
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
273 | impl_ops!(Ipv4Addr);
    | -------------------- in this macro invocation
    |
    = help: consider adding an explicit lifetime bound for `T`
    = note: the parameter type `T` must be valid for the empty lifetime...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
273 | impl_ops!(Ipv4Addr);
    | -------------------- in this macro invocation

error[E0311]: the parameter type `T` may not live long enough
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
273 | impl_ops!(Ipv4Addr);
    | -------------------- in this macro invocation
    |
    = help: consider adding an explicit lifetime bound for `T`
    = note: the parameter type `T` must be valid for the empty lifetime...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
273 | impl_ops!(Ipv4Addr);
    | -------------------- in this macro invocation

error[E0311]: the parameter type `T` may not live long enough
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
274 | impl_ops!(Ipv6Addr);
    | -------------------- in this macro invocation
    |
    = help: consider adding an explicit lifetime bound for `T`
    = note: the parameter type `T` must be valid for the empty lifetime...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
274 | impl_ops!(Ipv6Addr);
    | -------------------- in this macro invocation

error[E0311]: the parameter type `T` may not live long enough
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
274 | impl_ops!(Ipv6Addr);
    | -------------------- in this macro invocation
    |
    = help: consider adding an explicit lifetime bound for `T`
    = note: the parameter type `T` must be valid for the empty lifetime...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
274 | impl_ops!(Ipv6Addr);
    | -------------------- in this macro invocation

error: aborting due to previous error(s)

error: Could not compile `treebitmap`.
Build failed, waiting for other jobs to finish...
error[E0311]: the parameter type `T` may not live long enough
   --> src/tree_bitmap/mod.rs:479:9
    |
479 | impl<T> IntoIterator for TreeBitmap<T> {
    |         ^^^^^^^^^^^^
    |
    = help: consider adding an explicit lifetime bound for `T`
    = note: the parameter type `T` must be valid for the empty lifetime...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/tree_bitmap/mod.rs:479:9
    |
479 | impl<T> IntoIterator for TreeBitmap<T> {
    |         ^^^^^^^^^^^^

error[E0311]: the parameter type `T` may not live long enough
   --> src/tree_bitmap/mod.rs:479:9
    |
479 | impl<T> IntoIterator for TreeBitmap<T> {
    |         ^^^^^^^^^^^^
    |
    = help: consider adding an explicit lifetime bound for `T`
    = note: the parameter type `T` must be valid for the empty lifetime...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/tree_bitmap/mod.rs:479:9
    |
479 | impl<T> IntoIterator for TreeBitmap<T> {
    |         ^^^^^^^^^^^^

error[E0311]: the parameter type `T` may not live long enough
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
273 | impl_ops!(Ipv4Addr);
    | -------------------- in this macro invocation
    |
    = help: consider adding an explicit lifetime bound for `T`
    = note: the parameter type `T` must be valid for the empty lifetime...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
273 | impl_ops!(Ipv4Addr);
    | -------------------- in this macro invocation

error[E0311]: the parameter type `T` may not live long enough
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
273 | impl_ops!(Ipv4Addr);
    | -------------------- in this macro invocation
    |
    = help: consider adding an explicit lifetime bound for `T`
    = note: the parameter type `T` must be valid for the empty lifetime...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
273 | impl_ops!(Ipv4Addr);
    | -------------------- in this macro invocation

error[E0311]: the parameter type `T` may not live long enough
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
274 | impl_ops!(Ipv6Addr);
    | -------------------- in this macro invocation
    |
    = help: consider adding an explicit lifetime bound for `T`
    = note: the parameter type `T` must be valid for the empty lifetime...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
274 | impl_ops!(Ipv6Addr);
    | -------------------- in this macro invocation

error[E0311]: the parameter type `T` may not live long enough
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
274 | impl_ops!(Ipv6Addr);
    | -------------------- in this macro invocation
    |
    = help: consider adding an explicit lifetime bound for `T`
    = note: the parameter type `T` must be valid for the empty lifetime...
note: ...so that the type `T` will meet its required lifetime bounds
   --> src/lib.rs:259:17
    |
259 |         impl<T> IntoIterator for IpLookupTable<$addr_type, T> {
    |                 ^^^^^^^^^^^^
...
274 | impl_ops!(Ipv6Addr);
    | -------------------- in this macro invocation

error: aborting due to previous error(s)

error: build failed
```

cc @hroi

**Comment by Mark-Simulacrum** [comment]
Bisected to 826d8f3850b37a23481dfcf4a899b5dfc82d22e3 -- #41914 cc @eddyb

**Comment by eddyb** [comment]
Reduces to (note the `T: 'a` with `'a` not used anywhere):
```rust
struct Foo<T>(T);

struct IntoIter<T>(T);

impl<'a, T: 'a> Iterator for IntoIter<T> {
    type Item = ();

    fn next(&mut self) -> Option<()> {
        None
    }
}

impl<T> IntoIterator for Foo<T> {
    type Item = ();
    type IntoIter = IntoIter<T>;

    fn into_iter(self) -> IntoIter<T> {
        IntoIter(self.0)
    }
}

fn main() {}
```

cc @rust-lang/lang I thought we decided that kind of "use" of a parameter is invalid?

**Comment by kennytm** [comment]
There should be a lint about the useless lifetime ([this line](https://github.com/hroi/treebitmap/blob/67b8a1d591dd13a26b36519a92f5215a53c5c02e/src/tree_bitmap/mod.rs#L464) in real code) though.
