### ISSUE TITLE
found two different crates with name `std`

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#35636]
I'm trying to compile the following file:

```
#![feature(rustc_private)]
extern crate flate;
fn main() {}
```

This works with both 1.10 (stable) and 1.11 (beta) if I feed it the correct RUSTC_BOOTSTRAP_KEY. However for 1.12 (nightly 20160811) I'm getting this error:

```
$ rustc test.rs 
error[E0523]: found two different crates with name `std` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
 --> test.rs:2:1
  |
2 | extern crate flate;
  | ^^^^^^^^^^^^^^^^^^^

101 # exit code
```

I'm using my beta/nightly [PPA packages](https://launchpad.net/~infinity0/+archive/ubuntu/rust-nightly) for Ubuntu and not the "official" rust nightly, but I don't think I'm doing anything particularly weird that would cause this. In particular, the 1.11 and 1.12 packages have the same files, if one ignores the suffixes.

**Comment by Mark-Simulacrum** [comment]
I can't reproduce with recent nightly, so I'm going to go ahead and close.
