### PR TITLE
Do not accidentally treat multi-segment meta-items as single-segment

### LINKED ISSUE #55168: proc_macro_derive(attributes(path::to)) both does and doesn't work
```rust
// crate `derive`
// lib.proc-macro = true
#[proc_macro_derive(WellThen, attributes(well::then))]
pub fn derive(i: ::proc_macro::TokenStream) -> ::proc_macro::TokenStream {
    i
}

// crate `user`
use derive::WellThen;
#[derive(WellThen)]
#[well::then]
struct A;
```

```
error[E0433]: failed to resolve. Use of undeclared type or module `well`
  --> user\main.rs:3:3
   |
 3 | #[well::then]
   |   ^^^^ Use of undeclared type or module `well`
```

I would expect either for this to work or for `#[proc_macro_derive(attributes(..))]` to reject a path and only accept an ident, as specifying a path here doesn't work.

### PR DESCRIPTION
**Pull request by petrochenkov**
Fixes https://github.com/rust-lang/rust/issues/55168 and many other regressions from https://github.com/rust-lang/rust/pull/50030

Basically, attributes like `#[any::prefix::foo]` were commonly interpreted as `#[foo]` due to `name()` successfully returning the last segment (this applies to nested things as well `#[attr(any::prefix::foo)]`).

### CODE REVIEW

**Comment by petrochenkov** [comment]
@craterbot run start=master#c0086b9e8972fef9fd4af24bae20d45021ed06c6 end=try#290ac7b29f41ff9fa5232f9a1116ea71a3501063 mode=check-only

**Comment by Mark-Simulacrum** [comment]
@craterbot retry

**Comment by Mark-Simulacrum** [comment]
@craterbot retry

**Comment by petrochenkov** [comment]
Oh, great, no regressions.

**Comment by petrochenkov** [comment]
I'm going to beta-nominate the first three commits (https://github.com/rust-lang/rust/pull/58899/files/cd71788b8cbc55eb89a391eb65bcc6cb27c5a107) despite the size.
The regression these commits fix has large scope and backward-compatibility implications, so it would be good to fix it sooner.

**Comment by petrochenkov** [comment]
r? @estebank 

Reviewing tips for https://github.com/rust-lang/rust/pull/58899/commits/971542825c8bb23840d8ed00cbf967c1e45be5af:
The primary change is introduction of `fn ident(&self) -> Option<Ident>` API for `Attribute`/`MetaItem`/`NestedMetaItem` in `libsyntax/attr/mod.rs` (+ `fn ident_str(&self) -> Option<&str>` convenience methods) and removal of the old similar methods.
Code in other files in then migrated to the new API.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/59066#issuecomment-471282953, @bors r-

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting. Discovered that the phrase "first three commits" is ambiguous given non-determinism in github presentation. @petrochenkov will provide a more specific indication of what is being proposed.

leaving tagged as beta-nominated for now, not explicitly accepting nor rejecting until next week's meeting.

**Comment by petrochenkov** [comment]
Backport candidate prepared in https://github.com/rust-lang/rust/pull/59259
