### ISSUE TITLE
highlight-1.0.0 doesn't build on 1.16 beta

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#39806]
https://github.com/neunenak/hilite ac0768130d52219a247d383285ac4adb88d8d1f0

```
   Compiling getopts v0.2.14
   Compiling hilite v1.0.0 (file:///mnt2/dev/hilite)
error[E0277]: the trait bound `&&[std::string::String]: std::iter::Iterator` is not satisfied
  --> src/main.rs:83:32
   |
83 |                               .args(& program_args)
   |                                ^^^^ the trait `std::iter::Iterator` is not implemented for `&&[std::string::String]`
   |
   = note: `&&[std::string::String]` is not an iterator; maybe try calling `.iter()` or a similar method
   = note: required because of the requirements on the impl of `std::iter::IntoIterator` for `&&[std::string::String]`

error: aborting due to previous error

error: Could not compile `hilite`.

To learn more, run the command again with --verbose.
```

```
rustc 1.16.0-beta.1 (5276ba72e 2017-01-31)
binary: rustc
commit-hash: 5276ba72e8fe13597200254447fce9cb3783c583
commit-date: 2017-01-31
host: x86_64-unknown-linux-gnu
release: 1.16.0-beta.1
LLVM version: 3.9
```

cc @neunenak

**Comment by brson** [comment]
This also affects http2hpack-0.1.3 and lsio-0.1.16 cc @lambdastackio

**Comment by malbarbo** [comment]
This also affects rustup

**Comment by alexcrichton** [comment]
"expected" breakage from https://github.com/rust-lang/rust/pull/38856 I believe

**Comment by brson** [comment]
Also read-process-memory-0.1.0 and renv-0.2.2 cc @luser @cmsd2

**Comment by luser** [comment]
read-process-memory was a trivial fix to a test: https://github.com/luser/read-process-memory/commit/28a887f2de0b42087fea3eaef09c648e3102f685 . Thanks for the heads up!

**Comment by cmsd2** [comment]
fixed https://github.com/cmsd2/renv/commit/23053d2a2027238bfeaa0043935f386a595fe074

**Comment by arielb1** [comment]
This is expected inference breakage - moving to T-libs.

**Comment by luser** [comment]
I published read-process-memory 0.1.1 with the fix.

**Comment by alexcrichton** [comment]
Discussed during libs triage today the conclusion was that this falls under "acceptable API evolution", so we're not going to revert. If any assistance is needed though in updating crates, please let us know!
