### ISSUE TITLE
Regression: overflow evaluating X: MetaSized

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#143830]
See https://crater-reports.s3.amazonaws.com/beta-1.89-4/beta-2025-07-03/gh/red-lightning123.hwc/log.txt:

```

[INFO] [stdout] error[E0275]: overflow evaluating the requirement `ElementArray: MetaSized`
[INFO] [stdout]    --> hwc_lang_cbml/src/tags/src/parse/mod.rs:3:48
[INFO] [stdout]     |
[INFO] [stdout] 3   | pub fn parse_file_tokens(tokens : &[Token]) -> Result<File, String> {
[INFO] [stdout]     |                                                ^^^^^^^^^^^^^^^^^^^^
[INFO] [stdout]     |
[INFO] [stdout] note: required for `Box<ElementArray>` to implement `ParseTokens`
[INFO] [stdout]    --> hwc_lang_cbml/src/tags/src/parse/combinators.rs:5:32
[INFO] [stdout]     |
[INFO] [stdout] 5   | impl<T : ParseTokens + ?Sized> ParseTokens for Box<T> {
[INFO] [stdout]     |      -                         ^^^^^^^^^^^     ^^^^^^
[INFO] [stdout]     |      |
[INFO] [stdout]     |      unsatisfied trait bound introduced here
[INFO] [stdout] note: required because it appears within the type `NestElement`
[INFO] [stdout]    --> hwc_lang_cbml/src/tags/src/parse/nest_element.rs:7:5
[INFO] [stdout]     |
[INFO] [stdout] 7   |     NestElement,
[INFO] [stdout]     |     ^^^^^^^^^^^
[INFO] [stdout] note: required for `combinators::Any<(NestElement, TextElement, EmptyElement)>` to implement `ParseTokens`
[INFO] [stdout]    --> hwc_lang_cbml/src/tags/src/parse/combinators.rs:110:38
[INFO] [stdout]     |
[INFO] [stdout] 110 |           impl<$($T : ParseTokens, )*> ParseTokens for Any<($($T, )*)> {
[INFO] [stdout]     |                                        ^^^^^^^^^^^     ^^^^^^^^^^^^^^^
[INFO] [stdout] ...
[INFO] [stdout] 139 | / impl_any_up_to! {
[INFO] [stdout] 140 | |     [AnyVariants8 AnyVariants7 AnyVariants6 AnyVariants5 AnyVariants4 AnyVariants3 AnyVariants2 AnyVariants1]
[INFO] [stdout] 141 | |     [V8 V7 V6 V5 V4 V3 V2 V1]
[INFO] [stdout] 142 | |     [T8 T7 T6 T5 T4 T3 T2 T1]
[INFO] [stdout]     | |                           -- unsatisfied trait bound introduced here
[INFO] [stdout] 143 | | }
[INFO] [stdout]     | |_- in this macro invocation
[INFO] [stdout] note: required because it appears within the type `element::Element`
[INFO] [stdout]    --> hwc_lang_cbml/src/tags/src/parse/element.rs:7:5
[INFO] [stdout]     |
[INFO] [stdout] 7   |     Element,
[INFO] [stdout]     |     ^^^^^^^
[INFO] [stdout] note: required for `Group<(Optional<Whitespace>, element::Element, Optional<Whitespace>)>` to implement `ParseTokens`
[INFO] [stdout]    --> hwc_lang_cbml/src/tags/src/parse/combinators.rs:47:38
[INFO] [stdout]     |
[INFO] [stdout] 47  |         impl<$($T : ParseTokens, )*> ParseTokens for Group<($($T, )*)> {
[INFO] [stdout]     |                                      ^^^^^^^^^^^     ^^^^^^^^^^^^^^^^^
[INFO] [stdout] ...
[INFO] [stdout] 59  | impl_group_up_to! { T8 T7 T6 T5 T4 T3 T2 T1 }
[INFO] [stdout]     | ---------------------------------------------
[INFO] [stdout]     | |                                     |
[INFO] [stdout]     | |                                     unsatisfied trait bound introduced here
[INFO] [stdout]     | in this macro invocation
[INFO] [stdout] note: required because it appears within the type `file::File`
[INFO] [stdout]    --> hwc_lang_cbml/src/tags/src/parse/file.rs:7:5
[INFO] [stdout]     |
[INFO] [stdout] 7   |     File,
[INFO] [stdout]     |     ^^^^
[INFO] [stdout] note: required by an implicit `Sized` bound in `Result`
[INFO] [stdout]    --> /rustc/b5e10d8c000a153cae6a14d70372dc4b39439a3f/library/core/src/result.rs:548:1
[INFO] [stdout]     = note: this error originates in the macro `impl_any_traits_up_to` which comes from the expansion of the macro `impl_group_up_to` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by theemathas** [comment]
Minimized:

```rust
pub trait Mark {}

impl<T: ?Sized> Mark for *const T {}

pub struct Recursive(pub <Dummy as Trait>::Assoc);
impl Mark for Recursive {}

pub trait Trait {
    type Assoc;
}

pub struct Dummy;
impl Trait for Dummy
where
    *const Recursive: Mark,
{
    type Assoc = *mut Recursive;
}
```

<details>
<summary>Error output on beta:</summary>

```
error[E0275]: overflow evaluating the requirement `Recursive: MetaSized`
  --> src/lib.rs:5:26
   |
5  | pub struct Recursive(pub <Dummy as Trait>::Assoc);
   |                          ^^^^^^^^^^^^^^^^^^^^^^^
   |
note: required for `*const Recursive` to implement `Mark`
  --> src/lib.rs:3:17
   |
3  | impl<T: ?Sized> Mark for *const T {}
   |      -          ^^^^     ^^^^^^^^
   |      |
   |      unsatisfied trait bound introduced here
note: required for `Dummy` to implement `Trait`
  --> src/lib.rs:13:6
   |
13 | impl Trait for Dummy
   |      ^^^^^     ^^^^^
14 | where
15 |     *const Recursive: Mark,
   |                       ---- unsatisfied trait bound introduced here

error[E0275]: overflow evaluating the requirement `*const Recursive: Mark`
  --> src/lib.rs:6:15
   |
6  | impl Mark for Recursive {}
   |               ^^^^^^^^^
   |
note: required for `Dummy` to implement `Trait`
  --> src/lib.rs:13:6
   |
13 | impl Trait for Dummy
   |      ^^^^^     ^^^^^
14 | where
15 |     *const Recursive: Mark,
   |                       ---- unsatisfied trait bound introduced here
note: required because it appears within the type `Recursive`
  --> src/lib.rs:5:12
   |
5  | pub struct Recursive(pub <Dummy as Trait>::Assoc);
   |            ^^^^^^^^^
note: required by a bound in `Mark`
  --> src/lib.rs:1:1
   |
1  | pub trait Mark {}
   | ^^^^^^^^^^^^^^^^^ required by this bound in `Mark`

error[E0275]: overflow evaluating the requirement `Recursive: MetaSized`
  --> src/lib.rs:15:5
   |
15 |     *const Recursive: Mark,
   |     ^^^^^^^^^^^^^^^^^^^^^^
   |
note: required for `*const Recursive` to implement `Mark`
  --> src/lib.rs:3:17
   |
3  | impl<T: ?Sized> Mark for *const T {}
   |      -          ^^^^     ^^^^^^^^
   |      |
   |      unsatisfied trait bound introduced here
   = help: see issue #48214

For more information about this error, try `rustc --explain E0275`.
error: could not compile `tags` (lib) due to 3 previous errors
```

</details>

Presumably caused by #137944, cc @davidtwco

@rustbot labels +T-types +F-sized_hierarchy

**Comment by workingjubilee** [comment]
Should we revert the change to try and buy some time?

**Comment by compiler-errors** [comment]
This was a breaking change called out in https://github.com/rust-lang/rust/pull/137944#issuecomment-2912207485.

**Comment by compiler-errors** [comment]
Though it doesn't really seem like it was resolved: https://github.com/rust-lang/rust/pull/137944#issuecomment-2919170990, and so the breakage was landed without a fix AFAICT.

cc @lcnr @davidtwco

**Comment by apiraino** [comment]
Assigning priority (discussion on [Zulip](https://rust-lang.zulipchat.com/#narrow/channel/245100-t-compiler.2Fprioritization.2Falerts/topic/.23143830.20Regression.3A.20overflow.20evaluating.20X.3A.20MetaSized/near/528450954)).

@rustbot label -I-prioritize +P-critical

**Comment by lcnr** [comment]
cc @rust-lang/types my understanding is that we're explicitly accepting this breakage via an FCP. See https://rust-lang.zulipchat.com/#narrow/channel/326132-t-types.2Fmeetings/topic/2025-06-03.20weekly/near/522151239

Summarizing the situation here:
- `feature(sized_hierarchy)` is an accepted T-lang experiment
- This breakage is due to the fact that previously `?Sized` meant we had no bounds while it now lowers to a `MetaSized` bound.
```rust
pub trait Mark {}

// Removing the `?Sized` bound always errored
impl<T> Mark for *const T {}

pub struct Recursive(pub <Dummy as Trait>::Assoc);
impl Mark for Recursive {}

pub trait Trait {
    type Assoc;
}

pub struct Dummy;
impl Trait for Dummy
where
    *const Recursive: Mark,
{
    type Assoc = *mut Recursive;
}
```
- The error happens as currently cycles are treated as unproductive if they have at least one unproductive step, with some bugs :3 https://github.com/rust-lang/rust/issues/106040 We need to improve cycle handling with the new solver regardless, so there cycles are productive once they have at least one productive step. At this point this breakage no longer applies. See https://rust-lang.zulipchat.com/#narrow/channel/144729-t-types/topic/sized.20hierarchy.20.28.23137944.29/near/517823418 for a further minimization of this issue
- The breakage only affects a single project not on crates.io.

To avoid this breakage, we could either
- ignore `MetaSized` bounds if `feature(sized_hierarchy)` is not enabled, only breaking this pattern once we stabilize this feature or/and
  - given the very limited breakage, this additional complexity was not considered worth it, optionally disabling bounds/changing the way we prove things is easy to get wrong
- block the stabilization of this feature on `-Znext-solver`, completely avoiding the breakage
  - should be otherwise unnecessary

I think it's good to keep this issue open in case other people also encounter this in their private projects, but as is, this breakage is considered acceptable. Though I guess @davidtwco can you take an hour or two to  play with https://github.com/red-lightning123/hwc, checking whether the regression can be worked around.

**Comment by BoxyUwU** [comment]
I was under the impression we accepted this as part of our FCP yeah 👍 

downgraded the prio as we knew this was going to break and was intentional
