### ISSUE TITLE
regression: conflicting implementations of trait `Visitable` for type `Box<_>`

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#127341]
Not entirely clear if this is caused by a new impl in std or trait solver changes.

* https://crater-reports.s3.amazonaws.com/beta-1.80-4/beta-2024-06-22/reg/another-visitor-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.80-4/beta-2024-06-22/reg/derive-visitor-0.3.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.80-4/beta-2024-06-22/reg/gfx-xtra-0.2.0/log.txt

```
[INFO] [stdout] error[E0119]: conflicting implementations of trait `Visitable` for type `Box<_>`
[INFO] [stdout]   --> src/std_impls.rs:49:1
[INFO] [stdout]    |
[INFO] [stdout] 25 | / impl<C: 'static> Visitable for C
[INFO] [stdout] 26 | | where
[INFO] [stdout] 27 | |     for<'a> &'a C: IntoIterator,
[INFO] [stdout] 28 | |     for<'a> <&'a C as IntoIterator>::Item: AsVisitable<'a>,
[INFO] [stdout]    | |___________________________________________________________- first implementation here
[INFO] [stdout] ...
[INFO] [stdout] 49 |   impl<T: Visitable> Visitable for Box<T> {
[INFO] [stdout]    |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `Box<_>`
[INFO] [stdout]    |
[INFO] [stdout]    = note: downstream crates may implement trait `std_impls::AsVisitable<'a>` for type `<&'a std::boxed::Box<_> as std::iter::IntoIterator>::Item`
```

**Comment by compiler-errors** [comment]
Bisected derive-visitor example, since that crate has come up a few times. This bisected to https://github.com/rust-lang/rust/pull/117164#issuecomment-1970903449 cc @lcnr @fmease, though that particular crate didn't get mentioned in the stabilization report.

**Comment by apiraino** [comment]
Labelling also this as P-high for now ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23127339.20regression.3A.20trait.20bound.20is.20not.20satisfied.20Cow.2FBorrow.E2.80.A6)).

@rustbot label -I-prioritize +P-high

**Comment by lcnr** [comment]
all of these look like https://github.com/rust-lang/rust/issues/114061 to me, I consider this to be intended breakage.

**Comment by apiraino** [comment]
removing regression label to avoid having this popup in my searches for regressions

@rustbot label -regression-from-stable-to-beta

**Comment by lcnr** [comment]
I guess we should close this as intended then.
