### ISSUE TITLE
Nested match not being treated as an expression

### ISSUE THREAD

**Issue by Lonami** [rust-lang/rust#101234]
Apologies if this has been reported before. I'm not sure what keywords I could use to find a similar issue. I tried this code:

```rust
fn main() {
    let a = match 1 {
        1 => match 2 {
            2 => true,
            _ => false
        } && true,
        _ => false
    };
}
```

I expected to see this happen: the code compiles, and `a` ends up being `true`.

Instead, this happened: the inner `match` does not seem to be treated as an expression and fails as follows:

```
   Compiling playground v0.0.1 (/playground)
error: unexpected `,` in pattern
 --> src/main.rs:6:18
  |
6 |         } && true,
  |                  ^
  |
help: try adding parentheses to match on a tuple...
  |
6 ~         } (&& true,
7 ~         _) => false
  |
help: ...or a vertical bar to match on multiple alternatives
  |
6 ~         } && true |
7 ~         _ => false
  |

error: could not compile `playground` due to previous error
```

Neither of the suggestions fix the problem. However, writing `true && match 2` instead, or adding parenthesis around the entire inner `match` expression does solve the problem:

```rust
fn main() {
    let a = match 1 {
        1 => (match 2 {
            2 => true,
            _ => false
        }) && true,
        _ => false
    };
}
```

---

The following code also fails:

```rust
fn main() {
    let a = match 1 {
        1 => {
            match 2 {
                2 => true,
                _ => false
            } && true
        },
        _ => false
    };
}
```

But this time with another error (it thinks I meant `&&true` as in `&&bool`):

```
Compiling playground v0.0.1 (/playground)
error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): mismatched types
 --> src/main.rs:4:13
  |
4 | /             match 2 {
5 | |                 2 => true,
6 | |                 _ => false
7 | |             } && true
  | |             ^- help: consider using a semicolon here
  | |_____________|
  |               expected `()`, found `bool`

error[[E0308]](https://doc.rust-lang.org/nightly/error-index.html#E0308): `match` arms have incompatible types
  --> src/main.rs:9:14
   |
2  |       let a = match 1 {
   |  _____________-
3  | |         1 => {
4  | |             match 2 {
5  | |                 2 => true,
6  | |                 _ => false
7  | |             } && true
   | |               ------- this is found to be of type `&&bool`
8  | |         },
9  | |         _ => false
   | |              ^^^^^ expected `&&bool`, found `bool`
10 | |     };
   | |_____- `match` arms have incompatible types

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to 2 previous errors
```

Wrapping the inner `match` in `()` fixes it. Writing `true && match 2` instead also fixes it.

Both of the failing examples also seem to work if the inner `match` is not nested and it's the only `match` in the code.

### Meta

`rustc --version --verbose`:
```
Nightly channel

Build using the Nightly version: 1.65.0-nightly

(2022-08-30 02654a0844f5c8d29bac)
```

**Comment by arctic-penguin** [comment]
`match` probably does not do what you expect it does. https://doc.rust-lang.org/reference/expressions/match-expr.html
> A match expression branches on a pattern. 

You cannot use it like in other languages as an alternative to many `else if`s.

**Comment by ChayimFriedman2** [comment]
This is https://doc.rust-lang.org/stable/reference/statements.html#expression-statements:

An expression that consists of only a [block expression](https://doc.rust-lang.org/stable/reference/expressions/block-expr.html) or control flow expression, if used in a context where a statement is permitted, can omit the trailing semicolon. **This can cause an ambiguity between it being parsed as a standalone statement and as a part of another expression; in this case, it is parsed as a statement**.

**Comment by tczajka** [comment]
In the first code example, is the inner match in a "context where a statement is permitted"? I wouldn't think so, since the [reference](https://doc.rust-lang.org/stable/reference/statements.html#expression-statements) says:

> A statement is a component of a [block](https://doc.rust-lang.org/stable/reference/expressions/block-expr.html)

whereas this inner match expression is not a component of a block.

Hence I would think this shouldn't be ambiguous, it's unambiguously an expression context.
