### ISSUE TITLE
`#[non_exhaustive]` on variant should block cross-crate `as` casts

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#91161]
This currently compiles
```rust
// in crate 1
#[repr(u8)]
enum Foo {
    A,
    #[non_exhaustive]
    B,
}
```
```rust
// in crate 2
fn demo(f: Foo) -> u8 {
    f as u8
}
```

However, that `as` cast [would be an erroneous "non-primitive cast" if the variant ever got any fields](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=937d8b99fb52c90059e15d1cd66a73d0), as it's allowed to do by the `#[non_exhaustive]`.

Thus we need to fix the compiler so that the cast is rejected outside the crate that owns `Foo`.

**Comment by Badel2** [comment]
Across different crates the code does not compile, the `#[non_exhaustive]` attribute seems to mark the enum variant as private:

```
error[E0603]: unit variant `B` is private
 --> src/main.rs:4:19
  |
4 |     let _x = Foo::B as u8;
  |                   ^ private unit variant
  |
note: the unit variant `B` is defined here
 --> /tmp/issue-91161-dep/src/lib.rs:5:5
  |
5 |     B,
  |     ^
```

**Comment by scottmcm** [comment]
Confirmed this is a problem: https://github.com/rust-lang/rust/pull/91281

Nominating for lang to confirm that this should be fixed.  Presumably via a forward-compat error at first.

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/lang meeting, and we agree that this is a bug.

We should fix this if possible. We'll need a crater run to confirm that this won't break things.

**Comment by scottmcm** [comment]
And a clarification from the meeting:

This should error in the *downstream* crate, saying something along the lines of "enums with `#[non_exhaustive]` variants cannot be `as` cast".

I don't know how hard this is; hopefully it should be relatively straight-forward following all the other `non_exhaustive` logic.

**Comment by pazmank** [comment]
I tried the code in the first post and it still compiles with rustc 1.77.2 for thumbv7em-none-eabi target.

**Comment by dtolnay** [comment]
In all compiler versions since 1.65 (containing https://github.com/rust-lang/rust/pull/92744) the code at the top of this issue produces the following diagnostic.

```console
error[E0606]: casting `Foo` as `u8` is invalid
 --> crate2.rs:3:5
  |
3 |     f as u8
  |     ^^^^^^^
  |
  = note: cannot cast an enum with a non-exhaustive variant when it's defined in another crate
```
