### ISSUE TITLE
Passing mod through proc macro disrupts trait importing

### ISSUE THREAD

**Issue by CodeSandwich** [rust-lang/rust#50680]
Tested using rustc 1.27.0-nightly (acd3871ba 2018-05-10).
#### In `lib.rs`
```rust
#![feature(proc_macro)]
extern crate proc_macro;
use proc_macro::TokenStream;
#[proc_macro_attribute]
pub fn nothing(_: TokenStream, token_stream: TokenStream) -> TokenStream {
    token_stream
}
```
#### In `lib.rs`
```rust
#![feature(proc_macro, proc_macro_mod)]
extern crate macros;
use macros::nothing;
trait Trait1 { fn method(&self) {} }
trait Trait2 { fn method(&self) {} }
impl Trait1 for u8 {}
impl Trait2 for u8 {}
//#[nothing]
mod module {
    use super::Trait1;
    fn foo(arg: u8) {
        arg.method()
    }
}
```
### Try to compile
Compilation succeeds. There exist 2 traits, which fit `u8::method`, but only `Trait1` is imported.
### Unomment `#[nothing]` and try to compile
Compilation fails. Rust acts as if `Trait2` was imported too:
```
error[E0034]: multiple applicable items in scope
  --> src/lib.rs:12:13
   |
12 |         arg.method()
   |             ^^^^^^ multiple `method` found
   |
note: candidate #1 is defined in an impl of the trait `Trait1` for the type `u8`
  --> src/lib.rs:4:16
   |
4  | trait Trait1 { fn method(&self) {} }
   |                ^^^^^^^^^^^^^^^^
note: candidate #2 is defined in an impl of the trait `Trait2` for the type `u8`
  --> src/lib.rs:5:16
   |
5  | trait Trait2 { fn method(&self) {} }
   |                ^^^^^^^^^^^^^^^^
```

**Comment by CodeSandwich** [comment]
Not sure when exactly it was fixed, but it works with `rustc 1.29.0-nightly (254f8796b 2018-07-13)` :tada:
