### ISSUE TITLE
Bad diagnostics for GATs in trait paths

### ISSUE THREAD

**Issue by jackh726** [rust-lang/rust#81801]
The diagnostics introduced by https://github.com/rust-lang/rust/pull/77524 are wrong in some cases, e.g. in [gat-trait-path-missing-lifetime](https://github.com/rust-lang/rust/blob/8dfa5836cd7c94f5eb7cc8489d47ae7a3a9995d0/src/test/ui/generic-associated-types/gat-trait-path-missing-lifetime.rs) we get the following stderr:

```
error[E0107]: missing generics for associated type `X::Y`
 --> src/test/ui/generic-associated-types/gat-trait-path-missing-lifetime.rs:5:8
  |
5 |   type Y<'a>;
  |        ^ expected 1 lifetime argument
  |
note: associated type defined here, with 1 lifetime parameter: `'a`
 --> src/test/ui/generic-associated-types/gat-trait-path-missing-lifetime.rs:5:8
  |
5 |   type Y<'a>;
  |        ^ --
help: use angle brackets to add missing lifetime argument
  |
5 |   type Y<'a><'a>;
  |         ^^^^

error: aborting due to previous error; 1 warning emitted
```

_Originally posted by @b-naber in https://github.com/rust-lang/rust/issues/79554#issuecomment-773576589_

**Comment by henryboisdequin** [comment]
The fix to this would be pointing to `fn foo<'a, T1: X<Y = T1>>(t : T1) -> T1::Y<'a>` and emmiting the error there right?

**Comment by b-naber** [comment]
> The fix to this would be pointing to `fn foo<'a, T1: X<Y = T1>>(t : T1) -> T1::Y<'a>` and emmiting the error there right?

Yes.

**Comment by estebank** [comment]
Another case:

> [Given](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e0681b02b38787670516669847a026f8):
> 
> ```rust
> #![feature(generic_associated_types)]
> 
> // The cyclic dependency between trait A and B compiles as expected
> trait A {
>     type BType: B<AType = Self>;
> }
> 
> trait B {
>     type AType: A<BType = Self>;
> }
> 
> // rustc crashes on the generic cyclic dependency between traits C and D
> trait C {
>     type DType<T>: D<T, CType = Self>;
> }
> trait D<T> {
>     type CType: C<DType = Self>;
> }
> ```
> 
> we currently emit
> 
> ```
> error[E0107]: missing generics for associated type `C::DType`
>   --> src/lib.rs:14:10
>    |
> 14 |     type DType<T>: D<T, CType = Self>;
>    |          ^^^^^ expected 1 type argument
>    |
> note: associated type defined here, with 1 type parameter: `T`
>   --> src/lib.rs:14:10
>    |
> 14 |     type DType<T>: D<T, CType = Self>;
>    |          ^^^^^ -
> help: use angle brackets to add missing type argument
>    |
> 14 |     type DType<T><T>: D<T, CType = Self>;
>    |               ^^^
> ```
> 
> where the correct suggestion would be
> 
> ```
> 
> error[E0107]: missing generics for associated type `C::DType`
>   --> src/lib.rs:14:10
>    |
> 17 |     type CType: C<DType = Self>;
>    |                   ^^^^^ expected 1 type argument
>    |
> note: associated type defined here, with 1 type parameter: `T`
>   --> src/lib.rs:14:10
>    |
> 14 |     type DType<T>: D<T, CType = Self>;
>    |          ^^^^^ -
> help: use angle brackets to add missing type argument
>    |
> 17 |     type CType: C<DType<T> = Self>;
>    |                        ^^^
> ```
> 
> CC #81712
