### PR TITLE
When needing type annotations in local bindings, account for impl Trait and closures

### LINKED ISSUE #40014: detect when unconstrained type parameters could be resolved by a closure return type
Building on the changes in https://github.com/rust-lang/rust/pull/39361, it'd be nice to suggest when the user ought to annotate a closure return type, as I think many users are not even aware this is possible. [Example](https://is.gd/QACAwG):

```rust
fn main() {
    let _v = || [];
}
```

I'd like to suggest something like :

```
error[E0101]: cannot determine a type for this expression: unconstrained type
 --> <anon>:2:17
  |
2 |     let _v = || [];
  |              -- ^^ cannot resolve type of expression
                 |
                 consider annotating the return type of this closure like so `|| -> TYPE { [] }`
```

Not sure the best way to phrase that yet. =)

cc @cengizIO -- interested in following up on this? I can help mentor it.

cc @estebank @jonathandturner -- any thoughts on how to phrase the suggestion?

### LINKED ISSUE #46680: Bad error message when using try operator in a closure
Minimal reproduction:

```rust
|| {
    Err(())?;
    Ok(())
}
```

Leads to an error message like:

```
error[E0282]: type annotations needed
 --> src/main.rs:3:9
  |
3 |         Err(())?;
  |         --------
  |         |
  |         cannot infer type for `_`
  |         in this macro invocation

error: aborting due to previous error
```

Because `?` uses `Into` and it's ambiguous which type you're converting this error into. Even as a relatively-veteran Rust programmer it still took me some time and playing around before I worked out what was causing this error, I can't imagine how it must be for a new recruit. I think the ideal solution would be to have it default to `Into<Self>` as long as the error types of all of the expressions `?` is used on match, but that would require an RFC  and at the bare minimum a more explicit error message could be written for this case.

### LINKED ISSUE #63504: When needing type annotation do not suggest using `impl Trait` or closure
_Subset of https://github.com/rust-lang/rust/issues/63502_

When encountering

```
#![feature(async_await)]

use std::io::Error;

fn make_unit() -> Result<(), Error> { 
    Ok(())
}

fn main() {
    let fut = async {
        make_unit()?;
        
        Ok(())
    };
}
```

Do not suggest "consider giving `fut` the explicit type `impl std::future::Future`, with the type parameters specified ", as introduced in https://github.com/rust-lang/rust/pull/61361, when encountering `impl Trait`:

https://github.com/rust-lang/rust/blob/60960a260f7b5c695fd0717311d72ce62dd4eb43/src/librustc/infer/error_reporting/need_type_info.rs#L140-L169

Also, [the case for closures](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c143609bf2c38b7a8bc61a37771d8c32) (CC https://github.com/rust-lang/rust/issues/46680):

```
error[E0282]: type annotations needed for `[closure@src/main.rs:3:13: 6:6]`
 --> src/main.rs:4:9
  |
3 |     let x = || {
  |         - consider giving `x` the explicit type `[closure@src/main.rs:3:13: 6:6]`, with the type parameters specified
4 |         Err(())?;
  |         ^^^^^^^^ cannot infer type
```

### LINKED ISSUE #63506: Suggest `Box::new` on E0308 when appropriate
When encountering a boxed value as expected and a stack allocated value that could be boxed to fulfill the expectation, like in the following snippet, suggest `Box::new` wrapping:

```
fn main() {
    let x: Box<Fn() -> _> = || {
        Err(())?;
        Ok(())
    };
}
```

```
error[E0308]: mismatched types
 --> src/main.rs:3:29
  |
3 |       let x: Box<Fn() -> _> = || {
  |  _____________________________^
4 | |         Err(())?;
5 | |         Ok(())
6 | |     };
  | |_____^ expected struct `std::boxed::Box`, found closure
  |
  = note: expected type `std::boxed::Box<dyn std::ops::Fn() -> _>`
             found type `[closure@src/main.rs:3:29: 6:6]`
```

Should suggest:

```
fn main() {
    let x: Box<Fn() -> _> = Box::new(|| {
        Err(())?;
        Ok(())
    });
}
```

### PR DESCRIPTION
**Pull request by estebank**
Fix https://github.com/rust-lang/rust/issues/46680, fix https://github.com/rust-lang/rust/issues/63504, fix https://github.com/rust-lang/rust/issues/63506, fix #40014, cc https://github.com/rust-lang/rust/issues/63502.

### CODE REVIEW

File: src/librustc_typeck/check/mod.rs [hunk 1]
```diff
@@ -3980,6 +3981,40 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                self.can_coerce(boxed_found, expected),
+                self.sess().source_map().span_to_snippet(expr.span),
+            ) {
+                err.span_suggestion(
+                    expr.span,
+                    "you can store this in the heap calling `Box::new`",
+                    format!("Box::new({})", snippet),
+                    Applicability::MachineApplicable,
+                );
+                err.note("for more information about the distinction between the stack and the \
```
Comment (Centril) [inline src/librustc_typeck/check/mod.rs]:
```suggestion
                err.note("for more on the distinction between the stack and the \
```

**Comment by Centril** [comment]
Thanks! r=me with ^--- addressed :)

File: src/librustc/infer/error_reporting/need_type_info.rs [hunk 2]
```diff
@@ -165,6 +175,26 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+            Some(ty::TyS { sty: ty::Closure(def_id, substs), .. }) => {
+                let msg = " for the closure".to_string();
+                let fn_sig = substs.closure_sig(*def_id, self.tcx);
+                let args = fn_sig.inputs()
+                    .skip_binder()
+                    .iter()
+                    .next()
+                    .map(|args| args.tuple_fields()
+                        .map(|arg| arg.to_string())
+                        .collect::<Vec<_>>().join(", "))
```
[the remark this answers is not in the document]
Comment (estebank) [reply src/librustc/infer/error_reporting/need_type_info.rs]: The extra indentation is _inside_ the `map`'s closure.

[the remark this answers is not in the document]
Comment (Centril) [reply src/librustc/infer/error_reporting/need_type_info.rs]: Oh so it is; the `))` should move the second parenthesis to a newline tho I think (anyways I don't care much since rustfmt will eventually fix it all ^^).

File: src/test/ui/inference/cannot-infer-async-enabled-impl-trait-bindings.stderr [hunk 3]
```diff
@@ -0,0 +1,19 @@
...
+LL | #![feature(impl_trait_in_bindings)]
+   |            ^^^^^^^^^^^^^^^^^^^^^^
+   |
+   = note: `#[warn(incomplete_features)]` on by default
+
+error[E0282]: type annotations needed for `impl std::future::Future`
+  --> $DIR/cannot-infer-async-enabled-impl-trait-bindings.rs:14:9
+   |
+LL |     let fut = async {
+   |         --- consider giving `fut` the explicit type `impl std::future::Future`, with the type parameters specified
```
[the remark this answers is not in the document]
Comment (estebank) [reply src/test/ui/inference/cannot-infer-async-enabled-impl-trait-bindings.stderr]: https://github.com/rust-lang/rust/issues/63526

File: src/librustc/infer/error_reporting/need_type_info.rs [hunk 4]
```diff
@@ -151,12 +151,22 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
         //   |         the type parameter `E` is specified
         // ```
         let (ty_msg, suffix) = match &local_visitor.found_ty {
-            Some(ty) if &ty.to_string() != "_" && name == "_" => {
+            Some(ty) if &ty.to_string() != "_" &&
+                name == "_" &&
+                // FIXME: Remove this check after `impl_trait_in_bindings` is stabilized.
```
[the remark this answers is not in the document]
Comment (estebank) [reply src/librustc/infer/error_reporting/need_type_info.rs]: I believe this is not entirely necessary, given that I added an explicit gate for the feature (which would cause it to be noticed during stabilization), but nonetheless: https://github.com/rust-lang/rust/issues/63527

**Comment by estebank** [comment]
@Centril I have an extra commit that could either go on this PR or a follow up, changing the suggestion for specific cases of closures, recommending setting a return type instead of a boxed closure. Should I include it in this PR and you do an extra round of reviews?

**Comment by Centril** [comment]
@estebank I'm fine with either... ;)

**Comment by estebank** [comment]
@bors r-

@Centril incoming.

File: src/librustc/infer/error_reporting/need_type_info.rs [hunk 5]
```diff
@@ -136,6 +154,35 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
             let expr = self.tcx.hir().expect_expr(body_id.hir_id);
             local_visitor.visit_expr(expr);
         }
+        let err_span = if let Some(pattern) = local_visitor.found_arg_pattern {
```
Comment (estebank) [inline src/librustc/infer/error_reporting/need_type_info.rs]: Everything below here is moving from _compile vec of span labels and then create error_ to _create error as early as possible and operate on `DiagnosticBuilder` directly_.

File: src/librustc/infer/error_reporting/need_type_info.rs [hunk 6]
```diff
@@ -136,6 +154,35 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+            pattern.span
+        } else {
+            span
+        };
+
+        let ty_msg = match local_visitor.found_ty {
```
Comment (estebank) [inline src/librustc/infer/error_reporting/need_type_info.rs]: The slight `match` duplication is to allow us to build the `err` early, and to remove some unnecessary branching.

File: src/librustc/infer/error_reporting/need_type_info.rs [hunk 7]
```diff
@@ -150,34 +197,47 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
+                            "give this closure an explicit return type without `_` placeholders",
+                            suggestion,
+                            Applicability::HasPlaceholders,
+                        );
+                        err.span_label(span, InferCtxt::missing_type_msg(&name));
+                        return err;
+                    }
+                }
+
+                // This shouldn't be reachable, but just in case we leave a reasonable fallback.
```
Comment (estebank) [inline src/librustc/infer/error_reporting/need_type_info.rs]: I'd prefer to leave this in instead of ICEing because I lack the imagination to trigger this case.

File: src/librustc/infer/error_reporting/need_type_info.rs [hunk 8]
```diff
@@ -217,39 +291,36 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
-        );
-
-        for (target_span, label_message) in labels {
-            err.span_label(target_span, label_message);
+        }
+        if !err.span.span_labels().iter().any(|span_label| {
+                span_label.label.is_some() && span_label.span == span
+            }) && local_visitor.found_arg_pattern.is_none()
+        { // Avoid multiple labels pointing at `span`.
+            err.span_label(span, InferCtxt::missing_type_msg(&name));
```
Comment (estebank) [inline src/librustc/infer/error_reporting/need_type_info.rs]: See the diffs below for good examples of what this accomplishes.

File: src/librustc/infer/error_reporting/need_type_info.rs [hunk 9]
```diff
@@ -187,39 +291,36 @@ impl<'a, 'tcx> InferCtxt<'a, 'tcx> {
...
             // ```
-            labels.clear();
-            labels.push((
+            err.span_label(
                 pattern.span,
                 format!("consider giving this closure parameter {}", suffix),
-            ));
+            );
         } else if let Some(pattern) = local_visitor.found_local_pattern {
             if let Some(simple_ident) = pattern.simple_ident() {
```
Comment (Centril) [inline src/librustc/infer/error_reporting/need_type_info.rs]:
```suggestion
            let msg = if let Some(simple_ident) = pattern.simple_ident() {
```
`err.span_label(pattern.span, msg)` is in common for the `if let` + `match` and the `else`.

**Comment by Centril** [comment]
The code makes sense but could use a bit of refactoring so the method isn't too overwhelming to read. I've suggested some ways to fix that ^--- r=me with those addressed.

**Review by Centril — APPROVED** [review]
Thanks! r=me :)
