### ISSUE TITLE
regression 1.50: Duplicate symbol linker error

### ISSUE THREAD

**Issue by rylev** [rust-lang/rust#80951]
In the latest crater run, a crate that compiles on 1.49, did not compile on 1.50 with a linker error you can [see here](https://crater-reports.s3.amazonaws.com/beta-1.50-1/beta-2021-01-01/gh/devrandom.utxo-oracle/log.txt). 

@rustbot modify labels: +regression-from-stable-to-beta

**Comment by nagisa** [comment]
Seems like a not-genuine-regression, its just a case of cargo building and linking two different versions of the same crate (`secp256k1`), which appears to export `no_mangle` symbols if the error message looks right.

**Comment by wesleywiser** [comment]
Discussed in the release triage meeting. The above theory sounds plausible but we want to make sure there's not an actual issue here. 

One possibility @Mark-Simulacrum mentioned is that our rules around `no_mangle` symbols being exported has changed somehow in this release. @petrochenkov do you happen to know if something like that has changed in this release?

**Comment by petrochenkov** [comment]
No, I didn't follow the `no_mangle` changes.

**Comment by apiraino** [comment]
Removing `I-prioritize` label as it looks this is on the radar along with the other crater run issues

**Comment by Mark-Simulacrum** [comment]
I can confirm this is a regression from 1.49. However, I'm having trouble bisecting this - nightlies seem to fail with the linker error for a while back; I ran bisect up to 2020-07-20.

Not sure what to do - maybe worth pinging cleanup group to try to minify at least.

**Comment by steffahn** [comment]
https://github.com/devrandom/utxo-oracle does compile for me with `stable` i.e. `1.49`. If fails with `nightly` with `beta` but also with `1.48` or `1.47`.

**Comment by steffahn** [comment]
So this is not a regression, AFAICT.

With stable `1.49` (e1884a8e3c3e813aada8254edfa120e85bf5ffca) as well as current master (613ef740f3f37702728c6324f948d0abd1e9c82b), the linking error when compiling `utxo-oracle` only appears with a compiler that was built with the `channel = "dev"` or `channel = "beta"` option set (in `config.toml`). Using `channel = "stable"` does _not_ result in a linker error. _(I didn’t actually test `"beta"` on e1884a8e3c3e813aada8254edfa120e85bf5ffca.)_

I also tested current beta (1cd0303963629f317a08e7e52162ccca7232ae7f) and it doesn’t produce the problem with `channel = "stable"`, so it seems likely that `1.50` won’t regress this build.

Finally, as a double check, `1.48` (7eac88abb2e57e752f3302f02be5f3ce3d7adfb4) does produce the linking failure for me even with `channel = "stable"`. I didn’t go further yet in bisecting where the error disappeared between `1.48` and `1.49`.

**Comment by Mark-Simulacrum** [comment]
Interesting. Can we try to figure out what is causing that dependence on the channel?

**Comment by pnkfelix** [comment]
Visiting for P-high review.

There seems to be a lot of indication that this is not a true regression, but the oddities in terms of how the channel name is affecting the results here is worrisome.

Self-assigning for follow-up investigation.

**Comment by pnkfelix** [comment]
Also, review determined this no longer warrants P-high priority, not without stronger signal that this represents an actual regression.

@rustbot label: -P-high +P-medium

**Comment by jackh726** [comment]
No additional info here in about 3 years, closing for no reproduction.
