### ISSUE TITLE
Borrowed temporary dropped on nightly but works on stable

### ISSUE THREAD

**Issue by djc** [rust-lang/rust#148427]
I tried [this code](https://github.com/rust-lang/rustup/blob/fcd02c030edf73f22679c1620923302a171e445c/src/cli/rustup_mode.rs#L1219):

```rust
                writeln!(
                    cfg.process.stdout().lock(),
                    "{} ({})",
                    toolchain.name(),
                    match source {
                        ActiveSource::Default => &"default" as &dyn fmt::Display,
                        _ => &source.to_reason(),
                    }
                )?;
```

This compiles on stable (1.91). However, current nightly fails:

```rust
error[E0716]: temporary value dropped while borrowed
    --> src/cli/rustup_mode.rs:1225:31
     |
1223 | /                     match source {
1224 | |                         ActiveSource::Default => &"default" as &dyn fmt::Display,
1225 | |                         _ => &source.to_reason(),
     | |                               ^^^^^^^^^^^^^^^^^-
     | |                               |                |
     | |                               |                temporary value is freed at the end of this statement
     | |                               creates a temporary value which is freed while still in use
1226 | |                     }
     | |_____________________- borrow later used here
     |
     = note: consider using a `let` binding to create a longer lived value
```

I tried to make a minimal reproduction but [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=df2d754b93a6bbf45588b6df67231e27) fails on stable, too.

### Meta

nightly:
```
rustc 1.93.0-nightly (b15a874aa 2025-11-02)
binary: rustc
commit-hash: b15a874aafe7eab9ea3ac2c1d59c7b03e1425027
commit-date: 2025-11-02
host: aarch64-apple-darwin
release: 1.93.0-nightly
LLVM version: 21.1.3
```

`rustc --version --verbose`:
```
rustc 1.91.0 (f8297e351 2025-10-28)
binary: rustc
commit-hash: f8297e351a40c1439a467bbbb6879088047f50b3
commit-date: 2025-10-28
host: aarch64-apple-darwin
release: 1.91.0
LLVM version: 21.1.2
```
</p>
</details>

**Comment by traviscross** [comment]
Thanks for raising this for lang attention.

In this case, we accepted the breakage to happen directly.  We weren't even expecting there to be an FCW.  My own procedural analysis here is that this consequently does not need further confirmation.

(If someone on lang wants to raise it for reconsideration, of course feel free to do so.)

cc @rust-lang/lang

**Comment by theemathas** [comment]
It seems like there's going to be a [1.91.1 release](https://rust-lang.zulipchat.com/#narrow/channel/241545-t-release/topic/1.2E91.2E1/with/553918718). Is it feasible / reasonable / beneficial  to get a fix to the lint in that release? @dianne
