### ISSUE TITLE
regression: `Sign` is ambiguous

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#135672]
- https://crater-reports.s3.amazonaws.com/beta-1.85-1/beta-2025-01-12/reg/crypt_guard-1.3.7/log.txt

```
[INFO] [stdout] error[E0659]: `Sign` is ambiguous
[INFO] [stdout]    --> src/Core/cipher_aes_gcm_siv.rs:114:24
[INFO] [stdout]     |
[INFO] [stdout] 114 |         let mut hmac = Sign::new(plaintext.to_vec(), passphrase, Operation::Sign, SignType::Sha512);
[INFO] [stdout]     |                        ^^^^ ambiguous name
[INFO] [stdout]     |
[INFO] [stdout]     = note: ambiguous because of multiple glob imports of a name in the same module
```

note: there were some other (knock on?) errors in this crate see logs for more detail

**Comment by theemathas** [comment]
Presumably regressed in #118159, which added `std::fmt::Sign`.

**Comment by theemathas** [comment]
As it turns out, glob imports have been causing unstable items to affect stable code for a long time now. For example, the following code has been failing to compile since version 1.32.0, when `std::ffi::VaList` was added as an unstable type.

```rust
use foo::*;
use std::ffi::*;

mod foo {
    pub struct VaList;
}

fn main() {
    let x: VaList;
}
```

(I have not verified whether this issue with glob imports happens with versions older than 1.32.0.)

**Comment by Noratrieb** [comment]
This is the crate: https://crates.io/crates/crypt_guard

Not that many downloads (but also not none). Looks maintained so they would probably make a fix release when we tell them. Not on the team, but I'd lean towards accepting the breakage, just the usual glob import brittleness.

**Comment by Noratrieb** [comment]
I've notified them in https://github.com/mm9942/crypt_guard/issues/9

**Comment by mm9942** [comment]
Thanks for the infos!
