### ISSUE TITLE
Regression in required trait bounds in Rust 1.78.0 

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#124984]
### Code

[This code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=bd23d1c60cb7914c1a97b6edc7d68e15)

```rust
pub trait Host {}

impl<T: ?Sized + Host> Host for &mut T {}

pub trait GetHost<T>: Send + Sync + Copy + 'static {
    fn get_host<'a>(&self, data: &'a mut T) -> impl Host;
}

impl<T, U, F> GetHost<T> for F
where
    U: Host,
    F: Fn(&mut T) -> &mut U + Send + Sync + Copy + 'static,
{
    fn get_host<'a>(&self, data: &'a mut T) -> impl Host {
        self(data)
    }
}

fn main() {}
```

Compiles successfully with Rust 1.77.0 but fails to compile with Rust 1.78.0:

```
error[E0309]: the parameter type `U` may not live long enough
  --> foo.rs:15:9
   |
14 |     fn get_host<'a>(&self, data: &'a mut T) -> impl Host {
   |                 -- the parameter type `U` must be valid for the lifetime `'a` as defined here...
15 |         self(data)
   |         ^^^^^^^^^^ ...so that the type `U` will meet its required lifetime bounds
   |
help: consider adding an explicit lifetime bound
   |
14 |     fn get_host<'a>(&self, data: &'a mut T) -> impl Host where U: 'a {
   |                                                          +++++++++++

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0309`.
```

### Version it worked on

It most recently worked on: 1.77.0

### Version with regression

`rustc --version --verbose`:
```
rustc 1.78.0 (9b00956e5 2024-04-29)
binary: rustc
commit-hash: 9b00956e56009bab2aa15d7bff10916599e3d6d6
commit-date: 2024-04-29
host: x86_64-unknown-linux-gnu
release: 1.78.0
LLVM version: 18.1.2
```

### Information from cargo bisect-rustc

Regression in https://github.com/rust-lang-ci/rust/commit/68a543d6bf908a65b4a88af8bde140eb564bd88d (https://github.com/rust-lang/rust/pull/118882)

searched nightlies: from nightly-2024-02-01 to nightly-2024-03-16
regressed nightly: nightly-2024-02-15
searched commit range: https://github.com/rust-lang/rust/compare/a84bb95a1f65bfe25038f188763a18e096a86ab2...ee9c7c940c07d8b67c9a6b2ec930db70dcd23a46
regressed commit: https://github.com/rust-lang/rust/commit/7508c3e4c1349e3dd405547bc7dd8d9549e105b6

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 1.77.0 --end 1.78.0 --script rustc --preserve -- foo.rs --crate-type lib
```
</details>

**Comment by lcnr** [comment]
your code snippet does not seem to compile in 1.77 or 1.76? 🤔 https://rust.godbolt.org/z/vzhn87bfz

**Comment by alexcrichton** [comment]
That may be a godbolt issue perhaps? https://rust.godbolt.org/z/e6nxK5oaq shows it passing with 77/76 and locally 1.77.0 compiles the example for me.

**Comment by compiler-errors** [comment]
@alexcrichton: The code you shared in the issue has an extra `+ 'a`.

**Comment by alexcrichton** [comment]
Er apologies, that's my mistake. I was trying various versions locally and got the wires crossed. I've updated the above which also explains why the two godbolt links are differing in results.

I was surprised that this actually worked on 1.77.0, so is this actually a soundness issue fixed by #118882?

**Comment by lcnr** [comment]
The hidden type of `impl Host` ends up as `&'a U` and we currently don't have an implied `U: 'a` bound here. This breaks the invariants of our type system, using a pattern which can result in actual unsoundnesses. I don't think your snippet is unsound as is, but also don't know how we would fix #114936 without breaking your example

**Comment by alexcrichton** [comment]
Ah ok, if this is expected no worries, I just wanted to confirm!

Would you happen to know off the top of your head if there's a way we could somehow get this working? The ideal thing we want is:

```rust
fn foo<T>(f: impl Fn(&mut T) -> impl Host) { ... }
```

and we're trying to hack around it of sorts with a custom `GetHost` trait, but I'm having a tough time figuring out how to model this use case.

**Comment by alexcrichton** [comment]
Ah well in any case this appears to be expected so there's no issue here I believe. We'll work on getting something alternative working instead.

**Comment by lcnr** [comment]
> Would you happen to know off the top of your head if there's a way we could somehow get this working? The ideal thing we want is:

It's really hard as you need a `for<'a> U: 'a` bound which currently forces `U` to be `'static` while ideally it would only allow instantiating `'a` with lifetimes which outlive `'a`. We will support this in a few years as these kinds of bounds are necessary to fix e.g. #25860

but up until then I also don't have a nice fix for this :/

**Comment by alexcrichton** [comment]
Ah no worries! I was able to adapt [this](https://users.rust-lang.org/t/generic-closure-returns-that-can-capture-arguments/76513/3) and get something working, albeit not as egonomically as desired.

In any case thanks for the quick responses here, it's definitely appreciated!
