### PR TITLE
Don't require `Drop` for `[PhantomData<T>; N]` where `N` and `T` are generic, if `T` requires `Drop`

### LINKED ISSUE #115403: rustc refuses to compile const function due to potential drops even when nothing is being dropped
I tried this code:

```rust
use core::marker::PhantomData;
use std::sync::Arc;
struct Foo<T> {
    drop_value: Arc<u32>,
    pd: PhantomData<fn(T)>,
}

impl<T> Foo<T> {
    const fn convert<R>(self) -> Foo<R> {
        let Foo { drop_value, pd: _ } = self;

        Foo {
            drop_value,
            pd: PhantomData,
        }
    }
    
    const fn convert2<R>(self) -> Foo<R> {
        Foo {
            drop_value: self.drop_value,
            pd: PhantomData,
        }
    }
}
```

I expected to see this happen: It compiles

Instead, this happened:

```
Compiling playground v0.0.1 (/playground)
error[[E0493]](https://doc.rust-lang.org/nightly/error_codes/E0493.html): destructor of `Foo<T>` cannot be evaluated at compile-time
  --> src/lib.rs:9:25
   |
9  |     const fn convert<R>(self) -> Foo<R> {
   |                         ^^^^ the destructor for this type cannot be evaluated in constant functions
...
16 |     }
   |     - value is dropped here

For more information about this error, try `rustc --explain E0493`.
error: could not compile `playground` (lib) due to previous error
```

### Meta

This errors on stable 1.72 as well as on nightly-2023-08-30.

This is maybe the same as #109427, but since that is about patterns, and this is not, I thought the independent report is justified.

</p>
</details>

### LINKED ISSUE #115410: regression: destructor of `[MaybeUninit<T>; N]` cannot be evaluated at compile-time
### Code

I tried this code:

```rust
pub const fn f<T, const N: usize>(_: [std::mem::MaybeUninit<T>; N]) {}
```

I expected it to compile successfully. Instead, this happened:

```
error[E0493]: destructor of `[MaybeUninit<T>; N]` cannot be evaluated at compile-time
 --> x.rs:1:35
  |
1 | pub const fn f<T, const N: usize>(_: [std::mem::MaybeUninit<T>; N]) {}
  |                                   ^                                  - value is dropped here
  |                                   |
  |                                   the destructor for this type cannot be evaluated in constant functions
```

### Version it worked on

It most recently worked on 1.72

### Version with regression

Regressed in aafd75a9c510b0e91746b891eb4ebade43899af5 cc @fee1-dead @oli-obk

Originally reported in https://github.com/rust-lang/rust/issues/115403#issuecomment-1701000117 cc @itsxaos

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

### PR DESCRIPTION
**Pull request by oli-obk**
fixes https://github.com/rust-lang/rust/issues/115403
fixes https://github.com/rust-lang/rust/issues/115410

This was accidentally regressed in https://github.com/rust-lang/rust/pull/114134, because it was accidentally stabilized in #102204 (cc @rust-lang/lang, seems like an innocent stabilization, considering this PR is more of a bugfix than a feature).

While we have a whole month to beta backport this change before the regression hits stable, I'd still prefer not to go through an FCP on this PR (which fixes a regression), if T-lang wants an FCP, I can can open an issue about the change itself.

### CODE REVIEW

**Comment by oli-obk** [comment]
cc @fee1-dead

**Comment by fee1-dead** [comment]
cc @lcnr you assigned yourself on my PR

**Comment by lcnr** [comment]
this breaks
```rust
struct NeedsDrop;

impl Drop for NeedsDrop {
    fn drop(&mut self) {
        println!("dropping");
    }
}

struct Foo<const N: usize>([NeedsDrop; N]);

struct Bar(Foo<0>);

const fn should_not_drop(x: Bar) {}

fn main() {
    should_not_drop(Bar(Foo([])));
}
```

File: compiler/rustc_ty_utils/src/needs_drop.rs [hunk 1]
```diff
@@ -19,13 +19,32 @@ fn needs_drop_raw<'tcx>(tcx: TyCtxt<'tcx>, query: ty::ParamEnvAnd<'tcx, Ty<'tcx>
...
+    let res = drop_tys_helper(tcx, query.value, query.param_env, adt_has_dtor, false)
+        .filter(filter_array_elements(tcx, query.param_env))
+        .next()
+        .is_some();
 
     debug!("needs_drop_raw({:?}) = {:?}", query, res);
     res
 }
 
+/// HACK: in order to mistakenly assume that `[PhantomData<T>; N]` requires drop glue
```
Comment (lcnr) [inline compiler/rustc_ty_utils/src/needs_drop.rs:31]: something someething missing negation 😁 

```suggestion
/// HACK: in order to not mistakenly assume that `[PhantomData<T>; N]` requires drop glue
```

**Review by lcnr — COMMENTED** [review]
r=me after adding the test for the above regression

**Comment by Mark-Simulacrum** [comment]
note: this was also picked up in crater (https://crater-reports.s3.amazonaws.com/beta-1.73-1.2/beta-2023-09-10/reg/construe-0.0.3/log.txt), looks like it's already beta-nominated though.

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-09-14/near/390941295)

@rustbot label +beta-accepted
