### PR TITLE
`adt_const_params`: check referred-to types when checking impls of ConstParamTy on refs

### LINKED ISSUE #112124: `adt_const_params` allows impls of `ConstParamTy` with non-ConstParamTy pointees
I tried this code:

```rust
#![feature(adt_const_params)]

use core::marker::ConstParamTy;

struct Foo;

impl ConstParamTy for &'static Foo {}
```

I expected to see this happen: it should error

Instead, this happened: it compilers

### Meta

`playground version`:
```
Nightly channel

Build using the Nightly version: 1.72.0-nightly

(2023-05-29 498553fc04f6a3fdc534)
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by sjwang05**
Previously, we didn't check if referenced-to types of impls of `ConstParamTy` on refs actually implemented `ConstParamTy` in `type_allowed_to_implement_const_param_ty`, leading to code like the following compiling without error (#112124):

```rs
#![feature(adt_const_params)]
#![allow(incomplete_features)]

use std::marker::ConstParamTy;

#[derive(PartialEq, Eq)]
struct Foo;

impl ConstParamTy for &Foo {}

```

This would lead to ICEs when the inner referenced type had fields that were not `ConstParamTy` and were not const-evaluatable (#119299).

This PR modifies `type_allowed_to_implement_const_param_ty` to check if the referred-to type and all of its fields implement `ConstParamTy`. It additionally adds a new variant to the `ConstParamTyImplementationError` enum and a new error in the case the referenced-to type does not implement `ConstParamTy`.

cc @rust-lang/project-const-generics

Fixes #112124

### CODE REVIEW

**Comment by BoxyUwU** [comment]
I swear I remember writing a review that we needed to check this on the original PR :frowning:

**Comment by BoxyUwU** [comment]
Could you also do this:
> Checks should also be added for tuple,array and slice element tys just to be safe imo

**Comment by sjwang05** [comment]
Done. I split the logic into its own closure that gets called in the relevant branches, but otherwise the logic is the same as before. I also tweaked the error message slightly.

@rustbot review

**Comment by BoxyUwU** [comment]
Could you add the following two test cases:
```rust
// check-pass

struct Bar;
struct Foo(Bar);

impl ConstParamTy for Bar
where
  Foo: ConstParamTy {}

// impl checks means that this impl is only valid if `Bar: ConstParamTy` whic
// is only valid if `Foo: ConstParamTy` holds
impl ConstParamTy for Foo {}
```

```rust
// check that we actually take into account region constraints for `ConstParamTy` impl checks

#![feature(adt_const_params)]

use std::marker::ConstParamTy;

struct Foo<'a>(&'a u32);

struct Bar<T>(T);

impl ConstParamTy for Foo<'static> {}
impl<'a> ConstParamTy for Bar<Foo<'a>> {}
// ~^ ERROR: the trait `ConstParamTy` cannot be implemented for this type
```

---

Using an `ObligationCtxt` the way you are is slightly wrong and more complicated than what you're doing right now (see `all_fields_implement_trait` inside the nested loop for an example of what the logic roughly looks like for what you're trying to do).

Could you move the inside of the nested loop in `all_fields_implement_trait` to a new function `fn field_implements_trait` that returns the errors. Name feels a bit funny because we'll want to use it for things that arent strictly fields (i.e. the pointee type of references) but I think it's close enough to fit.

You can then use that function in `type_allowed_to_implement_const_param_ty` instead of setting up the ocx and infcx manually. You wouldn't need the closure once that's done as you can collect a list of tys when matching on the self ty then handle them all at once next to the `all_fields_implement_trait` call by iterating over them and calling `field_implements_trait`.

**Comment by BoxyUwU** [comment]
Thanks for the PR :smiley: that issue has been open so long lol :flushed:

**Comment by sjwang05** [comment]
Thanks for the help! I added the tests and fixed the `ObligationCtxt`-related code as suggested, though I feel like the implementation might be a bit messy due to us having to handle both `FieldDef`s and types--if you have any suggestions on how it could be improved, I'd be glad to make them. I also tweaked the error messages (again) to give slightly better errors on infringing inner tys in tuples.

@rustbot review

File: compiler/rustc_trait_selection/src/traits/misc.rs [hunk 1]
```diff
@@ -89,37 +92,97 @@ pub fn type_allowed_to_implement_const_param_ty<'tcx>(
...
+                    continue;
+                }
+
+                if let &ty::Adt(adt, args) = ty.kind() {
+                    adts_and_args.push((adt, args));
+                    inner_tys.push((ty, adt.did()));
+                } else {
+                    type_allowed_to_implement_const_param_ty(tcx, param_env, ty, parent_cause)?;
+                }
+            }
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/misc.rs:138]:
```suggestion
               inner_tys.push(ty);
```

File: compiler/rustc_trait_selection/src/traits/misc.rs [hunk 2]
```diff
@@ -89,37 +92,97 @@ pub fn type_allowed_to_implement_const_param_ty<'tcx>(
...
+            if !ty.has_concrete_skeleton() {
+                return Ok(());
+            }
+
+            if let &ty::Adt(adt, args) = ty.kind() {
+                adts_and_args.push((adt, args));
+                inner_tys.push((ty, adt.did()));
+            } else {
+                type_allowed_to_implement_const_param_ty(tcx, param_env, ty, parent_cause)?;
+            }
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/misc.rs:122]:
```suggestion
            inner_tys.push(ty);
```

File: compiler/rustc_trait_selection/src/traits/misc.rs [hunk 3]
```diff
@@ -89,37 +92,97 @@ pub fn type_allowed_to_implement_const_param_ty<'tcx>(
...
-        | ty::Char
-        | ty::Str
-        | ty::Array(..)
-        | ty::Slice(_)
-        | ty::Ref(.., hir::Mutability::Not)
-        | ty::Tuple(_) => return Ok(()),
+        ty::Uint(_) | ty::Int(_) | ty::Bool | ty::Char | ty::Str => return Ok(()),
 
-        &ty::Adt(adt, args) => (adt, args),
+        &ty::Adt(adt, args) => adts_and_args.push((adt, args)),
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/misc.rs:144]:
```suggestion
        &ty::Adt(adt, args) => {
            all_fields_implement_trait(
                tcx,
                param_env,
                self_type,
                adt,
                args,
                parent_cause,
                hir::LangItem::ConstParamTy,
            )
            .map_err(ConstParamTyImplementationError::InfrigingFields)?;
        }

```

File: compiler/rustc_trait_selection/src/traits/misc.rs [hunk 4]
```diff
@@ -89,37 +92,97 @@ pub fn type_allowed_to_implement_const_param_ty<'tcx>(
...
+            tcx,
+            param_env,
+            self_type,
+            adt,
+            args,
+            parent_cause,
+            hir::LangItem::ConstParamTy,
+        )
+        .map_err(ConstParamTyImplementationError::InfrigingFields)?;
+    }
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/misc.rs:160]:
```suggestion
```

File: compiler/rustc_trait_selection/src/traits/misc.rs [hunk 5]
```diff
@@ -89,37 +92,97 @@ pub fn type_allowed_to_implement_const_param_ty<'tcx>(
...
 
-    Ok(())
+    let mut infringing = Vec::new();
+    for (ty, def_id) in inner_tys {
+        let span = tcx.def_span(def_id);
```
Comment (BoxyUwU) [inline compiler/rustc_trait_selection/src/traits/misc.rs:164]:
```suggestion
    for ty in inner_tys {
        let span = match ty.kind() {
            TyKind::Adt(def, _) => tcx.def_span(def_id),
            _ => parent_cause.span,
        };
```

**Review by BoxyUwU — COMMENTED** [review]
There shouldn't be any need to call `type_allowed_to_implement_const_param_ty` (or do equivalent logic) recursively, so most of the code in the match arms should be able to be removed. I think the following changes ought to work. For `impl ConstParamTy for MyType` we just check all the fields implement `ConstParamTy` rather than checking all the fields _could_ implement `ConstParamTy` so I think doing the same thing for `[T]/&T/(T,)`  where we require `T: ConstParamTy` rather than `T` potentially being able to implement it, is okay.

**Comment by JohnCSimon** [comment]
@sjwang05 
ping from triage - can you post your status on this PR? This PR has not received an update in a few months.


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

Or if you're not going to continue, please close it. Thank you!

**Comment by BoxyUwU** [comment]
I'm just going to close this, feel free to re-open if you're interested in rebasing and applying the requested changes.
