### ISSUE TITLE
[LLVM HEAD] Build fails due to memory attribute changes

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#103961]
Building the compiler fails at LLVM head due to the changes introduced by https://github.com/llvm/llvm-project/commit/304f1d59ca41872c094def3aee0a8689df6aa398 ("[IR] Switch everything to use memory attribute"):

```
cargo:warning=llvm-wrapper/RustWrapper.cpp:217:12: error: no member named 'InaccessibleMemOnly' in 'llvm::Attribute'; did you mean simply 'InaccessibleMemOnly'?
--
  | cargo:warning=    return Attribute::InaccessibleMemOnly;
  | cargo:warning=           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | cargo:warning=           InaccessibleMemOnly
```

Based on my (limited) understanding the fix will not be entirely trivial, so opening an issue to track.

Found via our experimental rust + llvm at HEAD bot: https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/14694#01844218-71d4-4b0c-85a3-bf643a088de1

cc @nikic

**Comment by TimNN** [comment]
I'll give fixing this a go. @rustbot claim

**Comment by nikic** [comment]
I expect the path of least resistance here would be to export two new functions from our FFI API to create the readonly and inaccessiblememonly attributes. Exposing MemoryEffects to the Rust side is likely not worthwhile at this point.
