### PR TITLE
Fix hang in where-clause suggestion with `predicate_can_apply`

### LINKED ISSUE #104225: Hang with weird trait requirement
Found with a [modified fuzz-rustc](https://github.com/jruderman/fuzz-rustc).

### Code

This input effectively hangs the compiler during `item_types_checking` / trait selection.

```rust
fn f<B>(x: Vec<[[[B; 1]; 1]; 1]>) -> impl PartialEq<B> {
    x
}

fn main() {}
```

### Time complexity

The time spent increases exponentially(?) with the complexity of type `x` _and with the [recursion_limit](https://doc.rust-lang.org/reference/attributes/limits.html#the-recursion_limit-attribute) setting_.

| Setting | Time to reject |
| ------------- | ------------- |
| `#![recursion_limit = "16"]`  | 0.6 sec  |
| `#![recursion_limit = "32"]` | 3.5 sec |
| `#![recursion_limit = "48"]` | 107 sec |
| `#![recursion_limit = "128"]` (default) | Impatience prevailed |

### Regression

Regression in nightly-2022-05-28, from #96046. At the same time, the error message changed from E0275 to E0277.

<details><summary>Error before 2022-05-28</summary>

[E0275: An evaluation of a trait requirement overflowed](https://doc.rust-lang.org/error_codes/E0275.html)

```
error[E0275]: overflow evaluating the requirement `[&&[Vec<&&[&&[_]], _>]]: PartialEq<[_]>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "96"]` attribute to your crate (`main`)
  = note: required because of the requirements on the impl of `PartialEq<&[_]>` for `&[&&[Vec<&&[&&[_]], _>]]`
  = note: 47 redundant requirements hidden
  = note: required because of the requirements on the impl of `PartialEq<Vec<&[&[&[Vec<&[&[&[Vec<&[&[&&[Vec<&[&[&&[Vec<&[&&[&&[Vec<&[&&[&&[Vec<&&[&&[_]], _>]]; _], _>]]], _>]; _]], _>]]], _>; _]]], _>]]], _>>` for `Vec<[[[Vec<&[&[&[Vec<&[&[&[Vec<&[&[&&[Vec<&[&[&&[Vec<&[&&[&&[Vec<&[&&[&&[Vec<&&[&&[_]], _>]]; _], _>]]], _>]; _]], _>]]], _>; _]]], _>]]], _>; 1]; 1]; 1]>`
```

</details>

<details><summary>Current error</summary>

[E0277: trait requirement not satisfied](https://doc.rust-lang.org/nightly/error_codes/E0277.html)

```
error[E0277]: can't compare `Vec<[[[B; 1]; 1]; 1]>` with `B`
 --> input.rs:3:38
  |
3 | fn f<B>(x: Vec<[[[B; 1]; 1]; 1]>) -> impl PartialEq<B> {
  |                                      ^^^^^^^^^^^^^^^^^ no implementation for `Vec<[[[B; 1]; 1]; 1]> == B`
4 |     x
  |     - return type was inferred to be `Vec<[[[B; 1]; 1]; 1]>` here
  |
  = help: the trait `PartialEq<B>` is not implemented for `Vec<[[[B; 1]; 1]; 1]>`
help: consider introducing a `where` clause, but there might be an alternative better way to express this requirement
  |
3 | fn f<B>(x: Vec<[[[B; 1]; 1]; 1]>) -> impl PartialEq<B> where Vec<[[[B; 1]; 1]; 1]>: PartialEq<B> {
  |                                                        +++++++++++++++++++++++++++++++++++++++++
```

</details>

### Version

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (85f4f41de 2022-11-08)
binary: rustc
commit-hash: 85f4f41deb1557ca8ab228319d33003dd2f20f45
commit-date: 2022-11-08
host: x86_64-apple-darwin
release: 1.67.0-nightly
LLVM version: 15.0.4
```

@rustbot label +I-compiletime +I-hang

### PR DESCRIPTION
**Pull request by compiler-errors**
Using `predicate_may_hold` during error reporting causes an evaluation overflow, which (because we use `evaluate_obligation_no_overflow`) then causes the predicate to need to be re-evaluated locally, which results in a hang. 

... but since the "add a where clause" suggestion is best-effort, just throw any overflow errors. No need for 100% accuracy.

r? @lcnr who has been thinking about overflows... Let me know if you want more context about this issue, and as always, feel free to reassign.

Fixes #104225

### CODE REVIEW

**Review by lcnr — COMMENTED** [review]
generally this seems fine, but why does this not result in an infinite hang if we manually try to check `Vec<[[[?0; 1]; 1]; 1]>: PartialEq<?0>` :thinking: something like
```rust
#![recursion_limit = "128"]

fn f<B>(x: (B,)) -> Vec<[[[B; 1]; 1]; 1]> {
    vec![]
}

fn is_eq<T: PartialEq<B>, B>(_: (B,), _: T) {}

fn main() {
    let b = loop {};
    is_eq(b, f(b));
}
```

**Comment by compiler-errors** [comment]
I actually tested something similar while investigating this issue -- I actually don't know why this doesn't hang but instead quickly reports an error when registered as an obligation during typeck'ing. I'll have to investigate.

**Comment by compiler-errors** [comment]
> generally this seems fine, but why does this not result in an infinite hang if we manually try to check `Vec<[[[?0; 1]; 1]; 1]>: PartialEq<?0>`

Oh, @lcnr, this is because of this check that the inference context is tainted. 

https://github.com/rust-lang/rust/blob/6d651a295e0e0c331153288b10b78344a4ede20b/compiler/rustc_trait_selection/src/traits/select/mod.rs#L1098-L1103

If it's *not* tainted, we fatally abort on an overflow, but if it *is* tainted, then we'll keep evaluating a bunch of nonsense predicates leading to the hang.

Notice how this code hangs when the commented line is uncommented (which causes infcx to become tainted):
```rust
fn f() {
    // 1i32.cos();
    foo::<_>();
}

fn foo<B>() where Vec<[[[B; 1]; 1]; 1]>: PartialEq<B> {}

fn main() {}
```

**Comment by lcnr** [comment]
can you still add https://github.com/rust-lang/rust/pull/104269#pullrequestreview-1178902347 as a test? It looks like this hang is something we will have to deal with for non-fatal overflow.

r=me after that

**Comment by matthiaskrgr** [comment]
@bors r- this needs to be reblessed it seems
https://github.com/rust-lang/rust/pull/104671

````
ailures:

---- [ui] src/test/ui/typeck/hang-in-overflow.rs stdout ----
diff of stderr:

8	   = note: required for `...` to implement `...`
9	   = note: 127 redundant requirements hidden
10	   = note: required for `...` to implement `...`
+	   = note: the full type name has been written to '$TEST_BUILD_DIR/typeck/hang-in-overflow/hang-in-overflow.long-type-13273308321832961787.txt'
11	note: required by a bound in `foo`
12	  --> $DIR/hang-in-overflow.rs:14:28
13	   |


The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/typeck/hang-in-overflow/hang-in-overflow.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args typeck/hang-in-overflow.rs`

error: 1 errors occurred comparing output.
status: exit status: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/typeck/hang-in-overflow.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/typeck/hang-in-overflow" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/typeck/hang-in-overflow/auxiliary"
stdout: none
--- stderr -------------------------------
error[E0275]: overflow evaluating the requirement `&&[&&mut [&&[&[&_]]; _]]: PartialEq<&_>`
  --> /checkout/src/test/ui/typeck/hang-in-overflow.rs:8:5
   |
LL |     foo::<_>();
Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
   |     ^^^^^^^^
   |
   = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`hang_in_overflow`)
   = note: required for `[&&[&&mut [&&[&[&_]]; _]]]` to implement `PartialEq<[&_]>`
   = note: 127 redundant requirements hidden
   = note: required for `Vec<[[[&[...; _]; 1]; 1]; 1]>` to implement `PartialEq<&[&mut [&mut [&mut [&&mut [&[&[&[&&[&[&[&[&[&[&[&[&&mut [&[&[[&&[&[&[&mut [&&[&[&[&mut [&&[&[&[&&mut [&&[&[&&mut [&&[&&[&[&&[&&[&&[&[&[&&[&&[&[&&mut [&[&&[&[&&[&&mut [&&[&[&&[&&mut [&&[&[&_]]; _]]]]]]]]; _]]]]]; _]]]]]]]]]]]]; _]]]; _]]]]]]]]; _]]]]]]]; _]]]]]]]]]]]]; _]>`
   = note: the full type name has been written to '/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/typeck/hang-in-overflow/hang-in-overflow.long-type-13273308321832961787.txt'
note: required by a bound in `foo`
  --> /checkout/src/test/ui/typeck/hang-in-overflow.rs:14:28
   |
LL | fn foo<B>()
   |    --- required by a bound in this
LL | where
LL |     Vec<[[[B; 1]; 1]; 1]>: PartialEq<B>,
   |                            ^^^^^^^^^^^^ required by this bound in `foo`
````
