### ISSUE TITLE
[ICE]: None in query system

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#107089]
### Code

```Rust
fn a() -> _ { &a
```

### Affected release channels

- [ ] Previous Stable
- [ ] Current Stable
- [ ] Current Beta
- [X] Current Nightly

### Rust Version

```Shell
rustc 1.68.0-nightly (333ee6c46 2023-01-18)
binary: rustc
commit-hash: 333ee6c466972185973d5097f8b5fb0f9fb13fa5
commit-date: 2023-01-18
host: x86_64-unknown-linux-gnu
release: 1.68.0-nightly
LLVM version: 15.0.6
```

### Current error output

```Shell
error: this file contains an unclosed delimiter
 --> b700324286b0aae9d7752ca9feea39665148a71e.rs:1:18
  |
1 | fn a() -> _ { &a
  |             -    ^
  |             |
  |             unclosed delimiter
```

### Backtrace

```Shell
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/compiler/rustc_query_system/src/query/job.rs:141:44
stack backtrace:
   0:     0x7f3b29f653ca - std::backtrace_rs::backtrace::libunwind::trace::h50542de70121e929
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f3b29f653ca - std::backtrace_rs::backtrace::trace_unsynchronized::hae0fad0188b638fb
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f3b29f653ca - std::sys_common::backtrace::_print_fmt::h0db5adad57c4bf89
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f3b29f653ca - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h00bcafe34ad7431d
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f3b29fc867e - core::fmt::write::hac51cd027be97ada
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/core/src/fmt/mod.rs:1213:17
   5:     0x7f3b29f55a15 - std::io::Write::write_fmt::h3d0d4a9f33ed60b4
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/io/mod.rs:1682:15
   6:     0x7f3b29f65195 - std::sys_common::backtrace::_print::h91a5e2dc0c5534c6
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f3b29f65195 - std::sys_common::backtrace::print::hf5bbf2aee1aca335
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f3b29f67f5f - std::panicking::default_hook::{{closure}}::hb617088b31f5607b
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/panicking.rs:267:22
   9:     0x7f3b29f67c9b - std::panicking::default_hook::h8aabc36d33777a9f
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/panicking.rs:286:9
  10:     0x7f3b2d2482e4 - <rustc_driver[3007fa38fe7f0954]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[830d3b100652ecaa]::ops::function::FnOnce<(&core[830d3b100652ecaa]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f3b29f6879a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h73dc741209159f0b
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/alloc/src/boxed.rs:2002:9
  12:     0x7f3b29f6879a - std::panicking::rust_panic_with_hook::ha64a2ebee15afbaf
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/panicking.rs:692:13
  13:     0x7f3b29f684d2 - std::panicking::begin_panic_handler::{{closure}}::h0e260611a29c4e4b
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/panicking.rs:577:13
  14:     0x7f3b29f6587c - std::sys_common::backtrace::__rust_end_short_backtrace::he6832640d64ae3e0
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x7f3b29f68222 - rust_begin_unwind
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/panicking.rs:575:5
  16:     0x7f3b29fc5023 - core::panicking::panic_fmt::hab8eca7df403fce4
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/core/src/panicking.rs:64:14
  17:     0x7f3b29fc50bd - core::panicking::panic::h563f32e09bf4e452
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/core/src/panicking.rs:114:5
  18:     0x7f3b2ca86c17 - <rustc_query_system[1c311a51d396ff65]::query::job::QueryJobId>::find_cycle_in_stack::<rustc_middle[6fc96dfead90d7a7]::dep_graph::dep_node::DepKind>
  19:     0x7f3b2b5cae16 - rustc_query_system[1c311a51d396ff65]::query::plumbing::try_execute_query::<rustc_query_impl[d3da972c3560dd09]::queries::fn_sig, rustc_query_impl[d3da972c3560dd09]::plumbing::QueryCtxt>
  20:     0x7f3b2b621a13 - <rustc_middle[6fc96dfead90d7a7]::ty::context::TyCtxt>::bound_fn_sig
  21:     0x7f3b2c9c3e47 - <rustc_middle[6fc96dfead90d7a7]::ty::print::pretty::FmtPrinter as rustc_middle[6fc96dfead90d7a7]::ty::print::pretty::PrettyPrinter>::pretty_print_type
  22:     0x7f3b2c9c5738 - <rustc_middle[6fc96dfead90d7a7]::ty::sty::TypeAndMut as rustc_middle[6fc96dfead90d7a7]::ty::print::Print<rustc_middle[6fc96dfead90d7a7]::ty::print::pretty::FmtPrinter>>::print
  23:     0x7f3b2c9c2fa5 - <rustc_middle[6fc96dfead90d7a7]::ty::print::pretty::FmtPrinter as rustc_middle[6fc96dfead90d7a7]::ty::print::pretty::PrettyPrinter>::pretty_print_type
  24:     0x7f3b2d739713 - <rustc_middle[6fc96dfead90d7a7]::ty::TraitPredicate as rustc_middle[6fc96dfead90d7a7]::ty::print::Print<rustc_middle[6fc96dfead90d7a7]::ty::print::pretty::FmtPrinter>>::print
  25:     0x7f3b2d739cec - <rustc_middle[6fc96dfead90d7a7]::ty::PredicateKind as rustc_middle[6fc96dfead90d7a7]::ty::print::Print<rustc_middle[6fc96dfead90d7a7]::ty::print::pretty::FmtPrinter>>::print
  26:     0x7f3b2d805217 - <rustc_middle[6fc96dfead90d7a7]::ty::print::pretty::FmtPrinter as rustc_middle[6fc96dfead90d7a7]::ty::print::pretty::PrettyPrinter>::in_binder::<rustc_middle[6fc96dfead90d7a7]::ty::PredicateKind>
  27:     0x7f3b2d73a4be - <rustc_middle[6fc96dfead90d7a7]::ty::Predicate as core[830d3b100652ecaa]::fmt::Display>::fmt
  28:     0x7f3b29fc867e - core::fmt::write::hac51cd027be97ada
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/core/src/fmt/mod.rs:1213:17
  29:     0x7f3b29fba67f - core::fmt::Write::write_fmt::h2a03445db02f4d6a
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/core/src/fmt/mod.rs:197:9
  30:     0x7f3b29fba67f - alloc::fmt::format::format_inner::h05d4143a38e07d4b
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/alloc/src/fmt.rs:612:9
  31:     0x7f3b2d7a1b35 - rustc_middle[6fc96dfead90d7a7]::query::descs::evaluate_obligation
  32:     0x7f3b2dbf34a4 - rustc_query_impl[d3da972c3560dd09]::plumbing::create_query_frame::<rustc_middle[6fc96dfead90d7a7]::infer::canonical::Canonical<rustc_middle[6fc96dfead90d7a7]::ty::ParamEnvAnd<rustc_middle[6fc96dfead90d7a7]::traits::query::type_op::ProvePredicate>>>
  33:     0x7f3b2dbe4177 - <rustc_query_impl[d3da972c3560dd09]::query_structs::evaluate_obligation::{closure#0}::{closure#0} as core[830d3b100652ecaa]::ops::function::FnOnce<(rustc_query_impl[d3da972c3560dd09]::plumbing::QueryCtxt, rustc_middle[6fc96dfead90d7a7]::infer::canonical::Canonical<rustc_middle[6fc96dfead90d7a7]::ty::ParamEnvAnd<rustc_middle[6fc96dfead90d7a7]::ty::Predicate>>)>>::call_once
  34:     0x7f3b2da8d723 - <rustc_query_system[1c311a51d396ff65]::query::plumbing::QueryState<rustc_middle[6fc96dfead90d7a7]::infer::canonical::Canonical<rustc_middle[6fc96dfead90d7a7]::ty::ParamEnvAnd<rustc_middle[6fc96dfead90d7a7]::ty::Predicate>>, rustc_middle[6fc96dfead90d7a7]::dep_graph::dep_node::DepKind>>::try_collect_active_jobs::<rustc_query_impl[d3da972c3560dd09]::plumbing::QueryCtxt>
  35:     0x7f3b2c9e14d2 - <rustc_query_impl[d3da972c3560dd09]::Queries>::try_collect_active_jobs
  36:     0x7f3b2b5cada9 - rustc_query_system[1c311a51d396ff65]::query::plumbing::try_execute_query::<rustc_query_impl[d3da972c3560dd09]::queries::fn_sig, rustc_query_impl[d3da972c3560dd09]::plumbing::QueryCtxt>
  37:     0x7f3b2bb977e3 - <rustc_middle[6fc96dfead90d7a7]::ty::Ty>::fn_sig
  38:     0x7f3b2b561605 - <rustc_trait_selection[9671f98fbdb91800]::traits::select::SelectionContext>::assemble_candidates
  39:     0x7f3b2bce888f - <rustc_trait_selection[9671f98fbdb91800]::traits::select::SelectionContext>::candidate_from_obligation_no_cache
  40:     0x7f3b2bce7c7f - <rustc_query_system[1c311a51d396ff65]::dep_graph::graph::DepGraph<rustc_middle[6fc96dfead90d7a7]::dep_graph::dep_node::DepKind>>::with_anon_task::<rustc_middle[6fc96dfead90d7a7]::ty::context::TyCtxt, <rustc_trait_selection[9671f98fbdb91800]::traits::select::SelectionContext>::in_task<<rustc_trait_selection[9671f98fbdb91800]::traits::select::SelectionContext>::candidate_from_obligation::{closure#0}::{closure#0}, core[830d3b100652ecaa]::result::Result<core[830d3b100652ecaa]::option::Option<rustc_middle[6fc96dfead90d7a7]::traits::select::SelectionCandidate>, rustc_middle[6fc96dfead90d7a7]::traits::SelectionError>>::{closure#0}, core[830d3b100652ecaa]::result::Result<core[830d3b100652ecaa]::option::Option<rustc_middle[6fc96dfead90d7a7]::traits::select::SelectionCandidate>, rustc_middle[6fc96dfead90d7a7]::traits::SelectionError>>
  41:     0x7f3b2bce1244 - <rustc_trait_selection[9671f98fbdb91800]::traits::select::SelectionContext>::evaluate_stack
  42:     0x7f3b2bbd6d77 - <rustc_trait_selection[9671f98fbdb91800]::traits::select::SelectionContext>::evaluate_predicates_recursively::<alloc[597172b2b0be2ffa]::vec::into_iter::IntoIter<rustc_infer[1a24f95b14ffce22]::traits::Obligation<rustc_middle[6fc96dfead90d7a7]::ty::Predicate>>>
  43:     0x7f3b2bce208d - <rustc_trait_selection[9671f98fbdb91800]::traits::select::SelectionContext>::evaluate_stack
  44:     0x7f3b2bd2b8cc - <rustc_trait_selection[9671f98fbdb91800]::traits::select::SelectionContext>::evaluate_predicate_recursively
  45:     0x7f3b2bd28af1 - rustc_traits[ce9f689be602944c]::evaluate_obligation::evaluate_obligation
  46:     0x7f3b2bd24fdd - rustc_query_system[1c311a51d396ff65]::query::plumbing::get_query::<rustc_query_impl[d3da972c3560dd09]::queries::evaluate_obligation, rustc_query_impl[d3da972c3560dd09]::plumbing::QueryCtxt, rustc_middle[6fc96dfead90d7a7]::dep_graph::dep_node::DepKind>
  47:     0x7f3b2b5d0add - <rustc_infer[1a24f95b14ffce22]::infer::InferCtxt as rustc_trait_selection[9671f98fbdb91800]::traits::query::evaluate_obligation::InferCtxtExt>::evaluate_obligation
  48:     0x7f3b2b5ce7d5 - rustc_hir_analysis[4242f85aba23ed]::collect::infer_return_ty_for_fn_sig
  49:     0x7f3b2b5cba50 - rustc_hir_analysis[4242f85aba23ed]::collect::fn_sig
  50:     0x7f3b2b5ca311 - rustc_query_system[1c311a51d396ff65]::query::plumbing::try_execute_query::<rustc_query_impl[d3da972c3560dd09]::queries::fn_sig, rustc_query_impl[d3da972c3560dd09]::plumbing::QueryCtxt>
  51:     0x7f3b2b5c986f - <rustc_query_impl[d3da972c3560dd09]::Queries as rustc_middle[6fc96dfead90d7a7]::ty::query::QueryEngine>::fn_sig
  52:     0x7f3b2bb3d080 - rustc_hir_analysis[4242f85aba23ed]::collect::convert_item
  53:     0x7f3b2bb3721d - <rustc_middle[6fc96dfead90d7a7]::hir::map::Map>::visit_item_likes_in_module::<rustc_hir_analysis[4242f85aba23ed]::collect::CollectItemTypesVisitor>
  54:     0x7f3b2bb3701c - rustc_hir_analysis[4242f85aba23ed]::collect::collect_mod_item_types
  55:     0x7f3b2c7fbe41 - rustc_query_system[1c311a51d396ff65]::query::plumbing::try_execute_query::<rustc_query_impl[d3da972c3560dd09]::queries::collect_mod_item_types, rustc_query_impl[d3da972c3560dd09]::plumbing::QueryCtxt>
  56:     0x7f3b2cc3b2cd - <rustc_query_impl[d3da972c3560dd09]::Queries as rustc_middle[6fc96dfead90d7a7]::ty::query::QueryEngine>::collect_mod_item_types
  57:     0x7f3b2b87bb15 - <rustc_middle[6fc96dfead90d7a7]::hir::map::Map>::for_each_module::<rustc_hir_analysis[4242f85aba23ed]::check_crate::{closure#0}::{closure#0}::{closure#0}>
  58:     0x7f3b2b87b008 - <rustc_session[d9021b7531949cab]::session::Session>::track_errors::<rustc_hir_analysis[4242f85aba23ed]::check_crate::{closure#0}, ()>
  59:     0x7f3b2b87acff - rustc_hir_analysis[4242f85aba23ed]::check_crate
  60:     0x7f3b2b87aa1b - rustc_interface[a3bd2224478d897e]::passes::analysis
  61:     0x7f3b2c9b57ee - rustc_query_system[1c311a51d396ff65]::query::plumbing::try_execute_query::<rustc_query_impl[d3da972c3560dd09]::queries::analysis, rustc_query_impl[d3da972c3560dd09]::plumbing::QueryCtxt>
  62:     0x7f3b2cc37c1a - <rustc_query_impl[d3da972c3560dd09]::Queries as rustc_middle[6fc96dfead90d7a7]::ty::query::QueryEngine>::analysis
  63:     0x7f3b2c4d6a53 - <rustc_interface[a3bd2224478d897e]::passes::QueryContext>::enter::<rustc_driver[3007fa38fe7f0954]::run_compiler::{closure#1}::{closure#2}::{closure#2}, core[830d3b100652ecaa]::result::Result<(), rustc_errors[24ae80d350ed6ef3]::ErrorGuaranteed>>
  64:     0x7f3b2c4d54a8 - <rustc_interface[a3bd2224478d897e]::interface::Compiler>::enter::<rustc_driver[3007fa38fe7f0954]::run_compiler::{closure#1}::{closure#2}, core[830d3b100652ecaa]::result::Result<core[830d3b100652ecaa]::option::Option<rustc_interface[a3bd2224478d897e]::queries::Linker>, rustc_errors[24ae80d350ed6ef3]::ErrorGuaranteed>>
  65:     0x7f3b2c4d3328 - rustc_span[8b627345fe9560b3]::with_source_map::<core[830d3b100652ecaa]::result::Result<(), rustc_errors[24ae80d350ed6ef3]::ErrorGuaranteed>, rustc_interface[a3bd2224478d897e]::interface::run_compiler<core[830d3b100652ecaa]::result::Result<(), rustc_errors[24ae80d350ed6ef3]::ErrorGuaranteed>, rustc_driver[3007fa38fe7f0954]::run_compiler::{closure#1}>::{closure#0}::{closure#0}>
  66:     0x7f3b2c4d2e01 - <scoped_tls[919fbd9b743d1ab7]::ScopedKey<rustc_span[8b627345fe9560b3]::SessionGlobals>>::set::<rustc_interface[a3bd2224478d897e]::interface::run_compiler<core[830d3b100652ecaa]::result::Result<(), rustc_errors[24ae80d350ed6ef3]::ErrorGuaranteed>, rustc_driver[3007fa38fe7f0954]::run_compiler::{closure#1}>::{closure#0}, core[830d3b100652ecaa]::result::Result<(), rustc_errors[24ae80d350ed6ef3]::ErrorGuaranteed>>
  67:     0x7f3b2c4d23e2 - std[d57f0b25e837618f]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[a3bd2224478d897e]::util::run_in_thread_pool_with_globals<rustc_interface[a3bd2224478d897e]::interface::run_compiler<core[830d3b100652ecaa]::result::Result<(), rustc_errors[24ae80d350ed6ef3]::ErrorGuaranteed>, rustc_driver[3007fa38fe7f0954]::run_compiler::{closure#1}>::{closure#0}, core[830d3b100652ecaa]::result::Result<(), rustc_errors[24ae80d350ed6ef3]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[830d3b100652ecaa]::result::Result<(), rustc_errors[24ae80d350ed6ef3]::ErrorGuaranteed>>
  68:     0x7f3b2c4d218c - <<std[d57f0b25e837618f]::thread::Builder>::spawn_unchecked_<rustc_interface[a3bd2224478d897e]::util::run_in_thread_pool_with_globals<rustc_interface[a3bd2224478d897e]::interface::run_compiler<core[830d3b100652ecaa]::result::Result<(), rustc_errors[24ae80d350ed6ef3]::ErrorGuaranteed>, rustc_driver[3007fa38fe7f0954]::run_compiler::{closure#1}>::{closure#0}, core[830d3b100652ecaa]::result::Result<(), rustc_errors[24ae80d350ed6ef3]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[830d3b100652ecaa]::result::Result<(), rustc_errors[24ae80d350ed6ef3]::ErrorGuaranteed>>::{closure#1} as core[830d3b100652ecaa]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  69:     0x7f3b29f72bd3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7ba1652ef014411c
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/alloc/src/boxed.rs:1988:9
  70:     0x7f3b29f72bd3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb86249b0355c08e6
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/alloc/src/boxed.rs:1988:9
  71:     0x7f3b29f72bd3 - std::sys::unix::thread::Thread::new::thread_start::h7258c93114561772
                               at /rustc/333ee6c466972185973d5097f8b5fb0f9fb13fa5/library/std/src/sys/unix/thread.rs:108:17
  72:     0x7f3b29d048fd - <unknown>
  73:     0x7f3b29d86a60 - <unknown>
  74:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.68.0-nightly (333ee6c46 2023-01-18) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to previous error
```

### Anything else?

Only crashes on nightly and not beta or stable for some reason :thinking:

**Comment by lukas-code** [comment]
regressed in https://github.com/rust-lang/rust/pull/106200

<details>
<summary>bisector output</summary>

searched nightlies: from nightly-2023-01-04 to nightly-2023-01-19
regressed nightly: nightly-2023-01-05
searched commit range: https://github.com/rust-lang/rust/compare/c7572670a1302f5c7e245d069200e22da9df0316...659e169d37990b9c730a59a96081f2ef7afbe8f1
regressed commit: https://github.com/rust-lang/rust/commit/5c18bc6137256693e604a701b7d1bf10e93aaa2d

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --regress=ice 
```
</details>
</details>

**Comment by chenyukang** [comment]
Intresting, this is caused by cycle in function signature, 
modify to below code will also get the error.
```rust
fn a() -> _ { &a }
```

and we have delayed errors like this:

```console
error: internal compiler error[E0391]: cycle detected when computing function signature of `a`
 --> ./p/c.rs:1:1
  |
1 | fn a() -> _ { &a }
  | ^^^^^^^^^^^
  |
note: ...which requires type-checking `a`...
 --> ./p/c.rs:1:1
  |
1 | fn a() -> _ { &a }
  | ^^^^^^^^^^^
  = note: ...which again requires computing function signature of `a`, completing the cycle
note: cycle used when collecting item types in top-level module
 --> ./p/c.rs:1:1
  |
1 | / fn a() -> _ { &a }
2 | | fn main() { }
  | |_____________^
  = note: delayed at    0: <rustc_errors::HandlerInner>::emit_diagnostic
```

@compiler-errors 
this line of code gets into the query system:
https://github.com/compiler-errors/rust/blob/89086f7d36e3a692b48cae8a408057734f044567/compiler/rustc_hir_analysis/src/collect.rs#L1329
