### PR TITLE
Improve hygiene of `alloc::format!`

### LINKED ISSUE #63687: gfx_device_gl 0.16.1 broken on latest nightly
Caused by #63613. To be precise the https://github.com/rust-lang/rust/pull/63613/files#diff-c915449964a130718bd732c4f035b2cfR101 change.

It basically does:

```rust
extern crate gfx_core as core;
format!(...);
```

Because `format!` uses `::core::format_args` to refer to `format_args!`, it will try to resolve it in `gfx_core`, which doen't contain `format_args!`.

```
   Compiling gfx_device_gl v0.16.1
error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> /Users/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.16.1/src/shade.rs:434:24
    |
434 |                 name = format!("Target{}", index);
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0433]: failed to resolve: could not find `format_args` in `core`
   --> /Users/bjorn/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.16.1/src/shade.rs:487:30
    |
487 |             let color_name = format!("Target{}\0", i);
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^ could not find `format_args` in `core`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
```

### PR DESCRIPTION
**Pull request by petrochenkov**
`format` now uses `format_args` though a `__export` module, as described in https://github.com/rust-lang/rust/issues/63687#issuecomment-526254208.

Fixes https://github.com/rust-lang/rust/issues/63687

### CODE REVIEW

**Review by dtolnay — APPROVED** [review]

**Comment by dtolnay** [comment]
@bors r+

But I would like to see the hygienic suggestion from https://github.com/rust-lang/rust/issues/63687#issuecomment-526254208 implemented. That approach of `$crate::__export::...` is common practice in the library ecosystem.

**Comment by petrochenkov** [comment]
@bors r-
(I'll change the PR to use `__export`.)

**Comment by JohnCSimon** [comment]
Ping from triage - 
@petrochenkov - What is the status of this PR? 
Thank you.

**Comment by petrochenkov** [comment]
Will update in a couple of days.

**Comment by petrochenkov** [comment]
Updated.

**Comment by lzutao** [comment]
Should we change the PR title too?
