### ISSUE TITLE
Cannot compile with GCC 6.2.0

### ISSUE THREAD

**Issue by nathansizemore** [rust-lang/rust#38009]
```
$ make
cfg: version 1.13.0-dev (2c6933acc 2016-11-07)
cfg: build triple x86_64-unknown-linux-gnu
cfg: host triples x86_64-unknown-linux-gnu
cfg: target triples x86_64-unknown-linux-gnu
cfg: host for x86_64-unknown-linux-gnu is x86_64
cfg: os for x86_64-unknown-linux-gnu is unknown-linux-gnu
cfg: have good valgrind for x86_64-unknown-linux-gnu
cfg: using CC=gcc (CFG_CC)
cfg: disabling valgrind run-pass tests
cmake: llvm
make[1]: Entering directory '/home/nathan/development/build/x86_64-unknown-linux-gnu/llvm'
make[2]: Entering directory '/home/nathan/development/build/x86_64-unknown-linux-gnu/llvm'
make[3]: Entering directory '/home/nathan/development/build/x86_64-unknown-linux-gnu/llvm'
make[3]: Leaving directory '/home/nathan/development/build/x86_64-unknown-linux-gnu/llvm'
make[3]: Entering directory '/home/nathan/development/build/x86_64-unknown-linux-gnu/llvm'
[  0%] Building CXX object lib/Support/CMakeFiles/LLVMSupport.dir/CrashRecoveryContext.cpp.o
In file included from /home/nathan/development/rust/src/llvm/include/llvm/Support/Mutex.h:18:0,
                 from /home/nathan/development/rust/src/llvm/lib/Support/CrashRecoveryContext.cpp:14:
/home/nathan/development/rust/src/llvm/include/llvm/Support/Threading.h:61:16: error: ‘once_flag’ in namespace ‘std’ does not name a type
   typedef std::once_flag once_flag;
                ^~~~~~~~~
/home/nathan/development/rust/src/llvm/include/llvm/Support/Threading.h:91:18: error: variable or field ‘call_once’ declared void
   void call_once(once_flag &flag, Function &&F, Args &&... ArgList) {
                  ^~~~~~~~~
/home/nathan/development/rust/src/llvm/include/llvm/Support/Threading.h:91:18: error: ‘once_flag’ was not declared in this scope
/home/nathan/development/rust/src/llvm/include/llvm/Support/Threading.h:91:29: error: ‘flag’ was not declared in this scope
   void call_once(once_flag &flag, Function &&F, Args &&... ArgList) {
                             ^~~~
/home/nathan/development/rust/src/llvm/include/llvm/Support/Threading.h:91:44: error: expected primary-expression before ‘&&’ token
   void call_once(once_flag &flag, Function &&F, Args &&... ArgList) {
                                            ^~
/home/nathan/development/rust/src/llvm/include/llvm/Support/Threading.h:91:46: error: ‘F’ was not declared in this scope
   void call_once(once_flag &flag, Function &&F, Args &&... ArgList) {
                                              ^
/home/nathan/development/rust/src/llvm/include/llvm/Support/Threading.h:91:54: error: expected primary-expression before ‘&&’ token
   void call_once(once_flag &flag, Function &&F, Args &&... ArgList) {
```

**Comment by Mark-Simulacrum** [comment]
I feel like I saw an issue about this and closed it earlier, since this is really not our fault; if we want to track LLVM compatibility with various gcc versions we should open a single bug to track them.
