### ISSUE TITLE
enum variant values must be cast to their own type

### ISSUE THREAD

**Issue by metajack** [rust-lang/rust#13902]
The following program does not compile:

```
#![allow(non_camel_case_types)]

static JSVAL_TAG_CLEAR: u32 = 0xFFFFFF80;
static JSVAL_TYPE_INT32: u8 = 0x01;
static JSVAL_TYPE_UNDEFINED: u8 = 0x02;
#[repr(u32)]
enum ValueTag {
    JSVAL_TAG_INT32 = JSVAL_TAG_CLEAR | (JSVAL_TYPE_INT32 as u32),
    JSVAL_TAG_UNDEFINED = JSVAL_TAG_CLEAR | (JSVAL_TYPE_UNDEFINED as u32),
}

fn main() {
    let _ = JSVAL_TAG_INT32;
}
```

If you add `as u32` after `JSVAL_TAG_CLEAR` then it compiles fine. I assume this is interacting with `repr` such that it doesn't know the real type.

**Comment by frewsxcv** [comment]
*visiting for triage*

I updated your code so that it compiles with the latest Rust (enum namespacing):

```rust
static JSVAL_TAG_CLEAR: u32 = 0xFFFFFF80;
static JSVAL_TYPE_INT32: u8 = 0x01;
static JSVAL_TYPE_UNDEFINED: u8 = 0x02;
#[repr(u32)]
enum ValueTag {
    JSVAL_TAG_INT32 = JSVAL_TAG_CLEAR | (JSVAL_TYPE_INT32 as u32),
    JSVAL_TAG_UNDEFINED = JSVAL_TAG_CLEAR | (JSVAL_TYPE_UNDEFINED as u32),
}

fn main() {
    let _ = ValueTag::JSVAL_TAG_INT32;
}
```

Even with `as u32` after `JSVAL_TAG_CLEAR`, it is not insistent upon using constants for enum values:

```rust
/t/triage $ rustc foo.rs
foo.rs:6:23: 6:74 error: expected constant: bad operands for binary [E0080]
foo.rs:6     JSVAL_TAG_INT32 = JSVAL_TAG_CLEAR as u32 | (JSVAL_TYPE_INT32 as u32),
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
foo.rs:7:27: 7:82 error: expected constant: bad operands for binary [E0080]
foo.rs:7     JSVAL_TAG_UNDEFINED = JSVAL_TAG_CLEAR as u32 | (JSVAL_TYPE_UNDEFINED as u32),
                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
```

**Comment by arielb1** [comment]
This does work in 1.0

**Comment by frewsxcv** [comment]
@arielb1 This doesn't work for me in 1.0

http://is.gd/CFYTay

**Comment by frewsxcv** [comment]
@arielb1 What codeblock did you test this with?

**Comment by arielb1** [comment]
You need to use `const` instead of `static` of course.

**Comment by frewsxcv** [comment]
Regression test added in #26670
