### PR TITLE
Avoid use imports in `thread_local_inner!`

### LINKED ISSUE #131863: Hygiene issues with use declarations in `thread_local!` implementation
```rust
use std::cell::RefCell;

struct Dom;

type Storage<T> = RefCell<Option<T>>;

thread_local! {
    static CURRENT_DOM: Storage<Dom> = const { RefCell::new(None) };
}
```

The above code worked in 1.80.1 but fails to compile with 1.81.0 on platforms without `cfg(target_thread_local)`. In my case this was `aarch64-linux-android`.

The issue seems to be that the macro expansion contains a use declaration that pulls in another type called `Storage` into the scope:
https://github.com/rust-lang/rust/blob/3ed6e3cc69857129c1d314daec00119ff47986ed/library/std/src/sys/thread_local/os.rs#L24-L25
This changed recently in https://github.com/rust-lang/rust/pull/126953.

A similar change was made to the implementation for platforms with `cfg(target_thread_local)` in https://github.com/rust-lang/rust/pull/125525:
https://github.com/rust-lang/rust/blob/3ed6e3cc69857129c1d314daec00119ff47986ed/library/std/src/sys/thread_local/native/mod.rs#L57-L59
Replacing `Storage` with `EagerStorage` in the example produces a similar regression for 1.79.0 -> 1.80.0.

The example is from [`yakui`](https://github.com/SecondHalfGames/yakui/blob/8e76915c46aa673a5bc9700193171156c24783ae/crates/yakui-core/src/context.rs#L6-L12).

### Version it worked on

It most recently worked on: 1.80.1

### Version with regression

`rustc --version --verbose`:
```
rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: x86_64-pc-windows-msvc
release: 1.81.0
LLVM version: 18.1.7
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
error[E0658]: use of unstable library feature 'thread_local_internals': internal details of the thread_local macro
 --> src\lib.rs:8:25
  |
8 |     static CURRENT_DOM: Storage<Dom> = const { RefCell::new(None) };
  |                         ^^^^^^^^^^^^

error[E0271]: expected `__init` to be a fn item that returns `Storage<Dom>`, but it returns `RefCell<Option<Dom>>`
 --> src\lib.rs:7:1
  |
7 | / thread_local! {
8 | |     static CURRENT_DOM: Storage<Dom> = const { RefCell::new(None) };
9 | | }
  | | ^
  | | |
  | |_expected `Storage<Dom>`, found `RefCell<Option<Dom>>`
  |   required by a bound introduced by this call
  |
  = note: expected struct `std::thread::local_impl::Storage<Dom>`
             found struct `RefCell<Option<Dom>>`
note: required by a bound in `std::thread::local_impl::Storage::<T>::get`
 --> /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/thread_local/os.rs:69:5
  = note: this error originates in the macro `$crate::thread::local_impl::thread_local_inner` which comes from the expansion of the macro `thread_local` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
 --> src\lib.rs:7:1
  |
7 | / thread_local! {
8 | |     static CURRENT_DOM: Storage<Dom> = const { RefCell::new(None) };
9 | | }
  | | ^
  | | |
  | |_expected `Option<&mut Option<Storage<Dom>>>`, found `Option<&mut Option<RefCell<...>>>`
  |   arguments to this method are incorrect
  |
  = note: expected enum `Option<&mut Option<std::thread::local_impl::Storage<Dom>>>`
             found enum `Option<&mut Option<RefCell<Option<Dom>>>>`
note: method defined here
 --> /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/thread_local/os.rs:69:12
  = note: this error originates in the macro `$crate::thread::local_impl::thread_local_inner` which comes from the expansion of the macro `thread_local` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
 --> src\lib.rs:7:1
  |
7 | / thread_local! {
8 | |     static CURRENT_DOM: Storage<Dom> = const { RefCell::new(None) };
9 | | }
  | |_^ expected `*const RefCell<Option<Dom>>`, found `*const Storage<Dom>`
  |
  = note: expected raw pointer `*const RefCell<Option<Dom>>`
             found raw pointer `*const std::thread::local_impl::Storage<Dom>`
  = note: this error originates in the macro `$crate::thread::local_impl::thread_local_inner` which comes from the expansion of the macro `thread_local` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0271, E0308, E0658.
For more information about an error, try `rustc --explain E0271`.
error: could not compile `minimal` (lib) due to 4 previous errors
```

</p>
</details>

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

### PR DESCRIPTION
**Pull request by jieyouxu**
Previously, the use imports in `thread_local_inner!` can shadow user-provided types or type aliases of the names `Storage`, `EagerStorage`, `LocalStorage` and `LocalKey`. This PR fixes that by dropping the use imports and instead refer to the std-internal types via fully qualified paths. A basic test is added to ensure `thread_local!`s with static decls with type names that match the aforementioned std-internal type names can successfully compile.

Fixes #131863.

### CODE REVIEW

**Comment by Noratrieb** [comment]
@rustbot label beta-nominated 
https://github.com/rust-lang/rust/issues/131863#issuecomment-2421186397

**Comment by ChrisDenton** [comment]
Should this be stable nominated too? Maybe it's not worth a point release on its own but if one does happen for some other reason then it might be good to include this?

**Comment by lqd** [comment]
[A comment](https://github.com/rust-lang/rust/issues/131863#issuecomment-2421186397) on the issue says the following about stable nomination:

> I think it's uncommon enough that a backport to stable isn't necessary, though that's up to the team.

**Comment by Noratrieb** [comment]
Given that no one complained during the entire 1.81 cycle, this doesn't seem very urgent. Beta should be enough imo
