### ISSUE TITLE
Rustc should hint at accidental member access instead of associated function call on local variables

### ISSUE THREAD

**Issue by RDambrosio016** [rust-lang/rust#83987]
I tried this code:

```rust
struct Foo;

impl Foo {
    pub fn bar() {}
}

fn main() {
    let baz = Foo {};
    baz::bar();
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=69cea2de96d73a7c2c8f4ca0af0cf702

I expected to see this happen: 
```
error: use of undeclared crate or module `baz`

...

did you mean to call the function `bar` on `baz`?

baz.bar();
   ^
```

Instead, this happened:
```
error[E0433]: failed to resolve: use of undeclared crate or module `baz`
 --> src/main.rs:9:5
  |
9 |     baz::bar();
  |     ^^^ use of undeclared crate or module `baz`
```
No hint that maybe they meant to call bar as an associated function.

### Meta

`rustc --version --verbose`: Playground 1.51 stable, doesnt work on nightly 1.53 either
