### ISSUE TITLE
Inference regression in nightly affecting `Pin::set` and futures

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rust#56237]
`futures-util-preview` does not build on the current nightly because the compiler is unable to infer that a type is `Sized`. This is a regression in the latest nightly.

The line that errors is [here](https://github.com/rust-lang-nursery/futures-rs/blob/b7769180b091f22da12d35ea808779ddfa17b7e3/futures-util/src/future/maybe_done.rs#L110).

Error message:

```
error[E0277]: the size for values of type `<&mut future::maybe_done::MaybeDone<Fut> as std::ops::Deref>::Target` cannot be known at compilation time
   --> futures-util/src/future/maybe_done.rs:110:9
    |
110 |         Pin::set(self, MaybeDone::Done(res));
    |         ^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `<&mut future::maybe_done::MaybeDone<Fut> as std::ops::Deref>::Target`
```

Relevant commits: https://github.com/rust-lang/rust/compare/edaac35d6...6acbb5b65

cc rust-lang-nursery/futures-rs#1350

**Comment by hcpl** [comment]
Minimized example without `Pin` and external dependencies:

```rust
use std::ops::{Deref, DerefMut};

fn foo<P>(_value: <P as Deref>::Target)
where
    P: DerefMut,
    <P as Deref>::Target: Sized,
{}

fn main() {
    foo::<&mut u32>(2);
}
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=70fca173716025c40c20e05fbb5809e8).

**Comment by oli-obk** [comment]
Possibly caused by https://github.com/rust-lang/rust/pull/56045

cc @qnighy

**Comment by cramertj** [comment]
Enabling the `unsized_locals` feature fixes this, so this is being caused by the gate [here](https://github.com/rust-lang/rust/pull/56045/files#diff-1d1b0d29a2e8da97c6bfb6e364d920c7R3961).

**Comment by qnighy** [comment]
Perhaps do I need some normalization before doing deferred `Sized`ness checking?

**Comment by pnkfelix** [comment]
triage. This is now a stable-to-beta regression. P-high.

**Comment by pnkfelix** [comment]
assigning to @nikomatsakis to either r+ PR #56282, come up with a new fix, or delegate those options to someone else.
