### ISSUE TITLE
Travis is failing ("undefined reference to LLVMInitializeSystemZ*")

### ISSUE THREAD

**Issue by TimNN** [rust-lang/rust#36077]
Excerpt from a recent travis build:

```
  = note: /build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-836a4172.so: undefined reference to `LLVMInitializeSystemZTargetInfo'
/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-836a4172.so: undefined reference to `LLVMInitializeSystemZTargetMC'
/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-836a4172.so: undefined reference to `LLVMInitializeSystemZAsmParser'
/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-836a4172.so: undefined reference to `LLVMInitializeSystemZTarget'
/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-836a4172.so: undefined reference to `LLVMInitializeSystemZAsmPrinter'
collect2: error: ld returned 1 exit status
```

These symbols were introduced in #36028.

cc @japaric
