### ISSUE TITLE
Regression on nightly when compiling mio for wasm32-wasi

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#99502]
Steps to reproduce:

```
$ rustup toolchain install 1.62.1 --target wasm32-wasi
$ rustup toolchain install nightly-2022-07-19 --target wasm32-wasi
$ git clone https://github.com/tokio-rs/mio.git
$ cd mio
$ git checkout v0.8.4
$ cargo +1.62.1 build --target wasm32-wasi --all-features
   Compiling libc v0.2.126
   Compiling log v0.4.17
   Compiling cfg-if v1.0.0
   Compiling wasi v0.11.0+wasi-snapshot-preview1
   Compiling mio v0.8.4 (/home/ben/code/mio)
    Finished dev [unoptimized + debuginfo] target(s) in 0.66s
$ cargo +nightly-2022-07-19 build --target wasm32-wasi --all-features
   Compiling log v0.4.17
   Compiling libc v0.2.126
   Compiling cfg-if v1.0.0
   Compiling wasi v0.11.0+wasi-snapshot-preview1
   Compiling mio v0.8.4 (/home/ben/code/mio)
error[E0658]: use of unstable library feature 'wasi_ext'
 --> src/io_source.rs:5:5
  |
5 | use std::os::wasi::io::AsRawFd;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #71213 <https://github.com/rust-lang/rust/issues/71213> for more information
  = help: add `#![feature(wasi_ext)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `mio` due to previous error
```

It's possible that this was accidentally stabilized, then feature gated later.

**Comment by ehuss** [comment]
This seems to be caused by #95956.

I was thinking #99292 might address this, but I tried that PR and it doesn't seem to work.  Maybe @Aaron1011 can confirm.

cc @yaahc

**Comment by yaahc** [comment]
Looks like another case of https://github.com/rust-lang/rust/pull/99288, `AsRawFd` is stable but the `std::os::wasi::io` module it lives in is not: https://doc.rust-lang.org/stable/std/os/wasi/io/index.html

Just need to add `#[cfg_attr(not(bootstrap), rustc_allowed_through_unstable_modules)]` and it should work.

**Comment by bstrie** [comment]
I'll work on this.

**Comment by bstrie** [comment]
@yaahc Using your suggested fix, I have a simple PR to address this, if you'd like to review: https://github.com/rust-lang/rust/pull/99723 . I've confirmed locally that a toolchain built with this patch fixes the regression.
