### ISSUE TITLE
1.95 beta regression: "malformed `feature` attribute input"

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#153764]
Regression found in the 1.95.0 beta crater run.

```
[INFO] [stdout] error[E0565]: malformed `feature` attribute input
[INFO] [stdout]   --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/assemble-core-0.2.0/src/unstable.rs:16:5
[INFO] [stdout]    |
[INFO] [stdout] 16 |     #[feature(feature = "text_factory")]
[INFO] [stdout]    |     ^^^^^^^^^^^^^^^^^^----------------^^
[INFO] [stdout]    |     |                 |
[INFO] [stdout]    |     |                 didn't expect any arguments here
[INFO] [stdout]    |     help: must be of the form: `#[feature(feature1, feature2, ...)]`
```

* https://crater-reports.s3.amazonaws.com/beta-1.95-1/beta-2026-03-05/reg/assemble-std-0.2.0/log.txt

```
[INFO] [stdout] error[E0539]: malformed `feature` attribute input
[INFO] [stdout]  --> src/models/whisper/mod.rs:1:1
[INFO] [stdout]   |
[INFO] [stdout] 1 | #![feature("whisper")]
[INFO] [stdout]   | ^^^^^^^^^^^---------^^
[INFO] [stdout]   | |          |
[INFO] [stdout]   | |          expected a valid identifier here
[INFO] [stdout]   | help: must be of the form: `#![feature(feature1, feature2, ...)]`
```

* https://crater-reports.s3.amazonaws.com/beta-1.95-1/beta-2026-03-05/gh/MikeIvanichev.norma/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.95-3/1.95.0-beta.3/reg/norma-0.0.3/log.txt

```
[INFO] [stdout] error[E0539]: malformed `feature` attribute input
[INFO] [stdout]  --> src/lib.rs:4:1
[INFO] [stdout]   |
[INFO] [stdout] 4 | #[feature("serde_feature")]
[INFO] [stdout]   | ^^^^^^^^^^---------------^^
[INFO] [stdout]   | |         |
[INFO] [stdout]   | |         expected a valid identifier here
[INFO] [stdout]   | help: must be of the form: `#[feature(feature1, feature2, ...)]`
```

* https://crater-reports.s3.amazonaws.com/beta-1.95-1/beta-2026-03-05/reg/isfet-0.1.3/log.txt

```
[INFO] [stdout] error[E0539]: malformed `feature` attribute input
[INFO] [stdout]  --> src/lib.rs:4:1
[INFO] [stdout]   |
[INFO] [stdout] 4 | #[feature("proc_macro_lib2")]
[INFO] [stdout]   | ^^^^^^^^^^-----------------^^
[INFO] [stdout]   | |         |
[INFO] [stdout]   | |         expected a valid identifier here
[INFO] [stdout]   | help: must be of the form: `#[feature(feature1, feature2, ...)]`
```

* https://crater-reports.s3.amazonaws.com/beta-1.95-3/1.95.0-beta.3/reg/starlane-primitive-macros-0.3.21/log.txt

In four out of the five affected crates, it seems like the authors of the code intended to write `cfg(feature = "something")`. In `starlane-primitive-macros`, it seems the author wrote `#[feature(....)]` when they meant `#![feature(....)]`, with a `!`

**Comment by theemathas** [comment]
Presumably regressed in #152985. cc @JonathanBrouwer @jdonszelmann
