### PR TITLE
Fix #124275: Implemented Default for `Arc<str>`

### LINKED ISSUE #124275: `Arc<str>` does not have a `Default` impl
I tried this code:

```rust
    let my_var: Arc<str> = Default::default();
    assert_eq!(my_var, Arc::from(""));
```

I expected to see this happen: 

> Compiles and Runs successfully.

Instead, this happened: 
```rust
error[E0277]: the trait bound `str: Default` is not satisfied
 --> src/main.rs:4:28
  |
4 |     let my_var: Arc<str> = Default::default();
  |                            ^^^^^^^^^^^^^^^^^^ the trait `Default` is not implemented for `str`, which is required by `Arc<str>: Default`
  |
  = help: the following other types implement trait `Default`:
            &str
            &mut str
  = note: required for `Arc<str>` to implement `Default`

For more information about this error, try `rustc --explain E0277`.
```

It does work for `Arc<&str>` but not for `Arc<str>`. This is because `str` doesn't have a Default impl (presumably due to being unsized).

In theory its as "simple" as adding this into the `std/alloc` library, which does pass `./x.py check library/core` on my machine. However this is definitely not the most efficient implementation of the intended result, and perhaps an implementation similar to `impl Default for Box<str>` would suffice more acutely.
```rust
#[cfg(not(no_global_oom_handling))]
impl Default for Arc<str> {
    /// Creates an empty str inside an Arc
    #[inline]
    fn default() -> Self {
        Arc::from("")
    }
}
```

### Meta

`rustc --version --verbose`: `Stable channel: Build using the Stable version: 1.77.2`. 
Applies on nightly: `Nightly channel: Build using the Nightly version: 1.79.0-nightly (2024-04-21 fb898629a26e4acec59c)` also.

### PR DESCRIPTION
**Pull request by Billy-Sheppard**
With added implementations.

```
GOOD    Arc<CStr> 
BROKEN  Arc<OsStr> // removed
GOOD    Rc<str>
GOOD    Rc<CStr>
BROKEN  Rc<OsStr> // removed

GOOD    Rc<[T]> 
GOOD    Arc<[T]>
```

For discussion of https://github.com/rust-lang/rust/pull/124367#issuecomment-2091940137.

Key pain points currently:
> I've had a guess at the best locations/feature attrs for them but they might not be correct.

> However I'm unclear how to get the OsStr impl to compile, which file should they go in to avoid the error below? Is it possible, perhaps with some special std rust lib magic?

### CODE REVIEW

**Comment by zachs18** [comment]
I think the `stable` attributes should probably be something like `#[stable(feature = "more_rc_default_impls", since = "CURRENT_RUSTC_VERSION")]`, (literally `CURRENT_RUSTC_VERSION`, it will be replaced with 1.XX when 1.XX branches ([e.g.](https://github.com/rust-lang/rust/pull/122754))).

**Comment by Billy-Sheppard** [comment]
This PR is now the main solution for #124275

**Comment by Mark-Simulacrum** [comment]
Hm, I see that there was an FCP in https://github.com/rust-lang/rust/pull/124367#issuecomment-2091940137 for these APIs, but I'm wondering if there was discussion already on whether these should return *new* Arc's or a shared Arc for the type (e.g., Arc<str> with an empty string can share a single static, rather than having to allocate each time).

r? @dtolnay to make the decision whether to re-evaluate FCP or not (just random roll for libs-api)

**Comment by zachs18** [comment]
Regarding returning new vs shared Arcs, I think the docs could perhaps be updated to say something like 

```rs
impl Default for (A)Rc<...> {
    /// Creates an empty ... inside an `(A)Rc`.
    ///
    /// This may or may not share an allocation with other `(A)Rc`s (on the same thread (for `Rc`)).
    fn default() -> Self { ... }
}
```

with the "may or may not" giving wiggle-room to add the "single shared allocation" semantics later (or to decide against it), but without blocking the impls on implementing those semantics now (It'd be doable for the concrete types `Arc<str>`/`Arc<CStr>`/etc, but it would be harder to do for `Arc<[T]>`[^1] or any `Rc<...>`[^2], and also harder to justify the cost).

[^1]: I have some [rough draft code](https://github.com/zachs18/empty-rc-slice/blob/main/src/arc.rs#L39-L42) that implements the shared allocation semantics for `Arc<[T]>`, but it wouldn't work in `alloc` because it uses `RwLock` which is from `std`. The concrete type impls could probably just use an `AtomicPtr` each though, which is available in `core`.

[^2]: The `Rc` impls in my code require `thread_local!`s, as I think any implementation would, so I don't see a way to include any of those in `alloc`. `#[thread_local]` is IIUC not available on every platform[^3].

[^3]: Though I guess if we have the "may or may not" verbiage, then it could be platform-dependent whether or not the single-shared-allocation semantics are implemented.

**Comment by Mark-Simulacrum** [comment]
I would expect that a shared allocation would use something like the [static empty groups in hashbrown](https://github.com/rust-lang/hashbrown/blob/master/src/raw/generic.rs#L54-L70). For `str` for example we'd just have the strong + weak count header in a `static EMPTY: Rc/ArcInner<()>` or similar, and return EMPTY.clone() from these functions. (Some care would need to be taken to ensure that std itself "owns" one of the reference counts at all times, but that seems easy enough.)

**Comment by zachs18** [comment]
I hadn't thought of that, but yeah having a `static ArcInner<_>` would be a much simpler solution than lazily-initailizing a shared pointer. to a dynamic allocation. That also makes it simpler to do for `[T]`, since we can just have a shared static for each alignment up to some threshold, and do the current make-a-new-allocation-on-each-call for anything over-aligned.

@Billy-Sheppard I have a [branch](https://github.com/zachs18/rust/tree/arc-default) with these changes if you'd like to incorporate them into this PR, or perhaps just the first commit with the documentation, and I can submit the implementation as a later PR.

**Comment by Billy-Sheppard** [comment]
> I hadn't thought of that, but yeah having a `static ArcInner<_>` would be a much simpler solution than lazily-initailizing a shared pointer. to a dynamic allocation. That also makes it simpler to do for `[T]`, since we can just have a shared static for each alignment up to some threshold, and do the current make-a-new-allocation-on-each-call for anything over-aligned.
> 
> Billy-Sheppard I have a [branch](https://github.com/zachs18/rust/tree/arc-default) with these changes if you'd like to incorporate them into this PR, or perhaps just the first commit with the documentation, and I can submit the implementation as a later PR.

Thanks Zach, they seem like reasonable implementations to me.

**Comment by Billy-Sheppard** [comment]
It doesn't quite seem to compile, I presume it isn't meeting the trait bounds for `internal_into_inner_with_allocator`?

**Comment by zachs18** [comment]
`internal_into_inner_with_allocator` was renamed in https://github.com/rust-lang/rust/pull/124981 to `into_inner_with_allocator`. The jobs run on `master` so that's been applied. If you `git rebase origin/master` and change those calls it should be fixed. Sorry about the confusion, I hadn't updated that branch since that was merged.

**Comment by Billy-Sheppard** [comment]
apologies for the terrible merge, not quite sure how I managed that

**Comment by zachs18** [comment]
The current commit in this PR has a very long commit message from the merge issues, not sure if that needs to be fixed.

I have updated and rebased my `arc-default` branch; the contents should be the exact same as you currently have, but with separate commits with the original commit messages without the extra stuff. You should be able to run (while on this PR's branch; assuming you have my fork as the `zachs18` remote) `git fetch --all && git reset --hard zachs18/arc-default && git push -f` to get the commit messages back to normal.

**Comment by Billy-Sheppard** [comment]
I forgot to push my amended message, unfortunately the broken merge will still show in the PR comments here (apologies for all those that got pinged, I hadn't realised the merge didn't grab the current upstream.

**Comment by zachs18** [comment]
I still think it would be ideal to have the separate commits, so that the "shared-allocation" commit can be split out if necessary. The current commit also doesn't have the correct attribution.

**Comment by Billy-Sheppard** [comment]
Ah yes I was wondering about that (attributing).

Good call

**Review by dtolnay — APPROVED** [review]
Thanks!

I would be interested to review a followup PR that makes these share the same static ArcInner, instead of 6 different effectively-identical ones. The representation I would expect is a 16-byte-aligned static with the following contents:

```text
+---------------+---------------+-+-----------------------------+
| strong count  |  weak count   |0|          padding            |
+---------------+---------------+-+-----------------------------+
```

This works as the `ArcInner<[T]>` for any `align_of::<T>() <= 16`, and also `str` and `CStr`.
