### PR TITLE
Use heuristics to suggest assignment

### PR DESCRIPTION
**Pull request by estebank**
When detecting a possible `=` -> `:` typo in a `let` binding, suggest
assigning instead of setting the type.

Partially address #57828.

### CODE REVIEW

**Comment by estebank** [comment]
Follow up work would be to silence likely knock-down errors. To do, we should keep track of having suggested `:`→`=` (the span is enough) and not emit the "invalid parenthesized type parameters" and "ambiguous associated type" errors if their spans are contained by it.

File: src/librustc_resolve/late.rs [hunk 1]
```diff
@@ -351,6 +351,9 @@ struct LateResolutionVisitor<'a, 'b> {
 
     /// Only used for better errors on `fn(): fn()`.
     current_type_ascription: Vec<Span>,
+
+    /// Only used for better errors on `let <pat>: <expr, not type>;`.
+    current_let_binding: Option<(Span, Span)>,
```
Comment (Centril) [inline src/librustc_resolve/late.rs]: At this point there are a lot of "for diagnostics" state in `LateResolutionVisitor` -- could we perhaps move these into their own struct `diag: Diagnostics` to clarify this throughout the code so that they don't seep into semantic logic?

File: src/librustc_resolve/late.rs [hunk 2]
```diff
@@ -374,7 +377,18 @@ impl<'a, 'tcx> Visitor<'tcx> for LateResolutionVisitor<'a, '_> {
         self.resolve_expr(expr, None);
     }
     fn visit_local(&mut self, local: &'tcx Local) {
+        debug!("visit_local {:?} {:?} {:?}", local, local.pat, local.pat.kind);
```
Comment (Centril) [inline src/librustc_resolve/late.rs]:
```suggestion
        debug!("LateResolutionVisitor::visit_local {:?} {:?} {:?}", local, local.pat, local.pat.kind);
```

File: src/librustc_resolve/late.rs [hunk 3]
```diff
@@ -374,7 +377,18 @@ impl<'a, 'tcx> Visitor<'tcx> for LateResolutionVisitor<'a, '_> {
...
+        let val = match local {
```
Comment (Centril) [inline src/librustc_resolve/late.rs]: "val" here is rather vague, could a more descriptive name be used?

File: src/librustc_resolve/late.rs [hunk 4]
```diff
@@ -374,7 +377,18 @@ impl<'a, 'tcx> Visitor<'tcx> for LateResolutionVisitor<'a, '_> {
...
+            Local { pat, ty: Some(ty), init: None, .. } => match pat.kind {
+                // We check for this to avoid tuple struct fields.
+                PatKind::Wild => None,
```
Comment (Centril) [inline src/librustc_resolve/late.rs]: We have `let _: <type>` here -- what's special about that?

File: src/librustc_resolve/late/diagnostics.rs [hunk 5]
```diff
@@ -256,6 +261,20 @@ impl<'a> LateResolutionVisitor<'a, '_> {
         if !levenshtein_worked {
             err.span_label(base_span, fallback_label);
             self.type_ascription_suggestion(&mut err, base_span);
+            if let Some(span) = self.current_let_binding.and_then(|(pat_sp, ty_sp)| {
+                if ty_sp.contains(base_span) && is_local {
```
Comment (Centril) [inline src/librustc_resolve/late/diagnostics.rs]: Could use `.then_with(...)` here (https://github.com/rust-lang/rust/pull/65195).

**Comment by Centril** [comment]
Is this a commonly occurring problem? cc @hsivonen didn't really elaborate and they are not a newcomer.

**Comment by estebank** [comment]
We already handle this kind of error when there are parse errors, but this case is insidious because it parses correctly and then causes multiple knock down errors. The big win would be to turn the three errors into just one.

File: src/librustc_resolve/late.rs (hunk 4 above)
Comment (estebank) [reply src/librustc_resolve/late.rs]: I've seen no way to differentiate between `let _: <type>;` and `struct T(usize);`. Without this filter the suggestion triggers incorrectly for the latter in one of the tests.

File: src/librustc_resolve/late.rs [hunk 6]
```diff
@@ -548,12 +568,15 @@ impl<'a, 'b> LateResolutionVisitor<'a, '_> {
             },
             label_ribs: Vec::new(),
             current_trait_ref: None,
-            current_trait_assoc_types: Vec::new(),
-            current_self_type: None,
-            current_self_item: None,
-            current_function: None,
-            unused_labels: Default::default(),
-            current_type_ascription: Vec::new(),
+            diagnostic_metadata: DiagnosticMetadata {
```
Comment (Centril) [inline src/librustc_resolve/late.rs]:
```suggestion
            diagnostic_metadata: DiagnosticMetadata::default(),
```

File: src/librustc_resolve/late/diagnostics.rs (hunk 5 above)
Comment (estebank) [reply src/librustc_resolve/late/diagnostics.rs]: Changed it in a different way.

**Comment by hsivonen** [comment]
> Is this a commonly occurring problem?

I don't know how commonly this occurs, but when it did occur, it was confusing.

**Comment by estebank** [comment]
@hsivonen would the current output have been enough for you to quickly identify the issue?

```
error[E0573]: expected type, found local variable `num`
  --> $DIR/let-binding-init-expr-as-ty.rs:2:27
   |
LL |     let foo: i32::from_be(num);
   |            --             ^^^ not a type
   |            |
   |            help: use `=` if you meant to assign

error: parenthesized type parameters may only be used with a `Fn` trait
  --> $DIR/let-binding-init-expr-as-ty.rs:2:19
   |
LL |     let foo: i32::from_be(num);
   |                   ^^^^^^^^^^^^
   |
   = note: `#[deny(parenthesized_params_in_types_and_modules)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #42238 <https://github.com/rust-lang/rust/issues/42238>

error[E0223]: ambiguous associated type
  --> $DIR/let-binding-init-expr-as-ty.rs:2:14
   |
LL |     let foo: i32::from_be(num);
   |              ^^^^^^^^^^^^^^^^^ help: use fully-qualified syntax: `<i32 as Trait>::from_be`
```

Further improvements would get pretty hairy pretty quickly.

**Comment by hsivonen** [comment]
> would the current output have been enough for you to quickly identify the issue?

Likely yes. Thank you!

**Comment by JohnTitor** [comment]
It seems chocolatey is now available, let's check if it works.
@bors treeclosed-

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/65851#issuecomment-546643277 with log https://rust-lang.github.io/rust-log-analyzer/log-viewer/#https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/11971/logs/49

@bors r-

**Comment by estebank** [comment]
Fallout from the suggestions change. I'll rebase and fix.
