### PR TITLE
std: Fix build for NuttX targets

### PR DESCRIPTION
**Pull request by thaliaarchi**
Fix std build for all NuttX targets. It is the single largest set of failures on <https://does-it-build.noratrieb.dev/>. Although, ESP-IDF also requires these same gates, there are other issues for those targets.

This can verified be running `x check library/std --target=` for all NuttX targets.

cc @no1wudi

### CODE REVIEW

**Review by no1wudi — APPROVED** [review]
LGTM, thanks!

BTW, the missing SIGABRT will be fixed by https://github.com/rust-lang/libc/pull/4353

**Comment by thaliaarchi** [comment]
Nice! When I saw the missing `SIGABRT` via `x check library`, I decided to scale back my ambition and only fix `x check library/std` for now, haha.

**Comment by thaliaarchi** [comment]
@Mark-Simulacrum Hey, friendly two-week ping.

I've checked it again locally, rebased onto master, and it's still necessary for building NuttX.

**Comment by thaliaarchi** [comment]
This PR has been quite unlucky with CI :sweat_smile:. The first failures in the two rollups were caused by other PRs and the third rollup and when tested alone look spurious. The only kind of failure we could possibly get for this is a compile error, but since the platforms changed here aren't tested in CI, it effectively changes nothing.

Can we try again in the queue?

Rollup https://github.com/rust-lang/rust/pull/139717#issuecomment-2799036117 (caused by https://github.com/rust-lang/rust/pull/137494)
```
error: unused variable: `open_devnull`
  --> library/std/src/sys/pal/unix/mod.rs:65:17
   |
65 |         let mut open_devnull = || {
   |                 ^^^^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_open_devnull`

error: variable does not need to be mutable
  --> library/std/src/sys/pal/unix/mod.rs:65:13
   |
65 |         let mut open_devnull = || {
   |             ----^^^^^^^^^^^^
```

Rollup https://github.com/rust-lang/rust/pull/139723#issuecomment-2799439976 (caused by https://github.com/rust-lang/rust/pull/138881)
```
---- [codegen] tests/codegen/array-cmp.rs stderr ----
error: verification with 'FileCheck' failed
/checkout/tests/codegen/array-cmp.rs:43:12: error: CHECK: expected string not found in input
 // CHECK: %[[PA01:.+]] = getelementptr{{.+}}i8, ptr %a, i64 2
```

Rollup https://github.com/rust-lang/rust/pull/139728#issuecomment-2799563681
```
curl: (6) Could not resolve host: ci-mirrors.rust-lang.org
Process completed with exit code 6.
```

Alone https://github.com/rust-lang/rust/pull/138972#issuecomment-2799584141
```
---- [ui] tests/ui/abi/extern/extern-call-deep.rs stderr ----
thread 'main' panicked at src/tools/remote-test-client/src/main.rs:309:9:
client.read_exact(&mut header) failed with Connection reset by peer (os error 104)
```

**Comment by jieyouxu** [comment]
```
2025-04-13T03:57:03.7507822Z thread 'main' panicked at src/tools/remote-test-client/src/main.rs:309:9:
2025-04-13T03:57:03.7509260Z client.read_exact(&mut header) failed with Connection reset by peer (os error 104)
2025-04-13T03:57:03.7510193Z note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

@bors retry
