### ISSUE TITLE
regression: trait bound not satisfied

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#125194]
- https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/blades-0.5.0/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/kino-mc.rsmt2/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/rsmt2-0.16.2/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/kprav33n.aoc22.rs/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/rene-0.1.0/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/CallumJHays.quickdiff/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/Heiss.blades-heading/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/Punie.legend/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/cost-management.cost-management-api/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/grego.blades-katex-rs/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/o-santi.nixchess/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/robertohuertasm.yt-api-rest-actix-web/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/gh/vorrarit.test-rust/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/blades-katex-0.1.2/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/etwin_forum_store-0.12.3/log.txt
 - https://crater-reports.s3.amazonaws.com/beta-1.79-2/beta-2024-05-11/reg/serde_flat_path-0.1.2/log.txt

```
[INFO] [stdout] error[E0277]: the trait bound `for<'a> beef::generic::Cow<'a, str, beef::wide::internal::Wide>: Borrow<beef::generic::Cow<'_, str, lean::internal::Lean>>` is not satisfied
[INFO] [stdout]    --> src/page.rs:433:18
[INFO] [stdout]     |
[INFO] [stdout] 433 |             .get(template)
[INFO] [stdout]     |              --- ^^^^^^^^ the trait `for<'a> Borrow<beef::generic::Cow<'_, str, lean::internal::Lean>>` is not implemented for `beef::generic::Cow<'a, str, beef::wide::internal::Wide>`
[INFO] [stdout]     |              |
[INFO] [stdout]     |              required by a bound introduced by this call
[INFO] [stdout]     |
```

likely #119820 cc @lcnr, this was intended breakage afaik

**Comment by lcnr** [comment]
likely caused by https://github.com/rust-lang/rust/pull/119820. I am considering to reenable the old behavior for one more beta version to give this more time on nightly. Doing so is straightforward and non-breaking

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23125194.20regression.3A.20trait.20bound.20not.20satisfied)).

@rustbot label -I-prioritize +P-critical

**Comment by lcnr** [comment]
lowering priority to `P-high`. We will have to decide whether to push back the stabilization of this change by yet another version however :thinking:

**Comment by apiraino** [comment]
Changes in #119820 were reverted so in theory these regressions are neutralized (IIUC)

**Comment by lcnr** [comment]
only reverted on the previous beta (now stable), it still affects nightly (and the new beta)

**Comment by lcnr** [comment]
reopening until the beta-revert

**Comment by Mark-Simulacrum** [comment]
backported in https://github.com/rust-lang/rust/pull/127618
