### ISSUE TITLE
Undefined symbol _fltused when compiling to x86_64-unknown-uefi

### ISSUE THREAD

**Issue by IsaacWoods** [rust-lang/rust#62785]
Recent nightlies give the following linker error when trying to compile with the `x86_64-unknown-uefi` target:
```
error: linking with `rust-lld` failed: exit code: 1
  |
  = note: "rust-lld" "-flavor" "link" "/NOLOGO" "/NXCOMPAT" "/nodefaultlib" "/entry:efi_main" "/subsystem:efi_applic
ation" "/LIBPATH:/home/isaac/Documents/pebble/bootloader/target/sysroot/lib/rustlib/x86_64-unknown-uefi/lib" "/home/
isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/bootloader-cb388c983ab7c215.bootloader.17p
m2976-cgu.0.rcgu.o" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/bootloader-cb38
8c983ab7c215.bootloader.17pm2976-cgu.1.rcgu.o" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/r
elease/deps/bootloader-cb388c983ab7c215.bootloader.17pm2976-cgu.10.rcgu.o" "/home/isaac/Documents/pebble/bootloader/
target/x86_64-unknown-uefi/release/deps/bootloader-cb388c983ab7c215.bootloader.17pm2976-cgu.11.rcgu.o" "/home/isaac/
Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/bootloader-cb388c983ab7c215.bootloader.17pm2976-
cgu.12.rcgu.o" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/bootloader-cb388c983
ab7c215.bootloader.17pm2976-cgu.13.rcgu.o" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/relea
se/deps/bootloader-cb388c983ab7c215.bootloader.17pm2976-cgu.14.rcgu.o" "/home/isaac/Documents/pebble/bootloader/targ
et/x86_64-unknown-uefi/release/deps/bootloader-cb388c983ab7c215.bootloader.17pm2976-cgu.15.rcgu.o" "/home/isaac/Docu
ments/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/bootloader-cb388c983ab7c215.bootloader.17pm2976-cgu.
2.rcgu.o" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/bootloader-cb388c983ab7c2
15.bootloader.17pm2976-cgu.3.rcgu.o" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/dep
s/bootloader-cb388c983ab7c215.bootloader.17pm2976-cgu.4.rcgu.o" "/home/isaac/Documents/pebble/bootloader/target/x86_
64-unknown-uefi/release/deps/bootloader-cb388c983ab7c215.bootloader.17pm2976-cgu.5.rcgu.o" "/home/isaac/Documents/pe
bble/bootloader/target/x86_64-unknown-uefi/release/deps/bootloader-cb388c983ab7c215.bootloader.17pm2976-cgu.6.rcgu.o
" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/bootloader-cb388c983ab7c215.bootl
oader.17pm2976-cgu.7.rcgu.o" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/bootlo
ader-cb388c983ab7c215.bootloader.17pm2976-cgu.8.rcgu.o" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unkno
wn-uefi/release/deps/bootloader-cb388c983ab7c215.bootloader.17pm2976-cgu.9.rcgu.o" "/OUT:/home/isaac/Documents/pebbl
e/bootloader/target/x86_64-unknown-uefi/release/deps/bootloader-cb388c983ab7c215.efi" "/OPT:REF,ICF" "/DEBUG" "/LIBP
ATH:/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps" "/LIBPATH:/home/isaac/Documents
/pebble/bootloader/target/release/deps" "/LIBPATH:/home/isaac/Documents/pebble/bootloader/target/sysroot/lib/rustlib
/x86_64-unknown-uefi/lib" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/libx86_64
-e73f78284a1860d7.rlib" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/libbitflags
-094ae181fdaa32fd.rlib" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/libmer-507c
9f2f8b4d808b.rlib" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/libscroll-363628
fffd45fc02.rlib" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/libbit_field-0de0b
ae1c29c3197.rlib" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/liblog-7dddffb9af
6bf12e.rlib" "/home/isaac/Documents/pebble/bootloader/target/x86_64-unknown-uefi/release/deps/libcfg_if-6874da1a7a9e
b04a.rlib" "/home/isaac/Documents/pebble/bootloader/target/sysroot/lib/rustlib/x86_64-unknown-uefi/lib/librustc_std_
workspace_core-34dfaa25be8aa12b.rlib" "/home/isaac/Documents/pebble/bootloader/target/sysroot/lib/rustlib/x86_64-unk
nown-uefi/lib/libcore-6847ba0a79455c40.rlib" "/home/isaac/Documents/pebble/bootloader/target/sysroot/lib/rustlib/x86
_64-unknown-uefi/lib/libcompiler_builtins-0eac2e6da53df529.rlib"
  = note: rust-lld: error: undefined symbol: _fltused
          >>> referenced by libcore-6847ba0a79455c40.rlib(core-6847ba0a79455c40.core.e2k58cht-cgu.12.rcgu.o)
          >>> referenced by libcore-6847ba0a79455c40.rlib(core-6847ba0a79455c40.core.e2k58cht-cgu.15.rcgu.o)
          >>> referenced by libcore-6847ba0a79455c40.rlib(core-6847ba0a79455c40.core.e2k58cht-cgu.5.rcgu.o)
          >>> referenced by libcore-6847ba0a79455c40.rlib(core-6847ba0a79455c40.core.e2k58cht-cgu.6.rcgu.o)
          >>> referenced by libcore-6847ba0a79455c40.rlib(core-6847ba0a79455c40.core.e2k58cht-cgu.3.rcgu.o)
          >>> referenced by libcore-6847ba0a79455c40.rlib(core-6847ba0a79455c40.core.e2k58cht-cgu.10.rcgu.o)
          >>> referenced by libcompiler_builtins-0eac2e6da53df529.rlib(compiler_builtins-0eac2e6da53df529.compiler_b
uiltins.6cufwy9q-cgu.0.rcgu.o)
```

My guess at likely causes is [this commit](https://github.com/rust-lang-nursery/compiler-builtins/commit/bf3a9e9d0b9c4693c8e49fcdc626117e0d5b74fc) to `compiler-builtins`. The project itself does not use any floating-point operations so I'm surprised that any code that refers to this symbol is included in the final executable.

I'm not sure what the best fix for this would be (assuming this isn't intended behaviour), but adding this somewhere in the project works in the meantime:
```
#[used]
#[no_mangle]
pub static _fltused: i32 = 0;
```

**Comment by nikomatsakis** [comment]
Update from compiler-team:

Marking as high priority but the most obvious next step would be to bisect this and validate which PR caused the problem. The [cargo-bisect-rustc](https://github.com/rust-lang-nursery/cargo-bisect-rustc) tool could be very helpful here.

cc @varkor, since the commit cited above was from them, though it's not clear to me if that is the true cause

**Comment by jyao1** [comment]
https://reviews.llvm.org/D56548 changed the policy to generate _fltused symbol - *"It should be emitted when any floating-point operations (including calls) are present in the object, not just when calls to printf/scanf with floating point args are made."*

To resolve the x86_64-unknown-uefi issue, we may have below possible options:
1) Let LLVM not generate _fltused.
1.1) Add option to force LLVM not to generate _fltused in MSVC, because we use MSVC tool chain only but not link MSVC library. It seems need update in LLVM project. The benefit is that we can use LLVM MSVC to build other embedded project with NODEFAULTLIB option.
1.2) Use non-MSVC target for UEFI. Not sure if GNU is an option. The default X64 calling convention between MSVC and GNU is different. Not sure if it is configurable.
1.3) Write UEFI RUST program carefully to avoid _fltused. That is very hard. Even simple core::fmt::{write}, *.as_ptr(), or core::ptr::write_bytes() will generate _fltused. Not a practical option.

2) Add _fltused symbol.
2.1) Add target_os specific symbol in rust. (rust repo such as libcore, or compiler-builtins repo.). But I am not sure how to expose it for uefi specific target_os. [cfg(all(target_os = “uefi”))] seems not work because we still use linux or windows toolchain, to build uefi target.
2.2) Add UEFI Intrinsic lib as standalone crate. That seems an easy option. The good thing is that it is extensible, if there are other compiler intrinsics needed in the future. But it may bring some confusing because the intrinsic is not really for UEFI, but for all embedded project without default lib.
2.3) Add symbol in each UEFI rust program, if it does not link to UEFI instrinsic lib.

**Comment by joshtriplett** [comment]
Ah, it seems unfortunate that using a format function triggers this even if not trying to format floats. (Though the LTO results seem encouraging.) In that case, yeah, I would suggest adding the LLVM option long-term, and until then, I think it makes sense to just define this in core internally.

`target_os` *should* work given that you use the uefi target; it defines the target OS as "uefi". (Also, you can just do so for x86_64.)

**Comment by oli-obk** [comment]
I opened https://github.com/rust-lang/rust/pull/64990 with the `_fltused` symbol added to libcore

**Comment by GabrielMajeri** [comment]
Hello! This issue seems to have reappeared. 

See, for example, [this](https://github.com/rust-osdev/uefi-rs/runs/7503555075?check_suite_focus=true) GitHub Actions job:

```
 = note: rust-lld: error: undefined symbol: _fltused
          >>> referenced by libuefi-ec1f12a68e3f8ed4.rlib(uefi-ec1f12a68e3f8ed4.5e0gotzcag6bbxy0.rcgu.o)
          >>> referenced by libcore-b9012135222c57c8.rlib(core-b9012135222c57c8.core.eba108b8-cgu.12.rcgu.o)
          >>> referenced by libcore-b9012135222c57c8.rlib(core-b9012135222c57c8.core.eba108b8-cgu.13.rcgu.o)
          

error: could not compile `uefi-test-runner` due to previous error
Error: command failed: exit status: 101
```

We've made no changes to the code, the CI simply downloaded the latest nightly. The errors seem to have started with `rustc 1.64.0-nightly (62b272d25 2022-07-21)`.

**Comment by nicholasbishop** [comment]
I think this is now re-fixed fortunately :)

This regressed in https://github.com/rust-lang/rust/commit/ceeb5ade201e4181c6d5df2ba96ae5fb2193aadc, and I think https://github.com/rust-lang/rust/pull/99676 fixed it. The latest nightly no longer has this error.

**Comment by AtomicGamer9523** [comment]
I have encountered this issue when compiling on `x86_64-pc-windows-msvc`:
```
libcompiler_builtins-9b73ba83da15270d.rlib(compiler_builtins-9b73ba83da15270d.compiler_builtins.da72492743c67d66-cgu.1.rcgu.o) : error LNK2001: unresolved external symbol _fltused
libcompiler_builtins-9b73ba83da15270d.rlib(compiler_builtins-9b73ba83da15270d.compiler_builtins.da72492743c67d66-cgu.4.rcgu.o) : error LNK2001: unresolved external symbol _fltused
libcompiler_builtins-9b73ba83da15270d.rlib(compiler_builtins-9b73ba83da15270d.compiler_builtins.da72492743c67d66-cgu.0.rcgu.o) : error LNK2001: unresolved external symbol _fltused
libcompiler_builtins-9b73ba83da15270d.rlib(compiler_builtins-9b73ba83da15270d.compiler_builtins.da72492743c67d66-cgu.3.rcgu.o) : error LNK2001: unresolved external symbol _fltused
libcore-f63b72dfc4a1ee75.rlib(core-f63b72dfc4a1ee75.core.40809e373ed9bf76-cgu.08.rcgu.o) : error LNK2001: unresolved external symbol _fltused
libcore-f63b72dfc4a1ee75.rlib(core-f63b72dfc4a1ee75.core.40809e373ed9bf76-cgu.15.rcgu.o) : error LNK2001: unresolved external symbol _fltused
libcore-f63b72dfc4a1ee75.rlib(core-f63b72dfc4a1ee75.core.40809e373ed9bf76-cgu.12.rcgu.o) : error LNK2001: unresolved external symbol _fltused
libcompiler_builtins-9b73ba83da15270d.rlib(compiler_builtins-9b73ba83da15270d.compiler_builtins.da72492743c67d66-cgu.2.rcgu.o) : error LNK2001: unresolved external symbol _fltused
libcore-f63b72dfc4a1ee75.rlib(core-f63b72dfc4a1ee75.core.40809e373ed9bf76-cgu.11.rcgu.o) : error LNK2001: unresolved external symbol _fltused
libcore-f63b72dfc4a1ee75.rlib(core-f63b72dfc4a1ee75.core.40809e373ed9bf76-cgu.14.rcgu.o) : error LNK2001: unresolved external symbol _fltused
libcore-f63b72dfc4a1ee75.rlib(core-f63b72dfc4a1ee75.core.40809e373ed9bf76-cgu.09.rcgu.o) : error LNK2001: unresolved external symbol _fltused
libcore-f63b72dfc4a1ee75.rlib(core-f63b72dfc4a1ee75.core.40809e373ed9bf76-cgu.10.rcgu.o) : error LNK2001: unresolved external symbol _fltused
```

**Comment by ChrisDenton** [comment]
Please open a new issue, ideally with a reproducible example if you're able.
