### PR TITLE
Implement the dbg!(..) macro

### PR DESCRIPTION
**Pull request by Centril**
Implements the `dbg!(..)` macro due to #54306.
cc https://github.com/rust-lang/rfcs/pull/2361

r? @alexcrichton

### CODE REVIEW

**Comment by SimonSapin** [comment]
Looks good, thanks!

@bors r+

File: src/libstd/macros.rs [hunk 1]
```diff
@@ -220,6 +220,126 @@ macro_rules! eprintln {
...
+/// let _ = dbg!(a); // <-- `a` is moved again; error!
+/// ```
+///
+/// [stderr]: https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)
+#[macro_export]
+#[unstable(feature = "dbg_macro", issue = "54306")]
+macro_rules! dbg {
+    ($val:expr) => {
+        // Use of `match` here is intentional because it affects the lifetimes
+        // of temporaries - https://stackoverflow.com/a/48732525/1063961
```
Comment (fbstj) [inline src/libstd/macros.rs]: is a Stack Overflow the best kind of link for this documentation? may be worth "archiving" as a blog post somewhere on the forge for example?

Comment (Centril) [reply src/libstd/macros.rs]: We can always update this to something better later -- I'd welcome a follow up PR if you have ideas :)
I think it is sufficient for now.

File: src/test/ui/rfc-2361-dbg-macro/dbg-macro-move-semantics.nll.stderr [hunk 2]
```diff
@@ -0,0 +1,36 @@
...
+   |
+LL |     let _ = dbg!(a);
+   |             ------- value moved here
+LL |     let _ = dbg!(a);
+   |             ^^^^^^^ value used here after move
+   |
+   = note: move occurs because `a` has type `NoCopy`, which does not implement the `Copy` trait
+   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
+
+error: aborting due to 3 previous errors
```
Comment (kennytm) [inline src/test/ui/rfc-2361-dbg-macro/dbg-macro-move-semantics.nll.stderr]:
```
[01:03:52] ---- [ui (nll)] ui/rfc-2361-dbg-macro/dbg-macro-move-semantics.rs stdout ----
[01:03:52] diff of stderr:
[01:03:52] 
[01:03:52] 9	   = note: move occurs because `a` has type `NoCopy`, which does not implement the `Copy` trait
[01:03:52] 10	   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
[01:03:52] 11	
[01:03:52] -	error[E0382]: borrow of moved value: `a`
[01:03:52] -	  --> $DIR/dbg-macro-move-semantics.rs:11:18
[01:03:52] -	   |
[01:03:52] -	LL |     let _ = dbg!(a);
[01:03:52] -	   |             ------- value moved here
[01:03:52] -	LL |     let _ = dbg!(a);
[01:03:52] -	   |                  ^ value borrowed here after move
[01:03:52] -	   |
[01:03:52] -	   = note: move occurs because `a` has type `NoCopy`, which does not implement the `Copy` trait
[01:03:52] -	   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
[01:03:52] -	
[01:03:52] -	error[E0382]: use of moved value: `a`
[01:03:52] -	  --> $DIR/dbg-macro-move-semantics.rs:11:13
[01:03:52] -	   |
[01:03:52] -	LL |     let _ = dbg!(a);
[01:03:52] -	   |             ------- value moved here
[01:03:52] -	LL |     let _ = dbg!(a);
[01:03:52] -	   |             ^^^^^^^ value used here after move
[01:03:52] -	   |
[01:03:52] -	   = note: move occurs because `a` has type `NoCopy`, which does not implement the `Copy` trait
[01:03:52] -	   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
[01:03:52] -	
[01:03:52] -	error: aborting due to 3 previous errors
[01:03:52] +	error: aborting due to previous error
[01:03:52] 35	
[01:03:52] 36	For more information about this error, try `rustc --explain E0382`.
[01:03:52] 37	
```

**Comment by kennytm** [comment]
@bors r-

NLL changes probably changed diagnostics, causing failure in https://github.com/rust-lang/rust/pull/54389#issuecomment-423213545. Could you rebase on latest master and verify if the CI still passes?

**Comment by pietroalbini** [comment]
Tests failed on wasm.
@bors r-

```
[00:59:02] ---- [ui] ui/rfc-2361-dbg-macro/dbg-macro-expected-behavior.rs stdout ----
[00:59:02] error: test run failed!
[00:59:02] status: exit code: 101
[00:59:02] status: exit code: 101
[00:59:02] command: "/node-v9.2.0-linux-x64/bin/node" "/checkout/src/etc/wasm32-shim.js" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/rfc-2361-dbg-macro/dbg-macro-expected-behavior/a.wasm"
[00:59:02] ------------------------------------------
[00:59:02] 
[00:59:02] ------------------------------------------
[00:59:02] stderr:
[00:59:02] stderr:
[00:59:02] ------------------------------------------
[00:59:02] RuntimeError: unreachable
[00:59:02]     at __rust_start_panic (wasm-function[148]:1)
[00:59:02]     at rust_panic.llvm.7229658430215002035 (wasm-function[142]:38)
[00:59:02]     at std::panicking::rust_panic_with_hook::h226a58a5977f2e17 (wasm-function[137]:500)
[00:59:02]     at std::panicking::continue_panic_fmt::h5f0126bd5d9da93f (wasm-function[136]:155)
[00:59:02]     at rust_begin_unwind (wasm-function[135]:3)
[00:59:02]     at core::panicking::panic_fmt::hebc42c0af7746402 (wasm-function[245]:80)
[00:59:02]     at core::result::unwrap_failed::hb8e1b756b0aad0f7 (wasm-function[19]:149)
[00:59:02]     at _$LT$core..result..Result$LT$T$C$$u20$E$GT$$GT$::unwrap::h047f9d6689dc96bf (wasm-function[1]:43)
[00:59:02]     at dbg_macro_expected_behavior::main::h80c10857552d47ce (wasm-function[6]:2332)
[00:59:02]     at std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::hffb7cd8ec38eb3e9 (wasm-function[9]:25)
[00:59:02]     at std::sys_common::backtrace::__rust_begin_short_backtrace::h178ce1cdbcfd3352 (wasm-function[68]:8)
[00:59:02]     at std::panicking::try::do_call::h92ed3f8ab1f1fe4c (.llvm.7229658430215002035) (wasm-function[134]:20)
[00:59:02]     at __rust_maybe_catch_panic (wasm-function[147]:5)
[00:59:02]     at std::rt::lang_start_internal::had2eaac6c6c88dfd (wasm-function[69]:150)
[00:59:02]     at std::rt::lang_start::hecee5b62d0f0e846 (wasm-function[8]:42)
[00:59:02]     at main (wasm-function[7]:11)
[00:59:02]     at Object.<anonymous> (/checkout/src/etc/wasm32-shim.js:136:20)
[00:59:02]     at Module._compile (module.js:641:30)
[00:59:02]     at Object.Module._extensions..js (module.js:652:10)
[00:59:02]     at Module.load (module.js:560:32)
[00:59:02] ------------------------------------------
[00:59:02] 
[00:59:02] 
[00:59:02] thread '[ui] ui/rfc-2361-dbg-macro/dbg-macro-expected-behavior.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3205:9
```

**Comment by SimonSapin** [comment]
Wasm targets don’t support subprocesses, right? So this failure is probably expected. I see some tests contain `// ignore-wasm`, this one probably need to as well.

**Comment by Centril** [comment]
Added `// ignore-wasm`; let's hope it works now :)

**Comment by Centril** [comment]
Same error...
I'm confused as to why the test is still running on wasm...

**Comment by Centril** [comment]
I added per @eddyb's notes:
```rust
// ignore-wasm32
// ignore-cloudabi no processes
// ignore-emscripten no processes
```
Let's hope that makes it work :)

**Comment by Centril** [comment]
I changed it to:
```rust
// run-pass
// ignore-cloudabi no processes
// ignore-emscripten no processes
```
since that's what the other tests do and that's more aligned with eddyb's and varkor's thoughts.

**Comment by RoelKluin** [comment]
The dbg macro lacks a possibility to format the output. For instance, it is not possible to print an u64 as hexadecimal. Therefore, I was thinking about below macro, if given more expressions, does allow formating:
```
#[macro_export]
macro_rules! dbg {
    ($expr:expr) => (dbg!("{:#?}", $expr));
    ($fmt:expr, $expr:expr$(, $opt:expr)*) => {
        match $expr {
            expr => {
                eprintln!(concat!("[{}:{}] {} = ", $fmt), file!(), line!(), stringify!($expr), &expr$(, $opt)*);
                expr
            }
        }
    }
}
```
With a single argument this behaves like current dbg, In case there are 2 or more, the first argument is a string literal format string, the second is the evaluated, optional remaining arguments can be provided as specified in the format string.

examples:
```
let t = dbg!(2 + 1);
let _: u64 = dbg!("{:x}", (1 << 63) | (t << 8));
let _: u64 = dbg!("{:x} with {}", (1 << 63) | (t << 8), t);
```
