### ISSUE TITLE
rustdoc: error[E0463]: can't find crate for `std`

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#96177]
With the last upstream rust, whenever I build rustdoc (with `x.py doc std --stage 1`) and try to use it on this code:

```rust
pub struct Foo(u8);
```

I get the following output:

```
$ ./build/x86_64-unknown-linux-gnu/stage1/bin/rustdoc foo.rs 
error[E0463]: can't find crate for `std`

error: Compilation failed, aborting rustdoc

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0463`.
```

I tried with `stage 2` but got the same error as well. Anyone has an idea what's going on?

**Comment by Mark-Simulacrum** [comment]
Cc @jyn514 

I suspect that this is related to some of the recent changes in this area - it's not clear to me that the command above *should* put std in the sysroot, but I can see how it might be expected too.

**Comment by GuillaumeGomez** [comment]
I've been using it for years so it was quite surprising. @jyn514 wrote that to build `std` sysroot, you now need to run `x.py build --stage 1 library/std src/tools/rustdoc`.

**Comment by jyn514** [comment]
> So the question I guess now is: should x.py doc std put std in the sysroot? Also I'm curious why it was changed.

This is caused by https://github.com/rust-lang/rust/pull/95450; it was intentional not to add these to the sysroot because it requires fully building the artifacts instead of only checking them. I don't think `doc` should add these to the sysroot, no, it's a separate thing conceptually than building the artifacts. The fact that it happened to work so long is just an accident.

> @jyn514 wrote that to build std sysroot, you now need to run x.py build --stage 1 library/std src/tools/rustdoc.

that's the long form - you can also just use `x build` and it will do the same.

**Comment by GuillaumeGomez** [comment]
Thanks for the explanations!
