### ISSUE TITLE
inherent assoc tys resolve with subtyping not equality

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#109789]
I tried this code:

```rust
#![feature(inherent_associated_types)]

struct Foo<T>(T);

impl Foo<fn(&'static ())> {
    type Assoc = u32;
}

trait Other {}
impl Other for u32 {}

fn bar(_: Foo<for<'a> fn(&'a ())>::Assoc) {}

```

I expected to see this happen: It not to compile as `Foo<for<'a> fn(&'a ())>` has no inherent impl defined on it

Instead, this happened: it compiled

### Meta
playground's nightly:
```
Build using the Nightly version: 1.70.0-nightly
(2023-03-29 17c11672167827b0dd92)
```

**Comment by fmease** [comment]
Fixed in #109410, although the error message is not *as* nice since we don't try to prettify it (yet). That should be done at a later stage though, IMO. [The trait analog](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=98283b850cfba0a6e66208a6501a332c) results in:

```
error: implementation of `Mid` is not general enough
  --> src/main.rs:17:11
   |
17 | fn bar(_: <Foo<for<'a> fn(&'a ())> as Mid>::Assoc) {}
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `Mid` is not general enough
   |
   = note: `Foo<for<'a> fn(&'a ())>` must implement `Mid`
   = note: ...but `Mid` is actually implemented for the type `Foo<fn(&'static ())>`
```

while the IAT one leads to the following error in #109410:

```
error[E0308]: mismatched types
  --> tests/ui/associated-inherent-types/issue-109789.rs:17:1
   |
17 | fn bar(_: Foo<for<'a> fn(&'a ())>::Assoc) {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected struct `Foo<fn(&'static ())>`
              found struct `Foo<for<'a> fn(&'a ())>`

error[E0308]: mismatched types
  --> tests/ui/associated-inherent-types/issue-109789.rs:17:11
   |
17 | fn bar(_: Foo<for<'a> fn(&'a ())>::Assoc) {}
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected struct `Foo<fn(&'static ())>`
              found struct `Foo<for<'a> fn(&'a ())>`
```

I should definitely fix the duplication of the diagnostic (albeit harmless).
As mentioned before, we spruce up the region error for traits in [`try_report_trait_placeholder_mismatch`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/error_reporting/nice_region_error/struct.NiceRegionError.html#method.try_report_trait_placeholder_mismatch). If I disable this logic, the trait analog yields almost the same error message (branch `master` with the cosmetic enhancements disabled):

```
error[E0308]: mismatched types
  --> analog.rs:17:11
   |
17 | fn bar(_: <Foo<for<'a> fn(&'a ())> as Mid>::Assoc) {}
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected trait `<Foo<for<'a> fn(&'a ())> as Mid>`
              found trait `<Foo<fn(&'static ())> as Mid>`
```

@rustbot claim

**Comment by fmease** [comment]
Regression test added.
