### ISSUE TITLE
Nightly regression - Option::cloned method resolution

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#44208]
[unic-ucd-normal](https://crates.io/crates/unic-ucd-normal) (and thus the supercrate [unic](https://crates.io/crates/unic)) was compiling on `rustc 1.21.0-nightly (e26688824 2017-08-27)` but fails on `rustc 1.21.0-nightly (c11f689d2 2017-08-29)`. (This is with the unpublished version at https://github.com/behnam/rust-unic/tree/master/unic/ucd/normal only.)  
[Passing build](https://travis-ci.org/behnam/rust-unic/jobs/269796515) & [Failing build](https://travis-ci.org/behnam/rust-unic/jobs/270210253)

```
   Compiling unic-ucd-normal v0.5.0 (file:///D:/Christopher/Documents/Code/Rust/rust-unic/unic/ucd/normal)
error[E0034]: multiple applicable items in scope
  --> unic\ucd\normal\src\lib.rs:63:65
   |
63 |         canonical_composition(a).and_then(|table| table.find(b).cloned())
   |                                                                 ^^^^^^ multiple `cloned` found
   |
   = note: candidate #1 is defined in an impl for the type `std::option::Option<&_>`
   = note: candidate #2 is defined in an impl for the type `std::option::Option<&mut _>`
```

This appears to be https://github.com/rust-lang/rust/issues/43738 (tracking) / https://github.com/rust-lang/rust/pull/43705 (impl) that is causing this. Note that we do not have `#![feature(option_ref_mut_cloned)]` (it didn't exist until today(?)).

Small reproduction in https://github.com/rust-lang/rust/issues/44208#issuecomment-326183331

**Comment by Mark-Simulacrum** [comment]
Nominating for @rust-lang/libs. Not sure if we can do much about this -- I'd expect this not to happen, as mutability shouldn't be inferred in most cases? A smaller example would definitely be helpful.

**Comment by CAD97** [comment]
@Mark-Simulacrum I got one! It's a bit weird...

https://play.rust-lang.org/?gist=66baa5300ee64ed6a0b0888e76c17dbc&version=nightly

```
use std::cmp;

fn canonical_composition(_: char) -> Option<&'static [(char, char)]> {
    static TABLE: &[(char, char)] = &[('a', 'a')];
    Some(TABLE)
}

trait DataTable<V> {
    fn find(&self, needle: char) -> Option<V>;
}

impl<'a, V> DataTable<&'a V> for &'a [(char, V)] {
    fn find(&self, needle: char) -> Option<&'a V> {
        self.binary_search_by_key(&needle, |&(k, _)| k)
            .map(|idx| &self[idx].1)
            .ok()
    }
}

impl DataTable<()> for &'static [(char, char)] {
    fn find(&self, needle: char) -> Option<()> {
        self.binary_search_by(|&(low, high)| if low > needle {
            cmp::Ordering::Greater
        } else if high < needle {
            cmp::Ordering::Less
        } else {
            cmp::Ordering::Equal
        }).map(|_| ())
            .ok()
    }
}

fn main() {
    canonical_composition('a').and_then(|table| table.find('a').cloned());
}
```

It seems to be caused by the two impls here, as removing the second eliminates the error (which is why I was having trouble finding a small reproduction)

**Comment by behnam** [comment]
It looks like the actual ambiguity is cause by having implementations for both `(char, V)` and `(char, char)` types, and is not actually about ref vs mut-ref; BUT, the error detection is confused and errs on the latter, instead of the former. It seems like this confusion could be the bug that needs to be fixed here.

**Comment by alexcrichton** [comment]
The libs team discussed this yesterday and @aturon volunteered to investigate this issue. In the meantime though we decided that we probably aren't going to revert.

**Comment by Mark-Simulacrum** [comment]
@aturon Any updates? This is due to land in 1.22 (which releases next week). If not, perhaps we can reassign.

**Comment by CAD97** [comment]
@Mark-Simulacrum 

Using the case in https://github.com/rust-lang/rust/issues/44208#issuecomment-326183331, it still causes an error on beta/nightly but not on stable:

```

**Comment by Mark-Simulacrum** [comment]
Right, because stable doesn't yet have the regression -- it will once 1.22 (current beta) is released next Thursday.

**Comment by aturon** [comment]
@Mark-Simulacrum thanks much for checking in. I don't have the cycles to look into this at the moment. @eddyb or @arielb1, would one of you mind?

**Comment by eddyb** [comment]
IIRC @arielb1 made some changes in the recent past to method resolution, not sure if they're related.

**Comment by arielb1** [comment]
@aturon 

This is caused by #43705, normal expected inference breakage.

**Comment by CAD97** [comment]
There's more to it than just an added fn. This case _should not be offered_ `std::option::Option::<&mut _>::cloned` as an option.

Using a reproduction case as simple as I was able to make it: <https://play.rust-lang.org/?gist=73317abb09e9e9b3469eb32d6a7d2545&version=beta>

```rust
trait DataTable<V> {
    fn find(&self, needle: char) -> Option<V>;
}

impl<'a, V> DataTable<&'a V> for &'a [(char, V)] {
    fn find(&self, _: char) -> Option<&'a V> {
        None
    }
}

impl DataTable<()> for &'static [(char, char)] {
    fn find(&self, _: char) -> Option<()> {
        None
    }
}

fn main() {
    static TABLE: &[(char, char)] = &[('a', 'a')];
    let x: Option<char> = TABLE.find('a').cloned();
}
```

Run as is, we get 
```
error[E0034]: multiple applicable items in scope
  --> src/main.rs:19:43
   |
19 |     let x: Option<char> = TABLE.find('a').cloned();
   |                                           ^^^^^^ multiple `cloned` found
   |
   = note: candidate #1 is defined in an impl for the type `std::option::Option<&_>`
   = note: candidate #2 is defined in an impl for the type `std::option::Option<&mut _>`
```

Comment out the second impl block, lines 11-15, _it compiles fine_.

Comment out the first impl block, lines 5-9, and we get
```
error[E0599]: no method named `cloned` found for type `std::option::Option<()>` in the current scope
  --> src/main.rs:19:43
   |
19 |     let x: Option<char> = TABLE.find('a').cloned();
   |                                           ^^^^^^
   |
   = note: the method `cloned` exists but the following trait bounds were not satisfied:
           `&mut std::option::Option<()> : std::iter::Iterator`
```

For completion, removing the call to `.cloned()` and the type specification for `let x`, we get
```
error[E0283]: type annotations required: cannot resolve `&[(char, char)]: DataTable<_>`
  --> src/main.rs:19:19
   |
19 |     let x = TABLE.find('a');
   |       
```

The type annotation on `let x` existing or not does not change the compiler output.

<hr>

Because the two impls `DataTable<&'a V> for &'a [(char, V)]` and `DataTable<()> for &'static [(char, char)]` exist, `((&'static [('a', 'a')]) as DataTable<_>).find('a')` is ambiguous. The resulting type should be `Option<&char>` or `Option<()>` depending on which `DataTable` impl is used. `Option::cloned` is only impl'd _once_, and _only on `Option<&char>`, not `Option<()>`._ More importantly, there is _no mutable reference anywhere_, so the compiler tripping up and suggesting `Option<&mut _>` _makes no sense_.

Whatever the issue is, it's more than the interface evolving to have multiple options. _These two options should not both be considered in this case._ Something with resolution must be going wrong to suggest the `Option<&mut _>` impl when there is no mutable reference anywhere.

**Comment by CAD97** [comment]
I have made a repro case of what I believe to be the same root issue (occurring on stable) without the stdlib fn call: <https://play.rust-lang.org/?gist=0faa6d4304f76c72d6941934c02edd97&version=stable>

```rust
struct Container<T> {
    inner: T,
}

impl<T> Container<&'static T> {
    fn do_something(&self) {
        println!("Container<&'a T>::do_something");
    }
}

impl<'a, T> Container<&'a mut T> {
    fn do_something(&self) {
        println!("Container<&'a mut T>::do_something");
    }
}

trait Issue<T> {
    fn make_container(&self) -> Container<T>;
}

impl<T> Issue<&'static T> for &'static [(char, T)] {
    fn make_container(&self) -> Container<&'static T> {
        Container { inner: &self[0].1 }
    }
}

impl Issue<()> for &'static [(char, char)] {
    fn make_container(&self) -> Container<()> {
        Container { inner: () }
    }
}

fn main() {
    static ARR: &[(char, char)] = &[('a', 'a')];
    let _ = ARR.make_container().do_something();
}
```

Compiling gives us:
```
error[E0034]: multiple applicable items in scope
  --> src/main.rs:35:34
   |
35 |     let _ = ARR.make_container().do_something();
   |                                  ^^^^^^^^^^^^ multiple `do_something` found
   |
note: candidate #1 is defined in an impl for the type `Container<&'static _>`
  --> src/main.rs:6:5
   |
6  | /     fn do_something(&self) {
7  | |         println!("Container<&'a T>::do_something");
8  | |     }
   | |_____^
note: candidate #2 is defined in an impl for the type `Container<&mut _>`
  --> src/main.rs:12:5
   |
12 | /     fn do_something(&self) {
13 | |         println!("Container<&'a mut T>::do_something");
14 | |     }
   | |_____^
```

OK, we have conflicting impls for `Container<&'static _>` and `Container<&mut _>`, do we? Let's delete the one for `Container<&'static _>` then!
```
error[E0277]: the trait bound `&[(char, char)]: Issue<&mut _>` is not satisfied
  --> src/main.rs:35:17
   |
35 |     let _ = ARR.make_container().do_something();
   |                 ^^^^^^^^^^^^^^ the trait `Issue<&mut _>` is not implemented for `&[(char, char)]`
   |
   = help: the following implementations were found:
             <&'static [(char, T)] as Issue<&'static T>>
             <&'static [(char, char)] as Issue<()>>
```

I can open a new issue or rewrite the OP to focus on this issue directly if desired. If someone else wants to take a go at simplifying this repro down more, please do take a stab at it; I was unable to remove anything more while still reproing this behavior.

**Comment by CAD97** [comment]
Given that the inference issue is preexisting for this strange case and the regression is merely from expanding the available fn on `Option`, my vote is to release 1.22 as is, but to investigate this as an issue on its own right. #43705 merely opened another door to the preexisting inference issue.

**Comment by eddyb** [comment]
@arielb1 Could we use it *only* in case of ambiguity?

**Comment by arielb1** [comment]
@eddyb 

That would be fragile - a predicate-saatisfying method could still *shadow* a valid method.

**Comment by Mark-Simulacrum** [comment]
https://crates.io/crates/rabble v0.4.1 is broken by this, cc @andrewjstone

**Comment by andrewjstone** [comment]
I actually worked around this on a branch for rabble a few weeks ago but haven't merged it in. I will say, I didn't really understand what the problem was as I'm no expert in inference, but it was fixable in a hacky sort of way. https://github.com/andrewjstone/rabble/compare/histogram#diff-12d610bc541176e32ea0df8d15d0a369

**Comment by Mark-Simulacrum** [comment]
@aturon Do you want to look into this or should we just close it? Nothing is really going to change here I think since this is on stable anyway -- might be a bug in the compiler, though.

**Comment by Mark-Simulacrum** [comment]
I believe @arielb1 believes that this isn't really a bug, and that the cause is known. As such, I'm going to close. Please comment if that's not the correct conclusion to draw from the discussion above.

**Comment by dhardy** [comment]
I just tried to write the following, and it failed. Feels like a bug given the incorrect bound, but seems to be related to the story here. Shall I open a new report?
```rust
fn extract(x: &Option<u32>) -> u32 {
    x.cloned().unwrap_or_default()
}
```
Error:
```
error[E0599]: no method named `cloned` found for type `&std::option::Option<u32>` in the current scope
 --> src/main.rs:2:7
  |
2 |     x.cloned().unwrap_or_default()
  |       ^^^^^^
  |
  = note: the method `cloned` exists but the following trait bounds were not satisfied:
          `&mut &std::option::Option<u32> : std::iter::Iterator`
          `&mut std::option::Option<u32> : std::iter::Iterator`
```
