### PR TITLE
Do not inline finish_grow

### LINKED ISSUE #78471: Code bloat from RawVec::grow_amortized
The change in #72227 made non-PGO builds of Firefox's libxul.so's .text section grow by close to 1MB. libxul.so has a ~89MB section, which makes it a > 1% size increase in a library where about only 16% of the code is rust, which makes it a > 7% (!) increase in size. This comes from the fact that essentially all uses of Vec::push inline this all for some reason, and it's used all across the place.

### PR DESCRIPTION
**Pull request by glandium**
Fixes #78471.

Looking at libgkrust.a in Firefox, the sizes for the `gkrust.*.o` file is:
- 18584816 (text) 582418 (data) with unmodified master
- 17937659 (text) 582554 (data) with #72227 reverted
- 17968228 (text) 582858 (data) with `#[inline(never)]` on `grow_amortized` and `grow_exact`, but that has some performance consequences
- 17927760 (text) 582322 (data) with this change

So in terms of size, at least in the case of Firefox, this patch more than undoes the regression. I don't think it should affect performance, but we'll see.

### CODE REVIEW

**Comment by glandium** [comment]
If I look at libgkrust.a in Firefox, the `.text` size for the gkrust.*.o file is:
- 19118203 with current master
- 18402141 with #72227 reverted
- 18356853 with `#[inline(never)]` on `grow_amortized` and `grow_exact`
- 18337894 with this patch

So in terms of size, at least in the case of Firefox, this patch more than undoes the regression. I don't think it should affect performance, but we'll see.

**Comment by jyn514** [comment]
Would it make sense to instead mark `grow_amortized` and `grow_exact` as inline(never)?

**Comment by jyn514** [comment]
Oh I missed https://github.com/rust-lang/rust/pull/78483, sorry.

**Comment by gparker42** [comment]
This looks like the right inlining boundary as intended by @nnethercote. `finish_grow` deliberately handles as much type-independent work as possible, so a single copy could be shared by all `Vec` types.

#78471 reported `grow_amortized` being inlined all the way back into callers of `Vec::push`. @glandium, do you see that in your libgkrust.a? That sounds unprofitable - I'd expect the call to `RawVec::reserve` to be another inlining boundary - but I couldn't reproduce the reported aggressive inlining in my own small tests.

**Comment by glandium** [comment]
It may only happen with -Clto.

**Comment by gparker42** [comment]
Ah, that looks like it: I need both -Clto and a sufficiently large inline-threshold (larger than the opt-level=3 default).

Can you build your libgkrust.a with an inlining boundary at `RawVec::reserve`? That reduces the `Vec::push` inlined size to around ten instructions. (I'm still getting set up for code size experiments here.)

**Comment by glandium** [comment]
> Ah, that looks like it: I need both -Clto and a sufficiently large inline-threshold (larger than the opt-level=3 default).

It happens in Firefox with `-Clto -Copt-level=2`.

> Can you build your libgkrust.a with an inlining boundary at `RawVec::reserve`? That reduces the `Vec::push` inlined size to around ten instructions. (I'm still getting set up for code size experiments here.)

That would likely make things slower, similarly to #78483.

**Comment by gparker42** [comment]
> > Can you build your libgkrust.a with an inlining boundary at `RawVec::reserve`? That reduces the `Vec::push` inlined size to around ten instructions. (I'm still getting set up for code size experiments here.)
> 
> That would likely make things slower, similarly to #78483.

I'm betting that `reserve` can be a more profitable inlining boundary than `grow_amortized` was, but I'll tinker with that on my own.

**Comment by nnethercote** [comment]
> I'm betting that `reserve` can be a more profitable inlining boundary than `grow_amortized` was, but I'll tinker with that on my own.

I tried a number of things in and around `reserve`, results were sensitive and unpredictable and I couldn't get improvements.

This patch seems fine, though. I'm a little surprised I didn't never-inline `finish_grow` myself.

@bors r+

**Comment by glandium** [comment]
```
/checkout/src/test/codegen/vec-iter-collect-len.rs:9:16: error: CHECK-NOT: excluded string found in input
 // CHECK-NOT: call
               ^
/checkout/obj/build/i686-unknown-linux-gnu/test/codegen/vec-iter-collect-len/vec-iter-collect-len.ll:134:2: note: found here
 call void @llvm.lifetime.start.p0i8(i64 12, i8* nonnull %0)
 ^~~~
```

How can one work around that?

**Comment by jyn514** [comment]
```
$ git log --oneline src/test/codegen/vec-iter-collect-len.rs
2a663555ddf Remove licenses
1001b2beee5 inore some codegen tests when debug assertions are enabled
f67453729c1 std: Ensure OOM is classified as `nounwind`
$ git show f67453729c1 src/test/codegen/vec-iter-collect-len.rs
commit f67453729c19b435686c94936d8145051e7f1284
Author: Alex Crichton <alex@alexcrichton.com>
Date:   Thu May 24 12:03:05 2018 -0700

    std: Ensure OOM is classified as `nounwind`
    
    OOM can't unwind today, and historically it's been optimized as if it can't
    unwind. This accidentally regressed with recent changes to the OOM handler, so
    this commit adds in a codegen test to assert that everything gets optimized away
    after the OOM function is approrpiately classified as nounwind
    
    Closes #50925


added: src/test/codegen/vec-iter-collect-len.rs
────────────────────────────────────────────────────────────────────────────────────

1
// Copyright 2017 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

// no-system-llvm
// compile-flags: -O
#![crate_type="lib"]

#[no_mangle]
pub fn get_len() -> usize {
    // CHECK-LABEL: @get_len
    // CHECK-NOT: call
    // CHECK-NOT: invoke
    [1, 2, 3].iter().collect::<Vec<_>>().len()
}
```

@alexcrichton do you understand why this change could have broken the test?

**Comment by alexcrichton** [comment]
Sorry I don't really have much to add. Given that a function is inline(never) here though it's presumably being inlined in that test case and now it's not.

**Comment by glandium** [comment]
But the failure is not on calling the `inline(never)` function, it's on calling `@llvm.lifetime.start`

**Comment by glandium** [comment]
That said, now looking at the test, it would complain about the `inline(never)` function eventually. I'm not sure what this test is trying to do though...

**Comment by nagisa** [comment]
What the linked test is really testing is that `[1, 2, 3].iter().collect::<Vec<_>>().len()` optimises out the allocations and effectively produces just 3 in the assembly. This comes directly from the referenced issue report https://github.com/rust-lang/rust/issues/50925.

Now that some allocation-related function is no longer inlined, the LLVM is unable to see-through and optimize out the allocation to produce the [current assembly](https://rust.godbolt.org/z/x7aWWz). So its a genuine regression.

**Comment by glandium** [comment]
Trying a new version that still inlines the function into grow_exact, hoping that it will work around the issue.
Sizewise, with current mozilla-central, with, I think, a slightly different build config compared to earlier numbers, these are the numbers I'm getting for `.text` size of libgkrust.a:
- 18514308 with rustc master
- 17867395 with rustc master + #72227 reverted
- 17850670 with rustc master + this patch

So it does have a slightly less good result than the previous patch, but still covers more than the regression.

**Comment by jyn514** [comment]
Looks like this has some [semantic conflicts](https://bors.tech/essay/2017/02/02/pitch/) when rebased over master.

```
error[E0425]: cannot find function `finish_grow_never_inline` in this scope
   --> library/alloc/src/raw_vec.rs:428:19
    |
428 |           let ptr = finish_grow_never_inline(new_layout, self.current_memory(), &mut self.alloc)?;
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^ help: a function with a similar name exists: `finish_grow_never_inlined`
...
502 | / fn finish_grow_never_inlined<A>(
503 | |     new_layout: Result<Layout, LayoutErr>,
504 | |     current_memory: Option<(NonNull<u8>, Layout)>,
505 | |     alloc: &mut A,
...   |
510 | |     finish_grow(new_layout, current_memory, alloc)
511 | | }
    | |_- similarly named function `finish_grow_never_inlined` defined here

error[E0412]: cannot find type `LayoutErr` in this scope
   --> library/alloc/src/raw_vec.rs:503:32
    |
503 |     new_layout: Result<Layout, LayoutErr>,
    |                                ^^^^^^^^^
    | 
   ::: /checkout/library/core/src/alloc/layout.rs:408:1
    |
408 | pub struct LayoutError {
    | ---------------------- similarly named struct `LayoutError` defined here
```

**Comment by glandium** [comment]
> Looks like this has some semantic conflicts when rebased over master.

I had the changes locally, but forgot to commit --amend before pushing. Facepalm.

**Comment by jyn514** [comment]
Looks like most of the regressions are on `-doc` runs, which isn't a big deal.

**Comment by emilio** [comment]
So... should this land?

**Comment by glandium** [comment]
So the problem here seems to be that SpecFromIterNested for Vec on TrustedLen iterators uses spec_extend, which uses reserve, which uses grow_amortized. Which makes sense when extending an existing Vec... not necessarily when creating one.

**Comment by glandium** [comment]
Ironically, removing the specialization of SpecFromIterNested for TrustedLen iterators fixes it, because the default impl uses with_capacity, which just allocates directly.

**Comment by glandium** [comment]
The specialization comes from #70793. @the8472 do you have thoughts?

**Comment by the8472** [comment]
> Ironically, removing the specialization of SpecFromIterNested for TrustedLen iterators fixes it, because the default impl uses with_capacity, which just allocates directly.

That it does, but then it only writes the first item into the new vector and also delegates to `extend` which will then contain code to grow the vec if the size hint has been an underestimate. So both code paths should contain calls to `reserve`. Unless one gets optimized better than the other.

> The specialization comes from #70793.

Not quite, that particular specialization [did exist before my changes](https://github.com/rust-lang/rust/pull/70793/files#diff-b78c3ab6d37f4ede32195707528f8a76c49d4557cc9d3a7a09417b5157729b9fL2134-L2142) (you'll have to unfold the vec.rs diff first to jump to the marked lines). I only moved it around as part of implementing other specializations.

I believe the current implementation for `TrustedLen` uses `Vec::new()` + `extend` (which also has a specialization for `TrustedLen`) on the *assumption* that growing an empty vector is equivalent to using `with_capacity` because an empty vector is known to have capacity 0 and thus should optimize well.

If that is not the case then this specialization could be rewritten to use `with_capacity`, but `TrustedLen` docs say that it's allowed to return `(usize::MAX, None)` which we probably don't want to allocate? At least the `SpecExtend` specialization for `TrustedLen` does not try to do that and instead falls back to normal growth behavior.

**Comment by the8472** [comment]
To clarify, if you remove 

https://github.com/rust-lang/rust/blob/e6225434fff7d493baac0aa91c57f2da923ea196/library/alloc/src/vec.rs#L2325-L2336

but keep 

https://github.com/rust-lang/rust/blob/e6225434fff7d493baac0aa91c57f2da923ea196/library/alloc/src/vec.rs#L2296-L2323

then in the case of a `I: TrustedLen` it will *still* delegate to the following because both variants call `spec_extend`

https://github.com/rust-lang/rust/blob/e6225434fff7d493baac0aa91c57f2da923ea196/library/alloc/src/vec.rs#L2545-L2576

which also calls

https://github.com/rust-lang/rust/blob/e6225434fff7d493baac0aa91c57f2da923ea196/library/alloc/src/vec.rs#L2610-L2630


Which means this does *more* calls into the allocation and resize machinery, not fewer. So if this somehow generates less code then it might be due to changes in inlining or the generic variant somehow being easier to the optimize despite containing more code.

**Comment by the8472** [comment]
Maybe I misunderstood

> So the problem here seems to be that SpecFromIterNested for Vec on TrustedLen iterators uses spec_extend, which uses reserve, which uses grow_amortized. Which makes sense when extending an existing Vec... not necessarily when creating one.

Is this comment still about code size or about the perf results? If `with_capacity` performs better than `reserve` then it might be as easy as replacing `reserve` with `reserve_exact` in the `SpecExtend` implementation.

**Comment by glandium** [comment]
> Maybe I misunderstood
> 
> > So the problem here seems to be that SpecFromIterNested for Vec on TrustedLen iterators uses spec_extend, which uses reserve, which uses grow_amortized. Which makes sense when extending an existing Vec... not necessarily when creating one.
> 
> Is this comment still about code size or about the perf results? If `with_capacity` performs better than `reserve` then it might be as easy as replacing `reserve` with `reserve_exact` in the `SpecExtend` implementation.

The comment was specifically about performance, since the "fix" for the code size issue (which un-inlines finish_grow), breaks the test for collect().len() essentially optimizing down to just returning the length in some cases (involving TrustedLen).

The question, though, is whether SpecExtend should be using reserve_exact in all cases, and I suspect it shouldn't. That is, `Vec::extend`, run in sequence, should probably still use the amortized-growing strategy. So maybe the right tradeoff would be to reserve_exact instead of reserve when the length coming in is 0. But I could also see this having a perf impact on hot loops of `Vec::extend` because of the additional branch...

So it might make more sense to do it at the SpecFromIterNested::from_iter level for TrustedLen, which would essentially bring it on par with the default case, but without pulling from the iterator first and only if the size_hint comes with an upper-bound.

**Comment by glandium** [comment]
So, something like this:
```diff
--- a/library/alloc/src/vec.rs
+++ b/library/alloc/src/vec.rs
@@ -2103,7 +2103,10 @@ impl<T, I> SpecFromIterNested<T, I> for Vec<T>
     I: TrustedLen<Item = T>,
 {
     fn from_iter(iterator: I) -> Self {
-        let mut vector = Vec::new();
+        let mut vector = match iterator.size_hint() {
+            (_, Some(upper)) => Vec::with_capacity(upper),
+            _ => Vec::new(),
+        };
         // must delegate to spec_extend() since extend() itself delegates
         // to spec_from for empty Vecs
         vector.spec_extend(iterator);
```

**Comment by the8472** [comment]
Looks reasonable and should still optimize for the `collect().len()` case considering that the default implementation has similar branches.

**Comment by glandium** [comment]
FTR, I already validated that it still optimizes the `collect().len()` case from `vec-iter-collect-len.rs`.

**Comment by glandium** [comment]
Should we queue another round of perf tests for the SpecFromIterNested change?

**Comment by jyn514** [comment]
Wow, that is a really large savings in max-rss 🎉

**Comment by the8472** [comment]
max-rss is really noisy, compare to the noise run which shows similarly-sized fluctuations on other crates.

**Comment by lcnr** [comment]
i'm a bit out of the loop here, sry

It looks like it is fine to land this PR as is rn and I would be fine with landing if https://github.com/rust-lang/rust/pull/78682#issuecomment-720727189 is still up to date. It might even make sense to move that summary into the PR description so that it's added to the merge commit.

@bors delegate+

**Comment by glandium** [comment]
I'll get new numbers and paste them in the PR message. I've never used bors myself, do I @-it with "rollup" when I'm done?

**Comment by jyn514** [comment]
@glandium you would say `@bors r=lcnr rollup=never`. `rollup=always` is only for PRs that don't affect perf or are trivial, like fixing typos in comments.

**Comment by jyn514** [comment]
damn it bors

@bors r-
