### PR TITLE
Add test for the missing Clone requirement for Cow slices

### LINKED ISSUE #141241: Suboptimal diagnostic for `Cow<'static, [SomeType]>` if `SomeType` doesn't implement `Clone`
### Code

```Rust
use std::borrow::Cow;

struct A{}

struct B {
    test: Cow<'static, [A]>
    
}
```

### Current output

```Shell
error[E0277]: the trait bound `[A]: ToOwned` is not satisfied
   --> src/main.rs:6:11
    |
6   |     test: Cow<'static, [A]>
    |           ^^^^^^^^^^^^^^^^^ the trait `ToOwned` is not implemented for `[A]`
    |
    = help: the trait `ToOwned` is implemented for `[T]`
note: required by a bound in `Cow`
   --> /playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/borrow.rs:181:8
    |
179 | pub enum Cow<'a, B: ?Sized + 'a>
    |          --- required by a bound in this enum
180 | where
181 |     B: ToOwned,
    |        ^^^^^^^ required by this bound in `Cow`
```

### Desired output

```Shell
error[E0277]: the trait bound `A: Clone` is not satisfied
   --> src/main.rs:6:11
    |
6   |     test: Cow<'static, [A]>
    |           ^^^^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `A`
    |
    = help: consider adding a `#[derive(Clone)]` to `A`
note: required by a bound in `impl ToOwned for [A]`
note: required by a bound in `Cow`
   --> /playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/borrow.rs:181:8
    |
179 | pub enum Cow<'a, B: ?Sized + 'a>
    |          --- required by a bound in this enum
180 | where
181 |     B: ToOwned,
    |        ^^^^^^^ required by this bound in `Cow`
```

### Rationale and extra context

The error message is at the same time claiming that there is a `ToOwned` impl for `[T]`, while it suggests that this impl is missing. I needed to open the documentation to see that the existing impl is bound on `T: Clone`, it would be much better if the error message could mention that on it's own.

### Other cases

```Rust

```

### Rust Version

```Shell
Build using the Nightly version: 1.89.0-nightly

(2025-05-18 4d051fb306e661654d08)
```

### Anything else?

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=32d1974ef50688ff46111907ccd75fbb

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes rust-lang/rust#141241

### CODE REVIEW

**Review by jieyouxu — APPROVED** [review]
Thanks, r=me once PR CI is green.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/162619/9e9544da4cd757c74428bad35059cc8122fdcd7d..6581f4cb2b5a127e020770ac7c64418e509050fa)*
