### ISSUE TITLE
1.97 beta regression due to `TryFromIntError` changing size

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#157363]
This regression was found by the 1.97 beta crater run.

```
[INFO] [stdout] error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
[INFO] [stdout]   --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/ethnum-1.5.2/src/error.rs:16:14
[INFO] [stdout]    |
[INFO] [stdout] 16 |     unsafe { mem::transmute(()) }
[INFO] [stdout]    |              ^^^^^^^^^^^^^^
[INFO] [stdout]    |
[INFO] [stdout]    = note: source type: `()` (0 bits)
[INFO] [stdout]    = note: target type: `TryFromIntError` (8 bits)
```

It affects 230 dependents of `ethnum` version 1.5.2 or earlier. (`ethnum` version 1.5.3 was released on April 20 to fix this.)

* https://crater-reports.s3.amazonaws.com/beta-1.97-3-v2/1.97.0-beta.1/gh/Akash9900.flowdesk/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.97-3-v2/1.97.0-beta.1/gh/0rd1r3hv.algs4/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.97-3-v2/1.97.0-beta.1/gh/0xh3rman.sui-types/log.txt
* etc.

Presumably regressed in https://github.com/rust-lang/rust/pull/153178. cc @sorairolake, @tgross35

I assume this is acceptable breakage, but I'm filing this issue just in case some action is needed (e.g., a mention in the release notes).

**Comment by tgross35** [comment]
Opened an issue https://github.com/nlordell/ethnum-rs/issues/60.

We make no guarantees about the internals of std types (unless specified) so I'm not sure we need a release note mention. Maybe this type should have a constructor if other crates want to make use of it?

**Comment by theemathas** [comment]
@tgross ethnum is already fixed. This regression affects only dependents of older versions.

**Comment by nlordell** [comment]
This should have been fixed here: https://github.com/nlordell/ethnum-rs/pull/58 and released in 1.5.3.

**Comment by theemathas** [comment]
There's also another "regression" related to `TryFromIntError`. But this time, it's due to the `Debug` output changing:

```
[INFO] [stdout] note: panic did not contain expected string
[INFO] [stdout]       panic message: "index out of bounds: TryFromIntError(NegOverflow)"
[INFO] [stdout]  expected substring: "index out of bounds: TryFromIntError(())"
```

https://crater-reports.s3.amazonaws.com/beta-1.97-3-v2/1.97.0-beta.1/reg/univec-1.1.0/log.txt

---

Edit: Another crate had the same regression.

```
[INFO] [stdout] note: panic did not contain expected string
[INFO] [stdout]       panic message: "nanos_to_duration() overflowed seconds value for Duration: TryFromIntError(PosOverflow)"
[INFO] [stdout]  expected substring: "nanos_to_duration() overflowed seconds value for Duration: TryFromIntError(())"
```

https://crater-reports.s3.amazonaws.com/beta-1.97-3-v2/1.97.0-beta.1/reg/roundable-0.2.0/log.txt

---

Edit 2: Yet another crate.

```
[INFO] [stdout] note: panic did not contain expected string
[INFO] [stdout]       panic message: "called `Result::unwrap()` on an `Err` value: TryFromIntError(Zero)"
[INFO] [stdout]  expected substring: "called `Result::unwrap()` on an `Err` value: TryFromIntError(())"
```

https://crater-reports.s3.amazonaws.com/beta-1.97-3-v2/1.97.0-beta.1/gh/qter-project.puzzle-theory/log.txt

**Comment by cuviper** [comment]
https://doc.rust-lang.org/nightly/std/fmt/trait.Debug.html#stability
> Derived `Debug` formats are not stable, and so may change with future Rust versions. Additionally, `Debug` implementations of types provided by the standard library (`std`, `core`, `alloc`, etc.) are not stable, and may also change with future Rust versions.

**Comment by the8472** [comment]
We discussed this during today's T-libs meeting and consider this acceptable breakage.
