### PR TITLE
Fix fallout from #57667

### PR DESCRIPTION
**Pull request by ishitatsuyuki**
PR #57667 fixed a memory leak in `P::filter_map` (where `P` is the special pointer type used in the compiler's AST).

but @eddyb pointed out a bug in it: https://github.com/rust-lang/rust/pull/57667#discussion_r252219506

### CODE REVIEW

File: src/libsyntax/ptr.rs [hunk 1]
```diff
@@ -101,7 +102,9 @@ impl<T: 'static> P<T> {
                 // Recreate self from the raw pointer.
                 Some(P { ptr: Box::from_raw(p) })
             } else {
-                drop(Box::from_raw(p));
+                // Free the allocated memory only,
+                // do not drop T as it was ptr::read above.
+                drop(Box::from_raw(p as *mut ManuallyDrop<T>));
```
Comment (eddyb) [inline src/libsyntax/ptr.rs]: cc @RalfJung this is a clever trick I didn't consider!

**Comment by eddyb** [comment]
r=me if @RalfJung can confirm it's a correct approach

File: src/libsyntax/ptr.rs (hunk 1 above)
Comment (RalfJung) [reply src/libsyntax/ptr.rs]: Yeah I think this should work. I don't like the raw ptr cast though, it's so easy to get those wrong -- but I also don't know another way here.

**Comment by ishitatsuyuki** [comment]
Do you suggestions on alternatives to raw pointer cast? If not, I guess the code should be merged as-is.

**Comment by ollie27** [comment]
This might be a shot in the dark but would something like the following work (and deal with the FIXME):

```rust
pub fn filter_map<F>(self, f: F) -> Option<P<T>> where
    F: FnOnce(T) -> Option<T>,
{
    unsafe {
        // Transmute to `Box<MaybeUninit<T>>` so if `f` `panic`s or returns
        // `None` the `Box` will be freed but not the inner T.
        let mut maybe_box: Box<MaybeUninit<T>> = mem::transmute(self.ptr);
        let x = f(ptr::read(maybe_box.as_ptr()))?;
        maybe_box.set(x);
        Some(P { ptr: mem::transmute(maybe_box) })
    }
}
```

**Comment by ishitatsuyuki** [comment]
I think @ollie27's suggestion is pretty good, any opinions/alternatives regarding the use of transmute?

**Comment by RalfJung** [comment]
It seems to me that using `ManuallyDrop` instead of `MaybeUninit` is sufficient?

**Comment by ishitatsuyuki** [comment]
@RalfJung the snippet above uses MaybeUninit::set.

**Comment by ollie27** [comment]
I guess this would work:

```rust
pub fn filter_map<F>(self, f: F) -> Option<P<T>> where
    F: FnOnce(T) -> Option<T>,
{
    unsafe {
        // Transmute to `Box<ManuallyDrop<T>>` so if `f` `panic`s or returns
        // `None` the `Box` will be freed but not the inner T.
        let mut manaully_drop_box: Box<ManuallyDrop<T>> = mem::transmute(self.ptr);
        let x = f(ManuallyDrop::take(&mut manaully_drop_box))?;
        *manaully_drop_box = ManuallyDrop::new(x);
        Some(P { ptr: mem::transmute(manaully_drop_box) })
    }
}
```

**Comment by RalfJung** [comment]
Yeah, something like that.

Either way though I think it'd be good to avoid "open" `transmute` and use helper functions instead.  Turning `Box<MaybeUninit<T>>` into `Box<T>` should probably even become a stable (unsafe) operation some day.

**Comment by Dylan-DPC** [comment]
ping from triage @ishitatsuyuki @eddyb what's the update on this?

**Comment by RalfJung** [comment]
@ishitatsuyuki could you update this to one of the proposed panic-safe schemes? If not I can r+ this, because it is an improvement, but the other version is even better.

**Comment by ishitatsuyuki** [comment]
Actually I invented one that is drastically simpler, based on ManuallyDrop.

The pains are with the `Box<[T]>` methods. I know that the best way would be adding some methods to Box itself, but I'm not inclined to do that since that's not future-proof (a pre-RFC has been on internals, for example).

**Comment by RalfJung** [comment]
Not sure if I like changing `P` itself -- for once, didn't you forget to add a `impl Drop`?

But it seems like some local private conversion functions between `Box<T>` and `Box<ManuallyDrop<T>>` would help. Long-term we probably want something like this in libstd. (We also want that for `MaybeUninit`, this should probably be co-designed.)

**Comment by ishitatsuyuki** [comment]
I spent some effort and wrote things again. Hopefully this is what you wanted.

File: src/liballoc/boxed.rs [hunk 2]
```diff
@@ -270,6 +270,20 @@ impl<T: ?Sized> Box<T> {
         // additional requirements.
         unsafe { Pin::new_unchecked(boxed) }
     }
+
+    /// Converts a `Box<T>` into a `Box<ManuallyDrop<T>>`
+    #[unstable(feature = "box_manually_drop", issue = "0")]
```
Comment (RalfJung) [inline src/liballoc/boxed.rs]: I meant local helper functions in the `P` module... this also works but now you have to create a tracking issue and add it here.

File: src/libsyntax/ptr.rs [hunk 3]
```diff
@@ -63,45 +64,37 @@ impl<T: 'static> P<T> {
...
-        mem::forget(self);
+        // If a panic occurs in `f`, leak the inner T.
+        let mut manually_drop_box = Box::into_manually_drop(self.ptr);
 
         unsafe {
-            ptr::write(p, f(ptr::read(p)));
-
-            // Recreate self from the raw pointer.
-            P { ptr: Box::from_raw(p) }
+            let x = f(ManuallyDrop::take(&mut manually_drop_box));
```
Comment (RalfJung) [inline src/libsyntax/ptr.rs]: Can you use `into_inner` instead of `take`?

Comment (ishitatsuyuki) [reply src/libsyntax/ptr.rs]: I don't think so, that would reallocate (or at least consume) the Box which defeats the point of P.

**Comment by ishitatsuyuki** [comment]
I will do the tracking issue thing tomorrow.

File: src/libsyntax/ptr.rs (hunk 3 above)
Comment (RalfJung) [reply src/libsyntax/ptr.rs]: It would move out of the box and then later move back into it, why would it reallocate? [This code does not reallocate either](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=a69fa345f41e00d1428d83261e1e52fe).

**Comment by RalfJung** [comment]
@rust-lang/libs any advise on how to proceed here -- should we add two new unstable methods with a tracking issue, or instead add two local private helper functions in `syntax::ptr`?

File: src/libsyntax/ptr.rs (hunk 3 above)
Comment (SimonSapin) [reply src/libsyntax/ptr.rs]: Oh wow. `Box` turns out to be even more magical than I realized. In this playground example shows that not only we can move a value out of `Box` without a `DerefMove` trait, but the compiler tracks such moves like for local variables and plain struct fields. Attempting to use the box before its contents are reassigned (if `*x = …` is removed) results in a compile time ``error[E0382]: use of moved value: `x` ``. But the box is still there and can be used again after its contents are reassigned.

And this is panic-safe too. In the assembly for https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=d4907435865f18159268fc36a8546016 we see that `foo` calls `box_free` but not `drop_t`.

So I think @RalfJung’s suggestion is the way to go.

**Comment by SimonSapin** [comment]
Per https://github.com/rust-lang/rust/pull/58021#discussion_r262855968 it looks like the one use case for those methods can be solved with plain `Box<T>` without `ManuallyDrop`. Unless there’s another use case, let’s not add public APIs.

**Comment by RalfJung** [comment]
I hadn't even thought so far, but you are right... this proper move tracking for boxes entirely sidesteps the need for `ManuallyDrop`. We can even write these methods in safe code.

File: src/libsyntax/ptr.rs (hunk 3 above)
Comment (SimonSapin) [reply src/libsyntax/ptr.rs]: Bonus possibly-unexpected detail:

https://github.com/rust-lang/rust/blob/f22dca0a1bef4141e75326caacc3cd59f3d5be8e/src/liballoc/boxed.rs#L290-L295

**Comment by ishitatsuyuki** [comment]
(Short on time this week, will update this weekend)

**Comment by ishitatsuyuki** [comment]
Done, thanks for all your help!

**Comment by RalfJung** [comment]
Thank you for your contribution!

@bors r+

**Comment by RalfJung** [comment]
@rust-lang/libs this fixes a double-drop bug introduced by https://github.com/rust-lang/rust/pull/57667, should we backport?

**Comment by SimonSapin** [comment]
#57667 landed on 2018-01-22 so it looks like it is present in 1.34, currently in beta. Nominating.

**Comment by RalfJung** [comment]
A panic in the collection tests on android? @rust-lang/infra doesn't look like it could be caused by this PR, does it?

**Comment by Mark-Simulacrum** [comment]
No this is a spurious failure (panicking during tests on Android sometimes leads to a segfault).

@bors retry

**Comment by RalfJung** [comment]
Timeout. @bors retry

File: src/libsyntax/ptr.rs (hunk 3 above)
Comment (eddyb) [reply src/libsyntax/ptr.rs]: Wow, I was aware of `Box` special-casing, but I do not recall being able to reinitialize the `Box` and reuse it!

@nikomatsakis @pnkfelix Do you happen to know when that might've happened?

Comment (nikomatsakis) [reply src/libsyntax/ptr.rs]: I believe this probably happened as part of the NLL transition. We decided to stop hobbling the treatment of `Box` during that discussion.

**Comment by pnkfelix** [comment]
Discussed in this week's T-compiler meeting. Approved for beta-backport.

(In parallel, @pnkfelix wants to make a regression test. But than need not hold up the backport.)

**Comment by pnkfelix** [comment]
> (In parallel, @pnkfelix wants to make a regression test. But than need not hold up the backport.)

I was careless and misread the patch, thinking that this was some `fn map` and `fn filter_map` in `libstd`; but that wasn't true at all, its in `libsyntax`. I'm not going to worry about a regression test.
