### ISSUE TITLE
Static cyclic references not compiled in current nightly rust version

### ISSUE THREAD

**Issue by chabapok** [rust-lang/rust#62189]
Let's tying to compile this code.This code compiled ok on stable and on nightly-2019-06-17 (for example at rust play site)

```
struct Foo {
    foo: Option<&'static Foo>
}

static FOO: Foo = Foo {
    foo: Some(&FOO),
};

fn main() {
    println!("Hello, world!");
}
```

But in current  rustc 1.37.0-nightly (d3e2cec29 2019-06-26) compilation fails with message:

```
error[E0391]: cycle detected when const-evaluating `FOO`
 --> src/main.rs:6:1
  |
6 | static FOO: Foo = Foo {
  | ^^^^^^^^^^^^^^^^^^^^^
  |
note: ...which requires const-evaluating `FOO`...
 --> src/main.rs:6:1
  |
6 | static FOO: Foo = Foo {
  | ^^^^^^^^^^^^^^^^^^^^^
  = note: ...which again requires const-evaluating `FOO`, completing the cycle
note: cycle used when const-evaluating + checking `FOO`
 --> src/main.rs:6:1
  |
6 | static FOO: Foo = Foo {
  | ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0391`.
```

**Comment by wesleywiser** [comment]
Bisected to:

- `nightly-2019-06-19` Ok
- `nightly-2019-06-20` Fail

04a3dd8a8...2fe7b3383

**Comment by cuviper** [comment]
I bisected to #58351, which is also part of the range @wesleywiser identified. I get build failures when I try to bisect further into the commits of that PR. cc @oli-obk @RalfJung

**Comment by oli-obk** [comment]
Hmm curious, we do have tests for such situations. I'll investigate, but it'll drop into beta today. It's probably an easy fix

**Comment by RalfJung** [comment]
> it'll drop into beta today

Today? Beta cutoff is on Tuesday.

**Comment by oli-obk** [comment]
Not this time I believe

**Comment by wesleywiser** [comment]
Beta cutoff is 2019-06-29 https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/stable.20release/near/168974542

**Comment by pnkfelix** [comment]
triage: P-high, remove nomination, assign to @oli-obk

**Comment by RalfJung** [comment]
FYI, Oli is on vacation for 2 weeks.

**Comment by RalfJung** [comment]
Should this be marked regression-from-stable-to-beta now?
