### ISSUE TITLE
Asymmetric "overflow evaluating the requirement" error with associated type constraint

### ISSUE THREAD

**Issue by tavianator** [rust-lang/rust#72098]
This code gives an error:

```rust
trait Foo {
    type Bar;
}

trait Baz<T: ?Sized + Foo>: Foo<Bar = T::Bar> {}

trait Qux: Baz<Self> {}
```

```
error[E0275]: overflow evaluating the requirement `<Self as Foo>::Bar`
 --> foo.rs:7:1
  |
7 | trait Qux: Baz<Self> {}
  | ^^^^^^^^^^^^^^^^^^^^^^^
```

Yet, moving the constraint to `T` instead of `Self` works fine:

```rust
trait Baz<T: ?Sized + Foo<Bar = <Self as Foo>::Bar>>: Foo {}
```

Since `T = Self` in the context of `Qux`, it's surprising this makes a difference.

### Meta

`rustc --version --verbose`:
```
rustc 1.45.0-nightly (7ebd87a7a 2020-05-08)
```

**Comment by tavianator** [comment]
It seems like this worked in Rust 1.3.0, but has been broken since 1.4.0

**Comment by camelid** [comment]
Assigning `P-medium` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2372098.20Asymmetric.20.22overflow.20evaluating.20the.20req.E2.80.A6) in the prioritization working group.
