### ISSUE TITLE
ipnetwork-0.12.1 doesn't build on 1.16 beta

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#39807]
```
   Doc-tests ipnetwork

running 11 tests
test IpNetwork::ip_0 ... FAILED
test IpNetwork::prefix_0 ... ok
test ipv4::Ipv4Network::contains_0 ... ok
test ipv4::Ipv4Network::broadcast_0 ... ok
test ipv4::Ipv4Network::mask_0 ... ok
test ipv4::Ipv4Network::network_0 ... ok
test ipv4::Ipv4Network::size_0 ... ok
test ipv4::Ipv4Network::nth_0 ... ok
test ipv4::Ipv4Network_0 ... ok
test ipv6::Ipv6Network::contains_0 ... ok
test ipv6::Ipv6Network::mask_0 ... ok

failures:

---- IpNetwork::ip_0 stdout ----
        error[E0284]: type annotations required: cannot resolve `<_ as std::str::FromStr>::Err == _`
 --> <anon>:6:77
  |
6 | assert_eq!(IpNetwork::V4("10.9.0.32/16".parse().unwrap()).ip(), "10.9.0.32".parse().unwrap());
  |                                                                             ^^^^^

error: aborting due to previous error(s)

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/session/mod.rs:203
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    IpNetwork::ip_0

test result: FAILED. 10 passed; 1 failed; 0 ignored; 0 measured

error: test failed
```

Works on 1.15.

cc @achanda

**Comment by nagisa** [comment]
There has been a large number of `From` implementations around the `IpAddr`/`Ipv4Addr`/`Ipv6Addr`/`SocketAddr`. Those are likely the reason this code does not compile anymore and such breakage is not considered a breaking change.

Actionable items: send a PR to the crate or inform the crate author via an issue.

**Comment by arielb1** [comment]
Looks like XIB (aka expected inference breakage). Assigning to T-libs.

**Comment by alexcrichton** [comment]
I believe this is a dupe of https://github.com/rust-lang/rust/issues/39825, caused by https://github.com/rust-lang/rust/pull/38464, so closing in favor of #39825.
