### ISSUE TITLE
Tonic master branch builds on 1.52 but not 1.51

### ISSUE THREAD

**Issue by davidpdrsn** [rust-lang/rust#85659]
I recently worked on some changes to [tonic](https://github.com/hyperium/tonic). The changes work fine on Rust 1.52 (the version I was on when I wrote the changes) but I've since discovered that things don't compile on Rust 1.51. I see an error like this:

```
error[E0391]: cycle detected when computing the bounds for type parameter `T`
   --> /Users/david.pedersen/dev/major/tonic/target/debug/build/tonic-reflection-8e8e4b3f5942cb14/out/grpc.reflection.v1alpha.rs:185:43
    |
185 |                 Response = http::Response<T::ResponseBody>,
    |                                           ^^^^^^^^^^^^^^^
    |
    = note: ...which again requires computing the bounds for type parameter `T`, completing the cycle
note: cycle used when computing explicit predicates of `proto::server_reflection_client::<impl at /Users/david.pedersen/dev/major/tonic/target/debug/build/tonic-reflection-8e8e4b3f5942cb14/out/grpc.reflection.v1alpha.rs:166:5: 215:6>::with_interceptor`
   --> /Users/david.pedersen/dev/major/tonic/target/debug/build/tonic-reflection-8e8e4b3f5942cb14/out/grpc.reflection.v1alpha.rs:185:43
    |
185 |                 Response = http::Response<T::ResponseBody>,
```

I'm not knowingly doing anything that requires Rust 1.52 so find this error a bit surprising. Could it be a bug in rustc?

Reproduction:

```
$ git clone https://github.com/hyperium/tonic.git
$ cd tonic
$ cargo +1.51 check -p examples
```

I expected to see this happen: Things should build on 1.51 as well as 1.52.

Instead, this happened: Doesn't build on 1.51, does build on 1.52.

**Comment by hellow554** [comment]
FWIW: here's a bisect:

searched nightlies: from nightly-2020-10-01 to nightly-2021-05-01
regressed nightly: nightly-2021-02-10
searched commits: from https://github.com/rust-lang/rust/commit/0fc6756b42e0556cc2e18079f5fc6b4d58f4e81a to https://github.com/rust-lang/rust/commit/097bc6a84f2280a889b9ab4b544f27851a978927
regressed commit: https://github.com/rust-lang/rust/commit/f4008fe94935d05ffb3a48fc5b7149070bb45550

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --end=2021-05-01 --access=github --regress=non-error
```
</details>

Probably https://github.com/rust-lang/rust/pull/80732 allows this code to compile

**Comment by jyn514** [comment]
@davidpdrsn releases are immutable, and I've never heard of doing a point release for anything other than stable. So I'm not sure what the point of this issue is even if it is a bugfix.

**Comment by Mark-Simulacrum** [comment]
We don't support non-current stable versions, so as this works on 1.52 (and presumably beta/nightly) I'll go ahead and close.

**Comment by davidpdrsn** [comment]
In case anyone is interested this was the fix https://github.com/hyperium/tonic/pull/669
