### PR TITLE
Add EmbeddedBook to test list in bootstrap

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
r? @alexcrichton

### CODE REVIEW

**Comment by oli-obk** [comment]
how did this PR break clippy!?

@rust-lang/infra any ideas

**Comment by phansch** [comment]
I think toolstate commented on the wrong PR here?

The [build log](https://api.travis-ci.com/v3/job/176586176/log.txt) says: 

```
[01:19:05] [0m[1m[38;5;9merror[E0004][0m[0m[1m: non-exhaustive patterns: `ConstParam(_)` not covered
```

which was introduced in https://github.com/rust-lang/rust/pull/58191. But that PR doesn't have a toolstate comment.

**Comment by Mark-Simulacrum** [comment]
This PR made toolstate work (do *anything*) after it broke when the embedded book was first added
