### PR TITLE
[mir] Special treatment for dereferencing a borrow to a static definition

### LINKED ISSUE #70584: regression - temporary value dropped while borrowed with static slice (as used by rust-phf)
The below code compiles in 1.40.0 but not in 1.42.0 (stable). (minimized example from rust-phf)

```rust
pub enum Slice<T: 'static> {
    Static(&'static [T]),
}

pub struct Map<K: 'static, V: 'static> {
    pub entries: Slice<(K, V)>,
}

static CONTENT : & 'static [ u8 ] = b"a";

pub static CONTENT_MAP: Map<&'static str, &'static [u8]> = {
    Map {
        entries: Slice::Static(&[
            ("content", CONTENT),
        ]),
    }
};
```

When built in 1.42.0, it produces the following error:

```shell
error[E0716]: temporary value dropped while borrowed
  --> src/lib.rs:13:33
   |
13 |            entries: Slice::Static(&[
   |   ________________________________-^
   |  |________________________________|
   | ||
14 | ||             ("content", CONTENT),
15 | ||         ]),
   | ||         ^
   | ||_________|
   | |__________creates a temporary which is freed while still in use
   |            cast requires that borrow lasts for `'static`
16 |        }
17 |    };
   |    - temporary value is freed at the end of this statement
```

The same error occurs using nightly.

There's an issue from January mentioning this build error on the rust-phf repo (seems to occur in 1.41.0+), but no followup discussion/work that I could find. https://github.com/sfackler/rust-phf/issues/187

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
Fix #70584.

As suggested by @oli-obk in this [comment](https://github.com/rust-lang/rust/issues/70584#issuecomment-626009260), one can chase the definition of the local variable being de-referenced and check if it is a true static variable. If that is the case, `validate_place` will admit the promotion.

This is my first time to contribute to `rustc`, and I have two questions.
1. A generalization to some extent is applied to decide if the promotion is possible in the static context. In case that there are more projection operations preceding the de-referencing, `validate_place` recursively decent into inner projection operations. I have put thoughts into its correctness but I am not totally sure about it.
2. I have a hard time to find a good place for the test case. This patch has to do with MIR, but this test case would look out of place compared to other tests in `src/test/ui/mir` or `src/test/ui/borrowck` because it does not generate errors while others do. It is tentatively placed in `src/test/ui/statics` for now.

Thank you for any comments and suggestions!

### CODE REVIEW

File: src/librustc_mir/transform/promote_consts.rs [hunk 1]
```diff
@@ -502,9 +502,33 @@ impl<'tcx> Validator<'_, 'tcx> {
     fn validate_place(&self, place: PlaceRef<'tcx>) -> Result<(), Unpromotable> {
         match place {
             PlaceRef { local, projection: [] } => self.validate_local(local),
-            PlaceRef { local: _, projection: [proj_base @ .., elem] } => {
+            PlaceRef { local, projection: [proj_base @ .., elem] } => {
                 match *elem {
-                    ProjectionElem::Deref | ProjectionElem::Downcast(..) => {
+                    ProjectionElem::Deref => {
```
Comment (oli-obk) [inline src/librustc_mir/transform/promote_consts.rs:507]: Theoretically this `place` may be `*some_local.field`, where the projection is `[.field, *]`. In that case simply grabbing the `local` and reading its value won't be correct. While `check_static_ptr` requires the constant to be just a pointer, `struct Foo { field: &'static i32 }` would also be represented as just a pointer. So I think there should be an additional `proj_base.is_empty()` check. Since currently no MIR can get built that contains something like that, you can just `assert!(proj_base.is_empty())` after the `check_static_ptr` check. Please leave a comment with the above reasoning there so we can figure out the logic again in the future.

File: src/librustc_mir/transform/promote_consts.rs [hunk 2]
```diff
@@ -502,9 +502,33 @@ impl<'tcx> Validator<'_, 'tcx> {
...
+                        let mut not_promotable = true;
+                        if let TempState::Defined { location, .. } = self.temps[local] {
```
Comment (oli-obk) [inline src/librustc_mir/transform/promote_consts.rs:509]: leave a comment here stating that dereferencing a reference to a static this way can only get generated from a direct access which is essentially `*&STATIC`, so we should just allow it.

**Review by oli-obk — COMMENTED** [review]
cc @rust-lang/wg-mir-opt this PR uses `self.temps[local]`, similarly to how we treat reborrows (`&*foo` if `foo` is a reference). I believe this is preferrable to the other possible solutions, namely:

* optimizing the MIR before promotion (and thus borrowck!) to convert `*FOO` to `BAR` where `const FOO: &'static T = &BAR;`. While I believe this optimization is strictly correct, doing such optimizations before borrowck seems dangerous
* changing MIR building to not emit those constants. This is very hard, because when building the MIR for a `BAR` access, we don't know whether it's going to be for a reference or for a read.

**Comment by oli-obk** [comment]
> * A generalization to some extent is applied to decide if the promotion is possible in the static context. In case that there are more projection operations preceding the de-referencing, `validate_place` recursively decent into inner projection operations. I have put thoughts into its correctness but I am not totally sure about it.

I commented on this directly in the diff. I don't believe any problematic situations can occur today, but better safe than sorry.

> * I have a hard time to find a good place for the test case. This patch has to do with MIR, but this test case would look out of place compared to other tests in `src/test/ui/mir` or `src/test/ui/borrowck` because it does not generate errors while others do. It is tentatively placed in `src/test/ui/statics` for now.

That's a good place. We have loads of tests that do not emit errors. Since this is about promotion it could also live in `src/test/ui/consts`, but as this issue is specifically about statics, let's leave the test where you put it.

File: src/librustc_mir/transform/promote_consts.rs (hunk 1 above)
Comment (dingxiangfei2009) [reply src/librustc_mir/transform/promote_consts.rs:507]: Using `assert!` may lead to unnecessary panicking in the compiler, so I opt for simply checking this case and preventing the promotion.

Comment (oli-obk) [reply src/librustc_mir/transform/promote_consts.rs:507]: Well... if the compiler is buggy, we'd like to know ;) Right now there's no way that assertion could ever trigger that I can think of.

Comment (dingxiangfei2009) [reply src/librustc_mir/transform/promote_consts.rs:507]: I see. I found a test case that fails the assertion. It is `ui/consts/static-raw-pointer-interning.rs`. For convenience, I just post it here, with simplification so that MIR is reasonably readable.
```rust
static FOO: Foo = Foo {
    field: &42 as *const i32,
};

struct Foo {
    field: *const i32,
}

unsafe impl Sync for Foo {}

fn main() {
    let _ = unsafe { *FOO.field };
}
```
And the produced MIR is the following.
```
// MIR for `main` 0 mir_map

fn main() -> () {
    let mut _0: ();                      // return place in scope 0 at example4.rs:11:11: 11:11
    let mut _1: i32;                     // in scope 0 at example4.rs:12:13: 12:34
    let mut _2: &Foo;                    // in scope 0 at example4.rs:12:23: 12:26
    scope 1 {
    }
    scope 2 {
    }

    bb0: {
        StorageLive(_1);                 // scope 0 at example4.rs:12:13: 12:34
        StorageLive(_2);                 // scope 2 at example4.rs:12:23: 12:26
        _2 = const {alloc0: &Foo};       // scope 2 at example4.rs:12:23: 12:26
                                         // ty::Const
                                         // + ty: &Foo
                                         // + val: Value(Scalar(alloc0))
                                         // mir::Constant
                                         // + span: example4.rs:12:23: 12:26
                                         // + literal: Const { ty: &Foo, val: Value(Scalar(alloc0)) }
        _1 = (*((*_2).0: *const i32));   // scope 2 at example4.rs:12:22: 12:32
        StorageDead(_2);                 // scope 0 at example4.rs:12:34: 12:35
        StorageDead(_1);                 // scope 0 at example4.rs:12:34: 12:35
        _0 = const ();                   // scope 0 at example4.rs:11:11: 13:2
                                         // ty::Const
                                         // + ty: ()
                                         // + val: Value(Scalar(<ZST>))
                                         // mir::Constant
                                         // + span: example4.rs:11:11: 13:2
                                         // + literal: Const { ty: (), val: Value(Scalar(<ZST>)) }
        goto -> bb2;                     // scope 0 at example4.rs:13:2: 13:2
    }

    bb1 (cleanup): {
        resume;                          // scope 0 at example4.rs:11:1: 13:2
    }

    bb2: {
        return;                          // scope 0 at example4.rs:13:2: 13:2
    }
}

alloc0 (static: FOO, size: 8, align: 8) {
    ╾───────alloc3────────╼                         │ ╾──────╼
}

alloc3 (size: 4, align: 4) {
    2a 00 00 00                                     │ *...
}
```
The statement of index `3` in the `bb0` block triggers the assertion. You may see that there is a nested record field access.

Comment (oli-obk) [reply src/librustc_mir/transform/promote_consts.rs:507]: Ah, ok. That makes sense actually, so... I guess we need an additional test for

```rust
pub struct Slice(&'static [i32]);

static CONTENT: i32 = 42;
pub static CONTENT_MAP: Slice = Slice(&[CONTENT]);

pub static FOO: (i32, i32) = (42, 43);
pub static CONTENT_MAP2: Slice = Slice(&[FOO.0]);
```

Comment (oli-obk) [reply src/librustc_mir/transform/promote_consts.rs:507]: In that case, I think we're testing the wrong projection. We're testing the last projection, but we need to check the first one. So you need a runtime check for `proj_base.is_empty()` as you described

File: src/test/ui/statics/static-promotion.rs [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+
+// Use of global static variables in literal values should be allowed for
+// promotion.
+// This test is to demonstrate the issue raised in
+// https://github.com/rust-lang/rust/issues/70584
+
+// Literal values were previously promoted into local static values when
+// other global static variables are used.
+
+struct A<T: 'static>(&'static T);
```
Comment (oli-obk) [inline src/test/ui/statics/static-promotion.rs:11]: This test does not actually test the thing you're trying to test. Your test passes on the playground

Comment (dingxiangfei2009) [reply src/test/ui/statics/static-promotion.rs:11]: Sorry, I pasted the wrong test case from the playground. :sweat:

Comment (oli-obk) [reply src/test/ui/statics/static-promotion.rs:11]: no worries

**Comment by oli-obk** [comment]
@bors r+

Thanks!

**Comment by oli-obk** [comment]
cc @rust-lang/wg-const-eval  (sorry for the late ping). This PR undoes a regression in implicit promotion within static items

**Comment by RalfJung** [comment]
Ah I guess this is fallout from making pointers-to-statics into const pointer literals? Is there anything else that this promotes now that used to not get promoted?

**Comment by oli-obk** [comment]
no, this just reverts that regression, it doesn't promote more things than were promoted before the regression was introduced
