### ISSUE TITLE
[generic_const_exprs] [nightly] Unable to unify a const generic expression with its value

### ISSUE THREAD

**Issue by devcexx** [rust-lang/rust#153393]
### Code

Hi all,

I was doing some Rust using the incomplete generic_const_exprs feature in an old compiler nightly compiler and, when I tried to update to the latest nightly version, it looks like some behavior have changed, that I consider a regression.

This code used to compile in rustc 1.89.0-nightly (2eef47813 2025-05-22):

I tried this code:

```rust
#![feature(generic_const_exprs)]
#![allow(incomplete_features)]

pub trait MyTrait {
    const N: usize;

    fn do_something(&mut self) -> [u32; Self::N];
}

pub struct MyStruct<A> {
    _phantom: core::marker::PhantomData<A>,
}

impl<A> MyTrait for MyStruct<A> {
    const N: usize = 1;

    fn do_something(&mut self) -> [u32; Self::N] {
        [1]
    }
}
```

This code stopped compiling on rustc 1.89.0-nightly (3e674b06b 2025-05-23), and the error still happening on the latest nightly compiler (rustc 1.96.0-nightly (d9563937f 2026-03-03), failing to compile with the following error:

```rust
error[E0308]: mismatched types
  --> src/lib.rs:18:9
   |
18 |         [1]
   |         ^^^ expected `Self::N`, found `1`
   |
   = note: expected constant `Self::N`
              found constant `1`
```

It looks like the new compiler is refusing to unify the value 1 with Self::N, even though the current impl does state that N = 1. Additionally, this wouldn't work either in the broken rustc versions:

```rust
[...]

impl<A> MyTrait for MyStruct<A> {
    const N: usize = 1;

    fn do_something(&mut self) -> [u32; 1] {
        [1]
    }
}
```
_(Note the change in the do_something function signature)_

This will fail with the following error, and presumably for the same reasons:

```rust
error[E0308]: method not compatible with trait
  --> src/lib.rs:17:5
   |
17 |     fn do_something(&mut self) -> [u32; 1] {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Self::N`, found `1`
   |
   = note: expected constant `Self::N`
              found constant `1`
```

However, if we remove the generic type `A` from the struct definition, it will compile on any of the aforementioned rustc versions:

```rust
#![feature(generic_const_exprs)]
#![allow(incomplete_features)]

pub trait MyTrait {
    const N: usize;

    fn do_something(&mut self) -> [u32; Self::N];
}

pub struct MyStruct {
    _unused: u32
}

impl MyTrait for MyStruct {
    const N: usize = 1;

    fn do_something(&mut self) -> [u32; Self::N] {
        [1]
    }
}
```

I would consider this a regression, and I will appreciate someone taking a look into this. Thanks in advance!
