### ISSUE TITLE
"Private trait in public interface warning" changes to error when an unrelated pub(crate) is present

### ISSUE THREAD

**Issue by SimonAdameit** [rust-lang/rust#89857]
Implementing a public trait for all types that implement a private trait emits a warning. However the presence of `pub(crate)` in an unrelated piece of code turns that warning into an error.

The warning is: ```warning: private trait `PrivateTrait` in public interface (error E0445)```
The error is: ```error[E0445]: private trait `PrivateTrait` in public interface```

The behaviour can be reproduced by commenting out `pub(crate) struct Foo` in this code:

```rust
trait PrivateTrait {}

pub trait PublicTrait {}

impl<T> PublicTrait for T where T: PrivateTrait {}


/*
Comment this out and the error is gone and the code compiles with a warning
*/
pub(crate) struct Foo;
```

### Meta

I confirmed the presence of this behaviour on the rust playground for:
- Stable channel
  Build using the Stable version: 1.55.0

- Beta channel
Build using the Beta version: 1.56.0-beta.4
(2021-10-04 e6e620e1c7e7257babdf)

- Nightly channel
Build using the Nightly version: 1.57.0-nightly
(2021-10-12 d7c97a02d1215e4ef26c)

### References

- This issue might be related: https://github.com/rust-lang/rust/issues/59090
- @vickenty found [this code](https://github.com/rust-lang/rust/blob/eeb16a2a892c2a29b1da3085e29f39efa3486e1c/compiler/rustc_privacy/src/lib.rs#L1891-L1910) in the compiler that might be the cause

**Comment by Dylan-DPC** [comment]
This code now compiles fine without the error.
