### ISSUE TITLE
lifetime bound not satisfied for a lending iterator (using generic associated types) with `for_each` method

### ISSUE THREAD

**Issue by Imberflur** [rust-lang/rust#91693]
I'm trying to write a streaming/lending iterator trait using the nightly `generic_associated_types` feature (i.e. in the vein outlined [here](https://blog.rust-lang.org/2021/08/03/GATs-stabilization-push.html)), in particular with a `for_each` method:

```rust
#![feature(generic_associated_types)]

pub trait LendingIterator {
    type Item<'a> where Self: 'a;
    fn next(&mut self) -> Option<Self::Item<'_>>;

    fn for_each<F>(mut self, mut f: F)
    where
        Self: Sized,
        F: FnMut(Self::Item<'_>),
    {
        while let Some(item) = self.next() {
            f(item)
        }
    }
}
```

However, the lifetime bounds don't appear to be satisfied for calling the `for_each` method  when `Self` contains non `'static` lifetimes:

```rust
pub struct Mutator<T>(T);

impl<T> LendingIterator for Mutator<T> {
    type Item<'a> where Self: 'a = &'a mut T;
    fn next(&mut self) -> Option<Self::Item<'_>> {
        Some(&mut self.0)
    }
}

pub fn bar<T>(m: Mutator<T>) {
    m.for_each(|_: &mut T| {});
}

pub fn foo<'m>(m: Mutator<&'m i32>) {
    m.for_each(|_: &mut &'m i32| {});
}
```
```
   Compiling playground v0.0.1 (/playground)
error[E0311]: the parameter type `T` may not live long enough
  --> src/lib.rs:28:7
   |
27 | pub fn bar<T>(m: Mutator<T>) {
   |            - help: consider adding an explicit lifetime bound...: `T: 'a`
28 |     m.for_each(|_: &mut T| {});
   |       ^^^^^^^^ ...so that the type `Mutator<T>` will meet its required lifetime bounds

error[E0477]: the type `Mutator<&i32>` does not fulfill the required lifetime
  --> src/lib.rs:32:7
   |
32 |     m.for_each(|_: &mut &'m i32| {});
   |       ^^^^^^^^

For more information about this error, try `rustc --explain E0477`.
error: could not compile `playground` due to 2 previous errors
```
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=3387851fbe49465476bcd7829dc2737f)

I think I would expect `'a` be constrained to not outlive `Self` rather than requiring `Self` outlive any particular `'a`. I could be missing something though.

It appears to be triggered by the inclusion of the closure parameter with its impilcit HRTB
So potentially this issue is related to https://github.com/rust-lang/rust/issues/88460

[forum discussion](https://users.rust-lang.org/t/gat-iterator-with-for-each-function/68396)

### Meta
Version tested with on the playground:
```
Nightly channel
Build using the Nightly version: 1.59.0-nightly
(2021-12-07 0b6f079e4987ded15c13)
```

**Comment by jackh726** [comment]
I think this is a known issue (iterator adapters don't play well with GATs atm), likely related to the leak check and universes work. Any fix here is probably going to be very involved.

**Comment by jackh726** [comment]
GATs issue triage: not blocking. This needs some work with Polonius, I think. But not backwards-incompatible.

**Comment by nikomatsakis** [comment]
Hi all. @jackh726  and I have read though this thread and discussed the concerns being raised. I wanted to write a comment that just tries to summarize the concerns to make sure that I'm not missing anything; I also would like to write a (separate) comment summarizing some of the other points that have been raised on the thread in the other direction.

### Core concerns

I believe there are a few fundamental concerns:

* GATs are useful but the current state is too rough and should not be stabilized (exemplified by [this comment by @burntsushi](https://github.com/rust-lang/rust/pull/96709#issuecomment-1118627760))
* GATs are too complex and don't carry their weight; we should just use them as an implementation detail (exemplified by [this comment by @nrc](https://github.com/rust-lang/rust/pull/96709#issuecomment-1118275010))
* Given the number of papercuts, how do we know that GATs will land us somewhere usable? (latent in nrc and burntsushi's comments)

Before going further, a question: **Are there are other concerns that don't fall under one of these headings?**

(One important point: I have not yet had time to read [Sabrina Jewson's post](https://sabrinajewson.org/blog/the-better-alternative-to-lifetime-gats) -- I will try to do that later today -- perhaps it adds some new concerns to what is found here.)

### GATs are useful but the current state is too rough and should not be stabilized

@BurntSushi points out that GATs in their current form have some pretty severe limitations. These limitations block one of the most compelling use cases, lending iterators, and fixing that will require polonius (c.f. [#92985](https://github.com/rust-lang/rust/issues/92985)). Worse, these limitations are hard to convey to users: things just kind of randomly don't work, and it's not obvious that this is the compiler's fault (this is kind of a "worst case" for learnability, since it can trick you into thinking you don't understand the model, when in fact you do).

Some examples:

* In many cases, we require you to write `where Self: 'a` annotations by hand as a hedge to decide whether we (a) ought to make them optional or (b) ought to infer them by default. This compromise satisfies no-one, in some sense, since they are mandatory but must be typed, but it is forwards compatible with either route.
* One notable one is that we are not handling "implied bounds" very well, so that one often has to add `T: 'static` bounds that ought not to be necessary (e.g., [#91693](https://github.com/rust-lang/rust/issues/91693)). 
* Some patterns, like a `filter` method on lending iterator, fundamentally require polonius (e.g., [#92985](https://github.com/rust-lang/rust/issues/92985)), since you need the ability to start a borrow by calling `next`, optionally return that borrow out of the function, but along the other paths stop using it and end the borrow. That is not something NLL currently supports.
* The stabilization report mentions other problems, like annoying syntax.


### GATs are too complex and we should just use them as an implementation detail

Learning about GATs will not be optional for Rust programmers. GATs make new sorts of abstractions possible, and those abstractions will show up in libraries. Programmers will have to read the docs for those libraries and hence will encounter GATs. GATs are pretty abstract and while they seem natural and intuitive to people well versed in Rust, they are terrifying for most programmers.

Two points of contrast:

* async-await is infectious and shows up in libraries, but if you're not doing I/O, you can largely ignore it (the post originally said if not doing *async* I/O, but I'm not sure that's true, given that things like "make an HTTP request" are fairly common tasks but the sync APIs also expose async variants).
* unsafe code is complex, but if you're just consuming libraries, it's an implementation detail.

This point interacts with the previous point: a complex thing with a solid implementation is one thing, but a complex thing with unpredictable papercuts and limitations is going to be nigh impossible to learn. The fact that there is so much excitement about this may make people be excited to give it a spin but unless they're real Rust experts they're going to get frustrated very quickly.

As an alternative to exposing GATs, we could just expose the various features ([return-position-impl-trait-in-traits][rpitit], async fns in traits) that are reliant on them as an implementation detail, without exposing the general use case. Before we stabilize GATs, we need a solid case for why we need the *general purpose* feature and not just the *things that make use of it*.

[rpitit]: https://rust-lang.github.io/impl-trait-initiative/explainer/rpit_trait.html

### Given the number of papercuts, how do we know that GATs will land us somewhere usable?

Latent in the above is a sense of "if there are this many papercuts, why do we believe that we'll ever be able to resolve them"? In short, GATs *as they are today* don't cut it -- too many limitations etc. The papercuts seem deep enough and complex enough that there is some fear that they won't fundamentally improve, in which case we are stuck with them in their current state, and that's a bad trade.

**Comment by Imberflur** [comment]
I've used <https://docs.rs/nougat/> also see this great explanation <https://sabrinajewson.org/blog/the-better-alternative-to-lifetime-gats>.
