### ISSUE TITLE
regression: Display and Debug for ErrorKind

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#94507]
[Crater](https://github.com/rust-lang/rust/issues/94345) picked up this issue in a number of crates:

* lightning-0.0.104:
  * https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/reg/lightning-background-processor-0.0.104/log.txt
  * https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/reg/lightning-block-sync-0.0.104/log.txt
  * https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/reg/lightning-invoice-0.12.0/log.txt
  * https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/reg/lightning-net-tokio-0.0.104/log.txt
  * https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/reg/lightning-signer-core-0.1.0-5/log.txt
  * https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/valentinewallace.ldk-tutorial-node/log.txt
  * https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/johncantrell97.ldk-bdk-sample/log.txt

```
[INFO] [stdout] error[E0034]: multiple applicable items in scope
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/github.com-1ecc6299db9ec823/lightning-0.0.104/src/ln/msgs.rs:962:32
[INFO] [stdout]     |
[INFO] [stdout] 962 |             DecodeError::Io(ref e) => e.fmt(f),
[INFO] [stdout]     |                                         ^^^ multiple `fmt` found
[INFO] [stdout]     |
[INFO] [stdout]     = note: candidate #1 is defined in an impl of the trait `std::fmt::Display` for the type `ErrorKind`
[INFO] [stdout]     = note: candidate #2 is defined in an impl of the trait `Debug` for the type `ErrorKind`
[INFO] [stdout] help: disambiguate the associated function for candidate #1
[INFO] [stdout]     |
[INFO] [stdout] 962 |             DecodeError::Io(ref e) => std::fmt::Display::fmt(&e, f),
[INFO] [stdout]     |                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[INFO] [stdout] help: disambiguate the associated function for candidate #2
[INFO] [stdout]     |
[INFO] [stdout] 962 |             DecodeError::Io(ref e) => Debug::fmt(&e, f),
[INFO] [stdout]     |                                       ~~~~~~~~~~~~~~~~~
[INFO] [stdout] 
```

**Comment by yaahc** [comment]
caused by https://github.com/rust-lang/rust/pull/93090

**Comment by m-ou-se** [comment]
Discussed in the libs meeting just now. We consider this breakage acceptable.
