### PR TITLE
Infer async closure signature from (old-style) two-part `Fn` + `Future` bounds

### LINKED ISSUE #127425: async closure parameter type inference does not work anymore
When using async closures, rust since around 1.80 fails to infer parameter type in most scenarios.

```rust
#![feature(async_closure)]

use anyhow::Error;
use futures::{stream::repeat_with, StreamExt};

fn accept_str(_: &str) {}
fn accept_string(_: &String) {}

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Error> {
    // when using closure returning async block - everything works
    repeat_with(|| "foo".to_owned())
        .take(1)
        .for_each(|value| async move {
            accept_str(&value); // ok
            accept_str(value.as_str()); // ok
            accept_string(&value); // ok
        })
        .await;

    // when using async closure, most options fail
    repeat_with(|| "foo".to_owned())
        .take(1)
        .for_each(async move |value| {
            // error on whole closure, rust thinks that type of value is `str`
            // accept_str(&value);

            // type annotations needed, cannot infer type
            // accept_str(value.as_str());

            // this works
            accept_string(&value); // ok
        })
        .await;

    // can be fixed by providing type hint on async closure parameter
    repeat_with(|| "foo".to_owned())
        .take(1)
        .for_each(async move |value: String| {
            accept_str(&value); // ok
            accept_str(value.as_str()); // ok
            accept_string(&value); // ok
        })
        .await;

    Ok(())
}
```

I expected to see this happen: All options used to work in past versions of rust

Instead, this happened: Without explicit type hint it fails

### Version it worked on
It used to work in the past, around 1.79

### Version with regression
```
rustc 1.81.0-nightly (524d806c6 2024-07-05)
binary: rustc
commit-hash: 524d806c62a82ecc0cf8634b94997ae506f4d6f9
commit-date: 2024-07-05
host: x86_64-pc-windows-msvc
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### LINKED ISSUE #127468: Inference of argument type of async closure is broken
Well, it is maybe not a regression technically, because I use unstable feature. However, I wouldn't like this to get into stable channel.

### Code

I tried this code:

```rust
#![feature(async_closure)]

use std::future::Future;

pub struct A {}
impl A {
    fn method(&self) {}
}

pub fn call<B, F>(f: F)
    where F: FnOnce(A) -> B, B: Future<Output=()>
{
    f(A {});
}

pub fn test() {
    call(async move |a| {
        a.method();
    });
}
```

I expected to see this happen: I don't have to specify type of 'a' parameter as it may be inferred from `call` signature.

Instead, this happened:
```
error[E0282]: type annotations needed
  --> src/lib.rs:18:9
   |
18 |         a.method();
   |         ^ cannot infer type
```

I did compiler bisection, here is the result:

```
searched nightlies: from nightly-2023-03-17 to nightly-2024-06-12
regressed nightly: nightly-2024-02-07
searched commit range: https://github.com/rust-lang/rust/compare/f067fd6084d750f3797f54b71771c5dbc149726f...256b6fb19a2c018eaad4806d2369d1f6a71fc6ec
regressed commit: https://github.com/rust-lang/rust/commit/4a2fe4491ea616983a0cf0cbbd145a39768f4e7a

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2023-03-17 --end 2024-06-12
```
</details>
```

### PR DESCRIPTION
**Pull request by compiler-errors**
When an async closure is passed to a function that has a "two-part" `Fn` and `Future` trait bound, like:

```rust
use std::future::Future;

fn not_exactly_an_async_closure(_f: F)
where
    F: FnOnce(String) -> Fut,
    Fut: Future<Output = ()>,
{}
```

The we want to be able to extract the signature to guide inference in the async closure, like:

```rust
not_exactly_an_async_closure(async |string| {
    for x in string.split('\n') { ... }
    //~^ We need to know that the type of `string` is `String` to call methods on it.
})
```

Closure signature inference will see two bounds: `<?F as FnOnce<Args>>::Output = ?Fut`, `<?Fut as Future>::Output = String`. We need to extract the signature by looking through both projections.

### Why?

I expect the ecosystem's move onto `async Fn` trait bounds (which are not affected by this PR, and already do signature inference fine) to be slow. In the mean time, I don't see major overhead to supporting this "old–style" of trait bounds that were used to model async closures.

r? oli-obk
Fixes #127468
Fixes #127425

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/closure.rs [hunk 1]
```diff
@@ -470,14 +471,37 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+            // It's possible we've passed the closure to a (somewhat out-of-fashion)
+            // `F: FnOnce() -> Fut, Fut: Future<Output = T>` style bound. Let's still
+            // guide inference here, since it's beneficial for the user.
             hir::ClosureKind::CoroutineClosure(hir::CoroutineDesugaring::Async)
-                if self.tcx.async_fn_trait_kind_from_def_id(trait_def_id).is_some() => {}
+                if self.tcx.fn_trait_kind_from_def_id(trait_def_id).is_some() =>
+            {
+                self.extract_sig_from_projection_and_future_bound(cause_span, projection)
+            }
             _ => return None,
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/closure.rs:491]:
```suggestion
            _ => None,
```

File: compiler/rustc_hir_typeck/src/closure.rs [hunk 2]
```diff
@@ -470,14 +471,37 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        cause_span: Option<Span>,
+        projection: ty::PolyProjectionPredicate<'tcx>,
+    ) -> Option<ExpectedSig<'tcx>> {
+        let projection = self.resolve_vars_if_possible(projection);
 
         let arg_param_ty = projection.skip_binder().projection_term.args.type_at(1);
-        let arg_param_ty = self.resolve_vars_if_possible(arg_param_ty);
         debug!(?arg_param_ty);
 
         let ty::Tuple(input_tys) = *arg_param_ty.kind() else {
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/closure.rs:507]: in what case does this end up not being a tuple?

Comment (oli-obk) [reply compiler/rustc_hir_typeck/src/closure.rs:507]: Will we get here even though an error has been reported when `FnOnce<Args>` does not satisfy `Args: Tuple`?

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/closure.rs:507]: > in what case does this end up not being a tuple?

Generic code, where we'll see a type parameter and not a tuple.

> Will we get here even though an error has been reported when FnOnce<Args> does not satisfy Args: Tuple?

There will be no error reported if we have a type parameter and a `A: Tuple` bound, but there will likely be a simple type mismatch error later on:

```
fn uwu<A: Tuple>(_: impl Fn<A, Output = ()>) {}

fn test<A: Tuple>() {
  uwu::<A>(|| {});
}
```

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/closure.rs:507]: Resulting in:

```
error[E0308]: mismatched types
 --> src/lib.rs:8:3
  |
8 |   uwu::<A>(|| {});
  |   ^^^^^^^^^^^^^^^ types differ
  |
  = note: expected trait `Fn<A>`
             found trait `Fn()`
note: required by a bound in `uwu`
 --> src/lib.rs:5:26
  |
5 | fn uwu<A: Tuple>(_: impl Fn<A, Output = ()>) {}
  |                          ^^^^^^^^^^^^^^^^^^ required by this bound in `uwu`
```

I'd rather not delay a bug here and just let inference fail gracefully, since the type mismatch is reported *after* the closure is type-checked.

File: compiler/rustc_hir_typeck/src/closure.rs [hunk 3]
```diff
@@ -500,6 +523,65 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+        let projection = self.resolve_vars_if_possible(projection);
+
+        let arg_param_ty = projection.skip_binder().projection_term.args.type_at(1);
+        debug!(?arg_param_ty);
+
+        let ty::Tuple(input_tys) = *arg_param_ty.kind() else {
+            return None;
+        };
+
+        // If the return type is a
```
Comment (oli-obk) [inline compiler/rustc_hir_typeck/src/closure.rs:558]: Since this is only called for `async` closures, and not regular closures returning futures, can it ever be anything else? I guess it could already have been inferred to the anonymous future type of the async block, but not sure how that situation can occur. Kinda tempted to explicitly ICE/error on it

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/closure.rs:558]: This can definitely be another type, and it will (as I said in the other thread) result in a type mismatch later on. We shouldn't ICE here.

```
fn hewwo(_: impl Fn() -> BoxedFuture<'static, ()>) {}

fn test() {
  hewwo(async || {}) // type mismatch on output
}
```

Comment (compiler-errors) [reply compiler/rustc_hir_typeck/src/closure.rs:558]: And we don't need to error here either, since we'll always have a type mismatch. We're searching through already-registered obligations in our fulfillment context, so these things are already being here, so it's not really benefitting us to handle errors during this inference.

**Comment by compiler-errors** [comment]
OK this is ready :3

**Comment by oli-obk** [comment]
bors r plus
