### PR TITLE
hir_typeck: be more conservative in making "note caller chooses ty param" note

### LINKED ISSUE #126547: Confusing "the caller chooses a type which can be different" [E308]
### Code

```Rust
fn f<T>(t: &T) -> T {
    t
}
```

### Current output

```Shell
error[E0308]: mismatched types
 --> src/lib.rs:2:5
  |
1 | fn f<T>(t: &T) -> T {
  |      -            - expected `T` because of return type
  |      |
  |      expected this type parameter
2 |     t
  |     ^ expected type parameter `T`, found `&T`
  |
  = note: expected type parameter `_`
                  found reference `&_`
  = note: the caller chooses a type for `T` which can be different from `&T`
```

### Desired output

```Shell
error[E0308]: mismatched types
 --> src/lib.rs:2:5
  |
1 | fn f<T>(t: &T) -> T {
  |      -            - expected `T` because of return type
  |      |
  |      expected this type parameter
2 |     t
  |     ^ expected type parameter `T`, found `&T`
  |
  = note: expected type parameter `_`
                  found reference `&_`
```

### Rationale and extra context

The statement "the caller chooses a type for `T` which can be different from `&T`" is confusing because `T` and `&T` *are* *always* different. I think it would be best to supress that note when the types only differ in reference-ness. The message was introduced in #122195.

### Other cases

_No response_

### Rust Version

```Shell
rustc 1.81.0-nightly (3cf924b93 2024-06-15)
binary: rustc
commit-hash: 3cf924b934322fd7b514600a7dc84fc517515346
commit-date: 2024-06-15
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jieyouxu**
In https://github.com/rust-lang/rust/pull/122195 I added a "caller chooses ty for type param" note for when the return expression type a.k.a. found type does not match the expected return type.

#126547 found that this note was confusing when the found return type *contains* the expected type, e.g.

```rs
fn f<T>(t: &T) -> T {
    t
}
```

because the found return type `&T` will *always* be different from the expected return type `T`, so the note was needlessly redundant and confusing.

This PR addresses that by not making the note if the found return type contains the expected return type.

r? @fmease (since you reviewed the original PR)

Fixes https://github.com/rust-lang/rust/issues/126547

### CODE REVIEW

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs [hunk 1]
```diff
@@ -874,9 +874,9 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 } else {
                     // Only point to return type if the expected type is the return type, as if they
                     // are not, the expectation must have been caused by something else.
-                    debug!("return type {:?}", hir_ty);
+                    debug!("return type (hir::Ty) {:?}", hir_ty);
                     let ty = self.lowerer().lower_ty(hir_ty);
-                    debug!("return type {:?}", ty);
+                    debug!("return type (ty) {:?}", ty);
                     debug!("expected type {:?}", expected);
```
Comment (fmease) [inline compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:880]: Btw, `tracing` has a nice shorthand for this but it doesn't matter (for future reference).

```rs
debug!(?hir_ty, "return type");
let ty = self.lowerer().lower_ty(hir_ty);
debug!(?ty, "return type {:?}");
debug!(ty = ?expected, "expected type");
```

which will print:

```
return type hir_ty=...
return type ty=...
expected type exp ty=...
```

**Review by fmease — APPROVED** [review]
Thanks!

File: compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs (hunk 1 above)
Comment (jieyouxu) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs:880]: (I actually did know that shorthand, I just copied over what existed lol)

Comment (jieyouxu) [reply compiler/rustc_hir_typeck/src/fn_ctxt/suggestions.rs]: ... but now that you mentioned it, it's indeed nicer so I changed it ^^

**Review by fmease — APPROVED** [review]
