### ISSUE TITLE
selection error diagnostics results in a query cycle

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#145611]
when fetching `effective_visibilities` for `Adt` self types of a local trait while proving a where-clause.

https://github.com/rust-lang/rust/blob/8c32e313cccf7df531e2d49ffb8227bb92304aee/compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs#L2871-L2889

This query fetches the hidden type of all opaque types https://github.com/rust-lang/rust/blob/8c32e313cccf7df531e2d49ffb8227bb92304aee/compiler/rustc_privacy/src/lib.rs#L1841-L1846

introduced in #143431, cc @xizheyin @compiler-errors

```rust
trait LocalTrait {}
struct SomeType;
fn impls_trait<T: LocalTrait>() {}
fn foo() -> impl Sized {
    impls_trait::<SomeType>();
}
```

results in
```
error[E0391]: cycle detected when computing type of `foo::{opaque#0}`
 --> src/lib.rs:4:13
  |
4 | fn foo() -> impl Sized {
  |             ^^^^^^^^^^
  |
note: ...which requires computing type of opaque `foo::{opaque#0}`...
 --> src/lib.rs:4:13
  |
4 | fn foo() -> impl Sized {
  |             ^^^^^^^^^^
note: ...which requires borrow-checking `foo`...
 --> src/lib.rs:4:1
  |
4 | fn foo() -> impl Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires promoting constants in MIR for `foo`...
 --> src/lib.rs:4:1
  |
4 | fn foo() -> impl Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires checking if `foo` contains FFI-unwind calls...
 --> src/lib.rs:4:1
  |
4 | fn foo() -> impl Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires building MIR for `foo`...
 --> src/lib.rs:4:1
  |
4 | fn foo() -> impl Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires match-checking `foo`...
 --> src/lib.rs:4:1
  |
4 | fn foo() -> impl Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires type-checking `foo`...
 --> src/lib.rs:4:1
  |
4 | fn foo() -> impl Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
  = note: ...which requires checking effective visibilities...
  = note: ...which again requires computing type of `foo::{opaque#0}`, completing the cycle
note: cycle used when checking that `foo::{opaque#0}` is well-formed
 --> src/lib.rs:4:13
  |
4 | fn foo() -> impl Sized {
  |             ^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

error[E0277]: the trait bound `SomeType: LocalTrait` is not satisfied
 --> src/lib.rs:5:19
  |
5 |     impls_trait::<SomeType>();
  |                   ^^^^^^^^ the trait `LocalTrait` is not implemented for `SomeType`
  |
help: this trait has no implementations, consider adding one
 --> src/lib.rs:1:1
  |
1 | trait LocalTrait {}
  | ^^^^^^^^^^^^^^^^
note: required by a bound in `impls_trait`
 --> src/lib.rs:3:19
  |
3 | fn impls_trait<T: LocalTrait>() {}
  |                   ^^^^^^^^^^ required by this bound in `impls_trait`
```
note the query cycle before the actually desired error

**Comment by xizheyin** [comment]
Reopen for unimplemented "Delay cycle error as bug for `crate_variances` or `effective_visibilities`"

See: [#t-compiler > query cycles: ICE if unexpected queries are involved](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/query.20cycles.3A.20ICE.20if.20unexpected.20queries.20are.20involved)
