### ISSUE TITLE
Rust claims that `Ok(T)` is the same as `&T`

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#54578]
Steps to reproduce:

- Have a function that takes a reference
- Call that function passing an expression using `?`
- Forget an `&`

Example code: https://play.rust-lang.org/?gist=c75cddbb4c5d8a1b63ec11dc3c5bca43&version=stable&mode=debug&edition=2015

Output:

```
error[E0308]: try expression alternatives have incompatible types
 --> src/main.rs:5:9
  |
5 |     foo(bar()?);
  |         ^^^^^^
  |         |
  |         expected &i32, found i32
  |         help: try wrapping with a success variant: `Ok(bar()?)`
  |
  = note: expected type `&i32`
             found type `i32`
```

Expected output:

```
error[E0308]: mismatched types
 --> src/main.rs:5:9
  |
5 |     foo(bar()?);
  |         ^^^^^^
  |         |
  |         expected &i32, found i32
  |         help: consider borrowing here: `&bar()?`
  |
  = note: expected type `&i32`
             found type `i32`
```

**Comment by sgrif** [comment]
The error used to be mostly correct at least as recently as 1.26.1 (I don't have 1.27 or 1.28 installed to quickly check), though "mismatched types" read "match arm with an incompatible type". I suspect this regression occurred in whatever commit fixed that bug.

**Comment by zackmdavis** [comment]
Related to #52537 (which regressed in #51938, sorry :cold_sweat: ).

**Comment by zackmdavis** [comment]
#55423 will/would change the output to

```
error[E0308]: try expression alternatives have incompatible types
 --> segrif.rs:5:9
  |
5 |     foo(bar()?);
  |         ^^^^^^ expected &i32, found i32
  |
  = note: expected type `&i32`
             found type `i32`

error: aborting due to previous error
```
