### ISSUE TITLE
format! .into() suggestion deletes the format macro

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#110017]
### Code

```Rust
pub fn foo(x: &str) -> Result<(), Box<dyn std::error::Error>> {
    Err(format!("error: {x}"))
}
```

### Current output

```Shell
Checking foo v0.1.0 (/Users/eric/Temp/foo)
error[E0308]: mismatched types
 --> src/lib.rs:2:9
  |
2 |     Err(format!("error: {x}"))
  |         ^^^^^^^^^^^^^^^^^^^^^ expected `Box<dyn Error>`, found `String`
  |
  = note: expected struct `Box<dyn std::error::Error>`
             found struct `String`
  = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)
help: call `Into::into` on this expression to convert `String` into `Box<dyn std::error::Error>`
 --> /Users/eric/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/macros.rs:121:12
  |
12|         res.into()
  |            +++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `foo` (lib) due to previous error
```

### Desired output

```Shell
Checking foo v0.1.0 (/Users/eric/Temp/foo)
error[E0308]: mismatched types
 --> src/lib.rs:2:9
  |
2 |     Err(format!("error: {x}"))
  |         ^^^^^^^^^^^^^^^^^^^^^ expected `Box<dyn Error>`, found `String`
  |
  = note: expected struct `Box<dyn std::error::Error>`
             found struct `String`
  = note: this error originates in the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)
help: call `Into::into` on this expression to convert `String` into `Box<dyn std::error::Error>`
 --> /Users/eric/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/macros.rs:121:12
  |
12|          Err(format!("error: {x}").into())
  |                                   +++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `foo` (lib) due to previous error
```

### Rationale and extra context

The suggestion converts the code to:

```
Err(.into())
```

which is invalid.

It should suggest:

```
Err(format!("error: {x}").into())
```

The suggestion works correctly for non-macro string values. 

This suggestion was introduced in #102496.

### Anything else?

```
rustc 1.70.0-nightly (cf7ada217 2023-04-03)
binary: rustc
commit-hash: cf7ada217c8ac63367b184afd9fffaff30f6ed44
commit-date: 2023-04-03
host: aarch64-apple-darwin
release: 1.70.0-nightly
LLVM version: 16.0.0
```

**Comment by MU001999** [comment]
It cannot be reproduced on [play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=2d1de5202395c36c8f0c0e77e85df5a1).

**Comment by Ezrashaw** [comment]
I'm able to reproduce it locally. It seems to be suggesting a change in `libstd`:
```
help: call `Into::into` on this expression to convert `String` into `Box<dyn std::error::Error>`
 --> /Users/eric/.rustup/toolchains/nightly-aarch64-apple-darwin/lib/rustlib/src/rust/library/alloc/src/macros.rs:121:12
```
(note the path)

I assume that this is due to macro expansion. It might not be working on the playground because the playground doesn't have the `rust-src` component installed but that's a total guess.

**Comment by ehuss** [comment]
The presence of `rust-src` only affects the human-readable rendering. The important part to me is the JSON output which has `"suggested_replacement": ".into()"` even without rust-src.

Ideally it would be something closer to what it looks like with `Err(String::new())`:

```javascript
    {
      "children": [],
      "code": null,
      "level": "help",
      "message": "call `Into::into` on this expression to convert `String` into `Box<dyn std::error::Error>`",
      "rendered": null,
      "spans": [
        {
          "byte_end": 85,
          "byte_start": 85,
          "column_end": 22,
          "column_start": 22,
          "expansion": null,
          "file_name": "src/lib.rs",
          "is_primary": true,
          "label": null,
          "line_end": 2,
          "line_start": 2,
          "suggested_replacement": ".into()",
          "suggestion_applicability": "MaybeIncorrect",
          "text": [
            {
              "highlight_end": 22,
              "highlight_start": 22,
              "text": "    Err(String::new())"
            }
          ]
        }
      ]
    }
```

**Comment by MU001999** [comment]
It seems to affect all macro expansions ([play](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f162f4af77624de8d98b61c608cf35a0)):
```rust
macro_rules! s {
    ($e: expr) => {
        String::from($e)
    }
}

pub fn foo(x: &str) -> Result<(), Box<dyn std::error::Error>> {
    Err(s!(x))
}
```

**Comment by Ezrashaw** [comment]
Is the solution to just disable this suggestion for macro-expanded code?

As an aside, perhaps the playground should get `rust-src`, especially because of its prevalence in sharing code which might need the additional context.

**Comment by fmease** [comment]
> Is the solution to just disable this suggestion for macro-expanded code?

I think it's possible to achieve the desired output found the description, although I'm not sure how exactly.
Typically, you would use `find_ancestor_inside` on the span to peel away the layers of macro invocations, though for
that you need to provide a parent to mark the end of the chain. `Span::source_callsite` doesn't need such a stopper but here its use would be incorrect if the macro call itself (e.g. `Err(s!(x)`) was inside of a macro expansion.

Earlier I briefly tried create a parent for `find_ancestor_inside` via `tcx.hir().span_with_body(tcx.hir().parent_id(expr.hir_id))` I think but that didn't work. Maybe `tcx.hir().get_enclosing_scope(/*???*/)` could work, not sure.

**Comment by Ezrashaw** [comment]
Yeah, would that be the desired solution though? Can this be generalized to all the other type mismatch suggestions?

**Comment by fmease** [comment]
That's a good question. It was mostly an experiment to see if this issue specifically can be solved with `find_ancestor_inside`.
