### ISSUE TITLE
Undefined reference to `getauxval` in function `init_have_lse_atomics`  when compiling to nightly `aarch64-unknown-linux-musl`

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/rust#89626]
### Code

I received this pull request, which caught a regression for `aarch64-unknown-linux-musl` when compiling for nightly. The same process works for stable and beta. I don't have a machine that can easily compile to this platform, so I can't reduce it at the moment: https://github.com/XAMPPRocky/rasn/pull/49

### Version it worked on

It most recently worked on: Works on stable and beta `1.56.0-beta.4 (e6e620e1c 2021-10-04)`

- https://github.com/XAMPPRocky/rasn/pull/49/checks?check_run_id=3827011175

### Version with regression

`rustc --version --verbose`: 1.57.0-nightly (0eabf25b9 2021-10-06)

- https://github.com/XAMPPRocky/rasn/pull/49/checks?check_run_id=3827012571

### Backtrace

```
= note: /rust/lib/rustlib/aarch64-unknown-linux-musl/lib/libcompiler_builtins-cbf6a032efba8222.rlib(cpu_model.o): In function `init_have_lse_atomics':
          /cargo/registry/src/github.com-1ecc6299db9ec823/compiler_builtins-0.1.49/./lib/builtins/cpu_model.c:786: undefined reference to `getauxval'
          collect2: error: ld returned 1 exit status
          
= help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
= note: use the `-l` flag to specify native libraries to link
= note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)
```

**Comment by XAMPPRocky** [comment]
Tagging https://github.com/rust-lang/rust/issues/76992 and https://github.com/rust-lang/rust/pull/85805 since they seem relevant and maybe a potential fix.

**Comment by jbg** [comment]
I tried to use this workaround: `RUSTFLAGS="-C target-feature=-outline-atomics"`

But it doesn't change anything. Is it because `+outline-atomics` is added after checking `-C target-feature` [here](https://github.com/rust-lang/rust/pull/83655/files#diff-9f3bfd2fdc228dcb1b352082a7ebc39b19c8bea15b73141f72d9f5021aa3c66cR420)?

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2389626.20Undefined.20reference.20to.20.60getauxval'.20in.20function.20.60init.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high

**Comment by BlackDex** [comment]
Rust stable is also having issues now.
```
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04

rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.56.1
LLVM version: 13.0.0

```
I was able to fix this on stable by adding this to the `RUSTFLAGS`
`-Clinker=/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld`

**Comment by hkratz** [comment]
Hmm, can't reproduce the issue with current stable (1.56.1). However the problem is present in the current beta (1.57) which will become stable soon.

**Comment by BlackDex** [comment]
If i use `blackdex/rust-musl:aarch64-musl-stable` i get the same errors.
Though for some reason if i use `messense/rust-musl-cross:aarch64-musl` it doesn't, even if i force use 1.56.1 because that image is still on 1.56.0. But if i use nightly on the `messense` image it does produce that same error.

The other way around is also a bit strange, if i force 1.56.0 (or even 1.55.0) on the `blackdex` image it still generates the error for some reason. Only difference i see that quickly is that `messense` is compiled with GCC 9.2.0, and the `blackdex` image with GCC 10.3.0.

**Comment by pnkfelix** [comment]
@XAMPPRocky can you confirm if this is fixed in 1.57 (and also current nightly)?

**Comment by BlackDex** [comment]
@pnkfelix for me it does not seem to work on both new stable and latest nightly. I still need the `-Clinker=rust-lld` RUSTFLAG.

**Comment by hkratz** [comment]
@BlackDex But you also had a problem with 1.56.1, so it does not seem like that is the same issue.

**Comment by BlackDex** [comment]
I get exactly the same error message and the exact same solution solves it, so not sure why it is that different.

**Comment by XAMPPRocky** [comment]
I can confirm that this is now fixed for me, https://github.com/XAMPPRocky/rasn/runs/4397275912?check_suite_focus=true

**Comment by hkratz** [comment]
@BlackDex The outline atomics feature was not enabled by default in Rust 1.55 and 1.56. So the root cause of the problem you are seeing must be different. I tried building a simple hello world project with your docker images and that worked fine for me. Can you file a new bug report with steps on how to reproduce the issue?

**Comment by BlackDex** [comment]
@hkratz i'm currently testing some different options on building the musl toolchain.
I am using gcc 10.3.0 and both rust-embedded and messense are using 9.2.0. ill check if that is causing the issue.
If that is the case, would that still be valid for a bug-report, if it is the gcc 10.3.0 which is causing this?

**Comment by pnkfelix** [comment]
> I can confirm that this is now fixed for me, https://github.com/XAMPPRocky/rasn/runs/4397275912?check_suite_focus=true

closing as fixed.

From my reading of the comment thread, it is not clear to me if the issues encountered by @BlackDex are outright bugs or not. but even if they are bugs, they need to be filed as fresh issues.

**Comment by Techcable** [comment]
I still have this exact same problem on stable, 1.55 and latest nightly 😦 

I am building on alpine in a VM.

**Comment by jbg** [comment]
> I still have this exact same problem on stable, 1.55 and latest nightly 😦 
> 
> 
> 
> I am building on alpine in a VM.

Can you share the complete error?

**Comment by Techcable** [comment]
> > I still have this exact same problem on stable, 1.55 and latest nightly 😦
> > I am building on alpine in a VM.
> 
> Can you share the complete error?

Yes. Here is a gist: https://gist.github.com/Techcable/1b1dbf9a808cc62381bf2866e64c31e8

The code is public `gitpatcher-bin` available [here](https://github.com/Techcable/gitpatcher/tree/master/bin)

**Comment by lolo32** [comment]
I encountered the same issue building `cargo-deny` crate.

I successfully built it using `CFLAGS=-mno-outline-atomics` like said @jbg in his post (see https://github.com/rust-lang/rust/issues/89626#issuecomment-945814003)

**Comment by ehuss** [comment]
FWIW, I'm still running into issues with getauxval missing on aarch64 when linking with C code. I'm not sure what the issue is exactly, though this issue seems to be the most likely related that I can find. I'm not sure how to minimize, but here's a dockerfile that reproduces it:

```Dockerfile
FROM alpine:3.18.2

RUN apk add pkgconfig build-base curl openssl-dev openssl-libs-static
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > rustup.sh
RUN sh ./rustup.sh --profile minimal --default-toolchain nightly -y
ENV PATH=/root/.cargo/bin:${PATH}
WORKDIR /tmp
RUN cargo new foo
WORKDIR /tmp/foo
RUN cargo add git2
RUN echo 'use git2::*; fn main() { git2::Repository::init("x").unwrap(); }' > src/main.rs
# This also fails with -F git2/vendored-openssl.
RUN cargo run
```

This fails with:

```
= note: /usr/lib/gcc/aarch64-alpine-linux-musl/12.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: /root/.rustup/toolchains/nightly-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libcompiler_builtins-d1519a8aba827abf.rlib(45c91108d938afe8-cpu_model.o): in function `init_have_lse_atomics':
        /cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.91/./lib/builtins/cpu_model.c:1051: undefined reference to `getauxval'
        /usr/lib/gcc/aarch64-alpine-linux-musl/12.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: /root/.rustup/toolchains/nightly-aarch64-unknown-linux-musl/lib/rustlib/aarch64-unknown-linux-musl/lib/libcompiler_builtins-d1519a8aba827abf.rlib(45c91108d938afe8-cpu_model.o): in function `init_cpu_features':
        /cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.91/./lib/builtins/cpu_model.c:1344: undefined reference to `getauxval'
        /usr/lib/gcc/aarch64-alpine-linux-musl/12.2.1/../../../../aarch64-alpine-linux-musl/bin/ld: /cargo/registry/src/index.crates.io-6f17d22bba15001f/compiler_builtins-0.1.91/./lib/builtins/cpu_model.c:1345: undefined reference to `getauxval'
        collect2: error: ld returned 1 exit status
```

Above are noted several workarounds:
`-Clinker=rust-lld` or `-Zgcc-ld=lld` or `CFLAGS=-mno-outline-atomics`

I'm not sure were the problem lies, though #76992 seems suspicious.

```
rustc 1.73.0-nightly (903e279f4 2023-07-18)
binary: rustc
commit-hash: 903e279f468590fa3425f8aff7f3d61a5a873dbb
commit-date: 2023-07-18
host: aarch64-unknown-linux-musl
release: 1.73.0-nightly
LLVM version: 16.0.5
```

**Comment by peterwaller-arm** [comment]
Please can this issue be reopened. It still manifests on stable rust today, but only under limited circumstances.

As others have noted, the issue is caused by `-lc` appearing before `libcompiler_builtins.rlib`. Using LLD fixes the issue because LLD has a different behaviour to bfd/gold ld; argument order of libraries does not matter there. It looks as though the issue can be worked around with `-C link-arg=-lc` in rustflags, (which I assume makes `-lc` appear at the end).

Oddly, I have two different uses of `cargo test` within a build system, one of which gives an undefined reference to `getauxval`, and the other does not. So I suspect the underlying issue is there but not always manifesting.

I can see that the fix of using `--start-group` and `--end-group` considered in #76992 has been dropped for lack of bandwidth and a performance impact concern. A potential simpler fix could be to repeat `-lc` at the end of the link arguments to protect against this case.

**Comment by jacobbramley** [comment]
It's possible to trigger this by building the default "hello world" application with `RUSTFLAGS="-C target-feature=+crt-static"`. I'm using a Debian 10 x86_64 host with the OS-packaged `g++-aarch64-linux-gnu` toolchain. Some other linkers and environments seem to have slightly different behaviours.

This isn't limited to MUSL; I'm actually using `aarch64-unknown-linux-gnu`.

Finally: `-C link-arg=-lc` isn't quite a complete workaround for static builds because there's a trailling `-Wl,-Bdynamic`, so appending `-lc` to the command line causes it to be dynamically linked. Instead, `-C link-args=-Wl,-Bstatic -C link-args=-lc` does the right thing (and `file` now reports that the result is statically linked).

**Comment by apiraino** [comment]
I'm going to reopen this issue, we'll probably need to figure out a few regressions when linking for `musl` filed recently

**Comment by wesleywiser** [comment]
@bjorn3 [noticed](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.5D.202023-10-27.20P-high.20review/near/398913657) that

> the -lc linker arg does come right after liblibc.rlib rather than at the end

@pnkfelix has volunteered to investigate why that is happening.

**Comment by alyssais** [comment]
This doesn't seem to be a problem for me any more since https://github.com/rust-lang/rust/commit/9ed0d11efbec18a1fa4155576a3bcb685676d23c.

**Comment by Noratrieb** [comment]
it looks like this has been fixed. feel free to open a new issue if it happens again.
