### PR TITLE
libunwind: readd link attrs to _Unwind_Backtrace

### LINKED ISSUE #93349: rustc fails to build with in-tree libunwind and lld
Trying to build `rustc` on Debian with the following config used to work, but now fails:

```
changelog-seen = 2

[llvm]
ninja = true

[rust]
use-lld = true
llvm-libunwind = 'in-tree'
```

`./x.py build` exits with:

```
error: linking with `cc` failed: exit status: 1                                                                       
  |                                                                                                                   
  = note: "cc" "-m64" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/rustc_main-f54cdb57b4be29de.rustc_main.fcfbea46-cgu.0.rcgu.o" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/rustc_main-f54cdb57b4be29de.rustc_main.fcfbea46-cgu.1.rcgu.o" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/re
lease/deps/rustc_main-f54cdb57b4be29de.rustc_main.fcfbea46-cgu.2.rcgu.o" "-Wl,--as-needed" "-L" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-L" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps" "-L" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/psm-b9043e4a2f1f60fc/out" "-L" "/home/george/code/g
ithub/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/build/rustc_llvm-bb58500732d87599/out" "-L" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/llvm/build/lib" "-L" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps" "-lrustc_driver-823f1
f0eeb9a9bf8" "-Wl,--start-group" "-L" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-lstd-2b94913ec1c710dc" "-Wl,--end-group" "-Wl,-Bstatic" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-4ab75a05eb98bf89.rlib" "-Wl,-Bdynamic" "-lrt" "-ldl" "-lpthread" "-lm" "-lz" "-lstdc++" "-ldl" "-lutil" "-lrt" "-lpthrea
d" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/rustc_main-f54cdb57b4be29de" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-Wl,-O1" "-nodefaultlibs" "-Wl,-z,origin" "-Wl,-rpath,$ORIGIN/../lib" "-fuse-ld=lld"
  = note: ld.lld: error: /home/george/code/github/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/x86_64-unknown-linux-gnu/release/deps/librustc_driver-823f1f0eeb9a9bf8.so: undefined reference to _Unwind_Backtrace [--no-allow-shlib-undefined]

```

`git bisect` points to https://github.com/rust-lang/rust/commit/1c07096a45a15de64216f12ec726333870e372b1 as the culprit. It seems that the changes to `libunwind.rs` at line 237 accidentally dropped `#[link(name = "unwind", kind = "static")]` from `_Unwind_Backtrace`; readding this attribute allows `rustc` to build successfully.

I have a fix for this I'll upload shortly; just wanted to file an issue to reference first. :)

### PR DESCRIPTION
**Pull request by gburgessiv**
It seems the removal of these in 1c07096a45a15de64216f12ec726333870e372b1 was unintended; readding them fixes the build.

fixes rust-lang/rust#93349

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
I'm under the impression that on Unix-style platforms `#[link]` doesn't need to be repeated beyond one block at most, so I'm not actually sure why the build would be failing before and succeeding afterwards. I realize that this may fix things but do you know why it fixes things?

**Comment by gburgessiv** [comment]
Hm, I'd naively assumed that it was somehow directly associated with the `extern` block it preceded. I'll dig a bit deeper to figure out what exactly this is changing, then. :)

**Comment by petrochenkov** [comment]
>I'm under the impression that on Unix-style platforms `#[link]` doesn't need to be repeated beyond one block at most

See the FIXME above in the same file.
Unfortunately someone thought it was a good idea to include this information into heuristics for reexporting symbols from dylibs.

**Comment by alexcrichton** [comment]
I apologize @gburgessiv but you'll need to find a new reviewer for this as I'm going to recuse myself. If I'm going to be passive-aggressively insulted when I try to help out it's not worth my time.

**Comment by petrochenkov** [comment]
@alexcrichton 
If this is about my comment, then no insult was intended, there's literally a FIXME in the file describing the issue in detail. That logic in the compiler is old, I didn't know who implemented it.

**Comment by Mark-Simulacrum** [comment]
@bors r+

I think this makes sense for now, though I agree we should have a clearer story around names referenced with intent to export as the comment in the file suggests.

**Comment by gburgessiv** [comment]
Oops -- sorry this fell off my radar. :) Thank you all!
