### ISSUE TITLE
Error reporting from attribute macros regressed in 1.46.0

### ISSUE THREAD

**Issue by ahl** [rust-lang/rust#76360]
We take particular care to make sure that compilation errors associated with the items to which our attribute macros are applied are comprehensible. To that end we have tests to check the output of a variety of expected illegal programs to make sure developers could reasonably be expected to understand and correct those errors. In 1.46.0 we noticed a change in that behavior. While there were some beneficial changes to the way errors qualify structs, traits, etc. there seems to be a regression where 1.46.0 shows less information than in 1.45.0

I've put together a small repo that demonstrates the problem: https://github.com/ahl/span_regression

The first example is this macro:

```rust
#[proc_macro_attribute]
pub fn identity(
    _attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    item
}
```

Now consider this test program:

```rust
struct Thing {
    x: i32,
    y: i32,
}

#[identity]
fn doit() -> Thing {
    Thing {
        "howdy".to_string(),
    }
}
```

Under 1.45.0 one of the errors produced looks like this:
```
error[E0063]: missing fields `x`, `y` in initializer of `Thing`
  --> examples/test.rs:10:5
   |
10 |     Thing {
   |     ^^^^^ missing `x`, `y`
```

Under 1.46.0 that has changed to this:
```
error[E0063]: missing fields `x`, `y` in initializer of `Thing`
```

Note that under 1.46.0 no code is underlined.

Now consider a slightly more complicated macro:

```
#[proc_macro_attribute]
pub fn nested(
    _attr: proc_macro::TokenStream,
    item: proc_macro::TokenStream,
) -> proc_macro::TokenStream {
    let mut ret = proc_macro::TokenStream::new();
    let pre = vec![
        proc_macro::TokenTree::Ident(proc_macro::Ident::new("fn", proc_macro::Span::call_site())),
        proc_macro::TokenTree::Ident(proc_macro::Ident::new("foo", proc_macro::Span::call_site())),
        proc_macro::TokenTree::Group(proc_macro::Group::new(
            proc_macro::Delimiter::Parenthesis,
            proc_macro::TokenStream::new(),
        )),
        proc_macro::TokenTree::Group(proc_macro::Group::new(proc_macro::Delimiter::Brace, item)),
    ];
    ret.extend(pre);
    ret
}
```
(Note I had been using `quote!` but wanted to make sure that wasn't causing the problem)

With a similar example as above on 1.45.0:
```
error: expected identifier, found `"yo"`
  --> examples/test.rs:20:9
   |
19 |     Thing {
   |     ----- while parsing this struct
20 |         "yo".to_string(),
   |         ^^^^ expected identifier
```

With 1.46.0:
```
error[E0308]: mismatched types
  --> examples/test.rs:17:1
   |
17 | #[nested]
   | ^^^^^^^^^
   | |
   | expected struct `Thing`, found `()`
   | expected `Thing` because of return type
```

Rather than pointing to the offending code, the rustc error now points (unhelpfully) to the macro itself.

The general improvements made to error reporting in 1.46.0 (simpler naming, reduced duplicate errors) is greatly appreciated. This was one small regression I saw amongst the otherwise monotonic improvements.

**Comment by LeSeulArtichaut** [comment]
If I remember correctly, we should still be able to use `cargo-bisect-rustc` to bisect a regression in 1.46.0.
@rustbot ping cleanup

**Comment by LeSeulArtichaut** [comment]
Assigning `P-high` [as discussed as part of the Prioritization WG procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2376360.20Error.20reporting.20from.20attribute.20macros.20r.E2.80.A6).

**Comment by estebank** [comment]
Cc @petrochenkov

**Comment by Aaron1011** [comment]
This is caused by https://github.com/rust-lang/rust/pull/73345 - since we no longer pass a `Nonterminal` to an attribute macro, the pretty-print/reparse check get used (and fails), which causes us to lose spans.

This is a very interesting corner case - the `span_regression` error is testing the behavior of a proc-macro called on a syntactically invalid `Item`. It looks like this was previously relying on the parser to manage to recover an `Item`, despite the fact that the body is syntactically invalid.

I think there are two possible ways to fix this:

* Disable the pretty-print/reparse check when we recovered from parse errors during the attribute target - this would restore the 1.45.0 behavior of the `span_regression` repository. However, this would effectively mean that the parser recovery behavior is now part of the stable surface of the compiler, instead of just a trick for producing more meaningful error messages. Any future changes to parser recovery could cause us to start invoking an attribute macro, if we were able to parse enough of the target to produce an AST struct.
* Skip invoking attribute macros if there were any errors during the parsing of the attribute target, regardless of recovery behavior. Since attributes produce an arbitrary `TokenStream` as output, this would require us to remove the target item entirely (since we can't know what the attribute macro would have produced). Effectively, custom attribute macros would disable parser recovery.

**Comment by Aaron1011** [comment]
@ahl Thanks for providing such a nicer reproducer?

**Comment by ahl** [comment]
@Aaron1011 thanks for the quick diagnosis.

I agree with your assessment that both options have downsides (I think in your final paragraph you're describing option 2 rather than option 1 vis-a-vis removing the struct entirely).

Option 1 seems like a bit of a mess; option 2 seems more "philosophically pure" while being a little less pragmatic. I agree that option 2 is probably preferable and that a crisp semantic like "only valid items will cause the invocation of attribute macros" is a very clear delineation between `proc_macro` and `proc_macro_attribute`.

**Comment by estebank** [comment]
@Aaron1011 I agree with your assessment and think that the second option is the obviously correct choice for us. This might cause some weird errors for proc macros with pseudo DSLs that are no longer turned into valid code, but given that we are already recovering the parse most of the body will be treated as empty anyways, so it should be fine™.

**Comment by camelid** [comment]
Could we also add something where the compiler emits one of its “this is a bug” messages if an error doesn’t show span information? Or is that not feasible?

**Comment by Aaron1011** [comment]
@camelid: Right now, we deliberately create these 'dummy spans' due to issue https://github.com/rust-lang/rust/issues/43081. PR https://github.com/rust-lang/rust/pull/76130 makes progress towards eliminating these cases, but there's still more work to be done.

In the future, I think it would definitely make sense to emit a warning, and direct users to open a bug report. However, I don't think we'd want to emit an actual ICE - it would just create noise, since the query stack and call stack aren't useful for debugging missing spans.

**Comment by camelid** [comment]
@Aaron1011 Okay, thanks!

**Comment by Aaron1011** [comment]
The pretty-print/reparse check has been removed on the latest Nighty, leading to a better error message:

```
error: expected identifier, found `"howdy"`
  --> examples/test.rs:11:9
   |
10 |     Thing {
   |     ----- while parsing this struct
11 |         "howdy".to_string(),
   |         ^^^^^^^ expected identifier

error: expected identifier, found `"yo"`
  --> examples/test.rs:18:9
   |
17 |     Thing {
   |     ----- while parsing this struct
18 |         "yo".to_string(),
   |         ^^^^ expected identifier

error[E0063]: missing fields `x`, `y` in initializer of `Thing`
  --> examples/test.rs:10:5
   |
10 |     Thing {
   |     ^^^^^ missing `x`, `y`

error[E0063]: missing fields `x`, `y` in initializer of `Thing`
  --> examples/test.rs:17:5
   |
17 |     Thing {
   |     ^^^^^ missing `x`, `y`

error: aborting due to 4 previous errors
```

However, we should still come to a decision about whether or not proc-macros should be invoked when we've managed to recover a syntactically invalid attribute target.

**Comment by pnkfelix** [comment]
[Discussed at P-high review](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bsteering.20meeting.5D.202022-11-11.20compiler-team.23559.20P-high.20III/near/309214681)

> Doing recovery, emitting diagnostics about the recovery, and then running macros on the original unrecovered input means that macros must reimplement their own recovery independent and inconsistent with rustc — so rustc will diagnose what it thinks you meant, and the macro will diagnose what it thinks, and probably they won't align.

This seems like a real problem. I'm asking @estebank and @compiler-errors to try to dedicate some brain cycles to looking over the suggestions here and trying to drive progress towards a solution.

**Comment by pnkfelix** [comment]
2023 Q1 P-high triage: Assigning to WG-diagnostics to drive aforementioned followup work.

**Comment by apiraino** [comment]
Visited during [T-compiler P-high review](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Btriage.5D.202026-06-19.20P-high.20review/near/604901361)[#t-compiler/meetings > &#91;triage&#93; 2026-06-19 P-high review @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Btriage.5D.202026-06-19.20P-high.20review/near/604901361)

Downgrading and ping to @rust-lang/wg-diagnostics for a check if this issue still repro in its entirety or something changed in the meanwhile

@rustbot label -P-high +P-medium

**Comment by estebank** [comment]
Current output with the repro repo:

```
error: expected identifier, found `"howdy"`
  --> examples/test.rs:11:9
   |
10 |     Thing {
   |     ----- while parsing this struct
11 |         "howdy".to_string(),
   |         ^^^^^^^ expected identifier

error: expected identifier, found `"yo"`
  --> examples/test.rs:18:9
   |
17 |     Thing {
   |     ----- while parsing this struct
18 |         "yo".to_string(),
   |         ^^^^ expected identifier
```

By 1.60 it was already:

```
error: expected identifier, found `"howdy"`
  --> examples/test.rs:11:9
   |
10 |     Thing {
   |     ----- while parsing this struct
11 |         "howdy".to_string(),
   |         ^^^^^^^ expected identifier

error: expected identifier, found `"yo"`
  --> examples/test.rs:18:9
   |
17 |     Thing {
   |     ----- while parsing this struct
18 |         "yo".to_string(),
   |         ^^^^ expected identifier

error[E0063]: missing fields `x` and `y` in initializer of `Thing`
  --> examples/test.rs:10:5
   |
10 |     Thing {
   |     ^^^^^ missing `x` and `y`

error[E0063]: missing fields `x` and `y` in initializer of `Thing`
  --> examples/test.rs:17:5
   |
17 |     Thing {
   |     ^^^^^ missing `x` and `y`
```

I feel comfortable closing (as I expect we have a test for similar situations already).
