### ISSUE TITLE
Failed to bootstrap rustc due to size assertions

### ISSUE THREAD

**Issue by psumbera** [rust-lang/rust#109254]
Rut language (lates git sources) build on Solaris x86 fails with:
```
error[E0308]: mismatched types
    --> /builds/psumbera/rust-lang-build/compiler/rustc_index/src/lib.rs:29:32
     |
27   | macro_rules! static_assert_size {
     | ------------------------------- in this expansion of `static_assert_size!`
28   |     ($ty:ty, $size:expr) => {
29   |         const _: [(); $size] = [(); ::std::mem::size_of::<$ty>()];
     |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an array with a fixed size of 136 elements, found one with 144 elements
     |
    ::: compiler/rustc_ast/src/ast.rs:3130:5
     |
3130 |     static_assert_size!(Item, 136);
     |     ------------------------------ in this macro invocation

error[E0308]: mismatched types
    --> /builds/psumbera/rust-lang-build/compiler/rustc_index/src/lib.rs:29:32
     |
27   | macro_rules! static_assert_size {
     | ------------------------------- in this expansion of `static_assert_size!`
28   |     ($ty:ty, $size:expr) => {
29   |         const _: [(); $size] = [(); ::std::mem::size_of::<$ty>()];
     |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an array with a fixed size of 64 elements, found one with 72 elements
     |
    ::: compiler/rustc_ast/src/ast.rs:3131:5
     |
3131 |     static_assert_size!(ItemKind, 64);
     |     --------------------------------- in this macro invocation
```
Strange is that build on Solaris SPARC is ok.

I tried to use git bisect and it says:

7e855d5f3112f59fea95c900297daff8d342056f is the first bad commit
commit 7e855d5f3112f59fea95c900297daff8d342056f
Author: Nicholas Nethercote <n.nethercote@gmail.com>
Date:   Mon Jan 30 15:39:22 2023 +1100

    Use `ThinVec` in a few more AST types.

**Comment by Nilstrieb** [comment]
These assertions test the sizes of types in the compiler. SPARC works because they are only enabled on x86. Could it be that your host compiler is outdated and doesn't have the layout optimizations needed to make the types this small? Building rustc is only supported with a bootstrap compiler that is one version behind the source. You should be able to first compile the working commit, and then use the built compiler to compile the newer commit.

**Comment by psumbera** [comment]
It must have been something which was fixed in Rust 1.68.2. Versin1.68.0 was failing, 1.68.2 isn't. Closing it.
