### ISSUE TITLE
const_generics: link fails with undefined reference, hidden symbol isn't defined

### ISSUE THREAD

**Issue by Dirbaio** [rust-lang/rust#83972]
This code [(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=95832c231ba907ef3491428a04f0f0f8)

```rust
#![feature(const_generics)]

pub trait Foo {
    fn foo(&self);
}

pub struct FooImpl<const N: usize>;
impl<const N: usize> Foo for FooImpl<N> {
    fn foo(&self) {}
}

pub trait Bar: 'static {
    type Foo: Foo;
    fn get() -> &'static Self::Foo;
}

struct BarImpl;
impl Bar for BarImpl {
    type Foo = FooImpl<{ 4 }>;
    fn get() -> &'static Self::Foo {
        &FooImpl
    }
}

pub fn boom<B: Bar>() {
    B::get().foo();
}

fn main() {
    boom::<BarImpl>();
}

```

fails to link with

```

error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-Wl,--as-needed" "-L" "/playground/.rustup/toolchains/nightly-x86_*snip*own-linux-gnu/lib/libcompiler_builtins-8b33f9cbbc9652fe.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /usr/bin/ld: /playground/target/debug/deps/playground-dea6a74639071602.playground.27snrtcg-cgu.0.rcgu.o: in function `playground::boom':
          /playground/src/main.rs:26: undefined reference to `<playground::FooImpl<_> as playground::Foo>::foo'
          /usr/bin/ld: /playground/target/debug/deps/playground-dea6a74639071602: hidden symbol `_ZN64_$LT$playground..FooImpl$LT$_$GT$$u20$as$u20$playground..Foo$GT$3foo17hc9e5ef50b3fc24d9E' isn't defined
          /usr/bin/ld: final link failed: bad value
          collect2: error: ld returned 1 exit status
```

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (c051c5ddd 2021-04-06)
binary: rustc
commit-hash: c051c5ddda79f45fad196ca3a4690251e377d043
commit-date: 2021-04-06
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

**Comment by Dirbaio** [comment]
Builds correctly with `rustc 1.53.0-nightly (5e65467ef 2021-03-26)`
Fails with `rustc 1.53.0-nightly (9b0edb7fd 2021-03-27)`

**Comment by eggyal** [comment]
> Fails with `rustc 1.53.0-nightly (9b0edb7fd 2021-03-27)`

@Dirbaio are you sure about that?  I see it succeeding with 2021-03-27 but failing with 2021-03-28.

searched nightlies: from nightly-2021-03-26 to nightly-2021-04-07
regressed nightly: nightly-2021-03-28
searched commits: from https://github.com/rust-lang/rust/commit/5e65467eff3d1da4712586d8402d1d2e1d6654bc to https://github.com/rust-lang/rust/commit/9b0edb7fddacd6a60a380c1ce59159de597ab270
regressed commit: https://github.com/rust-lang/rust/commit/9b0edb7fddacd6a60a380c1ce59159de597ab270

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2021-03-26 
```
</details>

**Comment by eggyal** [comment]
Since const generics stabilised in 1.53, `#![feature(const_generics)]` is no longer necessary—and, strangely, the link error disappears without that feature flag (whether on stable or nightly).

**Comment by Dirbaio** [comment]
The code I originally found this in does require `#![feature(const_generics)]` and `#![feature(const_evaluatable_checked)]`, but while minimizing it I arrived to this.

The error also disappears when removing the braces in `{ 4 }`

**Comment by tmiasko** [comment]
`const_generics` feature enables lazy normalization. It seems that in one place a symbol name is constructed using an unevaluated const, while the other uses the evaluated one. This crates a mismatch in legacy symbol mangling scheme which hashes the substs. The issue also disappears in `-Zsymbol-mangling-version=v0` which evaluates the const during mangling.

```
$ rustc -Zprint-mono-items=lazy -Zverbose ...
MONO_ITEM fn <FooImpl<Const(Unevaluated(Unevaluated { def: WithOptConstParam { did: DefId(0:18 ~ a[317d]::{impl#1}::Foo::{constant#0}), const_param_did: Some(DefId(0:7 ~ a[317d]::FooImpl::N)) }, substs: [], promoted: None }): usize)> as Foo>::foo @@ a.7rcbfp3g-cgu.0[Internal]
```

**Comment by agausmann** [comment]
I'm seeing a similar error: #97186, with a very similar example!

It seems that `Unevaluated` generic const parameters are making their way through monomorphization and into symbol mangling, which should definitely be fixed.

Passing `-Zsymbol-mangling-version=v0` also fixes the linker error in my issue.
