### PR TITLE
Suggest a borrow when using dbg

### LINKED ISSUE #120327: Suggest a borrow when using dbg!()
### Code

```Rust
fn s() -> String {
    let a = String::new();
    dbg!(a);
    return a;
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0382]: use of moved value: `a`
 --> src/lib.rs:4:12
  |
2 |     let a = String::new();
  |         - move occurs because `a` has type `String`, which does not implement the `Copy` trait
3 |     dbg!(a);
  |     ------- value moved here
4 |     return a;
  |            ^ value used here after move
  |
help: borrow this binding in the pattern to avoid moving the value
 --> /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/macros.rs:364:13
  |
36|             ref tmp => {
  |             +++

For more information about this error, try `rustc --explain E0382`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Desired output

```Shell
help: consider borrowing instead of transferring ownership.

dbg!(&a);
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Rust Version

```Shell
Example was in the playground: "Build using the Nightly version: 1.77.0-nightly (2024-01-23 5d3d3479d774754856db)"

My machine has the same message:

rustc 1.76.0-nightly (a96d57bdb 2023-12-15)
binary: rustc
commit-hash: a96d57bdb6d2bb6d233d7d5aaefc2995ab99be01
commit-date: 2023-12-15
host: aarch64-apple-darwin
release: 1.76.0-nightly
LLVM version: 17.0.6
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by chenyukang**
Fixes #120327 
r? @estebank

### CODE REVIEW

**Comment by chenyukang** [comment]
@estebank, any comments on this PR?

**Comment by wesleywiser** [comment]
r? rust-lang/compiler

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 1]
```diff
@@ -498,21 +500,98 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+                                    name.clone().into_local_path().unwrap_or_default()
+                                }
+                                other => PathBuf::from(other.prefer_local().to_string()),
+                            };
+                        file_path.starts_with(&root.join("library/std/"))
+                    },
                 );
+                // it's useless to suggest inserting `ref` when the span comes from std library
+                // anyway, user can not modify std library in most cases, so let's keep it quite?
+                if !from_std {
```
Comment (oli-obk) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:523]: I think you'll want to forbid the suggestion whenever it points anywhere but to local code, the standard library is just the most common external crate in our test suite, but the issue probably exists for any dependency?

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 2]
```diff
@@ -498,21 +500,98 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+                        sugg,
+                        Applicability::MachineApplicable,
+                    );
+                }
             }
         }
     }
 
+    // for dbg!(x) which may take onwership, suggest dbg!(&x) instead
+    // but here we actually does not checking the macro name is `dbg!`
```
Comment (oli-obk) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:540]:
```suggestion
    // but here we actually do not check whether the macro name is `dbg!`
```

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 3]
```diff
@@ -498,21 +500,98 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+        &self,
+        body: &hir::Expr<'_>,
+        span: Option<Span>,
+        move_span: Span,
+        err: &mut Diag<'tcx>,
+    ) {
+        // only suggest for macro
+        if move_span.source_callsite() == move_span {
+            return;
+        }
```
Comment (oli-obk) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:552]: why? How do the diagnostics look without macros and could they improved by this, too?

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 4]
```diff
@@ -498,21 +500,98 @@ impl<'cx, 'tcx> MirBorrowckCtxt<'cx, 'tcx> {
...
+        let sm = self.infcx.tcx.sess.source_map();
+        let arg_code = if let Some(span) = span
+            && let Ok(code) = sm.span_to_snippet(span)
```
Comment (oli-obk) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:555]: I would prefer not to be using snippets for making decisions. Do we not have the expression of the value somewhere?

Comment (chenyukang) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:531]: Seems no, I just have a try to use ExpressionFinder to get the hir, and it only can not handle this scenario:

https://github.com/rust-lang/rust/pull/120990/files#diff-bd7f956e58a376780df31f75794e7af9b5d4043582aed6f129ae386a2b83ebdeR13-R17

the argument comes from the function parameters, since an ExpressionFinder will search in the body.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs (hunk 3 above)
Comment (chenyukang) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs]: If we don't limit only for macro, it will also add suggestion for this code:

```rust
fn s() -> String {
    let a = String::new();
    let _b = match a {
        tmp => {
            eprintln!("dbg: {}", tmp);
            tmp
        }
    };
    return a;
}

```

with diagnostic:

```console
 --> ./t/ha.rs:15:12
   |
7  |     let a = String::new();
   |         - move occurs because `a` has type `String`, which does not implement the `Copy` trait
...
10 |         tmp => {
   |         --- value moved here
...
15 |     return a; //~ ERROR use of moved value:
   |            ^ value used here after move
   |
help: consider borrowing instead of transferring ownership
   |
9  |     let _b = match &a {
   |                    +
help: borrow this binding in the pattern to avoid moving the value
   |
10 |         ref tmp => {
   |         +++
```

Seems it's also a good one.

I will add it into testcase.

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs (hunk 1 above)
Comment (chenyukang) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs]: changed it to:

```rust
    && !move_span.is_dummy()
    && !self.infcx.tcx.sess.source_map().is_imported(move_span)
```

**Comment by chenyukang** [comment]
@rustbot ready
I could not find a better way without using snippets.

**Review by oli-obk — CHANGES_REQUESTED** [review]
whoops, forgot to send the review I wrote recently

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 5]
```diff
@@ -509,6 +517,59 @@ impl<'infcx, 'tcx> MirBorrowckCtxt<'_, '_, 'infcx, 'tcx> {
...
+        place: &Place<'tcx>,
+        move_span: Span,
+        err: &mut Diag<'infcx>,
+    ) {
+        let var_info = self.body.var_debug_info.iter().find(|info| match info.value {
+            VarDebugInfoContents::Place(ref p) => p == place,
+            _ => false,
+        });
+        let arg_name = if let Some(var_info) = var_info {
+            var_info.name.to_string()
```
Comment (oli-obk) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:535]:
```suggestion
            var_info.name
```

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 6]
```diff
@@ -509,6 +517,59 @@ impl<'infcx, 'tcx> MirBorrowckCtxt<'_, '_, 'infcx, 'tcx> {
...
+        }
+        impl Visitor<'_> for MatchArgFinder {
+            fn visit_expr(&mut self, e: &hir::Expr<'_>) {
+                // dbg! is expanded into a match pattern, we need to find the right argument span
+                if let hir::ExprKind::Match(expr, ..) = &e.kind
+                    && let hir::ExprKind::Path(hir::QPath::Resolved(
+                        _,
+                        path @ Path { segments: [seg], .. },
+                    )) = &expr.kind
+                    && seg.ident.name.as_str() == &self.arg_name
```
Comment (oli-obk) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:552]:
```suggestion
                    && seg.ident.name == self.arg_name
```

File: compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs [hunk 7]
```diff
@@ -509,6 +517,59 @@ impl<'infcx, 'tcx> MirBorrowckCtxt<'_, '_, 'infcx, 'tcx> {
...
+        });
+        let arg_name = if let Some(var_info) = var_info {
+            var_info.name.to_string()
+        } else {
+            return;
+        };
+        struct MatchArgFinder {
+            expr_span: Span,
+            match_arg_span: Option<Span>,
+            arg_name: String,
```
Comment (oli-obk) [inline compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs:542]:
```suggestion
            arg_name: Symbol,
```

Comment (chenyukang) [reply compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs]: fixed, thanks!

**Comment by chenyukang** [comment]
seems this PR is forgotten by bors for some reason,
I'm not sure...

**Comment by matthiaskrgr** [comment]
@bors r- needs rebase + build fix 
https://github.com/rust-lang/rust/pull/127775#issuecomment-2229142779

**Comment by chenyukang** [comment]
rebased.

**Comment by matthiaskrgr** [comment]
thx!
@bors r=oli-obk
