### ISSUE TITLE
"x.py install" no longer respects missing-tools=true

### ISSUE THREAD

**Issue by jbeich** [rust-lang/rust#61435]
Regressed by 59291dc788d4, see [error log](http://beefy9.nyi.freebsd.org/data/112amd64-default/503212/logs/errors/rust-nightly-1.37.0.20190601.log).
```
Building stage2 tool miri (x86_64-unknown-freebsd)
running: "build/x86_64-unknown-freebsd/stage0/bin/cargo" "build" "--target" "x86_64-unknown-freebsd" "-j" "1" "--release" "--frozen" "--manifest-path" "src/tools/miri/Cargo.toml" "--message-format" "json"
   Compiling miri v0.1.0 (src/tools/miri)
error[E0412]: cannot find type `Mir` in module `mir`
  --> src/tools/miri/src/fn_call.rs:20:45
   |
20 |     ) -> EvalResult<'tcx, Option<&'mir mir::Mir<'tcx>>> {
   |                                             ^^^ not found in `mir`
help: there is an enum variant `rustc::session::config::BorrowckMode::Mir` and 3 others; try using the variant's enum
   |
20 |     ) -> EvalResult<'tcx, Option<&'mir rustc::session::config::BorrowckMode>> {
   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20 |     ) -> EvalResult<'tcx, Option<&'mir rustc::session::config::OutputType>> {
   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
20 |     ) -> EvalResult<'tcx, Option<&'mir rustc_mir::util::borrowck_errors::Origin>> {
   |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[...]
Some errors have detailed explanations: E0061, E0412.
For more information about an error, try `rustc --explain E0061`.
error: Could not compile `miri`.

To learn more, run the command again with --verbose.
command did not execute successfully: "build/x86_64-unknown-freebsd/stage0/bin/cargo" "build" "--target" "x86_64-unknown-freebsd" "-j" "1" "--release" "--frozen" "--manifest-path" "src/tools/miri/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101
      < ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-unknown-freebsd" }, target: "x86_64-unknown-freebsd", tool: "miri", path: "src/tools/miri", mode: ToolRustc, is_optional_tool: true, source_type: Submodule, extra_features: [] }
    < Miri { compiler: Compiler { stage: 2, host: "x86_64-unknown-freebsd" }, target: "x86_64-unknown-freebsd", extra_features: [] }
Unable to build miri, skipping dist
  < Miri { compiler: Compiler { stage: 2, host: "x86_64-unknown-freebsd" }, target: "x86_64-unknown-freebsd" }
skipping Install miri stage2 (x86_64-unknown-freebsd)
< Miri { compiler: Compiler { stage: 2, host: "x86_64-unknown-freebsd" }, target: "x86_64-unknown-freebsd" }
c Assemble { target_compiler: Compiler { stage: 2, host: "x86_64-unknown-freebsd" } }
> Analysis { compiler: Compiler { stage: 2, host: "x86_64-unknown-freebsd" }, target: "x86_64-unknown-freebsd" }
  > Analysis { compiler: Compiler { stage: 2, host: "x86_64-unknown-freebsd" }, target: "x86_64-unknown-freebsd" }
Dist analysis
    c Std { compiler: Compiler { stage: 2, host: "x86_64-unknown-freebsd" }, target: "x86_64-unknown-freebsd" }
image_src: "build/x86_64-unknown-freebsd/stage2-std/x86_64-unknown-freebsd/release/deps/save-analysis", dst: "build/tmp/dist/rust-analysis-nightly-x86_64-unknown-freebsd-image/lib/rustlib/x86_64-unknown-freebsd/analysis"
thread 'main' panicked at 'fs::read_dir(src) failed with No such file or directory (os error 2)', src/bootstrap/lib.rs:1217:18
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Traceback (most recent call last):
  File "x.py", line 11, in <module>
    bootstrap.main()
  File "src/bootstrap/bootstrap.py", line 847, in main
    bootstrap(help_triggered)
  File "src/bootstrap/bootstrap.py", line 833, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "src/bootstrap/bootstrap.py", line 141, in run
    raise RuntimeError(err)
RuntimeError: failed to run: build/bootstrap/debug/bootstrap install --verbose --config ./config.toml --jobs 1
```

**Comment by Centril** [comment]
cc @alexcrichton

**Comment by AaronKutch** [comment]
Does this have anything to do with problems I had building the rust compiler? I forgot to get the real git install and not just GitHub Desktop, and I got an obfuscated error which took me a lot of time to fix.
I was going to file an issue to get x.py to check that all the needed tools are in place, and that Python was 2.7.x, but I see this issue with "missing-tools" in its title.

**Comment by o01eg** [comment]
https://github.com/rust-lang/rust/pull/61750 fixed this error for me.

**Comment by jbeich** [comment]
I confirm, [builds fine](http://beefy9.nyi.freebsd.org/data/112amd64-default/504455/logs/rust-nightly-1.37.0.20190618.log).
