### ISSUE TITLE
Pre-expansion gating collects spans from un`Success`ful macro matchers

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#65846]
Setting high priority as this affects performance collection.

Sample error, likely possible to see more at https://perf.rust-lang.org/status.html

```
error[E0658]: type ascription is experimental
   --> components/style/stylesheets/viewport_rule.rs:290:43
    |
290 |                 declaration!($declaration(value: try!($parse(input)),
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
...
325 |             "orientation" => ok!(Orientation(Orientation::parse)),
    |                              ------------------------------------ in this macro invocation
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/23416
    = help: add `#![feature(type_ascription)]` to the crate attributes to enable
```

**Comment by Mark-Simulacrum** [comment]
I suspect this was caused by https://github.com/rust-lang/rust/pull/65742 -- presumably, that PR does something wrong, as I suspect that the expression here is _not_ type ascription -- `try!($parse(input))` is not a type -- so we're probably being overeager. If we don't have immediate ideas as to why then I think we should revert the PR.

cc @Centril @davidtwco

**Comment by Centril** [comment]
Reduced to:

```rust
macro_rules! mac {
    ($e:expr) => {};
    (label: $v:expr, MARKER) => {};
}

mac!(label: 0, MARKER);
```

which results in:

```rust
error: expected type, found `0`
 --> src/lib.rs:6:13
  |
6 | mac!(label: 0, MARKER);
  |           - ^ expected type
  |           |
  |           tried to parse a type due to this
```

on stable, and:

```rust
error: expected type, found `0`
 --> src/lib.rs:6:13
  |
6 | mac!(label: 0, MARKER);
  |           - ^ expected type
  |           |
  |           tried to parse a type due to this type ascription
  |
  = note: `#![feature(type_ascription)]` lets you annotate an expression with a type: `<expr>: <type>`
  = note: for more information, see https://github.com/rust-lang/rust/issues/23416
```

on nightly.

**Comment by Centril** [comment]
I'm not sure how this code managed to work before because it *is* parsing a type ascription (successfully when using `mac!(label: try!(), MARKER);`). Just to be sure, I verified this with:

```diff
         let parser_snapshot_before_type = self.clone();
         match self.parse_ty_no_plus() {
             Ok(rhs) => {
-                Ok(mk_expr(self, rhs))
+                let expr = mk_expr(self, rhs);
+                if let ExprKind::Type(..) = expr.kind  {
+                    panic!("PARSED TYPE ASCRIPTION!");
+                }
+                Ok(expr)
             }
```
where the input was:
```rust
macro_rules! mac {
    ($e:expr) => {};
    (label: $v:expr, MARKER) => {};
}

mac!(label: try!(), MARKER)
```

Somehow this type ascription disappears later before `PostExpansionVisitor`?

---------------------------

All in all, I believe that at least from the POV of the parser, the behavior is expected and therefore there is no bug. This should be fixed on perf's end, at least in the interim, by switching to a token besides `:`.

**Comment by Mark-Simulacrum** [comment]
This is still a breaking change - and I would expect it to be fixed in the parser, especially as in this case the macro input doesn't even look like type ascription, it's token colon expression, whereas type ascription would be token colon type, right?
Plus, the token colon expression macro form seems pretty common (used all over the place, I imagine, in many macros). I don't think we can just wholesale break things like this.

I'll look into a fix for perf, just to get us unbroken, but I feel pretty strongly so far that this is a breaking change and a bug.

**Comment by Centril** [comment]
> especially as in this case the macro input doesn't even look like type ascription, it's token colon expression, whereas type ascription would be token colon type, right?

Well it is parsing a type ascription because it is constructing an `ExprKind::Type`. Otherwise https://github.com/rust-lang/rust/pull/65742 would have no effect. For example, consider (*[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2af7f85f155ef44ee14626ba3cad3583)*):
```rust
macro_rules! m {
    ($e:expr) => { dbg!(0); };
    (lab as $e:expr, foo) => { dbg!(1); };
}

fn main() {
    m!(lab as 1, foo);
}
```

Because of the first arm, this will error with *"error: expected type, found `1`"* despite `, foo` not matching the first arm.

Another case to consider is (*[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=20482659210810e41e08d04c0a0a85c8)*):
```rust
macro_rules! m {
    ($e:expr) => { dbg!(0); };
    (box $e:expr, foo) => { dbg!(1); };
}

fn main() {
    m!(box 1, foo);
}
```

This also used to compile and now emits a feature gate error? Why? Because macro expansion will try each arm in a `macro_rules!` item one at a time until it reaches the first `Success(...)` and then do transcription. https://github.com/rust-lang/rust/blob/46e6c533d08a2c6d22083a2756a0b569e001c3c4/src/libsyntax_expand/mbe/macro_rules.rs#L186-L248

In this case, once we have parsed `ExprKind::Type`, a span has been added to [`GatedSpans`](https://doc.rust-lang.org/nightly/nightly-rustc/syntax/sess/struct.GatedSpans.html) by the parser. Once we reach feature gate checking, all of those spans will turn into emitted feature gating errors. This is well illustrated by the following example (*[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ef9e5ed5b9b5c6f412f73d1a0a90a087)*):

```rust
macro_rules! m {
    ($e:expr) => { dbg!(0); };
    (box $e:expr, foo2) => { dbg!(1); };
}

fn main() {
    m!(box 1, foo);
}
```

The only way I know of to not do that which might possibly be correct and still perform pre-expansion gating would be to snapshot `GatedSpans` and only commit to additions it once we have reached `Success(...) =>`. This would need to be maintained as a stack to handle macros calling macros (should be taken care of by recursion in the compiler itself, hopefully).

> Plus, the token colon expression macro form seems pretty common (used all over the place, I imagine, in many macros). I don't think we can just wholesale break things like this.

https://github.com/rust-lang/rust/pull/64672#issuecomment-542642603 (crates.io had 5 regressions where 4 of those were from the same project with the same root and then there was another root; github had 2 regressions)

> I'll look into a fix for perf, just to get us unbroken, but I feel pretty strongly so far that this is a breaking change and a bug.

If there is a bug, having done the investigation, I can say with certainty that it is not in https://github.com/rust-lang/rust/pull/65742 but rather a pre-existing one in `fn generic_extension`. 

Also, we should absolutely continue performing pre-expansion gating. To not do so would mean leaking all new syntax into stable immediately! In the long run, that will make both users and the language team unhappy. Moreover, making things which were accidentally stable unstable is legitimized by https://github.com/rust-lang/rfcs/pull/2405, which you signed off on yourself.

**Comment by Mark-Simulacrum** [comment]
I would expect pre-expansion gating in this form (i.e., macro input parsing) to either emit a future-incompatibility warning (like we do for methods that might conflict with a future stabilization, I believe) or simply pretend that the gated form does not exist unless the feature gate is enabled.

I get that this is likely hard -- and might not even be practical -- but as it is currently, even though I personally do not expect us to stabilize box expressions in their current syntax/form for what is likely on the order of years, if ever, it seems really odd to forbid the `<ident> <expr>` form specifically for `box` but nothing else. In some sense, this is making it appear that the syntax has been chosen "consciously" rather than just being a historical artifact, for the most part.

> To not do so would mean leaking all new syntax into stable immediately! 

This is basically my point -- as it is implemented today, all Rust users pay the pain of new syntax in macros immediately upon its addition. That gives us no time for experimentation or to decide if that's a good thing; furthermore, Rust users who use stable may experience breakage from unstable features. Maybe that's fine -- and we just need to be _really careful_ when adding/modifying unstable syntax parsing -- but to me it seems like that's probably not quite what we want. I, at least, would expect that an unstable feature, even when it comes to syntax, is invisible, possibly modulo diagnostics, to stable users of the compiler (or those not using the specific feature gate).

**Comment by Mark-Simulacrum** [comment]
We've fixed perf.rlo so removing high priority label.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/65860.

**Comment by Centril** [comment]
That's a distinct problem. That one is about cfg-expansion and this is about macro matchers. They will have different solutions. I'll try to look at fixing this one today.

**Comment by Centril** [comment]
I have a fix in https://github.com/rust-lang/rust/pull/65974.
