### ISSUE TITLE
associated type `Inner` not found

### ISSUE THREAD

**Issue by dev-ardi** [rust-lang/rust#132414]
### Code

I can't provide an example for now, but I've bisected the issue to this PR: 
https://github.com/rust-lang/rust/pull/132194
@compiler-errors  

I expected to see this happen: compile succesfully

Instead, this happened:
```rs
error[E0220]: associated type `Inner` not found for `T`
   --> redacted.rs:560:20
    |
560 |     ) -> Result<T::Inner, RedactedError>
    |                    ^^^^^ associated type `Inner` not found
```

**Comment by compiler-errors** [comment]
You haven't provided enough to repro this, but I assume your "redacted" function is an async fn in trait. If so, this is a duplicate of https://github.com/rust-lang/rust/issues/132372, and should be fixed. If it's not an AFIT, please reopen this issue with a more detailed example; this bug report isn't actionable currently 😺

**Comment by dev-ardi** [comment]
Thanks!
