### ISSUE TITLE
Slice patterns don't work with non-Copy types

### ISSUE THREAD

**Issue by cake4289** [rust-lang/rust#50764]
Slice patterns cannot be used to destructure arrays of non-`Copy` types:

```rust
struct Struct;

fn main() {
    let x = [Struct, Struct];
    let [a, b] = x;
}
```

```
error[E0382]: use of moved value: `x[..]`
 --> src/main.rs:5:13
  |
5 |     let [a, b] = x;
  |          -  ^ value used here after move
  |          |
  |          value moved here
  |
  = note: move occurs because `x[..]` has type `Struct`, which does not implement the `Copy` trait
```

This makes array destructuring pretty redundant IMHO as moving out of a `Copy` array could already be done through indexing; moving out of a non-`Copy` array cannot be done but destructuring provides a safe syntax to do so.

On a related note, the following code fails to compile:

```rust
struct Struct;

fn main() {
    let x = [Struct, Struct];
    let a = x[0];
}
```

This should at the very least compile in the same way as

```rust
struct Struct;

fn main() {
    let x = [Struct, Struct];
    let [a, _] = x;
}
```

Which *does* compile correctly in rust 1.26.

**Comment by csmoe** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/26736

**Comment by vandenheuvel** [comment]
I'm not sure that this is really a duplicate, as #26736 is now resolved but the above example fails to compile on `1.45.0-nightly (2020-05-27 664fcd3f046e2a682460)`.
