### ISSUE TITLE
Compilation error with nightly: `the trait ~const Deref is not implemented for String`

### ISSUE THREAD

**Issue by ogoffart** [rust-lang/rust#103677]
### Code

```rust
const _: fn(&String) = |s| { &*s as &str; };
```

Compiles in stable rust (1.64)  as well as in beta.
But in nightly, we get this compilation error: 

```
error[[E0277]](https://doc.rust-lang.org/nightly/error-index.html#E0277): the trait bound `String: Deref` is not satisfied
 --> src/lib.rs:4:30
  |
4 | const _: fn(&String) = |s| { &*s as &str; };
  |                              ^^^ the trait `~const Deref` is not implemented for `String`
  |
note: the trait `Deref` is implemented for `String`, but that implementation is not `const`
 --> src/lib.rs:4:30
  |
4 | const _: fn(&String) = |s| { &*s as &str; };
  |                              ^^^

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` due to previous error
```

playground link: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c4decfd8064f4074814df6e0d4e0859c

### Version it worked on

1.64, and beta

### Version with regression

current nightly

**Comment by Nilstrieb** [comment]
searched nightlies: from nightly-2022-08-01 to nightly-2022-10-24
regressed nightly: nightly-2022-09-23
searched commit range: https://github.com/rust-lang/rust/compare/9062b780b32d2eab060b4432863e085d9504ca5c...e7119a0300b87a3d670408ee8e847c6821b3ae80
regressed commit: https://github.com/rust-lang/rust/commit/7a8636c843bd24038fe1d1f69b4a8e4b0ea55d4e

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 2022-08-01 --regress error --access github
```
</details>

**Comment by Nilstrieb** [comment]
searched nightlies: from nightly-2022-08-01 to nightly-2022-10-24
regressed nightly: nightly-2022-09-23
searched commit range: https://github.com/rust-lang/rust/compare/9062b780b32d2eab060b4432863e085d9504ca5c...e7119a0300b87a3d670408ee8e847c6821b3ae80
regressed commit: https://github.com/rust-lang/rust/commit/7a8636c843bd24038fe1d1f69b4a8e4b0ea55d4e

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 2022-08-01 --regress error --access github
```
</details>

**Comment by Nilstrieb** [comment]
@fee1-dead @oli-obk

**Comment by oli-obk** [comment]
Seems like closures pick the constness of their parent when they should always be notconst
