### ISSUE TITLE
Cycle detected when computing whether impls specialize one another, across crate boundaries

### ISSUE THREAD

**Issue by patrick-gu** [rust-lang/rust#90817]
I tried this code (note: the crate name is `bug`, and this only occurs when the files are separate):

In `src/lib.rs`:
```rust
pub trait Reducible {
    type Reduced;
}

pub struct Base;

pub struct Higher;

impl Reducible for Higher {
    type Reduced = Base;
}

pub trait Reduce<R> {}

impl<T> Reduce<Base> for T {}

impl<T, R> Reduce<R> for T
where
    R: Reducible,
    T: Reduce<R::Reduced>,
{
}

pub fn reduce<R>(_: R)
where
    (): Reduce<R>,
{
}
```

In `src/main.rs`:
```rust
fn main() {
    bug::reduce(bug::Higher);
}
```

I expected to see this happen: Code compiles successfully, as it would if everything was in `main.rs`.

Instead, this happened: the compiler emits an error:

```
error[E0391]: cycle detected when computing whether impls specialize one another
  --> C:\path\to\bug\src\lib.rs:17:1
   |
17 | / impl<T, R> Reduce<R> for T
18 | | where
19 | |     R: Reducible,
20 | |     T: Reduce<R::Reduced>,
21 | | {
22 | | }
   | |_^
   |
   = note: ...which immediately requires computing whether impls specialize one another again
note: cycle used when type-checking `main`
  --> src\main.rs:1:1
   |
1  | fn main() {
   | ^^^^^^^^^

For more information about this error, try `rustc --explain E0391`.
error: could not compile `bug` due to previous error
```

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0 (09c42c458 2021-10-18)
binary: rustc
commit-hash: 09c42c45858d5f3aedfa670698275303a3d19afa
commit-date: 2021-10-18
host: x86_64-pc-windows-msvc
release: 1.56.0
LLVM version: 13.0.0
```
This also appears to be present on 1.58.0-nightly 2021-11-10, commit hash 82af160c2cb9c349a0373cba98d8ad7f911f0d34.

**Comment by patrick-gu** [comment]
This check seems to allow the code to compile when the impls are in the same crate:
https://github.com/rust-lang/rust/blob/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/compiler/rustc_trait_selection/src/traits/specialize/mod.rs#L123-L129

**Comment by patrick-gu** [comment]
It seems that the cause of the issue is that, when trying to fulfil the bound `(): Reduce<Higher>`, it is checked whether the first impl specializes the second impl:
https://github.com/rust-lang/rust/blob/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/compiler/rustc_trait_selection/src/traits/select/mod.rs#L1693-L1706
Since specialization could be enabled, the compiler tries to determine if it is present:
https://github.com/rust-lang/rust/blob/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/compiler/rustc_trait_selection/src/traits/specialize/mod.rs#L131-L171
In trying to fulfill the trait obligations, the bounds on the second candidate are evaluated again:
https://github.com/rust-lang/rust/blob/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/compiler/rustc_trait_selection/src/traits/select/mod.rs#L961-L973
Which requires deciding between the two impls:
https://github.com/rust-lang/rust/blob/6bda5b331cfe7e04e1fe348c58a928fc2b650f4f/compiler/rustc_trait_selection/src/traits/select/mod.rs#L1525-L1543
Creating a loop.

**Comment by patrick-gu** [comment]
A similar problem is present in 1.57.0, but not in 1.56.0.

`src/lib.rs`:
```rust
pub trait Change<T> {
    type Changed;
}

impl<T> Change<T> for () {
    type Changed = T;
}

pub trait Split {
    type First;
    type Rest;
}

pub trait Combine<T> {}

impl<U> Combine<()> for U {}

impl<T, U> Combine<U> for T
where
    U: Split,
    Self: Change<U::First>,
    <Self as Change<U::First>>::Changed: Combine<U::Rest>,
{
}

pub fn combine<T>(_: T)
where
    (): Combine<T>,
{
}
```

`src/main.rs`:
```rust
fn main() {
    bug::combine(());
}
```

**Comment by apiraino** [comment]
@patrick-gu  for the code [in the first comment](https://github.com/rust-lang/rust/issues/90817#issue-1051506978) can you identify a previous version of Rust that does not reproduce the issue? I've tried backtracking to really old nightlies and I could not find a version that does *not* reproduce.

I confirm that the snippet [in this comment](https://github.com/rust-lang/rust/issues/90817#issuecomment-999003405) reproduce the error in 1.57 and not 1.56.1

**Comment by patrick-gu** [comment]
@apiraino The code in the first comment compiles on 1.8.0 but not on 1.9.0. The error message for 1.9.0 is:
```
error: Could not compile `bug`.

Caused by:
  Process didn't exit successfully: `rustc src/main.rs --crate-name bug --crate-type bin -g --out-dir /path/to/bug/target/debug --emit=dep-info,link -L dependency=/path/to/bug/target/debug -L dependency=/path/to/bug/target/debug/deps --extern bug=/path/to/bug/target/debug/libbug.rlib` (signal: 11, SIGSEGV: invalid memory reference)
```
with no mention of a cycle.

In 1.22.0, the error message mentions a cycle:
```
error[E0391]: unsupported cyclic reference between types/traits detected
  --> /path/to/bug/src/lib.rs:17:1
   |
17 | / impl<T, R> Reduce<R> for T
18 | | where
19 | |     R: Reducible,
20 | |     T: Reduce<R::Reduced>,
21 | | {
22 | | }
   | |_^ cyclic reference
   |
note: the cycle begins when computing whether impls specialize one another...
  --> /path/to/bug/src/lib.rs:17:1
   |
17 | / impl<T, R> Reduce<R> for T
18 | | where
19 | |     R: Reducible,
20 | |     T: Reduce<R::Reduced>,
21 | | {
22 | | }
   | |_^
   = note: ...which then again requires computing whether impls specialize one another, completing the cycle.
```

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2390817.20Cycle.20detected.20when.20computing.20whether.20impls.20speciali.E2.80.A6)) to this old issue. Can only reproduce the miscompile on the stable rustc channel and not on _beta_ or _nightly_ channel (weird).

@rustbot label -I-prioritize +P-low

**Comment by jakubadamw** [comment]
Fixed in https://github.com/rust-lang/rust/pull/126139 (nightly-2024-06-12, 1.80).

@rustbot label +E-needs-test

**Comment by tiif** [comment]
Closing as per comment https://github.com/rust-lang/rust/pull/161395#issuecomment-5380404399
