### ISSUE TITLE
1.99 beta crater regression: ICE with "item_name: no name for DefPath"

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#161915]
This regression was found by the 1.99 crater run.

<details>
<summary>Error log</summary>

```
[INFO] [stdout] error: internal compiler error: /rustc-dev/f47d5bb13648d5c859f5b438eb7dc834b9729961/compiler/rustc_middle/src/ty/mod.rs:1830:13: item_name: no name for DefPath { data: [DisambiguatedDefPathData { data: TypeNs("param"), disambiguator: 0 }, DisambiguatedDefPathData { data: TypeNs("Parameter"), disambiguator: 0 }, DisambiguatedDefPathData { data: AnonAssocTy("create_form"), disambiguator: 0 }], krate: crate0 }
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stderr] 
[INFO] [stderr] thread 'rustc' (1218) panicked at /rustc-dev/f47d5bb13648d5c859f5b438eb7dc834b9729961/compiler/rustc_middle/src/ty/mod.rs:1830:13:
[INFO] [stderr] Box<dyn Any>
[INFO] [stderr] stack backtrace:
[INFO] [stderr]    0:     0x7415f6aed9d6 - <<std[104cf6e2632825ea]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[7c831bd917ebf35f]::fmt::Display>::fmt
[INFO] [stderr]    1:     0x7415f720ba4f - core[7c831bd917ebf35f]::fmt::write
[INFO] [stderr]    2:     0x7415f8493eec - <std[104cf6e2632825ea]::sys::stdio::unix::Stderr as core[7c831bd917ebf35f]::io::write::Write>::write_fmt
[INFO] [stderr]    3:     0x7415f6ac0e3a - std[104cf6e2632825ea]::panicking::default_hook::{closure#0}
[INFO] [stderr]    4:     0x7415f6ae1c83 - std[104cf6e2632825ea]::panicking::default_hook
[INFO] [stderr]    5:     0x7415f5a5d0ea - std[104cf6e2632825ea]::panicking::update_hook::<alloc[2fdc3f7464fcf288]::boxed::Box<rustc_driver_impl[f4d229a0c8ac5a64]::install_ice_hook::{closure#1}>>::{closure#0}
[INFO] [stderr]    6:     0x7415f6ae2122 - std[104cf6e2632825ea]::panicking::panic_with_hook
[INFO] [stderr]    7:     0x7415f5a8b334 - std[104cf6e2632825ea]::panicking::begin_panic::<rustc_errors[a4cbaee20011b56]::ExplicitBug>::{closure#0}
[INFO] [stderr]    8:     0x7415f5a83dce - std[104cf6e2632825ea]::sys::backtrace::__rust_end_short_backtrace::<std[104cf6e2632825ea]::panicking::begin_panic<rustc_errors[a4cbaee20011b56]::ExplicitBug>::{closure#0}, !>
[INFO] [stderr]    9:     0x7415f5a81f0e - std[104cf6e2632825ea]::panicking::begin_panic::<rustc_errors[a4cbaee20011b56]::ExplicitBug>
[INFO] [stderr]   10:     0x7415f5a96cb1 - <rustc_errors[a4cbaee20011b56]::diagnostic::BugAbort as rustc_errors[a4cbaee20011b56]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
[INFO] [stderr]   11:     0x7415f6025969 - rustc_middle[954fe3e16bec5a04]::util::bug::opt_span_bug_fmt::<rustc_span[8903846d21f6f0d]::span_encoding::Span>::{closure#0}
[INFO] [stderr]   12:     0x7415f6025d62 - rustc_middle[954fe3e16bec5a04]::ty::context::tls::with_opt::<rustc_middle[954fe3e16bec5a04]::util::bug::opt_span_bug_fmt<rustc_span[8903846d21f6f0d]::span_encoding::Span>::{closure#0}, !>::{closure#0}
[INFO] [stderr]   13:     0x7415f6010710 - rustc_middle[954fe3e16bec5a04]::ty::context::tls::with_context_opt::<rustc_middle[954fe3e16bec5a04]::ty::context::tls::with_opt<rustc_middle[954fe3e16bec5a04]::util::bug::opt_span_bug_fmt<rustc_span[8903846d21f6f0d]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
[INFO] [stderr]   14:     0x7415f40e3f34 - rustc_middle[954fe3e16bec5a04]::util::bug::bug_fmt
[INFO] [stderr]   15:     0x7415f67e8471 - <rustc_middle[954fe3e16bec5a04]::ty::context::TyCtxt>::item_name::<rustc_span[8903846d21f6f0d]::def_id::DefId>
[INFO] [stderr]   16:     0x7415f68d92ee - <rustc_trait_selection[8261745d7436e2a6]::error_reporting::TypeErrCtxt>::cmp
[INFO] [stderr]   17:     0x7415f68c54e0 - <rustc_trait_selection[8261745d7436e2a6]::error_reporting::TypeErrCtxt>::values_str
[INFO] [stderr]   18:     0x7415f68c71ac - <rustc_trait_selection[8261745d7436e2a6]::error_reporting::TypeErrCtxt>::note_type_err
[INFO] [stderr]   19:     0x7415f68d4117 - <rustc_trait_selection[8261745d7436e2a6]::error_reporting::TypeErrCtxt>::report_and_explain_type_error
[INFO] [stderr]   20:     0x7415f75bac8f - <rustc_hir_typeck[c090edd6fef8b9e2]::fn_ctxt::FnCtxt>::check_argument_types
[INFO] [stderr]   21:     0x7415f75ac861 - <rustc_hir_typeck[c090edd6fef8b9e2]::fn_ctxt::FnCtxt>::check_expr_method_call
[INFO] [stderr]   22:     0x7415f7547c31 - <rustc_hir_typeck[c090edd6fef8b9e2]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   23:     0x7415f7544470 - <rustc_hir_typeck[c090edd6fef8b9e2]::fn_ctxt::FnCtxt>::check_expr_block
[INFO] [stderr]   24:     0x7415f7547c03 - <rustc_hir_typeck[c090edd6fef8b9e2]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   25:     0x7415f753d674 - <rustc_hir_typeck[c090edd6fef8b9e2]::fn_ctxt::FnCtxt>::check_expr_if
[INFO] [stderr]   26:     0x7415f7549537 - <rustc_hir_typeck[c090edd6fef8b9e2]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   27:     0x7415f7544568 - <rustc_hir_typeck[c090edd6fef8b9e2]::fn_ctxt::FnCtxt>::check_expr_block
[INFO] [stderr]   28:     0x7415f7547c03 - <rustc_hir_typeck[c090edd6fef8b9e2]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
[INFO] [stderr]   29:     0x7415f751f14d - rustc_hir_typeck[c090edd6fef8b9e2]::check::check_fn
[INFO] [stderr]   30:     0x7415f7f1e13d - rustc_hir_typeck[c090edd6fef8b9e2]::typeck_with_inspect::{closure#0}
[INFO] [stderr]   31:     0x7415f7f1c680 - rustc_query_impl[3a4626ca803709b4]::query_vtables::typeck_root::invoke_provider_fn::__rust_begin_short_backtrace
[INFO] [stderr]   32:     0x7415f7f0b435 - rustc_query_impl[3a4626ca803709b4]::execution::try_execute_query::<rustc_data_structures[f9f608bc5ea564a]::vec_cache::VecCache<rustc_span[8903846d21f6f0d]::def_id::LocalDefId, rustc_middle[954fe3e16bec5a04]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[954fe3e16bec5a04]::dep_graph::graph::DepNodeIndex>, false>
[INFO] [stderr]   33:     0x7415f7f0b071 - rustc_query_impl[3a4626ca803709b4]::query_vtables::typeck_root::execute_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   34:     0x7415f74621bf - rustc_mir_build[ab3f0697f3504e24]::thir::pattern::check_match::check_match
[INFO] [stderr]   35:     0x7415f74611a9 - rustc_query_impl[3a4626ca803709b4]::query_vtables::check_match::invoke_provider_fn::__rust_begin_short_backtrace
[INFO] [stderr]   36:     0x7415f81c4dbb - rustc_query_impl[3a4626ca803709b4]::execution::try_execute_query::<rustc_data_structures[f9f608bc5ea564a]::vec_cache::VecCache<rustc_span[8903846d21f6f0d]::def_id::LocalDefId, rustc_middle[954fe3e16bec5a04]::query::erase::ErasedData<[u8; 1usize]>, rustc_middle[954fe3e16bec5a04]::dep_graph::graph::DepNodeIndex>, false>
[INFO] [stderr]   37:     0x7415f81c4b31 - rustc_query_impl[3a4626ca803709b4]::query_vtables::check_match::execute_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   38:     0x7415f7d1f162 - rustc_mir_build[ab3f0697f3504e24]::builder::build_mir_inner_impl
[INFO] [stderr]   39:     0x7415f72218f4 - rustc_mir_transform[6d6fd8fa799b6e3a]::mir_built
[INFO] [stderr]   40:     0x7415f7f0b435 - rustc_query_impl[3a4626ca803709b4]::execution::try_execute_query::<rustc_data_structures[f9f608bc5ea564a]::vec_cache::VecCache<rustc_span[8903846d21f6f0d]::def_id::LocalDefId, rustc_middle[954fe3e16bec5a04]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[954fe3e16bec5a04]::dep_graph::graph::DepNodeIndex>, false>
[INFO] [stderr]   41:     0x7415f7f0b167 - rustc_query_impl[3a4626ca803709b4]::query_vtables::mir_built::execute_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   42:     0x7415f723ca75 - rustc_mir_transform[6d6fd8fa799b6e3a]::ffi_unwind_calls::has_ffi_unwind_calls
[INFO] [stderr]   43:     0x7415f723c447 - rustc_query_impl[3a4626ca803709b4]::query_vtables::has_ffi_unwind_calls::invoke_provider_fn::__rust_begin_short_backtrace
[INFO] [stderr]   44:     0x7415f81c4dbb - rustc_query_impl[3a4626ca803709b4]::execution::try_execute_query::<rustc_data_structures[f9f608bc5ea564a]::vec_cache::VecCache<rustc_span[8903846d21f6f0d]::def_id::LocalDefId, rustc_middle[954fe3e16bec5a04]::query::erase::ErasedData<[u8; 1usize]>, rustc_middle[954fe3e16bec5a04]::dep_graph::graph::DepNodeIndex>, false>
[INFO] [stderr]   45:     0x7415f81c4af1 - rustc_query_impl[3a4626ca803709b4]::query_vtables::has_ffi_unwind_calls::execute_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   46:     0x7415f81af611 - rustc_mir_transform[6d6fd8fa799b6e3a]::mir_promoted
[INFO] [stderr]   47:     0x7415f81af492 - rustc_query_impl[3a4626ca803709b4]::query_vtables::mir_promoted::invoke_provider_fn::__rust_begin_short_backtrace
[INFO] [stderr]   48:     0x7415f7aacc83 - rustc_query_impl[3a4626ca803709b4]::execution::try_execute_query::<rustc_data_structures[f9f608bc5ea564a]::vec_cache::VecCache<rustc_span[8903846d21f6f0d]::def_id::LocalDefId, rustc_middle[954fe3e16bec5a04]::query::erase::ErasedData<[u8; 16usize]>, rustc_middle[954fe3e16bec5a04]::dep_graph::graph::DepNodeIndex>, false>
[INFO] [stderr]   49:     0x7415f7aac5e7 - rustc_query_impl[3a4626ca803709b4]::query_vtables::mir_promoted::execute_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   50:     0x7415f820c691 - rustc_borrowck[9e8b42e9bd840514]::mir_borrowck
[INFO] [stderr]   51:     0x7415f820c4d9 - rustc_query_impl[3a4626ca803709b4]::query_vtables::mir_borrowck::invoke_provider_fn::__rust_begin_short_backtrace
[INFO] [stderr]   52:     0x7415f7f0b435 - rustc_query_impl[3a4626ca803709b4]::execution::try_execute_query::<rustc_data_structures[f9f608bc5ea564a]::vec_cache::VecCache<rustc_span[8903846d21f6f0d]::def_id::LocalDefId, rustc_middle[954fe3e16bec5a04]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[954fe3e16bec5a04]::dep_graph::graph::DepNodeIndex>, false>
[INFO] [stderr]   53:     0x7415f7f0aff9 - rustc_query_impl[3a4626ca803709b4]::query_vtables::mir_borrowck::execute_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   54:     0x7415f85c3c85 - rustc_hir_analysis[7a56d32287b241ae]::collect::type_of::opaque::find_opaque_ty_constraints_for_rpit
[INFO] [stderr]   55:     0x7415f85c3972 - rustc_hir_analysis[7a56d32287b241ae]::collect::type_of::type_of_opaque
[INFO] [stderr]   56:     0x7415f722747d - rustc_query_impl[3a4626ca803709b4]::execution::try_execute_query::<rustc_middle[954fe3e16bec5a04]::query::caches::DefIdCache<rustc_middle[954fe3e16bec5a04]::query::erase::ErasedData<[u8; 8usize]>>, false>
[INFO] [stderr]   57:     0x7415f7716f46 - rustc_query_impl[3a4626ca803709b4]::query_vtables::type_of_opaque::execute_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   58:     0x7415f7705d28 - rustc_hir_analysis[7a56d32287b241ae]::collect::type_of::type_of
[INFO] [stderr]   59:     0x7415f770ac36 - rustc_query_impl[3a4626ca803709b4]::query_vtables::type_of::invoke_provider_fn::__rust_begin_short_backtrace
[INFO] [stderr]   60:     0x7415f722747d - rustc_query_impl[3a4626ca803709b4]::execution::try_execute_query::<rustc_middle[954fe3e16bec5a04]::query::caches::DefIdCache<rustc_middle[954fe3e16bec5a04]::query::erase::ErasedData<[u8; 8usize]>>, false>
[INFO] [stderr]   61:     0x7415f7227123 - rustc_query_impl[3a4626ca803709b4]::query_vtables::type_of::execute_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   62:     0x7415f76468db - <rustc_privacy[165d6f4e2130175a]::ReachEverythingInTheInterfaceVisitor>::ty
[INFO] [stderr]   63:     0x7415f7a87525 - rustc_privacy[165d6f4e2130175a]::effective_visibilities
[INFO] [stderr]   64:     0x7415f849a49a - rustc_query_impl[3a4626ca803709b4]::execution::try_execute_query::<rustc_middle[954fe3e16bec5a04]::query::caches::SingleCache<rustc_middle[954fe3e16bec5a04]::query::erase::ErasedData<[u8; 8usize]>>, false>
[INFO] [stderr]   65:     0x7415f83a1f24 - rustc_query_impl[3a4626ca803709b4]::query_vtables::effective_visibilities::execute_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   66:     0x7415f81d6b3e - rustc_hir_analysis[7a56d32287b241ae]::check::check::check_item_type
[INFO] [stderr]   67:     0x7415f81c579c - rustc_hir_analysis[7a56d32287b241ae]::check::wfcheck::check_well_formed
[INFO] [stderr]   68:     0x7415f81c575f - rustc_query_impl[3a4626ca803709b4]::query_vtables::check_well_formed::invoke_provider_fn::__rust_begin_short_backtrace
[INFO] [stderr]   69:     0x7415f81c4dbb - rustc_query_impl[3a4626ca803709b4]::execution::try_execute_query::<rustc_data_structures[f9f608bc5ea564a]::vec_cache::VecCache<rustc_span[8903846d21f6f0d]::def_id::LocalDefId, rustc_middle[954fe3e16bec5a04]::query::erase::ErasedData<[u8; 1usize]>, rustc_middle[954fe3e16bec5a04]::dep_graph::graph::DepNodeIndex>, false>
[INFO] [stderr]   70:     0x7415f81c4b55 - rustc_query_impl[3a4626ca803709b4]::query_vtables::check_well_formed::execute_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   71:     0x7415f81c2153 - rustc_hir_analysis[7a56d32287b241ae]::check::wfcheck::check_type_wf
[INFO] [stderr]   72:     0x7415f81c204f - rustc_query_impl[3a4626ca803709b4]::query_vtables::check_type_wf::invoke_provider_fn::__rust_begin_short_backtrace
[INFO] [stderr]   73:     0x7415f84995a3 - rustc_query_impl[3a4626ca803709b4]::execution::try_execute_query::<rustc_middle[954fe3e16bec5a04]::query::caches::SingleCache<rustc_middle[954fe3e16bec5a04]::query::erase::ErasedData<[u8; 1usize]>>, false>
[INFO] [stderr]   74:     0x7415f8499353 - rustc_query_impl[3a4626ca803709b4]::query_vtables::check_type_wf::execute_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   75:     0x7415f7907f64 - rustc_hir_analysis[7a56d32287b241ae]::check_crate
[INFO] [stderr]   76:     0x7415f7f0c97a - rustc_interface[ac0d84a5b4fdc1f2]::passes::analysis
[INFO] [stderr]   77:     0x7415f849af0a - rustc_query_impl[3a4626ca803709b4]::execution::try_execute_query::<rustc_middle[954fe3e16bec5a04]::query::caches::SingleCache<rustc_middle[954fe3e16bec5a04]::query::erase::ErasedData<[u8; 0usize]>>, false>
[INFO] [stderr]   78:     0x7415f849aceb - rustc_query_impl[3a4626ca803709b4]::query_vtables::analysis::execute_query_non_incr::__rust_end_short_backtrace
[INFO] [stderr]   79:     0x7415f8567e18 - rustc_interface[ac0d84a5b4fdc1f2]::interface::run_compiler::<(), rustc_driver_impl[f4d229a0c8ac5a64]::run_compiler::{closure#0}>::{closure#2}
[INFO] [stderr]   80:     0x7415f8533524 - std[104cf6e2632825ea]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[ac0d84a5b4fdc1f2]::util::run_in_thread_with_globals<rustc_interface[ac0d84a5b4fdc1f2]::util::run_in_thread_pool_with_globals<rustc_interface[ac0d84a5b4fdc1f2]::interface::run_compiler<(), rustc_driver_impl[f4d229a0c8ac5a64]::run_compiler::{closure#0}>::{closure#2}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
[INFO] [stderr]   81:     0x7415f85332ed - <std[104cf6e2632825ea]::thread::lifecycle::spawn_unchecked<rustc_interface[ac0d84a5b4fdc1f2]::util::run_in_thread_with_globals<rustc_interface[ac0d84a5b4fdc1f2]::util::run_in_thread_pool_with_globals<rustc_interface[ac0d84a5b4fdc1f2]::interface::run_compiler<(), rustc_driver_impl[f4d229a0c8ac5a64]::run_compiler::{closure#0}>::{closure#2}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[7c831bd917ebf35f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
[INFO] [stderr]   82:     0x7415f85d1ec7 - <std[104cf6e2632825ea]::sys::thread::unix::Thread>::new::thread_start
[INFO] [stderr]   83:     0x7415f1a8307a - <unknown>
[INFO] [stderr]   84:     0x7415f1b16534 - clone
[INFO] [stderr]   85:                0x0 - <unknown>
[INFO] [stderr] 
[INFO] [stderr] note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md
[INFO] [stderr] 
[INFO] [stderr] note: rustc 1.99.0-beta.1 (f47d5bb13 2026-08-17) running on x86_64-unknown-linux-gnu
[INFO] [stderr] 
[INFO] [stderr] note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2
[INFO] [stderr] 
[INFO] [stderr] note: some of the compiler flags provided by cargo are hidden
[INFO] [stderr] 
[INFO] [stderr] query stack during panic:
[INFO] [stderr] #0 [typeck_root] type-checking `order::<impl at src/order.rs:33:1: 33:54>::forms`
[INFO] [stderr] #1 [check_match] match-checking `order::<impl at src/order.rs:33:1: 33:54>::forms`
[INFO] [stderr] #2 [mir_built] building MIR for `order::<impl at src/order.rs:33:1: 33:54>::forms`
[INFO] [stderr] #3 [has_ffi_unwind_calls] checking if `order::<impl at src/order.rs:33:1: 33:54>::forms` contains FFI-unwind calls
[INFO] [stderr] #4 [mir_promoted] promoting constants in MIR for `order::<impl at src/order.rs:33:1: 33:54>::forms`
[INFO] [stderr] #5 [mir_borrowck] borrow-checking `order::<impl at src/order.rs:33:1: 33:54>::forms`
[INFO] [stderr] #6 [type_of_opaque] computing type of opaque `order::<impl at src/order.rs:33:1: 33:54>::forms::{opaque#0}`
[INFO] [stderr] #7 [type_of] computing type of `order::<impl at src/order.rs:33:1: 33:54>::forms::{opaque#0}`
[INFO] [stderr] #8 [effective_visibilities] checking effective visibilities
[INFO] [stderr] #9 [check_well_formed] checking that `order::<impl at src/order.rs:23:1: 23:38>` is well-formed
[INFO] [stderr] #10 [check_type_wf] checking that types are well-formed
[INFO] [stderr] #11 [analysis] running analysis passes on crate `werewolf`
[INFO] [stderr] end of query stack
[INFO] [stdout] For more information about this error, try `rustc --explain E0554`.
[INFO] [stdout] 
[INFO] [stderr] error: could not compile `werewolf` (bin "werewolf") due to 1 previous error; 1 warning emitted
```

</details>

https://crater-reports.s3.amazonaws.com/beta-1.99-4/1.99.0-beta.1/gh/Tortoaster.werewolf/log.txt

Note that the affected crate has invalid code (it previously had a normal compile error), and the crate uses an unstable feature.

**Comment by cyrgani** [comment]
smaller:
```rust
trait Parameter {
    fn create() -> impl Form;
}

trait Form {}

fn forms_at_phase<T: Parameter, U: Parameter>() -> impl Form {
    match true {
        true => T::create(),
        false => U::create(),
    }
}
```

bisects to https://github.com/rust-lang/rust/pull/159610

**Comment by theemathas** [comment]
Probably regressed in #159189. cc @estebank (author), @chenyukang (reviewer)

**Comment by apiraino** [comment]
IIUC the first error can be ignored, a `cargo check` fails even after doing what is suggested.
```
[INFO] [stdout] error[E0554]: `#![feature]` may not be used on the beta release channel
[INFO] [stdout]  --> src/main.rs:2:1
[INFO] [stdout]   |
[INFO] [stdout] 2 | #![feature(return_position_impl_trait_in_trait)]
[INFO] [stdout]   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove the attribute
[INFO] [stdout]   |
[INFO] [stdout]   = help: the feature `return_position_impl_trait_in_trait` has been stable since `1.75.0` and no longer requires an attribute to enable
```

The crate does not compile on stable but on beta produces an ICE and the ICE covers any useful error.


EDIT: basically what Tim says 😅

**Comment by chenyukang** [comment]
It's because of try to get name from RPITIT, I will create a PR to fix it.

**Comment by itsjunetime** [comment]
I'm pretty sure that this is the same as #159680 and #161503 - the playground reproducer for #161503 at least doesn't ICE anymore.

**Comment by estebank** [comment]
Fixed in beta by https://github.com/rust-lang/rust/pull/162258
