### PR TITLE
Add `Thread::{into_raw, from_raw}`

### PR DESCRIPTION
**Pull request by ibraheemdev**
Public API:
```rust
#![unstable(feature = "thread_raw", issue = "97523")]

impl Thread {
    pub fn into_raw(self) -> *const ();
    pub unsafe fn from_raw(ptr: *const ()) -> Thread;    
}
```

ACP: https://github.com/rust-lang/libs-team/issues/200

### CODE REVIEW

File: library/std/src/thread/mod.rs [hunk 1]
```diff
@@ -1203,6 +1203,50 @@ impl Thread {
         self.cname().map(|s| unsafe { str::from_utf8_unchecked(s.to_bytes()) })
     }
 
+    /// Consumes the `Thread`, returning a raw pointer.
```
Comment (SabrinaJewson) [inline library/std/src/thread/mod.rs:1206]: You might want to make the guarantees of this pointer more explicit, for example:

* It can’t be round-tripped though `&()`
* Any kind of reading or writing to the address of this pointer should be considered unsound
* The pointer is not valid for anything other than `Thread::from_raw`

**Comment by CryZe** [comment]
Doesn't this make the assumption that a Thread always is a pointer. Is this something that is true (for all future platforms) and we want to publicly guarantee?

File: library/std/src/thread/mod.rs (hunk 1 above)
Comment (saethlin) [reply library/std/src/thread/mod.rs:1206]: > It can’t be round-tripped though `&()`

I don't think this should be documented here. Maybe it should go on the `pointer` type itself, because you should never expect to be able to round-trip a pointer to any type through a reference of any type.

**Comment by ibraheemdev** [comment]
> Doesn't this make the assumption that a Thread always is a pointer. Is this something that is true (for all future platforms) and we want to publicly guarantee?

It does, but given that `Thread` implements `Clone`, and acts as a channel, I think this is a reasonable assumption.

**Comment by saethlin** [comment]
> Doesn't this make the assumption that a Thread always is a pointer.

No, I think all that this requires is that a `Thread`'s identity be able to round-trip through `usize`.

File: library/std/src/thread/mod.rs (hunk 1 above)
Comment (SabrinaJewson) [reply library/std/src/thread/mod.rs:1206]: Well, it would be fine to expect it for `<NonNull<()>>::dangling()`. But it’s still a fair point.

Comment (saethlin) [reply library/std/src/thread/mod.rs:1206]: Making the reference for that case is UB

**Comment by Mark-Simulacrum** [comment]
I'm not personally convinced that stashing these into an AtomicPtr is worth us exposing these opaque conversion functions -- can you say more about the use case perhaps?

It seems like if we want to encourage that kind of pattern exposing the inner Arc more directly might be a better path, though it has its own complexities -- I'm not a fan of the `*const ()` "opaque" pointer in the API here. But adding a full new type representing the inside of a Thread struct isn't trivial, so that might be the right solution.

r? @joshtriplett for libs-api approval of unstable API surface area

**Comment by ibraheemdev** [comment]
@Mark-Simulacrum The use case is a parker/queue that manages notifying threads waiting on a given resource, for example [this thread waker for `block_on`](https://github.com/zesterer/pollster/blob/b9f4ce079ba3a246173d85b81daa1b043013ea0d/src/lib.rs#L42).

**Comment by JohnCSimon** [comment]
ping from triage:
@ibraheemdev 
Returning to you to address build failures.


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

@rustbot author

**Comment by h33p** [comment]
It appears I implemented the same thing in https://github.com/rust-lang/rust/pull/109794. Here's an ACP I created as well: https://github.com/rust-lang/libs-team/issues/200

Also, this should probably be T-libs-api, I don't know if I can do that:

@rustbot label +T-libs-api -T-libs

**Comment by pitaj** [comment]
@joshtriplett ping from triage, no movement for 10 months. What is the status of this PR? Are we waiting on ACP 200?

**Comment by joshtriplett** [comment]
r? libs

**Comment by joshtriplett** [comment]
*takes libs-api hat off*

*puts libs hat on*

*reviews*

@bors r+

**Comment by jieyouxu** [comment]
Failed in https://github.com/rust-lang/rust/pull/129349#issuecomment-2301612152

```
error[E0277]: `core::marker::PhantomPinned` cannot be unpinned
     |
     |
1527 |         Arc::into_raw(Pin::into_inner(self.inner)) as *const ()
     |                       --------------- ^^^^^^^^^^ within `thread::Inner`, the trait `core::marker::Unpin` is not implemented for `core::marker::PhantomPinned`, which is required by `thread::Inner: core::marker::Unpin`
     |                       required by a bound introduced by this call
     |
     = note: consider using the `pin!` macro
             consider using `Box::pin` if you need to access the pinned value outside of the current scope
```

@bors r-

**Comment by tgross35** [comment]
(reopened so this gets its own CI run)

**Comment by WaffleLapkin** [comment]
@ibraheemdev I don't think this is waiting on bors? looks more like waiting on review?

**Comment by WaffleLapkin** [comment]
@ibraheemdev when re-approving a PR that was approved by someone else before, you should use `@bors r=reviewer` (i.e. `@bors r=joshtriplett`). this is not a big deal, but please do use r= in the future.
