### PR TITLE
Make `const_lit_matches_ty` check literal suffixes for exact type match

### PR DESCRIPTION
**Pull request by lapla-cogito**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/152906)*

`const_lit_matches_ty` ignored literal suffixes. This let the `try_lower_anon_const_lit` fast path produce a mistyped `ty::Const::Value`, bypassing the type mismatch error that typeck would otherwise report.

### CODE REVIEW

File: tests/ui/const-generics/mgca/type_const-mismatched-literal-suffix.rs [hunk 1]
```diff
@@ -0,0 +1,10 @@
+//@ compile-flags: --emit=link
```
Comment (lapla-cogito) [inline tests/ui/const-generics/mgca/type_const-mismatched-literal-suffix.rs]: This was required to perform MIR analysis.

File: tests/ui/const-generics/mgca/type_const-mismatched-types.stderr [hunk 2]
```diff
@@ -1,21 +1,3 @@
...
-   |
-LL | type const FREE2: isize = FREE;
-   | ^^^^^^^^^^^^^^^^^^^^^^^ expected `isize`, found `usize`
-
-error[E0308]: mismatched types
-  --> $DIR/type_const-mismatched-types.rs:16:27
-   |
-LL |     type const N: usize = false;
-   |                           ^^^^^ expected `usize`, found `bool`
-
```
Comment (lapla-cogito) [inline tests/ui/const-generics/mgca/type_const-mismatched-types.stderr:18]: This fix, as mentioned above, fixes the ICE while simultaneously reverting the seemingly redundant error output introduced in #152001 (in fact, this ICE was identified as originating from this PR in the original issue).

**Comment by lapla-cogito** [comment]
This change also fixes #152962, so I’ve added a test for it.

File: compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs [hunk 3]
```diff
@@ -2851,6 +2851,7 @@ impl<'tcx> dyn HirTyLowerer<'tcx> + '_ {
             if const_lit_matches_ty(tcx, &l.lit, l.ty, l.neg) {
```
Comment (BoxyUwU) [inline compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2855]: In theory `const_lit_matches_ty` is supposed to check this. Can you look into why that's incorrectly returning `true` for `type const LEN: usize = 0u8`?

Comment (lapla-cogito) [reply compiler/rustc_hir_analysis/src/hir_ty_lowering/mod.rs:2855]: I see! The match arms in `const_lit_matches_ty()` (maybe also introduced in #152001?) for integer and float literals use broad patterns that ignore the literal's suffix. Specifically, the `..` discards the `LitIntType` suffix information entirely, and `ty::Uint(_)` matches any unsigned integer type including `usize`. So for `type const LEN: usize = 0u8`, it returns `true` even though `u8 != usize`.

File: tests/ui/const-generics/mgca/type_const-mismatched-literal-suffix.rs (hunk 1 above)
Comment (lqd) [reply tests/ui/const-generics/mgca/type_const-mismatched-literal-suffix.rs]: Do you mean forcing codegen? If so check out the build-fail directive.

Comment (lapla-cogito) [reply tests/ui/const-generics/mgca/type_const-mismatched-literal-suffix.rs]: > Do you mean forcing codegen?

No, this ICE occurs when rustc reaches the MIR analysis stage despite the presence of type errors. I think the `build-fail` directive is inappropriate here because, IIUC, it first requires the check pass to succeed. However, this test contains type errors that cause the check pass to fail, so compiletest aborts the test before ever reaching the full build where the ICE would occur.

**Comment by lapla-cogito** [comment]
Looking at #153075, I understand that literals will be handled as `ConstArgKind::Literal` (`MgcaDisambiguation::Direct`) instead of `AnonConst`, which means they will go through `lower_const_arg_literal()` rather than `const_lit_matches_ty()` via `try_lower_anon_const_lit()`. This means the same ICE could occur through a different path. Given that, I think there are the following options (though I'm not sure how much should be addressed in this PR 😵  ):

- Add a `const_lit_matches_ty()` check in `lower_const_arg_literal` as well
- Have `lit_to_const()` itself detect the mismatch between the suffixed literal's type and the expected type — this would also fix the ICE
- Taint type-mismatched consts as errors, as Boxy suggests

I'd also be happy to merge the current fix as-is (with an updated commit message, since it would no longer prevent the ICE once #153075 lands) and address the deeper issue in a follow-up PR.

File: tests/ui/const-generics/mgca/type_const-mismatched-literal-suffix.rs [hunk 4]
```diff
@@ -0,0 +1,17 @@
...
+//~^ ERROR the constant `1` is not of type `usize`
+//~| NOTE expected `usize`, found `i32`
+
+fn main() {
+    const { CONST };
+    //~^ ERROR transmuting from 4-byte type to 8-byte type: `i32` -> `usize`
+    //~| NOTE evaluation of `main::{constant#0}` failed here
+    //~| NOTE erroneous constant encountered
+    //~| NOTE erroneous constant encountered
+    //~| NOTE duplicate diagnostic emitted due to `-Z deduplicate-diagnostics=no`
```
Comment (lapla-cogito) [inline tests/ui/const-generics/mgca/type_const-mismatched-literal-suffix.rs]: This is redundant, but it should resolve if `lower_const_arg_literal` uses `const_lit_matches_ty` (this will be addressed in a follow-up PR since it should resolve the ICE).

**Comment by lapla-cogito** [comment]
Only x86_64-gnu-llvm-20 produces different errors that cause CI to fail, but TBH, I don't really understand the cause... 🤷
