### PR TITLE
Use equality when relating formal and expected type in arg checking

### LINKED ISSUE #129286: Regression in clone impl of enum with variant that has a field with a bivariant substitution
I tried this code:

```rust
trait Array {
    type Item;
}

trait Platform {
    type Assoc: Array<Item = Self::Assoc2>;
    type Assoc2;
}

struct Message<A, B>
where
    A: Array<Item = B>,
{
    pub field: A,
}

impl<A, B> Clone for Message<A, B>
where
    A: Array<Item = B>,
{
    fn clone(&self) -> Self {
        todo!()
    }
}

fn clone<P: Platform>(x: &Message<P::Assoc, P::Assoc2>) {
    let x: Message<_, _> = Clone::clone(x);
}
```

I expected it to work.

Instead, this happened: 

```
error[E0282]: type annotations needed
  --> src/lib.rs:31:32
   |
31 |     Enum::Variant(Clone::clone(x))
   |                                ^ cannot infer type for reference `&Message<<P as Platform>::Assoc, _>`
```

I regressed this in #129059. I have no idea yet why it's happening! This also could be minimized further, I think.

### PR DESCRIPTION
**Pull request by compiler-errors**
#129059 uncovered an interesting issue in argument checking. When we check arguments, we create three sets of types:
* Formals
* Expected
* Actuals

The **actuals** are the types of the argument expressions themselves. The **formals** are the types from the signature that we're checking. The **expected** types are the formal types, but passed through `expected_inputs_for_expected_outputs`:

https://github.com/rust-lang/rust/blob/a971212545766fdfe0dd68e5d968133f79944a19/compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs#L691-L725

This method attempts to constrain the formal inputs by relating the [expectation](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir_typeck/expectation/enum.Expectation.html) of the call expression and the formal output.

When we check an argument, we get the expression's actual type, and then we first attempt to coerce it to the expected type:

https://github.com/rust-lang/rust/blob/a971212545766fdfe0dd68e5d968133f79944a19/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs#L280-L293

Then we subtype the expected type and the formal type:

https://github.com/rust-lang/rust/blob/a971212545766fdfe0dd68e5d968133f79944a19/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs#L299-L305

However, since we are now recording the right coercion target (since #129059), we now end up recording the expected type to the typeck results, rather than the actual.

Since that expected type was [fudged](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_infer/infer/struct.InferCtxt.html#method.fudge_inference_if_ok), it has fresh variables. And since the expected type is only subtyped against the formal type, if that expected type has a bivariant parameter, it will likely remain unconstrained since `Covariant * Bivariant = Bivariant` according to [xform](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/enum.Variance.html#method.xform). This leads to an unconstrained type variable in writeback.

AFAICT, there's no reason for us to be using subtyping here, though. The expected output is already related to the expectation by subtyping:

https://github.com/rust-lang/rust/blob/a971212545766fdfe0dd68e5d968133f79944a19/compiler/rustc_hir_typeck/src/fn_ctxt/_impl.rs#L713

So the formals don't need "another" indirection of subtyping in the argument checking... So I've changed it to use equality here. We could alternatively fix this by requiring WF for all the expected types to constrain their bivariant parameters, but this seems a bit overkill.

Fixes #129286

### CODE REVIEW

**Comment by compiler-errors** [comment]
I expect the only person who's able to review this to be lcnr, who is gone, but I guess I'll just assign it to them.

r? lcnr

File: tests/ui/coercion/constrain-expectation-in-arg.rs [hunk 1]
```diff
@@ -0,0 +1,19 @@
+//@ check-pass
+
```
Comment (lcnr) [inline tests/ui/coercion/constrain-expectation-in-arg.rs:2]: please add an explanation of what this is testing

**Review by lcnr — COMMENTED** [review]
can you move the computation of `expected_input_tys` into `check_argument_types`? I feel like treating them as potentially detached from the `formal_input_tys` is confusing and what caused this bug

r=me on the core change, if you feel like your refactoring is too invasive, I am going to review it this friday

**Comment by compiler-errors** [comment]
probably not worth that last commit just because it does very little

File: compiler/rustc_hir_typeck/src/callee.rs [hunk 2]
```diff
@@ -502,18 +502,12 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
         let fn_sig = self.normalize(call_expr.span, fn_sig);
 
-        // Call the generic checker.
-        let expected_arg_tys = self.expected_inputs_for_expected_output(
-            call_expr.span,
-            expected,
-            fn_sig.output(),
-            fn_sig.inputs(),
-        );
         self.check_argument_types(
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/callee.rs:505]: why not just pass in the whole `fn_sig` :thinking: we currently always pass in inputs, outputs, and c_variadic manually

File: compiler/rustc_hir_typeck/src/expr.rs [hunk 3]
```diff
@@ -1668,15 +1668,22 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
...
+                    return Err(TypeError::Mismatch);
+                }
+                Ok(self.resolve_vars_if_possible(adt_ty))
+            })
+            .ok()
+        });
+        if let Some(adt_ty_hint) = adt_ty_hint {
+            // re-link the variables that the fudging above can create.
+            self.demand_eqtype(span, adt_ty_hint, adt_ty);
+        }
```
Comment (lcnr) [inline compiler/rustc_hir_typeck/src/expr.rs:1686]: that's weird, why do we first check whether subtyping succeeds to then require equality 🤔 I feel like this can just be a `commit_if_ok` using `eq`

File: compiler/rustc_hir_typeck/src/callee.rs (hunk 2 above)
Comment (lcnr) [reply compiler/rustc_hir_typeck/src/callee.rs:505]: ah, `check_argument_types` is also used during diagnostics 🤔 that code should also be able to use a full error dumm `FnSig` though 🤔

**Review by lcnr — COMMENTED** [review]
some more nits, I think this is already a pretty good improvement 😊

**Comment by compiler-errors** [comment]
@rustbot ready

I don't think any more changes can be done, and if they should, I'd rather do them as follow-ups.

**Comment by compiler-errors** [comment]
@rustbot label +beta-nominated

Fixes a beta regression: https://github.com/rust-lang/rust/issues/130576

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202024-09-26/near/472905175). A backport PR will be authored by the release team at the end of the current development cycle.

@rustbot label +beta-accepted
