### PR TITLE
Ensure enum cast moves

### LINKED ISSUE #102389: `as` cast of non-`Copy` enum is no longer a move
@MinusKelvin noticed this 1.63→1.64 change in https://github.com/rust-lang/rust/issues/102303#issuecomment-1260192064

I tried this code:

```rust
pub enum Enum { A, B, C }
pub fn func(inbounds: &Enum, array: &[i16; 3]) -> i16 {
    array[*inbounds as usize]
}
```

I expected to see this happen: because `Enum` is non-`Copy`, an error about moving out from behind a reference, like happened in 1.63 <https://rust.godbolt.org/z/vGPqbsE6v>
```text
error[E0507]: cannot move out of `*inbounds` which is behind a shared reference
 --> <source>:3:11
  |
3 |     array[*inbounds as usize]
  |           ^^^^^^^^^ move occurs because `*inbounds` has type `Enum`, which does not implement the `Copy` trait
```

Instead, this happened: it compiles fine in 1.64 <https://rust.godbolt.org/z/svsPMxTs8> and in nightly <https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=817f19e95903785423743c2a8466c189>

---

This is probably cased by

Change enum->int casts to not go through MIR casts #96862

which is mentioned in https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1640-2022-09-22

It's unclear to me whether this is intentional under the banner of "`Drop` behaviour", since there's no `Drop` trait involved.

### PR DESCRIPTION
**Pull request by nbdd0121**
Fix #102389

r? @pnkfelix

### CODE REVIEW

File: src/test/run-pass-valgrind/cast-enum-with-dtor.rs [hunk 1]
```diff
@@ -28,7 +28,7 @@ fn main() {
     {
         let e = E::C;
         assert_eq!(e as u32, 2);
-        assert_eq!(FLAG.load(Ordering::SeqCst), 0);
+        assert_eq!(FLAG.load(Ordering::SeqCst), 1);
```
Comment (pnkfelix) [inline src/test/run-pass-valgrind/cast-enum-with-dtor.rs:31]: when I first read this PR, I was concerned that this change to this test does not represent a pure revert of the change in behavior injected by #96862 (see specifically https://github.com/rust-lang/rust/pull/96862/files#diff-7e1f76bb00c9a4c88616e00451baa4b95f56d066d893b0bd781f17dadfcf1338 , which changed a *different* line in this test).

However, @nbdd0121 has pointed out to me that we never intended to specify how drop interacts with casting of C enums, and in fact #97652 made the pre-existing lint against such casts into a future-incompat error. So I am no longer concerned about the change in behavior to this test.

**Comment by pnkfelix** [comment]
Nominating for backport as https://github.com/rust-lang/rust/issues/102389 is a P-critical issue that is both stable-to-stable 

@rustbot label: +beta-nominated +stable-nominated

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-10-20/near/305157065)

@rustbot label +beta-accepted
