### PR TITLE
Partial work on building with Cargo

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
This cherry picks the commits I'm directly approving from #70999, I want to land them so that that PR is smaller.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
cc @luca-barbieri -- just cherry-picking your commits that I want to approve without some further thought / feedback so that we don't need to rebase them and such. These seem definitely good to have :)

@bors r+

Self-approving since I've just cherry-picked @luca-barbieri's commits essentially, with only minor edits to the compiler-rt root.

**Comment by Mark-Simulacrum** [comment]
Cherry-picked one more commit. @bors r+

File: src/librustc_session/lib.rs [hunk 1]
```diff
@@ -3,7 +3,6 @@
 
 // Use the test crate here so we depend on getopts through it. This allow tools to link to both
 // librustc_session and libtest.
```
Comment (ollie27) [inline src/librustc_session/lib.rs:5]: Is this comment still correct?

Comment (Mark-Simulacrum) [reply src/librustc_session/lib.rs:5]: Ah, it might not be, good call. I *think* that tools should continue to work with this PR, but I can try and check locally (and if so update this comment) due to the `pub use getopts` below. If we do have problems in practice then we can workaround them I think.

**Comment by Mark-Simulacrum** [comment]
As best as I can tell clippy/miri do build with this, and rustfmt will likely need to bump it's rustc_session dependency (to stop trying to pull getopts from the sysroot). But I believe the comment isn't correct, so approving (I've pushed an update removing it).

If it turns out that rustfmt or some other tool does in fact need this I believe it should be true that they can use getopts from the rustc_session in the sysroot. But if that's not right, then we can back this out.

@bors r+

File: src/libstd/Cargo.toml [hunk 2]
```diff
@@ -47,7 +47,7 @@ hermit-abi = { version = "0.1.10", features = ['rustc-dep-of-std'] }
 wasi = { version = "0.9.0", features = ['rustc-dep-of-std'], default-features = false }
 
 [features]
-default = ["std_detect_file_io", "std_detect_dlsym_getauxval"]
+default = ["std_detect_file_io", "std_detect_dlsym_getauxval", "panic-unwind"]
```
Comment (eddyb) [inline src/libstd/Cargo.toml:50]: This is somewhat surprising to me, what's the explanation?

Comment (Mark-Simulacrum) [reply src/libstd/Cargo.toml:50]: We need to link to some panic runtime for std to build and I believe bootstrap always builds std with panic-unwind linked in today.

Comment (eddyb) [reply src/libstd/Cargo.toml:50]: Wouldn't this negatively affect some `-Zbuild-std` uses?

File: src/librustc_session/lib.rs [hunk 3]
```diff
@@ -1,10 +1,4 @@
 #![feature(crate_visibility_modifier)]
-#![feature(test)]
-
-// Use the test crate here so we depend on getopts through it. This allow tools to link to both
-// librustc_session and libtest.
-extern crate getopts;
-extern crate test as _;
```
Comment (matthiaskrgr) [inline src/librustc_session/lib.rs:7]: I'm wondering if this broke rustfmt and rls in https://github.com/rust-lang/rust/pull/71059#issuecomment-612676428

Comment (eddyb) [reply src/librustc_session/lib.rs:7]: Oh right link-related `extern crate`s still exist in rustc.

Comment (mati865) [reply src/librustc_session/lib.rs:7]: The error:
```
error[E0464]: multiple matching crates for `getopts`
 --> /cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_session-651.0.0/lib.rs:6:1
  |
6 | extern crate getopts;
  | ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: candidates:
          crate `getopts`: /checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-2a6246002b81ef60.rlib
          crate `getopts`: /checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-c6adfde1f127313e.rlib

error[E0463]: can't find crate for `getopts`
 --> /cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_session-651.0.0/lib.rs:6:1
  |
6 | extern crate getopts;
  | ^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 2 previous errors
```

Comment (Mark-Simulacrum) [reply src/librustc_session/lib.rs:7]: Seems likely, but I'm pretty sure that once y'all bump the autopublished librustc_session crate then things should work. If not, please do let me know, we can re-add this here as needed.
