### ISSUE TITLE
Internal Compiler Error: 'attempt to subtract with overflow', compiler/rustc_session/src/session.rs:478:22

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/rust#84219]
Build `rustc` with overflow checking enabled:
```
RUSTFLAGS="-C overflow-checks=on" ./x.py build --stage 1
```
Then try compiling the following program (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):
```rust
const M;
```

```
$ ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc bug.rs 
error: free constant item without body
 --> bug.rs:1:1
  |
1 | const M;
  | ^^^^^^^-
  |        |
  |        help: provide a definition for the constant: `= <expr>;`

error[E0601]: `main` function not found in crate `bug`
 --> bug.rs:1:1
  |
1 | const M;
  | ^^^^^^^^ consider adding a `main` function to `bug.rs`

thread 'rustc' panicked at 'attempt to subtract with overflow', /home/dwrensha/src/rust/compiler/rustc_session/src/session.rs:475:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.51.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0601`.

```

**Comment by dwrensha** [comment]
The ICE is a regression, introduced in #82720. 

The overflowing subtraction happens here:

https://github.com/rust-lang/rust/blob/0894d1e9067f9df1afe612942e1d93901a6e1d8f/compiler/rustc_session/src/session.rs#L470-L479


cc @matthewjasper @henryboisdequin

**Comment by hyd-dev** [comment]
([`src/test/ui/parser/item-free-const-no-body-semantic-fail.rs`](https://github.com/rust-lang/rust/blob/0894d1e9067f9df1afe612942e1d93901a6e1d8f/src/test/ui/parser/item-free-const-no-body-semantic-fail.rs) and [`src/test/ui/parser/item-free-static-no-body-semantic-fail.rs`](https://github.com/rust-lang/rust/blob/0894d1e9067f9df1afe612942e1d93901a6e1d8f/src/test/ui/parser/item-free-static-no-body-semantic-fail.rs) can also hit this when `overflow-checks = true`, see https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Test.20failures.20with.20.60overflow-checks.20.3D.20true.60.)

**Comment by hyd-dev** [comment]
([`src/test/ui/parser/item-free-const-no-body-semantic-fail.rs`](https://github.com/rust-lang/rust/blob/0894d1e9067f9df1afe612942e1d93901a6e1d8f/src/test/ui/parser/item-free-const-no-body-semantic-fail.rs) and [`src/test/ui/parser/item-free-static-no-body-semantic-fail.rs`](https://github.com/rust-lang/rust/blob/0894d1e9067f9df1afe612942e1d93901a6e1d8f/src/test/ui/parser/item-free-static-no-body-semantic-fail.rs) can also hit this when `overflow-checks = true`, see https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Test.20failures.20with.20.60overflow-checks.20.3D.20true.60.)

**Comment by apiraino** [comment]
Assigning priority as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2384219.20Internal.20Compiler.20Error.3A.20'attempt.20to.20subtract.20with.20o.E2.80.A6) and removing `I-prioritize`.

@rustbot label -I-prioritize +P-medium

**Comment by pietroalbini** [comment]
This regression will unfortunately be included in 1.52.0 stable. Updating the labels.

**Comment by ehuss** [comment]
This was discussed a bit on Zulip [here](https://zulip-archive.rust-lang.org/131828tcompiler/09940turningonintegeroverflowcheckingwhenbuildingrustc.html). I did a small amount of investigation, and found that the code that checks if "errors were generated" does not handle stashed errors correctly. It keeps a count of errors, but with stashed errors that count can go up and down at various times.  In this particular case, an error is stashed and then stolen. 

The comment on the relevant function ("Remove this method, it should never be needed.") isn't really clear why it shouldn't be needed.  In general, that error tracking logic needs to change to handle stashed errors correctly.

**Comment by estebank** [comment]
@ehuss `track_errors` is a remnant from when we desired to check at the end of each stage and stop rustc from continuing. This is the easiest and safest course of action, but leads to the "waves of errors" experience. We've been moving away from that, but just removing `track_errors` blindly would cause a bunch of ICEs when codepaths that still assume things are well formed are exercised.
