### ISSUE TITLE
Trait bound requiring the same trait with different lifetimes results in a compile error

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#129950]
I tried this code:

```rust
trait SomeTrait<'a> {}

fn foo<'a, 'b, T: SomeTrait<'a> + SomeTrait<'b>>() {}
```

I expected this code to compile, but instead I got this error:

```
   Compiling playground v0.0.1 (/playground)
error[E0283]: type annotations needed: cannot satisfy `T: SomeTrait<'a>`
 --> src/lib.rs:3:19
  |
3 | fn foo<'a, 'b, T: SomeTrait<'a> + SomeTrait<'b>>() {}
  |                   ^^^^^^^^^^^^^
  |
note: multiple `impl`s or `where` clauses satisfying `T: SomeTrait<'a>` found
 --> src/lib.rs:3:19
  |
3 | fn foo<'a, 'b, T: SomeTrait<'a> + SomeTrait<'b>>() {}
  |                   ^^^^^^^^^^^^^   ^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0283`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Meta

Reproduces on the playground on "Stable version: 1.80.1" and "Nightly version: 1.83.0-nightly (2024-09-03 d6c8169c186ab16a3404)"

This compiles in rust 1.3.0. ICEs in rust 1.4.0-1.6.0. Fails to compile in rust 1.7.0.

**Comment by workingjubilee** [comment]
Oh.

This is https://github.com/rust-lang/rust/pull/30389

**Comment by theemathas** [comment]
@workingjubilee How does this relate to [RFC 1214](https://rust-lang.github.io/rfcs/1214-projections-lifetimes-and-wf.html)? The RFC seems to imply that errors caused by the changes could be fixed by adding more bounds somewhere. And I can't figure out how to add such a bound for this case.

**Comment by compiler-errors** [comment]
If you want to fix this, you need to write `T: for<'r> SomeTrait<'r>`. This is not fixable under the way the type system works today.

**Comment by workingjubilee** [comment]
@theemathas The RFC is incomplete, I refer to this comment:
```rust

                // Typically, this ambiguity should only happen if
                // there are unresolved type inference variables
                // (otherwise it would suggest a coherence
                // failure). But given #21974 that is not necessarily
                // the case -- we can have multiple where clauses that
                // are only distinguished by a region, which results
                // in an ambiguity even when all types are fully
                // known, since we don't dispatch based on region
                // relationships.
```

**Comment by workingjubilee** [comment]
alternatively this could also be considered a duplicate of https://github.com/rust-lang/rust/issues/21974
