### ISSUE TITLE
Can't compile crate that depends on a crate that depends on a proc_macro crate

### ISSUE THREAD

**Issue by Arnavion** [rust-lang/rust#37839]
Windows 7 x64, with rust msvc compiled at 0172e463b0f0c720069d96602209f77c50380066 as well as rustc 1.15.0-nightly (ba872f270 2016-11-17)

It seems a bin/lib crate that depends on a lib crate that in turn depends on a proc macro crate doesn't compile because rustc complains that the proc macro crate was compiled as a dylib.

I have a proc macro crate `foo`, a lib crate `bar` that depends on `foo`, and a bin crate `baz` that depends on `bar`. `bar` compiles fine and generates `libbar.rlib`, but `baz` fails to compile with:

```
error[E0462]: found staticlib `foo` instead of rlib or dylib which `bar` depends on
  --> src\main.rs:1:1
  |
1 | extern crate bar;
  | ^^^^^^^^^^^^^^^^^
  |
  = help: please recompile that crate using --crate-type lib
  = note: crate `foo` path #1: C:\Stuff\Sources\baz\target\debug\deps\foo-7f298898a71a7d96.dll.lib
```

Repro: https://github.com/Arnavion/rust-37839 Run `cargo build` under `baz/`

---

On Linux, since only a .so is generated (no .lib equivalent), the error is different but the cause is presumably the same.

```
error[E0463]: can't find crate for `foo` which `bar` depends on
 --> src/main.rs:1:1
  |
1 | extern crate bar;
  | ^^^^^^^^^^^^^^^^^ can't find crate
```

Note again that this error is when compiling `baz`. There is no problem when compiling `bar`.

**Comment by alexcrichton** [comment]
This appears to be a regression in the range https://github.com/rust-lang/rust/compare/cae6ab1c458ade22b4c228fcd4195917c96e2465...0ed951993

cc @jseyfried any ideas?

**Comment by alexcrichton** [comment]
Note that this isn't Windows-specific, I've reproduced on Linux.

**Comment by jseyfried** [comment]
This was caused by #37542 -- should have used `kind` [here](https://github.com/rust-lang/rust/pull/37542/files#diff-974185a1d0122c6d970a1e4faaedbe5fR348) (like [this](https://github.com/rust-lang/rust/pull/37542/files#diff-974185a1d0122c6d970a1e4faaedbe5fR330)) instead of `PathKind::Crate`.
Fixed in #37846.
