### ISSUE TITLE
alacritty/vte fails to build on rustc master   (mutable references are not allowed in constant functions)

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#79152]
Upstream ticket: https://github.com/alacritty/vte/issues/68

### Code
https://github.com/alacritty/vte/
I tried this code:

```rust
<code>
```

I expected to see this happen: *explanation*
The code compiles on
````
   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.47.0 (18bf6b4f0 2020-10-07)
     beta-x86_64-unknown-linux-gnu unchanged - rustc 1.48.0-beta.10 (8236dc07b 2020-11-15)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.50.0-nightly (f5230fbf7 2020-11-16)
````
but fails to build on rustc master `rustc 1.50.0-nightly (c919f490b 2020-11-17)`
which I assumes makes this a regression:
````
    Checking vte v0.9.0 (/tmp/vte)
error[E0658]: mutable references are not allowed in constant functions
   --> src/table.rs:9:1
    |
9   | / generate_state_changes!(state_changes, {
10  | |     Anywhere {
11  | |         0x18 => (Ground, Execute),
12  | |         0x1a => (Ground, Execute),
...   |
170 | |     }
171 | | });
    | |___^
    |
    = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
    = help: add `#![feature(const_mut_refs)]` to the crate attributes to enable
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
   --> src/table.rs:9:1
    |
9   | / generate_state_changes!(state_changes, {
10  | |     Anywhere {
11  | |         0x18 => (Ground, Execute),
12  | |         0x1a => (Ground, Execute),
...   |
170 | |     }
171 | | });
    | |___^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors
````

### Version it worked on

It most recently worked on: 

### Version with regression

`rustc --version --verbose`:
```
<version>
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by matthiaskrgr** [comment]
cargo-bisect-rustc says the regression is caused by c6a6105bccd5599daf0ecef40c4b5ffa175fc1c1

**Comment by matthiaskrgr** [comment]
Maybe https://github.com/rust-lang/rust/pull/79032 ?

**Comment by jyn514** [comment]
cc @lcnr

**Comment by matthiaskrgr** [comment]
I assume this is the cause of the error: https://github.com/alacritty/vte/blob/master/vte_generate_state_changes/src/lib.rs#L28

**Comment by SNCPlay42** [comment]
MCVE:

```rust
const fn foo() {
    let mut array = [[0; 1]; 1];
    array[0][0] = 1;
}
```

**Comment by SNCPlay42** [comment]
Could be #74989.

**Comment by SNCPlay42** [comment]
Reverting #74989 fixes the regression.

**Comment by spastorino** [comment]
Assigning `P-critical` as [discussed as part of the Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2379152.20alacritty.2Fvte.20fails.20to.20build.20on.20rustc.20m.E2.80.A6) and removing `I-prioritize`.

**Comment by lcnr** [comment]
> I don't think we should use the `Index` impl here but instead keep using builtin indexing

we probably have to update something here:
https://github.com/rust-lang/rust/blob/8d2d0014922e9f541694bfe87642749239990e0e/compiler/rustc_typeck/src/check/writeback.rs#L204-L236
