### ISSUE TITLE
Since 1.33 imports conflict with variable in local scope

### ISSUE THREAD

**Issue by mocsy** [rust-lang/rust#60695]
Since 1.33 imports conflict with variable names which used to work with 1.32 and before.
I found nothing about this in the change logs, so I assume it's a regression.
In Some(...):
```
error[E0308]: mismatched types
   --> src/modules/access/mod.rs:142:21
    |
142 |         if let Some(id) = self.extensions().get::<PermissionBox>() {
    |                     ^^ expected struct `modules::access::PermissionBox`, found struct `schema::access_control::columns::id`
```
In fn params:
`fn get_token(id: i64) -> String`

**Comment by hellow554** [comment]
Can you provide a little example? Some thing simple as

```
mod a {
    // your member her
}

fn main() {
    // your conflicting code here
}
```

**Comment by Mark-Simulacrum** [comment]
Closing as there is insufficient information to reproduce this. Thanks!
