### PR TITLE
Allow `global_asm!` in statement positions (take 2)

### LINKED ISSUE #156760: [ICE]: `could not resolve DefId`
auto-reduced (treereduce-rust):
````rust
fn fun<U>() {
    core::arch::global_asm!("{}", sym<U>::pure);
}

````

original:
````rust
fn fun<U>() {
    core::arch::global_asm!("{}", sym<U>::pure);
}

fn main() {}

````

Version information
````
rustc 1.97.0-nightly (60592ad7c 2026-05-19)
binary: rustc
commit-hash: 60592ad7c63cdb7cfe092f785bb224b655512926
commit-date: 2026-05-19
host: x86_64-unknown-linux-gnu
release: 1.97.0-nightly
LLVM version: 22.1.4

````

Possibly related line of code:
https://github.com/rust-lang/rust/blob/60592ad7c63cdb7cfe092f785bb224b655512926/compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs#L1665-L1677

Command:
`/home/matthias/.rustup/toolchains/master/bin/rustc `

<details><summary><strong>Program output</strong></summary>
<p>

```
error[E0601]: `main` function not found in crate `mvce`
 --> /tmp/icemaker_global_tempdir.eELG3YDCWLcR/rustc_testrunner_tmpdir_reporting.JsbSoBDkXgfp/mvce.rs:3:2
  |
3 | }
  |  ^ consider adding a `main` function to `/tmp/icemaker_global_tempdir.eELG3YDCWLcR/rustc_testrunner_tmpdir_reporting.JsbSoBDkXgfp/mvce.rs`

error: internal compiler error: could not resolve DefId(0:4 ~ mvce[9936]::fun::U)
 --> /tmp/icemaker_global_tempdir.eELG3YDCWLcR/rustc_testrunner_tmpdir_reporting.JsbSoBDkXgfp/mvce.rs:2:39
  |
2 |     core::arch::global_asm!("{}", sym<U>::pure);
  |                                       ^


thread 'rustc' (2508534) panicked at /rustc-dev/60592ad7c63cdb7cfe092f785bb224b655512926/compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:1671:14:
Box<dyn Any>
stack backtrace:
   0:     0x7f5c40e8f769 - <<std[ad415756b38c0d3b]::sys::backtrace::BacktraceLock>::print::DisplayBacktrace as core[3c43f6ff08284740]::fmt::Display>::fmt
   1:     0x7f5c4161fc48 - core[3c43f6ff08284740]::fmt::write
   2:     0x7f5c40ea6456 - <std[ad415756b38c0d3b]::sys::stdio::unix::Stderr as std[ad415756b38c0d3b]::io::Write>::write_fmt
   3:     0x7f5c40e6598e - std[ad415756b38c0d3b]::panicking::default_hook::{closure#0}
   4:     0x7f5c40e830a3 - std[ad415756b38c0d3b]::panicking::default_hook
   5:     0x7f5c3fc817b1 - std[ad415756b38c0d3b]::panicking::update_hook::<alloc[d177848e48595987]::boxed::Box<rustc_driver_impl[4164e2e4872c99f5]::install_ice_hook::{closure#1}>>::{closure#0}
   6:     0x7f5c40e83382 - std[ad415756b38c0d3b]::panicking::panic_with_hook
   7:     0x7f5c3fcaf081 - std[ad415756b38c0d3b]::panicking::begin_panic::<rustc_errors[7308b8b6801eff0]::ExplicitBug>::{closure#0}
   8:     0x7f5c3fca7f66 - std[ad415756b38c0d3b]::sys::backtrace::__rust_end_short_backtrace::<std[ad415756b38c0d3b]::panicking::begin_panic<rustc_errors[7308b8b6801eff0]::ExplicitBug>::{closure#0}, !>
   9:     0x7f5c3fca7ddb - std[ad415756b38c0d3b]::panicking::begin_panic::<rustc_errors[7308b8b6801eff0]::ExplicitBug>
  10:     0x7f5c3fcba561 - <rustc_errors[7308b8b6801eff0]::diagnostic::BugAbort as rustc_errors[7308b8b6801eff0]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  11:     0x7f5c3fd710cc - <rustc_errors[7308b8b6801eff0]::DiagCtxtHandle>::span_bug::<rustc_span[1d2b36215d4b3a94]::span_encoding::Span, alloc[d177848e48595987]::string::String>
  12:     0x7f5c3e290ea7 - rustc_hir[a98e5f59d1d70dd8]::intravisit::walk_qpath::<rustc_hir_analysis[920e2b21ee3cb3b1]::collect::resolve_bound_vars::BoundVarContext>
  13:     0x7f5c3e28ce92 - rustc_hir[a98e5f59d1d70dd8]::intravisit::walk_qpath::<rustc_hir_analysis[920e2b21ee3cb3b1]::collect::resolve_bound_vars::BoundVarContext>
  14:     0x7f5c4231ad56 - rustc_hir[a98e5f59d1d70dd8]::intravisit::walk_expr::<rustc_hir_analysis[920e2b21ee3cb3b1]::collect::resolve_bound_vars::BoundVarContext>
  15:     0x7f5c42319aee - <rustc_hir_analysis[920e2b21ee3cb3b1]::collect::resolve_bound_vars::BoundVarContext>::with::<<rustc_hir_analysis[920e2b21ee3cb3b1]::collect::resolve_bound_vars::BoundVarContext as rustc_hir[a98e5f59d1d70dd8]::intravisit::Visitor>::visit_nested_body::{closure#0}>
  16:     0x7f5c42316727 - rustc_hir[a98e5f59d1d70dd8]::intravisit::walk_item::<rustc_hir_analysis[920e2b21ee3cb3b1]::collect::resolve_bound_vars::BoundVarContext>
  17:     0x7f5c417a906a - rustc_query_impl[f6c0eecf6401915]::query_impl::resolve_bound_vars::invoke_provider_fn::__rust_begin_short_backtrace
  18:     0x7f5c417a8026 - rustc_query_impl[f6c0eecf6401915]::execution::try_execute_query::<rustc_data_structures[56fc8927348ab394]::vec_cache::VecCache<rustc_hir_id[9a89635926ddfe31]::OwnerId, rustc_middle[35b507296d99f42b]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[35b507296d99f42b]::dep_graph::graph::DepNodeIndex>, false>
  19:     0x7f5c417a7c17 - rustc_query_impl[f6c0eecf6401915]::query_impl::resolve_bound_vars::execute_query_non_incr::__rust_end_short_backtrace
  20:     0x7f5c417a8c12 - rustc_query_impl[f6c0eecf6401915]::query_impl::named_variable_map::invoke_provider_fn::__rust_begin_short_backtrace
  21:     0x7f5c417a8026 - rustc_query_impl[f6c0eecf6401915]::execution::try_execute_query::<rustc_data_structures[56fc8927348ab394]::vec_cache::VecCache<rustc_hir_id[9a89635926ddfe31]::OwnerId, rustc_middle[35b507296d99f42b]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[35b507296d99f42b]::dep_graph::graph::DepNodeIndex>, false>
  22:     0x7f5c417a7983 - rustc_query_impl[f6c0eecf6401915]::query_impl::named_variable_map::execute_query_non_incr::__rust_end_short_backtrace
  23:     0x7f5c41cbef3e - <dyn rustc_hir_analysis[920e2b21ee3cb3b1]::hir_ty_lowering::HirTyLowerer>::lower_ty
  24:     0x7f5c4193192d - <rustc_hir_typeck[253df1399b213f63]::fn_ctxt::FnCtxt>::resolve_ty_and_res_fully_qualified_call
  25:     0x7f5c41933eea - <rustc_hir_typeck[253df1399b213f63]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  26:     0x7f5c42d0ef99 - <rustc_hir_typeck[253df1399b213f63]::fn_ctxt::FnCtxt>::check_expr_asm
  27:     0x7f5c419383a3 - <rustc_hir_typeck[253df1399b213f63]::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  28:     0x7f5c41c95838 - rustc_hir_typeck[253df1399b213f63]::typeck_with_inspect::{closure#0}
  29:     0x7f5c41c8c54c - rustc_query_impl[f6c0eecf6401915]::query_impl::typeck_root::invoke_provider_fn::__rust_begin_short_backtrace
  30:     0x7f5c418d2d66 - rustc_query_impl[f6c0eecf6401915]::execution::try_execute_query::<rustc_data_structures[56fc8927348ab394]::vec_cache::VecCache<rustc_span[1d2b36215d4b3a94]::def_id::LocalDefId, rustc_middle[35b507296d99f42b]::query::erase::ErasedData<[u8; 8usize]>, rustc_middle[35b507296d99f42b]::dep_graph::graph::DepNodeIndex>, false>
  31:     0x7f5c418d2643 - rustc_query_impl[f6c0eecf6401915]::query_impl::typeck_root::execute_query_non_incr::__rust_end_short_backtrace
  32:     0x7f5c418d9354 - <rustc_middle[35b507296d99f42b]::ty::context::TyCtxt>::par_hir_body_owners::<rustc_hir_analysis[920e2b21ee3cb3b1]::check_crate::{closure#1}>::{closure#0}
  33:     0x7f5c418d8d2a - rustc_hir_analysis[920e2b21ee3cb3b1]::check_crate
  34:     0x7f5c418d44a1 - rustc_interface[13b9c333f0edbd65]::passes::analysis
  35:     0x7f5c42774f89 - rustc_query_impl[f6c0eecf6401915]::execution::try_execute_query::<rustc_middle[35b507296d99f42b]::query::caches::SingleCache<rustc_middle[35b507296d99f42b]::query::erase::ErasedData<[u8; 0usize]>>, false>
  36:     0x7f5c42774c69 - rustc_query_impl[f6c0eecf6401915]::query_impl::analysis::execute_query_non_incr::__rust_end_short_backtrace
  37:     0x7f5c4279035b - rustc_interface[13b9c333f0edbd65]::interface::run_compiler::<(), rustc_driver_impl[4164e2e4872c99f5]::run_compiler::{closure#0}>::{closure#1}
  38:     0x7f5c42754cc0 - std[ad415756b38c0d3b]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[13b9c333f0edbd65]::util::run_in_thread_with_globals<rustc_interface[13b9c333f0edbd65]::util::run_in_thread_pool_with_globals<rustc_interface[13b9c333f0edbd65]::interface::run_compiler<(), rustc_driver_impl[4164e2e4872c99f5]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  39:     0x7f5c427553ad - <std[ad415756b38c0d3b]::thread::lifecycle::spawn_unchecked<rustc_interface[13b9c333f0edbd65]::util::run_in_thread_with_globals<rustc_interface[13b9c333f0edbd65]::util::run_in_thread_pool_with_globals<rustc_interface[13b9c333f0edbd65]::interface::run_compiler<(), rustc_driver_impl[4164e2e4872c99f5]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[3c43f6ff08284740]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  40:     0x7f5c427561ac - <std[ad415756b38c0d3b]::sys::thread::unix::Thread>::new::thread_start
  41:     0x7f5c3bc981b9 - <unknown>
  42:     0x7f5c3bd1d21c - <unknown>
  43:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: please make sure that you have updated to the latest nightly

note: rustc 1.97.0-nightly (60592ad7c 2026-05-19) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [resolve_bound_vars] resolving lifetimes for `fun::{global_asm#0}`
#1 [named_variable_map] looking up a named region inside `fun::{global_asm#0}`
#2 [typeck_root] type-checking `fun::{global_asm#0}`
#3 [analysis] running analysis passes on crate `mvce`
end of query stack
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0601`.

```

</p>
</details>

### LINKED ISSUE #156894: `global_asm!` in statement position has weird behavior with `Self`
```rust
use std::marker::PhantomData;
use std::arch::global_asm;

struct S<T>(PhantomData<T>);

impl<T> S<T> {
    fn meow(&self) {
        global_asm!("/* {} */", sym Self::meow);
    }
}
```

This code should be forbidden because it uses a generic in `global_asm!`, which isn't meaningful.

Instead, the compiler became confused and was reporting errors about `Sized`.

```
error[E0277]: the size for values of type `T` cannot be known at compilation time
 --> src/lib.rs:8:37
  |
6 | impl<T> S<T> {
  |      - this type parameter needs to be `Sized`
7 |     fn meow(&self) {
8 |         global_asm!("/* {} */", sym Self::meow);
  |                                     ^^^^ doesn't have a size known at compile-time
  |
note: required by an implicit `Sized` bound in `S`
 --> src/lib.rs:4:10
  |
4 | struct S<T>(PhantomData<T>);
  |          ^ required by the implicit `Sized` requirement on this type parameter in `S`
help: consider relaxing the implicit `Sized` restriction
  |
4 | struct S<T: ?Sized>(PhantomData<T>);
  |           ++++++++

error[E0599]: the associated function or constant `meow` exists for struct `S<T>`, but its trait bounds were not satisfied
 --> src/lib.rs:8:43
  |
4 | struct S<T>(PhantomData<T>);
  | ----------- associated function or constant `meow` not found for this struct
...
8 |         global_asm!("/* {} */", sym Self::meow);
  |                                           ^^^^ associated function or constant cannot be called on `S<T>` due to unsatisfied trait bounds
  |
note: trait bound `T: Sized` was not satisfied
 --> src/lib.rs:6:6
  |
6 | impl<T> S<T> {
  |      ^  ----
  |      |
  |      unsatisfied trait bound introduced here
help: consider relaxing the type parameter's implicit `Sized` bound
  |
6 | impl<T: ?Sized> S<T> {
  |       ++++++++
```

### Meta
`rustc --version --verbose`:
```
rustc 1.98.0-nightly (23a3312d9 2026-05-23)
binary: rustc
commit-hash: 23a3312d92a1c4ba0373f1e25277be20ba8bb28c
commit-date: 2026-05-23
host: x86_64-unknown-linux-gnu
release: 1.98.0-nightly
LLVM version: 22.1.6
```

Caused by #156582 allowing this position
Potentially related to #156760, a variant that uses turbofish syntax instead
cc #156855 and #156884

@rustbot label +A-global-asm +T-compiler

### PR DESCRIPTION
**Pull request by daxpedda**
Tracking Issue: https://github.com/rust-lang/rust/issues/156965.
Fixes rust-lang/rust#156760 .
Fixes rust-lang/rust#156894.

### Description

Currently `global_asm!` is only allowed in a module root. This feature, `feature(global_asm_statement_position)`, allows it to appear in any position an item can appear.

```rust
mod foo {
    // This was previously the only allowed position.
    global_asm!("");

    fn bar() {
        // Like any item, `Baz` can be added inside a function,
        // but has no relation to the parent function `bar()`.
        struct Baz;

        // This is not allowed today, its what this feature enables.
        global_asm!("");
    }
}
```

This is particularly useful for macros, where you otherwise have to wrap `global_asm!` in `mod foo { global_asm!(...); }`.

### History

Previously discussed on [Zulip](https://rust-lang.zulipchat.com/#narrow/channel/216763-project-inline-asm/topic/Item.20position.20global_asm/with/581784943).

This has been merged in rust-lang/rust#156582 and then reverted in rust-lang/rust#156884 because it was insta-stable. In that time two bugs surfaced: rust-lang/rust#156760 and rust-lang/rust#156894. Both were fixed with rust-lang/rust#156855, which was incorporated here. Thank you @Kokoro2336 and @folkertdev.

### CODE REVIEW

File: compiler/rustc_feature/src/unstable.rs [hunk 1]
```diff
@@ -573,6 +573,8 @@ declare_features! (
     (incomplete, generic_const_parameter_types, "1.87.0", Some(137626)),
     /// Allows any generic constants being used as pattern type range ends
     (incomplete, generic_pattern_types, "1.86.0", Some(136574)),
+    /// Allows `global_asm!` in statement positions.
+    (unstable, global_asm_statement_position, "CURRENT_RUSTC_VERSION", Some(0)),
```
Comment (daxpedda) [inline compiler/rustc_feature/src/unstable.rs]: Add the tracking issue here when we are ready.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/156919/6083f7891b5088184968e050d0eaecc7bcfd2b3d..3ad186f7280e590d6b663ea6f439c8604bbb004a)*

**Comment by folkertdev** [comment]
My understanding of our processes is that this needs some sort of thumbs up from T-lang, so nominating. See [#project-inline-asm > Item position global_asm](https://rust-lang.zulipchat.com/#narrow/channel/216763-project-inline-asm/topic/Item.20position.20global_asm/with/581784943) for extra context.

File: tests/ui/asm/global-asm-sym-generic-param.rs
Comment (folkertdev) [inline tests/ui/asm/global-asm-sym-generic-param.rs:1]: can you also add the example from https://github.com/rust-lang/rust/issues/156894#issuecomment-4532268257 using `PointeeSized`? 

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/156919/6083f7891b5088184968e050d0eaecc7bcfd2b3d..46594bfc942cea8973c68546a2e55b0535e0ff12)*

Comment (daxpedda) [reply tests/ui/asm/global-asm-sym-generic-param.rs:1]: I don't think its necessary, I believe the issue has nothing to do with `PointeeSized` but instead with `Self`, which I have covered in the test.

Let me know if you think otherwise!

Comment (daxpedda) [reply tests/ui/asm/global-asm-sym-generic-param.rs:1]: Just added it regardless of what I said earlier.

File: compiler/rustc_feature/src/unstable.rs [hunk 2]
```diff
@@ -573,6 +573,8 @@ declare_features! (
     (incomplete, generic_const_parameter_types, "1.87.0", Some(137626)),
     /// Allows any generic constants being used as pattern type range ends
     (incomplete, generic_pattern_types, "1.86.0", Some(136574)),
+    /// Allows `global_asm!` in statement positions.
+    (unstable, global_asm_statement_position, "CURRENT_RUSTC_VERSION", Some(156919)),
```
Comment (mejrs) [inline compiler/rustc_feature/src/unstable.rs]: This number should point to an actual tracking issue.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/156919/6083f7891b5088184968e050d0eaecc7bcfd2b3d..074562cb2cda0ecc16652fc65e6e80050dbb6073)*

Comment (folkertdev) [reply compiler/rustc_feature/src/unstable.rs]: Yes, this is waiting on the T-lang thumbs up, but this is likely just a formality so it's fine to open a tracking issue already. We can always close it if for some reason it won't be needed.

Comment (daxpedda) [reply compiler/rustc_feature/src/unstable.rs]: Done: #156965.

**Comment by folkertdev** [comment]
Vibes are good https://hackmd.io/mZFYKMR-R46CznGnFwHkUg#Allow-global_asm-in-statement-positions-take-2-rust156919. TC might provide some more context (we should wait for that before merging) but I think the meeting notes already show some things that need clarification.

Specifically I think the PR description should clarify how this works (i.e. generic functions don't duplicate the `global_asm!` when monomorphized; the item is just always lifted (once) to the top level).

I suspect "statement position" is kind of confusing here, we really mean "item position". I suspect they are the same thing in practice? Maybe make the similarity with defining a function within a function more explicit?

Also can you link the tracking issue in the PR description, and provide a basic description of the feature over there?

**Comment by traviscross** [comment]
We talked about this in the lang call today.  As I mentioned over on the tracking issue, we accepted the lang experiment and I'll champion it.  Thanks @daxpedda and @folkertdev for your efforts here.

And thanks @folkertdev for answering the questions from our minutes.  @scottmcm's question, as I understood it, was "shouldn't this work in the same way as `fn f() { struct S {} }`?"  The answer, I gather, is "that's what this PR does under a feature flag; we currently disallow this particular macro from appearing in statement position".

**Comment by daxpedda** [comment]
I agree that "statement-position" is confusing here and I would rather just change everything to "item-position", that includes the feature name, so `feature(global_asm_item_position)`. Would that be acceptable?

I've added a more complete description in the tracking issue https://github.com/rust-lang/rust/issues/156965 and copied it into the OP here.

I've also added a test to make sure that generic functions don't duplicate the `global_asm!`. Let me know if that test is not sufficient.

File: tests/ui/asm/x86_64/statement-global-asm.rs
Comment (folkertdev) [inline tests/ui/asm/x86_64/statement-global-asm.rs:1]: I think this should be a `codegen-llvm` test that checks that e.g. the `.global bar` line occurs exactly once (and I guess that foo is defined twice.

File: tests/ui/asm/statement-global-asm.rs
Comment (folkertdev) [inline tests/ui/asm/statement-global-asm.rs:1]: maybe also add something like 

```
const _: () = {
    global_asm!("...");
};

static X: () = {
    global_asm!("...");
};
```

which is weird but does work.

File: tests/ui/asm/statement-global-asm-error.rs
Comment (folkertdev) [inline tests/ui/asm/statement-global-asm-error.rs:1]: maybe add

```
unsafe extern "C" {
    global_asm!("...");
}

struct Foo;
impl Foo {
    global_asm!("...");
}
```

this should be rejected

**Review by folkertdev — COMMENTED** [review]
Based on https://doc.rust-lang.org/beta/nightly-rustc/rustc_hir/hir/enum.ItemKind.html at least using "item" seems right? @traviscross  given that T-lang is also responsible for names, do you have thoughts here?

Also for the example, I think it's stronger if you use a nested function definition instead of `struct Baz`.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/156919/8f02e856be945d5d879b2ff9b7d19dd6bfb1c0e5..42f304191e89e870c07428c6202e7460f4e85865)*

**Comment by traviscross** [comment]
> Based on https://doc.rust-lang.org/beta/nightly-rustc/rustc_hir/hir/enum.ItemKind.html at least using "item" seems right? @traviscross given that T-lang is also responsible for names, do you have thoughts here?

Sounds right to me.

**Comment by folkertdev** [comment]
Just checking in here, @daxpedda are you still interested in working on this feature?

**Comment by daxpedda** [comment]
Unfortunately we decided to go a different route in our project so this got deprioritized. But I plan to get back to it quite soonish.
