### ISSUE TITLE
rustdoc: multiple matching crates

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#56901]
https://crater-reports.s3.amazonaws.com/beta-1.32-1/beta-2018-12-05/reg/liquid-0.17.1/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.32-1/beta-2018-12-05/reg/strip-ansi-escapes-0.1.0/log.txt

```
Dec 10 12:33:59.404 INFO [stdout] error[E0464]: multiple matching crates for `liquid`
Dec 10 12:33:59.404 INFO [stdout]  --> /source/README.md:24:1
Dec 10 12:33:59.404 INFO [stdout]   |
Dec 10 12:33:59.404 INFO [stdout] 2 | extern crate liquid;
Dec 10 12:33:59.404 INFO [stdout]   | ^^^^^^^^^^^^^^^^^^^^
Dec 10 12:33:59.404 INFO [stdout]   |
Dec 10 12:33:59.404 INFO [stdout]   = note: candidates:
Dec 10 12:33:59.404 INFO [stdout]           crate `liquid`: /target/debug/deps/libliquid-eeb578747bf01ff6.rlib
Dec 10 12:33:59.404 INFO [stdout]           crate `liquid`: /target/debug/deps/libliquid-83d4a9ea0668f274.rlib
Dec 10 12:33:59.404 INFO [stdout]           crate `liquid`: /target/debug/deps/libliquid-fb59e7eda215bc63.rlib
Dec 10 12:33:59.404 INFO [stdout]           crate `liquid`: /target/debug/deps/libliquid-7ede636d4e4a6eee.rlib
Dec 10 12:33:59.404 INFO [stdout] 
Dec 10 12:33:59.404 INFO [stdout] error[E0463]: can't find crate for `liquid`
Dec 10 12:33:59.404 INFO [stdout]  --> /source/README.md:24:1
Dec 10 12:33:59.404 INFO [stdout]   |
Dec 10 12:33:59.404 INFO [stdout] 2 | extern crate liquid;
Dec 10 12:33:59.404 INFO [stdout]   | ^^^^^^^^^^^^^^^^^^^^ can't find crate
Dec 10 12:33:59.404 INFO [stdout] 
```

**Comment by QuietMisdreavus** [comment]
Caused by https://github.com/rust-lang/rust/pull/54939, cc @pnkfelix @alexcrichton

**Comment by alexcrichton** [comment]
This seems like something that probably worked by luck before. I don't this is enough to revert https://github.com/rust-lang/rust/pull/54939, so may just be a regression that slides.

**Comment by jyn514** [comment]
This works fine on current stable:
```
running 2 tests
test /home/joshua/src/rust/test-rustdoc/liquid-rust/README.md - liquid_rust::Usage (line 24) ... ok
test /home/joshua/src/rust/test-rustdoc/liquid-rust/README.md - liquid_rust::Usage (line 30) ... ok
```

Should the issue be closed?
