### PR TITLE
fix multiple issues when promoting type-test subject

### LINKED ISSUE #107426: Regression 1.66 "`some_fn::{opaque#0}<'_>` does not live long enough"
### Code

Unfortunately I couldn't minimize it further without using a dependency (code can be executed online [here](https://www.rustexplorer.com/b)):

```rust
/*
[dependencies]
sycamore = "0.8.2"
web-sys = "0.3"

*/

use sycamore::prelude::{Scope, View, Html, DomNode, ReadSignal, GenericNode};

pub fn create_toggle_bool<'a>(cx: Scope<'a>, initial: bool) -> (&'a ReadSignal<bool>, impl Fn() + Copy + 'a) {
    // let open = sycamore::prelude::create_signal(cx, false);
    // let open_toggle = || open.set(!*open.get());
    // (open, open_toggle)
    (todo!(), || {})
}

pub fn Foo<G: Html>(cx: Scope) -> View<G> {
    let (open, open_toggle) = create_toggle_bool(cx, false);

    // Uncomment these 2 lines to make it compile (moved out of the function)
    // let open = sycamore::prelude::create_signal(cx, false);
    // let open_toggle = || open.set(!*open.get());

    let a = move |_: web_sys::Event| open_toggle();

    move || {
        let __el = DomNode::text_node("test");
        ::sycamore::generic_node::GenericNode::event(&__el, cx, "click", a);
        __el;
    };

    todo!()
}

fn main() {
}
```

* [`GenericNode`](https://github.com/sycamore-rs/sycamore/blob/0.8.2/packages/sycamore-core/src/generic_node.rs#L38)
* [`DomNode#event`](https://github.com/sycamore-rs/sycamore/blob/0.8.2/packages/sycamore-web/src/dom_node.rs#L326-L336)
* [My failed attempt to reduce it further](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=6354ec84132bddbf7f89d24a32715b09)

The code compiles and runs with 1.66 but fails with 1.67:

```
error: `create_toggle_bool::{opaque#0}<'_>` does not live long enough
  --> src/main.rs:28:9
   |
28 |         ::sycamore::generic_node::GenericNode::event(&__el, cx, "click", a);
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I expect this code to still compile on 1.67

### Version it worked on

1.66

### Version with regression

1.67

```
rustc 1.67.0 (fc594f156 2023-01-24)
binary: rustc
commit-hash: fc594f15669680fa70d255faec3ca3fb507c3405
commit-date: 2023-01-24
host: x86_64-unknown-linux-gnu
release: 1.67.0
LLVM version: 15.0.6
```

### LINKED ISSUE #107516: 1.67 regression with `……::{opaque#0}<'_> does not live long enough` error
Discussed in https://users.rust-lang.org/t/rust-1-67-lifetime-error-compiles-with-1-66-what-changed/88483 and described on https://github.com/zotero/citeproc-rs/issues/154. I can reproduce a regression in 1.67.0 using the current latest commit “[`2ab195a1e6f84f0ff284813ece61dc62096abbfe`](https://github.com/zotero/citeproc-rs/commit/2ab195a1e6f84f0ff284813ece61dc62096abbfe)” in the `zotero/citeproc-rs` repo.

This issue was first incorrectly thought of as a sort of “duplicate” of #107426, since that issue originally claimed a 1.67 regression, too, but actually regressed in 1.66, and on a deliberate soundness fix (#95474).

However, bisection of the above-mentioned commit on `citeproc-rs` points to a different PR, that is
* #103491

Glancing at it, that PR does not look like it’s *supposed* to break anything. @rustbot label regression-from-stable-to-stable, T-compiler, E-needs-mcve

Compilation error
```
error: `QuoteSplitter<'_, impl Iterator<Item = (usize, char)> + '_>::events::{opaque#0}<'_>` does not live long enough
   --> crates/io/src/output/parse_quotes.rs:419:47
    |
419 |                 | MicroNode::Formatted(..) => EachSplitter::Index(Some(ix)),
    |                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: `QuoteSplitter<'_, impl Iterator<Item = (usize, char)> + '_>::events::{opaque#0}<'_>` does not live long enough
   --> crates/io/src/output/parse_quotes.rs:430:21
    |
430 | /                     EachSplitter::Splitter {
431 | |                         index: ix,
432 | |                         splitter,
433 | |                         seen_any: Some(false),
434 | |                     }
    | |_____________________^

error: could not compile `citeproc-io` due to 2 previous errors
```

bisection
````
searched toolchains a28f3c88e50a77bc2a91889241248c4543854e61 through b7bc90fea3b441234a84b49fdafeb75815eebbab


********************************************************************************
Regression in 7fe6f36224e92db6fbde952e0b7e50863161f6ee
********************************************************************************

==================================================================================
= Please file this regression report on the rust-lang/rust GitHub repository     =
=        New issue: https://github.com/rust-lang/rust/issues/new                 =
=     Known issues: https://github.com/rust-lang/rust/issues                     =
= Copy and paste the text below into the issue report thread.  Thanks!           =
==================================================================================

searched nightlies: from nightly-2022-09-10 to nightly-2023-01-20
regressed nightly: nightly-2022-11-22
searched commit range: https://github.com/rust-lang/rust/compare/a28f3c88e50a77bc2a91889241248c4543854e61...b7bc90fea3b441234a84b49fdafeb75815eebbab
regressed commit: https://github.com/rust-lang/rust/commit/7fe6f36224e92db6fbde952e0b7e50863161f6ee

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.5</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --prompt --access github --start 2022-09-10 --end 2023-01-20 --regress error 
```
````

### LINKED ISSUE #108635: error promoting type-tests from closures
The following should pass borrowck: 
```rust
trait Trait {
    type Item<'a>: 'a;
}

fn assert_static<T: 'static>(_: T) {}

fn test_args<I: Trait>() {
    let closure = |a, _b| assert_static(a);
    //~^ ERROR the associated type may not live long enough

    closure(None::<I::Item::<'_>>, &None::<I::Item::<'_>>);
}

fn test_upvars<I: Trait>() {
    let upvars = (None::<I::Item::<'_>>, &None::<I::Item::<'_>>);
    let _closure = || {
        let (a, _b) = upvars;
        assert_static(a);
        //~^ ERROR the associated type may not live long enough
    };
}
```

When promoting the type-test `I::Item::<'_>: 'static` from the closure to the parent function, we fail to do so because we can't express `'_` in terms of universal regions because the corresponding free region doesn't have an `external_name`?:
https://github.com/rust-lang/rust/blob/0b4ba4cf0ed52bb4f1ff9436b9a887fd5f049e6b/compiler/rustc_borrowck/src/region_infer/mod.rs#L1147

@rustbot label C-bug T-types A-NLL NLL-complete A-borrow-checker

### LINKED ISSUE #108639: error promoting type-tests from closures part 2
A variant of #108635 with a different etiology:
```rust
trait Trait {
    type Item<'a>: 'a;
}

fn assert_static<T: 'static>(_: T) {}
fn relate<T>(_: T, _: T) {}

fn test_args<I: Trait>() {
    let closure = |a, b| {
        relate(&a, b);
        assert_static(a);
        //~^ ERROR the associated type may not live long enough
    };
    closure(None::<I::Item::<'_>>, &None::<I::Item::<'_>>);
}
```

In the same context as #108635, we fail to find an equal universal region although there is a one.
https://github.com/rust-lang/rust/blob/0b4ba4cf0ed52bb4f1ff9436b9a887fd5f049e6b/compiler/rustc_borrowck/src/region_infer/mod.rs#L1145

@rustbot label C-bug T-types A-NLL NLL-complete A-borrow-checker

### PR DESCRIPTION
**Pull request by aliemjay**
Multiple interdependent fixes.  See linked issues for a short description of each.

When Promoting a type-test `T: 'a` from within the closure back to its parent function, there are a couple pre-existing bugs and limitations. They were exposed by the recent changes to opaque types because the type-test subject (`T`) is no longer a simple ParamTy.

Commit 1:
Fixes #108635
Fixes #107426

Commit 2:
Fixes #108639

Commit 3:
Fixes #107516

### CODE REVIEW

**Comment by aliemjay** [comment]
r? types

Needs some cleanup and updating comments.
@rustbot @author

**Comment by jackh726** [comment]
Wow @aliemjay. Impressive.

**Comment by jackh726** [comment]
@craterbot check

File: compiler/rustc_middle/src/mir/query.rs [hunk 1]
```diff
@@ -392,16 +385,56 @@ pub enum ClosureOutlivesSubject<'tcx> {
...
+        tcx.fold_regions(self.inner, |r, depth| match r.kind() {
+            ty::ReLateBound(debruijn, br) => {
+                debug_assert_eq!(debruijn, depth);
+                map(ty::RegionVid::new(br.var.index()))
+            }
+            _ => bug!("unexpected region {r:?}"),
+        })
+    }
+}
+
```
Comment (jackh726) [inline compiler/rustc_middle/src/mir/query.rs:440]: I don't really like this hack. Trying to think of a better alternative though.

I think it would be better to "formalize" this in some sense by having some way to have explicit "binders" of the captured regions, Or expanding on the concept of `external_name` a bit.

Comment (aliemjay) [reply compiler/rustc_middle/src/mir/query.rs:440]: Is it a hard-and-fast rule that `ty::Binder` is the only binder for `ReLateBound` regions? I don't think so -- we already have `Canonical<T>` which serves as a binder too. The only limitation is that the type can't implement `TypeFoldable`/Visitable because these only support ty::Binder.

I tweaked it a bit in a later commit to make it more clear.

Comment (jackh726) [reply compiler/rustc_middle/src/mir/query.rs:440]: Yeah, definitely a preexisting problem that's just more pointy now. I think we can land, but we should chat about a followup for this (and if it's something you want to pursue or something we should offload to someone else).

**Comment by jackh726** [comment]
Going to both stable and beta nominate. Unfortunately, we're going to miss the 1.67 stable to backport, but it's probably still worth getting this into 1.68.

File: compiler/rustc_middle/src/mir/query.rs (hunk 1 above)
Comment (aliemjay) [reply compiler/rustc_middle/src/mir/query.rs:440]: I'm happy to work on a followup PR. Let me open an issue to track this..

File: compiler/rustc_middle/src/mir/query.rs [hunk 2]
```diff
@@ -392,16 +385,56 @@ pub enum ClosureOutlivesSubject<'tcx> {
...
+impl<'tcx> ClosureOutlivesSubjectTy<'tcx> {
+    // All regions of `ty` must be of kind `ReVar`
+    // and must point to an early-bound region in the closure's signature.
+    pub fn new(tcx: TyCtxt<'tcx>, ty: Ty<'tcx>) -> Self {
+        let inner = tcx.fold_regions(ty, |r, depth| match r.kind() {
+            ty::ReVar(vid) => {
+                let br = ty::BoundRegion {
+                    var: ty::BoundVar::new(vid.index()),
+                    kind: ty::BrAnon(0u32, None),
```
[the remark this answers is not in the document]
Comment (aliemjay) [reply compiler/rustc_middle/src/mir/query.rs]: yeah I changed it in https://github.com/rust-lang/rust/pull/108691/commits/97381d2f1ef6481e201eb8fb8bbc1c5ddeffb61d.

**Comment by apiraino** [comment]
Beta backport accepted as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202023-03-09/near/340632535)

@rustbot label +beta-accepted

File: compiler/rustc_middle/src/mir/query.rs (hunk 1 above)
Comment (lcnr) [reply compiler/rustc_middle/src/mir/query.rs:440]: > I'm happy to work on a followup PR. Let me open an issue to track this..

did this happen?

Comment (aliemjay) [reply compiler/rustc_middle/src/mir/query.rs:440]: oops I missed that. I've opened #111310.
