### ISSUE TITLE
Rust 1.18 regression, yggie/mach, type annotations needed

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#41806]
https://github.com/yggie/mach

```
brian@ip-10-145-43-250:~/dev/mach⟫ git log -1
commit b1c15026e0f31117d0d54ee6eeaeadd3e94a3d92
Author: Bryan Yap <bryan.yap.mh@gmail.com>
Date:   Tue Jan 3 17:18:11 2017 +0000

    renamed CollisionBody to CollisionObject
```

```
brian@ip-10-145-43-250:/mnt2/dev⟫ rustc +beta -Vv
rustc 1.18.0-beta.1 (4dce67253 2017-04-25)
binary: rustc
commit-hash: 4dce67253d67785c74c8d270c38d774edd0deed8
commit-date: 2017-04-25
host: x86_64-unknown-linux-gnu
release: 1.18.0-beta.1
LLVM version: 3.9

```

```
brian@ip-10-145-43-250:~/dev/mach⟫ cargo +beta test
   Compiling mach v0.0.1 (file:///mnt2/dev/mach)
   Compiling pkg-config v0.3.8
   Compiling log v0.3.6
   Compiling itoa v0.1.1
   Compiling smallvec v0.1.8
error[E0282]: type annotations needed
  --> src/mach_world.rs:23:13
   |
23 |         let world = CustomWorld::new(
   |             ^^^^^
   |             |
   |             consider giving `world` a type
   |             cannot infer type for `custom_world::CustomWorld<collisions::broadphase::brute_force_broadphase::BruteForceBroadphase<collisions::body::Body<dynamics::dynamic_body_extension::DynamicBodyExtension<E>, collisions::narrowphase::null_narrowphase::NullNarrowphase>>, dynamics::solvers::mach_constraint_solver::MachConstraintSolver, collisions::detection::gjkepa::gjk_epa_detection::GJKEPADetection, _, dynamics::integrators::semi_implicit_euler::SemiImplicitEuler, collisions::body::Body<dynamics::dynamic_body_extension::DynamicBodyExtension<E>, collisions::narrowphase::null_narrowphase::NullNarrowphase>>`

   Compiling bitflags v0.7.0
   Compiling xml-rs v0.3.5
   Compiling regex-syntax v0.3.9
error: aborting due to previous error

error: Could not compile `mach`.
Build failed, waiting for other jobs to finish...
error: build failed

```

cc @yggie

**Comment by Mark-Simulacrum** [comment]
Seems to be caused by 84be2df0e9dac63a4e730c4f5652deb872060ad8 (#41236), cc @cengizIO. Note: This may be wrong, experimental bisect tool used.

**Comment by yggie** [comment]
simplest reproduction of the problem based on my codebase: https://is.gd/5JTVVw, looks like it has trouble inferring the types when using a temporary variable

**Comment by nikomatsakis** [comment]
I'm pretty sure this is actually the same as #41677. Will verify.

**Comment by nikomatsakis** [comment]
I can confirm that https://github.com/rust-lang/rust/pull/41716 fixes this problem in my local tests.

**Comment by cengizIO** [comment]
Since we've merged #41716 I think this can be closed.

**Comment by Mark-Simulacrum** [comment]
Agreed; closing. Let us know if anyone can reproduce on recent nightlies.
