### PR TITLE
Prevent to compute Item attributes twice

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
I came across this case when working on another part of rustdoc. Not a game changer but a nice little improvement.

cc @camelid 

r? @jyn514

### CODE REVIEW

**Review by pickfire — APPROVED** [review]
Looks good to me although I am not quite sure where are we calculating item attributes twice.

**Comment by GuillaumeGomez** [comment]
@pickfire We compute them in `Item::from_hir_id_and_parts` and then we replace the `attrs` field with the value returned by `merged_attrs`. :)

**Comment by bugadani** [comment]
And I was asked not to try and improve things around Item ... ;)

File: src/librustdoc/clean/types.rs [hunk 1]
```diff
@@ -140,6 +140,22 @@ impl Item {
         name: Option<Symbol>,
         kind: ItemKind,
         cx: &DocContext<'_>,
+    ) -> Item {
+        Self::from_def_id_and_attrs_and_parts(
+            def_id,
+            name,
+            kind,
+            box cx.tcx.get_attrs(def_id).clean(cx),
```
Comment (bugadani) [inline src/librustdoc/clean/types.rs:148]: How common is the case where attrs are empty? That box can be omitted (by turning the field into Option<Box<>>). I was planning on doing that, but unless it's a bigger change, it could probably be part of this PR.

Comment (GuillaumeGomez) [reply src/librustdoc/clean/types.rs:148]: I wouldn't bet on that to be honest. Trying to be too clever never ends well.

Comment (bugadani) [reply src/librustdoc/clean/types.rs:148]: We'll see, I guess I'll submit a PR anyway. But true, the additional complexity might backfire a bit.

Comment (jyn514) [reply src/librustdoc/clean/types.rs:148]: I don't think I'd call that too clever. @bugadani I'd be interested in seeing that PR :)

**Comment by jyn514** [comment]
@bors rollup=iffy

This affects perf.

**Comment by Dylan-DPC** [comment]
failed in [rollup](https://github.com/rust-lang/rust/pull/82458)

@bors r-

**Comment by jyn514** [comment]
```
error[E0308]: mismatched types
   --> src/librustdoc/clean/types.rs:175:34
    |
175 |             source: source.clean(cx),
    |                                  ^^ types differ in mutability
    |
    = note: expected mutable reference `&mut DocContext<'_>`
                       found reference `&DocContext<'_>`
error[E0308]: mismatched types
   --> src/librustdoc/clean/types.rs:177:57
    |
    |
177 |             visibility: cx.tcx.visibility(def_id).clean(cx),
    |                                                         ^^ types differ in mutability
    |
    = note: expected mutable reference `&mut DocContext<'_>`
                       found reference `&DocContext<'_>`
error: aborting due to 2 previous errors
```
@GuillaumeGomez this had a semantic conflict, it needs to be rebased.

**Comment by GuillaumeGomez** [comment]
Rebased!

@bors: r=jyn514
