### PR TITLE
Use subtyping for `UnsafeFnPointer` coercion, too

### LINKED ISSUE #129285: Can't cast higher-ranked safe fn to (not higher-ranked) unsafe fn ptr
I tried this code:

```rust
fn higher_ranked(ctx: &mut ()) {}

fn main() {
    fn as_unsafe<T>(_: unsafe fn(T)) {}
    as_unsafe(higher_ranked);
}

```

I expected to see it work.

Instead, this happened: 

```
error[E0308]: mismatched types
 --> src/main.rs:5:15
  |
5 |     as_unsafe(higher_ranked);
  |               ^^^^^^^^^^^^^ one type is more general than the other
  |
  = note: expected fn pointer `unsafe fn(&mut ())`
             found fn pointer `unsafe for<'a> fn(&'a mut ())`
```

This regressed in https://github.com/rust-lang/rust/pull/129059. This only happens when coercing from safe to unsafe, not unsafe to unsafe or safe to safe. I probably forgot something about how we construct the adjustment from unsafe to safe fn.

### PR DESCRIPTION
**Pull request by compiler-errors**
I overlooked this in #129059, which changed MIR typechecking to use subtyping for other fn pointer coercions.

Fixes #129285

### CODE REVIEW

**Comment by cjgillot** [comment]
I don't feel comfortable to review this. 
r? lcnr

File: compiler/rustc_borrowck/src/type_check/mod.rs [hunk 1]
```diff
@@ -2043,9 +2043,9 @@ impl<'a, 'tcx> TypeChecker<'a, 'tcx> {
 
                         let ty_fn_ptr_from = tcx.safe_to_unsafe_fn_ty(fn_sig);
 
-                        if let Err(terr) = self.eq_types(
-                            *ty,
+                        if let Err(terr) = self.sub_types(
                             ty_fn_ptr_from,
+                            *ty,
```
Comment (lcnr) [inline compiler/rustc_borrowck/src/type_check/mod.rs:2048]: can you flip the args and check whether there's an existing test which goes from fail to pass to make sure we check for that potential unsoundness?

r=me after that

Comment (compiler-errors) [reply compiler/rustc_borrowck/src/type_check/mod.rs:2048]: Yes, `tests/ui/nll/mir_check_cast_unsafe_fn.rs` checks this, which was added 7 years ago:

```
#![allow(dead_code)]

fn bar<'a>(input: &'a u32, f: fn(&'a u32) -> &'a u32) -> &'static u32 {
    // Here the NLL checker must relate the types in `f` to the types
    // in `g`. These are related via the `UnsafeFnPointer` cast.
    let g: unsafe fn(_) -> _ = f;
    unsafe { g(input) }
    //~^ ERROR lifetime may not live long enough
}

fn main() {}
```
