### PR TITLE
Fix #124275: Implemented Default for Arc<str>

### LINKED ISSUE #124275: `Arc<str>` does not have a `Default` impl
I tried this code:

```rust
    let my_var: Arc<str> = Default::default();
    assert_eq!(my_var, Arc::from(""));
```

I expected to see this happen: 

> Compiles and Runs successfully.

Instead, this happened: 
```rust
error[E0277]: the trait bound `str: Default` is not satisfied
 --> src/main.rs:4:28
  |
4 |     let my_var: Arc<str> = Default::default();
  |                            ^^^^^^^^^^^^^^^^^^ the trait `Default` is not implemented for `str`, which is required by `Arc<str>: Default`
  |
  = help: the following other types implement trait `Default`:
            &str
            &mut str
  = note: required for `Arc<str>` to implement `Default`

For more information about this error, try `rustc --explain E0277`.
```

It does work for `Arc<&str>` but not for `Arc<str>`. This is because `str` doesn't have a Default impl (presumably due to being unsized).

In theory its as "simple" as adding this into the `std/alloc` library, which does pass `./x.py check library/core` on my machine. However this is definitely not the most efficient implementation of the intended result, and perhaps an implementation similar to `impl Default for Box<str>` would suffice more acutely.
```rust
#[cfg(not(no_global_oom_handling))]
impl Default for Arc<str> {
    /// Creates an empty str inside an Arc
    #[inline]
    fn default() -> Self {
        Arc::from("")
    }
}
```

### Meta

`rustc --version --verbose`: `Stable channel: Build using the Stable version: 1.77.2`. 
Applies on nightly: `Nightly channel: Build using the Nightly version: 1.79.0-nightly (2024-04-21 fb898629a26e4acec59c)` also.

### PR DESCRIPTION
**Pull request by Aityz**
This implements ``Default`` for ``Arc<str>`` in ``library/alloc/src/boxed.rs``, fixing #124275

### CODE REVIEW

File: library/alloc/src/boxed.rs [hunk 1]
```diff
@@ -1284,6 +1287,15 @@ impl Default for Box<str> {
     }
 }
 
+#[cfg(not(no_global_oom_handling))]
```
Comment (clubby789) [inline library/alloc/src/boxed.rs:1290]:
```suggestion
#[cfg(all(not(no_global_oom_handling), not(no_rc)))]
```

**Comment by zachs18** [comment]
Is there a particular reason this is done in `library/alloc/src/boxed.rs` and not `library/alloc/src/sync.rs` where `Arc` itself is defined? Implementing it there would make the `cfg(not(no_rc))` not necessary, since `alloc::sync` itself doesn't exist under `--cfg no_rc`.

It might also make sense to implement `Default` for other `Arc<U>` for dynamically-sized types with a default `Box<U>` implementation, such as `[T]`, `CStr`, `OsStr`, though that doesn't have to happen in this PR. Similarly, `Rc<U>` could have default impls for those types, in `library/alloc/src/rc.rs`.

**Comment by Aityz** [comment]
> Is there a particular reason this is done in `library/alloc/src/boxed.rs` and not `library/alloc/src/sync.rs` where `Arc` itself is defined? Implementing it there would make the `cfg(not(no_rc))` not necessary, since `alloc::sync` itself doesn't exist under `--cfg no_rc`.
> 
> It might also make sense to implement `Default` for other `Arc<U>` for dynamically-sized types with a default `Box<U>` implementation, such as `[T]`, `CStr`, `OsStr`, though that doesn't have to happen in this PR. Similarly, `Rc<U>` could have default impls for those types, in `library/alloc/src/rc.rs`.

``boxed.rs`` has implementations for ``Box<str>`` while ``library/alloc/src/sync.rs`` has no implementations like that whatsoever. However, I believe your solution makes more sense.

**Comment by joshtriplett** [comment]
We discussed this in today's libs-api meeting and it seems reasonable.

We *would* like to see the additional impls for:

- `Arc<CStr>`
- `Arc<OsStr>`
- `Rc<str>`
- `Rc<CStr>`
- `Rc<OsStr>`

Starting a libs-api FCP to confirm that we want to approve these six impls:

@rfcbot merge

**Comment by Amanieu** [comment]
> We _would_ like to see the additional impls for:

Also `Rc<[T]>` and `Arc<[T]>`, for symmetry with `Box<[T]>`.

**Comment by Billy-Sheppard** [comment]
> We discussed this in today's libs-api meeting and it seems reasonable.
> 
> We _would_ like to see the additional impls for:
> 
> * `Arc<CStr>`
> * `Arc<OsStr>`
> * `Rc<str>`
> * `Rc<CStr>`
> * `Rc<OsStr>`
> 
> Starting a libs-api FCP to confirm that we want to approve these six impls:

> Also Rc<[T]> and Arc<[T]>, for symmetry with Box<[T]>.

I've implemented these on my branch here https://github.com/Billy-Sheppard/rust/tree/81b0331cc7a298f79ced7aec395510379df8fa1b

However I'm unclear how to get the `OsStr` impl to compile. Should these changes come in, in a separate PR?

```rust 
error[E0117]: only traits defined in the current crate can be implemented for types defined outside of the crate
    --> library/std/src/ffi/os_str.rs:1350:1
     |
1350 | impl Default for Arc<OsStr> {
     | ^^^^^^^^^^^^^^^^^----------
     | |                |
     | |                `Arc` is not defined in the current crate
     | impl doesn't use only types from inside the current crate
     |
     = note: define and implement a trait or new type instead

error[E0117]: only traits defined in the current crate can be implemented for types defined outside of the crate
    --> library/std/src/ffi/os_str.rs:1360:1
     |
1360 | impl Default for Rc<OsStr> {
     | ^^^^^^^^^^^^^^^^^---------
     | |                |
     | |                `Rc` is not defined in the current crate
     | impl doesn't use only types from inside the current crate
     |
     = note: define and implement a trait or new type instead

For more information about this error, try `rustc --explain E0117`.
```

**Comment by zachs18** [comment]
`impl Default for Arc<OsStr>` (or `Rc<OsStr>`) will run into the orphan rules since `OsStr` is in `std`, but `Arc` is from `alloc` and is not `#[fundamental]` like `Box` is. I don't know if there's a rustc magic attribute to ignore impl coherence rules. It *could* probably be worked around with an (unstable) `DefaultInArc` trait (described below). It might make sense to skip `Arc<OsStr>` and `Rc<OsStr>` for now to not block the other ones.

<details> <summary>DefaultInArc</summary>

```rust
// alloc::sync
pub trait DefaultInArc {
    fn default_arc() -> Arc<Self>;
}
impl<T: Default> DefaultInArc for T { /* call T::default() */ }
impl<T> DefaultInArc for [T] { /* empty slice */
impl DefaultInArc for str { /* empty string */ }
impl DefaultInArc for CStr { /* single NUL byte */ }

impl<T: DefaultInArc + ?Sized> Default for Arc<T>;

// std::sync (or maybe std::ffi)
impl DefaultInArc for OsStr { /* empty slice */ }
```

(similar for `DefaultInRc`, or perhaps they could be in the same trait)

This is the same coherence workaround that [`bytemuck::PodInOption`](https://docs.rs/bytemuck/1.15.0/bytemuck/trait.PodInOption.html) uses to allow downstream crates to implement `bytemuck::Pod` for `core::Option<downstream_crate::LocalType>`, which would be disallowed as a direct impl in `downstream_crate`.
</details>

**Comment by Billy-Sheppard** [comment]
> `impl Default for Arc<OsStr>` (or `Rc<OsStr>`) will run into the orphan rules since `OsStr` is in `std`, but `Arc` is from `alloc` and is not `#[fundamental]` like `Box` is. I don't know if there's a rustc magic attribute to ignore impl coherence rules. It _could_ probably be worked around with an (unstable) `DefaultInArc` trait (described below). It might make sense to skip `Arc<OsStr>` and `Rc<OsStr>` for now to not block the other ones.
> 
> DefaultInArc

This is what I assumed was going on. I'll let some others from the `libs-api` team chime in. I'm happy tto put my code in a separate PR for this discussion but didn't want to clobber the OPs work.

**Comment by joshtriplett** [comment]
I would propose we skip the OsStr impls for now due to this issue, and merge the rest.
