### PR TITLE
Change __rust_no_alloc_shim_is_unstable to be a function

### PR DESCRIPTION
**Pull request by dpaoliello**
This fixes a long sequence of issues:

1. A customer reported that building for Arm64EC was broken: #138541
2. This was caused by a bug in my original implementation of Arm64EC support, namely that only functions on Arm64EC need to be decorated with `#` but Rust was decorating statics as well.
3. Once I corrected Rust to only decorate functions, I started linking failures where the linker couldn't find statics exported by dylib dependencies. This was caused by the compiler not marking exported statics in the generated DEF file with `DATA`, thus they were being exported as functions not data.
4. Once I corrected the way that the DEF files were being emitted, the linker started failing saying that it couldn't find `__rust_no_alloc_shim_is_unstable`. This is because the MSVC linker requires the declarations of statics imported from other dylibs to be marked with `dllimport` (whereas it will happily link to functions imported from other dylibs whether they are marked `dllimport` or not).
5. I then made a change to ensure that `__rust_no_alloc_shim_is_unstable` was marked as `dllimport`, but the MSVC linker started emitting warnings that `__rust_no_alloc_shim_is_unstable` was marked as `dllimport` but was declared in an obj file. This is a harmless warning which is a performance hint: anything that's marked `dllimport` must be indirected via an `__imp` symbol so I added a linker arg in the target to suppress the warning.
6. A customer then reported a similar warning when using `lld-link` (<https://github.com/rust-lang/rust/pull/140176#issuecomment-2872448443>). I don't think it was an implementation difference between the two linkers but rather that, depending on the obj that the declaration versus uses of `__rust_no_alloc_shim_is_unstable` landed in we would get different warnings, so I suppressed that warning as well: #140954.
7. Another customer reported that they weren't using the Rust compiler to invoke the linker, thus these warnings were breaking their build: <https://github.com/rust-lang/rust/pull/140176#issuecomment-2881867433>. At that point, my original change was reverted (#141024) leaving Arm64EC broken yet again.

Taking a step back, a lot of these linker issues arise from the fact that `__rust_no_alloc_shim_is_unstable` is marked as `extern "Rust"` in the standard library and, therefore, assumed to be a foreign item from a different crate BUT the Rust compiler may choose to generate it either in the current crate, some other crate that will be statically linked in OR some other crate that will by dynamically imported.

Worse yet, it is impossible while building a given crate to know if `__rust_no_alloc_shim_is_unstable` will statically linked or dynamically imported: it might be that one of its dependent crates is the one with an allocator kind set and thus that crate (which is compiled later) will decide depending if it has any dylib dependencies or not to import `__rust_no_alloc_shim_is_unstable` or generate it. Thus, there is no way to know if the declaration of `__rust_no_alloc_shim_is_unstable` should be marked with `dllimport` or not.

There is a simple fix for all this: there is no reason `__rust_no_alloc_shim_is_unstable` must be a static. It needs to be some symbol that must be linked in; thus, it could easily be a function instead. As a function, there is no need to mark it as `dllimport` when dynamically imported which avoids the entire mess above.

There may be a perf hit for changing the `volatile load` to be a `tail call`, so I'm happy to change that part back (although I question what the codegen of a `volatile load` would look like, and if the backend is going to try to use load-acquire semantics).

Build with this change applied BEFORE #140176 was reverted to demonstrate that there are no linking issues with either MSVC or MinGW: <https://github.com/rust-lang/rust/actions/runs/15078657205>

Incidentally, I fixed `tests/run-make/no-alloc-shim` to work with MSVC as I needed it to be able to test locally (FYI for #128602)

r? @bjorn3 
cc @jieyouxu

### CODE REVIEW

**Comment by bjorn3** [comment]
Do you have a link to the problems you are having?

**Comment by dpaoliello** [comment]
YAML changes were for testing.
@rustbot label -T-infra

File: library/alloc/src/alloc.rs [hunk 1]
```diff
@@ -31,8 +31,14 @@ unsafe extern "Rust" {
     #[rustc_std_internal_symbol]
     fn __rust_alloc_zeroed(size: usize, align: usize) -> *mut u8;
 
+    #[rustc_nounwind]
+    #[rustc_std_internal_symbol]
+    #[cfg(not(bootstrap))]
+    fn __rust_no_alloc_shim_is_unstable();
```
Comment (bjorn3) [inline library/alloc/src/alloc.rs:37]: At the very least this symbol name will need to be changed to prevent UB when someone uses the old definition.

File: library/alloc/src/alloc.rs [hunk 2]
```diff
@@ -88,7 +94,10 @@ pub unsafe fn alloc(layout: Layout) -> *mut u8 {
     unsafe {
         // Make sure we don't accidentally allow omitting the allocator shim in
         // stable code until it is actually stabilized.
+        #[cfg(bootstrap)]
         core::ptr::read_volatile(&__rust_no_alloc_shim_is_unstable);
+        #[cfg(not(bootstrap))]
+        __rust_no_alloc_shim_is_unstable();
```
Comment (bjorn3) [inline library/alloc/src/alloc.rs:100]: Would `read_volatile(__rust_no_alloc_shim_is_unstable.addr().cast::<u8>())` (using the unstable `FnPtr::addr` method) work? Or maybe one of OpenBSD's exploit mitigations would break with that. Do we even care about that?

**Review by bjorn3 — COMMENTED** [review]
How do we handle regular `#[no_mangle]` statics that doesn't cause those linker warnings/errors?

File: compiler/rustc_codegen_gcc/src/allocator.rs [hunk 3]
```diff
@@ -124,34 +124,39 @@ fn create_wrapper_function(
...
+            .iter()
+            .enumerate()
+            .map(|(i, _)| func.get_param(i as i32).to_rvalue())
+            .collect::<Vec<_>>();
+        let ret = context.new_call(None, callee, &args);
+        //llvm::LLVMSetTailCall(ret, True);
+        if output.is_some() {
+            block.end_with_return(None, ret);
+        } else {
+            block.end_with_void_return(None);
```
Comment (antoyo) [inline compiler/rustc_codegen_gcc/src/allocator.rs:156]: There was [a fix](https://github.com/rust-lang/rustc_codegen_gcc/pull/676/files) for that done in the repo of cg_gcc, but since you change the same code anyway, I guess it would be better to have the fix here as well to make sure I don't forget it when fixing the merge conflict.

```suggestion
            block.add_eval(None, ret);
            block.end_with_void_return(None);
```

File: library/alloc/src/alloc.rs (hunk 2 above)
Comment (dpaoliello) [reply library/alloc/src/alloc.rs:100]: That would work for most platforms.

I'm not sure about OpenBSD, but it would certainly cause issues in Xbox kernel-mode, as it loads binaries as Execute-Only (i.e., they are not readable).

Again, I suspect that the volatile read is more expensive than a tail call to empty function as it may generate load-acquire semantics.

I'm not sure if we could get away with just getting the address of the function and not reading from it? Backends might optimize that away though...

File: library/alloc/src/alloc.rs (hunk 1 above)
Comment (dpaoliello) [reply library/alloc/src/alloc.rs:37]: Good point, I'll rename it.

**Comment by dpaoliello** [comment]
> How do we handle regular `#[no_mangle]` statics that doesn't cause those linker warnings/errors?

If the static is exported by one crate and referenced by another, then the compiler knows whether that static will be statically linked or dynamically imported since it can see the dependency chain between the current crate using the static and the declaring crate.

If the static is referenced via an `extern` block, then it is up to the user to correctly decorate it with a `#[link]` attribute. If they get that attribute wrong (mark it as dynamically imported when it is statically linked AND the declaration is in an obj being linked in, not an rlib) then they will see the linker warning.

File: library/alloc/src/alloc.rs (hunk 2 above)
Comment (bjorn3) [reply library/alloc/src/alloc.rs]: Maybe `black_box(__rust_no_alloc_shim_is_unstable as fn())`?

**Comment by bjorn3** [comment]
> If the static is exported by one crate and referenced by another, then the compiler knows whether that static will be statically linked or dynamically imported since it can see the dependency chain between the current crate using the static and the declaring crate.

If the static is defined inside an rlib, and we are currently compiling an rlib, rustc can't know if the static will be statically linked or dynamically imported. Only when we are linking the current rlib into something do we know if the other rlib was statically linked or dynamically linked.

**Comment by dpaoliello** [comment]
> > If the static is exported by one crate and referenced by another, then the compiler knows whether that static will be statically linked or dynamically imported since it can see the dependency chain between the current crate using the static and the declaring crate.
> 
> If the static is defined inside an rlib, and we are currently compiling an rlib, rustc can't know if the static will be statically linked or dynamically imported. Only when we are linking the current rlib into something do we know if the other rlib was statically linked or dynamically linked.

The warning is only emitted if something marked with `dllimport` is declared either in the current obj file or another obj file that is currently being linked: the MSVC linker doesn't complain if it's declared in a static library (.lib or .rlib).

File: library/alloc/src/alloc.rs (hunk 2 above)
Comment (RalfJung) [reply library/alloc/src/alloc.rs]: > Would read_volatile(__rust_no_alloc_shim_is_unstable.addr().cast::<u8>()) (using the unstable FnPtr::addr method) work?

Miri would definitely complain about that.

File: src/tools/miri/src/shims/foreign_items.rs [hunk 4]
```diff
@@ -731,6 +731,10 @@ trait EvalContextExtPriv<'tcx>: crate::MiriInterpCxExt<'tcx> {
                 this.mem_copy(ptr_src, ptr_dest, Size::from_bytes(n), true)?;
                 this.write_pointer(ptr_dest, dest)?;
             }
+            "__rust_no_alloc_shim_is_unstable_v2" => {
```
Comment (RalfJung) [inline src/tools/miri/src/shims/foreign_items.rs:734]: You put this in the section "C memory handling functions". That doesn't seem right.

Putting it with the "Rust allocation" seems best.

File: library/alloc/src/alloc.rs (hunk 2 above)
Comment (dpaoliello) [reply library/alloc/src/alloc.rs]: > Maybe `black_box(__rust_no_alloc_shim_is_unstable as fn())`?

Doesn't work: we get the correct behavior where it is required for linking to work, but then the codegen tests fail as the compiler is not able to optimize away allocations.

**Comment by bjorn3** [comment]
cc @ojeda this will require RfL changes when it lands.

**Comment by ojeda** [comment]
@bjorn3 Thanks for the ping! Currently we only use `core`, not `alloc` (and in the LTSs where we still use `alloc`, we only support a single Rust version) -- would we still need a change?

**Comment by ojeda** [comment]
Good news, then -- thanks for confirming!

**Comment by dpaoliello** [comment]
Ping... this is blocking me from fixing Arm64EC again. Can someone please review the PR?

File: library/alloc/src/alloc.rs [hunk 5]
```diff
@@ -31,8 +31,14 @@ unsafe extern "Rust" {
     #[rustc_std_internal_symbol]
     fn __rust_alloc_zeroed(size: usize, align: usize) -> *mut u8;
 
+    #[rustc_nounwind]
+    #[rustc_std_internal_symbol]
+    #[cfg(not(bootstrap))]
+    fn __rust_no_alloc_shim_is_unstable_v2();
     #[rustc_std_internal_symbol]
+    #[cfg(bootstrap)]
     static __rust_no_alloc_shim_is_unstable: u8;
```
Comment (bjorn3) [inline library/alloc/src/alloc.rs]: `#[cfg(bootstrap)]` is no longer necessary: https://blog.rust-lang.org/inside-rust/2025/05/29/redesigning-the-initial-bootstrap-sequence/

**Review by bjorn3 — APPROVED** [review]
Didn't get around reviewing this PR until now.

r=me with the `#[cfg(bootstrap)]` removed.

File: library/alloc/src/alloc.rs (hunk 5 above)
Comment (dpaoliello) [reply library/alloc/src/alloc.rs]: Oh, nice!
Removed `bootstrap`

File: src/tools/miri/src/shims/extern_static.rs [hunk 6]
```diff
@@ -45,10 +45,6 @@ impl<'tcx> MiriMachine<'tcx> {
 
     /// Sets up the "extern statics" for this machine.
     pub fn init_extern_statics(ecx: &mut MiriInterpCx<'tcx>) -> InterpResult<'tcx> {
-        // "__rust_no_alloc_shim_is_unstable"
-        let val = ImmTy::from_int(0, ecx.machine.layouts.u8); // always 0, value does not matter
-        Self::alloc_extern_static(ecx, "__rust_no_alloc_shim_is_unstable", val)?;
```
Comment (RalfJung) [inline src/tools/miri/src/shims/extern_static.rs:50]: After removing this symbol you'll also have to adjust `tests/pass/alloc-access-tracking.rs` and decrement the alloc id there by 1.

PR CI would have caught this, but strangely did not run here it seems.

Comment (dpaoliello) [reply src/tools/miri/src/shims/extern_static.rs:50]: I believe that adding the PR to the bors queue caused the PR jobs to be cancelled.

Comment (dpaoliello) [reply src/tools/miri/src/shims/extern_static.rs:50]: Fixed.

Comment (RalfJung) [reply src/tools/miri/src/shims/extern_static.rs:50]: > I believe that adding the PR to the bors queue caused the PR jobs to be cancelled.

I doubt it, that would be highly unusual.

**Comment by RalfJung** [comment]
@bors r-
failed in https://github.com/rust-lang/rust/pull/142283

**Comment by dpaoliello** [comment]
@bjorn3 could you please help me understand how this test was passing before?

It's a [linker failure](https://github.com/rust-lang/rust/pull/142283#issuecomment-2958459719) in the `tests/ui/sanitizer/dataflow.rs` test.
```
   = note: /usr/bin/ld: /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/sanitizer/dataflow/a.dataflow.a934cfd234e75439-cgu.0.rcgu.o: in function `_ZN8dataflow4main17h053d7a3d932e2846E.dfsan':
           dataflow.a934cfd234e75439-cgu.0:(.text._ZN8dataflow4main17h053d7a3d932e2846E.dfsan+0x161): undefined reference to `_RNvCsi58mtoTmQEJ_7___rustc35___rust_no_alloc_shim_is_unstable_v2.dfsan'
           collect2: error: ld returned 1 exit status
```

Was the load previously being optimized out? Seems like some of the other tests would have caught that...

**Comment by dpaoliello** [comment]
Oh, interesting, the symbol has a `.dfsan` suffix... so is this a name mangling issue? Or are we supposed to be generating a different symbol name for this case?

**Comment by bjorn3** [comment]
I suspect this sanitizer mangles the names of functions, but not of globals. I think the issue here is that the version script for libstd.so only exported the non-`.dfsan` version, while the executable needs the `.dfsan` version.

**Comment by dpaoliello** [comment]
Ugh, ok, so we need to generate the shim if the crate that would generate the shim has different sanitizers enabled? Or are there some sanitizers that don't change mangling?

**Comment by bjorn3** [comment]
@rcvalle how is the dataflow sanitizer supposed to handle the case where the standard library is compiled without it enabled, but the main executable is compiled with it enabled. Is that supposed to work or does the minimal test that you added work by accident before this PR? And if it is supposed to work, is there a way to predict when the symbol mangling happens such that we can change the version script accordingly?

**Comment by dpaoliello** [comment]
Looks like we could apply the `DisableSanitizerInstrumentation` attribute to it to disable dfsan from messing with it, but there's currently no Rust attribute which maps to that. Doesn't really work with the existing `no_sanitize` attribute since it disables a bunch of different sanitizers.

**Comment by dpaoliello** [comment]
I think that this test is broken. Per [LLVM's docs](https://clang.llvm.org/docs/DataFlowSanitizer.html):

> DFSan requires either all of your code to be instrumented or for uninstrumented functions to be listed as uninstrumented in the [ABI list](https://clang.llvm.org/docs/DataFlowSanitizer.html#abi-list).

We're not doing that as part of this test: `DataFlowSanitizer` requires that either the Standard Library is instrumented OR the Rust Compiler needs to generate an ABI list to indicate that the functions in the Standard Library are uninstrumented.

As an example, glibc is (intended to be) marked an uninstrumented:

> DataFlowSanitizer comes with a default ABI list which is intended to eventually cover the glibc library on Linux

I can't find any MCP or RFC associated with `DataFlowSanitizer`: 
- How is it supposed to interact with the Standard Library? Should it require an instrumented library? Or should it generate the ABI List?
- Should `#[no_sanitize]` be supported? For example, by marking the function with `DisableSanitizerInstrumentation` (which has other side effects)? Or by adding the function to some generated ABI list (not sure if that's sufficient)?

I'd also like to point out that Arm64EC continues to be broken (the final binary can't be linked), and the fix is blocked by this PR, which is blocked by this test. I don't believe that fixing a Tier 2 target should be blocked by an unstable(?) feature.

**Comment by bjorn3** [comment]
Does adding `_R*__rustc*` to https://github.com/rust-lang/rust/blob/master/tests/ui/sanitizer/dataflow-abilist.txt work? That should catch all `#[rustc_std_internal_symbol]` functions.

**Comment by dpaoliello** [comment]
> Does adding `_R*__rustc*` to https://github.com/rust-lang/rust/blob/master/tests/ui/sanitizer/dataflow-abilist.txt work? That should catch all `#[rustc_std_internal_symbol]` functions.

Yep, that worked.

**Comment by rylev** [comment]
The performance changes are more or less a wash so I don't think it necessitates any investigation.

@rustbot label: +perf-regression-triaged
