### ISSUE TITLE
Only the presence of futures-await regresses error-chain-derive

### ISSUE THREAD

**Issue by golddranks** [rust-lang/rust#50050]
Linking the `futures-await` crate and a crate that uses`error-chain-derive` together breaks the build. Here's a simple example: https://github.com/golddranks/test_futures_await_error_chain_derive Either of the two dependencies (`futures-await` and `dotenv`, which uses `error-chain-derive`) builds on its own (using the latest nightly), but together they refuse to build.

This seems to have something to do with the defsite hygiene: `error-chain-derive` is using derive macros 1.1, and the syntax for using it is as follows: (from https://github.com/purpliminal/rust-dotenv/blob/master/src/errors.rs )

```
#[derive(Debug, ErrorChain)]
#[cfg_attr(not(feature = "backtrace"), error_chain(backtrace = "false"))]
pub enum ErrorKind {
    // generic error string, required by derive_error_chain
    Msg(String),
    #[error_chain(custom)]
    #[error_chain(description = r#"|_| "Parsing Error""#)]
    #[error_chain(display = r#"|l| write!(f, "Error parsing line: '{}'", l)"#)]
    LineParse(String),
    #[error_chain(foreign)]
    Io(::std::io::Error),
    #[error_chain(foreign)]
    EnvVar(::std::env::VarError),
}
```
`|l| write!(f, "Error parsing line: '{}'", l)` breaks, because it can't find `f`: `cannot find value f in this scope`

It seems like just the presence of `futures-await` somehow affects how the Derive macros 1.1 hygiene works; however, the derive macros are stable, so this is an undesirable thing.

**Comment by golddranks** [comment]
Looking at the symptoms, likely to be the same bug as https://github.com/rust-lang/rust/issues/50061

**Comment by golddranks** [comment]
This still happens on the latest nightly (`79252ff4e 2018-04-29`), even after the patches https://github.com/rust-lang/rust/pull/50152 and https://github.com/alexcrichton/rust/commit/e9348738fca8c88dca6e343702eaa12ffc8df34c landed.

**Comment by golddranks** [comment]
Ping @petrochenkov @alexcrichton

**Comment by alexcrichton** [comment]
I've updated the OP and issue title to reflect the underlying issue, minimized at https://gist.github.com/alexcrichton/6b4c56549c6732e697eb0aa9986bf398.

The tl;dr; is that a `TokenStream` created through `TokenStream::from_str` (aka parsing code) cannot refer to tokens with the span `Span::call_site()` (nor tokens input to the macro itself). This means that for whatever reason the hygienic context applied to tokens created through parsing strings is *different* than that of `Span::call_site`, exposing "oddness" of hygiene.

@petrochenkov or @nrc, do y'all know where this might be occurring?

**Comment by petrochenkov** [comment]
@alexcrichton 
A guess: this may be a regression from changes in `src/libsyntax/ext/quote.rs` in https://github.com/rust-lang/rust/pull/49154 (`DUMMY_SP` -> `ident.span` for `ast::Ident` and `ast::Lifetime`).
Could you test whether reverting those two lines fixes the regression?
If it doesn't, then I'll try to investigate further sometime during this week.

**Comment by alexcrichton** [comment]
Sure yeah, I will test out that hypothesis tomorrow morning!

**Comment by jan-hudec** [comment]
@alexcrichton,
> The tl;dr; is that a TokenStream created through TokenStream::from_str (aka parsing code) cannot refer to tokens with the span Span::call_site() (nor tokens input to the macro itself). This means that for whatever reason the hygienic context applied to tokens created through parsing strings is different than that of Span::call_site, exposing "oddness" of hygiene.

I am probably missing something, but to me it sounds about right. I would expect manually parsed code to be its own context. That's the hygiene. Similar to literal code in template macros, except proc macros don't have definition site, so the context is simply fresh. To refer to the symbol from the call site, you can replace it with the `Token` from input or manually created with `Span::call_site()`, no?

**Comment by alexcrichton** [comment]
@jan-hudec I think you're right yeah, but the problem is that we've been advocating Macros 1.1 and 1.2 as "hygiene comes later, we're just copy/pasting code". That seems to not be the case and there's actual hygiene involved, which is unintended currently

**Comment by jan-hudec** [comment]
Except if `parse::<TokenStream>` is now made unhygienic, making it hygienic later won't be backward compatible. So it can't be as easy as just copy/pasting code.

**Comment by alexcrichton** [comment]
@jan-hudec oh it was always the intention that stringifcation loses all hygiene information. The upcoming `proc_macro` API is how we'll allow adding hygiene in the future (aka via `Span`)

**Comment by SergioBenitez** [comment]
I'm running into this on multiple projects: it's a show-stopper. I believe this may also be causing https://github.com/SergioBenitez/Rocket/issues/635.

One possible band-aid could be to add a `set_span(&mut self, span: Span)` method to `TokenStream` that sets all internal spans to `span`. Thus, as a work-around, one could do `stream.set_span(Span::call_site());`. I think we'll want such a method when hygiene is implemented in earnest, so it wouldn't hurt to have.

**Comment by SergioBenitez** [comment]
The following `stream` results in the same issue:

```rust
let code: &str = /* some Rust code with an identifier */;
let stream: proc_macro::TokenStream = code.parse().unwrap();
let stream: proc_macro::TokenStream = stream.into_iter()
    .map(|mut tree| { tree.set_span(Span::call_site()); tree })
    .collect();
```

Thus, the `set_span` method wouldn't help. This leads me to believe that the initial diagnosis by @alexcrichton either isn't the root cause of this bug or what I'm experiencing (most similar to https://github.com/rust-lang/rust/issues/50061) is different.

In particular, the issue I have is that name resolution information is lost when a `proc_macro` emits a call to a declarative macro by going through a `TokenStream`. Full reproducible example is below.

In `lib.rs`:

```rust
#![feature(proc_macro)]

extern crate proc_macro;
extern crate proc_macro2;
extern crate syn;
#[macro_use] extern crate quote;

use syn::Ident;
use proc_macro::{Span, TokenStream};
use quote::Tokens;

fn create(ident: &Ident) -> Tokens {
    // // This works.
    // quote!(do_f!(#ident))

    // // This does as well.
    // let new_ident = Ident::from(ident.to_string());
    // quote!(do_f!(#new_ident))

    // // So does this.
    // quote!(do_f!(x))

    // // This does not.
    // let source = format!("do_f!({})", ident);
    // let expr: syn::Expr = syn::parse_str(&source).unwrap();
    // quote!(#expr)

    // // Neither does this.
    // let source = format!("do_f!({})", ident);
    // let stream: proc_macro2::TokenStream = source.parse().unwrap();
    // quote!(#stream)

    // Nor this.
    let source = format!("do_f!({})", ident);
    let stream: proc_macro2::TokenStream = source.parse().unwrap();
    quote_spanned!(Span::call_site() => #stream)
}

#[proc_macro_attribute]
pub fn demo(_args: TokenStream, _input: TokenStream) -> TokenStream {
    let ident = Ident::from("x");
    let expr = create(&ident);
    let tokens: Tokens = quote! {
        macro_rules! do_f {
            ($id:ident) => ($id + 1)
        }

        fn f(#ident: usize) -> usize {
            #expr
        }
    };

    tokens.into()
}
```

In `main.rs`:

```rust
#![feature(proc_macro)]

extern crate codegen;
use codegen::demo;

#[demo] struct X;

fn main() {
    println!("Hello, world!");
}
```

Results in:

```rust
error[E0425]: cannot find value `x` in this scope
 --> src/main.rs:7:1
  |
7 | #[demo]
  | ^^^^^^^ not found in this scope
```

**Comment by SergioBenitez** [comment]
@petrochenkov This appears to be unrelated to whether `macro_rules!` or `macro` is used. The following fails just the same:

```rust
#[proc_macro_attribute]
pub fn demo(_args: TokenStream, _input: TokenStream) -> TokenStream {
    let ident = Ident::from("x");
    let expr = create(&ident);
    let tokens: Tokens = quote! {
        macro do_f($id:ident) {
            $id + 1
        }

        fn f(#ident: usize) -> usize {
            #expr
        }
    };

    tokens.into()
}
```

**Comment by petrochenkov** [comment]
Ok, that's good.
(I still plan to investigate this issue soon, this weekend most likely.)

**Comment by SergioBenitez** [comment]
I did some more testing. I'm using `proc-macro2` in my code, as seen in the example above. It turns out the issue only occurs (cc @alexcrichton, @dtolnay) if the `nightly` feature is enabled. Without it, everything works as expected. This is my temporary work-around.

**Comment by Arnavion** [comment]
Yes, because pm2 without the nightly feature stringifies the input and parses that. Only with the nightly feature does it use pm types directly.

**Comment by petrochenkov** [comment]
OK, here's a fix for the "Updated description" in the original comment:
https://github.com/petrochenkov/rust/commit/ecb73eb053340dacdbc8200207af85f9cb7e1f84

The problem is that the pre-fix behavior was intended - tokens parsed from strings have different context from `Span::call_site`.
They have `Span::macro_rules_def_site` context if I'd have to give it a name - it means that identifiers produced by strings behave like identifiers produced by `macro_rules`.

This means that produced local variables are hygienic, but everything else is not. Moreover, each string is a *different* `macro_rules` so in addition to `Span::call_site` incompatibility you can't refer to local variables generated by one string from expression generated any another string.

Tokens parsed from strings had `Span::call_site` context originally (https://github.com/rust-lang/rust/pull/40939 and before), but then they were changed in https://github.com/rust-lang/rust/pull/43179 (cc @oli-obk) to fix macro backtraces.
I don't think that was a correct and desirable change - we should not pull legacy hygiene machinery into anything related to macros 2.0 (and macros 1.1/1.2 as subsets of macros 2.0) and should not introduce inconsistency between tokens manually generated with `Span::call_site` and parsed from strings. Even [Macro 1.1 RFC](https://github.com/rust-lang/rfcs/blob/master/text/1681-macros-1.1.md) specified that `TokenStream::from_str` should use "same expansion context as the derive attribute itself" (i.e. call-site).

My commit above makes tokens parsed from strings `Span::call_site` again, but breaks macro backtraces, edition hygiene (https://github.com/rust-lang/rust/pull/50307) and it should also break macro detection for lints in clippy because `Span::call_site` is literally the span of the macro call expression, nothing in it tells that it was generated by a macro.
I do think that fixing name resolution is more important that breaking backtraces/clippy, but broken backtraces/clippy are still pretty bad.

---
(Implementation section)

A solution giving both `Span::call_site` name resolution and `Span::def_site` backtraces and macro detection for lints would requires a bit more implementation work.
I think we'd need a new `Mark` kind (`MarkKind::Transparent` or something) that would be stripped before doing resolution for local variables in the same way as `MarkKind::Legacy`s are stripped before resolving other names.
So the new `Mark` would keep all the information about token belonging to a macro necessary for backtraces/edition-hygiene/clippy, but wouldn't affect name resolution in any way - name resolution would be performed as if the span was call-site.
We actually need to modify `Span::call_site` to return a span with this new mark instead of the call-site span literally, so it would affect both parsed and manually created tokens.

**Comment by alexcrichton** [comment]
Thanks for the investigation @petrochenkov! Do you want to open a PR with your fix? I'd agree as well yeah that name resolution comes before backtraces/clippy

**Comment by petrochenkov** [comment]
If I won't be able to implement `MarkKind::Transparent` quickly enough, I'll open a PR with that patch.

**Comment by alexcrichton** [comment]
Ok awesome, thanks @petrochenkov!

**Comment by petrochenkov** [comment]
Some status update: I have an implementation for `MarkKind::Transparent` and it works by itself and interacts with "opaque"/"modern" macros (declarative `macro` or procedural `Span::def_site()`) correctly, but interactions with `macro_rules` are buggy.
In particular stuff like this:
```rust
macro_rules! m {
    () => {
        let_x_transparent!();
        let y = x;
    }
}

m!();
```
generates an "unresolved `x`" error while it shouldn't

So far it looks like I need to really dig into the core hygiene/resolution algorithms to fix this properly, perhaps by refactoring hygiene data in some way in which these opaque/transparent/semi-transparent interactions can be expressed more naturally than the current "syntax context transplantation" technique (see the large comment in `fn apply_mark`).

In the meantime I'll probably just sumbit a PR with the buggy version this weekend.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/51762 is submitted.
(It has the "transparent vs `macro_rules`" issue mentioned in the previous comment fixed.)

**Comment by SergioBenitez** [comment]
Is this fully fixed? We're still seeing issues on https://github.com/SergioBenitez/Rocket/issues/635, and I can also externally confirm that I'm seeing similar issues with other proc-macro/macro interactions.

**Comment by petrochenkov** [comment]
@SergioBenitez 
The issue as described in https://github.com/rust-lang/rust/issues/50050#issuecomment-390520317 is fully fixed and the the snippet from the [issue description](https://github.com/rust-lang/rust/issues/50050#issue-315442154) now works.
There can be other issues, of course, please file a separate ticket with minimized reproduction if something looks like a bug.
