### ISSUE TITLE
Cannot implement trait on type alias involving another trait's associated type

### ISSUE THREAD

**Issue by Ralith** [rust-lang/rust#59407]
When trying to implement `From` for nalgebra types, I discovered the following surprising behavior:

crate2/src/lib.rs
```rust
pub trait Foo {
    type Bar;
}

pub struct Baz;

impl Foo for Baz {
    type Bar = ();
}

pub struct Quux<T>(pub T);

pub type Corge = Quux<<Baz as Foo>::Bar>;
```

crate1/src/lib.rs
```rust
pub struct Grault;

// this doesn't compile
impl From<Grault> for crate2::Corge {
    fn from(x: Grault) -> Self {
        Self(())
    }
}

// but this seemingly equivalent impl works fine
impl From<Grault> for crate2::Quux<()> {
    fn from(x: Grault) -> Self {
        Self(())
    }
}
```

Error:
```
error[E0210]: type parameter `<crate2::Baz as crate2::Foo>::Bar` must be used as the type parameter for some local type (e.g. `MyStruct<<crate2::Baz as crate2::Foo>::Bar>`)
 --> src/lib.rs:3:1
  |
3 | impl From<Grault> for crate2::Corge {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type parameter `<crate2::Baz as crate2::Foo>::Bar` must be used as the type parameter for some local type
  |
  = note: only traits defined in the current crate can be implemented for a type parameter

error: aborting due to previous error

For more information about this error, try `rustc --explain E0210`.
```

The error occurs no matter which crate the type alias is in. In addition to failing at all here being almost certainly incorrect, the error message is strange; `Foo::Bar` is not a type parameter at all!

**Comment by dingxiangfei2009** [comment]
Let me simplify further with the following example. The following snippet gives the same error on `play.rust-lang.org`.
```rust
use crossbeam::channel::Sender; // 0.7.1
impl<T> From<&str> for Sender<T> {
    fn from(_ : &str) -> Self {
        unimplemented!()
    }
}
```
This [explanation](https://users.rust-lang.org/t/only-traits-defined-in-the-current-crate/8227/4) might be helpful.

**Comment by dingxiangfei2009** [comment]
This reproduction works in `rust`@`1.33.0` without any external crates.
```rust
pub trait TR {
    type A;
}
pub struct Q;
impl TR for Q {
    type A = ();
}
pub type QA = <Q as TR>::A;
impl From<&str> for QA {
    fn from(_ : &str) -> Self {
        unimplemented!()
    }
}
```
The message is the following.
```
error[E0210]: type parameter `<Q as TR>::A` must be used as the type parameter for some local type (e.g., `MyStruct<<Q as TR>::A>`)
 --> src/lib.rs:9:1
  |
9 | impl From<&str> for QA {
  | ^^^^^^^^^^^^^^^^^^^^^^ type parameter `<Q as TR>::A` must be used as the type parameter for some local type
  |
  = note: only traits defined in the current crate can be implemented for a type parameter

error: aborting due to previous error
```

Could it be a problem in parsing? The expected value of the `TyKind` here is `Projection` or `UnnormalizedProjection`, but the actual value is `Param`.

**Comment by dingxiangfei2009** [comment]
Okay, I see. `TyKind` is set to `Projection`, but the orphan checker does not normalize the projection.

**Comment by hrydgard** [comment]
Sorry to bump, but is there any progress expected on this? It's a pretty annoying bug.
