### PR TITLE
fix(rustdoc): Color doctest errors

### LINKED ISSUE #148749: doctest errors are no longer colored
```rs
/// ```
/// foo
/// ``` 
fn foo() {}
```
```
$ rustdoc --test lib.rs
---- lib.rs - foo (line 1) stdout ----
error[E0425]: cannot find value `foo` in this scope
 --> lib.rs:2:1
  |
3 | foo
  | ^^^ not found in this scope

error: aborting due to 1 previous error
```
On the `+beta` and `+nightly` channels, the stdout is no longer colored. Using `--color=always` fixes the issue.

Regressed in #147207 cc @Muscraft 

---
@rustbot label +A-doctests +T-rustdoc +regression-from-stable-to-beta

### PR DESCRIPTION
**Pull request by Muscraft**
@fmease's [Deep analysis](https://github.com/rust-lang/rust/issues/148749#issuecomment-3508455278) on the problem
> Yeah, here's a deep analysis by me from a few weeks back of what's going on ([#148101 (comment)](https://github.com/rust-lang/rust/pull/148101#discussion_r2462756875)):
> 
> > […]
> > However, since said PR ([#147207](https://github.com/rust-lang/rust/pull/147207): migrating coloring crates), `HumanEmitter::supports_color()` unconditionally(!) returns `false` (in fact, `Emitter::supports_color` is no longer used by anyone else and should be removed), so there's no reason to keep it. Rephrased, since that PR all compiler diagnostics for doctests are uncolored.
> > You could argue that I should keep it and patch `supports_color` in rustc to "work again". However, I'd rather rework our doctest coloring wholesale in a separate PR. At least before that migration PR, our setup was quite busted:
> > 
> > 1. First of all, it didn't query+set `supports_color` for syntactically invalid doctests, so syntax errors were always shown without color (contrary to e.g., name resolution errors).
> > 2. Second of all, calling `supports_color()` here was quite frankly wrong: Piping the output of `rustdoc … --test` into a file (or `| cat` or whatever) did **not** suppress colors. I'm not actually sure if we can ever address that nicely (without stripping ANSI codes after the fact) since we pass that diagnostic to `libtest`, right? I might very well be wrong here, maybe it's a non-issue.

<hr>

```rust
/// ```
/// foo
/// ``` 
fn foo() {}
```
```
rustdoc --test lib.rs
```

Stable:
stable

Beta:
beta

Nightly:
nightly

After:
after

Note: This will need to be backported to `beta`

Fixes: rust-lang/rust#148749

### CODE REVIEW

File: compiler/rustc_errors/src/emitter.rs [hunk 1]
```diff
@@ -3488,6 +3481,13 @@ pub fn stderr_destination(color: ColorConfig) -> Destination {
     }
 }
 
+pub fn get_stderr_color_choice(color: ColorConfig, stderr: &std::io::Stderr) -> ColorChoice {
+    let choice = color.to_color_choice();
+    // We need to resolve `ColorChoice::Auto` before `Box`ing since
+    // `ColorChoice::Auto` on `dyn Write` will always resolve to `Never`
```
Comment (fmease) [inline compiler/rustc_errors/src/emitter.rs]: Doesn't this comment only make sense inside `stderr_destination`? I would move it back there.

File: src/librustdoc/doctest/make.rs [hunk 2]
```diff
@@ -458,9 +458,12 @@ fn parse_source(
 
     let sm = Arc::new(SourceMap::new(FilePathMapping::empty()));
     let translator = rustc_driver::default_translator();
-    info.supports_color =
-        HumanEmitter::new(stderr_destination(ColorConfig::Auto), translator.clone())
-            .supports_color();
+    let supports_color = match get_stderr_color_choice(ColorConfig::Auto, &std::io::stderr()) {
```
Comment (fmease) [inline src/librustdoc/doctest/make.rs:461]: I should've realized that much earlier: Obviously, like on stable, `rustdoc bad-doctest.rs --test | cat` / `rustdoc bad-doctest.rs --test > file.txt` still leads to colored output because libtest outputs this to stdout while we're querying stderr here.

I consider this a bug but I don't want it to be fixed in this PR since there are some subtleties. E.g., if you pass `--no-capture` (previously known as `--nocapture`) to rustdoc, then both output streams don't get captured meaning querying stderr would actually make sense in that specific case. There are probably some other things that need consideration.

File: compiler/rustc_errors/src/emitter.rs [hunk 3]
```diff
@@ -3488,6 +3481,13 @@ pub fn stderr_destination(color: ColorConfig) -> Destination {
     }
 }
 
+pub fn get_stderr_color_choice(color: ColorConfig, stderr: &std::io::Stderr) -> ColorChoice {
+    let choice = color.to_color_choice();
```
Comment (fmease) [inline compiler/rustc_errors/src/emitter.rs:3487]: I'll provide some more context for other T-rustdoc members. In my opinion `to_color_choice` as used in both rustc & rustdoc is suboptimal as it doesn't harness the full power of crate `anstyle-query` due to the fact that it yields `Never` if the config is `Auto` and stderr is not a terminal meaning `NO_COLOR=1` works but e.g., `CLICOLOR_FORCE=1` doesn't.

That's a separate bug I or Muscraft will deal with in the future, hopefully.

I'm saying all that because I originally wanted to use `CLICOLOR_FORCE=1` in a potential regression test for https://github.com/rust-lang/rust/issues/148749 which requires `--color=auto` (not `--color=always`) which obviously never leads to colored output since it's captured by compiletest, not by the terminal. I wanted to use `CLICOLOR_FORCE=1` to indirectly test `--color=auto` (and have the golden file be an SVG or ANSI codes if that doesn't work out).

That's the reason why there's no regression test. If you have any other ideas, please let me know.

**Review by fmease — APPROVED** [review]
Thanks, one small nit!

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/148834/2636cb4c1328f5a3ab05b8d13a666ac5f3a48a08..6b4460d82a2a862aaefc08e271c90e5a1217fc0e)*

**Comment by fmease** [comment]
@bors rollup

r=me with https://github.com/rust-lang/rust/pull/148834#discussion_r2515842558 addressed in one way or another
