### ISSUE TITLE
ICE: 'assertion failed: !self.substitutions.is_empty()', compiler/rustc_errors/src/lib.rs

### ISSUE THREAD

**Issue by chengniansun** [rust-lang/rust#78651]
### Code

```Rust
use std::result;
impl result {
    fn into_future() -> Err {}
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (4f7612ac1 2020-10-31)
binary: rustc
commit-hash: 4f7612ac1499258025077f1fd05d2f429f9accfb
commit-date: 2020-10-31
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
```

### Error output

```
error[E0573]: expected type, found module `result`
   --> reduced-mutant.rs:2:6
    |
2   |   impl result {
    |        ^^^^^^ help: an enum with a similar name exists: `Result`

error[E0573]: expected type, found variant `Err`
 --> reduced-mutant.rs:3:25
  |
3 |     fn into_future() -> Err {}
  |                         ^^^ not a type
  |
thread 'rustc' panicked at 'assertion failed: !self.substitutions.is_empty()', compiler/rustc_errors/src/lib.rs:173:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (4f7612ac1 2020-10-31) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0573`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error[E0573]: expected type, found module `result`
   --> reduced-mutant.rs:2:6
    |
2   |   impl result {
    |        ^^^^^^ help: an enum with a similar name exists: `Result`

error[E0573]: expected type, found variant `Err`
 --> reduced-mutant.rs:3:25
  |
3 |     fn into_future() -> Err {}
  |                         ^^^ not a type
  |
thread 'rustc' panicked at 'assertion failed: !self.substitutions.is_empty()', compiler/rustc_errors/src/lib.rs:173:9
stack backtrace:
   0: std::panicking::begin_panic
   1: <rustc_errors::emitter::EmitterWriter as rustc_errors::emitter::Emitter>::emit_diagnostic
   2: rustc_errors::HandlerInner::emit_diagnostic
   3: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
   4: rustc_resolve::Resolver::resolve_crate
   5: rustc_interface::passes::configure_and_expand_inner
   6: rustc_interface::passes::configure_and_expand::{{closure}}
   7: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
   8: rustc_interface::passes::configure_and_expand
   9: rustc_interface::queries::Queries::expansion
  10: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  11: rustc_span::with_source_map
  12: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0-nightly (4f7612ac1 2020-10-31) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0573`.
```

</p>
</details>

**NOTE: The bug is found by our work-in-progress compiler testing tool Kira, and the test program is reduced/minimized by [Perses](https://github.com/chengniansun/perses)**

**Comment by fanninpm** [comment]
[Playground link of example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6b6711c234be987cef886ed4ea1ac5c7)

Can you confirm if this still ICEs with the latest nightly?

**Comment by chengniansun** [comment]
```
$ rustc --verbose --version
rustc 1.50.0-nightly (f76ecd066 2020-12-15)
binary: rustc
commit-hash: f76ecd0668fcdb289456cdc72a39ad15467cc454
commit-date: 2020-12-15
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly

$ rustc reduced-mutant.rs
error[E0573]: expected type, found module `result`
   --> reduced-mutant.rs:2:6
    |
2   |   impl result {
    |        ^^^^^^ help: an enum with a similar name exists: `Result`

error[E0573]: expected type, found variant `Err`
 --> reduced-mutant.rs:3:25
  |
3 |     fn into_future() -> Err {}
  |                         ^^^ not a type
  |
thread 'rustc' panicked at 'assertion failed: !self.substitutions.is_empty()', compiler/rustc_errors/src/lib.rs:151:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (f76ecd066 2020-12-15) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0573`.

$ cat reduced-mutant.rs
use std::result;
impl result {
    fn into_future() -> Err {}
}
$
```

**Comment by estebank** [comment]
I think this regression was introduced in https://github.com/rust-lang/rust/pull/72603/files#diff-7e4444c107c648eec7167c8fd88b2665cf1f6e68e2a77d7992001677c09dca81R534

`tool_only_suggestion_with_metadata` needs to be reworked to either have actual substitutions or remove the `assert`ion and likely early return higher up to make sure that substitutions are present when emitting the diagnostic.

**Comment by osa1** [comment]
I think there's another issue as I describe here: https://github.com/rust-lang/rust/issues/82092#issuecomment-778778726

Namely `import_candidate_to_enum_paths` doesn't work as advertised on paths like `std::prelude::v1::Err`, but it's still called on such paths.

Fixing that function (or the call site) would also fix this issue.

**Comment by apiraino** [comment]
Assigning `P-medium` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2378651.20ICE.3A.20'assertion.20failed.3A.20!self.2Esubstitutions.2Eis_empty.E2.80.A6) and removing `I-prioritize`.

**Comment by hameerabbasi** [comment]
The current nightly doesn't reproduce this:

```bash
$ cargo bisect-rustc --test-dir=. --start=2020-01-01 --regress=ice
...
ERROR: the end of the range (nightly-2021-02-17) does not reproduce the regression
```

I think just a testcase needs adding.

**Comment by osa1** [comment]
This still panics with current nightly ee88f46bb5e:

```
$ cat test.rs
use std::result;

impl result {
    fn into_future() -> Err {}
}

$ RUST_BACKTRACE=0 rustc +stage1 test.rs
error[E0573]: expected type, found module `result`
   --> test.rs:3:6
    |
3   | impl result {
    |      ^^^^^^ help: an enum with a similar name exists: `Result`
    |
   ::: /home/omer/rust/rust/library/core/src/result.rs:241:1
    |
241 | pub enum Result<T, E> {
    | --------------------- similarly named enum `Result` defined here

error[E0573]: expected type, found variant `Err`
 --> test.rs:4:25
  |
4 |     fn into_future() -> Err {}
  |                         ^^^ not a type
  |
thread 'rustc' panicked at 'assertion failed: !self.substitutions.is_empty()', compiler/rustc_errors/src/lib.rs:189:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.52.0-dev running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
error: aborting due to previous error

For more information about this error, try `rustc --explain E0573`.
```

**Comment by hameerabbasi** [comment]
This is rather strange.

```bash
$ cargo bisect-rustc --test-dir=. --end=ee88f46bb5e27c4d9f30326e69ff2298dcbeecb1 --regress=ice
...
ERROR: the commit at the end of the range (ee88f46bb5e27c4d9f30326e69ff2298dcbeecb1) does not reproduce the regression
$ cargo build
   Compiling bisect v0.1.0 (/home/habbasi/bisect)
error[E0573]: expected type, found module `result`
   --> src/main.rs:2:6
    |
2   |   impl result {
    |        ^^^^^^ help: an enum with a similar name exists: `Result`

error[E0573]: expected type, found variant `Err`
 --> src/main.rs:3:25
  |
3 |     fn into_future() -> Err {}
  |                         ^^^ not a type
  |
help: try using the variant's enum
  |
3 |     fn into_future() -> core::result::Result {}
  |                         ^^^^^^^^^^^^^^^^^^^^
3 |     fn into_future() -> crate::result::Result {}
  |                         ^^^^^^^^^^^^^^^^^^^^^
3 |     fn into_future() -> std::result::Result {}
  |                         ^^^^^^^^^^^^^^^^^^^

error[E0601]: `main` function not found in crate `bisect`
 --> src/main.rs:1:1
  |
1 | / use std::result;
2 | | impl result {
3 | |     fn into_future() -> Err {}
4 | | }
  | |_^ consider adding a `main` function to `src/main.rs`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0573, E0601.
For more information about an error, try `rustc --explain E0573`.
error: could not compile `bisect`

To learn more, run the command again with --verbose.
```

**Comment by hameerabbasi** [comment]
As stated in the edited message above, this ICE only happens on Rust 2015 edition.

```
********************************************************************************
Regression in nightly-2020-06-25
********************************************************************************

fetching https://static.rust-lang.org/dist/2020-06-24/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2020-06-24: 40 B / 40 B [================] 100.00 % 674.64 KB/s converted 2020-06-24 to ff5b446d2fdbd898bc97a751f2f72858de185cf1
fetching https://static.rust-lang.org/dist/2020-06-25/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2020-06-25: 40 B / 40 B [================] 100.00 % 689.42 KB/s converted 2020-06-25 to 67100f61e62a86f2bf9e38552ee138e231eddc74
looking for regression commit between 2020-06-24 and 2020-06-25
opening existing repository at "rust.git"
refreshing repository
fetching (via local git) commits from ff5b446d2fdbd898bc97a751f2f72858de185cf1 to 67100f61e62a86f2bf9e38552ee138e231eddc74
opening existing repository at "rust.git"
refreshing repository
looking up first commit
looking up second commit
checking that commits are by bors and thus have ci artifacts...
finding bors merge commits
found 6 bors merge commits in the specified range
  commit[0] 2020-06-23UTC: Auto merge of #73644 - ollie27:rustdoc_alias_filter, r=GuillaumeGomez
  commit[1] 2020-06-23UTC: Auto merge of #73669 - Manishearth:rollup-0n4u7vq, r=Manishearth
  commit[2] 2020-06-24UTC: Auto merge of #73293 - Aaron1011:feature/macro-rules-arg-capture, r=petrochenkov
  commit[3] 2020-06-24UTC: Auto merge of #73679 - ehuss:update-cargo, r=ehuss
  commit[4] 2020-06-24UTC: Auto merge of #73692 - Dylan-DPC:rollup-ehzsbfw, r=Dylan-DPC
  commit[5] 2020-06-24UTC: Auto merge of #73660 - flip1995:clippyup, r=nikomatsakis
ERROR: no commits between ff5b446d2fdbd898bc97a751f2f72858de185cf1 and 67100f61e62a86f2bf9e38552ee138e231eddc74 within last 167 days
```

**Comment by estebank** [comment]
The problem is an empty suggestion, https://github.com/rust-lang/rust/pull/82087 fixes this.
