### ISSUE TITLE
compiletest fails to build using local-rebuild=true + rustc 1.34.0-nightly (0ea22717a 2019-03-02)

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#58890]
```
error[E0063]: missing field `exclude_should_panic` in initializer of `test::TestOpts`
   --> src/tools/compiletest/src/main.rs:504:5
    |
504 |     test::TestOpts {
    |     ^^^^^^^^^^^^^^ missing `exclude_should_panic`

error: aborting due to previous error
```

**Comment by rchaser53** [comment]
maybe this will be fixed in https://github.com/laumann/compiletest-rs/pull/160

**Comment by bjorn3** [comment]
This has been fixed.
