### PR TITLE
revert 74989 ("Implement `Index` and `IndexMut` for arrays")

### LINKED ISSUE #79152: alacritty/vte fails to build on rustc master   (mutable references are not allowed in constant functions)
Upstream ticket: https://github.com/alacritty/vte/issues/68

### Code
https://github.com/alacritty/vte/
I tried this code:

```rust
<code>
```

I expected to see this happen: *explanation*
The code compiles on
````
   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.47.0 (18bf6b4f0 2020-10-07)
     beta-x86_64-unknown-linux-gnu unchanged - rustc 1.48.0-beta.10 (8236dc07b 2020-11-15)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.50.0-nightly (f5230fbf7 2020-11-16)
````
but fails to build on rustc master `rustc 1.50.0-nightly (c919f490b 2020-11-17)`
which I assumes makes this a regression:
````
    Checking vte v0.9.0 (/tmp/vte)
error[E0658]: mutable references are not allowed in constant functions
   --> src/table.rs:9:1
    |
9   | / generate_state_changes!(state_changes, {
10  | |     Anywhere {
11  | |         0x18 => (Ground, Execute),
12  | |         0x1a => (Ground, Execute),
...   |
170 | |     }
171 | | });
    | |___^
    |
    = note: see issue #57349 <https://github.com/rust-lang/rust/issues/57349> for more information
    = help: add `#![feature(const_mut_refs)]` to the crate attributes to enable
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
   --> src/table.rs:9:1
    |
9   | / generate_state_changes!(state_changes, {
10  | |     Anywhere {
11  | |         0x18 => (Ground, Execute),
12  | |         0x1a => (Ground, Execute),
...   |
170 | |     }
171 | | });
    | |___^
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors
````

### Version it worked on

It most recently worked on: 

### Version with regression

`rustc --version --verbose`:
```
<version>
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

### PR DESCRIPTION
**Pull request by matthiaskrgr**
This PR reverts https://github.com/rust-lang/rust/pull/74989 and adds a testcase for 
````rust
const fn foo() {
    let mut array = [[0; 1]; 1];
    array[0][0] = 1;
}
````
which compiles on stable and beta but not on nightly due to #74989 .
The offending commit had a crater run but the breaking change was missed which means it probably would not have landed if the breaking change had been noticed in time.

This PR fixes compilation of real-world crates such as https://github.com/alacritty/vte/

Fixes #79152

### CODE REVIEW

**Comment by Aaron1011** [comment]
This will break any code that started relying on the (insta-stable) `Index` and `IndexMut` impls.
I think the targeted fix suggested by @lcnr would be a better idea: https://github.com/rust-lang/rust/issues/79152#issuecomment-729958708

**Comment by Aaron1011** [comment]
I've opened https://github.com/rust-lang/rust/pull/79427 - the issue turned out to be a missing call to `resolve_vars_if_possible`

**Comment by oli-obk** [comment]
we decided in last weeks compiler team meeting that we'd do the revert and then immediately open a PR with the fix and impl again. I guess that only makes sense if we crater it, considering that there's a fix PR open. Since we didn't discuss running crater, and we do have a fix PR, let's favour the fix PR.

cc @rust-lang/compiler I'm making a decision against the meeting decision, since I think there's little benefit in reverting, only to readd with the fix and merge that immediately after.
