### ISSUE TITLE
[1.38] Regression: cannot find macro `trace!` in this scope

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#63888]
https://github.com/rust-lang/rust/issues/63628#issuecomment-524587231

>cannot find macro `trace!` in this scope

>cannot find macro `flatdata_intersperse!` in this scope

```
./reg/eztrace/0.1.0/beta-2019-08-13.txt:[INFO] [stderr] error: cannot find macro `trace!` in this scope

./reg/flatdata/0.3.0/beta-2019-08-13.txt:[INFO] [stderr] error: cannot find macro `flatdata_intersperse!` in this scope
```

Regression from https://github.com/rust-lang/rust/pull/63114, fixed in https://github.com/rust-lang/rust/pull/63717.
(The fix still needs a backport to beta.)

**Comment by nikomatsakis** [comment]
Needs to be closed once #63717 is backported
