### ISSUE TITLE
Duplicate `extern crate` in doc tests (2021-11-21 Nightly Regression)

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-lang/rust#91134]
We have a Rust-2015 doc test which has an `extern crate $CRATE_DOC_TEST_IS_IN` which started failing to build on nightly 2021-11-21 (but passes on stable/2021-11-20).

It now fails with

```
---- src/chain/transaction.rs - chain::transaction::TransactionData (line 22) stdout ----
error[E0259]: the name `lightning` is defined multiple times
 --> src/chain/transaction.rs:24:1
  |
3 | extern crate lightning;
  | ----------------------- previous import of the extern crate `lightning` here
4 | 
5 | extern crate r#lightning;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^ `lightning` reimported here
  |
  = note: `lightning` must be defined only once in the type namespace of this module

error: aborting due to previous error
```

**Comment by mathstuf** [comment]
Probably caused by 331465a867fd450939d23d6ebd0580fc0ef18059 (#91054; rollup #91064)? @camelid

**Comment by jyn514** [comment]
That seems unlikely, https://github.com/rust-lang/rust/pull/91026 is more plausible. #91066 doesn't affect doctests.

**Comment by mathstuf** [comment]
Oh, I think I got misled by the "rustdoc" bit.

**Comment by jyn514** [comment]
I can't reproduce this. I tried
```rust
/// ```
/// extern crate inner;
/// ```
pub trait Trait {
    type Item;
}
```
and running `cargo test --doc`, but all the tests passed fine. @TheBlueMatt can you link the original code?

**Comment by TheBlueMatt** [comment]
The failure is https://github.com/rust-bitcoin/rust-lightning/blob/main/lightning/src/chain/transaction.rs#L24 You can see the first failure in CI at https://github.com/rust-bitcoin/rust-lightning/runs/4288660534?check_suite_focus=true

**Comment by ehuss** [comment]
The following seems like a minimal reproduction when used with 2015:

```rust
/// ```
/// extern crate mycrate;
/// mycrate::foo();
/// ```
pub fn foo() {}
```

Bisected to #91026.

**Comment by jyn514** [comment]
cc @notriddle , I think it might make sense to revert #91026 temporarily unless you already have an idea for a fix.
