### ISSUE TITLE
Exponential slowdown in catching an `overflow` error.

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#91949]
This code is not expected to compile successfully:

````rs
fn main() {
    recurse(std::iter::empty());
}

struct Wrapped<T>(T);

struct IteratorOfWrapped<T, I: Iterator<Item = T>>(I);

impl<T, I: Iterator<Item = T>> Iterator for IteratorOfWrapped<T, I> {
    type Item = Wrapped<T>;
    fn next(&mut self) -> Option<Wrapped<T>> {
        self.0.next().map(Wrapped)
    }
}

fn recurse<T>(elements: T) -> Vec<char>
where
    T: Iterator<Item = ()>,
{
    recurse(IteratorOfWrapped(elements).map(|t| t.0))
}
````
This can't compile successfully because `recurse<T>` calls `recurse<Map<IteratorOfWrapped<(), T>, [closure@<source>:22:51: 22:58]>>` recursively, which then calls `recurse<Map<IteratorOfWrapped<(), Map<IteratorOfWrapped<(), T>, [closure@<source>:22:51: 22:58]>>, [closure@<source>:22:51: 22:58]>>`, and so on...

However up to stable 1.55, the code failed to compile quickly with the default recursion limit. On the [compiler explorer](https://godbolt.org/z/6vTvfPchY), you can see it even handling `#![recursion_limit = "800"]` without timeout. However, [go to 1.56](https://godbolt.org/z/f1Px86Y5f) and it no longer reaches a compilation error in time with `#![recursion_limit = "30"]`. Still just as slow on nightly (`rustc 1.59.0-nightly (6bda5b331 2021-12-12)`).

@rustbot label: regression-from-stable-to-stable, perf-regression, I-compiletime, T-compiler, E-needs-bisection 

Comes from: https://users.rust-lang.org/t/compiler-hanging/68804

Rough estimate on my machine: In the area of `recursion_limit` being `20`-`30`, the time more-than doubles for each increase of the recursion limit by `2` or `3`, so it really is exponential AFAICT.

**Comment by parasyte** [comment]
Possibly related to #89195?

**Comment by hkratz** [comment]
Bisected to #85868, cc @Aaron1011

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.1</summary>
searched nightlies: from nightly-2021-06-01 to nightly-2021-12-08
regressed nightly: nightly-2021-09-03
searched commit range: https://github.com/rust-lang/rust/compare/50171c310cd15e1b2d3723766ce64e2e4d6696fc...371f3cd3fe523d0b398ed1db1620667c53ba7d02
regressed commit: https://github.com/rust-lang/rust/commit/371f3cd3fe523d0b398ed1db1620667c53ba7d02

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 3 --start 2021-06-01 --script ./test.sh
```
</details>

@rustbot label -E-needs-bisection

**Comment by steffahn** [comment]
That PR seems incremental-compilation related. This leaves the question of whether the regression also happens without incremental compilation turned on, and whether or not it happens at the same point.

**Comment by steffahn** [comment]
Hard to know for certain until #89195 has a mvce. Also note that, as far as I understand, #89195 is observable with `cargo check` whereas this bug only appear with `cargo build`. (I somehow forgot to mention that...)

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2391949.20Exponential.20slowdown.20in.20catching.20an.20.60overflow.60.20error.2E) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high

**Comment by wesleywiser** [comment]
Retested since #90423 landed on nightly:

- rustc 1.55.0 (c8dfcfe04 2021-09-06): 13.1 seconds
- rustc 1.59.0-nightly (f8abed9ed 2021-12-26): 10.6 seconds

**Comment by steffahn** [comment]
Seems to have fixed the problem, indeed. @rustbot label E-needs-test.
