### ISSUE TITLE
regression: rustdoc interprets the `*` in `/** */` doc comments as literal Markdown

### ISSUE THREAD

**Issue by dalcde** [rust-lang/rust#92872]
### Code

I tried this code:

```rust
/**
 *     a
 */
pub fn foo() {}
```
When I run `cargo test`, I get
```
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 1 test
test src/lib.rs - foo (line 1) ... FAILED

failures:

---- src/lib.rs - foo (line 1) stdout ----
error[E0425]: cannot find value `a` in this scope
 --> src/lib.rs:2:1
  |
3 | a
  | ^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
Couldn't compile the test.

failures:
    src/lib.rs - foo (line 1)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.41s
```
Oddly it doesn't fail with `/**` replaced by `///`.

This worked on `rust version 1.60.0-nightly (092e1c9d2 2022-01-09)` but failed on `rust version 1.60.0-nightly (1409c015b 2022-01-11)`

**Comment by Alexendoo** [comment]
bisects to 89b9f7b284aacc5f8613438b80e4dd7bdd10549e, likely #92357

**Comment by camelid** [comment]
cc @GuillaumeGomez

**Comment by camelid** [comment]
The docs for the MCVE render with an itemized bullet at the top of the page on nightly, but not on stable. I think this is why replacing the `/**` with `///` makes the error go away: the `*` is interpreted as part of the docs, so it triggers the indented text to be treated as a code block (it seems there must be preceding text to trigger the code block formatting).

![image](https://user-images.githubusercontent.com/37223377/149435001-877a0a79-dcce-4b3a-b219-3cf52d068e28.png)

**Comment by camelid** [comment]
It seems like `/** */` comments are completely broken:

```rust
/**
 * Hello!
 */
pub fn foo() {}
```

![image](https://user-images.githubusercontent.com/37223377/149435080-7097feb8-6546-4ab8-a475-98340e9bf528.png)

I still don't understand how that change could've cause this though; the particular code removed was related to trimming whitespace, not asterisks. Must be a strange cross-interaction.

**Comment by GuillaumeGomez** [comment]
The `/** */` comments have always been working like this. It's not supposed to contain `*` at the beginning of each line.

**Comment by camelid** [comment]
@GuillaumeGomez They actually haven't; this is a regression. On stable, it looks like this:

![image](https://user-images.githubusercontent.com/37223377/149576951-ad6301a3-4936-44dd-8017-91a11bfbc812.png)

**Comment by GuillaumeGomez** [comment]
Interesting. How did we make the difference between:

```rust
/**
hello

 * list
 * list

```

and:

```rust
/**
* hello
*  * list
*  * list
*/
```

?

Do we need to have a star at each line or something?

**Comment by camelid** [comment]
I'm not sure exactly how it works, but I believe it's handled by this code (the code modified by the regressing PR, though I'm not sure _how_ it caused the regression): https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/util/comments/fn.beautify_doc_string.html
