### ISSUE TITLE
Rust 1.19 regression, minions 0.2.8, type mismatch

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#42618]
https://github.com/dbeck/acto-rs

```
commit 5311c872dd88d3bf034e023f501971c711dee41c
Author: David Beck <david.beck.priv@gmail.com>
Date:   Mon Aug 29 23:04:00 2016 +0100

    sanitize Observer interface
```

```
rustc 1.19.0-beta.1 (a87984118 2017-06-06)
binary: rustc
commit-hash: a879841184d6fe89b819425fde1568b50a54543f
commit-date: 2017-06-06
host: x86_64-unknown-linux-gnu
release: 1.19.0-beta.1
LLVM version: 4.0

```

```
brian@ip-10-145-43-250:~/dev/acto-rs⟫ cargo +beta test
   Compiling minions v0.2.7 (file:///mnt2/dev/acto-rs)
error[E0308]: mismatched types
   --> src/main.rs:147:14
    |
147 |       sum += i;
    |              ^ expected i32, found ()
    |
    = note: expected type `i32`
               found type `()`

error: aborting due to previous error(s)

error: Could not compile `minions`.

To learn more, run the command again with --verbose.
```

cc @dbeck

**Comment by Mark-Simulacrum** [comment]
The relevant code (which is in a test case, I believe) has been deleted on master of the relevant repo, but bisection shows failure was introduced in #42265 -- cc @eddyb @Zoxc, this is actually somewhat concerning. It's possible that this hints at some more wide-spread problem that patch introduced that just wasn't noticed yet, but I could be wrong.

Here is the code https://github.com/dbeck/acto-rs/blob/5311c872dd88d3bf034e023f501971c711dee41c/src/main.rs#L147.

**Comment by eddyb** [comment]
I really don't see how that could be happening - does it reproduce on nightly?

**Comment by Mark-Simulacrum** [comment]
Reproduces on nightly and 5aa34038ffd8c30ebdce5518a312a187385d3216.

**Comment by eddyb** [comment]
Reproduced with:
```rust
fn main() {
    let mut sum = 0;
    for i in std::sync::mpsc::channel().1.iter() {
        sum += i;
    }
}
```

**Comment by brson** [comment]
https://github.com/rust-lang/rust/pull/42634

**Comment by Mark-Simulacrum** [comment]
Reopening to track the beta backport of #42634. I don't know if this is the proper procedure but... seems good and not harmful.

**Comment by nikomatsakis** [comment]
@Mark-Simulacrum looks like beta backport landed in https://github.com/rust-lang/rust/pull/42927, no? Going to close for now, assuming I'm right.
