### ISSUE TITLE
liquidfun beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#44447]
The [liquidfun](https://crates.io/crates/liquidfun) crate version 0.8.0 fails to build on latest beta 1.21, while the build works on stable. The error output (full [log](http://cargobomb-reports.s3.amazonaws.com/stable-1.20-beta-1.21.0-beta.1/beta-2017-09-02/reg/liquidfun-0.8.0/log.txt)):

```
error[E0106]: missing lifetime specifier
   --> src/box2d/dynamics/body.rs:110:49
    |
110 |     fn b2Body_GetPosition(this: *mut B2Body) -> &Vec2;
    |                                                 ^ expected lifetime parameter
    |
    = help: this function's return type contains a borrowed value with an elided lifetime, but the lifetime cannot be derived from the arguments
    = help: consider giving it an explicit bounded or 'static lifetime
```

cc @rjanicek

**Comment by est31** [comment]
Bisected to e40dc66f47614eb2d1c8026d112a27b6f8b291d0 -- #43651 cc @petrochenkov @eddyb

**Comment by est31** [comment]
Minimal reproducing example:

```rust
extern {
    fn foo(this: *mut u8) -> &u32;
}
```

**Comment by arielb1** [comment]
I believe this is intentional.

**Comment by nikomatsakis** [comment]
This is a bug-fix, so closing as "behaving as expected".
