### ISSUE TITLE
1.97 beta regression: "conflicting implementations of trait"

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#157407]
This regression was discovered by the 1.97 beta crater run.

```
[INFO] [stdout] error[E0119]: conflicting implementations of trait `FromRow<'_, PgRow>` for type `ChallengeRecord`
[INFO] [stdout]    --> src/activities.rs:58:37
[INFO] [stdout]     |
[INFO] [stdout]  58 | #[derive(Clone, Debug, Deserialize, FromRow, PartialEq, Serialize)]
[INFO] [stdout]     |                                     ^^^^^^^ conflicting implementation for `ChallengeRecord`
[INFO] [stdout] ...
[INFO] [stdout] 114 | impl FromRow<'_, PgRow> for ChallengeRecord {
[INFO] [stdout]     | ------------------------------------------- first implementation here
[INFO] [stdout]     |
[INFO] [stdout]     = note: downstream crates may implement trait `sqlx::Decode<'_, _>` for type `activities::ActivityType`
[INFO] [stdout]     = note: downstream crates may implement trait `sqlx::Type<_>` for type `activities::ActivityType`
[INFO] [stdout]     = note: this error originates in the derive macro `FromRow` (in Nightly builds, run with -Z macro-backtrace for more info)
```

https://crater-reports.s3.amazonaws.com/beta-1.97-3-v2/1.97.0-beta.1/gh/njbartlett.pfnext-shuttle/log.txt

**Comment by theemathas** [comment]
Smaller reproducer:

```toml
[package]
name = "repro"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = { version = "0.9.0", features = ["postgres"] }
```

```rust
use sqlx::decode::Decode;
use sqlx::postgres::PgRow;
use sqlx::{Error, FromRow, Row};

pub struct ActivityType;

pub struct ChallengeRecord;

impl FromRow<'_, PgRow> for ChallengeRecord {
    fn from_row(_: &'_ PgRow) -> Result<Self, Error> {
        todo!()
    }
}

impl<'a, R: Row> FromRow<'a, R> for ChallengeRecord
where
    ActivityType: Decode<'a, R::Database>,
{
    fn from_row(__row: &'a R) -> sqlx::Result<Self> {
        todo!()
    }
}
```

Error on beta:

```
error[E0119]: conflicting implementations of trait `FromRow<'_, PgRow>` for type `ChallengeRecord`
  --> src/lib.rs:15:1
   |
 9 |   impl FromRow<'_, PgRow> for ChallengeRecord {
   |   ------------------------------------------- first implementation here
...
15 | / impl<'a, R: Row> FromRow<'a, R> for ChallengeRecord
16 | | where
17 | |     ActivityType: Decode<'a, R::Database>,
   | |__________________________________________^ conflicting implementation for `ChallengeRecord`
   |
   = note: downstream crates may implement trait `sqlx::Decode<'_, _>` for type `ActivityType`

For more information about this error, try `rustc --explain E0119`.
error: could not compile `repro` (lib) due to 1 previous error
```

**Comment by theemathas** [comment]
Minimized:

dep/src/lib.rs
```rust
pub trait Row {
    type Database;
}

pub struct PgRow;
```

src/lib.rs
```rust
use dep::{PgRow, Row};

pub trait FromRow {}
pub trait Decode<T> {}

pub struct ActivityType;

impl FromRow for PgRow {}

impl<R: Row> FromRow for R where ActivityType: Decode<R::Database> {}
```

Error output on beta
```
error[E0119]: conflicting implementations of trait `FromRow` for type `PgRow`
  --> src/lib.rs:10:1
   |
 8 | impl FromRow for PgRow {}
   | ---------------------- first implementation here
 9 |
10 | impl<R: Row> FromRow for R where ActivityType: Decode<R::Database> {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `PgRow`
   |
   = note: upstream crates may add a new impl of trait `dep::Row` for type `dep::PgRow` in future versions
   = note: downstream crates may implement trait `Decode<_>` for type `ActivityType`

For more information about this error, try `rustc --explain E0119`.
```

**Comment by theemathas** [comment]
Bisection results:

```
searched toolchains 4c4205163abcbd08948b3efab796c543ba1ea687 through 3bf5c6d99bc8a0c0d5b2f69826ed4f6d256a0a21


********************************************************************************
Regression in a3e96d8cb8a420022828d0a595277ad3671928a7
********************************************************************************

Attempting to search unrolled perf builds
ERROR: couldn't find perf build comment
```

Regressed in #155767. cc @adminwhite @lcnr

**Comment by theemathas** [comment]
My "smaller reproducer" and the "minimized" reproducer have different errors. (The latter mentions "upstream crates", while the former does not.) Odd.

**Comment by lcnr** [comment]
see the discussion on zulip https://rust-lang.zulipchat.com/#narrow/channel/326866-t-types.2Fnominated/topic/.23157407.3A.201.2E97.20beta.20regression.3A.20.22conflicting.20implementations.E2.80.A6/with/601113797

**Comment by theemathas** [comment]
Reopening to track beta backport.

**Comment by apiraino** [comment]
I assume this issue has been discussed by T-types (see [comment](https://github.com/rust-lang/rust/pull/157617#issuecomment-4794429970))

@rustbot label -i-types-nominated

**Comment by theemathas** [comment]
Fixed by https://github.com/rust-lang/rust/pull/158420
