### PR TITLE
Fix #56237: normalize type before deferred sizedness checking.

### LINKED ISSUE #56237: Inference regression in nightly affecting `Pin::set` and futures
`futures-util-preview` does not build on the current nightly because the compiler is unable to infer that a type is `Sized`. This is a regression in the latest nightly.

The line that errors is [here](https://github.com/rust-lang-nursery/futures-rs/blob/b7769180b091f22da12d35ea808779ddfa17b7e3/futures-util/src/future/maybe_done.rs#L110).

Error message:

```
error[E0277]: the size for values of type `<&mut future::maybe_done::MaybeDone<Fut> as std::ops::Deref>::Target` cannot be known at compilation time
   --> futures-util/src/future/maybe_done.rs:110:9
    |
110 |         Pin::set(self, MaybeDone::Done(res));
    |         ^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `std::marker::Sized` is not implemented for `<&mut future::maybe_done::MaybeDone<Fut> as std::ops::Deref>::Target`
```

Relevant commits: https://github.com/rust-lang/rust/compare/edaac35d6...6acbb5b65

cc rust-lang-nursery/futures-rs#1350

### PR DESCRIPTION
**Pull request by qnighy**
This seems to fix #56237, which was introduced by #56045. I don't thoroughly understand how this works, but the problem seemed to be a lack of normalization.

r? @cramertj

### CODE REVIEW

**Comment by pnkfelix** [comment]
Discussed at T-compiler meeting. accepted for backport to beta.

**Comment by qnighy** [comment]
@pnkfelix shall I prepare the backport by myself, or should I just wait for someone to do this?

**Comment by pnkfelix** [comment]
@qnighy most often i find that beta-accepted PR's are handled via rollups of a bunch of beta-accepted PR's at once, as you can see on PR #56930.

**Comment by qnighy** [comment]
@pnkfelix thanks, then I'll leave it untouched.
