### ISSUE TITLE
Could not compile `textwrap`

### ISSUE THREAD

**Issue by jvinolas** [rust-lang/rust#57665]
```
   Compiling tokio-current-thread v0.1.4                                                                 
   Compiling tokio-timer v0.2.8                                                                          
   Compiling quote v0.6.10                                                                               
   Compiling bytes v0.4.11                                                                               
   Compiling num-integer v0.1.39                                                                         
   Compiling futures-cpupool v0.1.8                                                                      
   Compiling mio v0.6.16                                                                                 
   Compiling textwrap v0.10.0                                                                            
   Compiling url v1.7.2                                                                                  
   Compiling msdos_time v0.1.6                                                                           
   Compiling cookie v0.11.0                                                                              
error: Could not compile `textwrap`.                                                                     
warning: build failed, waiting for other jobs to finish...
thread 'main' panicked at 'already borrowed: BorrowMutError', libcore/result.rs:1009:5                   
note: Run with `RUST_BACKTRACE=1` for a backtrace.                                                       
thread 'main' panicked at 'already borrowed: BorrowMutError', libcore/result.rs:1009:5                   
note: Run with `RUST_BACKTRACE=1` for a backtrace.                                                       
                                                                                                         
error: internal compiler error: unexpected panic                                                         
                                                                                                         
note: the compiler unexpectedly panicked. this is a bug.                                                 
                                                                                                         
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
                                                                                                         
note: rustc 1.31.1 (b6c32da9b 2018-12-18) running on aarch64-unknown-linux-gnu                           
                                                                                                         
note: compiler flags: -C debuginfo=2 --crate-type lib                                                    
                                                                                                         
note: some of the compiler flags provided by cargo are hidden                                            
                                                                                                         
error: Could not compile `url`.                                                                          
warning: build failed, waiting for other jobs to finish...
                                                                                                         
error: internal compiler error: unexpected panic                                                         
                                                                                                         
note: the compiler unexpectedly panicked. this is a bug.                                                 
                                                                                                         
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
                                                                                                         
note: rustc 1.31.1 (b6c32da9b 2018-12-18) running on aarch64-unknown-linux-gnu                           
                                                                                                         
note: compiler flags: -C debuginfo=2 --crate-type lib                                                    
                                                                                                         
note: some of the compiler flags provided by cargo are hidden                                            
                                                                                                         
./build.sh: line 77:  5728 Segmentation fault      (core dumped) cargo build --target aarch64-unknown-linux-gnu $modeflag
```

**Comment by estebank** [comment]
Could you provide a backtrace?

**Comment by hellow554** [comment]
Cannot reproduce it with 1.31.1 :/

**Comment by Centril** [comment]
@jvinolas Could you provide a minimal example which reproduces the ICE on older compilers?

**Comment by mgeisler** [comment]
Hey, textwrap author here. I don't think this can be reproduced any longer: updating to the 0.10.0 tag of textwrap and trying to compile with Rust 1.31.1 yields
```
 cargo test                                                                       (~/src/textwrap)
   Compiling tinyvec_macros v0.1.0                                                                          
   Compiling pulldown-cmark v0.1.2                                                                          
   Compiling bitflags v0.9.1                                                                                
   Compiling quote v0.3.15                                                                                  
error[E0658]: using the `?` macro Kleene operator for "at most one" repetition is unstable (see issue #48075)
 --> /home/mg/.cargo/registry/src/github.com-1ecc6299db9ec823/tinyvec_macros-0.1.0/src/lib.rs:9:106         
  |                                                                                                         
9 |         $v:vis fn $fname:ident ($seif:ident : $seifty:ty $(,$argname:ident : $argtype:ty)*) $(-> $ret:ty)? ;
  |                                                                                                          ^
```

The dependencies have made new patch releases which push up the minimum supported Rust version. I suggest closing this as not reproducible.
