### PR TITLE
Update clippy and RLS

### PR DESCRIPTION
**Pull request by oli-obk**
r? @Manishearth

### CODE REVIEW

**Comment by kennytm** [comment]
Does it matter that [Clippy's CI](https://travis-ci.org/rust-lang-nursery/rust-clippy/builds/354987594) is failing?

```
error[E0308]: mismatched types
  --> clippy_lints/src/unsafe_removed_from_name.rs:46:29
   |
46 |         UseTreeKind::Simple(Some(new_name)) => {
   |                             ^^^^^^^^^^^^^^ expected struct `syntax::ast::Ident`, found enum `std::option::Option`
   |
   = note: expected type `syntax::ast::Ident`
              found type `std::option::Option<_>`
error[E0308]: mismatched types
  --> clippy_lints/src/unsafe_removed_from_name.rs:55:29
   |
55 |         UseTreeKind::Simple(None) |
   |                             ^^^^ expected struct `syntax::ast::Ident`, found enum `std::option::Option`
   |
   = note: expected type `syntax::ast::Ident`
              found type `std::option::Option<_>`
error: aborting due to 2 previous errors
```

**Comment by oli-obk** [comment]
clippy's CI fails on this because the change is not yet in nightly. I used a locally built rustc to confirm

**Comment by oli-obk** [comment]
on that note. Is it possible to get the binaries from every PR? Maybe we could run clippy's CI on those instead of running it on nightly

**Comment by kennytm** [comment]
@oli-obk Yes, but those binaries will be deleted in 90 days.

**Comment by oli-obk** [comment]
> Yes, but those binaries will be deleted in 90 days.

That's fine. I just want to download the most recent one for every CI execution

**Comment by kennytm** [comment]
@oli-obk It would be available at `https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds/$COMMIT/$COMPONENT-nightly-$TARGET.tar.xz` where `$COMPONENT` is `rustc`, `rust-std`, `cargo`, etc. 

We reserve the right to change the URL though, so prefer to download through `rustup-toolchain-install-master` or `cargo-bisect-rustc`.

**Comment by kennytm** [comment]
@bors r+

Sorry for hijack. I've included an update to RLS here since it was broken by #48986.

**Comment by kennytm** [comment]
@bors retry 

rust-lang-nursery/rust-clippy@4edd140e57cce900fa930e1439bab469f5bbce46 was not yet merged into master. Created https://github.com/rust-lang-nursery/rust-clippy/tree/rustup-49134 for now. 

Please merge rust-lang-nursery/rust-clippy@4edd140e57cce900fa930e1439bab469f5bbce46 into master and delete the `rustup-49134` branch after this is merged and a new nightly is released.

```
[00:01:11] Submodule 'src/tools/clippy' (https://github.com/rust-lang-nursery/rust-clippy.git) unregistered for path 'src/tools/clippy'
[00:01:11] Submodule 'src/tools/clippy' (https://github.com/rust-lang-nursery/rust-clippy.git) registered for path 'src/tools/clippy'
[00:01:11] error: Server does not allow request for unadvertised object 4edd140e57cce900fa930e1439bab469f5bbce46
[00:01:11] Fetched in submodule path 'src/tools/clippy', but it did not contain 4edd140e57cce900fa930e1439bab469f5bbce46. Direct fetching of that commit failed.
```
