### ISSUE TITLE
Bad recovery for `<expression> ? <statement> ;`

### ISSUE THREAD

**Issue by bend-n** [rust-lang/rust#117208]
### Code

```Rust
pub fn foo() {
  let v = v?
  while let Ok(_) = v {};
}
```

### Current output

```Shell
error: expected one of `.`, `;`, `?`, `else`, or an operator, found `;`
 --> src/main.rs:4:25
  |
4 |   while let Ok(_) = v {};
  |                         ^ expected one of `.`, `;`, `?`, `else`, or an operator
```

### Desired output

```Shell
error: expected `;`, found `while`
 --> src/main.rs:4:25
  |
3 |  let v = v?
  |            ^ help: add ';' here
```

### Rationale and extra context

Confusing error

### Other cases

```Rust
Removing the semicolon as suggested causes

error: expected `;`, found `}`
 --> src/main.rs:4:25
  |
4 |   while let Ok(_) = v {}
  |                         ^ help: add `;` here
5 | }
  | - unexpected token

error[E0425]: cannot find value `v` in this scope
 --> src/main.rs:3:11
  |
3 |   let v = v?
  |           ^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
```

### Anything else?

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=pub+fn+foo%28%29+%7B%0A++let+v+%3D+v%3F%0A++while+let+Ok%28_%29+%3D+v+%7B%7D%3B%0A%7D%0Afn+main%28%29+%7B%7D)

**Comment by clubby789** [comment]
Can also be reproduced with
```rs
fn main() {
    v ? return;
}
```
Probably caused by #114028
