### PR TITLE
Redesign the std::iter::Step trait, tweak related iterator impls for ranges

### PR DESCRIPTION
**Pull request by SimonSapin**
CC https://github.com/rust-lang/rust/issues/42168

The trait is now:

```rust
/// Objects that have a notion of *successor* and *predecessor*
/// for the purpose of range iterators.
///
/// This trait is `unsafe` because implementations of the `unsafe` trait `TrustedLen`
/// depend on its implementations being correct.
#[unstable(feature = "step_trait",
           reason = "recently redesigned",
           issue = "42168")]
pub unsafe trait Step: Clone + PartialOrd + Sized {
    /// Returns the number of *successor* steps needed to get from `start` to `end`.
    ///
    /// Returns `None` if that number would overflow `usize`
    /// (or is infinite, if `end` would never be reached).
    ///
    /// This must hold for any `a`, `b`, and `n`:
    ///
    /// * `steps_between(&a, &b) == Some(0)` if and only if `a >= b`.
    /// * `steps_between(&a, &b) == Some(n)` if and only if `a.forward(n) == Some(b)`
    /// * `steps_between(&a, &b) == Some(n)` if and only if `b.backward(n) == Some(a)`
    fn steps_between(start: &Self, end: &Self) -> Option<usize>;

    /// Returns the value that would be obtained by taking the *successor* of `self`,
    /// `step_count` times.
    ///
    /// Returns `None` if this would overflow the range of values supported by the type `Self`.
    ///
    /// Note: `step_count == 1` is a common case,
    /// used for example in `Iterator::next` for ranges.
    ///
    /// This must hold for any `a`, `n`, and `m` where `n + m` doesn’t overflow:
    ///
    /// * `a.forward(n).and_then(|x| x.forward(m)) == a.forward(n + m)`
    fn forward(&self, step_count: usize) -> Option<Self>;

    /// Returns the value that would be obtained by taking the *predecessor* of `self`,
    /// `step_count` times.
    ///
    /// Returns `None` if this would overflow the range of values supported by the type `Self`.
    ///
    /// Note: `step_count == 1` is a common case,
    /// used for example in `Iterator::next_back` for ranges.
    ///
    /// This must hold for any `a`, `n`, and `m` where `n + m` doesn’t overflow:
    ///
    /// * `a.backward(n).and_then(|x| x.backward(m)) == a.backward(n + m)`
    fn backward(&self, step_count: usize) -> Option<Self>;
}
```

Arithmetic and overflow handling with multiple integer types of different widths and signedness is tricky, careful review would be appreciated.

Other changes:

* The unsafe trait `TrustedLen` is now implemented for ranges of <s>all integer types</s> all `T: Step` types. `Step` is now an `unsafe trait` as a consequence.
* Check for overflow everywhere. If it turns out the optimizer doesn’t manage to elide some of the checks that could be removed I’ll leave it to someone else to carefully optimize this, preferably without changing behavior. CC https://github.com/rust-lang/rust/issues/43064
* Remove `ExactSizeIterator` impls for `RangeInclusive<u16>` and `RangeInclusive<i16>` as they are incorrect on 16-bit platforms. CC https://github.com/rust-lang/rust/pull/43086#issuecomment-313872797
* Don’t reset inclusive ranges to `1...0` after the last iteration. Instead increment or decrement similarly to other iterations. If that would cause overflow, decrement/increment the other bound instead.
* Return `(usize::MAX, None)` instead of `(0, None)` in `size_hint` when the exact result would overflow `usize`.

### CODE REVIEW

**Comment by SimonSapin** [comment]
https://travis-ci.org/rust-lang/rust/jobs/251678510 `"env": "IMAGE=x86_64-gnu-llvm-3.7 ALLOW_PR=1 RUST_BACKTRACE=1"`

```
error: linking with `cc` failed: exit code: 1
[…]
undefined reference to `core::option::expect_failed::h6f9984c44d33d89c
```

🤔

**Comment by kennytm** [comment]
Merging this would make the situation in #43124 even worse — the speed of `(0 .. u16::MAX).collect::<Vec<_>>()` is reduced from ~110µs/iter to ~270µs/iter.

**Comment by oyvindln** [comment]
>

The [impl for TryFrom](https://github.com/rust-lang/rust/blob/master/src/libcore/num/mod.rs#L2514) casts the value to i/u128 to check if it's in range, maybe that is something that could cause issues as the 128-bit types are somewhat special.

**Comment by SimonSapin** [comment]
I think the current state of this PR is about the amount of effort I’m willing to put into this at the moment. If anyone would like to pick it up and push on the optimization front, feel free.

(I think going through 128-bit ints in `TryFrom` is unnecessary if we use separate code for `size_of::<$Source>() < size_of::<$Destination>()` vs `size_of::<$Source>() > size_of::<$Destination>()`.)

**Comment by carols10cents** [comment]
o.O I'm not sure why travis is failing like this with linking problems: https://travis-ci.org/rust-lang/rust/jobs/251678510#L1044

I tried restarting that job to make sure it wasn't something intermittent but it just failed in the same way again...

do you have any ideas why this might be happening for this PR @SimonSapin ?

**Comment by ExpHP** [comment]
>     /// Returns the number of *successor* steps needed to get from `start` to `end`.
>     ///
>     /// Returns `None` if that number would overflow `usize`
>     /// (or is infinite, if `end` would never be reached).
>     ///
>     /// This must hold for any `a`, `b`, and `n`:
>     ///
>     /// * `steps_between(&a, &b) == Some(0)` if and only if `a >= b`.
>     /// * `steps_between(&a, &b) == Some(n)` if and only if `a.forward(n) == Some(b)`
>     /// * `steps_between(&a, &b) == Some(n)` if and only if `b.backward(n) == Some(a)`



Surely this couId be better worded.  I had to read this docstring *very carefully* to convince myself that it does indeed follow the typical rust semantics of half-open ranges.

**Comment by SimonSapin** [comment]
@carols10cents On IRC @eddyb said it’s probably because intrinsics for u128 divison use a range iterator but are not allowed to link to panic code, and this PR adds calls to `Option::expect` in range iterator implementations. (Even if these "should" never panic, merely linking causes issues if that code is not optimized away.)

So it sounds like this needs more work to have correct overflow semantics without using panicking code.

@ExpHP I don’t mind rewriting this if you have a suggestion how. I avoided talking about addition and subtraction because `Step` can be implemented for things that are not necessarily numbers.

**Comment by ExpHP** [comment]
> @ExpHP I don’t mind rewriting this if you have a suggestion how. I avoided talking about addition and subtraction because Step can be implemented for things that are not necessarily numbers.

I would suggest making reference to the "length of the range `a..b`," which should already be readily familiar to almost any reader, and also places the trait in context of where it is used.  As far as I can tell, the only difference is that sometimes this function returns `None`.

File: src/libcore/iter/range.rs [hunk 1]
```diff
@@ -325,37 +408,53 @@ impl<A: Step> Iterator for ops::RangeInclusive<A> {
 
     #[inline]
     fn size_hint(&self) -> (usize, Option<usize>) {
+        // This seems redundant with a similar comparison that `Step::steps_between`
+        // implementations need to do, but it separates the `start > end` case from `start == end`.
+        // `steps_between` returns `Some(0)` in both of these cases, but we only want to add 1
+        // in the latter.
```
Comment (scottmcm) [inline src/libcore/iter/range.rs]: Should `steps_between` perhaps instead return something like `Result<Option<usize>, Unreachable>`?  Might make the documentation for the method easier to write, too.

File: src/libcore/iter/range.rs [hunk 2]
```diff
@@ -10,170 +10,235 @@
...
-
-    /// Subtracts one to this step, returning the result
-    fn sub_one(&self) -> Self;
+    /// Returns the value that would be obtained by taking the *successor* of `self`,
+    /// `step_count` times.
+    ///
+    /// Returns `None` if this would overflow the range of values supported by the type `Self`.
+    ///
+    /// Note: `step_count == 1` is a common case,
+    /// used for example in `Iterator::next` for ranges.
```
Comment (scottmcm) [inline src/libcore/iter/range.rs]: Would it be worth a `fn forward_one(&self) -> Option<Self> { self.forward(1) }` so the common case is overridable if needed?  I suppose it's always addable later if needed.

File: src/libcore/iter/range.rs [hunk 3]
```diff
@@ -280,7 +353,8 @@ impl<A: Step> Iterator for ops::RangeFrom<A> {
 
     #[inline]
     fn next(&mut self) -> Option<A> {
-        let mut n = self.start.add_one();
+        // Overflow can happen here. Panic when it does.
+        let mut n = self.start.forward(1).expect("overflow in RangeFrom::next");
```
Comment (scottmcm) [inline src/libcore/iter/range.rs]: IIRC this used to only panic in debug, right?

I like the change, but it might need to be called out in documentation somewhere.

**Comment by scottmcm** [comment]
Thanks for picking this up, @SimonSapin!  The trait looks way better now.

Some general musings on the trait:

- `steps_between` is very similar to `PartialOrd::cmp`, and [could be](https://github.com/rust-lang/rust/pull/43127#discussion_r127595049) a superset.  It might be interesting to remove the need for `PartialOrd` using that fact.
- Some of the range RFCs talked about ranges of slightly weird things like singly-linked list or DAG nodes which don't have computable or unique predecessors (respectively).  Would it be worth splitting the trait in two, like iterator?  (Now, I have no idea how to efficiently implement `steps_between` for those things, so it might be a moot point.)

**Comment by SimonSapin** [comment]
> Some of the range RFCs talked about ranges of slightly weird things like singly-linked list or DAG nodes which don't have computable or unique predecessors (respectively). Would it be worth splitting the trait in two, like iterator? 

So things that have a successor but no predecessor? Yes, this would require a trait separate from `Step` for the `DoubleEndedIterator` impl. But honestly this sounds so niche that I’m not convinced `std` should "go out of its way" to support it. Libraries with such types can define their own ranges and iterators.

**Comment by carols10cents** [comment]
friendly ping to keep this on your radar @SimonSapin !

**Comment by SimonSapin** [comment]
My understanding is that the main concern at this point is performance, and I wrote:

https://github.com/rust-lang/rust/pull/43127#issuecomment-313967696
> I think the current state of this PR is about the amount of effort I’m willing to put into this at the moment. If anyone would like to pick it up and push on the optimization front, feel free.

As to the CI failure, it might be fixed by https://github.com/rust-lang/rust/pull/43258. I’ve pushed a rebase to trigger a new build.

**Comment by SimonSapin** [comment]
Perf might be worth re-evaluating once #43248 or #43194 lands.

**Comment by alexcrichton** [comment]
ping @aturon for a review!

**Comment by SimonSapin** [comment]
This needs some more work that I’m not planning to do soon, closing to make that clear. Hopefully someone else can take over.

* In one Travis-CI configuration, "Building stage0 compiler artifacts" is failing at link-time with errors like ``undefined reference to `core::option::expect_failed::h6f9984c44d33d89c'``. Eddyb said this might be because `u128` division intrinsics use range iterators, and intrinsics are not allowed to link to panicking code. This PR introduces usage of `Option::expect` in range iterators, although for primitive integers types these should never panic (unless libcore is buggy). I think removing usage of `Option::expect` would require making the `Step` trait more complex, effectively undoing some of what this PR does. Maybe the intrinsics can be changed to not use range iterators instead?
* Several people have expressed concerns about performance. This needs benchmarking to see if this PR regresses it, maybe analyzing assembly code to figure out why and what can be done about it. If it turns out that overflow checking is responsible, consider how much overflow checking is desirable.
