### ISSUE TITLE
1.98 beta regressions involving ambiguous glob imports

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#159432]
This regression was found by the 1.98 crater run.

```
[INFO] [stdout] error[E0659]: `SequenceNumber` is ambiguous
[INFO] [stdout]    --> /opt/rustwide/cargo-home/git/checkouts/ros2-client-a2a0f36ac41415ea/3cab61b/src/service/mod.rs:347:51
[INFO] [stdout]     |
[INFO] [stdout] 347 |       sequence_number_gen: atomic::AtomicI64::new(SequenceNumber::default().into()),
[INFO] [stdout]     |                                                   ^^^^^^^^^^^^^^ ambiguous name
[INFO] [stdout]     |
[INFO] [stdout]     = note: ambiguous because of multiple glob imports of a name in the same module
[INFO] [stdout] note: `SequenceNumber` could refer to the struct imported here
[INFO] [stdout]    --> /opt/rustwide/cargo-home/git/checkouts/ros2-client-a2a0f36ac41415ea/3cab61b/src/service/mod.rs:10:3
[INFO] [stdout]     |
[INFO] [stdout]  10 |   *,
[INFO] [stdout]     |   ^
[INFO] [stdout]     = help: consider adding an explicit import of `SequenceNumber` to disambiguate
[INFO] [stdout] note: `SequenceNumber` could also refer to the struct imported here
[INFO] [stdout]    --> /opt/rustwide/cargo-home/git/checkouts/ros2-client-a2a0f36ac41415ea/3cab61b/src/service/mod.rs:18:9
[INFO] [stdout]     |
[INFO] [stdout]  18 | pub use request_id::*;
[INFO] [stdout]     |         ^^^^^^^^^^^^^
[INFO] [stdout]     = help: consider adding an explicit import of `SequenceNumber` to disambiguate
```

This error looks like it plausibly could be intentionally caused by #149195. cc @petrochenkov @mu001999

Errors similar to the above error affect 30 crates that were not previously found by the above PR's [crater run](https://github.com/rust-lang/rust/pull/149195#issuecomment-4058706923):

<details>
<summary>Affected crates</summary>

* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/dora-rs.dora-ros2-bridge/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/bengosney.lightningcss-py/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/tronical.css2slint/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/reg/shfonts-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/jolimail.mrml-core/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/sammosampson.hephaestus/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/PragmaTwice.ichigo-lang/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/ProgramCrafter.salsa-iwj-otter/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/Taher2512.strike-contracts-new/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/WangHoi.rtpmon/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/abdelrahmansheta16.SolLend-Backend/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/bobtajson.sol-oracle/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/dmitriyk-code.github4claude/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/golergka.rs-lox/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/hahastrongshi.rdtls/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/myers.myersrogue/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/nv0skar.Kiban/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/pludov.astro-epd-display/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/sammosampson.hephaestus/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/sum12.crawler/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/sunjay.wolf-asm/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/tiago-vargas.rust-lox-interpreter/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/reg/apple-bundle-0.1.4/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/reg/asn1rs-model-0.3.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/reg/elgamal_ristretto-0.2.3/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/reg/fake-avx512-0.0.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/reg/jsi-sys-0.3.0-alpha.5/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/reg/rsubox-0.2.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/reg/s1mple-0.0.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/reg/zima-0.1.0-alpha.2/log.txt

</details>

**Comment by petrochenkov** [comment]
From a cursory look, everything looks like legitimate examples of ambiguous glob imports.
The lint was reported for several years, most affected crates fixed it, but there's a long tail of outdated versions of the crates stuck in lock files.

**Comment by theemathas** [comment]
Some more instances of this from the **rustdoc** crater run:

<details>
<summary>Affected crates</summary>

* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/reg/jreflection-0.0.11/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/reg/jsi-0.3.0-alpha.5/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/reg/jup-lend-cpi-0.1.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/duesee.mls-utils/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/reg/scylladb-0.1.14/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/reg/resticular-0.1.12/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/AhmedMSedeek.tutorial/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/davidcuellard.scrypto-token-sale/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/flix59.kv_store_test/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/meQlause.synthetic-staking-reward/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/radstarter.BlueprintNftCollection/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/radstarter.BlueprintNftSecondary/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/Budmeister.budc/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/Muhammad-Owais-Warsi.gpui-color-picker/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/agabani.bevy-breakout/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/bcorey.yellow-nylon/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/displaced-lobster.sigil-siege/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/dwino.EngineRustLegionBracketLib/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/hfaulds.game-spike-01-ship-design/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/suxin2017.rust-less/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/tomaka.astc-encoder-rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/gh/wainwrightmark.EquilibriumRust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/reg/gridmapper-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/reg/iop-sdk-wasm-0.0.16/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/reg/jup-flashloan-cpi-0.1.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/reg/mcp-containers-2.2.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/reg/parcel_css-1.0.0-alpha.32/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/reg/tomcrypt-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.98-3/1.98.0-beta.1/reg/whirlpools-oktogen-0.1.0/log.txt

</details>

**Comment by theemathas** [comment]
My understanding of the state of this is: This is intended breakage. However, I find it a bit worrying that there are many instances of this that were not detected by [the previous crater run](https://github.com/rust-lang/rust/pull/149195#issuecomment-4058706923) (used to [inform](https://github.com/rust-lang/rust/pull/149195#issuecomment-4091314853) making that breakage) missed a lot of affected crates.

Should this issue be closed, or should we get FCP from T-lang to affirm the intended breakage first?

**Comment by apiraino** [comment]
Discussed during [T-compiler triage](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202026-07-30/near/613663359).

We are ok with these additional crates accepted as breakage but we want to be sure that also t-lang approves this result, since they were unexpected (see [previous comment](https://github.com/rust-lang/rust/issues/159432#issuecomment-5077541438)). Or at least why the `rustdoc` ones (see Guillaume's [comment](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202026-07-30/near/613667200)).

One discriminating factor is whether this breaking change was behind a FCW for enough time. If this is the case, we're fine with this result. By reading this [comment](https://github.com/rust-lang/rust/pull/149195#issuecomment-4394153304) in #149195 it seems that it is (or should be the case, IIUC). @mejrs is trying to find out in #159901 

@rustbot label -I-compiler-nominated +I-lang-nominated

**Comment by mejrs** [comment]
> [@mejrs](https://github.com/mejrs) is trying to find out in [#159901](https://github.com/rust-lang/rust/issues/159901)

I don't think it is related actually (but someone with more expertise should determine that), the pattern in #159901 has worked and still works unchanged.

My comment in the triage meeting was more about the fact that this code exists in the compiler
```rust
use rustc_span::Ident;

pub fn foo() {
    use rustc_ast::token::*; // Exports (private) `rustc_span::Ident;` and `rustc_ast::TokenKind::Ident`
    // use Ident
}
``` 
yet a FCW was not issued in the local crate. So I'm wondering if we are missing more cases where a FCW should be issued.

**Comment by traviscross** [comment]
We talked about this in the lang meeting with all members present.  We're going to accept this breakage.
