### PR TITLE
Correctly parse `{} && false` in tail expression

### LINKED ISSUE #54186: Two consecutive if lets cannot be used as function result
[MCVE](https://play.rust-lang.org/?gist=7a007ac374bd52313cfeaa58ef6c09e2&version=stable&mode=debug&edition=2015)

    fn nowork(a: Option<u32>, b: Option<u32>) -> bool {
        if let Some(x) = a { true } else { false }
        &&
        if let Some(y) = a { true } else { false }
    }
    
    fn work(a: Option<u32>, b: Option<u32>) -> bool {
        let z = if let Some(x) = a { true } else { false }
        &&
        if let Some(y) = a { true } else { false };
        z
    }

Error:

    error[E0308]: mismatched types
     --> src/main.rs:2:26
      |
    2 |     if let Some(x) = a { true } else { false }
      |                          ^^^^ expected (), found bool
      |
      = note: expected type `()`
                 found type `bool`

    error[E0308]: mismatched types
     --> src/main.rs:2:40
      |
    2 |     if let Some(x) = a { true } else { false }
      |                                        ^^^^^ expected (), found bool
      |
      = note: expected type `()`
                 found type `bool`

    error[E0308]: mismatched types
     --> src/main.rs:3:5
      |
    1 |   fn nowork(a: Option<u32>, b: Option<u32>) -> bool {
      |                                                ---- expected `bool` because of return type
    2 |       if let Some(x) = a { true } else { false }
    3 | /     &&
    4 | |     if let Some(y) = a { true } else { false }
      | |______________________________________________^ expected bool, found &&bool
      |
      = note: expected type `bool`
                 found type `&&bool`

Am I missing something? Why is the first one not allowed, but the second one?

### LINKED ISSUE #74233: 1.35 -> 1.36 regression: && incorrectly considered to be unable to start expressions.
This example [compiles on 1.35 but not 1.36 or later](https://godbolt.org/z/9bWe43):
```rust
pub fn foo() -> &'static &'static bool {
    {} // equivalent to {}; or ();
    &&false
}
```
(The example above was reduced from one involving `match ... {...} && false`, found by @digama0)

This regression was likely introduced by #60188, due to the definition of `can_continue_expr_unambiguously`: https://github.com/rust-lang/rust/blob/daecab3a784f28082df90cebb204998051f3557d/src/librustc_ast/util/parser.rs#L209-L232

That function lists all of the operators that *can't* start an expression, but only continue it.
`LAnd` (`&&`) is incorrectly included, as `&&expr` is parsed the same as `& &expr` at the start of an expression.

cc @estebank

### PR DESCRIPTION
**Pull request by estebank**
Fix #74233, fix #54186.

### CODE REVIEW

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/31818weeklymeeting2020072354818.html#204803375) at weekly T-compiler triage meeting.

Declining to backport (for both nominations). Removing nomination labels accordingly.

**Review by eddyb — APPROVED** [review]
