### ISSUE TITLE
Compilation errors when building rust with GCC 6.1

### ISSUE THREAD

**Issue by rjammala** [rust-lang/rust#33246]
Here is what I get when I clone rust from github and try to build it with GCC 6.1:

```
rjammalamadaka/rust/src/rt/miniz.c: In function ‘tinfl_decompress’:
rjammalamadaka/rust/src/rt/miniz.c:578:9: error: this ‘for’ clause does not guard... [-Werror=misleading-indentation]
         for ( i = 0; i <= 143; ++i) *p++ = 8; for ( ; i <= 255; ++i) *p++ = 9; for ( ; i <= 279; ++i) *p++ = 7; for ( ; i <= 287; ++i) *p++ = 8;
         ^~~
rjammalamadaka/rust/src/rt/miniz.c:578:47: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘for’
         for ( i = 0; i <= 143; ++i) *p++ = 8; for ( ; i <= 255; ++i) *p++ = 9; for ( ; i <= 279; ++i) *p++ = 7; for ( ; i <= 287; ++i) *p++ = 8;
                                               ^~~
rjammalamadaka/rust/src/rt/miniz.c: In function ‘tdefl_find_match’:
rjammalamadaka/rust/src/rt/miniz.c:1396:5: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
     if (!dist) break; p = s; q = d->m_dict + probe_pos; for (probe_len = 0; probe_len < max_match_len; probe_len++) if (*p++ != *q++) break;
     ^~
rjammalamadaka/rust/src/rt/miniz.c:1396:23: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
     if (!dist) break; p = s; q = d->m_dict + probe_pos; for (probe_len = 0; probe_len < max_match_len; probe_len++) if (*p++ != *q++) break;
```

**Comment by nagisa** [comment]
NOTE: I edited you message to format the report.

**Comment by durka** [comment]
Should we fix the code, or just turn off the warning? It looks like miniz.c was imported wholesale from somewhere else...

**Comment by frewsxcv** [comment]
Worth mentioning that we don't have the latest version in-tree:

https://github.com/richgel999/miniz/blob/master/miniz.c

**Comment by adelarsq** [comment]
@alexcrichton Just to know. Any reason to avoid a update for the ```miniz.c``` file?

**Comment by alexcrichton** [comment]
Nah should be fine to update!

**Comment by dns2utf8** [comment]
I updated the miniz.c locally, but it did not compile with gcc 6.1.1.
I am compiling with clang 3.7.1 now with the updated file, works so far.

**Comment by petevine** [comment]
No problem on ARM using gcc 6.1.0, go figure. And I didn't pass `-Wno-error` anywhere.

**Comment by petevine** [comment]
No wait, gcc was bootstrapped with `--disable-werror`

**Comment by dns2utf8** [comment]
I was able to build the compiler and the docs with clang and I opened a issue on miniz.

**Comment by petevine** [comment]
Likewise with gcc, just add `-Wno-error` to your CFLAGS for now.

**Comment by SimonSapin** [comment]
This fixes the build for me with GCC 6.1.1.

```diff
diff --git a/src/rt/miniz.c b/src/rt/miniz.c
index 2b803b0..b3a453d 100644
--- a/src/rt/miniz.c
+++ b/src/rt/miniz.c
@@ -575,7 +575,10 @@ tinfl_status tinfl_decompress(tinfl_decompressor *r, const mz_uint8 *pIn_buf_nex
       {
         mz_uint8 *p = r->m_tables[0].m_code_size; mz_uint i;
         r->m_table_sizes[0] = 288; r->m_table_sizes[1] = 32; TINFL_MEMSET(r->m_tables[1].m_code_size, 5, 32);
-        for ( i = 0; i <= 143; ++i) *p++ = 8; for ( ; i <= 255; ++i) *p++ = 9; for ( ; i <= 279; ++i) *p++ = 7; for ( ; i <= 287; ++i) *p++ = 8;
+        for ( i = 0; i <= 143; ++i) *p++ = 8;
+        for ( ; i <= 255; ++i) *p++ = 9;
+        for ( ; i <= 279; ++i) *p++ = 7;
+        for ( ; i <= 287; ++i) *p++ = 8;
       }
       else
       {
@@ -1393,7 +1396,10 @@ static MZ_FORCEINLINE void tdefl_find_match(tdefl_compressor *d, mz_uint lookahe
         if ((d->m_dict[probe_pos + match_len] == c0) && (d->m_dict[probe_pos + match_len - 1] == c1)) break;
       TDEFL_PROBE; TDEFL_PROBE; TDEFL_PROBE;
     }
-    if (!dist) break; p = s; q = d->m_dict + probe_pos; for (probe_len = 0; probe_len < max_match_len; probe_len++) if (*p++ != *q++) break;
+    if (!dist) break;
+    p = s;
+    q = d->m_dict + probe_pos;
+    for (probe_len = 0; probe_len < max_match_len; probe_len++) if (*p++ != *q++) break;
     if (probe_len > match_len)
     {
       *pMatch_dist = dist; if ((*pMatch_len = match_len = probe_len) == max_match_len) return;

**Comment by dns2utf8** [comment]
There is a PR addressing this: https://github.com/rust-lang/rust/pull/33798

**Comment by dns2utf8** [comment]
And I made a PR to upstream: https://github.com/richgel999/miniz/pull/52
Maybe upgrade miniz after it is merged.

Regards

**Comment by tbu-** [comment]
Fixed by #33798.

**Comment by Keruspe** [comment]
There's still another compilation failure with gcc 6 here

```
/var/tmp/paludis/build/dev-lang-rust-1.9.0-r1/work/rustc-1.9.0/src/rt/hoedown/src/document.c: In function 'char_link':
/var/tmp/paludis/build/dev-lang-rust-1.9.0-r1/work/rustc-1.9.0/src/rt/hoedown/src/document.c:1161:5: error: this 'else' clause does not guard... [-Werror=misleading-indentation]
     else nb_p--; i++;
     ^~~~
/var/tmp/paludis/build/dev-lang-rust-1.9.0-r1/work/rustc-1.9.0/src/rt/hoedown/src/document.c:1161:18: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the 'else'
     else nb_p--; i++;
                  ^
        ^ 
```

**Comment by steveklabnik** [comment]
We have since removed `hoedown` as well. Is anyone still seeing this issue? I believe it can be closed.
