### ISSUE TITLE
Confusing/wrong type inference error

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#46448]
The following code snippet fails to compile:
```rust
fn main() {
    let input = [
        [515, 912, 619, 2043, 96, 93, 2242, 1385, 2110, 860, 2255, 621, 1480, 118, 1230, 99]
    ];
    
    let result: i32 = input.iter().map(|row| {
        for a in row {
            for b in row {
                if a < b && b % a == 0 {
                    return b / a;
                }
            }
        }
        panic!()
    }).sum();

}
```

With the error:
```
error[E0308]: mismatched types
  --> src/main.rs:16:9
   |
16 |         panic!()
   |         ^^^^^^^^ expected (), found i32
   |
   = note: expected type `()`
              found type `i32`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

Since panic returns `!` the error doesn't make sense - the return type should unify with `i32` and everything should be fine. However it seems that's not actually the source of the error, as making this change will fix the program:
```rust
return (b / a) as i32;
```

**Comment by Spoonbender** [comment]
Triage: resolved

This code compiles on stable `rustc 1.59.0 (9d1b2106e 2022-02-23)`

**Comment by saethlin** [comment]
Can confirm, this was and is resolved.
