### ISSUE TITLE
Rust 1.45.0 and above no longer install clippy

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/rust#74431]
When updating from 1.44.1 to 1.45.0, clippy-driver and cargo-clippy are no longer installed by `./x.py install`.
`miri` and `cargo-miri` weren't previously installed but they are now, and the opposite is true for clippy-driver and cargo-clippy

**Comment by Keruspe** [comment]
Currently digging.

Might be related:

```
error[E0635]: unknown feature `const_transmute`                                                                                                                                                                                                
  --> /var/cache/paludis/distfiles/cargo-home/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_ast-664.0.0/lib.rs:13:12                                                                                                                 
   |                                                                                                                                                                                                                                           
13 | #![feature(const_transmute)]                                                                                                                                                                                                              
   |            ^^^^^^^^^^^^^^^       
```

**Comment by Keruspe** [comment]
This was unrelated.

Turns out I get `Dist clippy stage2 (x86_64-unknown-linux-gnu)` but then `skipping Install clippy stage2 (x86_64-unknown-linux-gnu)`

**Comment by Keruspe** [comment]
Ok, before we basically has `if ensure().is_some() || Self::should_install` and now we only have `Self::should_install` which defaults to false if tools isn't set in the configuration, even if extended is set to true

**Comment by Keruspe** [comment]
I think either should_install should default to true if tools is empty (like should_build) or the condition for all optional tools should be `ensure().is_some() && Self::should_install` instead of `||`

As of now, if an optional tool builds fine, it gets installed no matter what the tools config contain, but as soon as it's no longer optional (like clippy in 1.45.0) it doesn't get installed anymore unless its name is explicitely listed in the tools config. This is a really weird behaviour

**Comment by thomasjfox** [comment]
Fedora added this to the configure line for the 1.45.0 upgrade:
```
--tools=analysis,cargo,clippy,rls,rustfmt,src
```
That seems to be a workaround for the moment.

**Comment by Keruspe** [comment]
That's what I ended up doing here too.

The commented value in config.toml.example doesn't reflect the real default though

**Comment by heftig** [comment]
This is a regression. See also the discussion at https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/installing.20clippy.20from.20extended.20build
