### ISSUE TITLE
Defaulted const generic parameters no longer have the const arg's type checked

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#139643]
### Code

I tried this code:

```rust
struct Foo<const N: u32, const M: u64 = N>;
```

I expected to see this happen: It fail to compile like it uised to

Instead, this happened: it compile :>

Probably regressed in #125915 where we started lowering const arguments to `ConstArgKind::Path` instead of `ConstArgKind::Anon` so there is no longer implicitly an anon const with an expected type of `u64` with an expr typed as `u32`.

We *could* probably special case handling of types of defaulted const generics in wfcheck to be done even when generics are involved. Or just accept this as working code which is consistent with things like `struct Foo<T, U = <T as Iterator>::Item>(T, U);` 🤷‍♀ would need a types fcp for that tho

I don't believe this to be a soundness bug

**Comment by BoxyUwU** [comment]
P-low because it's not going to regress anyone, and its not unsound, and is potentially just a bug fix and is in line with how defaulted generic parameters work in general. cc @rust-lang/types

**Comment by lcnr** [comment]
I feel somewhat strongly about it. 

We currently have the approach of: if the default is fully concrete, check its bounds. I would like to extend this to if the *type of the default* is fully concrete, check `ConstArgHasType` for it

**Comment by compiler-errors** [comment]
>  I would like to extend this to if the type of the default is fully concrete, check ConstArgHasType for it

We already do that, I think?

```rust
struct Foo<const N: u32, const M: u64 = "">;
```

```
error[E0308]: mismatched types
 --> src/lib.rs:1:41
  |
1 | struct Foo<const N: u32, const M: u64 = "">;
  |                                         ^^ expected `u64`, found `&str`

For more information about this error, try `rustc --explain E0308`.
```

**Comment by lcnr** [comment]
No, we check `ConstArgHasType` if the *const itself* is concrete. This issue is that for generic constants with concrete types, we don't check `ConstArgHasType` for that concrete type
