### ISSUE TITLE
downcast beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#44445]
The tests of the [downcast](https://crates.io/crates/downcast) crate version 0.9.0 fail on latest beta 1.21, while they work on stable. The error output (full [log](http://cargobomb-reports.s3.amazonaws.com/stable-1.20-beta-1.21.0-beta.1/beta-2017-09-02/reg/downcast-0.9.0/log.txt)):

```
error[E0310]: the parameter type `X` may not live long enough
  --> examples/with_params.rs:11:1
   |
11 | downcast!(<X> Animal<X> where X: Debug);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: consider adding an explicit lifetime bound `X: 'static`...
note: ...so that the type `Animal<X> + 'static` will meet its required lifetime bounds
  --> examples/with_params.rs:11:1
   |
11 | downcast!(<X> Animal<X> where X: Debug);
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: this error originates in a macro outside of the current crate
```

cc @fkoep

**Comment by est31** [comment]
Using bisect-rust I've bisected the regression to 426711d11c6315a0bd5eed01327de824d807b65c (#43786). @scalexm @nikomatsakis is this an expected regression?

**Comment by scalexm** [comment]
@fkoep @est31 This is expected, the type parameter `X` indeed needs a `'static` bound so that the trait object type `Animal<X>` is `'static` (required by the `StdAny` trait). Before #43786, the bound was not checked.

However this code snippet revealed another compiler bug, which may alter the solution I'm proposing (adding a `X: 'static` where clause). Waiting for a confirmation by @nikomatsakis before we can close this issue.

**Comment by nikomatsakis** [comment]
So, this change is indeed correcting a soundness violation (https://github.com/rust-lang/rust/issues/43784), and the change doesn't appear to have caused widespread breakage. Therefore, we are going to leave the code as is. Tagging as relnotes. 

---

@scalexm 

> However this code snippet revealed another compiler bug, which may alter the solution I'm proposing

I guess that you are referring to https://github.com/rust-lang/rust/issues/44454 -- but I think the solution you are proposing is probably still correct, right?

**Comment by scalexm** [comment]
@nikomatsakis yes, just forgot to get back on this.
