### ISSUE TITLE
Rust nightly doesn't build on armv7-sony-vita-newlibeabihf

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/rust#147437]
Build error below. From https://github.com/rust-lang/socket2/actions/runs/18309085762/job/52133230573?pr=617#step:5:51

```rust
  error[E0425]: cannot find value `_SC_HOST_NAME_MAX` in crate `libc`
   --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/net/hostname/unix.rs:8:60
    |
  8 |     let host_name_max = match unsafe { libc::sysconf(libc::_SC_HOST_NAME_MAX) } {
    |                                                            ^^^^^^^^^^^^^^^^^ not found in `libc`
  
  For more information about this error, try `rustc --explain E0425`.
  error: could not compile `std` (lib) due to 1 previous error
```

### Meta

`rustc --version --verbose`:
```
rustc 1.92.0-nightly (3d8c1c1fc 2025-10-06)
binary: rustc
commit-hash: 3d8c1c1fc077d04658de63261d8ce2903546db13
commit-date: 2025-10-06
host: x86_64-unknown-linux-gnu
release: 1.92.0-nightly
LLVM version: 21.1.2
```

**Comment by folkertdev** [comment]
Lots of tier-3 targets are failing with this error (see e.g. https://does-it-build.noratrieb.dev/nightly?nightly=2025-10-06).

 Introduced in https://github.com/rust-lang/rust/pull/146937 cc @joboet

**Comment by ds84182** [comment]
Does the Rust standard library define a minimum POSIX version? Because from my investigation `_SC_HOST_NAME_MAX` is part of POSIX.1-2001 and its predecessor seems to be `MAXHOSTNAMELEN`.

**Comment by workingjubilee** [comment]
No. And I can hardly fault maintainers for not including a random symbol in their libc PR that didn't have an obvious practical use at the time.

Anyways: cc @nikarh @pheki @zetanumbers

**Comment by pheki** [comment]
TYSM @FenrirWolf!!

I got a report that the latest nightly is also failing for the `vita` on missing `libc::utimensat`, which is supported on the vita but not (yet) implemented by newlib

We may need to add it here for now: https://github.com/rust-lang/rust/blob/86b95ebc24092acac75e205d95e84e6d4539601f/library/std/src/sys/fs/unix.rs#L2141

Once the new libc version is released I'm willing to do that

**Comment by FenrirWolf** [comment]
new libc version with the fix is in: https://github.com/rust-lang/libc/releases/tag/0.2.178

**Comment by pheki** [comment]
It turns out that the new version ended up being a near miss due to ambiguous glob exports for `_SC_PAGESIZE` that makes `rustc` not able to resolve it, so while it fixes that issue, it ended up introducing another one.

While investigating that I ended up finding more issues that resulted in libc warnings. PR fixing those: https://github.com/rust-lang/libc/pull/4875

**Comment by pheki** [comment]
I realized  was actually compiling std via `x.py` and even with `rust.deny-warnings = false` in `bootstrap.toml`, the `future_incompatible` lint is denied.

By using the toolchain directly and the patch on `set_times_impl`, it actually works even with the ambiguous export, with "just" a warning:

```
warning: the following packages contain code that will be rejected by a future version of Rust: std v0.0.0 (/path/to/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/src/rust/library/std)
```

That fix is being proposed on https://github.com/rust-lang/rust/pull/150297

The [libc PR](https://github.com/rust-lang/libc/pull/4875) fixing the ambiguous export has been merged and will be eventually backported into libc 0.2.

<details>
<summary>Error and warnings when compiling std via `x.py`</summary>

```
error: `_SC_PAGESIZE` is ambiguous
   --> library/std/src/sys/pal/unix/os.rs:531:34
    |
531 |     unsafe { libc::sysconf(libc::_SC_PAGESIZE) as usize }
    |                                  ^^^^^^^^^^^^ ambiguous name
    |
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #114095 <https://github.com/rust-lang/rust/issues/114095>
    = note: ambiguous because of multiple glob imports of a name in the same module
note: `_SC_PAGESIZE` could refer to the constant defined here
   --> /home/bilko/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libc-0.2.178/src/lib.rs:48:9
    |
 48 | pub use new::*;
    |         ^^^
note: `_SC_PAGESIZE` could also refer to the constant defined here
   --> /home/bilko/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/libc-0.2.178/src/lib.rs:104:17
    |
104 |         pub use crate::unix::*;
    |                 ^^^^^^^^^^^
    = note: `#[deny(ambiguous_glob_imports)]` (part of `#[deny(future_incompatible)]`) on by default

warning: constant `DEV_NULL` is never used
  --> library/std/src/sys/process/unix/common.rs:32:15
   |
32 |         const DEV_NULL: &CStr = c"/dev/null";
   |               ^^^^^^^^
   |
   = note: `#[warn(dead_code)]` (part of `#[warn(unused)]`) on by default

warning: variants `Inherit`, `Explicit`, and `Owned` are never constructed
   --> library/std/src/sys/process/unix/common.rs:118:5
    |
117 | pub enum ChildStdio {
    |          ---------- variants in this enum
118 |     Inherit,
    |     ^^^^^^^
119 |     Explicit(c_int),
    |     ^^^^^^^^
120 |     Owned(FileDesc),
    |     ^^^^^

warning: field `0` is never read
   --> library/std/src/sys/process/unix/common.rs:133:8
    |
133 |     Fd(FileDesc),
    |     -- ^^^^^^^^
    |     |
    |     field in this variant
    |
    = note: `Stdio` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
    |
133 -     Fd(FileDesc),
133 +     Fd(()),
    |

warning: field `0` is never read
   --> library/std/src/sys/process/unix/common.rs:134:14
    |
134 |     StaticFd(BorrowedFd<'static>),
    |     -------- ^^^^^^^^^^^^^^^^^^^
    |     |
    |     field in this variant
    |
    = note: `Stdio` has a derived impl for the trait `Debug`, but this is intentionally ignored during dead code analysis
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
    |
134 -     StaticFd(BorrowedFd<'static>),
134 +     StaticFd(()),
    |

warning: methods `saw_nul`, `get_argv`, `get_program_cstr`, `get_closures`, `capture_env`, and `setup_io` are never used
   --> library/std/src/sys/process/unix/common.rs:241:12
    |
160 | impl Command {
    | ------------ methods in this implementation
...
241 |     pub fn saw_nul(&self) -> bool {
    |            ^^^^^^^
...
274 |     pub fn get_argv(&self) -> &CStringArray {
    |            ^^^^^^^^
...
278 |     pub fn get_program_cstr(&self) -> &CStr {
    |            ^^^^^^^^^^^^^^^^
...
311 |     pub fn get_closures(&mut self) -> &mut Vec<Box<dyn FnMut() -> io::Result<()> + Send + Sync>> {
    |            ^^^^^^^^^^^^
...
335 |     pub fn capture_env(&mut self) -> Option<CStringArray> {
    |            ^^^^^^^^^^^
...
350 |     pub fn setup_io(
    |            ^^^^^^^^

warning: function `construct_envp` is never used
   --> library/std/src/sys/process/unix/common.rs:376:4
    |
376 | fn construct_envp(env: BTreeMap<OsString, OsString>, saw_nul: &mut bool) -> CStringArray {
    |    ^^^^^^^^^^^^^^

warning: method `to_child_stdio` is never used
   --> library/std/src/sys/process/unix/common.rs:396:12
    |
395 | impl Stdio {
    | ---------- method in this implementation
396 |     pub fn to_child_stdio(&self, readable: bool) -> io::Result<(ChildStdio, Option<ChildPipe>)> {
    |            ^^^^^^^^^^^^^^

warning: method `fd` is never used
   --> library/std/src/sys/process/unix/common.rs:476:12
    |
475 | impl ChildStdio {
    | --------------- method in this implementation
476 |     pub fn fd(&self) -> Option<c_int> {
    |            ^^

warning: method `as_ptr` is never used
  --> library/std/src/sys/process/unix/common/cstring_array.rs:45:12
   |
14 | impl CStringArray {
   | ----------------- method in this implementation
...
45 |     pub fn as_ptr(&self) -> *const *const c_char {
   |            ^^^^^^

warning: `std` (lib) generated 10 warnings
error: could not compile `std` (lib) due to 2 previous errors; 10 warnings emitted
```

</details>
