### ISSUE TITLE
Confusing error when passing a closure to a function that expects a reference to a closure.

### ISSUE THREAD

**Issue by sosthene-nitrokey** [rust-lang/rust#116424]
### Code

```Rust
fn testing<F: Fn(u32)>(function: &F) {
    todo!()
}

fn main() {
    testing(|value|{
        value.to_string();
    })
}
```

### Current output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0282]: type annotations needed
 --> src/main.rs:6:14
  |
6 |     testing(|value|{
  |              ^^^^^
7 |         value.to_string();
  |         ----- type must be known at this point
  |
help: consider giving this closure parameter an explicit type
  |
6 |     testing(|value: /* Type */|{
  |                   ++++++++++++

For more information about this error, try `rustc --explain E0282`.
error: could not compile `playground` (bin "playground") due to previous error
```

### Desired output

```Shell
Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
 --> src/main.rs:6:13
  |
6 |       testing(|value|{
  |  _____-------_^
  | |     |
  | |     arguments to this function are incorrect
7 | |         value.to_string();
8 | |     })
  | |_____^ expected `&_`, found closure
  |
  = note: expected reference `&_`
               found closure `{closure@src/main.rs:6:13: 6:25}`
note: function defined here
 --> src/main.rs:1:4
  |
1 | fn testing<F: Fn(u32)>(function: &F) {
  |    ^^^^^^^             ------------
help: consider borrowing here
  |
6 |     testing(&|value|{
  |             +

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` (bin "playground") due to previous error
```

### Rationale and extra context

The thing missing for the code to typecheck is not the type of the closure parameter but the reference to the closure.

The "desired output" is taken from what is obtained after adding the type to the parameter. So following the compiler's suggestion does lead to an error message that is actually helpful. This message should likely be shown in the first place.

### Anything else?

Tested with :

Nightly channel
Build using the Nightly version: 1.75.0-nightly
(2023-10-03 187b8131d4f760f856b2)

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=931b32de6f575e6d9baa46432d973f3f)
