### ISSUE TITLE
Suboptimal diagnostic for `Cow<'static, [SomeType]>` if `SomeType` doesn't implement `Clone`

### ISSUE THREAD

**Issue by weiznich** [rust-lang/rust#141241]
### Code

```Rust
use std::borrow::Cow;

struct A{}

struct B {
    test: Cow<'static, [A]>
    
}
```

### Current output

```Shell
error[E0277]: the trait bound `[A]: ToOwned` is not satisfied
   --> src/main.rs:6:11
    |
6   |     test: Cow<'static, [A]>
    |           ^^^^^^^^^^^^^^^^^ the trait `ToOwned` is not implemented for `[A]`
    |
    = help: the trait `ToOwned` is implemented for `[T]`
note: required by a bound in `Cow`
   --> /playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/borrow.rs:181:8
    |
179 | pub enum Cow<'a, B: ?Sized + 'a>
    |          --- required by a bound in this enum
180 | where
181 |     B: ToOwned,
    |        ^^^^^^^ required by this bound in `Cow`
```

### Desired output

```Shell
error[E0277]: the trait bound `A: Clone` is not satisfied
   --> src/main.rs:6:11
    |
6   |     test: Cow<'static, [A]>
    |           ^^^^^^^^^^^^^^^^^ the trait `Clone` is not implemented for `A`
    |
    = help: consider adding a `#[derive(Clone)]` to `A`
note: required by a bound in `impl ToOwned for [A]`
note: required by a bound in `Cow`
   --> /playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/borrow.rs:181:8
    |
179 | pub enum Cow<'a, B: ?Sized + 'a>
    |          --- required by a bound in this enum
180 | where
181 |     B: ToOwned,
    |        ^^^^^^^ required by this bound in `Cow`
```

### Rationale and extra context

The error message is at the same time claiming that there is a `ToOwned` impl for `[T]`, while it suggests that this impl is missing. I needed to open the documentation to see that the existing impl is bound on `T: Clone`, it would be much better if the error message could mention that on it's own.

### Other cases

```Rust

```

### Rust Version

```Shell
Build using the Nightly version: 1.89.0-nightly

(2025-05-18 4d051fb306e661654d08)
```

### Anything else?

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=32d1974ef50688ff46111907ccd75fbb

**Comment by chenyukang** [comment]
This is fixed on nightly:

```console
help: the trait `ToOwned` is conditionally implemented for `[T]`
  --> $SRC_DIR/alloc/src/slice.rs:LL:COL
   |
   = note: unsatisfied requirement introduced here: `A: Clone`
```

but does not have the suggestion, i think it's ok.
