### ISSUE TITLE
`format!` error has wrong span when using encoded `{`

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#102057]
I tried this code:

```rust
format!("\x7Ba}")
```

I expected to see this happen: a "no value found" error pointing at the `a` token

Instead, this happened: a "no value found" error pointing at the `x7Ba`:

```
error[E0425]: cannot find value `a` in this scope
 --> src/main.rs:2:11
  |
2 | format!("\x7Ba}")
  |           ^^^^ not found in this scope
```

**Comment by cassaundra** [comment]
This doesn't seem to be an issue on stable, interestingly.

**Comment by Nemo157** [comment]
Yep, it works fine on 1.63.0, but has the problem on 1.65.0-beta.1 and the latest nightly.
