### ISSUE TITLE
Type inference failure in unreachable code

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#40073]
The following code works on stable 1.15.1 but not on current nightly compilers ([Play editor](https://is.gd/nj1nQp)):
```
enum X<T> {
    A(T), B
}

fn f(x: u32) -> X<()> {
    match x {
       _ => return X::A(()),
    }
    X::B
}

fn main() {
    f(0);
}
```

I encountered this using `Result` but realised a templated enum is sufficient. I can't replicate when replacing the `match` with an `if`.

**Comment by dhardy** [comment]
Maybe I should paste the error message too:
```
rustc 1.17.0-nightly (0f34b532a 2017-02-21)
error[E0282]: type annotations needed
 --> <anon>:9:5
  |
9 |     X::B
  |     ^^^^ cannot infer type for `T`

error: aborting due to previous error
```

**Comment by leonardo-m** [comment]
Note that X::B is an unreachable expression.

**Comment by dhardy** [comment]
That observation may be the key to it, thanks. I hadn't realised my `match` expression never returned.

In this case the error makes perfect sense (since `X::B` is never associated with the return type), but the error is misleading. Why even try to type-check unreachable code?

**Comment by TimNN** [comment]
Duplicate of #39984; as mentioned there likely caused by #39485 and potentially expected breakage?
