### ISSUE TITLE
Infinite nested structs started compiling in release mode

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#157047]
### Code

I'm not sure if this is a bug or not.

This weirdness was discovered while investigating https://github.com/rust-lang/unsafe-code-guidelines/issues/413. See also https://github.com/rust-lang/rust/issues/149898#issuecomment-4551058234. cc @RalfJung 

I tried this code:

```rust
use std::marker::PhantomData;

trait Chain {
    type Next;
}

impl<T> Chain for T {
    type Next = Thing<Option<T>>;
}

struct Thing<T: Chain>(T::Next, PhantomData<T>);

// Thing<i32> contains infinitely many layers of nested structs

#[inline(never)]
fn dummy<T>(_: T) {}

fn make_ptr<T: Chain>() {
    let x: *const Thing<T> = unsafe { std::mem::transmute(1_usize) };
    dummy(x);
}

fn main() {
    make_ptr::<i32>();
}
```

I compiled the code in release mode.

This code previously errored with the following error:
```
error: queries overflow the depth limit!
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`playground`)
  = note: query depth increased by 130 when computing layout of `Thing<i32>`
```

The code now compiles without errors.

### Version it worked on

The code failed to compile on the playground with stable rust version `1.95.0`.

### Version with regression

The code compiled without errors on the playground with rust version `1.97.0-beta.1 (2026-05-26 96f70397ed7ba8baf8d1)`

**Comment by theemathas** [comment]
Relatedly, the following code already compiles on 1.95.0 stable in release mode, and it's unclear to me whether it has UB or not.

```rust
use std::marker::PhantomData;

trait Chain {
    type Next;
}

impl<T> Chain for T {
    type Next = Thing<Option<T>>;
}

struct Thing<T: Chain>(T::Next, PhantomData<T>);

// Thing<i32> contains infinitely many layers of nested structs

fn project<T: Chain>() {
    let x: &Thing<T> = unsafe { std::mem::transmute(1_usize) };
    let y: &T::Next = &x.0;
}

fn main() {
    project::<i32>();
}
```

**Comment by RalfJung** [comment]
I think the question whether the code has UB is meaningless as the type does not exist. ;)

Cc @lcnr

**Comment by theemathas** [comment]
I bisected the code (with a raw pointer passed to a `#[inline(never)]` function) in the original issue with `cargo-bisect-rustc --start 1.95.0 --end beta --regress success -- build --release`.

```
searched toolchains bb779a91568ac1ee0b8a9dcb6b69219ef30b18a3 through 3bf5c6d99bc8a0c0d5b2f69826ed4f6d256a0a21


********************************************************************************
Regression in 64b72a1fa5449d928d5f553b01a596b78ee255d2
********************************************************************************

Attempting to search unrolled perf builds
ERROR: couldn't find perf build comment
```

Regressed in #150447. That.... doesn't make much sense to me. cc @WaffleLapkin

Also note that this regression/change affects the upcoming 1.96.0 version.

**Comment by RalfJung** [comment]
I think the diff [here](https://github.com/rust-lang/rust/pull/150447/changes#diff-b0320c2b8868f325d83c027fc5d71732636e9763551e35895488f30fe057c6e9) means that for raw pointers we now don't compute the layout of the pointee any more in some cases where we previously used to do that, which explains why that example now compiles.

**Comment by jieyouxu** [comment]
(Going to tag this as `regression-to-stable` since 1.96 is essentially the stable release today)

**Comment by WaffleLapkin** [comment]
I looked into it briefly just now; here are some of my thoughts:

----

If you replace `type Next = Thing<Option<T>>;` with `type Next = Thing<T>;` you can actually get a reasonable error (on old versions/debug):

```
error[E0391]: cycle detected when computing layout of `Thing<i32>`
  --> src/main.rs:11:1
   |
11 | struct Thing<T: Chain>(T::Next, PhantomData<T>);
   | ^^^^^^^^^^^^^^^^^^^^^^
   |
note: ...which requires computing layout of `<i32 as Chain>::Next`...
  --> src/main.rs:4:5
   |
 4 |     type Next;
   |     ^^^^^^^^^
   = note: ...which again requires computing layout of `Thing<i32>`, completing the cycle
   = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
```

---

The reason that the error is optimization level dependent is that the `layout_of` that triggers the error happens in codegen. If mir opts remove the code before it goes to codegen, there are no calls to `layout_of` and thus no error.

---

It's a bit weird that we disallow

```rust
struct X(X);
```
saying "`error[E0072]: recursive type `X` has infinite size`". Nothing is stopping us from making `X` have finite size (`0`) (this is not very useful as it only works for zsts, but maybe the error should be tweaked for this case).

---

Depending on `layout_of` being called in random places (like the code I changed in #150447) seems fragile. If we truly wanted to disallow infinitely recursive types, we should probably either check for them explicitly, or call `layout_of` on all types explicitly (both of which probably result in perf loss...)

**Comment by RalfJung** [comment]
Yeah that's a problem for which we already have an issue somewhere I think -- the exact set of types that gets checked for "well-formedness" is optimization-dependent. This mostly affects things like `[u8; usize::MAX]`, i.e. types that are ill-formed for being too big, but apparently it also affects types that are ill-formed for being too recursive.

**Comment by scottmcm** [comment]
This also makes me think of #153205 where nested structs also get through to MIR optimizations to cause problems there.

**Comment by RalfJung** [comment]
> This mostly affects things like [u8; usize::MAX], i.e. types that are ill-formed for being too big, but apparently it also affects types that are ill-formed for being too recursive.

Took me a bit to find that example again -- it is [here](https://github.com/rust-lang/rust/pull/104087#issuecomment-2035070170). @scottmcm you never turned that into an issue, or did you?

Here's an updated version of the example:
```rust
#![crate_type = "lib"]

#[unsafe(no_mangle)]
pub fn f() {
    g::<u16>();
}

pub fn g<T>() -> std::mem::MaybeUninit<[T; 1 << 62]> {
    std::mem::MaybeUninit::uninit()
}
```

**Comment by scottmcm** [comment]
No, I don't think I ever make an issue for that problem.

**Comment by RalfJung** [comment]
All right, I made one: https://github.com/rust-lang/rust/issues/157654
