### ISSUE TITLE
Standard library fails to build for arm64_32-apple-watchos

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/rust#147776]
Building the latest nightly with `--target arm64_32-apple-watchos`, fails with the following:

```rust
  error[E0308]: mismatched types
     --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/sync/condvar.rs:123:21
      |
  123 |             tv_sec: dur.as_secs() as i64,
      |                     ^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `i64`
  
  error[E0308]: mismatched types
     --> /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/pal/unix/sync/condvar.rs:124:22
      |
  124 |             tv_nsec: dur.subsec_nanos() as i64,
      |                      ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `i32`, found `i64`
```

### Meta

`rustc --version --verbose`:
```
rustc 1.92.0-nightly (57ef8d642 2025-10-15)
binary: rustc
commit-hash: 57ef8d642d21965304bde849bab4f389b4353e27
commit-date: 2025-10-15
host: x86_64-unknown-linux-gnu
release: 1.92.0-nightly
LLVM version: 21.1.3
```
<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by madsmtm** [comment]
Introduced in https://github.com/rust-lang/rust/pull/146503, I suspect it fails on other 32-bit targets as well.

CC @joboet, do you wanna take a look, or should I?

**Comment by NobodyXu** [comment]
This has been breaking cc pipeline and preventing release, any plan to fix this?

**Comment by Noratrieb** [comment]
You should remove it from the pipeline if this blocks you. This is a tier 3 target and therefore provided on an "as-is" basis and supported by the target maintainers.

**Comment by madsmtm** [comment]
> This has been breaking cc pipeline and preventing release, any plan to fix this?

Though to answer more directly, yes, I do plan to fix this, will hopefully post a PR today or tomorrow.
