### PR TITLE
Function pointers as const generic arguments

### LINKED ISSUE #62395: Const generics with function pointers produces linker error.
When attempting to compile a program using const generic function pointers, I get the following linker error:

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/playground/target/debug/deps/playground-343407c725b154da.playground.9gij2ntw-cgu.0.rcgu.o" "-o" "/playground/target/debug/deps/playground-343407c725b154da" "/playground/target/debug/deps/playground-343407c725b154da.3lfkt68d9bwnd0w.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/playground/target/debug/deps" "-L" "/playground/target/debug/build/backtrace-sys-0bad857f246b8d46/out" "-L" "/playground/target/debug/build/miniz-sys-cc52677d966ce23b/out" "-L" "/playground/target/debug/build/ring-3ec1d93b15dca95a/out" "-L" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-3155131507cc46c3.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-d295083df0b8f9bc.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-ee721caa5e399a5b.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-f522ac12e8b57785.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-fde635d685e9d5b4.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-400b98aa42a3327b.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-8d4d01f94c0ba00e.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-bbe52d74e07e8ddb.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-7809a3c56dc793e3.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-eb4f3199c7861934.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-33ebcd88f3886c16.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-a2ceb2a4c1b13237.rlib" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-c19151a56f15ba15.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-0ce4526441314674.rlib" "-Wl,-Bdynamic" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: /playground/target/debug/deps/playground-343407c725b154da.playground.9gij2ntw-cgu.0.rcgu.o: In function `playground::Wrapper<_>::call':
          /playground/src/main.rs:11: undefined reference to `playground::hello_world'
          collect2: error: ld returned 1 exit status
```

Source:
```rs
#![feature(const_generics)]

fn hello_world() {
    println!("Hello, world!");
}

struct Wrapper<const F: fn() -> ()>;

impl<const F: fn() -> ()> Wrapper<{F}> {
    fn call() {
        F();
    }
}

fn main() {
    Wrapper::<{hello_world}>::call();
}
```

I'm not sure what the intended behavior should be here, but I was expecting to be able to call the function that I passed as a const generic parameter, which the compiler seems to accept as valid, but is failing during the linking step.

### PR DESCRIPTION
**Pull request by BenLewis-Seequent**
Makes function pointers as const generic arguments usable. 

Fixes #62395

r? @varkor

### CODE REVIEW

File: src/librustc/ty/relate.rs [hunk 1]
```diff
@@ -561,37 +561,39 @@ pub fn super_relate_consts<R: TypeRelation<'tcx>>(
...
-                ty: a.ty,
-            }))
+        (ConstValue::Scalar(a_val), ConstValue::Scalar(b_val)) if a.ty == b.ty => {
+            if a_val == b_val {
+                Ok(ConstValue::Scalar(a_val))
+            } else if let ty::FnPtr(_) = a.ty.kind {
+                let alloc_map = tcx.alloc_map.lock();
+                let a_instance = alloc_map.unwrap_fn(a_val.to_ptr().unwrap().alloc_id);
+                let b_instance = alloc_map.unwrap_fn(b_val.to_ptr().unwrap().alloc_id);
+                if a_instance == b_instance {
```
Comment (oli-obk) [inline src/librustc/ty/relate.rs]: We don't support comparing function pointers in const eval because it's not clear what the behaviour should be.

1. In llvm it can happen that two different functions in fact have the same pointer (due to deduplicaton optimizations).
2. If a function `f` is defined in crate `a`, crates `b` and `c` take a function pointer to `f` and crate `d` compares these function pointers, the pointers can be unequal, due to `b` and `c` having their own copy of the function

I don't think we should expose function pointers to const generics until we've come to a solution in const eval.

Comment (oli-obk) [reply src/librustc/ty/relate.rs]: The tracking issue is https://github.com/rust-lang/rust/issues/53020

I think it would be ok if the use of function pointers in const generics were additionally gated by the `const_compare_raw_pointers` feature gate.

**Comment by varkor** [comment]
It would definitely be good not to ICE, or emit a link error here. Let's put the ability to use pointers in const arguments behind `const_compare_raw_pointers` as @oli-obk suggested, so people can play around with it intentionally, but it will throw a proper feature gate error otherwise.

**Comment by oli-obk** [comment]
> It would definitely be good not to ICE, or emit a link error here.

Oh I wasn't even worried about that, but UX is a good point, too. I worry about unsoundness because of differences between runtime and compile time for the same const evaluable code.

File: src/librustc_mir/monomorphize/collector.rs [hunk 2]
```diff
@@ -1264,7 +1264,13 @@ fn collect_const<'tcx>(
 ) {
     debug!("visiting const {:?}", constant);
 
-    match constant.val {
+    let substituted_constant = if let ConstValue::Param(param) = constant.val {
+        param_substs.const_at(param.index as usize)
+    } else {
+        constant
+    };
```
Comment (eddyb) [inline src/librustc_mir/monomorphize/collector.rs]: IMO it would be easier to substitute in the caller or even here but irrespective of the kind of constant, right now Unevaluated also has unnecessarily specific code.

Not to mention this should probably also normalize.

File: src/librustc/ty/print/pretty.rs [hunk 3]
```diff
@@ -973,6 +973,18 @@ pub trait PrettyPrinter<'tcx>:
                 return Ok(self);
             }
         }
+
+        if let ty::FnPtr(_) = ct.ty.kind {
```
Comment (Centril) [inline src/librustc/ty/print/pretty.rs]: The usage of `if let` throughout this function is pretty weird; should be rewritten with a `match` instead imo.

Comment (oli-obk) [reply src/librustc/ty/print/pretty.rs]: I tried that before. It becomes a mess because of all the fallbacks

Comment (Centril) [reply src/librustc/ty/print/pretty.rs]: In my experience that indicates that some functions need to be extracted.

Comment (skinny121) [reply src/librustc/ty/print/pretty.rs]: I managed to refactor it into a `match` statement, only the byte string and string case are a bit awkward.

**Comment by skinny121** [comment]
I gated the use of both raw pointers and function pointers behind the feature gate `const_compare_raw_pointers`.

File: src/librustc_typeck/collect.rs [hunk 4]
```diff
@@ -1511,9 +1511,29 @@ pub fn checked_type_of(tcx: TyCtxt<'_>, def_id: DefId, fail: bool) -> Option<Ty<
         }
 
         Node::GenericParam(param) => match &param.kind {
-            hir::GenericParamKind::Type { default: Some(ref ty), .. } |
-            hir::GenericParamKind::Const { ref ty, .. } => {
-                icx.to_ty(ty)
+            hir::GenericParamKind::Type { default: Some(ref ty), .. } => icx.to_ty(ty),
+            hir::GenericParamKind::Const { ty: ref hir_ty, .. } => {
```
Comment (oli-obk) [inline src/librustc_typeck/collect.rs]: @varkor do we have a type whitelist somewhere? I remember there being a thing where we only allow specific types for const generics

Comment (varkor) [reply src/librustc_typeck/collect.rs]: It hasn't been implemented yet: https://github.com/rust-lang/rust/issues/60286.

**Review by oli-obk — APPROVED** [review]

File: src/librustc_typeck/collect.rs [hunk 5]
```diff
@@ -1511,9 +1511,29 @@ pub fn checked_type_of(tcx: TyCtxt<'_>, def_id: DefId, fail: bool) -> Option<Ty<
...
+                        _ => None,
+                    };
+                    if let Some(unsupported_type) = err {
+                        feature_gate::emit_feature_err(
+                            &tcx.sess.parse_sess,
+                            sym::const_compare_raw_pointers,
+                            hir_ty.span,
+                            feature_gate::GateIssue::Language,
+                            &format!(
+                                "use of {} as const generic arguments are unstable",
```
Comment (varkor) [inline src/librustc_typeck/collect.rs]:
```suggestion
                                "using {} as const generic parameters is unstable",
```

**Review by varkor — COMMENTED** [review]
Thanks, this looks great! Minor diagnostic suggestion, and then it looks good to go!

**Comment by varkor** [comment]
(@skinny121: you'll need to run `x.py test src/test/ui --bless` to update the stderr files afterwards.)

**Comment by skinny121** [comment]
I forgot that I would have to do that :). I also rebased so that the stderr files reflect the changes from #65154.

File: src/test/ui/const-generics/raw-ptr-const-param.stderr [hunk 6]
```diff
@@ -0,0 +1,20 @@
...
+LL | #![feature(const_generics, const_compare_raw_pointers)]
+   |            ^^^^^^^^^^^^^^
+   |
+   = note: `#[warn(incomplete_features)]` on by default
+
+error[E0308]: mismatched types
+  --> $DIR/raw-ptr-const-param.rs:7:38
+   |
+LL |     let _: Const<{15 as *const _}> = Const::<{10 as *const _}>;
+   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^ expected `Scalar(0x000000000000000f) : *const u32`, found `Scalar(0x000000000000000a) : *const u32`
```
Comment (varkor) [inline src/test/ui/const-generics/raw-ptr-const-param.stderr]: These diagnostics are not great, but we can file an issue for that.

**Comment by varkor** [comment]
Thanks!

@bors r+ rollup

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/65227#issuecomment-539807302, @bors r-

**Comment by varkor** [comment]
Maybe we should normalise the printing of pointers to `{pointer}` or similar.

**Comment by eddyb** [comment]
> I changed the printing of point to `{pointer}`. This can probably be improved in future to be more detailed, as currently, it will produce potentially confusing diagnostics where found type looks the same as the expected type.

If there wasn't an issue opened for fixing this, there should be, so we won't forget about it.
