### ISSUE TITLE
`is_x86_feature_detected!("avx512f")` fails to build on beta and nightly

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/rust#68905]
The following program builds and runs on stable but fails to build on nightly:

```rust
fn main() {
    dbg!(is_x86_feature_detected!("avx512f"));
}
```

Here's the build error on `rustc 1.43.0-nightly (58b834344 2020-02-05)`:

```
error[E0658]: use of unstable library feature 'stdsimd'
 --> src/main.rs:2:10
  |
2 |     dbg!(is_x86_feature_detected!("avx512f"));
  |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/27731
  = help: add `#![feature(stdsimd)]` to the crate attributes to enable
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

But note that if I replace `"avx512f"` with `"avx2"`, the error goes away.

**Comment by Mark-Simulacrum** [comment]
cc @gnzlbg

**Comment by oconnor663** [comment]
Here's the output of `cargo-bisect-rustc`:

searched nightlies: from nightly-2020-01-02 to nightly-2020-02-10
regressed nightly: nightly-2020-02-06
searched commits: from https://github.com/rust-lang/rust/commit/c9290dceee2cb6b882b26ec6e294560e51ef0853 to https://github.com/rust-lang/rust/commit/58b834344fc7b9185e7a50db1ff24e5eb07dae5e
regressed commit: https://github.com/rust-lang/rust/commit/eda1a7adfcf6de70afa4ca0a6f709ed0e507516a

That points to https://github.com/rust-lang/rust/pull/68755, which is a large merge of stdarch. When I bisect stdarch, I find the error was introduced in https://github.com/rust-lang/stdarch/commit/cb6fa6800159e062ccb38c1179d69f19e1dde272, possibly intentionally. Is it the case that AVX-512 feature detection was never intended to be stabilized? Or maybe it got caught up in a larger group of unstable features? Prior to this regression, it did in fact work :)

**Comment by oconnor663** [comment]
A quick search through https://github.com/search?q=is_x86_feature_detected%21%28%22avx512f%22%29&type=Code turns up at least one other crate that fails to build on nightly for this reason:

```
git clone https://github.com/PoC-Consortium/scavenger
cd scavenger
cargo check --features=simd           # succeeds
cargo +nightly check --features=simd  # fails

**Comment by oconnor663** [comment]
@Mark-Simulacrum, this might be a hi-pri regression. (Though of course I'm biased cause it affects my crate.) If @gnzlbg isn't available to evaluate it, could we pull in someone else?

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/libs 

To be honest I'm not even entirely sure where this macro is implemented...

**Comment by Amanieu** [comment]
Caused by https://github.com/rust-lang/stdarch/pull/739, which started enforcing stability on individual features.

**Comment by oconnor663** [comment]
It looks like a crater run was done in September, but the `blake3` crate was published in January. Notably, that crate relies on std to _detect_ AVX-512 support, but the actual AVX-512 implementation code is in C or assembly. Also the `scavenger` crate I mentioned above hides its use of AVX-512 detection behind its `simd` feature, so I don't think crater would've caught it.

**Comment by Mark-Simulacrum** [comment]
Seems like there was no discussion done of whether this would break folks (or at least I can't find it). Clearly this is "permitted" under a strict interpretation of our stability rules, though is not documented on the macro at all; [the docs](https://doc.rust-lang.org/nightly/std/macro.is_x86_feature_detected.html) list avx512f with no warning that it is unstable. That at least sounds like a bug.

I guess someone (libs team?) needs to make a call on whether this is a bug, and whether we should fix it.

**Comment by Amanieu** [comment]
Considering that this broke two crates on stable, I think we should just go ahead and stabilize the avx512 features. I don't think there is any particular reason for holding back on them.

**Comment by pnkfelix** [comment]
(nominating to try to ensure T-libs resolves this in some manner before this hits stable.)

**Comment by sfackler** [comment]
Even if we don't want to stabilize the intrinsics themselves for whatever reason, it seems fine to allow detection of avx512 support via the macro.

**Comment by Mark-Simulacrum** [comment]
Could someone on T-libs fcp a stabilization for the following x86 features, which have been destabilized in nightly:

* mmx
* sse4a
* avx512f
* avx512cd
* avx512er
* avx512pf
* avx512bw
* avx512dq
* avx512vl
* avx512ifma
* avx512vbmi
* avx512vpopcntdq
* tbm

https://doc.rust-lang.org/nightly/std/macro.is_x86_feature_detected.html#supported-arguments

Once we get the ball rolling on that, I can work on trying to fix whatever the root cause of this destabilization is.

**Comment by Mark-Simulacrum** [comment]
(Or, if we don't want to stabilize all of them, and want to say "oh well breaking change", then that would be helpful too).

**Comment by Amanieu** [comment]
Also see #60109: there was an approved FCP to stabilize adx, tbm and sse4a but it got closed because the PR author was inactive.

**Comment by Amanieu** [comment]
According to https://github.com/rust-lang/stdarch/issues/310, it seems that a lot of AVX512 intrinsics are missing from `std::arch`. As such I don't think it really makes sense to stabilize the AVX512 feature.

I think the best approach would be to stabilize avx512 only for `is_x86_feature_detected`, since it was already (accidentally) stable and code is relying on it.

Any thoughts @rust-lang/libs @gnzlbg? I will write up a PR for stdarch if there are no objections.

**Comment by BurntSushi** [comment]
It seems to me that stabilizing `avx512` just as a parameter to `is_x86_feature_detected` should be fine? As in, I don't think there's any hazard of us never stabilizing it.

I'd be more skeptical of blanket stabilizing a bunch of parameters to `is_x86_feature_detected` though. For example, we might want to never stabilize anything to do with `mmx`.

>  it seems that a lot of AVX512 intrinsics are missing from std::arch. As such I don't think it really makes sense to stabilize the AVX512 feature.

Definitely agree here.

**Comment by Mark-Simulacrum** [comment]
To be clear, stable *today* has the list in https://github.com/rust-lang/rust/issues/68905#issuecomment-589098209 stabilized, which includes mmx -- we can technically say "woops" I guess and revert that to being unstable, but that seems not great. (Though if there are good reasons to do so, then perhaps we should.)

**Comment by mati865** [comment]
There are good reasons to forbid MMX. It's the only instruction from the list above which can cause misoptimization (breaking otherwise sound code).
It's removal is discussed in https://github.com/rust-lang/stdarch/issues/823

**Comment by oconnor663** [comment]
Is it important to get fixes in before the next beta is tagged in a couple weeks?

**Comment by Mark-Simulacrum** [comment]
It would be good, but I think it's not critical. We can always backport.

**Comment by oconnor663** [comment]
I've opened https://github.com/rust-lang/stdarch/pull/842 as a first stab at an upstream fix. That one only re-stabilizes the AVX-512 features (that were stable before), leaving `mmx`, `sse4a`, and `tbm` as they are. It sounds like we specifically don't want to include `mmx`, though I'm not sure what to do with the other two.

**Comment by mati865** [comment]
> It sounds like we specifically don't want to include mmx, though I'm not sure what to do with the other two.

Upstream topic about `sse4a` and `tbm`: https://github.com/rust-lang/stdarch/issues/668

**Comment by joshtriplett** [comment]
We discussed this in the language team meeting. We agreed that we should stabilize *processor feature detection* even if we don't have *intrinsics* for a given feature. So, in particular, we should re-stabilize support in `is_x86_feature_detected!` for any feature we know how to detect, even those we don't have stable intrinsics for. (That includes `mmx`, even though it doesn't sound like anyone is likely to care about it.)

@rfcbot poll lang Re-stabilize is_x86_feature_detected for any processor feature we know how to detect?

**Comment by Amanieu** [comment]
The following workaround can be used to detect AVX512F and AVX512VL (which is what BLAKE3 uses) without depending on any unstable features:

```rust
// Detection code based on the std_detect crate
#[cfg(any(target_arch = "x86", target_arch = "x86_64"))]
pub fn avx512f_avx512vl_detected() -> bool {
    use std::arch::x86_64::*;

    // Check for avx2 to ensure all needed CPUID features are available.
    if !is_x86_feature_detected!("avx2") {
        return false;
    }

    unsafe {
        // Check that the OS supports AVX512
        let xcr0 = _xgetbv(0);
        let os_avx512_support = xcr0 & 224 == 224;
        if !os_avx512_support {
            return false;
        }

        // Check that the CPU supports AVX512F and AVX512VL
        let CpuidResult { ebx, .. } = __cpuid(7);
        let avx512f = ebx & 1 << 16 != 0;
        let avx512vl = ebx & 1 << 31 != 0;
        avx512f && avx512vl
    }
}
```

Considering that these features were accidentally stabilized and that only 2 crates are depending on them I would propose that:
- We do not stabilize the avx512 detection flags.
- BLAKE3 and scavenger switch to using the above detection function.

**Comment by Mark-Simulacrum** [comment]
We have no concrete evidence it's just two crates though, right?

I myself was pretty convinced by @joshtriplett's argument in the lang team meeting that there's not really any reason to not stabilize detection for anything that we can reliably detect; the intrinsics themselves are a different story.

IIRC, one key benefit of the macro is that it globally caches the results, whereas your function would need additional work to do so, I think?

**Comment by Centril** [comment]
> We have no concrete evidence it's just two crates though, right?

(Not that this changes my view per the poll above, but I think we should not consider "absence of evidence is not evidence of absence" as a good argument. I think we should assume, for practical purposes, that there are no regressed crates until there's *positive* empirical evidence for something.)

**Comment by lu-zero** [comment]
I would avoid any kind of handcrafted cpudetection code scattered around.

(I have a patch pending in rav1e waiting for the avx512 cpu detection support to stabilize and probably other projects are in a similar situation)

**Comment by Amanieu** [comment]
Here's another affected crate: https://github.com/solana-labs/solana/commit/60877f9ba48c2c20cb90b522a5bb690d7989d85a

I've reconsidered my position: since `cfg(target_feature = "X")` is already stable for all feature flags (stable or unstable), I don't think it makes sense to block the same flag names for runtime feature detection.

**Comment by pnkfelix** [comment]
> I think we should assume, for practical purposes, that there are no regressed crates until there's _positive_ empirical evidence for something.

To me, the phrase "We should assume there are no regressed crates \[until there's empirical evidence otherwise\]" describes a model that is, in my opinion, too willing to accept breakage unnecessarily, and is not in line with ["if you are using the stable release of Rust, you will never dread upgrading to the next release"](https://blog.rust-lang.org/2014/10/30/Stability.html)

(But maybe I'm just someone who does think that the "absence of evidence" maxim *is* worth raising from time to time.)

**Comment by pnkfelix** [comment]
triage: After spending a while explaining this bug to @spastorino , I figured I should take the plunge and mark this as P-high.

(I'm not 100% sure if it is a release blocker per se, but my interpretation of the [comments above](https://github.com/rust-lang/rust/issues/68905#issuecomment-592063891) is that we would prefer to either land a fix for this before beta is cut or, failing that, prioritize a backport to the beta branch, so that the bug itself never hits stable.)

**Comment by Amanieu** [comment]
OK, let's try to make some progress on this. I'd like to propose stabilizing the following features for feature detection only:
- mmx
- sse4a
- tbm
- avx512f
- avx512cd
- avx512er
- avx512pf
- avx512bw
- avx512dq
- avx512vl

The SSE4a and TBM features were already scheduled to be stabilized in #60109, but the PR got abandoned. Only a subset of the AVX512 features are listed here because there is some uncertainty with the newer ones as to whether they should contain an underscore: `avx512vbmi` vs `avx512_vbmi`. Finally MMX, while not supported by LLVM, is a well known feature name.

@rfcbot fcp merge

**Comment by oconnor663** [comment]
https://github.com/rust-lang/stdarch/pull/842 is now up to speed with @Amanieu's proposal above.

**Comment by oconnor663** [comment]
As of the 1.42 release today, `cargo +beta install b3sum` is failing. This fix will need to be backported.

**Comment by Amanieu** [comment]
PR to update the submodule is here: #70151

I will need to be backported to beta.
