### ISSUE TITLE
loads.rs & stores.rs tests are failing with LLVM 3.6.1

### ISSUE THREAD

**Issue by sylvestre** [rust-lang/rust#27628]
```
---- [codegen] codegen/stores.rs stdout ----
	
error: verification with 'FileCheck' failed
status: exit code: 1
command: /usr/lib/llvm-3.6/bin/FileCheck -input-file=x86_64-unknown-linux-gnu/test/codegen/stores.ll /home/sylvestre/dev/debian/rustc.git/src/test/codegen/stores.rs
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
/home/sylvestre/dev/debian/rustc.git/src/test/codegen/stores.rs:25:11: error: expected string not found in input
// CHECK: [[VAR:%[0-9]+]] = load [4 x i8]*, [4 x i8]** %x
          ^
x86_64-unknown-linux-gnu/test/codegen/stores.ll:11:35: note: scanning from here
define void @small_array_alignment([4 x i8]* noalias dereferenceable(4)) unnamed_addr #0 {
                                  ^
x86_64-unknown-linux-gnu/test/codegen/stores.ll:14:2: note: possible intended match here
 %1 = bitcast [4 x i8]** %x to i8*
 ^
/home/sylvestre/dev/debian/rustc.git/src/test/codegen/stores.rs:36:11: error: expected string not found in input
// CHECK: [[VAR:%[0-9]+]] = load %Bytes*, %Bytes** %x
          ^
x86_64-unknown-linux-gnu/test/codegen/stores.ll:33:36: note: scanning from here
define void @small_struct_alignment(%Bytes* noalias dereferenceable(4)) unnamed_addr #0 {
                                   ^
x86_64-unknown-linux-gnu/test/codegen/stores.ll:36:2: note: possible intended match here
 %1 = bitcast %Bytes** %x to i8*
 ^

------------------------------------------

thread '[codegen] codegen/stores.rs' panicked at 'explicit panic', /home/sylvestre/dev/debian/rustc.git/src/compiletest/runtest.rs:1497


---- [codegen] codegen/loads.rs stdout ----
	
error: verification with 'FileCheck' failed
status: exit code: 1
command: /usr/lib/llvm-3.6/bin/FileCheck -input-file=x86_64-unknown-linux-gnu/test/codegen/loads.ll /home/sylvestre/dev/debian/rustc.git/src/test/codegen/loads.rs
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
/home/sylvestre/dev/debian/rustc.git/src/test/codegen/loads.rs:23:11: error: expected string not found in input
// CHECK: load i32*, i32** %x{{.*}}, !nonnull
          ^
x86_64-unknown-linux-gnu/test/codegen/loads.ll:12:39: note: scanning from here
define dereferenceable(4) i32* @borrow(i32* noalias readonly dereferenceable(4)) unnamed_addr #0 {
                                      ^
x86_64-unknown-linux-gnu/test/codegen/loads.ll:18:7: note: possible intended match here
 %2 = load i32** %x, align 8, !nonnull !0
      ^
/home/sylvestre/dev/debian/rustc.git/src/test/codegen/loads.rs:30:11: error: expected string not found in input
// CHECK: load i32*, i32** %x{{.*}}, !nonnull
          ^
x86_64-unknown-linux-gnu/test/codegen/loads.ll:31:17: note: scanning from here
define i32 @_box(i32* noalias dereferenceable(4)) unnamed_addr #0 {
                ^
x86_64-unknown-linux-gnu/test/codegen/loads.ll:37:7: note: possible intended match here
 %2 = load i32** %x, align 8, !nonnull !0
      ^
/home/sylvestre/dev/debian/rustc.git/src/test/codegen/loads.rs:39:11: error: expected string not found in input
// CHECK: [[VAR:%[0-9]+]] = load i32, i32* %{{.*}}, align 1
          ^
x86_64-unknown-linux-gnu/test/codegen/loads.ll:247:34: note: scanning from here
define i32 @small_array_alignment(i32) unnamed_addr #0 {
                                 ^
x86_64-unknown-linux-gnu/test/codegen/loads.ll:261:2: note: possible intended match here
 %7 = load i32* %6, align 1
 ^
/home/sylvestre/dev/debian/rustc.git/src/test/codegen/loads.rs:49:11: error: expected string not found in input
// CHECK: [[VAR:%[0-9]+]] = load i32, i32* %{{.*}}, align 1
          ^
x86_64-unknown-linux-gnu/test/codegen/loads.ll:269:35: note: scanning from here
define i32 @small_struct_alignment(i32) unnamed_addr #0 {
                                  ^
x86_64-unknown-linux-gnu/test/codegen/loads.ll:283:2: note: possible intended match here
 %7 = load i32* %6, align 1
 ^

------------------------------------------

thread '[codegen] codegen/loads.rs' panicked at 'explicit panic', /home/sylvestre/dev/debian/rustc.git/src/compiletest/runtest.rs:1497



failures:
    [codegen] codegen/loads.rs
    [codegen] codegen/stores.rs

test result: FAILED. 2 passed; 2 failed; 0 ignored; 0 measured
```

**Comment by dotdash** [comment]
Hrm, yeah, the IR format changed from 3.6 to 3.7. In this case, it's just the extra result type in the instructions.

Making that optional by changing

    // CHECK: [[VAR:%[0-9]+]] = load [4 x i8]*, [4 x i8]** %x

to something like

    // CHECK: [[VAR:%[0-9]+]] = load {{(\[4 x i8\]*, )?}}[4 x i8]** %x

should help with that. If you still have a build using LLVM 3.6 around, it'd be great if you could create a patch for this. If not, let me know and I'll create one this evening.

**Comment by sylvestre** [comment]
I will give it a try. 
I am not planning to switch to 3.7 right now as there is no official release yet.

**Comment by sanxiyn** [comment]
This is fixed.
