### ISSUE TITLE
Weird error in trait with HRTB for the same trait on `Self` in a method. Also bad diagnostic with nonsensical suggestion.

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#84435]
Given the following code: 

```rust
trait Trait<'a>: Sized {
    fn method(self)
    where
        for<'b> Self: Trait<'b>;
}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=87e8a1b1bd0f1588a08cdd7e0fe7face))

The current output is:

```rust
   Compiling playground v0.0.1 (/playground)
error[E0283]: type annotations needed
 --> src/lib.rs:1:1
  |
1 | trait Trait<'a>: Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
  | |
  | cannot infer type for type parameter `Self`
  | required by this bound in `Trait`
  |
  = note: cannot satisfy `Self: Trait<'a>`
help: consider specifying the type arguments in the function call
  |
1 | trait Trait<'a>: Sized::<Self, 'a> {
  |                       ^^^^^^^^^^^^

error: aborting due to previous error
```

I would’ve expected this code to compile. Even if there is a reason why it shouldn’t compile, the error message is about the most confusing/nonsensical error message I’ve ever seen. The “best” part is how it suggests adding arguments to `Sized`.

**Comment by steffahn** [comment]
This code used to compile fine in rust `1.0` through `1.3`, it used to ICE from `1.4` to `1.6` and it gives some kind of ``cannot resolve `Self : Trait<'a>`​`` / `E0283` error ever since `1.7`.

**Comment by SNCPlay42** [comment]
This looks similar to #84398, but that one's a recent regression.

**Comment by steffahn** [comment]
In `1.3`-`1.4` the ICE appears at `nightly-2015-08-15`.

```
> rustc +nightly-2015-08-14 --version
rustc 1.4.0-nightly (e2bebf32f 2015-08-14)
> rustc +nightly-2015-08-15 --version
rustc 1.4.0-nightly (ab450ef22 2015-08-14)
```

In `1.6`-`1.7` the ICE disappears and the error message appears at `nightly-2015-12-19`.

```
> rustc +nightly-2015-12-14 --version
rustc 1.7.0-nightly (110df043b 2015-12-13)
> rustc +nightly-2015-12-19 --version
rustc 1.7.0-nightly (8ad12c3e2 2015-12-19)
```

**Comment by ChayimFriedman2** [comment]
Another case of this bug (https://users.rust-lang.org/t/strange-type-annotations-needed-error/74117?u=chrefr):
```rust
trait Trait<'a> {}
trait Foo<'a>: Trait<'a> + for<'b> Trait<'b> {}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=94818406f96dfe5f1a086ccd01cf35a7
```
error[E0283]: type annotations needed
 --> src/lib.rs:2:16
  |
2 | trait Foo<'a>: Trait<'a> + for<'b> Trait<'b> {}
  |                ^^^^^^^^^ cannot infer type for type parameter `Self`
  |
  = note: cannot satisfy `Self: Trait<'a>`
```

**Comment by estebank** [comment]
Current output:

```
error[[E0283]](https://doc.rust-lang.org/stable/error_codes/E0283.html): type annotations needed: cannot satisfy `Self: Trait<'a>`
  |
note: multiple `impl`s or `where` clauses satisfying `Self: Trait<'a>` found
 --> src/lib.rs:1:1
  |
1 | trait Trait<'a>: Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
...
4 |         for<'b> Self: Trait<'b>;
  |                       ^^^^^^^^^
```
```
error[[E0283]](https://doc.rust-lang.org/stable/error_codes/E0283.html): type annotations needed: cannot satisfy `Self: Trait<'a>`
 --> src/lib.rs:2:16
  |
2 | trait Foo<'a>: Trait<'a> + for<'b> Trait<'b> {}
  |                ^^^^^^^^^
  |
note: multiple `impl`s or `where` clauses satisfying `Self: Trait<'a>` found
 --> src/lib.rs:2:16
  |
2 | trait Foo<'a>: Trait<'a> + for<'b> Trait<'b> {}
  |                ^^^^^^^^^   ^^^^^^^^^^^^^^^^^
```
