### ISSUE TITLE
Incorrect suggestion for function parameter of type `str`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#82820]
```rust
fn foo(bar: str) {}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=90215e0938244705618389b711881e3a))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> src/lib.rs:1:8
  |
1 | fn foo(bar: str) {}
  |        ^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `str`
help: function arguments must have a statically known size, borrowed types always have a known size
  |
1 | fn foo(&bar: str) {}
  |        ^

error: aborting due to previous error
```

-----

Applying the suggestion leads to yet more errors. The new errors *do* suggest using `&str`, but they still suggest invalid code:

```
error[E0308]: mismatched types
 --> src/lib.rs:1:8
  |
1 | fn foo(&bar: str) {}
  |        ^^^^-----
  |        |     |
  |        |     expected due to this
  |        expected `str`, found reference
  |        help: did you mean `bar`: `&str`
  |
  = note:   expected type `str`
          found reference `&_`

error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> src/lib.rs:1:8
  |
1 | fn foo(&bar: str) {}
  |        ^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `str`
help: function arguments must have a statically known size, borrowed types always have a known size
  |
1 | fn foo(&bar: &str) {}
  |              ^

error: aborting due to 2 previous errors
```

After applying the *new* suggestions, I get:

```
error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> src/lib.rs:1:9
  |
1 | fn foo(&bar: &str) {}
  |         ^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `str`
  = note: all local variables must have a statically known size
  = help: unsized locals are gated as an unstable feature

error: aborting due to previous error
```

This seems likely to send new users in circles.

**Comment by camelid** [comment]
Assigning `P-medium` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2382820.20Incorrect.20suggestion.20for.20function.20parameter.20of.20type.20.E2.80.A6) in the prioritization working group.

**Comment by apiraino** [comment]
I've bisected to this nightly range:

+nightly-2020-07-12-x86_64-unknown-linux-gnu `346aec9b0` => old error msg
+nightly-2020-07-26-x86_64-unknown-linux-gnu `d6953df14` => new error message

(I cannot bisect further because in between of that range I cannot install nightlies :man_shrugging: )

**Comment by hellow554** [comment]
Funny enough, when using `_` as variable name, the suggestion will get displayed correctly:

```
fn f(a: str) {}
fn g(_: str) {}
```

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> src/lib.rs:1:6
  |
1 | fn f(a: str) {}
  |      ^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `str`
help: function arguments must have a statically known size, borrowed types always have a known size
  |
1 | fn f(&a: str) {}
  |      ^

error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> src/lib.rs:2:6
  |
2 | fn g(_: str) {}
  |      ^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `str`
help: function arguments must have a statically known size, borrowed types always have a known size
  |
2 | fn g(_: &str) {}
```

**Comment by hellow554** [comment]
This seems to be fixed on nighlty, but not on beta... Let me try to find it

**Comment by hellow554** [comment]
But, as a sidenote: How could this ever be commited to master? I mean, it's obviosly wrong so say `&a: str` :/

I hope, that in the future the review process can be improved to detect such errors early on.

**Comment by camelid** [comment]
> The error was introduced in #78152, where the test has been adapted to match the wrong syntax, but nobody has seen this :( Let's hope in the future it will get noticed right away 😊

It looks like that PR caused a bunch of small diagnostics changes, so the reviewers probably just missed that bug.

**Comment by camelid** [comment]
Assigning myself for adding a test. @rustbot claim
