### PR TITLE
Handle nonnull pattern types in size skeleton

### LINKED ISSUE #155330: Regression: transmuting between raw pointer and Option<NonNull> no longer works
### Code

I tried this code:

```rust
use std::ptr::NonNull;
pub const fn is_null<'a, T: ?Sized>(ptr: *const T) -> bool {
    unsafe {
        matches!(
            core::mem::transmute::<*const T, Option<NonNull<T>>>(ptr),
            None
        )
    }
}
```

I expected to see this happen: Code compiles

Instead, this happened:

```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
 --> src/lib.rs:5:13
  |
5 |             core::mem::transmute::<*const T, Option<NonNull<T>>>(ptr),
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: source type: `*const T` (pointer to `T`)
  = note: target type: `Option<NonNull<T>>` (size can vary because of <T as Pointee>::Metadata)

For more information about this error, try `rustc --explain E0512`.
```

* * *

Bisected to 338dff3e3a375cb4a3c68be825058c582262655a #136006

### PR DESCRIPTION
**Pull request by oli-obk**
The original comment was correct, the size is always the same, but we have more information now. In theory there was an additional bug that would have allowed transmuting things of different sizes, but I don't see how that would have been actually doable as the `tail` types would always have differed.

fixes rust-lang/rust#155330

### CODE REVIEW

**Review by mati865 — APPROVED** [review]
@bors r+ rollup

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155340/57cb10ae1e27f54f72eb2968f6ddc8fe88b83ab5..8d642647bd32c4f1566086e19ac7192484d9b2eb)*
