### ISSUE TITLE
Failing to build dependency (criterion) in Rust 1.52.1 when it works on 1.52.0

### ISSUE THREAD

**Issue by Nateckert** [rust-lang/rust#85330]
Hi,

As I was working on my crate https://github.com/Nateckert/newton_rootfinder/tree/bug_criterion, I wasn't able to run `cargo test` in version 1.52.1 of Rust.

This issue is reproducible on commit `5b3ffab748584efc327294842f58fceb97dead1c` on branch `bug_criterion`

It seems to be platform dependant

### Code
 
I tried this code:

```bash
rustup default 1.52.0
cargo test
```

The previous code runs fine

```bash
rustup default 1.52.1
cargo test
```

I expected to see the tests to run smoothly, however, I got:

```
Compiling newton_rootfinder v0.6.0 (/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder)
   Compiling criterion v0.3.4
dyld: lazy symbol binding failed: Symbol not found: __ZN4core3ptr5write17he134e1ef58ed9196E
  Referenced from: /Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libserde_derive-59fc6572c32d11d8.dylib
  Expected in: flat namespace

dyld: Symbol not found: __ZN4core3ptr5write17he134e1ef58ed9196E
  Referenced from: /Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libserde_derive-59fc6572c32d11d8.dylib
  Expected in: flat namespace

error: could not compile `criterion`

Caused by:
  process didn't exit successfully: `rustc --crate-name criterion --edition=2018 /Users/nathaneckert/.cargo/registry/src/github.com-1ecc6299db9ec823/criterion-0.3.4/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="cargo_bench_support"' --cfg 'feature="default"' -C metadata=bf7612fd7d202f66 -C extra-filename=-bf7612fd7d202f66 --out-dir /Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps -L dependency=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps --extern atty=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libatty-8778e74db0e26e75.rmeta --extern cast=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libcast-97cec559d460f34a.rmeta --extern clap=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libclap-ff9cb72b97fca80d.rmeta --extern criterion_plot=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libcriterion_plot-877d62c5a199b748.rmeta --extern csv=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libcsv-3d49e045cc2a2771.rmeta --extern itertools=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libitertools-4a8bbcd802399ef8.rmeta --extern lazy_static=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/liblazy_static-636833fdad2098d0.rmeta --extern num_traits=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libnum_traits-96b13ddb5e8eb4b9.rmeta --extern oorandom=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/liboorandom-47a36f1104e83ba5.rmeta --extern plotters=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libplotters-677343b9e18988c5.rmeta --extern rayon=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/librayon-f2840e842c2bd86f.rmeta --extern regex=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libregex-7e1bc1bd52c2c5c2.rmeta --extern serde=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libserde-89ac4ad46923bafd.rmeta --extern serde_cbor=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libserde_cbor-2d829d9822cd06f8.rmeta --extern serde_derive=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libserde_derive-59fc6572c32d11d8.dylib --extern serde_json=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libserde_json-f7ac127dbc6f49cd.rmeta --extern tinytemplate=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libtinytemplate-9739375ae0e10512.rmeta --extern walkdir=/Users/nathaneckert/Desktop/Informatique/Code/Rust/newton_rootfinder/target/debug/deps/libwalkdir-13934b6c78fa5700.rmeta --cap-lints allow -C link-arg=-undefined -C link-arg=dynamic_lookup` (signal: 6, SIGABRT: process abort signal)
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### Version it worked on

It most recently worked on: Rust 1.52.0
It also works on `rustc 1.54.0-nightly (5c0292654 2021-05-11)`

### Version with regression

`rustc --version --verbose`:
```
rustc 1.52.1 (9bc8c42bb 2021-05-09)
binary: rustc
commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
commit-date: 2021-05-09
host: x86_64-apple-darwin
release: 1.52.1
LLVM version: 12.0.0
```

### Additional infos

The tests run without problem on Travis-CI (https://www.travis-ci.com/github/Nateckert/newton_rootfinder/jobs/505652512), on which I test only Linux, while my machine is a MacBook Pro from 2012, running macOS Catalina 10.15.7

Running the command `cargo build` works fine. However, the crate `criterion` is only a dev dependency.

I also tested `rustc 1.54.0-nightly (5c0292654 2021-05-11)` and the bug does not occur there. I get the expected output.

Best regards and thanks a lot for all the work !

**Comment by ehuss** [comment]
Sorry you're having that trouble. Unfortunately, I wasn't able to reproduce the issue.  I noticed in the error message that it includes the following flags:

`-C link-arg=-undefined -C link-arg=dynamic_lookup`

Those aren't normally used by rustc or cargo.  Do you perhaps have RUSTFLAGS set?  Or maybe something in cargo config files?  With nightly cargo, you can run `cargo config get -Z unstable-options` to check if there are any config settings.

You may also want to report the xcode version installed with `xcodebuild -version` and `cc --version`

**Comment by Nateckert** [comment]
`xcodebuild -version` returns 

```
Xcode 12.4
Build version 12D4e
```

`cc --version` returns :

```
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I don't think I am using RUSTFLAGS, just basic cargo mecanisms.

Also, I uninstalled rustup (`rustup self uninstall`) and reinstalled it and it is working properly.

I am not stuck with this issue anymore, but I would be happy to answer any follow-up questions if it could help others.

Thanks a lot

**Comment by apiraino** [comment]
@Nateckert Does it reproduce if you run a `cargo clean` after switching toolchain to 1.52.1 and before running `cargo test` again?

**Comment by Nateckert** [comment]
Unfortunately (or fortunately according to the point of view), as I reinstalled the toolchain, I do not encounter that issue anymore and I cannot test if `cargo clean` has any effect.

**Comment by apiraino** [comment]
@Nateckert I'm happy that you solved, so I'll tentatively close this issue. But don't hesitate to reopen this one (or a new one) if you encounter again this problem

@rustbot label -I-prioritize -E-needs-mcve -regression-untriaged
