### PR TITLE
Make `Unique::as_ptr`, `NonNull::dangling` and `NonNull::cast` const

### PR DESCRIPTION
**Pull request by TimDiekmann**

### CODE REVIEW

**Comment by oli-obk** [comment]
Please add some tests using these in a const context. Also consider making them `rustc_const_unstable` so the constness isn't insta-stable

**Comment by TimDiekmann** [comment]
Should `rustc_const_unstable` also apply on `Unique` as it's not `pub`?

r? @oli-obk

**Comment by oli-obk** [comment]
Since it's unstable, there's no need

File: src/libcore/ptr.rs [hunk 1]
```diff
@@ -2903,7 +2914,9 @@ impl<T: Sized> NonNull<T> {
     /// some other means.
     #[stable(feature = "nonnull", since = "1.25.0")]
     #[inline]
-    pub fn dangling() -> Self {
+    #[cfg(not(stage0))]
+    #[rustc_const_unstable(feature = "const_ptr_nonnull")]
```
Comment (oli-obk) [inline src/libcore/ptr.rs]: you can use `#[cfg_attr(not(stage0), rustc_const_unstable(feature = "const_ptr_nonnull"))]` in order to not need two items.

Comment (TimDiekmann) [reply src/libcore/ptr.rs]: Good point, will do it!

File: src/test/run-pass/consts/const-ptr-nonnull.rs [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+
+const fn cast<T, U>(non_null: NonNull<T>) -> NonNull<U> {
+    non_null.cast()
+}
+
+pub fn main() {
+    assert_eq!(dangling(), NonNull::dangling());
+
+    let mut i: i32 = 10;
+    let non_null_t = NonNull::new(&mut i).unwrap();
```
Comment (oli-obk) [inline src/test/run-pass/consts/const-ptr-nonnull.rs]: While the above functions are `const`, the evaluation doesn't happen via const eval. In order to trigger const eval, you're going to need an explicit `const FOO` item somewhere.

Comment (TimDiekmann) [reply src/test/run-pass/consts/const-ptr-nonnull.rs]: Should be fixed now

File: src/libcore/ptr.rs [hunk 3]
```diff
@@ -2790,7 +2790,7 @@ impl<T: ?Sized> Unique<T> {
     }
 
     /// Acquires the underlying `*mut` pointer.
-    pub fn as_ptr(self) -> *mut T {
+    pub const fn as_ptr(self) -> *mut T {
```
Comment (oli-obk) [inline src/libcore/ptr.rs]: cc @Centril is it too dangerous that just adding a `const` doesn't require anything like a `#[const_stable(since = "1.2.3")]` attribute?

File: src/test/run-pass/consts/const-ptr-nonnull.rs (hunk 2 above)
Comment (oli-obk) [reply src/test/run-pass/consts/const-ptr-nonnull.rs]: thanks!

File: src/libcore/ptr.rs (hunk 3 above)
Comment (Centril) [reply src/libcore/ptr.rs]: Dangerous from what perspective? If it's used in a min-const-fn it will also need to be min-const-fn... or do you mean from the POV of accidental stabilization?

Comment (oli-obk) [reply src/libcore/ptr.rs]: yes, accidental stabilization. Like making something stable that is already `const fn` stabilizes the constness along with it.

Comment (TimDiekmann) [reply src/libcore/ptr.rs]: Do you mean any stabilized const fn should have something like a `#[const_stable]` attribute?

Comment (Centril) [reply src/libcore/ptr.rs]: Ah... idk if I find it risky rising to the level of dangerous but there's some risk, no doubt. @varkor wanted it from a different perspective (https://github.com/rust-lang/rust/issues/57562#issuecomment-453794072) but I thought it too much of an annotation burden. However, from the POV of accidental stabilization, `#[const_stable(...)]` makes sense to me.

Can you open up an issue and cc me and varkor?

Comment (Centril) [reply src/libcore/ptr.rs]: @TimDiekmann Yeah, that's the idea.

**Comment by Centril** [comment]
Failed in https://github.com/rust-lang/rust/pull/58766#issuecomment-467760824, @bors r-

**Comment by TimDiekmann** [comment]
Whoops, that was by accident. I blame my mobile phone...

**Comment by oli-obk** [comment]
@bors r+

not sure if bors handles reopening PRs

**Comment by kennytm** [comment]
@bors r-

This PR failed in https://github.com/rust-lang/rust/pull/58866#issuecomment-468919773.

The new UI tests `ui/consts/const-ptr-{nonnull,unique}.rs` have different error messages in NLL comparison mode, e.g.

```diff
-	error[E0597]: borrowed value does not live long enough
+	error[E0716]: temporary value dropped while borrowed
2	  --> $DIR/const-ptr-nonnull.rs:4:37
3	   |
4	LL |     let x: &'static NonNull<u32> = &(NonNull::dangling());

-	   |                                     ^^^^^^^^^^^^^^^^^^^^^ temporary value does not live long enough
+	   |            ---------------------    ^^^^^^^^^^^^^^^^^^^^^ creates a temporary which is freed while still in use
+	   |            |
+	   |            type annotation requires that borrow lasts for `'static`
6	...
7	LL | }
-	   | - temporary value only lives until here
-	   |
-	   = note: borrowed value must be valid for the static lifetime...
+	   | - temporary value is freed at the end of this statement
11	
-	error[E0597]: borrowed value does not live long enough
+	error[E0716]: temporary value dropped while borrowed
13	  --> $DIR/const-ptr-nonnull.rs:9:37
14	   |
15	LL |     let x: &'static NonNull<u32> = &(non_null.cast());

-	   |                                     ^^^^^^^^^^^^^^^^^ temporary value does not live long enough
+	   |            ---------------------    ^^^^^^^^^^^^^^^^^ creates a temporary which is freed while still in use
+	   |            |
+	   |            type annotation requires that borrow lasts for `'static`
17	LL |     //~^ ERROR borrowed value does not live long enough
18	LL | }
-	   | - temporary value only lives until here
-	   |
-	   = note: borrowed value must be valid for the static lifetime...
+	   | - temporary value is freed at the end of this statement
22	
23	error: aborting due to 2 previous errors
24	

-	For more information about this error, try `rustc --explain E0597`.
+	For more information about this error, try `rustc --explain E0716`.
26	
```

**Comment by TimDiekmann** [comment]
How do I run the NLL test? It seems not to run with `./x.py test - - stage 1`

**Comment by Centril** [comment]
@TimDiekmann Add `--compare-mode=nll`.

**Comment by TimDiekmann** [comment]
Thanks @Centril, it worked

**Comment by oli-obk** [comment]
I love the new diagnostics!

**Comment by TimDiekmann** [comment]
Yes, indeed, very helpful!

**Comment by TimDiekmann** [comment]
Seems like a spurious failure as mentioned in https://github.com/rust-lang/rust/issues/58160.

**Comment by TimDiekmann** [comment]
> Command exited with code 259

Another one...
