### ISSUE TITLE
Badly worded note for non-constant array length

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#41871]
```rust
let len = 42;
let arr = [0; len];
```

rustc 1.0.0 - 1.11.0: `error: expected constant integer for repeat count, found variable`
rustc 1.12.0 - 1.15.0: `non-constant path in constant expression`
rustc 1.16.0 - present: `non-constant used with constant`

Can we have the first one back please?

**Comment by cbreeden** [comment]
To clarify, the problem is in the note:

```
rustc 1.17.0 (56124baa9 2017-04-24)
error[E0435]: attempt to use a non-constant value in a constant
 --> <anon>:3:19
  |
3 |     let arr = [0; len];
  |                   ^^^ non-constant used with constant

error: aborting due to previous error
```

**Comment by kennytm** [comment]
Message introduced in #35858, using the exact wording from #35801.

I think the note should be reworded to "non-constant used **as** constant".

**Comment by Mark-Simulacrum** [comment]
The error message today speaks the truth and does so quite well. Closing.

```
error[E0435]: attempt to use a non-constant value in a constant
 --> test.rs:3:19
  |
3 |     let arr = [0; len];
  |                   ^^^ non-constant used with constant

error: aborting due to previous error(s)
```

**Comment by durka** [comment]
The span label is still pretty nonsensical.

**Comment by Mark-Simulacrum** [comment]
Okay, I'll reopen. Can you provide the exact wording you'd expect? (I personally don't really see any point for a span label, but ... ).

**Comment by durka** [comment]
Either remove the label or just "non-constant value" seems to make more sense to me. It's the "with constant" that is weird IMO.

**Comment by durka** [comment]
I'll PR.

**Comment by JeffCarpenter** [comment]
I just came here after googling `attempt to use a non-constant value in a constant: non-constant value` and want to say that the first error message is a lot easier to understand!
