### PR TITLE
combine: stop eagerly evaluating consts

### PR DESCRIPTION
**Pull request by lcnr**
`super_relate_consts` eagerly evaluates constants which doesn't seem too great.

I now also finally understand why all of the unused substs test passed. The reason being
that we just evaluated the constants in `super_relate_consts` :laughing:

While this change isn't strictly necessary as evaluating consts here doesn't hurt, it still feels a lot cleaner to do it this way

r? @oli-obk @nikomatsakis

### CODE REVIEW

**Comment by oli-obk** [comment]
Oh yea, this is much better than the `visit_ct_substs` thing

@bors r+

**Comment by lcnr** [comment]
```
 error[E0283]: type annotations needed
   --> src/cargo/util/config/de.rs:530:63
    |
530 |                 seed.deserialize(Tuple2Deserializer(1i32, env.as_ref()))
    |                                                           ----^^^^^^--
    |                                                           |   |
    |                                                           |   cannot infer type for type parameter `T` declared on the trait `AsRef`
    |                                                           this method call resolves to `&T`
    |
    = note: cannot satisfy `std::string::String: AsRef<_>`
help: use the fully qualified path for the potential candidates
    |
530 |                 seed.deserialize(Tuple2Deserializer(1i32, <std::string::String as AsRef<OsStr>>::as_ref(env)))
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
530 |                 seed.deserialize(Tuple2Deserializer(1i32, <std::string::String as AsRef<std::path::Path>>::as_ref(env)))
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
530 |                 seed.deserialize(Tuple2Deserializer(1i32, <std::string::String as AsRef<str>>::as_ref(env)))
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
530 |                 seed.deserialize(Tuple2Deserializer(1i32, <std::string::String as AsRef<[u8]>>::as_ref(env)))
    |       
```
fun, let me check why this happens

**Comment by oli-obk** [comment]
not your fault, a lot of (all) PRs are failing right now

**Comment by lcnr** [comment]
@bors retry

this should work again now

**Comment by Aaron1011** [comment]
Failed due to https://github.com/rust-lang/rust/pull/81351 adding a new error to a test. I'll rebase this PR once that PR lands in the current rollup.

**Comment by camelid** [comment]
For easy reference, this is the log output from the failed rollup:

```
failures:

---- [ui] ui/const-generics/issues/issue-69654.rs stdout ----
diff of stderr:

4	LL | impl<T> Bar<T> for [u8; T] {}
5	   |                         ^ not a value
Some tests failed in compiletest suite=ui mode=ui host=x86_64-unknown-linux-gnu target=x86_64-unknown-linux-gnu
6	
-	error[E0599]: no function or associated item named `foo` found for struct `Foo<{_: usize}>` in the current scope
+	error[E0599]: the function or associated item `foo` exists for struct `Foo<{_: usize}>`, but its trait bounds were not satisfied
8	  --> $DIR/issue-69654.rs:17:10
9	   |
10	LL | struct Foo<const N: usize> {}

11	   | -------------------------- function or associated item `foo` not found for this
12	...
13	LL |     Foo::foo();
-	   |          ^^^ function or associated item not found in `Foo<{_: usize}>`
+	   |          ^^^ function or associated item cannot be called on `Foo<{_: usize}>` due to unsatisfied trait bounds
15	   |
-	   = note: the method `foo` exists but the following trait bounds were not satisfied:
+	   = note: the following trait bounds were not satisfied:
17	           `[u8; _]: Bar<[(); _]>`
18	
19	error: aborting due to 2 previous errors


The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/const-generics/issues/issue-69654/issue-69654.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args const-generics/issues/issue-69654.rs`

error: 1 errors occurred comparing output.
status: exit code: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/const-generics/issues/issue-69654.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/const-generics/issues/issue-69654" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/const-generics/issues/issue-69654/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error[E0423]: expected value, found type parameter `T`
  --> /checkout/src/test/ui/const-generics/issues/issue-69654.rs:5:25
   |
LL | impl<T> Bar<T> for [u8; T] {}
   |                         ^ not a value

error[E0599]: the function or associated item `foo` exists for struct `Foo<{_: usize}>`, but its trait bounds were not satisfied
  --> /checkout/src/test/ui/const-generics/issues/issue-69654.rs:17:10
   |
LL | struct Foo<const N: usize> {}
   | -------------------------- function or associated item `foo` not found for this
...
LL |     Foo::foo();
   |          ^^^ function or associated item cannot be called on `Foo<{_: usize}>` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `[u8; _]: Bar<[(); _]>`

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0423, E0599.
For more information about an error, try `rustc --explain E0423`.

------------------------------------------


---- [ui] ui/const-generics/issues/issue-69654-run-pass.rs stdout ----
diff of stderr:

-	error[E0599]: no function or associated item named `foo` found for struct `Foo<{_: usize}>` in the current scope
+	error[E0599]: the function or associated item `foo` exists for struct `Foo<{_: usize}>`, but its trait bounds were not satisfied
2	  --> $DIR/issue-69654-run-pass.rs:16:10
3	   |
4	LL | struct Foo<const N: usize> {}

5	   | -------------------------- function or associated item `foo` not found for this
6	...
7	LL |     Foo::foo();
-	   |          ^^^ function or associated item not found in `Foo<{_: usize}>`
+	   |          ^^^ function or associated item cannot be called on `Foo<{_: usize}>` due to unsatisfied trait bounds
9	   |
-	   = note: the method `foo` exists but the following trait bounds were not satisfied:
+	   = note: the following trait bounds were not satisfied:
11	           `[u8; _]: Bar<[(); _]>`
12	
13	error: aborting due to previous error


The actual stderr differed from the expected stderr.
Actual stderr saved to /checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/const-generics/issues/issue-69654-run-pass/issue-69654-run-pass.stderr
To update references, rerun the tests and pass the `--bless` flag
To only update this specific test, also pass `--test-args const-generics/issues/issue-69654-run-pass.rs`

error: 1 errors occurred comparing output.
status: exit code: 1
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/ui/const-generics/issues/issue-69654-run-pass.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "--error-format" "json" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Zemit-future-incompat-report" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/const-generics/issues/issue-69654-run-pass" "-A" "unused" "-Crpath" "-O" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/const-generics/issues/issue-69654-run-pass/auxiliary"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error[E0599]: the function or associated item `foo` exists for struct `Foo<{_: usize}>`, but its trait bounds were not satisfied
  --> /checkout/src/test/ui/const-generics/issues/issue-69654-run-pass.rs:16:10
   |
LL | struct Foo<const N: usize> {}
   | -------------------------- function or associated item `foo` not found for this
...
LL |     Foo::foo();
   |          ^^^ function or associated item cannot be called on `Foo<{_: usize}>` due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           `[u8; _]: Bar<[(); _]>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.

------------------------------------------



failures:
    [ui] ui/const-generics/issues/issue-69654-run-pass.rs
    [ui] ui/const-generics/issues/issue-69654.rs

test result: FAILED. 11239 passed; 2 failed; 88 ignored; 0 measured; 0 filtered out; finished in 115.27s
```

**Comment by lcnr** [comment]
should be ready for merge again

**Comment by lcnr** [comment]
is that one spurious? It looks like it to me

**Comment by camelid** [comment]
Hmm, maybe Apple builder timed out?
