### PR TITLE
Add a few known-bug tests

### PR DESCRIPTION
**Pull request by jackh726**
The labels of these tests should be changed from `S-bug-has-mcve` to `S-bug-has-test` once this is merged.

cc:
- #89196
- #90950
- #99492
- #101350
- #101518
- #103705
- #103899
- #104034

I couldn't reproduce the failures in #101962 and #100772 (so either these have started passing, or I didn't repro properly), so leaving those out for now.

#102065 was a bit more complicated, since it uses `rustc_private` and I didn't want to mess with that.

### CODE REVIEW

File: src/test/ui/issues/issue-102065.rs [hunk 1]
```diff
@@ -0,0 +1,13 @@
+// check-fail
```
Comment (jackh726) [inline src/test/ui/issues/issue-102065.rs:1]: I couldn't really find a better place for this :/

File: src/test/ui/issues/issue-102065.stderr [hunk 2]
```diff
@@ -0,0 +1,19 @@
+error[E0463]: can't find crate for `rustc_codegen_llvm`
```
Comment (jackh726) [inline src/test/ui/issues/issue-102065.stderr:1]: Ah wait...

Just gonna remove this one.

**Comment by matthiaskrgr** [comment]
>(so either these have started passing, or I didn't repro properly)

I can still reproduce both of the ICEs with latest nightly :thinking:

**Comment by jackh726** [comment]
> > (so either these have started passing, or I didn't repro properly)
> 
> I can still reproduce both of the ICEs with latest nightly 🤔

Likely I just didn't make the reproductions correctly.

**Comment by jackh726** [comment]
The `known-bug` attribute disables the need for error annotations. They aren't useful so much for searching for tests to fix, but rather to document known issues and help catch fixes or changes from unrelated things.

File: src/test/incremental/issue-101518.rs [hunk 3]
```diff
@@ -0,0 +1,31 @@
+// revisions: cfail1 cfail2
```
Comment (Mark-Simulacrum) [inline src/test/incremental/issue-101518.rs:1]: It seems like these aren't actually used?

**Review by Mark-Simulacrum — COMMENTED** [review]
r=me with either revisions removed or an explanation

File: src/test/incremental/issue-101518.rs (hunk 3 above)
Comment (jackh726) [reply src/test/incremental/issue-101518.rs]: Incremental test seem to require revisions. But I suppose we only need one.
