### PR TITLE
Migrate libraries from ptr::slice_from_raw_parts to .cast_slice

### PR DESCRIPTION
**Pull request by Paladynee**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/156109)*

Tracking issue for `#![feature(ptr_cast_slice)]`: rust-lang/rust#149103 
This commit updates most callsites of ptr::slice_from_raw_parts within ./library to the more concise but unstable postfix `.cast_slice()` method on raw pointers, using the `ptr_cast_slice` feature. Some tests in alloctests have also been updated.

No functional change, debatably improved readability.

### CODE REVIEW

**Comment by Paladynee** [comment]
some notable places like core::slice::from_raw_parts have not been updated, because i felt like changing that would harm readability than improving it.

**Comment by Paladynee** [comment]
hmm wait let me revert that doc change, apparently it is exactly the same in `std::ptr::slice_from_raw_parts`. this is all so confusing since all the names are super similar lol

**Comment by xtqqczze** [comment]
Could `&*ptr::slice_from_raw_parts` be written as `slice::from_raw_parts`?

**Comment by jhpratt** [comment]
> `stdarch` is developed in its own repository. If possible, consider making this change to [rust-lang/stdarch](https://github.com/rust-lang/stdarch?rgh-link-date=2026-05-03T12%3A41%3A16Z) instead.

Aside from this, `r=me`

**Comment by Paladynee** [comment]
> Could `&*ptr::slice_from_raw_parts` be written as `slice::from_raw_parts`?

i believe they are equivalent other than the debug UB assertion, yes

**Comment by Paladynee** [comment]
I'm not touching anything in;
- coretests
- core::slice
- any `ptr::slice_from_raw_parts{_mut}` call in stable documentations
- believe i can revert the stdarch thing since it seems too complicated for me to change for now

with that, i think this pr is ready

@rustbot ready

**Comment by xtqqczze** [comment]
> Could `&*ptr::slice_from_raw_parts` be written as `slice::from_raw_parts`?

The `library/core/src/slice/sort/shared/smallsort.rs` changes should be reverted as they conflict with https://github.com/rust-lang/rust/pull/156192.

**Comment by Paladynee** [comment]
> > Could `&*ptr::slice_from_raw_parts` be written as `slice::from_raw_parts`?
> 
> The `library/core/src/slice/sort/shared/smallsort.rs` changes should be reverted as they conflict with #156192.

done

**Comment by jhpratt** [comment]
@bors r-

https://github.com/rust-lang/rust/pull/156263#issuecomment-4394204563

File: library/std/src/sys/pal/sgx/abi/usercalls/alloc.rs [hunk 1]
```diff
@@ -151,7 +151,7 @@ unsafe impl<T: UserSafeSized> UserSafe for [T] {
         let elem_size = size_of::<T>();
         assert_eq!(size % elem_size, 0);
         let len = size / elem_size;
-        ptr::slice_from_raw_parts_mut(ptr as _, len)
+        (ptr as _).cast_slice(len)
```
Comment (xtqqczze) [inline library/std/src/sys/pal/sgx/abi/usercalls/alloc.rs]:
```log
  error[E0282]: type annotations needed
     --> /rustc/620725bffcba2613fa6243f559657c2bedb5615f/library/std/src/sys/pal/sgx/abi/usercalls/alloc.rs:154:9
      |
  154 |         (ptr as _).cast_slice(len)
      |         ^^^^^^^^^^ cannot infer type
```

https://github.com/rust-lang/rust/actions/runs/25475505562/job/74748095499#step:28:10939

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/156109/e95e73209faf6ead2bc5c7636e45e589a751b79b..14315f9793cd60268a25f5359728a49751ce035e)*

Comment (Paladynee) [reply library/std/src/sys/pal/sgx/abi/usercalls/alloc.rs]: should be fixed now

**Comment by xtqqczze** [comment]
Apparently this file requires changes:

https://github.com/rust-lang/rust/blob/3e353d7353b0cd6fa4eefd5c882457cc2708184c/tests/mir-opt/inline/inline_shims.drop.Inline.panic-abort.diff#L39-L42

**Comment by Paladynee** [comment]
i ran all tests with --bless and the only change was that file, pushed the changes

**Comment by Paladynee** [comment]
any updates? @jhpratt

**Comment by jhpratt** [comment]
Sorry, I was travelling Europe for the past couple weeks :)

@bors r+
