### ISSUE TITLE
Incorrect generic parameter parsing when using const type_name.

### ISSUE THREAD

**Issue by w41ter** [rust-lang/rust#101884]
I tried this code:

```rust
#![feature(const_type_name)]

use std::future::Future;

const fn do_something_depends_on_name<F: Future>() -> &'static str {
    std::any::type_name::<F>()
}

// error[E0401]: can't use generic parameters from outer function
const fn do_something_depends_on_name_1<F: Future>() -> &'static str {
    const type_name: &str = std::any::type_name::<F>();   
    type_name
}

fn main() {
    
}

```

I expected to see this happen: both functions should compile and pass.

Instead, this happened: function `do_something_depends_on_name_1` cannot be compiled, and the error message given by the compiler is: 

```
error[[E0401]](https://doc.rust-lang.org/nightly/error-index.html#E0401): can't use generic parameters from outer function
  --> src/main.rs:11:51
   |
10 | const fn do_something_depends_on_name_1<F: Future>() -> &'static str {
   |                                         - type parameter from outer function
11 |     const type_name: &str = std::any::type_name::<F>();   
   |                                                   ^ use of generic parameter from outer function
```

### Meta

Build using the Nightly version: 1.65.0-nightly (2022-09-15 cf9ed0dd5836201843d2). See: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a79a161c558e64a472822605d824e138

**Comment by lukas-code** [comment]
The error is correct. You cannot use the generic arguments of functions on [items](https://doc.rust-lang.org/reference/items.html), including constants, defined in functions. This is because items in functions work exactly like "global" items outside of functions, except they can only be accessed from the function.

```rust
fn generic<T>() {}

fn foo<T>() {
    const _: () = generic::<T>();
}
```
```
Compiling playground v0.0.1 (/playground)
error[[E0401]](https://doc.rust-lang.org/nightly/error-index.html#E0401): can't use generic parameters from outer function
 --> src/lib.rs:4:29
  |
3 | fn foo<T>() {
  |        - type parameter from outer function
4 |     const _: () = generic::<T>();
  |                             ^ use of generic parameter from outer function

For more information about this error, try `rustc --explain E0401`.
error: could not compile `playground` due to previous error
```

In your example you could replace the constant with a `let` binding to [make it compile](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=1ccfa4a0f210f8fdc2951dd2f0dfdea8):
```rust
#![feature(const_type_name)]

use std::future::Future;

const fn do_something_depends_on_name<F: Future>() -> &'static str {
    std::any::type_name::<F>()
}

// error[E0401]: can't use generic parameters from outer function
const fn do_something_depends_on_name_1<F: Future>() -> &'static str {
    let type_name: &str = std::any::type_name::<F>();   
    type_name
}

fn main() {
    
}
```

**Comment by w41ter** [comment]
@lukas-code Oh I see, thanks for your explanation!
