### ISSUE TITLE
1.80.1 requires additional type annotations, thus failing to compile previously working code

### ISSUE THREAD

**Issue by VincentWo** [rust-lang/rust#129193]
### Code

I tried this code:

```rust
struct Error;

fn ret_impl_iter(res: Result<i32, Error>) -> impl Iterator<Item = Result<i32, Error>> {
    std::iter::once(res)
}

fn test() -> Result<Box<[i32]>, Error> {
    let res: Result<_, _> = Ok(1);
    let it = ret_impl_iter(res);
    let col = it
        .map(|res| res.map(Into::into)) 
        .collect::<Result<Box<_>, Error>>()?;

    Ok(col.into())
}
```

I expected to see this happen: Successful Compilation

Instead, this happened: Compilation failed with error:
```
error[E0282]: type annotations needed for `Box<_>`
  --> src/main.rs:14:9
   |
14 |     let col = it
   |         ^^^
...
18 |     Ok(col.into())
   |            ---- type must be known at this point
   |
help: consider giving `col` an explicit type, where the placeholders `_` are specified
   |
14 |     let col: Box<_> = it
   |            ++++++++

error: aborting due to 1 previous error

For more information about this error, try `rustc --explain E0282`
```
Note that I already tried to trim this example, inlining `ret_impl_iter`, removing `.map(|res| res.map(Into::into))` or using `Vec<_>` instead of `Box<_>` all make the error go away for me 

### Version it worked on

It most recently worked on 1.79 and prior releases

### Version with regression

`rustc --version --verbose`:
```
rustc 1.80.1 (3f5fd8dd4 2024-08-06)
```

Note that this is not a purely theoretical example: Trying to compile the time crate v0.3.34 fails with basically this error (which is how I encountered it), but later versions of time compile

**Comment by Urgau** [comment]
See #127343 and [#127343 (comment)](https://github.com/rust-lang/rust/issues/127343#issuecomment-2218261296)

**Comment by VincentWo** [comment]
Sorry, tried looking for an existing issue and did not find anything, thank you for the info.
