### PR TITLE
Make __rust_alloc_error_handler_should_panic a function

### LINKED ISSUE #143253: Linking broken on arm64ec due to __rust_alloc_error_handler_should_panic symbol
Attempting to link any program on the arm64ec target yields

```
error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostARM64\\arm64\\link.exe" "/NOLOGO" "C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\rustcou23Eq\\symbols.o" "<72 object files omitted>" "<sysroot>\\lib\\rustlib\\arm64ec-pc-windows-msvc\\lib/{libtest-*,libgetopts-*,libunicode_width-*,librustc_std_workspace_std-*,libstd-*,libpanic_unwind-*,libwindows_targets-*,librustc_demangle-*,libstd_detect-*,libhashbrown-*,librustc_std_workspace_alloc-*,libunwind-*,libcfg_if-*,librustc_std_workspace_core-*,liballoc-*,libcore-*,libcompiler_builtins-*}.rlib" "kernel32.lib" "kernel32.lib" "kernel32.lib" "kernel32.lib" "ntdll.lib" "userenv.lib" "ws2_32.lib" "dbghelp.lib" "/defaultlib:msvcrt" "/machine:arm64ec" "softintrin.lib" "/NXCOMPAT" "/LIBPATH:C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-1949cf8c6b5b557f\\windows_x86_64_msvc-0.52.6\\lib" "/OUT:C:\\a\\lithium\\lithium\\target\\arm64ec-pc-windows-
  = note: some arguments are omitted. use `--verbose` to show all linker arguments
  = note: symbols.o : error LNK2001: unresolved external symbol #_RNvCse3amHqTQ2bx_7___rustc39___rust_alloc_error_handler_should_panic (EC Symbol)␍
          symbols.o : error LNK2001: unresolved external symbol #_RNvCse3amHqTQ2bx_7___rustc39___rust_alloc_error_handler_should_panic (EC Symbol)␍
          C:\a\lithium\lithium\target\arm64ec-pc-windows-msvc\debug\deps\lithium-21aeb5d0fedc4d6a.exe : fatal error LNK1120: 1 unresolved externals␍
```

I think this was broken by #140809, more specifically 0cdd7f50b06fb363a2e8b0f6d270e0ed14476af8 which started exporting all `#[rustc_std_internal_symbol]` symbols. `__rust_alloc_error_handler_should_panic` is a static, but is erroneously [marked as a function](https://github.com/rust-lang/rust/blob/c65dccabacdfd6c8a7f7439eba13422fdd89b91e/compiler/rustc_codegen_ssa/src/back/symbol_export.rs#L227) and that breaks mangling. I've tried to draft a PR to mark it as `Data`, but I think might encounter the same problems as what eventually lead to #141061 and I'm not qualified to judge that.

cc @dpaoliello

### Versions

My CI has passed on `rustc 1.90.0-nightly (b03b3a7ec 2025-06-26)` and now fails on `rustc 1.90.0-nightly (35f603652 2025-06-29)`. I don't really have access to an ARM64 Windows machine other than that, but this is probably enough info? Here's [the relevant Actions job](https://github.com/iex-rs/lithium/actions/runs/15930906269/job/45072779556).

@rustbot label +A-allocators +A-linkage +O-AArch64 +O-windows-msvc +T-compiler -needs-triage

### PR DESCRIPTION
**Pull request by dpaoliello**
Fixes rust-lang/rust#143253

`__rust_alloc_error_handler_should_panic` is a static but was being exported as a function.

For most targets this doesn't matter, but Arm64EC Windows uses different decorations for exported variables vs functions, hence it fails to link when `-Z oom=abort` is enabled.

We've had issues in the past with statics like this (see rust-lang/rust#141061) but the tldr; is that Arm64EC needs symbols correctly exported as either a function or data, and data MUST and MUST ONLY be marked `dllimport` when the symbol is being imported from another binary, which is non-trivial to calculate for these compiler-generated statics.

So, instead, the easiest thing to do is to make `__rust_alloc_error_handler_should_panic` a function instead.

Since `__rust_alloc_error_handler_should_panic` isn't involved in any linking shenanigans, I've marked it as `AlwaysInline` with the hopes that the various backends will see that it is just returning a constant and perform the same optimizations as the previous implementation.

r? @bjorn3

### CODE REVIEW

**Comment by bjorn3** [comment]
> Since __rust_alloc_error_handler_should_panic isn't involved in any linking shenanigans, I've marked it as AlwaysInline with the hopes that the various backends will see that it is just returning a constant and perform the same optimizations as the previous implementation.

That won't have any effect. It is part of the allocator shim object file, which doesn't participate in LTO unless you use `-Clinker-plugin-lto`. With `-Clinker-plugin-lto` it should in principle always be inlined even without that attribute. Still can't hurt to have it I guess.

File: library/std/src/alloc.rs [hunk 1]
```diff
@@ -349,10 +349,10 @@ fn default_alloc_error_hook(layout: Layout) {
         // This symbol is emitted by rustc next to __rust_alloc_error_handler.
         // Its value depends on the -Zoom={panic,abort} compiler option.
         #[rustc_std_internal_symbol]
-        static __rust_alloc_error_handler_should_panic: u8;
+        fn __rust_alloc_error_handler_should_panic() -> u8;
```
Comment (bjorn3) [inline library/std/src/alloc.rs]: Chromium also defines this symbol, so let's make it a `_v2` too. https://source.chromium.org/chromium/chromium/src/+/main:build/rust/allocator/lib.rs;l=97

File: src/tools/miri/src/shims/extern_static.rs
Comment (RalfJung) [inline src/tools/miri/src/shims/extern_static.rs:1]: As before `alloc-access-tracking` will need to be adjusted (probably be decrementing the ID by 1).

Comment (dpaoliello) [reply src/tools/miri/src/shims/extern_static.rs:1]: Ah, yep, good catch!

**Review by bjorn3 — APPROVED** [review]

**Comment by bjorn3** [comment]
r=me with CI passing

**Comment by tgross35** [comment]
Since this is changing to a new `_v2` name now, why not make it a static rather than a function call?

**Comment by RalfJung** [comment]
IIUC that's very hard to do correctly on arm64ec, and because one fairly niche platform makes this (needlessly?) complicated, we have to use a less optimal solution on all platforms...

(I guess we could switch between function and data variable depending on the target, but that'd mean even more hacks in rustc.)

**Comment by tgross35** [comment]
Ah, that's the `dllimport` comment in the top post? Makes sense. If the situation improves, v3 can be a static 😆
