### ISSUE TITLE
Type inference regression in rustc 1.18

### ISSUE THREAD

**Issue by khuey** [rust-lang/rust#42545]
https://github.com/khuey/rustc-1.18-regression

I'm not sure that this is a *minimal* testcase, but it's small enough to poke around at.  With rustc 1.17 this compiles fine.  With 1.18 I get 

```
error[E0284]: type annotations required: cannot resolve `<_ as futures::IntoFuture>::Future == _`
  --> src/lib.rs:15:18
   |
15 |           Box::new(join_all(vec2.iter()
   |  __________________^
16 | |                           .map(move |_| {
17 | |                               iter::<_, _, ()>(vec1.iter()
18 | |                                                .filter_map(move |_| {
...  |
24 | |                                   })
25 | |                           })))
```

**Comment by frewsxcv** [comment]
For posterity, this is also broken on the latest nightly as well

```
rustc 1.19.0-nightly (f062832b2 2017-06-07)
binary: rustc
commit-hash: f062832b208e94f2f0f26ed7fb5c48c172069fbe
commit-date: 2017-06-07
host: x86_64-apple-darwin
release: 1.19.0-nightly
LLVM version: 4.0
```

**Comment by nikomatsakis** [comment]
triage: P-high -- regression

**Comment by Mark-Simulacrum** [comment]
Bisected to 141e8a6a0203d546b9775ba6ecdc5eb1d748c3d4, #41716 -- cc @nikomatsakis.

**Comment by nikomatsakis** [comment]
Well, I can certainly *reproduce* it =)

**Comment by nikomatsakis** [comment]
This may be a dup of https://github.com/rust-lang/rust/issues/42552

**Comment by nikomatsakis** [comment]
My fix for #42552 also fixes this.

**Comment by khuey** [comment]
Is the fix going to make it into 1.19?  A 1.18.1?

**Comment by Mark-Simulacrum** [comment]
The PR (https://github.com/rust-lang/rust/pull/42659) is beta-nominated, so if it's accepted the fix will be backported and make it into 1.19. However, I doubt we'd release 1.18.1 -- it's possible, though.
