### PR TITLE
Prefer projection candidates instead of param_env candidates for Sized predicates

### LINKED ISSUE #89352: Covariance-related GAT lifetime mismatch
[I tried this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c44f2a8b6b9fe671e97c3956e24f8d02):

```rust
#![feature(generic_associated_types)]

use core::marker::PhantomData;

pub trait GenAssoc<T> {
    type Iter<'a>;
    fn iter(&self) -> Self::Iter<'_>;
    fn reborrow<'long: 'short, 'short>(iter: Self::Iter<'long>) -> Self::Iter<'short>;
}

pub struct Wrapper<'a, T: 'a, A: GenAssoc<T>> {
    a: A::Iter<'a>,
    _p: PhantomData<T>,
}

impl<'a, T: 'a, A: GenAssoc<T>> GenAssoc<T> for Wrapper<'a, T, A>
where
    A::Iter<'a>: Clone,
{
    type Iter<'b> = ();
    fn iter<'s>(&'s self) -> Self::Iter<'s> {
        let a = A::reborrow::<'a, 's>(self.a.clone());
    }

    fn reborrow<'long: 'short, 'short>(iter: Self::Iter<'long>) -> Self::Iter<'short> {
        ()
    }
}
```

I expected to see this happen: Successful compilation.

Instead, this happened: Errors as follows.
```text

error[E0308]: mismatched types
  --> src/lib.rs:23:13
   |
23 |         let a = A::reborrow::<'a, 's>(self.a.clone());
   |             ^ lifetime mismatch
   |
   = note: expected type `Sized`
              found type `Sized`
note: the lifetime `'s` as defined on the method body at 22:13...
  --> src/lib.rs:22:13
   |
22 |     fn iter<'s>(&'s self) -> Self::Iter<'s> {
   |             ^^
note: ...does not necessarily outlive the lifetime `'a` as defined on the impl at 16:6
  --> src/lib.rs:16:6
   |
16 | impl<'a, T: 'a, A: GenAssoc<T>> GenAssoc<T> for Wrapper<'a, T, A>
   |      ^^

For more information about this error, try `rustc --explain E0308`.
```

Note that it expected and found "type `Sized`", which doesn't make sense.  Additionally, I don't see what is restricting `'s` to outlive `'a`; and indeed, [the error can be worked around](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b8cbf041d30c1868ba21336c2a8a1e71).

### Meta
Playground:
```text
Nightly channel
Build using the Nightly version: 1.57.0-nightly
(2021-09-28 8f8092cc32ec171becef)
```

The [original use-case](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=400026cd1b780a9f85cf36ae74de0e90) tied the lifetime parameter of the GAT to the type in typical fashion.  Discovered in [this URLO thread](https://users.rust-lang.org/t/unable-to-make-code-compile-with-generic-associated-lifetimes/65281/).

@rustbot label  +F-generic_associated_types +A-lifetimes +requires-nightly +A-diagnostics

### PR DESCRIPTION
**Pull request by jackh726**
Fixes #89352

Also includes some drive by logging and verbose printing changes that I found useful when debugging this, but I can remove this if needed.

This is a little hacky - but imo no more than the rest of `candidate_should_be_dropped_in_favor_of`. Importantly, in a Chalk-like world, both candidates should be completely compatible.

r? @nikomatsakis

### CODE REVIEW

**Comment by JanBeh** [comment]
Does this also solve https://github.com/rust-lang/rust/issues/92798?

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
I was a bit wary at first, but preferring a projection or dynamic candidate seems actually pretty harmless to me, and quite unlikely to influence inference, so +1.

@bors r+
