### ISSUE TITLE
Cycle in impl Self in associated function

### ISSUE THREAD

**Issue by Arnaz87** [rust-lang/rust#81960]
I tried this code, in the playground:

```rust
struct Foo;
impl Foo {
    fn f () {
        impl Self { }
    }
}
```

In all of the versions, the same thing happened. A compiler error:

```
error[E0391]: cycle detected when computing type of `<impl at src/lib.rs:4:1: 8:2>::f::<impl at src/lib.rs:6:9: 6:22>`
 --> src/lib.rs:6:14
  |
6 |         impl Self { }
  |              ^^^^
  |
  = note: ...which again requires computing type of `<impl at src/lib.rs:4:1: 8:2>::f::<impl at src/lib.rs:6:9: 6:22>`, completing the cycle
note: cycle used when collecting item types in top-level module
 --> src/lib.rs:2:1
  |
2 | / struct Foo;
3 | |
4 | | impl Foo {
5 | |     fn f () {
6 | |         impl Self { }
7 | |     }
8 | | }
  | |_^

```

I guess for best reference, this is the beta version used in the playground the time I tried, but it happened in all stable, nightly and beta.

```
Build using the Beta version: 1.50.0-beta.9
(2021-02-06 2efd07024a6d1dc0d4ea)
```

and stable:

```
Build using the Stable version: 1.49.0
```

I needed this code for an attribute macro, which would wrap an associated function, and reimplement the original funcion in an internal impl in the wrapper function. This is the minimal code to reproduce my problem.

**Comment by jonas-schievink** [comment]
Also happens with just `impl Self {}` by itself. Not a bug, just a bad diagnostic.

**Comment by estebank** [comment]
Somewhat surprisingly a nested `impl Foo {}` is not a problem. This might be a reasonable side step for your macro for now. Modifying the item collection process to make this work might be workable, but it won't happen soon enough for your needs.

**Comment by compiler-errors** [comment]
@BoxyUwU fixed this
