### ISSUE TITLE
Suggestion to add the question mark operator creates invalid code for structs that use the shorthand syntax

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#118145]
### Code

```Rust
struct Stuff { count: i32 }
struct Error;

fn demo() -> Result<Stuff, Error> {
    let count = Ok(1);
    Ok(Stuff { count })
}
```

### Current output

```text
error[E0308]: mismatched types
 --> src/lib.rs:6:16
  |
6 |     Ok(Stuff { count })
  |                ^^^^^ expected `i32`, found `Result<{integer}, _>`
  |
  = note: expected type `i32`
             found enum `Result<{integer}, _>`
help: use the `?` operator to extract the `Result<{integer}, _>` value, propagating a `Result::Err` value to the caller
  |
6 |     Ok(Stuff { count? })
  |                     +
```

### Desired output

```text
error[E0308]: mismatched types
 --> src/lib.rs:6:16
  |
6 |     Ok(Stuff { count })
  |                ^^^^^ expected `i32`, found `Result<{integer}, _>`
  |
  = note: expected type `i32`
             found enum `Result<{integer}, _>`
help: use the `?` operator to extract the `Result<{integer}, _>` value, propagating a `Result::Err` value to the caller
  |
6 |     Ok(Stuff { count: count? })
  |                     ++++++++
```

### Anything else?

This appears to be a new diagnostic, as it appears in 1.75.0-beta.3 (2023-11-20 b66b7951b9b4258fc433) but not in 1.74.0.

**Comment by shepmaster** [comment]
Introduced in f3d20be42bba6672be4818781487a7904b47354b; /cc @chenyukang @b-naber

**Comment by shepmaster** [comment]
The same happens when the `?` operator is not applicable and `unwrap` is suggested instead:

```rust
struct Stuff { count: i32 }
struct Error;

fn demo() -> Stuff {
    let count = Ok(1);
    Ok(Stuff { count })
}
```

```
help: consider using `Result::expect` to unwrap the `Result<{integer}, _>` value, panicking if the value is a `Result::Err`
  |
6 |     Ok(Stuff { count.expect("REASON") })
  |                     +++++++++++++++++
```
