### ISSUE TITLE
Is exact count of other implementations useful in this error message?

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#102864]
I got the following CI failure in #102862
```text
---- [ui] src/test/ui/try-trait/bad-interconversion.rs stdout ----
diff of stderr:

16	             <f64 as From<i16>>
17	             <f64 as From<i32>>
18	             <f64 as From<i8>>
-	           and 67 others
+	           and 68 others
20	   = note: required for `Result<u64, u8>` to implement `FromResidual<Result<Infallible, i32>>`
21	
22	error[E0277]: the `?` operator can only be used on `Result`s, not `Option`s, in a function that returns `Result`
```

I don't know if this is a diagnostics request or a UI test normalization request, but getting UI test failures when adding a `From` implementation is kinda annoying (if admittedly easy enough to fix).

So I wonder how much value the exact number here is providing.  I wonder if it might make sense to change the message to 

> and many others

if it's above some threshold.

I can't see any reason the exact count is useful to the programmer reading the error (at least when it's a large number), and it might save some work in error message generation to stop once it's found a bunch.

**Comment by compiler-errors** [comment]
I'm fine with either of the suggestions, choosing some other phrasing for large numbers of trait candidates or normalizing it in the UI tests themselves.

Coincidentally, @mejrs just implemented a trybuild normalization for this in dtolnay/trybuild@ea3f2070321b7718ad5244af1fe38658f18c4917. 

The code we use to generate "`... and {} others`" is kinda scattered all over the place for different suggestions, but if we're gonna change one we should change them all.

>  and it might save some work in error message generation to stop once it's found a bunch.

But this shouldn't be a primary motivation, since we calculate the list of candidates (and other lists used in suggestions that end with "`... and {} others`") eagerly, and it'd probably be more work to make it lazy -- especially because diagnostics code isn't focused on speed.
