### PR TITLE
Revert "Stabilize `str_as_str`"

### LINKED ISSUE #152961: Regression in `rgb` with `as_mut_slice`
### Code

Cargo.toml
```toml
[package]
name = "rust-test"
version = "0.1.0"
edition = "2024"

[dependencies]
resvg = "=0.34.1"
```

main.rs
```rust
extern crate resvg;
fn main() { }
```

I'll try to make a smaller reproducer

### Regression

This compiles on nightly 2026-02-21, but fails on nightly 2026-02-22.

```
error[E0308]: mismatched types
  --> /home/jonathan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/resvg-0.34.1/src/filter/iir_blur.rs:63:22
   |
63 |     gaussian_channel(data, &d, 0, buf);
   |     ---------------- ^^^^ expected `&mut [u8]`, found `&mut [RGBA<u8>]`
   |     |
   |     arguments to this function are incorrect
   |
   = note: expected mutable reference `&mut [u8]`
              found mutable reference `&mut [rgb::RGBA<u8>]`
note: function defined here
  --> /home/jonathan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/resvg-0.34.1/src/filter/iir_blur.rs:69:4
   |
69 | fn gaussian_channel(data: &mut [u8], d: &BlurData, channel: usize, buf: &mut Vec<f64>) {
   |    ^^^^^^^^^^^^^^^^ ---------------

```

### Cause

Found because rust-timer failed in https://github.com/rust-lang/rust/pull/152934, so this has serious impact.
Locally bisected to PR https://github.com/rust-lang/rust/pull/151603

CC @jhpratt @GrigorenkoPV

### PR DESCRIPTION
**Pull request by JonathanBrouwer**
Reverts https://github.com/rust-lang/rust/pull/151603, clean revert.
Fixes https://github.com/rust-lang/rust/issues/152961

### CODE REVIEW

**Comment by jieyouxu** [comment]
Can a regression test be added (i.e. https://github.com/rust-lang/rust/issues/152961#issuecomment-3940571461) to catch future re-regressions?

**Comment by GrigorenkoPV** [comment]
LGTM, ~would appreciate if someone could re-open the tracking issue (#130366)~. Thanks!
