### PR TITLE
[WIP] Fix compiler regression from 1.64.0 relating to `&(dyn Trait + '_)` params

### LINKED ISSUE #103762: Broken compilation with `&(dyn Trait + '_)`
### Code

I tried this code:

```rust
pub trait AsStr {
    fn as_str(&self) -> &str;
}

fn foo(bar: &(dyn AsStr + '_)) -> &'_ str {
    bar.as_str()
}
```

I expected to see this happen: code compiles successfully.

Instead, this happened:
```
error[E0106]: missing lifetime specifier
 --> src/main.rs:5:36
  |
5 | fn foo(bar: &(dyn AsStr + '_)) -> &'_ str {
  |             -----------------      ^^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say which one of `bar`'s 2 lifetimes it is borrowed from
help: consider introducing a named lifetime parameter
  |
5 | fn foo<'a>(bar: &'a (dyn AsStr + 'a)) -> &'a str {
  |       ++++       ++              ~~       ~~

For more information about this error, try `rustc --explain E0106`.
```

### Version it worked on

It most recently worked on Rust 1.63.0.

### Version with regression

It is broken on current stable, i.e. 1.64.0.

Here's the output by `cargo-bisect-rustc`:

> searched nightlies: from nightly-2022-06-24 to nightly-2022-08-05
> regressed nightly: nightly-2022-07-15
> searched commit range: https://github.com/rust-lang/rust/compare/87588a2afd9ca903366f0deaf84d805f34469384...c2f428d2f3340a0e7d995f4726223db91b93704c
> regressed commit: https://github.com/rust-lang/rust/commit/f1a8854f9be2e5cad764d630a53d26c7b72f8162
> 
> <details>
> <summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>
> 
> 
> Host triple: x86_64-unknown-linux-gnu
> Reproduce with:
> ```bash
> cargo bisect-rustc --end=1.64.0 -- check 
> ```
> </details>
> 

It seems to have been found previously by `gluon` developers and fixed in their own code [in this commit](https://github.com/gluon-lang/gluon/commit/f30127bf5e27520d41a654154381c2e9601d2f3e), and today popped up also [on URLO](https://users.rust-lang.org/t/possible-to-use-cargo-timings-on-a-project-that-uses-gluon/83458).

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

### PR DESCRIPTION
**Pull request by BGR360**
This is my attempt to fix #103762. It doesn't fully work. I'd like some input on what to try next.

What I did was special-case the treatment of anonymous lifetime bounds (`+ '_`) in trait object types when they are encountered inside a function's parameters. I simply resolved them to `LifetimeRes::Infer` to try to let typeck figure them out.

This does successfully get around the error that the OP of #103762 encountered, and goes through to astconv.

However, now it fails in astconv with the following error:

```
error[E0228]: the lifetime bound for this object type cannot be deduced from context; please supply an explicit bound
  --> src/test/ui/lifetimes/issue-103762-1.rs:19:23
   |
19 | fn b1(_: &i32, _: Box<dyn Trait + '_>) -> &str { loop {} }
   |                       ^^^^^^^^^^^^^^
```

And I discovered an existing test case which shows that `(_: Box<dyn Trait + '_>)` was previously accepted, which I found interesting. It now fails with the same error though:

```
error[E0228]: the lifetime bound for this object type cannot be deduced from context; please supply an explicit bound
  --> src/test/ui/regions/regions-trait-1.rs:25:18
   |
25 | fn get_v(gc: Box<dyn GetCtxt + '_>) -> usize {
   |                  ^^^^^^^^^^^^^^^^
```

I don't know for sure what this means, but it sounds like I'm sorta between a rock and a hard place. I think astconv probably wants `Fresh` lifetimes for these anonymous bounds, but `resolve_fn_signature` does _not_ want that. Does there perhaps want to be a `LifetimeRes::FreshIfNoOtherFresh`?

I'm definitely in over my head a bit here. I've learned quite a bit about rustc_resolve in trying to do this, but the amount of time it would take me alone to learn enough about it to figure out where to go next is too much. I think I really need some direction from somebody who's familiar with this.

r? @cjgillot since it seems you've been the one doing most of the work to do more lifetime checking in rustc_resolve.

But if they're busy, then @compiler-errors is this an area of rustc I could pick your brain about at your office hours?

### CODE REVIEW

**Comment by compiler-errors** [comment]
> is this an area of rustc I could pick your brain about at your office hours?

Feel free, though I am not super familiar, it's definitely something I can dig into.

File: compiler/rustc_resolve/src/late.rs [hunk 1]
```diff
@@ -1787,6 +1805,32 @@ impl<'a: 'ast, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
...
+    /// ```
+    ///
+    /// When we're resolving function parameters, we usually want each elided or
+    /// anonymous lifetime to result in a new elision candidate, but not in this case.
+    #[instrument(level = "trace", skip(self))]
+    fn resolve_anonymous_lifetime_in_trait_object_bounds(&mut self, lifetime: &Lifetime) {
+        debug_assert_eq!(lifetime.ident.name, kw::UnderscoreLifetime);
+        debug_assert!(self.diagnostic_metadata.current_trait_object.is_some());
+
+        if self.in_func_params {
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:1825]: This is likely to be incorrect in some corner cases. Could you:
- iterate on `self.lifetime_ribs` like `resolve_anonymous_lifetime` does,
- check `LifetimeRibKind::Fresh`?

Is the behaviour restricted to function parameters, or anywhere we have a `Fresh` rib?
What should `impl &(dyn Trait + '_) { /**/ }` mean?

File: compiler/rustc_resolve/src/late.rs [hunk 2]
```diff
@@ -1787,6 +1805,32 @@ impl<'a: 'ast, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
...
+            self.with_lifetime_rib(LifetimeRibKind::Elided(LifetimeRes::Infer), |this| {
```
Comment (cjgillot) [inline compiler/rustc_resolve/src/late.rs:1826]: The resolution is not `Infer`. In HIR, we should get an `ImplicitObjectLifetimeDefault`, but I did not create such variant in `LifetimeRes`. Could you create an extra `ImplicitObjectLifetimeDefault` variant in `LifetimeRes` and adapt lowering to translate it to `LifetimeName::ImplicitObjectLifetimeDefault`?

`Infer` means that type-checking will try to find the correct lifetime through type-inference. This is typically what appears in function bodies. `ImplicitObjectLifetimeDefault` means that we will inspect the surrounding type to apply the object lifetime rules: `&'a (dyn Trait + '_)` implicitly becomes `&'a (dyn Trait + 'a)` etc.

File: compiler/rustc_resolve/src/late.rs (hunk 1 above)
Comment (BGR360) [reply compiler/rustc_resolve/src/late.rs:1825]: `impl &(dyn Trait + '_) { ... }` isn't allowed:

```
error[E0390]: cannot define inherent `impl` for primitive types
  --> /Users/ben/Documents/Rust/rust-lang/rust/src/test/ui/lifetimes/issue-103762-1.rs:42:6
   |
LL | impl &(dyn Trait + '_) {
   |      ^^^^^^^^^^^^^^^^^
   |
   = help: consider using an extension trait instead
   = note: you could also try moving the reference to uses of `dyn Trait` (such as `self`) within the implementation
```

I can believe that this way of doing it is brittle. Can you try to think of any more edge cases? I'm fresh out of ideas at the moment.

I'll try out your strategy of checking for the presence of the rib. Though I think you probably meant `LifetimeRibKind::AnonymousCreateParameter` rather than `LifetimeRibKind::Fresh`?

File: compiler/rustc_resolve/src/late.rs (hunk 2 above)
Comment (BGR360) [reply compiler/rustc_resolve/src/late.rs]: Thank you for the pointer!

This does indeed get us past any errors in resolve and astconv, and all the tests I wrote compile as I had intended.

However, it seems `ImplicitObjectLifetimeDefault` results in the wrong lifetime for `Box<dyn Trait + '_>`, as this failed test shows:

```rust
// check-pass

struct Ctxt {
    v: usize,
}

trait GetCtxt {
    // Here the `&` is bound in the method definition:
    fn get_ctxt(&self) -> &Ctxt;
}

struct HasCtxt<'a> {
    c: &'a Ctxt,
}

impl<'a> GetCtxt for HasCtxt<'a> {
    // Ok: Have implied bound of WF(&'b HasCtxt<'a>)
    // so know 'a: 'b
    // so know &'a Ctxt <: &'b Ctxt
    fn get_ctxt<'b>(&'b self) -> &'a Ctxt {
        self.c
    }
}

fn get_v(gc: Box<dyn GetCtxt + '_>) -> usize {
    gc.get_ctxt().v
}

fn main() {
    let ctxt = Ctxt { v: 22 };
    let hc = HasCtxt { c: &ctxt };
    assert_eq!(get_v(Box::new(hc) as Box<dyn GetCtxt>), 22);
}
```

```
---- [ui] src/test/ui/regions/regions-trait-1.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/Users/ben/Documents/Rust/rust-lang/rust/build/aarch64-apple-darwin/stage1/bin/rustc" "/Users/ben/Documents/Rust/rust-lang/rust/src/test/ui/regions/regions-trait-1.rs" "-Zthreads=1" "--target=aarch64-apple-darwin" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "--emit" "metadata" "-C" "prefer-dynamic" "--out-dir" "/Users/ben/Documents/Rust/rust-lang/rust/build/aarch64-apple-darwin/test/ui/regions/regions-trait-1" "-A" "unused" "-Crpath" "-Cdebuginfo=0" "-Lnative=/Users/ben/Documents/Rust/rust-lang/rust/build/aarch64-apple-darwin/native/rust-test-helpers" "-L" "/Users/ben/Documents/Rust/rust-lang/rust/build/aarch64-apple-darwin/test/ui/regions/regions-trait-1/auxiliary"
stdout: none
--- stderr -------------------------------
error[E0597]: `ctxt` does not live long enough
  --> /Users/ben/Documents/Rust/rust-lang/rust/src/test/ui/regions/regions-trait-1.rs:31:27
   |
LL |     let hc = HasCtxt { c: &ctxt };
   |                           ^^^^^ borrowed value does not live long enough
LL |     assert_eq!(get_v(Box::new(hc) as Box<dyn GetCtxt>), 22);
   |                      ------------ cast requires that `ctxt` is borrowed for `'static`
LL | }
   | - `ctxt` dropped here while still borrowed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0597`.
------------------------------------------
```

So, I'm not sure where to go from there.

File: compiler/rustc_resolve/src/late.rs (hunk 1 above)
Comment (cjgillot) [reply compiler/rustc_resolve/src/late.rs:1825]: `impl Trait for &(dyn Trait2 + '_) {}` is allowed.

If you want corner cases:
```
fn foo(_: fn(&(dyn Trait + '_)) -> &(dyn Trait + '_)) {}
fn bar(_: [u8; { { fn blah() -> &(dyn Trait + '_) {} }; 5 }]) {}
```

> I'll try out your strategy of checking for the presence of the rib. Though I think you probably meant LifetimeRibKind::AnonymousCreateParameter rather than LifetimeRibKind::Fresh?

Exactly.

File: compiler/rustc_resolve/src/late.rs (hunk 2 above)
Comment (BGR360) [reply compiler/rustc_resolve/src/late.rs]: ^^ This is the more concerning bit. Please advise when you can.

**Comment by cjgillot** [comment]
@BGR360 I realise that I led you in a completely wrong direction. I'm sorry. The fix is actually much simpler than all this: ignore the lifetime from the trait object when looking for elision candidates.
That was the behaviour in the old HIR-based code: https://github.com/rust-lang/rust/blob/b276b65f46465cffe207b4b732e6ab4642d47558/compiler/rustc_resolve/src/late/lifetimes.rs#L2857-L2861

The easiest way to do that is to thread a `ast::visit::BoundKind` in `ast::visit::LifetimeCtxt::Bound`, and skip inserting anything into `self.lifetime_elision_candidates` if the lifetime is elided and the context is `LifetimeCtxt::Bound(BoundKind::TraitObject)`.

**Comment by Dylan-DPC** [comment]
Closing this PR as inactive. Feel free to open a new pr if you wish to continue working on this.
