### ISSUE TITLE
Crash when compiling an event handler implementation with latest stable rustc 1.88.0

### ISSUE THREAD

**Issue by gents83** [rust-lang/rust#143821]
### Code

you can find it here:
https://github.com/gents83/INOX/blob/master/crates/resources/src/event_handlers.rs
compiling the crate inside:
https://github.com/gents83/INOX/tree/master/crates/resources
```rust
impl<T> EventHandler for SerializableResourceEventHandler<T>
where
    T: SerializableResource,
    <T as DataTypeResource>::DataType: Send + Sync,
{
    fn handle_events(&self, f: &dyn LoadFunction) {
        self.listener
            .process_messages(|msg: &SerializableResourceEvent<T>| {
                let SerializableResourceEvent::<T>::Load(path, on_create_data) = msg;
                //inox_log::debug_log!("Received load event for: {:?}", path);
                if <T as SerializableResource>::is_matching_extension(path.as_path()) {
                    //inox_log::debug_log!("Handling it!");
                    let p = path.clone();
                    let on_create_data = on_create_data.clone();
                    f(Box::new(move |shared_data, message_hub| {
                        T::create_from_file(shared_data, message_hub, p.as_path(), on_create_data);
                    }));
                }
            });
    }
}
```

### Meta
rustc version 1.88.0

### Error output
```
error: internal compiler error: compiler\rustc_borrowck\src\universal_regions.rs:928:36: cannot convert `ReLateParam(DefId(0:225 ~ inox_resources[5473]::event_handlers::{impl#6}::handle_events::{closure#0}), LateNamed(DefId(0:722 ~ inox_resources[5473]::event_handlers::{impl#6}::handle_events::'_), '_))` to a region vid


thread 'rustc' panicked at compiler\rustc_borrowck\src\universal_regions.rs:928:36:
Box<dyn Any>
stack backtrace:
   0:     0x7ff85e7ba9c2 - std::backtrace_rs::backtrace::win64::trace
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\..\..\backtrace\src\backtrace\win64.rs:85
   1:     0x7ff85e7ba9c2 - std::backtrace_rs::backtrace::trace_unsynchronized
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
   2:     0x7ff85e7ba9c2 - std::sys::backtrace::_print_fmt
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\sys\backtrace.rs:66
   3:     0x7ff85e7ba9c2 - std::sys::backtrace::impl$0::print::impl$0::fmt
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\sys\backtrace.rs:39
   4:     0x7ff85e7ed18b - core::fmt::rt::Argument::fmt
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\core\src\fmt\rt.rs:181
   5:     0x7ff85e7ed18b - core::fmt::write
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\core\src\fmt\mod.rs:1446
   6:     0x7ff85e7b0b17 - std::io::default_write_fmt
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\io\mod.rs:639
   7:     0x7ff85e7b0b17 - std::io::Write::write_fmt<std::sys::stdio::windows::Stderr>
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\io\mod.rs:1914
   8:     0x7ff85e7ba805 - std::sys::backtrace::BacktraceLock::print
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\sys\backtrace.rs:42
   9:     0x7ff85e7c045a - std::panicking::default_hook::closure$0
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\panicking.rs:300
  10:     0x7ff85e7c01f0 - std::panicking::default_hook
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\panicking.rs:327
  11:     0x7ff85fedf589 - core[3c86ab912ec38c67]::slice::sort::unstable::heapsort::heapsort::<((rustc_lint_defs[852ad02eb4e36d75]::Level, &str), usize), <((rustc_lint_defs[852ad02eb4e36d75]::Level, &str), usize) as core[3c86ab912ec38c67]::cmp::PartialOrd>::lt>
  12:     0x7ff85e7c10ee - std::panicking::rust_panic_with_hook
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\panicking.rs:841
  13:     0x7ff861776943 - RINvNtNtNtNtCs5cb5cxfFw7H_4core5slice4sort6stable9quicksort9quicksortTjRNtNtCs2UPeNLgV7Nx_12rustc_errors7snippet10AnnotationENCINvMNtCs2ocB3yIIgEv_5alloc5sliceSB15_11sort_by_keyTINtNtBa_3cmp7ReversejEbENCNCNvMs5_NtB1c_7emitterNtB3o_12HumanEmitter18render_s
  14:     0x7ff861769e89 - std[df32d1bc89881d89]::sys::backtrace::__rust_end_short_backtrace::<std[df32d1bc89881d89]::panicking::begin_panic<rustc_errors[21f88e7a2b20a5b5]::ExplicitBug>::{closure#0}, !>
  15:     0x7ff861769e71 - std[df32d1bc89881d89]::panicking::begin_panic::<rustc_errors[21f88e7a2b20a5b5]::ExplicitBug>
  16:     0x7ff861783bc5 - <rustc_errors[21f88e7a2b20a5b5]::diagnostic::BugAbort as rustc_errors[21f88e7a2b20a5b5]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  17:     0x7ff8616c8c29 - rustc_middle[415f7117aa72a916]::util::bug::span_bug_fmt::<rustc_span[42e336d87a219f10]::span_encoding::Span>
  18:     0x7ff861699cdd - <rustc_middle[415f7117aa72a916]::ty::consts::Const>::walk
  19:     0x7ff861699aa6 - <rustc_middle[415f7117aa72a916]::ty::consts::Const>::walk
  20:     0x7ff8616c8b22 - rustc_middle[415f7117aa72a916]::util::bug::bug_fmt
  21:     0x7ff85eeab192 - <alloc[1bd79818fa64b571]::rc::Rc<rustc_mir_dataflow[3d6a567cba390439]::points::DenseLocationMap>>::drop_slow
  22:     0x7ff85e0db858 - <rustc_borrowck[94623f7bbe74a0e8]::region_infer::values::PlaceholderIndices>::lookup_index
  23:     0x7ff85e0e0ab8 - <rustc_borrowck[94623f7bbe74a0e8]::type_check::relate_tys::NllTypeRelating>::create_next_universe
  24:     0x7ff85ef92673 - <rustc_borrowck[94623f7bbe74a0e8]::type_check::TypeChecker as rustc_middle[415f7117aa72a916]::mir::visit::Visitor>::visit_rvalue
  25:     0x7ff85ef52dc5 - <rustc_borrowck[94623f7bbe74a0e8]::type_check::TypeChecker as rustc_middle[415f7117aa72a916]::mir::visit::Visitor>::visit_body
  26:     0x7ff85efcd078 - <rustc_borrowck[94623f7bbe74a0e8]::type_check::TypeChecker as rustc_middle[415f7117aa72a916]::mir::visit::Visitor>::visit_const_operand
  27:     0x7ff85e0db19a - <rustc_borrowck[94623f7bbe74a0e8]::region_infer::values::PlaceholderIndices>::lookup_index
  28:     0x7ff85ef06e34 - rustc_borrowck[94623f7bbe74a0e8]::mir_borrowck
  29:     0x7ff85f70d48b - rustc_query_impl[dbd98c1d837197ef]::plumbing::query_key_hash_verify_all
  30:     0x7ff85f649863 - RINvNtNtCs7IFNuxsOQZH_18rustc_query_system5query8plumbing17try_execute_queryINtCsiSfPmaTe9VX_16rustc_query_impl13DynamicConfigINtNtCsco0OWYSRcIH_21rustc_data_structures9vec_cache8VecCacheNtNtCs5K2xb0UU2Jw_10rustc_span6def_id10LocalDefIdINtNtNtCs5BYDmTWcnKQ
  31:     0x7ff85f717de5 - rustc_query_impl[dbd98c1d837197ef]::plumbing::query_key_hash_verify_all
  32:     0x7ff85e8250e3 - <rustc_interface[cdf4984d0e22fb97]::passes::LintStoreExpandImpl as rustc_expand[eb94a41e01d8b712]::base::LintStoreExpand>::pre_expansion_lint
  33:     0x7ff85adadb57 - rustc_interface[cdf4984d0e22fb97]::passes::analysis
  34:     0x7ff85e33e0ba - RINvNtNtCs7IFNuxsOQZH_18rustc_query_system5query8plumbing17try_execute_queryINtCsiSfPmaTe9VX_16rustc_query_impl13DynamicConfigINtNtCsco0OWYSRcIH_21rustc_data_structures9vec_cache8VecCacheNtNtCs5K2xb0UU2Jw_10rustc_span6def_id8CrateNumINtNtNtCs5BYDmTWcnKQ_12
  35:     0x7ff85e247a7c - RINvNtNtCs7IFNuxsOQZH_18rustc_query_system5query8plumbing17try_execute_queryINtCsiSfPmaTe9VX_16rustc_query_impl13DynamicConfigINtNtB4_6caches11SingleCacheINtNtNtCs5BYDmTWcnKQ_12rustc_middle5query5erase6ErasedAhj0_EEKb0_KB3s_KB3s_ENtNtB1f_8plumbing9QueryCtx
  36:     0x7ff85e3445dc - rustc_query_impl[dbd98c1d837197ef]::query_system
  37:     0x7ff85ad6ecc5 - std[df32d1bc89881d89]::sys::backtrace::__rust_begin_short_backtrace::<<std[df32d1bc89881d89]::thread::Builder>::spawn_unchecked_<ctrlc[dac7a3742903fcef]::set_handler_inner<rustc_driver_impl[824051745b838893]::install_ctrlc_handler::{closure#0}>::{closure#0}, ()>::{closure#1}::{closure#0}::{closure#0}, ()>
  38:     0x7ff85ad68f23 - std[df32d1bc89881d89]::sys::backtrace::__rust_begin_short_backtrace::<<std[df32d1bc89881d89]::thread::Builder>::spawn_unchecked_<ctrlc[dac7a3742903fcef]::set_handler_inner<rustc_driver_impl[824051745b838893]::install_ctrlc_handler::{closure#0}>::{closure#0}, ()>::{closure#1}::{closure#0}::{closure#0}, ()>
  39:     0x7ff85ad647af - RINvNtNtCsja4ZeDc2XAj_3std3sys9backtrace28___rust_begin_short_backtraceNCNCINvNtCshGilUj5gLc1_15rustc_interface4util26run_in_thread_with_globalsNCINvB1e_31run_in_thread_pool_with_globalsNCINvNtB1g_9interface12run_compileruNCNvCsbbk6E3yTTQl_17rustc_driver_i
  40:     0x7ff85ad73020 - std[df32d1bc89881d89]::sys::backtrace::__rust_begin_short_backtrace::<<std[df32d1bc89881d89]::thread::Builder>::spawn_unchecked_<ctrlc[dac7a3742903fcef]::set_handler_inner<rustc_driver_impl[824051745b838893]::install_ctrlc_handler::{closure#0}>::{closure#0}, ()>::{closure#1}::{closure#0}::{closure#0}, ()>
  41:     0x7ff85e7c545d - alloc::boxed::impl$28::call_once
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\alloc\src\boxed.rs:1966
  42:     0x7ff85e7c545d - alloc::boxed::impl$28::call_once
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\alloc\src\boxed.rs:1966
  43:     0x7ff85e7c545d - std::sys::pal::windows::thread::impl$0::new::thread_start
                               at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library\std\src\sys\pal\windows\thread.rs:56
  44:     0x7ff9979de8d7 - BaseThreadInitThunk
  45:     0x7ff99919bf2c - RtlUserThreadStart

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.88.0 (6b00bc388 2025-06-23) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type lib -C opt-level=1 -C embed-bitcode=no -C debuginfo=2 -C debug-assertions=on -C incremental=[REDACTED] -C link-arg=-fuse-ld=lld

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `event_handlers::<impl at resources\src\event_handlers.rs:93:1: 96:52>::handle_events`
#1 [analysis] running analysis passes on this crate
end of query stack
error: could not compile `inox_resources` (lib)
```

**Comment by Snarpix** [comment]
Same problem - ICE on stable 1.88

### Code(reduced)
```Rust
fn data_<T: 'static>(_: &()) -> &T {
    loop {}
}

fn register<T, F>(f: F) -> IfaceToken<T>
where
    T: 'static,
    F: FnOnce(&()),
{
    loop {}
}

fn method_with_cr_async<CB>(cb: CB)
where
    CB: Fn(),
{
    loop {}
}

struct IfaceToken<T: 'static>(T);

fn foo<T>() -> IfaceToken<T> {
    register::<T, _>(|b: &()| {
        method_with_cr_async(|| {
            data_::<T>(&());
        });
    })
}

struct A();

fn main() {
    foo::<A>();
}
```

Original code was from dbus-crossroads.

### Meta
ICE on rustc versions 1.86-1.88, including nightly.
Rust 1.85.1 complies.

### Error output
```
error: internal compiler error: compiler/rustc_borrowck/src/universal_regions.rs:928:36: cannot convert `ReLateParam(DefId(0:16 ~ rust_repro[c6fb]::foo::{closure#0}), LateNamed(DefId(0:23 ~ rust_repro[c6fb]::foo::'_), '_))` to a region vid
```
<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at compiler/rustc_borrowck/src/universal_regions.rs:928:36:
Box<dyn Any>
stack backtrace:
   0:     0x7fb0c2546543 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h46a716bba2450163
   1:     0x7fb0c2c05947 - core::fmt::write::h275e5980d7008551
   2:     0x7fb0c3cc16d1 - std::io::Write::write_fmt::h561a66a0340b6995
   3:     0x7fb0c25463a2 - std::sys::backtrace::BacktraceLock::print::hafb9d5969adc39a0
   4:     0x7fb0c2549f9a - std::panicking::default_hook::{{closure}}::hae2e97a5c4b2b777
   5:     0x7fb0c2549b1f - std::panicking::default_hook::h3db1b505cfc4eb79
   6:     0x7fb0c1575b93 - std[61bb86a81f0491]::panicking::update_hook::<alloc[7c55b5a5cf9e3c5f]::boxed::Box<rustc_driver_impl[b7d73271a09ede7d]::install_ice_hook::{closure#1}>>::{closure#0}
   7:     0x7fb0c254a813 - std::panicking::rust_panic_with_hook::h409da73ddef13937
   8:     0x7fb0c15b1f41 - std[61bb86a81f0491]::panicking::begin_panic::<rustc_errors[38d461c0e4a8a2b3]::ExplicitBug>::{closure#0}
   9:     0x7fb0c15a5e16 - std[61bb86a81f0491]::sys::backtrace::__rust_end_short_backtrace::<std[61bb86a81f0491]::panicking::begin_panic<rustc_errors[38d461c0e4a8a2b3]::ExplicitBug>::{closure#0}, !>
  10:     0x7fb0c15a5bf3 - std[61bb86a81f0491]::panicking::begin_panic::<rustc_errors[38d461c0e4a8a2b3]::ExplicitBug>
  11:     0x7fb0c15bc5c1 - <rustc_errors[38d461c0e4a8a2b3]::diagnostic::BugAbort as rustc_errors[38d461c0e4a8a2b3]::diagnostic::EmissionGuarantee>::emit_producing_guarantee
  12:     0x7fb0c1c2adaa - rustc_middle[1134768a56a896b4]::util::bug::opt_span_bug_fmt::<rustc_span[1f7aec696a0836ce]::span_encoding::Span>::{closure#0}
  13:     0x7fb0c1c0331a - rustc_middle[1134768a56a896b4]::ty::context::tls::with_opt::<rustc_middle[1134768a56a896b4]::util::bug::opt_span_bug_fmt<rustc_span[1f7aec696a0836ce]::span_encoding::Span>::{closure#0}, !>::{closure#0}
  14:     0x7fb0c1c0318b - rustc_middle[1134768a56a896b4]::ty::context::tls::with_context_opt::<rustc_middle[1134768a56a896b4]::ty::context::tls::with_opt<rustc_middle[1134768a56a896b4]::util::bug::opt_span_bug_fmt<rustc_span[1f7aec696a0836ce]::span_encoding::Span>::{closure#0}, !>::{closure#0}, !>
  15:     0x7fb0bee85ff0 - rustc_middle[1134768a56a896b4]::util::bug::bug_fmt
  16:     0x7fb0c32b316a - <rustc_infer[90ea0da8f705ff7b]::infer::outlives::obligations::TypeOutlives<&mut rustc_borrowck[177ef636edd0ce33]::type_check::constraint_conversion::ConstraintConversion>>::components_must_outlive
  17:     0x7fb0c3c2c477 - <rustc_borrowck[177ef636edd0ce33]::type_check::constraint_conversion::ConstraintConversion>::convert
  18:     0x7fb0c3c2ae2f - <rustc_borrowck[177ef636edd0ce33]::type_check::TypeChecker>::prove_closure_bounds
  19:     0x7fb0bfed40d0 - <rustc_borrowck[177ef636edd0ce33]::type_check::TypeChecker as rustc_middle[1134768a56a896b4]::mir::visit::Visitor>::visit_rvalue
  20:     0x7fb0c3f9d233 - <rustc_borrowck[177ef636edd0ce33]::type_check::TypeChecker as rustc_middle[1134768a56a896b4]::mir::visit::Visitor>::visit_body
  21:     0x7fb0c3c3fd14 - rustc_borrowck[177ef636edd0ce33]::do_mir_borrowck
  22:     0x7fb0c3c2cbf6 - <rustc_borrowck[177ef636edd0ce33]::root_cx::BorrowCheckRootCtxt>::get_or_insert_nested
  23:     0x7fb0c2fca8ef - rustc_borrowck[177ef636edd0ce33]::mir_borrowck
  24:     0x7fb0c2fca59f - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_borrowck::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 8usize]>>
  25:     0x7fb0c2fcc664 - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_data_structures[e24569e090b577b3]::vec_cache::VecCache<rustc_span[1f7aec696a0836ce]::def_id::LocalDefId, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 8usize]>, rustc_query_system[48caa8a8a4cfcb68]::dep_graph::graph::DepNodeIndex>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, true>
  26:     0x7fb0c2fa3d12 - rustc_query_impl[6f0ca6887c150a69]::query_impl::mir_borrowck::get_query_incr::__rust_end_short_backtrace
  27:     0x7fb0c35e0bd4 - rustc_interface[a43b584b4c4124b4]::passes::run_required_analyses
  28:     0x7fb0c3aedb5e - rustc_interface[a43b584b4c4124b4]::passes::analysis
  29:     0x7fb0c3aedb35 - rustc_query_impl[6f0ca6887c150a69]::plumbing::__rust_begin_short_backtrace::<rustc_query_impl[6f0ca6887c150a69]::query_impl::analysis::dynamic_query::{closure#2}::{closure#0}, rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 0usize]>>
  30:     0x7fb0c3eaaf04 - rustc_query_system[48caa8a8a4cfcb68]::query::plumbing::try_execute_query::<rustc_query_impl[6f0ca6887c150a69]::DynamicConfig<rustc_query_system[48caa8a8a4cfcb68]::query::caches::SingleCache<rustc_middle[1134768a56a896b4]::query::erase::Erased<[u8; 0usize]>>, false, false, false>, rustc_query_impl[6f0ca6887c150a69]::plumbing::QueryCtxt, true>
  31:     0x7fb0c3eaa828 - rustc_query_impl[6f0ca6887c150a69]::query_impl::analysis::get_query_incr::__rust_end_short_backtrace
  32:     0x7fb0c3daa0c7 - rustc_interface[a43b584b4c4124b4]::passes::create_and_enter_global_ctxt::<core[105cb658ab12d76f]::option::Option<rustc_interface[a43b584b4c4124b4]::queries::Linker>, rustc_driver_impl[b7d73271a09ede7d]::run_compiler::{closure#0}::{closure#2}>::{closure#2}::{closure#0}
  33:     0x7fb0c3cfe966 - rustc_interface[a43b584b4c4124b4]::interface::run_compiler::<(), rustc_driver_impl[b7d73271a09ede7d]::run_compiler::{closure#0}>::{closure#1}
  34:     0x7fb0c3cb523e - std[61bb86a81f0491]::sys::backtrace::__rust_begin_short_backtrace::<rustc_interface[a43b584b4c4124b4]::util::run_in_thread_with_globals<rustc_interface[a43b584b4c4124b4]::util::run_in_thread_pool_with_globals<rustc_interface[a43b584b4c4124b4]::interface::run_compiler<(), rustc_driver_impl[b7d73271a09ede7d]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>
  35:     0x7fb0c3cb56b4 - <<std[61bb86a81f0491]::thread::Builder>::spawn_unchecked_<rustc_interface[a43b584b4c4124b4]::util::run_in_thread_with_globals<rustc_interface[a43b584b4c4124b4]::util::run_in_thread_pool_with_globals<rustc_interface[a43b584b4c4124b4]::interface::run_compiler<(), rustc_driver_impl[b7d73271a09ede7d]::run_compiler::{closure#0}>::{closure#1}, ()>::{closure#0}, ()>::{closure#0}::{closure#0}, ()>::{closure#1} as core[105cb658ab12d76f]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  36:     0x7fb0c3cb6aab - std::sys::pal::unix::thread::Thread::new::thread_start::h1822d22fde68314f
  37:     0x7fb0bdaa57eb - <unknown>
  38:     0x7fb0bdb2918c - <unknown>
  39:                0x0 - <unknown>

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.88.0 (6b00bc388 2025-06-23) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type bin -C embed-bitcode=no -C debuginfo=2 -C incremental=[REDACTED]

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [mir_borrowck] borrow-checking `foo`
#1 [analysis] running analysis passes on this crate
end of query stack
warning: `rust_repro` (bin "rust_repro") generated 3 warnings
error: could not compile `rust_repro` (bin "rust_repro"); 3 warnings emitted

Caused by:
  process didn't exit successfully: `/home/snarpix/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name rust_repro --edition=2024 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=127 --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values())' -C metadata=02fcb308bcded37d -C extra-filename=-3c5760be336cf5c4 --out-dir /mnt/extra/rust_repro/target/debug/deps -C incremental=/mnt/extra/rust_repro/target/debug/incremental -L dependency=/mnt/extra/rust_repro/target/debug/deps` (exit status: 101)](error: internal compiler error: compiler/rustc_borrowck/src/universal_regions.rs:928:36: cannot convert `ReLateParam(DefId(0:16 ~ rust_repr)
```

</p>
</strong></summary>

**Comment by Snarpix** [comment]
Probably duplicate of https://github.com/rust-lang/rust/issues/135845, but this one:

1. Have been compiling on 1.85.1
2. Has ICE on stable

**Comment by Snarpix** [comment]
Bisection showed regression in nightly-2025-01-15

<details>

```
********************************************************************************
Regression in nightly-2025-01-15
********************************************************************************

fetching https://static.rust-lang.org/dist/2025-01-14/channel-rust-nightly-git-commit-hash.txt
missing nightly for 2025-01-14
fetching https://static.rust-lang.org/dist/2025-01-13/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2025-01-13: 40 B / 40 B [==============================================================] 100.00 % 811.42 KB/s converted 2025-01-13 to 48a426eca9df23b24b3559e545cf88dee61d4de9
fetching https://static.rust-lang.org/dist/2025-01-15/channel-rust-nightly-git-commit-hash.txt
nightly manifest 2025-01-15: 40 B / 40 B [================================================================] 100.00 % 1.19 MB/s converted 2025-01-15 to 8361aef0d7c29b1501a316a208ed84cd8a2ae5da
looking for regression commit between 2025-01-13 and 2025-01-15
fetching (via remote github) commits from max(48a426eca9df23b24b3559e545cf88dee61d4de9, 2025-01-11) to 8361aef0d7c29b1501a316a208ed84cd8a2ae5da
ending github query because we found starting sha: 48a426eca9df23b24b3559e545cf88dee61d4de9
get_commits_between returning commits, len: 16
  commit[0] 2025-01-12: Auto merge of #135384 - saethlin:inline-copy-from-slice, r=joboet
  commit[1] 2025-01-12: Auto merge of #135420 - GuillaumeGomez:rollup-93vepka, r=GuillaumeGomez
  commit[2] 2025-01-13: Auto merge of #135371 - Mark-Simulacrum:no-alloc-case-cmp, r=compiler-errors
  commit[3] 2025-01-13: Auto merge of #135352 - notriddle:notriddle/stability-shown, r=camelid
  commit[4] 2025-01-13: Auto merge of #135430 - jhpratt:rollup-39cecwd, r=jhpratt
  commit[5] 2025-01-13: Auto merge of #135167 - mzacho:depth-limit-const-eval-query, r=oli-obk
  commit[6] 2025-01-13: Auto merge of #135204 - RalfJung:win64-zst, r=SparrowLii
  commit[7] 2025-01-13: Auto merge of #135192 - jdupak-ms:cdb-tests, r=wesleywiser
  commit[8] 2025-01-14: Auto merge of #135438 - matthiaskrgr:rollup-rt2zrbz, r=matthiaskrgr
  commit[9] 2025-01-14: Auto merge of #135465 - jhpratt:rollup-7p93bct, r=jhpratt
  commit[10] 2025-01-14: Auto merge of #135359 - RalfJung:lang-start-unwind, r=joboet
  commit[11] 2025-01-14: Auto merge of #135473 - matthiaskrgr:rollup-ksnst4l, r=matthiaskrgr
  commit[12] 2025-01-14: Auto merge of #135442 - antoyo:subtree-update_cg_gcc_2025_01_12, r=GuillaumeGomez
  commit[13] 2025-01-14: Auto merge of #135278 - tgross35:ignore-std-dep-crates, r=SparrowLii
  commit[14] 2025-01-14: Auto merge of #135313 - compiler-errors:needs-mono, r=BoxyUwU
  commit[15] 2025-01-14: Auto merge of #135496 - matthiaskrgr:rollup-ps0cjzn, r=matthiaskrgr
ERROR: no CI builds available between 48a426eca9df23b24b3559e545cf88dee61d4de9 and 8361aef0d7c29b1501a316a208ed84cd8a2ae5da within last 167 days
```

</details>

**Comment by Snarpix** [comment]
Bisection by commits points to 99657aa3389885d40e7aa0f1729186a72a4be8b5.
So this is definitely duplicate of https://github.com/rust-lang/rust/issues/135845, but this reproduces on stable instead of nightly.
Caused by https://github.com/rust-lang/rust/pull/135479.

Actually looking on my example - it shouldn't compile on  1.85.1. 
fn foo<T>() passes T to fn register<T, F>() where T: 'static.
Since T is not 'static in foo this should cause compilation error.

**Comment by Snarpix** [comment]
Bisection by commits points to 99657aa3389885d40e7aa0f1729186a72a4be8b5.
So this is definitely duplicate of https://github.com/rust-lang/rust/issues/135845, but this reproduces on stable instead of nightly.
Caused by https://github.com/rust-lang/rust/pull/135479.

Actually looking on my example - it shouldn't compile on  1.85.1. 
fn foo<T>() passes T to fn register<T, F>() where T: 'static.
Since T is not 'static in foo this should cause compilation error.
