### PR TITLE
disabling a test for bitrig and openbsd

### LINKED ISSUE #24108: regression under openbsd: undefined reference to `_Unwind_Resume`
I have noted a regression in `make check` starting from 263fdfeea868dd086da3585ee6fe7d23993e66f8 (found with bisect).

the failing test is one of `doc-trpl-no-stdlib`. The fail occurs with stage1 and with stage2 (it have help a lot for bisect: only 50 min for 1 step of bisect)

I extract the example to a standalone file, and manually run rustc: the error is a linking error:
```
original.o(.text._ZN6option15Option$LT$T$GT$8and_then21h10563965396030871015E+0xa0): In function `option::Option$LT$T$GT$::and_then::h10563965396030871015': undefined reference to `_Unwind_Resume'
```

it seems -lgcc isn't passed by rustc, whereas the symbol `_Unwind_Resume` was present in `option::Option<T>::and_then`.

Any help would be appreciate.

### PR DESCRIPTION
**Pull request by dhuseby**
the code block in the no-stdlib.md file caused test failure on bitrig and openbsd.

Closes #24108

### CODE REVIEW

**Comment by dhuseby** [comment]
@semarie here's the PR.

**Comment by semarie** [comment]
Fixes #24108 
@dhuseby thanks.
