### ISSUE TITLE
faulty module resolution on `nightly 2019-04-12`

### ISSUE THREAD

**Issue by niklasad1** [rust-lang/rust#60011]
Hey, when I'm trying to build https://github.com/rust-rocksdb/rust-rocksdb/commit/ea770309c8ccf99e7e2d9be0194f476bbf008346 on `nightly 2019-04-12`

I get the following error (much more similar errors):

```bash
error[E0412]: cannot find type `rocksdb_t` in module `ffi`
  --> src/lib.rs:92:22
   |
92 |     inner: *mut ffi::rocksdb_t,
```

In `src/lib.rs` the following line exist:
`extern crate librocksdb_sys as ffi;`

Thus, I think `std::ffi` is used instead of `librocksdb_sys as ffi` 

Works fine on `stable`

**Comment by jonas-schievink** [comment]
Works fine on `rustc 1.35.0-nightly (2975a3c4b 2019-04-15)` for me, can you update your nightly and retry?

**Comment by jonas-schievink** [comment]
I cannot reproduce this even on `rustc 1.35.0-nightly (99da733f7 2019-04-12)` and `rustc 1.35.0-nightly (3de010678 2019-04-11)`. @niklasad1 can you write up how to reproduce this in more detail?

**Comment by niklasad1** [comment]
@jonas-schievink Thanks for investigating, you can find the dump [here](https://gist.github.com/niklasad1/5691405db68bba79f83ee7b89db0da55) (I don't know what I can provide more)

Well, I think my `rustc` installation is broken it failed to update this morning and when I specify the `toolchain` in the `rust-toolchain` it builds successfully and when I don't it doesn't build! 

However, it actually shows the correct checksum: `99da733f7`

**Comment by jonas-schievink** [comment]
@niklasad1 okay, in that case you might be able to fix this by just reinstalling rustup and the Rust toolchain then. Closing as a system issue.

If you manage to track this down to a rustup bug you can open an issue at https://github.com/rust-lang/rustup.rs/
