### PR TITLE
Don't highlight `let` expressions as having type `bool` in let-chain error messages

### LINKED ISSUE #147665: Diagnostics say that the `let` in let chains has type bool
### Code

```Rust
fn main() {
    if let x = 1 && 2 {}
}
```

### Current output

```Shell
error[E0308]: mismatched types
 --> src/main.rs:2:21
  |
2 |     if let x = 1 && 2 {}
  |        ---------    ^ expected `bool`, found integer
  |        |
  |        expected because this is `bool`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` (bin "playground") due to 1 previous error
```

### Desired output

```Shell

```

### Rationale and extra context

The compiler is saying that `let x = 1` has type `bool`, which doesn't make much sense.

### Other cases

```Rust

```

### Rust Version

```Shell
Reproducible on the playground with version: 1.92.0-nightly (2025-10-13 4b94758d2ba7d0ef71cc)
```

### Anything else?

Discovered by ashtree129 on the community discord.

### PR DESCRIPTION
**Pull request by pommicket**
Fixes rust-lang/rust#147665.

### CODE REVIEW

**Review by madsmtm — APPROVED** [review]
Tracing back a bit, this diagnostic was introduced in https://github.com/rust-lang/rust/pull/105192, which is before let chains, so it's reasonable to assume that it wasn't taken into account then.

The fix looks simple enough that I'm comfortable approving it even though I'm not that well-versed in this part of the codebase, thanks!

@bors r+ rollup

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/147738/28d0a4a205f9e511ad2f51ee79a4aa19a704a455..984542c4e229bbb5be070d1e276022f0b68513ec)*

**Comment by chenyukang** [comment]
Thanks!
I updated the PR description to use `Fixes` link the issue.
