### ISSUE TITLE
Regression in incremental compilation in rustc 1.14.0-nightly: `multiple definition of`

### ISSUE THREAD

**Issue by fkjogu** [rust-lang/rust#36852]
After updating from 1.13.0 nightlies to 1.14.0, using incremental compilation, my crate does not compile any more. Not sure, how to reduce this to a minimal example yet. A normal, non-incremental build works without problems.

This issue remains after `cargo clean` and removing the incremental compilation cache directory.

Here is the truncated log of a `env RUSTFLAGS="-Z incremental=.cache/ -A warnings" RUST_TEST_THREADS=1 cargo build --verbose`:
```
cat: cat: No such file or directory
     Running `rustc src/main.rs --crate-name simulation -g --test -C metadata=2cb208864766c980 -C extra-filename=-2cb208864766c980 --out-dir <path>/g/target/debug --emit=dep-info,link -L dependency=<path>/target/debug/deps --extern env_logger=<path>/target/debug/deps/libenv_logger-c716af707f2027e1.rlib --extern ndarray=<path>/target/debug/deps/libndarray-094ef2312f739d64.rlib --extern quickcheck=<path>/target/debug/deps/libquickcheck-515b6650caa2c559.rlib --extern rand=<path>/target/debug/deps/librand-49a08859d086fffe.rlib --extern log=<path>/target/debug/deps/liblog-bf16bb9a4912b11d.rlib --extern toml=<path>/target/debug/deps/libtoml-1a75b37a708f335b.rlib --extern mpi=<path>/target/debug/deps/libmpi-805ef1d96ee3a367.rlib --extern rustc_serialize=<path>/target/debug/deps/librustc_serialize-3561541d79c18212.rlib --extern fftw3=<path>/target/debug/deps/libfftw3.rlib --extern stochasticsampling=<path>/target/debug/deps/libstochasticsampling.rlib -Z incremental=.cache/ -A warnings -L native=<path>/target/debug/build/mpi-45137787103608a4/out -L native=<otherpath>/.local/mpich/lib`
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "<path>/g/target/debug/simulation-2cb208864766c980.simulation.o" "<path>/target/debug/simulation-2cb208864766c980.simulation-__test.o" "-o" "<path>/target/debug/simulation-2cb208864766c980" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "<path>/target/debug/deps" "-L" "<path>/target/debug/build/mpi-45137787103608a4/out" "-L" "<otherpath>/.local/mpich/lib" "-L" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "<path>/target/debug/deps/libstochasticsampling.rlib" "<path>/target/debug/deps/libtoml-1a75b37a708f335b.rlib" "<path>/target/debug/deps/libfftw3.rlib" "<path>/target/debug/deps/libndarray-094ef2312f739d64.rlib" "<path>/target/debug/deps/libmatrixmultiply-c99528890372b0f7.rlib" "<path>/target/debug/deps/libnum-1fa4854b44bb6a54.rlib" "<path>/target/debug/deps/libnum_complex-704ef091ce88b7b2.rlib" "<path>/target/debug/deps/libnum_iter-50df698bc905252c.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libtest-6eb85298.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libterm-6eb85298.rlib" "<path>/target/debug/deps/libmpi-805ef1d96ee3a367.rlib" "<path>/target/debug/deps/libnum_rational-7726582d22be0b52.rlib" "<path>/target/debug/deps/libnum_bigint-a144dbec313e5e23.rlib" "<path>/target/debug/deps/librustc_serialize-3561541d79c18212.rlib" "<path>/target/debug/deps/libitertools-42383a1bef75ce72.rlib" "<path>/target/debug/deps/libenv_logger-c716af707f2027e1.rlib" "<path>/target/debug/deps/liblog-bf16bb9a4912b11d.rlib" "<path>/target/debug/deps/librand-49a08859d086fffe.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libgetopts-6eb85298.rlib" "<path>/target/debug/deps/libconv-756d3d190d1196d1.rlib" "<path>/target/debug/deps/libnum_integer-52fdddf28cd8e924.rlib" "<path>/target/debug/deps/libcustom_derive-fc85df60b7fcbe53.rlib" "<path>/target/debug/deps/libregex-a99351f81f55a22d.rlib" "<path>/target/debug/deps/libutf8_ranges-5c6a6dacba3be7ce.rlib" "<path>/target/debug/deps/libregex_syntax-b3fc207b97c83ddf.rlib" "<path>/target/debug/deps/libthread_local-a3c0092e9fb6507d.rlib" "<path>/target/debug/deps/libaho_corasick-d1dfd931d7cac82f.rlib" "<path>/target/debug/deps/libmemchr-c555f740a543880f.rlib" "<path>/target/debug/deps/libnum_traits-92bb90166cd1857c.rlib" "<path>/target/debug/deps/libthread_id-bcd46c79a620a618.rlib" "<path>/target/debug/deps/liblibc-1417726cb94dbc83.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-6eb85298.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-6eb85298.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-6eb85298.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librand-6eb85298.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcollections-6eb85298.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-6eb85298.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc_jemalloc-6eb85298.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-6eb85298.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_unicode-6eb85298.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-6eb85298.rlib" "<otherpath>/.multirust/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-6eb85298.rlib" "-l" "fftw3" "-l" "fftw3" "-l" "mpi" "-l" "mpi" "-l" "util" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: <path>/g/target/debug/deps/libregex-a99351f81f55a22d.rlib(regex-a99351f81f55a22d.regex-re_bytes.o): In function `core::ops::FnOnce::call_once::h01f520c993dae163':
regex-re_bytes.rs:(.text._ZN4core3ops6FnOnce9call_once17h01f520c993dae163E+0x0): multiple definition of `core::ops::FnOnce::call_once::h01f520c993dae163'
<path>/g/target/debug/deps/libregex-a99351f81f55a22d.rlib(regex-a99351f81f55a22d.regex-re_unicode.o):regex-re_unicode.rs:(.text._ZN4core3ops6FnOnce9call_once17h01f520c993dae163E+0x0): first defined here
<path>/g/target/debug/deps/libregex-a99351f81f55a22d.rlib(regex-a99351f81f55a22d.regex-re_set-bytes.o): In function `core::ops::FnOnce::call_once::h01f520c993dae163':
regex-re_set-bytes.rs:(.text._ZN4core3ops6FnOnce9call_once17h01f520c993dae163E+0x0): multiple definition of `core::ops::FnOnce::call_once::h01f520c993dae163'
<path>/g/target/debug/deps/libregex-a99351f81f55a22d.rlib(regex-a99351f81f55a22d.regex-re_unicode.o):<home>.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.77/src/re_trait.rs:121: first defined here
<path>/g/target/debug/deps/libregex-a99351f81f55a22d.rlib(regex-a99351f81f55a22d.regex-re_set-unicode.o): In function `core::ops::FnOnce::call_once::h01f520c993dae163':
regex-re_set-unicode.rs:(.text._ZN4core3ops6FnOnce9call_once17h01f520c993dae163E+0x0): multiple definition of `core::ops::FnOnce::call_once::h01f520c993dae163'
<path>/g/target/debug/deps/libregex-a99351f81f55a22d.rlib(regex-a99351f81f55a22d.regex-re_unicode.o):<home>.cargo/registry/src/github.com-1ecc6299db9ec823/regex-0.1.77/src/re_trait.rs:121: first defined here
collect2: error: ld returned 1 exit status
```

## Meta

`rustc --version --verbose`:
```
rustc 1.14.0-nightly (86affcdf6 2016-09-28)
binary: rustc
commit-hash: 86affcdf6c622278a89b73bb7f1b8ac00e970888
commit-date: 2016-09-28
host: x86_64-unknown-linux-gnu
release: 1.14.0-nightly
```

**Comment by michaelwoerister** [comment]
This is likely an error in the codegen unit partitioning code.
Is the codebase in question available somewhere?

**Comment by michaelwoerister** [comment]
OK, I can reproduce when building tests for https://github.com/rust-lang-nursery/regex.

**Comment by michaelwoerister** [comment]
@fkjogu The latest nightly should contain a fix for this. Would you mind testing it against your codebase?

**Comment by fkjogu** [comment]
Can confirm it's fixed!
