### PR TITLE
Add Sized trait display when implemented on type

### LINKED ISSUE #24183: rustdoc: Self: Sized bounds in different crates are pruned
For example [`Iterator::map`](http://doc.rust-lang.org/std/iter/trait.Iterator.html#method.map) should have a `Self: Sized` bound, but we're a little too aggressive about pruning out the `Sized` bounds.

For comparison [`core::iter::Iterator::map`](http://doc.rust-lang.org/core/iter/trait.Iterator.html#method.map) does indeed have the bound.

### LINKED ISSUE #75413: Rustdoc: generated documentation doesn't include Sized
In generated Rustdoc documentation, it would make sense to show whether a type is `Sized` or not.

Looking at the documentation for [slice](https://doc.rust-lang.org/std/primitive.slice.html#synthetic-implementations) (which is !Sized) and [Cell](https://doc.rust-lang.org/std/cell/struct.Cell.html#synthetic-implementations) (which is Sized), we see no reference to `Sized` in either location.

DSTs may largely be second class citizens at the moment, but it would still be useful to surface this information in the docs.

As I see it, there's two options which make sense:
1. Simply show `Sized` on all Sized types.
2. Instead, show nothing on Sized types and show `!Sized` on non-Sized types.

The first option is more in line with the way that the rest of the traits are surfaced. but may be somewhat confusing (in that `Sized` is special because it's implied to be implemented, unless you specifically specify otherwise in trait bounds).

The second option is more in line with the way we think about `Sized` with respect to bounds, but also seems confusing in that negative trait bounds are not a supported feature.

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes https://github.com/rust-lang/rust/issues/24183.

I'm not too happy about the hack I had to add in here, however, it seems like the `Sized` trait is **very** special.

cc @jyn514 
r? @ollie27

### CODE REVIEW

**Comment by jyn514** [comment]
Oops, looks like triagebot got confused. @GuillaumeGomez I think you need to put `cc` after the `r?`?

r? @ollie27

**Comment by GuillaumeGomez** [comment]
ping

File: src/librustdoc/clean/auto_trait.rs [hunk 1]
```diff
@@ -32,113 +32,133 @@ impl<'a, 'tcx> AutoTraitFinder<'a, 'tcx> {
...
-                        polarity,
-                        synthetic: true,
-                        blanket_impl: None,
-                    }),
-                })
+                self.generate_for_trait(ty, trait_def_id, param_env, param_env_def_id)
             })
-            .collect()
+            .collect();
+        if ty.is_sized(self.cx.tcx.at(rustc_span::DUMMY_SP), param_env) {
```
Comment (jyn514) [inline src/librustdoc/clean/auto_trait.rs:152]: Can you get the span from `param_env_def_id`, maybe?

File: src/test/rustdoc/empty-section.rs [hunk 2]
```diff
@@ -2,12 +2,12 @@
 
 #![feature(negative_impls)]
 
-pub struct Foo;
+pub struct Foo<T: ?Sized>(T);
```
Comment (jyn514) [inline src/test/rustdoc/empty-section.rs:5]: Why did this change?

Comment (GuillaumeGomez) [reply src/test/rustdoc/empty-section.rs:5]: Because otherwise, the `Sized` trait impl will appear and make `// @!has - 'Auto Trait Implementations'` check fail.

File: src/librustdoc/clean/auto_trait.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/auto_trait.rs:152]: Is it important to have it?

**Comment by GuillaumeGomez** [comment]
Ok, seems to be ready!

**Comment by JohnCSimon** [comment]
triage: merge conflict

@Rustbot label: -S-waiting-on-review +S-waiting-on-author

**Comment by GuillaumeGomez** [comment]
It's still waiting for a review.

@rustbot label: -S-waiting-on-author +S-waiting-on-review

File: src/test/rustdoc/sized_trait.rs [hunk 3]
```diff
@@ -0,0 +1,15 @@
+#![crate_name = "foo"]
+
+// @has foo/struct.Bar.html
+// @has - '//h3[@id="impl-Sized"]' 'impl Sized for Bar'
```
Comment (jyn514) [inline src/test/rustdoc/sized_trait.rs:4]: This seems not super helpful. Almost all types implement `Sized`. I think it would be more helpful to only show `impl !Sized`, which is outside the ordinary.

Comment (GuillaumeGomez) [reply src/test/rustdoc/sized_trait.rs:4]: That's a good point. Just to confirm: what do you think @rust-lang/rustdoc ?

Comment (Manishearth) [reply src/test/rustdoc/sized_trait.rs:4]: Agreed

Comment (camelid) [reply src/test/rustdoc/sized_trait.rs:4]: Yeah, and if we change our mind we can always add `impl Sized for Bar` back later.

Comment (GuillaumeGomez) [reply src/test/rustdoc/sized_trait.rs:4]: Fine by me! Let's go for it then.

File: src/test/rustdoc/sized_trait.rs [hunk 4]
```diff
@@ -0,0 +1,15 @@
...
+pub struct Bar {
+    a: u16,
+}
+
+// @has foo/struct.Foo.html
+// @has - '//h3[@id="impl-Sized"]' 'impl<T> Sized for Foo<T>'
```
Comment (Nemo157) [inline src/test/rustdoc/sized_trait.rs:10]: Shouldn't this be `impl<T: Sized> Sized for Foo<T>`?

Comment (GuillaumeGomez) [reply src/test/rustdoc/sized_trait.rs:10]: The compiler assumes by default that the generics are `Sized` iiuc.

Comment (Nemo157) [reply src/test/rustdoc/sized_trait.rs:10]: Ah, yeah, in that case there should be a testcase for `struct Foo<T: ?Sized>(T);` too.

Comment (GuillaumeGomez) [reply src/test/rustdoc/sized_trait.rs:10]: Good idea. I'll add it when I'll make the update.

**Comment by GuillaumeGomez** [comment]
It now only displays in case the `Sized` trait isn't implemented.

File: src/librustdoc/clean/auto_trait.rs [hunk 5]
```diff
@@ -32,111 +32,132 @@ impl<'a, 'tcx> AutoTraitFinder<'a, 'tcx> {
...
-                })
+                self.generate_for_trait(ty, trait_def_id, param_env, param_env_def_id, false)
             })
-            .collect()
+            .collect();
+        if !ty.is_sized(self.cx.tcx.at(rustc_span::DUMMY_SP), param_env) {
+            // In case `#![no_core]` is used, `sized_trait` returns nothing.
+            if let Some(item) = self.cx.tcx.lang_items().sized_trait().and_then(|sized_trait_did| {
+                self.generate_for_trait(ty, sized_trait_did, param_env, param_env_def_id, true)
+            }) {
```
Comment (jyn514) [inline src/librustdoc/clean/auto_trait.rs:156]: Hmm, does it make sense to give an error here instead? I guess it doesn't really matter in practice, programs without `Sized` are basically useless.

```
> cat no_sized.rs 
#![feature(no_core, lang_items)]
#![no_core]
#![crate_type = "lib"]

fn f() {}
> rustc no_sized.rs 
error: requires `sized` lang_item
```

File: src/librustdoc/core.rs [hunk 6]
```diff
@@ -530,6 +531,16 @@ crate fn run_global_ctxt(
         module_trait_cache: RefCell::new(FxHashMap::default()),
         cache: Cache::default(),
     };
+
+    // Small hack to force the Sized trait to be present.
+    //
+    // Note that in case of `#![no_core]`, the trait is not available...
```
Comment (jyn514) [inline src/librustdoc/core.rs:537]:
```suggestion
    // Note that in case of `#![no_core]`, the trait is not available.
```

File: src/librustdoc/core.rs [hunk 7]
```diff
@@ -530,6 +531,16 @@ crate fn run_global_ctxt(
...
+    if let Some(sized_trait_did) = ctxt.tcx.lang_items().sized_trait() {
+        let mut sized_trait = build_external_trait(&ctxt, sized_trait_did);
+        sized_trait.is_auto = true;
+        ctxt.external_traits.borrow_mut().insert(sized_trait_did, sized_trait);
```
Comment (jyn514) [inline src/librustdoc/core.rs:541]: You have unique access to `ctxt`, you don't need to use interior mutability.
```suggestion
        ctxt.external_traits.get_mut().insert(sized_trait_did, sized_trait);
```

**Review by jyn514 — COMMENTED** [review]
Note this will have major conflicts with #82020, so you may want to wait to work on it more until that's merged.

File: src/librustdoc/clean/auto_trait.rs (hunk 5 above)
Comment (GuillaumeGomez) [reply src/librustdoc/clean/auto_trait.rs]: I don't think we should. It's not up to rustdoc.

File: src/librustdoc/core.rs (hunk 7 above)
Comment (GuillaumeGomez) [reply src/librustdoc/core.rs:541]:
```
error[E0596]: cannot borrow data in an `Rc` as mutable
   --> src/librustdoc/core.rs:541:9
    |
541 |         ctxt.external_traits.get_mut().insert(sized_trait_did, sized_trait);
    |         ^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable
```

**Comment by GuillaumeGomez** [comment]
Updated!

File: src/librustdoc/core.rs (hunk 7 above)
Comment (jyn514) [reply src/librustdoc/core.rs:541]: Oh boo, ok. I think @camelid was going to make a PR getting rid of the Rc sometime soon.

File: src/librustdoc/clean/auto_trait.rs [hunk 8]
```diff
@@ -29,6 +29,106 @@ impl<'a, 'tcx> AutoTraitFinder<'a, 'tcx> {
...
     }
 
+    fn generate_for_trait(
+        &mut self,
+        ty: Ty<'tcx>,
+        trait_def_id: DefId,
+        param_env: ty::ParamEnv<'tcx>,
+        param_env_def_id: DefId,
+        f: &auto_trait::AutoTraitFinder<'tcx>,
+        discard_positive_impl: bool,
```
Comment (jyn514) [inline src/librustdoc/clean/auto_trait.rs:39]:
```suggestion
        // If this is set, show only negative trait implementations, not positive ones.
        discard_positive_impl: bool,
```

**Review by jyn514 — COMMENTED** [review]
This looks good :) r=me with nit fixed, it took me a second to understand the code the first time.

**Comment by GuillaumeGomez** [comment]
> it took me a second to understand the code the first time.

Oh sorry, I tried to make the parameter name as explicit as possible but I realize that some comments would have make it much better. I added another one in addition to the one you suggested. :)

File: src/librustdoc/core.rs (hunk 7 above)
Comment (camelid) [reply src/librustdoc/core.rs:541]: This one is hard to get rid of because it's shared between `DocContext` and `clean::Crate`. `clean::Crate` only seems to use it as a bridge between `DocContext` and `Cache`

https://github.com/rust-lang/rust/blob/9b471a3f5fe57e5c6e08acf665f2094422415a3d/src/librustdoc/clean/types.rs#L58-L60

`Cache` then `take`s the data

https://github.com/rust-lang/rust/blob/master/src/librustdoc/formats/cache.rs#L164

I think we'll need bigger architectural changes, like passing the field directly to `Cache`, in order to get rid of the intermediary. Doing that should make the code clearer and reduce the potential for sneaky bugs like giving the field to `Cache` via `Crate` and then trying to use the `DocContext` version later and finding nothing in it.
