### PR TITLE
Fixed E0528 label and unit test

### LINKED ISSUE #36194: E0528 needs to be updated to new format
From: src/test/compile-fail/E0528.rs

E0528 needs a span_label, updating it from:

```
error[E0528]: pattern requires at least 3 elements but array has 2
  --> src/test/compile-fail/E0528.rs:16:10
   |
16 |         &[a, b, c, rest..] => { //~ ERROR E0528
   |          ^^^^^^^^^^^^^^^^^
```

To:

```
error[E0528]: pattern requires at least 3 elements but array has 2
  --> src/test/compile-fail/E0528.rs:16:10
   |
16 |         &[a, b, c, rest..] => { //~ ERROR E0528
   |          ^^^^^^^^^^^^^^^^^ pattern cannot match array of 2 elements
```

### PR DESCRIPTION
**Pull request by EugeneGonzalez**
Fixes #36194 part of #35233.

r? @jonathandturner

### CODE REVIEW

**Comment by EugeneGonzalez** [comment]
@jonathandturner this is ready for review. Travis-CI failed because of #36138.

**Comment by jonathandturner** [comment]
Looks good.

@bors r+ rollup
