### PR TITLE
Fix into() cast paren check precedence

### LINKED ISSUE #47699: Add parenthesis around suggestions to use `.into()` on cast expr
[Given the following code](https://play.rust-lang.org/?gist=e697723431394a15eaaba4681653f1d1&version=nightly):

```
fn main() {
    let array = [1, 2, 3];
    test(array.len() as u8);
}

fn test(length: u32) {
    println!("{}", length);
}
```

rustc suggests

```
error[E0308]: mismatched types
 --> src/main.rs:3:10
  |
3 |     test(array.len() as u8);
  |          ^^^^^^^^^^^^^^^^^ expected u32, found u8
help: you can cast an `u8` to `u32`, which will zero-extend the source value
  |
3 |     test(array.len() as u8.into());
  |          ^^^^^^^^^^^^^^^^^^^^^^^^
```

The suggestion should be enclosing the entire expression in parenthesis.

This was introduced in #47247. The solution is to change [`needs_paren`](https://github.com/rust-lang/rust/pull/47247/files#diff-124df07081a1185b5a4d40cdcf0cf4ffR339) to be inclusive of the precedence of `as`, in other words, change the `<` with `<=` and add a test for the behavior.

### PR DESCRIPTION
**Pull request by etaoins**
As discussed in #47699 the logic for determining if an expression needs parenthesis when suggesting an `.into()` cast is incorrect. Two broken examples from nightly are:

```
error[E0308]: mismatched types
 --> main.rs:4:10
  |
4 |     test(foo as i8);
  |          ^^^^^^^^^ expected i32, found i8
help: you can cast an `i8` to `i32`, which will sign-extend the source value
  |
4 |     test(foo as i8.into());
  |
```

```
error[E0308]: mismatched types
 --> main.rs:4:10
  |
4 |     test(*foo);
  |          ^^^^ expected i32, found i8
help: you can cast an `i8` to `i32`, which will sign-extend the source value
  |
4 |     test(*foo.into());
  |
```

As suggested by @petrochenkov switch the precedence check to `PREC_POSTFIX`. This catches both `as` and unary operators. Fixes #47699.

r? @petrochenkov

### CODE REVIEW

**Comment by petrochenkov** [comment]
@bore r+ rollup

**Comment by petrochenkov** [comment]
@etaoins 
>As suggested by @petrochenkov switch the precedence check to
`PREC_POSTFIX`

A small remark - it's better to avoid @mentioning people in commit descriptions because it will may generate quite a few unwanted email notification while the commit passes through CI, especially with rollups.

**Comment by kennytm** [comment]
@petrochenkov That's the PR description copied to the commit message by bors though...

**Comment by petrochenkov** [comment]
@kennytm 
Hmm, maybe bors should remove `@`s before copying the message?
I often manually remove "r? me"s from PR descriptions assigned to me (but often forget) because they generate unwanted notifications too.
