### PR TITLE
Avoid duplicating StorageLive in let-else

### LINKED ISSUE #101867: `miri` no longer builds after rust-lang/rust#101410
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#101410, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @dingxiangfei2009, do you think you would have time to do the follow-up work?
If so, that would be great!

### LINKED ISSUE #101932: `StorageLive already live` in const `let else` regression
I tried this code:

```rust
#![feature(let_else)]

const fn foo(a: Option<i32>) -> i32 {
    let Some(a) = a else {
        return 42
    };
    
    a + 1
}

fn main() {
    const A: i32 = foo(None);
    const B: i32 = foo(Some(1));

    println!("{} {}", A, B);
}
```

I expected to see this happen: The code should compile and print "42 2".

Instead, this happened: The evaluation of the constant `B` fails with `StorageLive on a local that was already live`.

This code last compiled with `nightly-2022-09-15-x86_64-unknown-linux-gnu (750bd1a7f 2022-09-14)` and first failed with `nightly-2022-09-16-x86_64-unknown-linux-gnu (cf9ed0dd5 2022-09-15)`.

### Meta

`rustc --version --verbose`:
```
rustc 1.65.0-nightly (95a992a68 2022-09-16)
binary: rustc
commit-hash: 95a992a68694d8bf3959bd2c0ac27ce9e9208b59
commit-date: 2022-09-16
host: x86_64-unknown-linux-gnu
release: 1.65.0-nightly
LLVM version: 15.0.0
```

<details><summary>Backtrace</summary>
<p>

```
error[E0080]: evaluation of constant value failed
  --> main.rs:4:14
   |
4  |     let Some(a) = a else {
   |              ^
   |              |
   |              StorageLive on a local that was already live
   |              inside `foo` at main.rs:4:14
...
13 |     const B: i32 = foo(Some(1));
   |                    ------------ inside `B` at main.rs:13:20

error: aborting due to previous error

For more information about this error, try `rustc --explain E0080`.
```

</p>
</details>

### PR DESCRIPTION
**Pull request by dingxiangfei2009**
cc @est31 

Fix #101867
Fix #101932

#101410 introduced directives to activate storages of bindings in let-else earlier. However, since it is using the machinery of `match` and friends for pattern matching and binding, those storages are activated for the second time. This PR adjusts this behavior and avoid the duplicated activation for let-else statements.

### CODE REVIEW

**Comment by dingxiangfei2009** [comment]
`./x.py test src/tools/miri` is now passing again after this change. You may try it out.

**Comment by oli-obk** [comment]
Please also add a mir-opt test. https://github.com/rust-lang/rust/pull/101410#issuecomment-1248806073 seems like a good candidate as it is very minimal.

File: compiler/rustc_mir_build/src/build/matches/mod.rs [hunk 1]
```diff
@@ -416,6 +417,7 @@ impl<'a, 'tcx> Builder<'a, 'tcx> {
         arm_span: Option<Span>,
         arm_scope: Option<region::Scope>,
         match_scope: Option<region::Scope>,
+        storages_alive: bool,
```
Comment (oli-obk) [inline compiler/rustc_mir_build/src/build/matches/mod.rs:420]: Not your fault, but the arguments to this function are getting out of hand. Not sure what to do here, but doesn't need to happen in this PR.

**Comment by Mark-Simulacrum** [comment]
Preemptively beta-nominating for backport to 1.65 (into which https://github.com/rust-lang/rust/pull/101410 landed), since it seems likely this would otherwise only make 1.66.

**Comment by dingxiangfei2009** [comment]
@oli-obk Thank you! I have added that test mentioned in the #101410 thread. I have tentatively selected `mir_map` which is hopefully very close to the original MIR generated. Please advise better choices. :pray:

**Comment by est31** [comment]
@dingxiangfei2009 now that #93628 has been merged, can you rebase this PR? Most importantly, the test files will need `#![cfg_attr(bootstrap, feature(let_else))]`, instead of `#![feature(let_else)]`.

Also, would it be possible to add the example from #101932 as a run-pass regression test? So add `// run-pass` to it as well as `// issue #101932`, and put it e.g. into `src/test/ui/let-else/const-fn.rs`.

**Comment by dingxiangfei2009** [comment]
@est31 branch rebased with the test case from #101932 

cc @oli-obk for the relevant changes.

**Comment by RalfJung** [comment]
This issue is completely blocking Miri development, would be good to get the fix landed ASAP. :)

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://blog.rust-lang.org/2022/09/22/Rust-1.64.0.html)

@rustbot label +beta-accepted

**Comment by RalfJung** [comment]
Judging from [this](https://forge.rust-lang.org/release/backporting.html?highlight=beta#beta-backporting-in-rust-langrust) the release team will do the beta backports so I consider this done from my end now. :)
