### ISSUE TITLE
Regression in clone impl of enum with variant that has a field with a bivariant substitution

### ISSUE THREAD

**Issue by compiler-errors** [rust-lang/rust#129286]
I tried this code:

```rust
trait Array {
    type Item;
}

trait Platform {
    type Assoc: Array<Item = Self::Assoc2>;
    type Assoc2;
}

struct Message<A, B>
where
    A: Array<Item = B>,
{
    pub field: A,
}

impl<A, B> Clone for Message<A, B>
where
    A: Array<Item = B>,
{
    fn clone(&self) -> Self {
        todo!()
    }
}

fn clone<P: Platform>(x: &Message<P::Assoc, P::Assoc2>) {
    let x: Message<_, _> = Clone::clone(x);
}
```

I expected it to work.

Instead, this happened: 

```
error[E0282]: type annotations needed
  --> src/lib.rs:31:32
   |
31 |     Enum::Variant(Clone::clone(x))
   |                                ^ cannot infer type for reference `&Message<<P as Platform>::Assoc, _>`
```

I regressed this in #129059. I have no idea yet why it's happening! This also could be minimized further, I think.

**Comment by compiler-errors** [comment]
Weirdly, this also only happens when the `Clone::clone` call is being directly passed to `Enum::Variant`. Is this due to `Expectation`, perhaps?

**Comment by compiler-errors** [comment]
https://github.com/rust-lang/rust/blob/79611d90b6b3fc6f17a0b07ba228b28e89de16e3/compiler/rustc_hir_typeck/src/fn_ctxt/checks.rs#L299-L305

lol we're not actually constraining the target of the coercion properly

**Comment by compiler-errors** [comment]
Minimal:

```
trait Trait {
    type Item;
}

struct Struct<A: Trait<Item = B>, B> {
    pub field: A,
}

fn identity<T>(x: T) -> T {
    x
}

fn test<A: Trait<Item = B>, B>(x: &Struct<A, B>) {
    let x: &Struct<_, _> = identity(x);
}
```
