### ISSUE TITLE
Confusing "the caller chooses a type which can be different" [E308]

### ISSUE THREAD

**Issue by jendrikw** [rust-lang/rust#126547]
### Code

```Rust
fn f<T>(t: &T) -> T {
    t
}
```

### Current output

```Shell
error[E0308]: mismatched types
 --> src/lib.rs:2:5
  |
1 | fn f<T>(t: &T) -> T {
  |      -            - expected `T` because of return type
  |      |
  |      expected this type parameter
2 |     t
  |     ^ expected type parameter `T`, found `&T`
  |
  = note: expected type parameter `_`
                  found reference `&_`
  = note: the caller chooses a type for `T` which can be different from `&T`
```

### Desired output

```Shell
error[E0308]: mismatched types
 --> src/lib.rs:2:5
  |
1 | fn f<T>(t: &T) -> T {
  |      -            - expected `T` because of return type
  |      |
  |      expected this type parameter
2 |     t
  |     ^ expected type parameter `T`, found `&T`
  |
  = note: expected type parameter `_`
                  found reference `&_`
```

### Rationale and extra context

The statement "the caller chooses a type for `T` which can be different from `&T`" is confusing because `T` and `&T` *are* *always* different. I think it would be best to supress that note when the types only differ in reference-ness. The message was introduced in #122195.

### Rust Version

```Shell
rustc 1.81.0-nightly (3cf924b93 2024-06-15)
binary: rustc
commit-hash: 3cf924b934322fd7b514600a7dc84fc517515346
commit-date: 2024-06-15
host: x86_64-unknown-linux-gnu
release: 1.81.0-nightly
LLVM version: 18.1.7
```

**Comment by fmease** [comment]
Thanks, that message definitely doesn't make sense.
CC @jieyouxu (#122195). When I suggested you to move `note_caller_chooses_ty_for_ty_param` out of `try_suggest_return_impl_trait` [here](https://github.com/rust-lang/rust/pull/122195/files#r1518186556) to be catch more cases that was a bit too aggressive — that's on me. We should replicate some parts of `try_suggest_return_impl_trait`, namely checking that the type param in question does not occur in the return expression type. That did cross my mind back then but I didn't really follow up on that though for some reason.

**Comment by jieyouxu** [comment]
Thanks for the cc @fmease, I'll take a look ~today/tomorrow

**Comment by jieyouxu** [comment]
Opened #126558 to suppress the note if found return type contains the expected return type (type parameter).
