### ISSUE TITLE
[1.31 beta] Trait bound is not satisfied

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54467]
The following crates fail to build on `1.30` due to trait bound errors.

* [combine-language](https://crates.io/crates/combine-language) `3.0.1` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/combine-language-3.0.1/log.txt)) cc @Marwes
* [postgis](https://crates.io/crates/postgis) `0.6.0` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/postgis-0.6.0/log.txt)) cc @andelf
  * [vectortile](https://crates.io/crates/vectortile) `0.2.1` (depends on `postgis`) regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/vectortile-0.2.1/log.txt)) cc @kestred

**Comment by Marwes** [comment]
For combine it seems like rustc no longer sees that `I::Item == char` despite that being specified in the `where` bound :/

```
error[E0277]: the trait bound `<I as combine::StreamOnce>::Error: combine::ParseError<char, <I as combine::StreamOnce>::Range, <I as combine::StreamOnce>::Position>` is not satisfied
Sep 21 16:12:45.476 INFO kablam!    --> src/lib.rs:163:1
Sep 21 16:12:45.476 INFO kablam!     |
Sep 21 16:12:45.476 INFO kablam! 163 | / pub struct Reserved<'a: 'b, 'b, I>
Sep 21 16:12:45.476 INFO kablam! 164 | | where
Sep 21 16:12:45.476 INFO kablam! 165 | |     I: Stream<Item = char> + 'b,
Sep 21 16:12:45.476 INFO kablam! 166 | |     I::Error: ParseError<I::Item, I::Range, I::Position>,
Sep 21 16:12:45.477 INFO kablam! 167 | | {
Sep 21 16:12:45.477 INFO kablam! 168 | |     parser: Lex<'a, 'b, Try<Skip<Str<I>, NotFollowedBy<LanguageParser<'a, 'b, I, char>>>>>,
Sep 21 16:12:45.477 INFO kablam! 169 | | }
Sep 21 16:12:45.477 INFO kablam!     | |_^ the trait `combine::ParseError<char, <I as combine::StreamOnce>::Range, <I as combine::StreamOnce>::Position>` is not implemented for `<I as combine::StreamOnce>::Error`
```

**Comment by arielb1** [comment]
This looks like a "soft" deadlock on `normalize_param_env_or_error` caused by implied bounds.

Minified:
```Rust
pub trait Stream {
    type Item;
    type Error;
}

pub trait ParseError<I> {
    type Output;
}

pub struct Lex<'a, I>
    where I: Stream,
          I::Error: ParseError<char>,
          <<I as Stream>::Error as ParseError<char>>::Output: 'a
{
    x: &'a <I::Error as ParseError<char>>::Output
}

pub struct Reserved<'a, I> where
    I: Stream<Item=char> + 'a,
    I::Error: ParseError<I::Item>
{
    x: Lex<'a, I>
}

fn main() {}
```

**Comment by arielb1** [comment]
to detail: `normalize_param_env_or_error` does not try to normalize the param env in some sort of fixed-point computation - that would be hard without lazy normalization or some other major refactor of the trait system. Therefore, it normalizes the param env insided the unnormalized param env.

This means that bounds such as `<<I as Stream>::Error as ParseError<char>>::Output: 'a` are normalized in the unnormalized param env, which contains `I::Error: ParseError<I::Item>,` instead of `I::Error: ParseError<char>,`.

**Comment by arielb1** [comment]
Note that this is broken even on older nightlies as long as `#![feature(infer_outlives_requirements)] ` is enabled.

**Comment by arielb1** [comment]
I'll try to get a fix done later this week.

**Comment by pnkfelix** [comment]
visited at T-compiler. P-high.

**Comment by pnkfelix** [comment]
My understanding is that this is resolved by #54877

**Comment by Mark-Simulacrum** [comment]
Interestingly, this is not fixed on current beta (or perhaps re-regressed); I'm reopening and retagging.

Specifically at least postgis is failing to build: https://crater-reports.s3.amazonaws.com/beta-1.31-1/beta-2018-10-30/reg/vectortile-0.2.2/log.txt

**Comment by Mark-Simulacrum** [comment]
cc @arielb1 @pnkfelix @rust-lang/compiler

**Comment by pnkfelix** [comment]
Maybe we need to reconsider backporting PR #54701 ... will investigate...

**Comment by nikomatsakis** [comment]
### Test results

postgis 0.6.0

- ❌ nightly (2018-11-13)
- ❌ beta (1.31.0-beta.9)
- ✅ stable (1.30.1)

combine-language 3.0.1:

- ✅  nightly (2018-11-13)
- ✅  beta (1.31.0-beta.9)
- ✅ stable (1.30.1)

**Comment by nikomatsakis** [comment]
Seems like postgis-0.6.0 simply wasn't fixed.

**Comment by nikomatsakis** [comment]
Trying to investigate more deeply. (Also, I realize now that @Mark-Simulacrum this is likely the issue you were talking about when you were talking about re-regressing..?)
