### ISSUE TITLE
Regression in diagnostic quality for unimplemented traits on arrays.

### ISSUE THREAD

**Issue by BGR360** [rust-lang/rust#92113]
Commit dcd716fee2303c93a0bf1ba68e667c9bc4bf3558 (https://github.com/rust-lang/rust/pull/86986) appears to have regressed the quality of compiler diagnostics produced when an array type does not satisfy a trait but its slice version does (there may be other scenarios that see similar regressions, but this is where I've seen it).

This is currently blocking https://github.com/rust-lang/rust/pull/91314.

Motivating example ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c9f9bb3a828c28cc18c6591d545fb5db)):

```rust
trait Read {}

impl Read for &[u8] {}

fn wants_read(_: impl Read) {}

fn main() {
    wants_read([0u8]);
}
```

When compiled on dcd716fee2303c93a0bf1ba68e667c9bc4bf3558~1 (83b32f27fc6c34b0b411f47be31ab4ae07eafed4), rustc provides a help message telling the user that the trait is implemented for slices:

```
error[E0277]: the trait bound `[u8; 1]: Read` is not satisfied
 --> ../scratch/issue-90528-unsizing-suggestion-1.rs:8:16
  |
8 |     wants_read([0u8]);
  |     ---------- ^^^^^ the trait `Read` is not implemented for `[u8; 1]`
  |     |
  |     required by a bound introduced by this call
  |
  = help: the following implementations were found:
            <&[u8] as Read>
note: required by a bound in `wants_read`
 --> ../scratch/issue-90528-unsizing-suggestion-1.rs:5:23
  |
5 | fn wants_read(_: impl Read) {}
  |                       ^^^^ required by this bound in `wants_read`
```

Compiled on dcd716fee2303c93a0bf1ba68e667c9bc4bf3558, this help message no longer appears:

```
error[E0277]: the trait bound `[u8; 1]: Read` is not satisfied
 --> ../scratch/issue-90528-unsizing-suggestion-1.rs:8:16
  |
8 |     wants_read([0u8]);
  |     ---------- ^^^^^ the trait `Read` is not implemented for `[u8; 1]`
  |     |
  |     required by a bound introduced by this call
  |
note: required by a bound in `wants_read`
 --> ../scratch/issue-90528-unsizing-suggestion-1.rs:5:23
  |
5 | fn wants_read(_: impl Read) {}
  |                       ^^^^ required by this bound in `wants_read`
```

Inspiration for regression tests can be taken from https://github.com/rust-lang/rust/pull/91314.

@rustbot modify labels: +A-diagnostics +T-compiler +D-terse

cc @lcnr

**Comment by lcnr** [comment]
While I think mentioning `<&[u8] as Read>` here is useful, I do not believe that reverting the change in #86986 is the right fix here.

I think that we could actually change these diagnostics to more generally deal with stuff like deref impls by explicitly looking for potential impls instead of looking at the existing impl candidates.

So when encountering a "trait bound is not satisfied" error for some type `T`, we look at impls for type `&T`, `&mut T` and `[U]` (if `T = [U; N]`) and then mention these impls with a note like "considering using a reference".

Do you want to look at this yourself, if not I should hopefully be able to make some time for this over the next few weeks

cc @estebank

**Comment by BGR360** [comment]
> I do not believe that reverting the change in #86986 is the right fix here.

Certainly not. I'm a little bummed that the work I did in https://github.com/rust-lang/rust/pull/91314 is kaput, but I agree with you.

> explicitly looking for potential impls instead of looking at the existing impl candidates

I like that idea, but it seems like we're lacking tests to tell us what else might have lost information as a result of https://github.com/rust-lang/rust/pull/86986, which will make it harder to know exactly which types of potential impls we should look for. The work I was doing in https://github.com/rust-lang/rust/pull/91314 obviously tells us one category of potential impls we need to check: `[U]` if `T = [U; N]`, but how can we . I'll have to lean on your understanding of the work you did; perhaps you just know 

> Do you want to look at this yourself

I _was_ just poking around in there, but this seems like a larger time commitment compared to the very directed suggestion generation of https://github.com/rust-lang/rust/pull/91314.

With guidance, I'd be happy to try out doing just the `[U; N] -> [U]` searching, and seeing how it goes from there. My main worry is that it sounds like this may not be something we've done before in `rustc_trait_selection` (that is, constructing a new type and querying for impls on that type). But if there is an example you can point me to, then that would probably make it a lot easier.

@rustbot label +A-traits

**Comment by lcnr** [comment]
alright :+1: i also believe that we aren't doing anything like that, but i think the required changes won't be too large. Going to write some instructions this week, feel free to ping me either here or on zulip in case i forget

**Comment by lcnr** [comment]
so, we collect the impl candidates in https://github.com/rust-lang/rust/blob/e100ec5bc7cd768ec17d75448b29c9ab4a39272b/compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs#L1440-L1443

The reason we don't consider slice impls anymore is this comparision
https://github.com/rust-lang/rust/blob/e100ec5bc7cd768ec17d75448b29c9ab4a39272b/compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs#L1471-L1473

we want some fuzzy equality here instead of comparing their simplified types. How exactly that fuzzy equality should work requires a bit of fiddling so that's something you probably just have to experiment with yourself. I would expect that directly using `Ty` here is better than using `SimplifiedType`s. It should end up looking similar to https://github.com/rust-lang/rust/blob/e100ec5bc7cd768ec17d75448b29c9ab4a39272b/compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs#L1389 which you can probably just use (after modifying it a bit) :sweat_smile:

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2392113.20Regression.20in.20diagnostic.20quality.20for.20unimplemented.20t.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-low

**Comment by BGR360** [comment]
This is fixed on stable. Not sure exactly what fixed it, but I suspect https://github.com/rust-lang/rust/pull/93298.

```
error[E0277]: the trait bound `[u8; 1]: Read` is not satisfied
 --> src/main.rs:8:16
  |
8 |     wants_read([0u8]);
  |     ---------- ^^^^^ the trait `Read` is not implemented for `[u8; 1]`
  |     |
  |     required by a bound introduced by this call
  |
  = help: the trait `Read` is implemented for `&[u8]`
note: required by a bound in `wants_read`
 --> src/main.rs:5:23
  |
5 | fn wants_read(_: impl Read) {}
  |                       ^^^^ required by this bound in `wants_read`
```
