### ISSUE TITLE
Static lifetimes checking regression in rustc 1.41.0

### ISSUE THREAD

**Issue by ilyavenner** [rust-lang/rust#69114]
I tried [this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=551de68b1179d7eb692e6c286b0979da):

```rust
static FOO: u8 = 42;
static mut BAR: &'static u8 = &FOO;

fn main() {
    unsafe {
        println!("{}", BAR);
        foo();
        println!("{}", BAR);
    }
}

fn foo() {
    let n = 42;
    unsafe {
        BAR = &n;
    }
}
```

I expected to see this:

```
error[E0597]: `n` does not live long enough
  --> src/main.rs:15:15
   |
15 |         BAR = &n;
   |         ------^^
   |         |     |
   |         |     borrowed value does not live long enough
   |         assignment requires that `n` is borrowed for `'static`
16 |     }
17 | }
   | - `n` dropped here while still borrowed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0597`.
```

Instead, happens **undefined behavior**. Program successfully compiles in the Rust `stable 1.41.0` but fails to compile in `stable 1.40.0` (thats what I want).

**Comment by ecstatic-morse** [comment]
Regressed in a449535bbc7912c4adc1bbf2ab2738d0442f212c, likely #66587 cc @matthewjasper.

**Comment by nikomatsakis** [comment]
Visited in the compiler team triage meeting. It would be good to look into closing this ASAP. @matthewjasper do you think you'll have time to investigate? If not, I'd want to find someone else.

**Comment by nikomatsakis** [comment]
We've assigned this speculatively to @matthewjasper -- if you think you won't be able to investigate promptly, though, feel free to unassign and ping t-compiler for reassignment, @matthewjasper.

**Comment by eddyb** [comment]
I expected the behavior to match that of this example (which still errors):
```rust
fn foo(p: *mut &'static u8) {
    let n = 42;
    unsafe {
        *p = &n;
    }
}
```
I wonder if the `'static` gets erased somehow. Maybe an "user type annotation" is required on the `*mut T` from a `static mut FOO: T`, to give it a lifetime'd type?
