### ISSUE TITLE
Const generics and structural match.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#71415]
Not sure whether this has been reported before.
I tried this code:

```rust
#![feature(const_generics)]
#![feature(structural_match)]

use std::marker::{StructuralPartialEq, StructuralEq};

struct Container<T: StructuralPartialEq + StructuralEq, const V: T>;

fn main() {
    let container1: Container<i32, {42}> = Container;
    let container2: Container<&'static str, "Hello world"> = Container;
}

```

I expected to see this happen:  The compile passes.

Instead, this happened:
```text
error[E0741]: the types of const generic parameters must derive `PartialEq` and `Eq`
 --> src/main.rs:6:66
  |
6 | struct Container<T: StructuralPartialEq + StructuralEq, const V: T>;
  |                                                                  ^ `T` doesn't derive both `PartialEq` and `Eq`
```
### Meta

`rustc --version --verbose`:
```
Nightly channel
Build using the Nightly version: 1.44.0-nightly

(2020-04-21 45d050cde277b22a7558)
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

@rustbot modify labels to +A-const generics F-const generics T-compiler requires-nightly

**Comment by crlf0710** [comment]
```rust
#![feature(const_generics)]
#![feature(structural_match)]

use std::marker::{StructuralPartialEq, StructuralEq};

struct Container<T: StructuralPartialEq + StructuralEq + PartialEq + Eq, const V: T>;

fn main() {
    let container1: Container<i32, {42}> = Container;
    let container2: Container<&'static str, "Hello world"> = Container;
}
```
This also doesn't work.

**Comment by varkor** [comment]
I'm pretty sure `StructuralPartialEq` and `StructuralEq` are not supposed to be public like this… it's not valid to claim that an arbitrary type is `structural_match`. I don't expect this to work.

cc @pnkfelix @eddyb

**Comment by lcnr** [comment]
We don't allow const paramters with generic types at all afaik. So while the error message is misleading, I don't think that this will work soon.

**Comment by varkor** [comment]
> We don't allow const paramters with generic types at all afaik. So while the error message is misleading, I don't think that this will work soon.

Right, this will actually be improved by https://github.com/rust-lang/rust/pull/70845, which makes this explicit.

**Comment by crlf0710** [comment]
Thanks. Is this a language limitation or implementation limitation? Will lazy normalization allow this to be written?

**Comment by varkor** [comment]
It won't be supported after lazy normalisation specifically, but we would like to be able to use const parameters with generic types eventually.

**Comment by vmarkushin** [comment]
Also consider [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=59dec1bc6a73dac68eb014bcfaa9f112) example
```
#![feature(const_generics)]

#[derive(PartialEq, Eq)]
enum Nat {
    Z,
    S(Box<Nat>)
}

fn foo<const N: Nat>() {}
```

**Comment by lcnr** [comment]
@vmarkushin can you open a separate issue for this as your example seems distinct enough to be tracked separately?

**Comment by vmarkushin** [comment]
@lcnr, of course. I will.
