### PR TITLE
build llvm with systemz backend enabled, and link to related libraries

### LINKED ISSUE #36077: Travis is failing ("undefined reference to LLVMInitializeSystemZ*")
Excerpt from a recent travis build:

```
  = note: /build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-836a4172.so: undefined reference to `LLVMInitializeSystemZTargetInfo'
/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-836a4172.so: undefined reference to `LLVMInitializeSystemZTargetMC'
/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-836a4172.so: undefined reference to `LLVMInitializeSystemZAsmParser'
/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-836a4172.so: undefined reference to `LLVMInitializeSystemZTarget'
/build/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-836a4172.so: undefined reference to `LLVMInitializeSystemZAsmPrinter'
collect2: error: ld returned 1 exit status
```

These symbols were introduced in #36028.

cc @japaric

### PR DESCRIPTION
**Pull request by japaric**
when building rust against system llvm

closes #36077

r? @alexcrichton

### CODE REVIEW

File: src/rustllvm/PassWrapper.cpp [hunk 1]
```diff
@@ -131,12 +131,19 @@ LLVMRustAddPass(LLVMPassManagerRef PM, LLVMPassRef rust_pass) {
 #define SUBTARGET_PPC
 #endif
 
+#ifdef LLVM_COMPONENT_SYSTEMZ
```
Comment (japaric) [inline src/rustllvm/PassWrapper.cpp]: > link to related libraries when building rust against system llvm

this fixes the travis builds. We could add a build slave that tests building rust against system llvm to avoid these in the future

Comment (japaric) [inline src/rustllvm/PassWrapper.cpp]: > build slave

I meant bors. Travis doesn't block PRs.

File: configure [hunk 2]
```diff
@@ -1747,7 +1747,7 @@ do
         CMAKE_ARGS="$CMAKE_ARGS -DLLVM_ENABLE_ASSERTIONS=ON"
     fi
 
-    CMAKE_ARGS="$CMAKE_ARGS -DLLVM_TARGETS_TO_BUILD='X86;ARM;AArch64;Mips;PowerPC'"
+    CMAKE_ARGS="$CMAKE_ARGS -DLLVM_TARGETS_TO_BUILD='X86;ARM;AArch64;Mips;PowerPC;SystemZ'"
```
Comment (japaric) [inline configure]: > build llvm with systemz backend enabled

I'm not sure why bors didn't catch this... Are all the build slaves using rustbuild now?

**Comment by japaric** [comment]
cc @TimNN

File: configure (hunk 2 above)
Comment (alexcrichton) [inline configure]: Hm no there's still many slaves using the makefiles. I thought we had enough support though to work with an LLVM that was missing some targets...

**Comment by alexcrichton** [comment]
Thanks @japaric! I'll wait to r+ until travis is green
