### PR TITLE
const-eval: allow calling functions with targat features disabled at compile time in WASM

### LINKED ISSUE #116516: `#[target_feature(enable = "simd128")]` does not work properly on 1.73, but work fine on 1.72.1
### Code

I tried this code on 1.73:

```rust
use std::arch::wasm32::*;

#[target_feature(enable = "simd128")]
fn foo() {
	const FOO: v128 = i8x16(0, 1, -1, -1, -1, -1, -1, -1, 2, 3, -1, -1, -1, -1, -1, -1);
	println!("{:?}", FOO);
}

fn main() {
    foo();
}
```

Compiled it with `cargo build --target=wasm32-unknown-unknown`, I expected it to compile fine as on previous 1.72.1, but it gave me these errors:

```shell
$ cargo build --target=wasm32-unknown-unknown
   Compiling regression_test v0.1.0 (C:\Users\123\Desktop\regression_test)
error[E0080]: evaluation of constant value failed
 --> src\main.rs:5:20
  |
5 |     const FOO: v128 = i8x16(0, 1, -1, -1, -1, -1, -1, -1, 2, 3, -1, -1, -1, -1, -1, -1);
  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ calling a function that requires unavailable target features: simd128

note: erroneous constant used
 --> src\main.rs:6:19
  |
6 |     println!("{:?}", FOO);
  |                      ^^^

note: erroneous constant used
 --> src\main.rs:6:19
  |
6 |     println!("{:?}", FOO);
  |                      ^^^
  |
  = note: this note originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0080`.
error: could not compile `regression_test` (bin "regression_test") due to previous error

```

### Version it worked on

It most recently worked on: 1.72.1

Output:

```shell
$ cargo build --target=wasm32-unknown-unknown
Compiling regression_test v0.1.0 (C:\Users\123\Desktop\regression_test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
```

### Version with regression

`rustc --version --verbose`:
```shell
$ rustc --version --verbose
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-pc-windows-msvc
release: 1.73.0
LLVM version: 17.0.2
```

### Other

I read release notes for 1.73 and couldn't find anything that could be related to this, also tried to search for an existing issue about this - no luck. This issue also broke compilation of [fast_image_resize](https://crates.io/crates/fast_image_resize) crate and transitively, Fyrox game engine.

### PR DESCRIPTION
**Pull request by eduardosm**
This is not unsafe on WASM, see https://github.com/rust-lang/rust/pull/84988

r? @RalfJung 

Fixes https://github.com/rust-lang/rust/issues/116516

### CODE REVIEW

File: src/tools/miri/tests/pass/function_calls/target_feature_wasm.rs [hunk 1]
```diff
@@ -0,0 +1,11 @@
+//@only-target-wasm32: tests WASM-specific behavior
```
Comment (RalfJung) [inline src/tools/miri/tests/pass/function_calls/target_feature_wasm.rs:1]: Currently we wouldn't even run this test; [these lines](https://github.com/rust-lang/miri/blob/318c4211df1c8df5a30f8d8f3503133ff4f90dcc/ci.sh#L113-L114) control what we run on wasm. Can you add `wasm` there so that the filters pick up the new test you added?

File: src/tools/miri/tests/pass/function_calls/target_feature_wasm.rs [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+//@compile-flags: -C target-feature=-simd128
+
+fn main() {
+    // Calling functions with `#[target_feature]` is not unsafe on WASM, see #84988
```
Comment (RalfJung) [inline src/tools/miri/tests/pass/function_calls/target_feature_wasm.rs:5]:
```suggestion
    // Calling functions with `#[target_feature]` is allowed on WASM, see #84988
```

File: tests/ui/consts/const-eval/const_fn_target_feature_wasm.rs [hunk 3]
```diff
@@ -0,0 +1,14 @@
+// only-wasm32
+// compile-flags:-C target-feature=-simd128
+// build-pass
+
+#![crate_type = "lib"]
+
+#[cfg(target_feature = "simd128")]
+compile_error!("simd128 target feature should be disabled");
+
+// Calling functions with `#[target_feature]` is not unsafe on WASM, see #84988
```
Comment (RalfJung) [inline tests/ui/consts/const-eval/const_fn_target_feature_wasm.rs:10]:
```suggestion
// Calling functions with `#[target_feature]` is not unsound on WASM, see #84988.
```

File: src/tools/miri/tests/pass/function_calls/target_feature_wasm.rs (hunk 1 above)
Comment (eduardosm) [reply src/tools/miri/tests/pass/function_calls/target_feature_wasm.rs:1]: I manually ran the test, but I didn't notice it wouldn't run as part of the test suite.

**Comment by RalfJung** [comment]
LGTM, thanks!
@bors r+
