### PR TITLE
Update Cargo and RLS

### PR DESCRIPTION
**Pull request by ehuss**
## cargo

32 commits in 0ec7281b9c36ca7f724bfac8b029633910270a48..2fb77a49b43bf7266793c07a19a06749e6a8ad5a
2018-08-20 21:18:45 +0000 to 2018-09-07 17:00:19 +0000
- clippy: resolve all warnings about useless format!() (rust-lang/cargo#5966)
- make `cargo install` ignore .cargo/config (rust-lang/cargo#5874)
- Force `cargo fix` to rebuild (rust-lang/cargo#5944)
- Fix path::deep_dependencies_trigger_rebuild often failing in CI (rust-lang/cargo#5952)
- Introduce the CWD macro in test output asserting (rust-lang/cargo#5950)
- Extract FixArgs::prepare_for_edition_resolve (rust-lang/cargo#5949)
- Add `--allow-staged` to `cargo fix` (rust-lang/cargo#5943)
- Remove Cargo's internal `hamcrest` module (rust-lang/cargo#5945)
- Further reduce assert_that usage (rust-lang/cargo#5942)
- Replace lots of hamcrest's assert_that with a builder style (rust-lang/cargo#5929)
- Add documentation for creating test dependencies. (rust-lang/cargo#5939)
- Only use non-absolute paths for `path` dependencies (rust-lang/cargo#5935)
- Metabuild (RFC 2196) (rust-lang/cargo#5628)
- Fix test failure on nightly due to `codemap::Span` change. (rust-lang/cargo#5937)
- Make "cargo uninstall" uninstall the cwd bins (rust-lang/cargo#5927)
- fix cargo not doing anything when the input and output mtimes are equal (rust-lang/cargo#5919)
- List URL in HTTP download failures (rust-lang/cargo#5926)
- Improve the `cargo install` deprecation messaging (rust-lang/cargo#5925)
- Add `required-features` to `SerializedTarget` (rust-lang/cargo#5902)
- Add a configuration option to fetch with git-the-CLI (rust-lang/cargo#5914)

Added:
- Add a way to skip the `use_the_cli` test for rust repo. (rust-lang/cargo#5976)
- Do not use a disabled-option in the docs (rust-lang/cargo#5973)
- Fix a doc link (rust-lang/cargo#5970)
- Migrate some architecture notes from the wiki (rust-lang/cargo#5971)
- Provide http-config option for curl low-speed-limit/time (rust-lang/cargo#5957)

Added:
- Bump Cargo to 0.30.0 (rust-lang/cargo#5991)
- Change the default edition for `cargo new` to 2018 (rust-lang/cargo#5989)
- Stabilize `edition` key and add `cargo new --edition` (rust-lang/cargo#5984)
- Remove/rework some redundant .cwd(p.root()) in tests (rust-lang/cargo#5987)
- Don't use an empty RUSTC_WRAPPER (rust-lang/cargo#5985)
- fix: Fix unusual errors with `RUSTC_WRAPPER` (rust-lang/cargo#5983)
- Fix http.timeout documentation. (rust-lang/cargo#5977)

## rls

6 commits in cf6358a00540a83dcc6e8c243f3306ccdbb9c354..ac2e802ae9115786196a498e22086d403efd95a4
2018-09-04 14:46:47 +0200 to 2018-09-08 00:17:42 +0200
- Update cargo. (rust-lang-nursery/rls#1048)
- Fix duplicated warning for rand::Rng::gen_ascii_chars (rust-lang-nursery/rls#1042)
- Avoid void-params deserialize errors (rust-lang-nursery/rls#1041)
- Remove cached args/envs from old single crate mode (rust-lang-nursery/rls#1040)
- Include message in dispatch error log line (rust-lang-nursery/rls#1039)
- Compile with newest rustc master (rust-lang-nursery/rls#1036)

### CODE REVIEW

**Comment by ehuss** [comment]
🤔 It passes locally for me, and I'm stumped as to how it could fail.  @alexcrichton let me know if you have any ideas why it would fail, otherwise I can try investigating more.

**Comment by kennytm** [comment]
@ehuss Are you testing on Windows?

```
---- git::use_the_cli stdout ----
running `C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\release\cargo.exe build -v`
thread 'git::use_the_cli' panicked at '
Expected: execs
    but: exited with exit code: 101
--- stdout
--- stderr
    Updating git repository `file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/cit/t654/dep1`
     Running `git fetch --tags --quiet file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/cit/t654/dep1 refs/heads/*:refs/heads/*`
fatal: '/C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/cit/t654/dep1' does not appear to be a git repository
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
error: failed to load source for a dependency on `dep1`
Caused by:
  Unable to update file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/cit/t654/dep1
Caused by:
  failed to clone into: C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\cit\t654\home\.cargo\git\db\dep1-9eccd544448225e8
Caused by:
  process didn't exit successfully: `git fetch --tags --quiet file:///C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/cit/t654/dep1 refs/heads/*:refs/heads/*` (exit code: 128)
', tools\cargo\tests\testsuite\support\mod.rs:731:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failures:
    git::use_the_cli
test result: FAILED. 1406 passed; 1 failed; 4 ignored; 0 measured; 0 filtered out
```

**Comment by ehuss** [comment]
@kennytm yea, tested on windows and mac within the rust tree.  The test has also been passing on Cargo's appveyor.

**Comment by alexcrichton** [comment]
git's error message is quite funny:

```
fatal: '/C:/projects/rust/build/x86_64-pc-windows-msvc/stage2-tools/x86_64-pc-windows-msvc/cit/t654/dep1' does not appear to be a git repository
```

That `/C:/...` doesn't seem right and it seems like `file://` URLs may not be as supported on windows git. This may be an issue with MSYS git vs "Windows git". I think that this repo has a different `PATH` management strategy than Cargo, which means that the default `git.exe` (probably the official installer) which supports `file://` path is in place with Cargo but not in place here where MinGW `git` (which probably doesn't support this url scheme) is shadowing the other `git.exe`

I think it'd be fine to force Cargo to either whitelist this test to not run (like we do for cross-compilation tests) and then only run it on Cargo's CI.

**Comment by ehuss** [comment]
Ah, I can confirm the mingw /usr/bin/git does not like windows-style file urls.

Do you have a preferred way to detect this scenario?  A new env var?  Check for "windows" in `git --version`?  Something else?  I can prep a PR if you'd like.

**Comment by alexcrichton** [comment]
It's probably easiest to do what the cross-compilation tests do which is to execute the test unless a "weird env var" is set. The tests here in this repository would set such an environment variable, but in Cargo we'd continue to run the test by default.

I suppose a *real* fix is to add this to Cargo itself and figure out the best `file://` path to give down to `git`, but it's fine to leave that as an open issue for now.

**Comment by ehuss** [comment]
Updated to skip the test (I think this one place should be sufficient, though I'm not certain). I could add an `if cfg!(windows)` if you'd like, but I'm not sure if it's necessary.

**Comment by kennytm** [comment]
@bors r-

We're in the beta protection week and this PR breaks RLS in https://github.com/rust-lang/rust/pull/54021#issuecomment-419388559. cc @nrc.

```
[01:11:16] error[E0277]: a collection of type `std::collections::HashMap<&std::path::Path, (cargo::core::package_id::PackageId, cargo::core::manifest::Target, cargo::core::compiler::build_config::CompileMode)>` cannot be built from an iterator over elements of type `(&cargo::core::manifest::TargetSourcePath, (cargo::core::package_id::PackageId, cargo::core::manifest::Target, cargo::core::compiler::build_config::CompileMode))`
[01:11:16]    --> tools\rls\src\build\plan.rs:190:14
[01:11:16]     |
[01:11:16] 190 |             .collect();
[01:11:16]     |              ^^^^^^^ a collection of type `std::collections::HashMap<&std::path::Path, (cargo::core::package_id::PackageId, cargo::core::manifest::Target, cargo::core::compiler::build_config::CompileMode)>` cannot be built from `std::iter::Iterator<Item=(&cargo::core::manifest::TargetSourcePath, (cargo::core::package_id::PackageId, cargo::core::manifest::Target, cargo::core::compiler::build_config::CompileMode))>`
[01:11:16]     |
[01:11:16]     = help: the trait `std::iter::FromIterator<(&cargo::core::manifest::TargetSourcePath, (cargo::core::package_id::PackageId, cargo::core::manifest::Target, cargo::core::compiler::build_config::CompileMode))>` is not implemented for `std::collections::HashMap<&std::path::Path, (cargo::core::package_id::PackageId, cargo::core::manifest::Target, cargo::core::compiler::build_config::CompileMode)>`
[01:11:16] 
[01:11:16] error[E0599]: no method named `parent` found for type `&cargo::core::manifest::TargetSourcePath` in the current scope
[01:11:16]    --> tools\rls\src\build\plan.rs:200:26
[01:11:16]     |
[01:11:16] 200 |                         .parent()
[01:11:16]     |                          ^^^^^^
[01:11:16] 
[01:11:18] error[E0308]: mismatched types
[01:11:18]   --> tools\rls\src\project_model.rs:77:22
[01:11:18]    |
[01:11:18] 77 |                   lib: cargo_pkg
[01:11:18]    |  ______________________^
[01:11:18] 78 | |                     .targets()
[01:11:18] 79 | |                     .iter()
[01:11:18] 80 | |                     .find(|t| t.is_lib())
[01:11:18] 81 | |                     // racer expect name 'underscored'(crate) name
[01:11:18] 82 | |                     .map(|t| (t.src_path().to_owned(), t.name().replace('-', "_"))),
[01:11:18]    | |___________________________________________________________________________________^ expected struct `std::path::PathBuf`, found enum `cargo::core::manifest::TargetSourcePath`
[01:11:18]    |
[01:11:18]    = note: expected type `std::option::Option<(std::path::PathBuf, std::string::String)>`
[01:11:18]               found type `std::option::Option<(cargo::core::manifest::TargetSourcePath, std::string::String)>`
```

**Comment by ehuss** [comment]
I'll try to fix it.

**Comment by alexcrichton** [comment]
@ehuss when updating mind making sure this picks up https://github.com/rust-lang/cargo/pull/5991 as well?

**Comment by ehuss** [comment]
@alexcrichton updated
