### PR TITLE
x.py: do not build Miri by default on stable/beta

### LINKED ISSUE #73117: rust 1.44.0 fails to build in miri v0.1.0 on NetBSD/i386 8.0
I have already successfully built rust 1.44.0 on NetBSD/amd64 8.0.
Next I'm tackling NetBSD/i386 8.0, but that is not going as expected, the build
errors out after hours of apparent successful building with

```
   Compiling miri v0.1.0 (/usr/pkgsrc/lang/rust/work/rustc-1.44.0-src/src/tools/miri)
error[E0478]: lifetime bound not satisfied
   --> src/tools/miri/src/diagnostics.rs:182:18
    |
182 | impl<'mir, 'tcx> EvalContextExt<'mir, 'tcx> for crate::MiriEvalContext<'mir, 'tcx> {}
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: lifetime parameter instantiated with the lifetime `'tcx` as defined on the impl at 182:12
   --> src/tools/miri/src/diagnostics.rs:182:12
    |
182 | impl<'mir, 'tcx> EvalContextExt<'mir, 'tcx> for crate::MiriEvalContext<'mir, 'tcx> {}
    |            ^^^^
note: but lifetime parameter must outlive the lifetime `'mir` as defined on the impl at 182:6
   --> src/tools/miri/src/diagnostics.rs:182:6
    |
182 | impl<'mir, 'tcx> EvalContextExt<'mir, 'tcx> for crate::MiriEvalContext<'mir, 'tcx> {}
    |      ^^^^

```

and several more instances of a similar error, and

```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'tcx` due to conflicting requirements
   --> src/tools/miri/src/helpers.rs:267:35
    |
267 |         impl<'ecx, 'mir, 'tcx, F> ValueVisitor<'mir, 'tcx, Evaluator<'tcx>>
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: first, the lifetime cannot outlive the lifetime `'tcx` as defined on the impl at 267:26...
   --> src/tools/miri/src/helpers.rs:267:26
    |
267 |         impl<'ecx, 'mir, 'tcx, F> ValueVisitor<'mir, 'tcx, Evaluator<'tcx>>
    |                          ^^^^
note: ...so that the types are compatible
   --> src/tools/miri/src/helpers.rs:267:35
    |
267 |         impl<'ecx, 'mir, 'tcx, F> ValueVisitor<'mir, 'tcx, Evaluator<'tcx>>
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: expected  `rustc_mir::interpret::ValueVisitor<'mir, 'tcx, machine::Evaluator<'tcx>>`
               found  `rustc_mir::interpret::ValueVisitor<'_, '_, machine::Evaluator<'_>>`
note: but, the lifetime must be valid for the lifetime `'mir` as defined on the impl at 267:20...
   --> src/tools/miri/src/helpers.rs:267:20
    |
267 |         impl<'ecx, 'mir, 'tcx, F> ValueVisitor<'mir, 'tcx, Evaluator<'tcx>>
    |                    ^^^^
note: ...so that the types are compatible
   --> src/tools/miri/src/helpers.rs:272:22
    |
272 |             type V = MPlaceTy<'tcx, Tag>;
    |                      ^^^^^^^^^^^^^^^^^^^
    = note: expected  `rustc_mir::interpret::visitor::Value<'mir, 'tcx, machine::Evaluator<'tcx>>`
               found  `rustc_mir::interpret::visitor::Value<'_, '_, machine::Evaluator<'tcx>>`
```

I'm confused.  Why would the amd64 build succeed and the i386 build fail when
building the same sources, with what appears to be a rust language issue??

I expected the build on NetBSD/i386 8.0 to succeed.

Instead, this happened: (see above).

The bootstrap compiler is rust 1.43.1.

### Meta

`rustc --version --verbose`:
```
rustc 1.43.1
binary: rustc
commit-hash: unknown
commit-date: unknown
host: i686-unknown-netbsd
release: 1.43.1
LLVM version: 9.0
```

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/73117

Do I need to do anything to make sure Miri is still built by the tools CI builder? Are there other tools that should be off-by-default?

Also, unfortunately the `DEFAULT` associated const has no doc comment, so I have no idea what it does, or why there are semmingly two places where the default build of tools is controlled.

### CODE REVIEW

File: src/bootstrap/tool.rs [hunk 1]
```diff
@@ -652,20 +653,20 @@ macro_rules! tool_extended {
...
-    Cargofmt, rustfmt, "src/tools/rustfmt", "cargo-fmt", {};
-    CargoClippy, clippy, "src/tools/clippy", "cargo-clippy", {};
-    Clippy, clippy, "src/tools/clippy", "clippy-driver", {};
-    Miri, miri, "src/tools/miri", "miri", {};
-    CargoMiri, miri, "src/tools/miri/cargo-miri", "cargo-miri", {};
-    Rls, rls, "src/tools/rls", "rls", {
+    Cargofmt, rustfmt, "src/tools/rustfmt", "cargo-fmt", default=true, {};
+    CargoClippy, clippy, "src/tools/clippy", "cargo-clippy", default=true, {};
+    Clippy, clippy, "src/tools/clippy", "clippy-driver", default=true, {};
+    Miri, miri, "src/tools/miri", "miri", default=false, {};
```
Comment (mati865) [inline src/bootstrap/tool.rs:659]: This will disable miri on nightly and dev builds.

Something like that should enable miri for nightly and dev builds:
```rust
    Miri, miri, "src/tools/miri", "miri", default=builder.build.unstable_features(), {};
```
Alternatively enable for nightly only:
```rust
    Miri, miri, "src/tools/miri", "miri", default=builder.build.config.channel == "nightly", {};
```

Comment (RalfJung) [reply src/bootstrap/tool.rs:659]: I can't use run-time values though if I put this into the `DEFAULT` constant (whatever that does). Also I think hygiene will prevent me from referring to `builder`, but I could use a closure to get around that.

Comment (mati865) [reply src/bootstrap/tool.rs]: Right, maybe Mark comes up with an idea.

Comment (RalfJung) [reply src/bootstrap/tool.rs]: For now I changed the macro to say whether a tool is "stable", and then just enable all tools per default on nightly/dev builds.

But I still have no idea what to do with that undocumented `DEFAULT` constant.

File: src/bootstrap/tool.rs [hunk 2]
```diff
@@ -606,17 +607,22 @@ macro_rules! tool_extended {
 
         impl Step for $name {
             type Output = Option<PathBuf>;
-            const DEFAULT: bool = true;
+            const DEFAULT: bool = $stable; // FIXME What does this do?
```
Comment (Mark-Simulacrum) [inline src/bootstrap/tool.rs:610]: DEFAULT-enabled tools means that this step will be run by default (e.g., on x.py build). In this case it's also subject to the default_condition in should_run, though.

**Review by Mark-Simulacrum — COMMENTED** [review]
This seems reasonable, though would be good to fixup the FIXME.

File: src/bootstrap/tool.rs (hunk 2 above)
Comment (RalfJung) [reply src/bootstrap/tool.rs]: @Mark-Simulacrum I updated the PR. Does it make sense now?

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
Thanks for adding a comment to DEFAULT while we're at it :)

This does indeed look correct to me, though (as all defaults) it should be noted that people can override this by explicitly requesting a miri build (e.g. `x.py build src/tools/miri`) but that seems fine.

@bors r+

**Comment by RalfJung** [comment]
> by explicitly requesting a miri build (e.g. x.py build src/tools/miri) but that seems fine.

Yeah, or by adding it to `tools`. But if they asked for it, they should get it IMO -- seems fine.
