### ISSUE TITLE
the trait bound `&[u8]: std::convert::From<&[_; 0]>` is not satisfied

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#113238]
* https://crater-reports.s3.amazonaws.com/beta-1.71-4/beta-2023-06-25/gh/bchallenor.firebreak/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.71-4/beta-2023-06-25/reg/kresp-0.1.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.71-4/beta-2023-06-25/gh/AustinHaugerud.bextract/log.txt
* multiple `impl`s satisfying `[f32; 3]: From<_>` found in the `core` crate
  * https://crater-reports.s3.amazonaws.com/beta-1.71-4/beta-2023-06-25/gh/Maxeonyx.terrain-viewer/log.txt
  * possibly related?

**Comment by hameerabbasi** [comment]
This seems to already have been fixed on the `main` branch and also on cca7ee58110726983951a19d5fb7316d9243925d (which is what I get if I run `cargo-bisect-rustc` with the HEAD of the `beta` branch).

**Comment by compiler-errors** [comment]
@hameerabbasi how did you build this? You need to build all the tests to reproduce this, too.

**Comment by compiler-errors** [comment]
This seems to have regressed in #106704. From the UI test at the bottom of that PR, it seems to suggest that we've added a new `&[u8]: From<gimli::read::endian_slice::EndianSlice<'_, Endian>>>` implementation, which may have affected the inference/coercion somewhere in that program.

**Comment by Mark-Simulacrum** [comment]
Seems likely, and seems like that trait impl might be removable - though maybe a breaking change for gimli?

**Comment by cuviper** [comment]
This is reproducible on stable if gimli 0.27.* is pulled in at all:

```rust
extern crate gimli;
fn main() {
    let _ = <&[u8]>::from(&[]);
}
```

```
error[E0277]: the trait bound `&[u8]: From<&[_; 0]>` is not satisfied
 --> src/main.rs:3:27
  |
3 |     let _ = <&[u8]>::from(&[]);
  |             ------------- ^^^ the trait `From<&[_; 0]>` is not implemented for `&[u8]`
  |             |
  |             required by a bound introduced by this call
  |
  = help: the trait `From<EndianSlice<'input, Endian>>` is implemented for `&'input [u8]`
```

But now that `std` is pulling that version of gimli, everyone gets to feel the pain. Without that impl, `&[u8]` would only have the reflexive `From`, driving the `&[]` into an unsizing coercion. An uncoerced `From<&[T; N]> for &[T]` seems totally plausible though - I wonder if we've tried that before? (It's way too late to add new impls to 1.71 though.)

> seems like that trait impl might be removable - though maybe a breaking change for gimli?

I didn't look into how it's used, but `EndianSlice` is a public type, so yes that would be breaking to remove it.

Reverting #106704 is going to be hard too, because the new gimli is coming from `backtrace` (submodule in `std`) -> `addr2line 0.19` -> `gimli 0.27`, and there are other backtrace updates that I expect we want to keep.

**Comment by cuviper** [comment]
Hmm, actually it seems to build ok if I just downgrade to `addr2line 0.18` (which also drops to `gimli 0.26`) here:
https://github.com/rust-lang/rust/blob/f06c1b82f231401543bb61c799446d0f28769390/library/std/Cargo.toml#L26

So I guess it doesn't really need APIs of the newer version, but I don't know if we'll miss fixes or functionality. I can PR this as a release band-aid if others agree that it makes sense...

**Comment by Nilstrieb** [comment]
What's the plan for the future? I don't think we want to stay on old gimli forever. Hope that gimli removes the impl in a breaking release, which we could then pull in?

**Comment by cuviper** [comment]
> So I guess it doesn't really need APIs of the newer version,

Actually, there were no API changes in addr2line 0.18 to 0.19, only the dependency changes:
https://github.com/gimli-rs/addr2line/compare/0.18.0...0.19.0

> for 1.70 (releasing next week)?

That's 1.71.0.

> What's the plan for the future?

Unknown. I can see if adding `From<&[T; N]> for &[T]` is actually feasible, but it's possible that this may introduce other ambiguities. Another (hacky) possibility is to get gimli to only remove that impl under its "rustc-dep-of-std" feature, since they document this feature as not part of their stable API, assuming any internal use can be converted to other means.

**Comment by workingjubilee** [comment]
@Mark-Simulacrum The backtrace crate is going to need that gimli and object to be capable of later supporting AIX and also probably more recent platforms as well, as some object fixes were fixing platforms like watchOS. And it needs that gimli and addr2line to support the new DWARF formats which finally allow split debuginfo so we can maybe finally not have every Rust program be a hugely bloated binary on Linux and other Unix-y platforms.

Downgrading is an acceptable hotfix for stopping a regression from hitting stable, not for the long term.

**Comment by workingjubilee** [comment]
Also we're actually on addr2line 0.20 now.

**Comment by cuviper** [comment]
> Also we're actually on addr2line 0.20 now.

The master branch is, but I'm only thinking about beta -> 1.71.0 at the moment. We can take the next release cycle to figure out a "better" change, or else decide to make everyone eat the inference failure.

**Comment by workingjubilee** [comment]
Of course.

Anyone who is building for the targets we improved support for (I mean, aside from *all Split DWARF*) is probably building on nightly anyways, no worry about that.

**Comment by cuviper** [comment]
> * https://crater-reports.s3.amazonaws.com/beta-1.71-4/beta-2023-06-25/gh/AustinHaugerud.bextract/log.txt

FWIW, this one is actually a deref coercion, so it would need explicit `From<&Vec<T>> for &[T]` instead, if we're going to resolve these long-term with more standard library impls.

**Comment by cuviper** [comment]
> * multiple `impl`s satisfying `[f32; 3]: From<_>` found in the `core` crate
>     * https://crater-reports.s3.amazonaws.com/beta-1.71-4/beta-2023-06-25/gh/Maxeonyx.terrain-viewer/log.txt
>     * possibly related?

```rust
[INFO] [stdout] error[E0283]: type annotations needed
[INFO] [stdout]    --> src/program.rs:131:61
[INFO] [stdout]     |
[INFO] [stdout] 131 |                     camera_position: <[f32; 3]>::from(self.camera.position.into()),
[INFO] [stdout]     |                                      ----------------                      ^^^^
[INFO] [stdout]     |                                      |
[INFO] [stdout]     |                                      required by a bound introduced by this call
[INFO] [stdout]     |
[INFO] [stdout]     = note: multiple `impl`s satisfying `[f32; 3]: From<_>` found in the `core` crate:
[INFO] [stdout]             - impl<T> From<!> for T;
[INFO] [stdout]             - impl<T> From<(T, T, T)> for [T; 3];
[INFO] [stdout]             - impl<T> From<T> for T;
```
This one is a consequence of #97594, because `Point3` can convert to either `[T; 3]` or `(T, T, T)`, and now the array can convert from either of those as well. But I think the `from` was already redundant?

**Comment by workingjubilee** [comment]
I can't figure out what is being exposed to make this a problem: https://github.com/rust-lang/backtrace-rs/commit/ef961e29a4ec68ae59b430838467ef56ad6633f6

Is it really just a failure to wall off private impls in std from inference?

**Comment by cuviper** [comment]
> Is it really just a failure to wall off private impls in std from inference?

Is there such a thing as a private impl? Even if these weren't `pub` types, `dyn`/`impl Trait` is possible.

Anyway, this is the gimli change in 0.27, and it was "just" a clippy appeasement:
https://github.com/gimli-rs/gimli/commit/6190562e56088c59d5dff060e9f2e9b3b2d0e7a7#diff-04070dfc44eacc67115d519df82d3dab3aa3472f857a9fddd6bb1684d19f5b94

**Comment by workingjubilee** [comment]
Anyways I think we should land the downgrade of the dep for 1.71's sake but I _also_ think that Rust's inference algorithm resolving if there's a single possible impl but not if there's 2, and not finding another way to find the actual impl to use, is a problem.

**Comment by cuviper** [comment]
This general phenomenon is not new, e.g. #51916.

**Comment by workingjubilee** [comment]
Correct, I am mostly saying that it's a problem that we have merely accepted it.

**Comment by workingjubilee** [comment]
Though perhaps it was less of a problem when Clippy did not demand as many sacrifices.

**Comment by Mark-Simulacrum** [comment]
I've included a downgrade to addr2line 1.18 in https://github.com/rust-lang/rust/pull/113483/commits/1dcfc263f3a5520bfaa3ca57a730afed692ad051.

**Comment by klensy** [comment]
Interesting that #111076 fixed similar (observing impls from private deps) issue with miniz_oxide, but not with gimli. miniz_oxide is direct dependency, while gimli indirect (addr2line->gimli).

**Comment by philipc** [comment]
Sorry, I wasn't aware that trait implementations can could cause this sort of problem. I'm happy to revert that change in gimli if it helps here.

> Actually, there were no API changes in addr2line 0.18 to 0.19, only the dependency changes:

gimli is part of the public API of addr2line, so a version bump in gimli requires a version bump in addr2line.

**Comment by cuviper** [comment]
I'm updating the milestone so we don't forget that this still needs to be addressed in 1.72.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://github.com/rust-lang/rust/issues/113238#issuecomment-1655082378)).

@rustbot label -I-prioritize +P-high

**Comment by wesleywiser** [comment]
Visited during T-compiler's weekly triage meeting. While this doesn't seem to be strictly under our purview, we are a bit concerned that the 1.72 release is coming up and this doesn't seem to have been mitigated in 1.72 yet. 

Personally, I think if gimli is willing to remove the impl and ship a new major release (and coordinate that into a new addr2line release) that seems like the best medium term option. We may already be too late in the beta release cycle for that though so perhaps backporting the addr2line downgrade to 1.72 to ensure this regression does not accidentally get released makes sense?

**Comment by cuviper** [comment]
@philipc thanks for gimli-rs/gimli#669. Are you planning to make a release? (with addr2line as well if semver bumped)

We need to figure out the mitigation on 1.72-beta soon, but a downgrade to `addr2line 0.18` doesn't work this time:

```
error[E0432]: unresolved imports `addr2line::LookupContinuation`, `addr2line::LookupResult`
   --> library/std/src/../../backtrace/src/symbolize/gimli.rs:163:25
    |
163 |         use addr2line::{LookupContinuation, LookupResult};
    |                         ^^^^^^^^^^^^^^^^^^  ^^^^^^^^^^^^ no `LookupResult` in the root
    |                         |
    |                         no `LookupContinuation` in the root

error[E0412]: cannot find type `SplitDwarfLoad` in crate `addr2line`
   --> library/std/src/../../backtrace/src/symbolize/gimli/elf.rs:461:22
    |
461 |     load: addr2line::SplitDwarfLoad<EndianSlice<'data, Endian>>,
    |                      ^^^^^^^^^^^^^^ not found in `addr2line`

error[E0599]: no method named `make_dwo` found for struct `Dwarf` in the current scope
   --> library/std/src/../../backtrace/src/symbolize/gimli/elf.rs:488:27
    |
488 |                 dwo_dwarf.make_dwo(&load.parent);
    |                           ^^^^^^^^ method not found in `Dwarf<EndianSlice<'_, LittleEndian>>`
```

Maybe those changes can be reverted, but I didn't try.

**Comment by philipc** [comment]
gimli release PR is up. I'll do some testing and release gimli and addr2line tomorrow.

**Comment by cuviper** [comment]
Upgrading beta `std` to `addr2line v0.21.0` -> `gimli v0.28.0` works! So I think we could do just that as a targeted fix for 1.72-beta, and a fuller update following rust-lang/backtrace-rs#557 on master for 1.73-nightly.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/114955 / https://github.com/rust-lang/rust/pull/114825 fixed this, so closing.
