### ISSUE TITLE
Duplicate warning on some attributes with wrong targets

### ISSUE THREAD

**Issue by JonathanBrouwer** [rust-lang/rust#147417]
The following three cases create a hard error AND a warning:
```rust
fn main() {
    #[no_mangle] || {};
}
```
```
error: `#[no_mangle]` cannot be used on a closure as it has no name
 --> src/main.rs:2:5
  |
2 |     #[no_mangle] || {};
  |     ^^^^^^^^^^^^

warning: `#[no_mangle]` attribute cannot be used on closures
 --> src/main.rs:2:5
  |
2 |     #[no_mangle] || {};
  |     ^^^^^^^^^^^^
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = help: `#[no_mangle]` can be applied to methods, functions, and statics
  = note: `#[warn(unused_attributes)]` (part of `#[warn(unused)]`) on by default
```

```rust
#[inline]
macro_rules! test {
    () => {}
}
```
```
error[E0518]: attribute should be applied to function or closure
 --> src/main.rs:5:1
  |
5 | #[inline]
  | ^^^^^^^^^ not a function or closure

warning: `#[inline]` attribute cannot be used on macro defs
 --> src/main.rs:5:1
  |
5 | #[inline]
  | ^^^^^^^^^
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = help: `#[inline]` can only be applied to functions
  = note: `#[warn(unused_attributes)]` (part of `#[warn(unused)]`) on by default
```

```rust
#[no_mangle] pub const RAH: usize = 5;
```
```
warning: `#[no_mangle]` attribute cannot be used on constants
  --> src/main.rs:10:1
   |
10 | #[no_mangle] pub const RAH: usize = 5;
   | ^^^^^^^^^^^^
   |
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = help: `#[no_mangle]` can be applied to functions and statics
   = note: `#[warn(unused_attributes)]` (part of `#[warn(unused)]`) on by default

error: const items should never be `#[no_mangle]`
  --> src/main.rs:10:14
   |
10 | #[no_mangle] pub const RAH: usize = 5;
   |              ---------^^^^^^^^^^^^^^^^
   |              |
   |              help: try a static value: `pub static`
   |
   = note: `#[deny(no_mangle_const_items)]` on by default
```

@rustbot claim

**Comment by JonathanBrouwer** [comment]
@rustbot -needs-triage +regression-from-stable-to-beta +A-diagnostics +A-attributes +T-compiler
Caused by https://github.com/rust-lang/rust/pull/145085

**Comment by qidirbaev** [comment]
Are there any updates?

**Comment by JonathanBrouwer** [comment]
I'll make sure to implement this somewhere in the next few days :)

**Comment by Noratrieb** [comment]
@qidirbaev This issue is still brand new, only 12 hours old. It's way too early to ask for updates like this. Remember that our contributors are often volunteers that are working on their own schedules in their own time. I'm sure Jonathan will get to it eventually, but if you want to accelerate this process you shouldn't write such messages but instead offer to help with the fix :).

**Comment by JonathanBrouwer** [comment]
Found another case
```rust
pub fn foo(
    #[must_use]
    b: i32,
) {}
```
```
error: allow, cfg, cfg_attr, deny, expect, forbid, and warn are the only allowed built-in attributes in function parameters
 --> src/main.rs:2:5
  |
2 |     #[must_use]
  |     ^^^^^^^^^^^
warning: `#[must_use]` attribute cannot be used on function params
 --> src/main.rs:2:5
  |
2 |     #[must_use]
  |     ^^^^^^^^^^^
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = help: `#[must_use]` can be applied to data types, functions, traits, and unions
  = note: `#[warn(unused_attributes)]` (part of `#[warn(unused)]`) on by default
```
