### PR TITLE
bootstrap: Include feature-gated items in bootstrap tool docs

### PR DESCRIPTION
**Pull request by Zalathar**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/161900)*

I noticed that the [nightly-rustc docs for `build_helper`](https://doc.rust-lang.org/nightly/nightly-rustc/build_helper/index.html) don't include the `metrics` module, because it's gated behind the non-default feature flag `feature = "metrics"`.

This PR fixes that by using `--all-features` to document all features, and enabling rustdoc's `#![feature(doc_cfg)]` [(via -`Zcrate-attr`)](https://github.com/rust-lang/rust/issues/138287) so that rustdoc will indicate which items require feature flags.

The first two commits are a general cleanup of `tool_doc!` to pull almost all of its non-trivial code out of the macro and into regular functions.

### CODE REVIEW

**Comment by Zalathar** [comment]
As a follow-up we could also enable this for compiler crates, since a few of them have feature flags to enable nightly-only features when they aren't being used by rust-analyzer.

**Comment by Zalathar** [comment]
I would also like to note that this would have been *much* more annoying without `-Zcrate-attr`.

**Comment by Zalathar** [comment]
I really want to blanket allow `clippy::too_many_arguments` and `clippy::type_complexity` across all of bootstrap, but I won't do that in this PR.

**Comment by Kobzol** [comment]
r? kobzol

Note that this will conflict a lot with https://github.com/rust-lang/rust/pull/161716. In general I'm happy to see most of the code move out of a macro.

**Comment by Kobzol** [comment]
Aside: do you find the build_helper/bootstrap docs being present in the nightly rustc docs useful?

**Comment by Zalathar** [comment]
> Aside: do you find the build_helper/bootstrap docs being present in the nightly rustc docs useful?

I use the nightly-rustc docs intermittently, but when I do reach for them it's nice to have everything there in one place, especially when I'm not at a computer and can't easily search the source.

**Comment by Zalathar** [comment]
> Note that this will conflict a lot with #161716. In general I'm happy to see most of the code move out of a macro.

If conflicts are a concern, I can potentially cut this PR down to just the main fix (within the macro), and defer the macro-extraction to follow-up work.

(I had to do the extraction to work on the fix, but now that I have the fix it should be easy to backport to main.)

**Comment by Kobzol** [comment]
I'd perhaps either do that, or wait for the other PR to get merged, yeah.

**Comment by Kobzol** [comment]
Looks good, thanks! Feel free to r=me once PR CI is green.

**Comment by Zalathar** [comment]
PR CI is green.

@bors r=Kobzol

**Comment by GuillaumeGomez** [comment]
I think it's the one which broke in https://github.com/rust-lang/rust/pull/162298#issuecomment-5542189429.

Lot of errors like:

```
error[E0725]: the feature `rustc_private` is not in the list of allowed features
 --> /rustc/cce05538c14655b12f69e264c494b616bf3eff7c/src/tools/rustfmt/src/lib.rs:1:12
  |
1 | #![feature(rustc_private)]
  |            ^^^^^^^^^^^^^
```

@bors r-

File: src/bootstrap/src/core/build_steps/doc.rs [hunk 1]
```diff
@@ -1371,78 +1358,121 @@ macro_rules! tool_doc {
...
+        cargo.arg("--lib");
+    }
+
+    for krate in crates {
+        cargo.arg("-p").arg(krate);
+    }
+
+    // Tell rustdoc to document which items require feature flags.
+    cargo.arg("--all-features");
+    cargo.allow_features("doc_cfg");
```
Comment (Zalathar) [inline src/bootstrap/src/core/build_steps/doc.rs]: Ah, the problem is that if a `tool_doc!` entry *doesn't* specify a list of allowed features, then this line has the side-effect of disallowing all features other than `doc_cfg`.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/161900/71238e21fc55e73ab3aad8c9f79fed7a47a179e1..8f1843dc0a2e0730350dab49f9c09c9295fb758f)*

**Comment by Zalathar** [comment]
Weird that this keeps happening. 

@bors try jobs=dist-x86_64-linux-alt

**Comment by Zalathar** [comment]
Since CI has been weird today, let's run the try job *again*, after a fresh rebase.

@bors try jobs=dist-x86_64-linux-alt

**Comment by Zalathar** [comment]
I can reproduce the failure locally, so it's a real failure.

It seems to be triggered by the added `cargo.arg("--all-features")`. So perhaps there's some non-default rustfmt feature that is doing weird things.

**Comment by Zalathar** [comment]
In order to fix the rustfmt doc failures, I added a flag to selectively disable `--all-features` for a particular tool.

As a prerequisite to that, I also did a general cleanup of the syntax used by `tool_doc!`, because the current syntax is confusingly inconsistent.

@bors try jobs=dist-x86_64-linux-alt
@rustbot ready

**Comment by Zalathar** [comment]
Looks like Miri is also having trouble. Let's keep excluding tools until we find a configuration that works.

@bors try jobs=dist-x86_64-linux-alt

**Comment by Zalathar** [comment]
Note to self: My current draft tries to enable `all_features` by default, but given the potential for future trouble (especially for subtree tools), perhaps I should enable it explicitly for only the stage0 tool crates that actually have non-default features.

**Comment by jieyouxu** [comment]
> Note to self: My current draft tries to enable `all_features` by default, but given the potential for future trouble (especially for subtree tools), perhaps I should enable it explicitly for only the stage0 tool crates that actually have non-default features.

I wouldn't be surprised if subtree tools don't successfully document under `--all-features` if they don't actually exercise `--all-features` in subtree CI TBH

**Comment by Kobzol** [comment]
I think that we can just enable the features explicitly, if we need them documented.
