### ISSUE TITLE
Import associated item of generic trait and confusing "type annotations needed"

### ISSUE THREAD

**Issue by camsteffen** [rust-lang/rust#159199]
### Code

```Rust
#![feature(import_trait_associated_functions)]

trait X<Y> {
    fn foo() -> String;
}

use X::foo;

fn test() {
    let _ = foo();
}
```

### Current output

```Shell
error[E0283]: type annotations needed
  --> src/lib.rs:10:13
   |
10 |     let _ = foo();
   |             ^^^^^ cannot infer type
   |
   = note: the type must implement `X<_>`

For more information about this error, try `rustc --explain E0283`.
```

### Desired output

Either the import should be disallowed, or the error should suggest using a trait-qualified function name.

### Rationale and extra context

I don't know if there is any way to use an imported associated item of a generic trait?

[Tracking issue](https://github.com/rust-lang/rust/issues/134691)

### Other cases

```Rust

```

### Rust Version

```Shell
Nightly channel
Build using the Nightly version: 1.99.0-nightly

(2026-07-11 be8e82435eb04fbe75ed)
```

**Comment by camsteffen** [comment]
> I don't know if there is any way to use an imported associated item of a generic trait?

Found one.

```rust
use From::from;

pub fn test() {
    test2(from);
}

fn test2(f: impl Fn(String) -> String) {}
```
