### PR TITLE
fix drop scope for `super let` bindings within `if let`

### LINKED ISSUE #145328: `pin!()` has incorrect/unexpected drop order inside if-let.
My intuition is that, with regards to drop order, `pin!(expr)` should behave like `&mut expr`. However, this is not the case inside let chains.

```rust
use std::pin::pin;

struct LoudDrop(&'static str);
impl Drop for LoudDrop {
    fn drop(&mut self) {
        println!("{}", self.0);
    }
}

fn main() {
    if let x = LoudDrop("0")
        && let y = pin!(LoudDrop("1"))
    {}
    if let x = LoudDrop("3")
        && let y = &mut LoudDrop("2")
    {}
}
```

The above code outputs: `0`, `1`, `2`, `3`. It should output `1`, `0`, `2`, `3`.

cc @m-ou-se 

Discovered in https://github.com/rust-lang/rust/pull/141295#issuecomment-3181206335

Note that `pin!()` started being implemented with `super let` in version 1.88.0, the same version where let chains were stabilized.

@rustbot labels +A-pin +F-let_chains +A-destructors +F-super_let

### Meta

Reproducible on the playground with version `1.89.0` and version `1.91.0-nightly (2025-08-11 1ebbd87a62ce96a72b22)`

Related PRs:

- https://github.com/rust-lang/rust/pull/145342

### LINKED ISSUE #145374: Regression when dropping temporary value in match in older editions
Compiling the following code in older editions (edition 2024 works):

```rust
use std::fmt;

pub struct ItemIdentifier;

impl ItemIdentifier {
    fn nserror() -> Self {
        todo!()
    }

    pub fn path(&self) -> impl fmt::Display + '_ {
        0
    }
}

struct Ty {
    pointee: Box<Self>,
}

impl Ty {
    fn is_static_object(&self) -> bool {
        true
    }

    fn behind_pointer(&self) -> impl fmt::Display + '_ {
        0
    }
}

fn foo(ty: &Ty, f: &mut fmt::Formatter<'_>) {
    let _res = match ty {
        Ty { pointee } if pointee.is_static_object() => {
            write!(
                f,
                "{}, {}",
                pointee.behind_pointer(),
                ItemIdentifier::path(&ItemIdentifier::nserror()),
            )
        }
        _ => todo!(),
    };
}

fn main() {}
```

(Reduced from https://github.com/madsmtm/objc2/tree/master/crates/header-translator, this is as small as I managed to make it).

Fails compiling with:
```
error[E0716]: temporary value dropped while borrowed
  --> src/main.rs:36:39
   |
36 |                 ItemIdentifier::path(&ItemIdentifier::nserror()),
   |                 ----------------------^^^^^^^^^^^^^^^^^^^^^^^^^-
   |                 |                     |
   |                 |                     creates a temporary value which is freed while still in use
   |                 a temporary with access to the borrow is created here ...
37 |             )
38 |         }
   |         -
   |         |
   |         temporary value is freed at the end of this statement
   |         ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `impl std::fmt::Display + '_`
   |
   = note: consider using a `let` binding to create a longer lived value

For more information about this error, try `rustc --explain E0716`.
```

A `cargo bisect-rustc` reveals that this was introduced in https://github.com/rust-lang/rust/pull/143376, it is unclear to me if this breakage was intentional or not?

CC @dianne @est31

@rustbot modify labels: +regression-from-stable-to-nightly

### PR DESCRIPTION
**Pull request by dianne**
Fixes rust-lang/rust#145328 by making non-lifetime-extended `super let` reuse the logic used to compute drop scopes for non-lifetime-extended temporaries.

Also fixes rust-lang/rust#145374, which regressed due to rust-lang/rust#143376 introducing `if let`-like scopes for match arms with guards.

Tracking issue for `super let`: rust-lang/rust#139076

This is a regression fix / breaking change for macros stably exposing `super let`, including `pin!` and `format_args!`.
Nominating to be discussed alongside rust-lang/rust#145328: @rustbot label +I-lang-nominated +I-libs-api-nominated

### CODE REVIEW

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by theemathas** [comment]
How does #145374 relate to this? The code there doesn't use `super let` anywhere.

**Comment by dianne** [comment]
Format arguments, e.g. as used by, `write!` are also implemented in terms of `super let`. This is visible when printing the HIR of that test case.

**Comment by traviscross** [comment]
We talked about this in the lang call today.  For our notes, here's how I'd demonstrate the issue:

```rust
fn main() {
    assert_drop_order(1..=4, |e| {
        (
            if let _x = e.log(3)
                && let _x = &e.log(2)
            {
                drop(e.log(1))
            },
            { drop(e.log(4)) },
        );
    });
    assert_drop_order(1..=4, |e| {
        (
            if let _x = e.log(2)
                && let _x = { super let x = &e.log(4); x }
            {
                drop(e.log(1))
            },
            { drop(e.log(3)) },
        );
    });
}
```

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&code=%2F%2F+This+demonstrates+an+error+in+drop+order+identified+by+theemathas%0A%2F%2F+related+to+%60super+let%60+and+therefore+%60pin%21%60+and+%60write%21%60.%0A%2F%2F%0A%2F%2F+See%3A%0A%2F%2F%0A%2F%2F+-+https%3A%2F%2Fgithub.com%2Frust-lang%2Frust%2Fpull%2F145342%0A%2F%2F+-+https%3A%2F%2Fgithub.com%2Frust-lang%2Frust%2Fissues%2F145328%0A%2F%2F%0A%2F%2F+Author%3A+TC%0A%2F%2F+Date%3A+2025-08-13%0A%0A%23%21%5Bfeature%28super_let%29%5D%0A%23%21%5Ballow%28irrefutable_let_patterns%29%5D%0A%0Ause+core%3A%3Acell%3A%3ARefCell%3B%0A%0Afn+main%28%29+%7B%0A++++assert_drop_order%281..%3D4%2C+%7Ce%7C+%7B%0A++++++++%28%0A++++++++++++if+let+_x+%3D+e.log%283%29%0A++++++++++++++++%26%26+let+_x+%3D+%26e.log%282%29%0A++++++++++++%7B%0A++++++++++++++++drop%28e.log%281%29%29%0A++++++++++++%7D%2C%0A++++++++++++%7B+drop%28e.log%284%29%29+%7D%2C%0A++++++++%29%3B%0A++++%7D%29%3B%0A++++assert_drop_order%281..%3D4%2C+%7Ce%7C+%7B%0A++++++++%28%0A++++++++++++if+let+_x+%3D+e.log%282%29%0A++++++++++++++++%26%26+let+_x+%3D+%7B+super+let+x+%3D+%26e.log%284%29%3B+x+%7D%0A++++++++++++%7B%0A++++++++++++++++drop%28e.log%281%29%29%0A++++++++++++%7D%2C%0A++++++++++++%7B+drop%28e.log%283%29%29+%7D%2C%0A++++++++%29%3B%0A++++%7D%29%3B%0A%7D%0A%0A%2F%2F+%23+Test+scaffolding...%0A%0Astruct+DropOrder%28RefCell%3CVec%3Cu64%3E%3E%29%3B%0Astruct+LogDrop%3C%27o%3E%28%26%27o+DropOrder%2C+u64%29%3B%0A%0Aimpl+DropOrder+%7B%0A++++fn+log%28%26self%2C+n%3A+u64%29+-%3E+LogDrop%3C%27_%3E+%7B%0A++++++++LogDrop%28self%2C+n%29%0A++++%7D%0A%7D%0A%0Aimpl%3C%27o%3E+Drop+for+LogDrop%3C%27o%3E+%7B%0A++++fn+drop%28%26mut+self%29+%7B%0A++++++++self.0.0.borrow_mut%28%29.push%28self.1%29%3B%0A++++%7D%0A%7D%0A%0A%23%5Btrack_caller%5D%0Afn+assert_drop_order%28%0A++++ex%3A+impl+IntoIterator%3CItem+%3D+u64%3E%2C%0A++++f%3A+impl+Fn%28%26DropOrder%29%2C%0A%29+%7B%0A++++let+order+%3D+DropOrder%28RefCell%3A%3Anew%28Vec%3A%3Anew%28%29%29%29%3B%0A++++f%28%26order%29%3B%0A++++let+order+%3D+order.0.into_inner%28%29%3B%0A++++let+expected%3A+Vec%3Cu64%3E+%3D+ex.into_iter%28%29.collect%28%29%3B%0A++++assert_eq%21%28order%2C+expected%29%3B%0A%7D%0A)

In the call, we discussed what we'd expect the behavior to be for `super let`.  Recalling the basic equivalence underlying this work, we expect that `&EXPR === { super let x = &EXPR; x }`.  Given that, the discrepancy in drop order above is clearly not justifiable.

Everyone on the call agreed with that analysis, so let's agree via FCP 1) to accept this and 2) to waive our 10-day FCP period so we can hopefully get this into the point release that we need to cut anyway due to https://github.com/rust-lang/rust/pull/145262.

@rfcbot fcp merge

Note that the crater results aren't back yet.  We can file a concern if anything surprises us enough to change the plan here.  That however seems unlikely.

**Comment by wesleywiser** [comment]
This proposed stable backport was discussed in the T-compiler steering meeting today and there was a fair amount of concern about backporting this to stable for a few reasons:
1. Changes to drop order are subtle and having more time for the fix to be validated "in the wild" is helpful
2. The regression occurred in 1.88 so we've already shipped a full release cycle with the issue, delaying a few more weeks in the case of a beta backport typically does not make these kinds of situations worse
3. (perhaps just a restatement of point 1) but we _really_ would like to see backports have some bake time on nightly 

This is not a definitive "backport declined" but we thought it could be useful to T-lang to know our current position on backporting this.

**Comment by tmandry** [comment]
@rfcbot reviewed

I would defer to T-compiler on the stable backport risk. I would encourage a beta backport however.

I do not think we are likely to see much impact in the wild since this can only be observed via `pin!()` and `format_args!()` macros inside of `if let`, and neither of those macros produce something you would match on. The most likely scenario by far would be `if let Pat = pin!(expr).method()` where part of `expr` is sensitive to drop order. Those are both pretty rare.

However, the consequences of any impact that does exist can be large (especially if the change doesn't cause any compilation errors and leads to runtime bugs), and changing this kind of subtle behavior is ungreat, so it would be good to minimize the window this bug exists in.

Many thanks to @theemathas for finding this bug and to @dianne for the fix.

**Comment by theemathas** [comment]
> this can only be observed via...

@tmandry There is a second way that this bug can be observed. See #145374.

**Comment by dianne** [comment]
That's only nightly, though, since it requires #143376; landing this before the beta cutoff for 1.91.0 (or beta-backporting it after) should be sufficient to fix that. The regression visible in stable Rust is only with `if let`.

**Comment by dianne** [comment]
`format_args!` is affected, yes. #145374 can be modified to use `let` chains to get a 1.88-to-1.89 regression in Rust 2024, which is fixed by this PR. I can try reducing it if needed for a test, but change the definition of `foo` in that issue's example to

```rust
fn foo(ty: &Ty, f: &mut fmt::Formatter<'_>) {
    if let Ty { pointee } = ty
        && let _ = write!(
            f,
            "{}, {}",
            pointee.behind_pointer(),
            ItemIdentifier::path(&ItemIdentifier::nserror()),
        )
    {}
}
```

**Comment by theemathas** [comment]
@dianne A 1.88-to-1.89 regression? I thought we only had a 1.87-to-1.88 regression, and a 1.89-to-nightly regression.

**Comment by dianne** [comment]
Oh nice, I think that's a different bug! Temporary lifetime extension is happening there. Here's the pretty-printed HIR:

```rust
fn foo() {
    let _x =
        {
            super let args = (&1, &new_ref(&new_thing()));
            super let args =
                [format_argument::new_debug(args.0),
                        format_argument::new_debug(args.1)];
            format_arguments::new_v1(&["", ", "], &args)
        };
}
```

Unlike with `write!`, which doesn't put the `super let`s in a position where they can be lifetime-extended, these `super let`s are extended by the outer `let`, which ends up tangling up the drop order (which I assume is a bug).

This PR only changes non-lifetime-extended `super let`, so that regression is unaffected.

**Comment by theemathas** [comment]
Here's the minimization of the 1.88-to-1.89 regression which is fixed by this PR:

```rust
#[derive(Debug)]
struct Thing;

#[derive(Debug)]
struct Ref<'a>(&'a Thing);
impl Drop for Ref<'_> {
    fn drop(&mut self) {}
}

fn new_thing() -> Thing {
    Thing
}

fn new_ref(x: &Thing) -> Ref<'_> {
    Ref(x)
}

pub fn foo(f: &mut std::fmt::Formatter<'_>) {
    if let _x = write!(f, "{:?}, {:?}", 1, new_ref(&new_thing())) {}
}
```

I am filing the other bug as a separate issue.

**Comment by theemathas** [comment]
This code causes this PR to ICE in the `dropping_copy_types` lint:

```rust
pub fn foo() {
    drop(format_args!("a"));
}
```

**Comment by dianne** [comment]
Thanks for testing this! That's also a separate bug; it ICEs with debug asserts on before my commits. Here's what it looks like on stable/nightly with debug asserts off:
```
help: use `let _ = ...` to ignore the expression or result
  |
2 -     drop(format_args!("a"));
2 +     drop(let _ = );
  |
```

**Comment by theemathas** [comment]
The crater run is clean. No relevant regressions or fixes.

**Comment by apiraino** [comment]
Stable backport decline as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202025-08-21/near/535514776). 

We reviewed again the stable backport and [our concerns](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202025-08-14/near/534493618) still stand.

@rustbot label +stable-nominated
