### ISSUE TITLE
1.95 beta regression: "no method named `accept` found for struct..."

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#153849]
Regression found by the 1.95 beta crater run.

```
[INFO] [stdout] error[E0599]: no method named `accept` found for struct `Server<{closure@src/main.rs:31:77: 31:91}>` in the current scope
[INFO] [stdout]   --> src/main.rs:37:16
[INFO] [stdout]    |
[INFO] [stdout] 37 |         server.accept(&config.server.address)?;
[INFO] [stdout]    |                ^^^^^^ method not found in `Server<{closure@src/main.rs:31:77: 31:91}>`
[INFO] [stdout]    |
[INFO] [stdout]    = note: the method was found for
[INFO] [stdout]            - `Server<T, STACK_SIZE>`
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] For more information about this error, try `rustc --explain E0599`.
```

https://crater-reports.s3.amazonaws.com/beta-1.95-3/1.95.0-beta.3/reg/url-redirect-0.3.0/log.txt

**Comment by theemathas** [comment]
Bisection results:

```
searched toolchains 503745e9170b40841611aaaa634641edffd00b29 through 67aec36df76a7b67b71a8ee47684467e16f1847e


********************************************************************************
Regression in 75b9d89c68a4a92758349272aa4e35a8eb7a6708
********************************************************************************

Attempting to search unrolled perf builds
ERROR: couldn't find perf build comment
```

Regressed in #151380. cc @ShoyuVanilla @lcnr

**Comment by ShoyuVanilla** [comment]
Fortunately, https://github.com/rust-lang/rust/issues/153849 fixes this as well. Thanks, again ❤️

**Comment by lcnr** [comment]
with https://github.com/rust-lang/rust/pull/154307 merged this can now be closed?
