### PR TITLE
Do not deduce parameter attributes during CTFE

### LINKED ISSUE #151748: 1.93 regression satisfying send obligation
I cannot share a reproduction right at this moment (closed source), I will work to minimise the error sometime soon. I will describe the error that I am seeing though, incase someone can figure out a minimum repro by the error and regression alone.

* With 1.92, my code compiles. 
* With 1.93 dev profile, my code compiles. 
* With 1.93 release profile, my code no longer compiles. 
* With 1.93 release and debug-assertions, my code still doesn't compile.

I see the following (truncated) error:

```rust
error: cannot check whether the hidden type of opaque type satisfies auto traits
   --> proxy/src/pglb/local_proxy.rs:115:14
    |
115 |             .boxed()
    |              ^^^^^
    |
    = note: fetching the hidden types of an opaque inside of the defining scope is not supported. You can try moving the opaque type and the item that actually registers a hidden type into a new submodule
note: opaque type is declared here
   --> proxy/src/pqproto.rs:155:1
    |
155 | / pub async fn read_startup<S>(stream: &mut S) -> io::Result<FeStartupPacket>
156 | | where
157 | |     S: AsyncRead + Unpin,
    | |_________________________^
...
note: required by a bound in `futures::FutureExt::boxed`
   --> /Users/conrad.ludgate/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/futures-util-0.3.31/src/future/future/mod.rs:516:23
    |
514 |     fn boxed<'a>(self) -> BoxFuture<'a, Self::Output>
    |        ----- required by a bound in this associated function
515 |     where
516 |         Self: Sized + Send + 'a,
    |                       ^^^^ required by this bound in `FutureExt::boxed`
```

I bisected this to the following commit f37aa9955f03bb1bc6fe08670cb1ecae534b5815 (#147890).

I've been told that there is a post-mono trait solver pass that can be influenced by mir transforms, which would explain why I see this issue only with `--release`.

I was able to fix the issue with the following modifications

before:
```rust
pub async fn read_startup<S>(stream: &mut S) -> io::Result<FeStartupPacket>
where
    S: AsyncRead + Unpin,
{
    ...
}
```

after:
```rust
pub fn read_startup<S>(
    stream: &mut S,
) -> impl Future<Output = io::Result<FeStartupPacket>> + Send + '_
where
    S: AsyncRead + Unpin + Send,
{
    read_startup_inner(stream)
}

async fn read_startup_inner<S>(stream: &mut S) -> io::Result<FeStartupPacket>
where
    S: AsyncRead + Unpin + Send,
{
    ...
}
```

I know there's not a lot to go off of here, I apologise for this. As I say, I hope to have some time eventually to minimise this regression.

### LINKED ISSUE #152497: regression/1.93: async closures - error[E0391]: cycle detected when evaluating type-level constant
<!--
Thank you for filing a bug report! 🐛 Please provide a short summary of the bug,
along with any information you feel relevant to replicating the bug.
-->

### Source code to reproduce

The source code is available [here](https://github.com/petiaccja/sed-manager-rs/releases/tag/compiler-error%2Fcycle-detected). Unfortunately I don't have minimal repro as the error is involving a large part of my application.

The application must be built using `cargo build --release`.

### Description of the issue

**I expected to see this happen**: application compiles successfully

**Instead, this happened**: compilation fails with `error[E0391]: cycle detected when evaluating type-level constant`

The compilation failure occurs **on rustc version 1.93, but not on 1.92** and earlier, which suggests it's possible to compile the code and this might be a regression. I've had similar issues with async closures before, but I managed to work around them. You can see the exact rustc version in the section down below.

The error only occurs when using **a release build, not on dev builds**.

Complete error message:
```
error[E0391]: cycle detected when evaluating type-level constant                                                                                                                                                                                                           
  --> sed_manager\src\spec\column_types\reference_types.rs:19:28
   |
19 | pub type SPRef = ObjectUID<{ SP.mask() }>;
   |                            ^^^^^^^^^^^^^
   |
note: ...which requires const-evaluating + checking `spec::column_types::reference_types::SPRef::{constant#0}`...
  --> sed_manager\src\spec\column_types\reference_types.rs:19:30
   |
19 | pub type SPRef = ObjectUID<{ SP.mask() }>;
   |                              ^^
note: ...which requires simplifying constant for the type system `spec::generated::core::all::table_id::SP`...
  --> D:\Programming\sed-manager-rs\target\release\build\sed_manager-3a9768ca6fc6b2ba\out/spec.rs:1:48923
   |
 1 | ...ol" ; pub const METHOD_ID : ThisUID = ThisUID :: new (25769803776u64) ; const NAME_METHOD_ID : & str = "MethodID" ; pub const SP : ThisUID = ThisUID :: new (2220498092032u64) ; const NAME_SP : & str = "SP" ; pub const SP_INFO : ThisUID = ThisUID :: new (8... 
   |                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires const-evaluating + checking `spec::generated::core::all::table_id::SP`...
  --> D:\Programming\sed-manager-rs\target\release\build\sed_manager-3a9768ca6fc6b2ba\out/spec.rs:1:48923
   |
 1 | ...ol" ; pub const METHOD_ID : ThisUID = ThisUID :: new (25769803776u64) ; const NAME_METHOD_ID : & str = "MethodID" ; pub const SP : ThisUID = ThisUID :: new (2220498092032u64) ; const NAME_SP : & str = "SP" ; pub const SP_INFO : ThisUID = ThisUID :: new (8... 
   |                                                                                                                        ^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires computing call ABI of `messaging::uid::<impl at sed_manager\src\messaging\uid.rs:78:1: 78:14>::new`...
  --> sed_manager\src\messaging\uid.rs:84:5
   |
84 |     pub const fn new(value: u64) -> Self {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires deducing parameter attributes for messaging::uid::<impl at sed_manager\src\messaging\uid.rs:78:1: 78:14>::new...
  --> sed_manager\src\messaging\uid.rs:84:5
   |
84 |     pub const fn new(value: u64) -> Self {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires checking if item has MIR available: `messaging::uid::<impl at sed_manager\src\messaging\uid.rs:78:1: 78:14>::new`...
  --> sed_manager\src\messaging\uid.rs:84:5
   |
84 |     pub const fn new(value: u64) -> Self {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: ...which requires getting a list of all mir_keys...
note: ...which requires computing type of `applications::activate_locking::activate_locking::{closure#0}::{closure#0}::{closure#0}`...
  --> sed_manager\src\applications\activate_locking.rs:33:31
   |
33 |           .with(async |session| {
   |  _______________________________^
34 | |             let life_cycle_state: LifeCycleState = session.get(locking_sp.as_uid(), SP::LIFE_CYCLE_STATE).await?;
35 | |             if life_cycle_state != LifeCycleState::ManufacturedInactive {
36 | |                 return Err(Error::AlreadyActivated);
...  |
39 | |             Ok::<(), Error>(())
40 | |         })
   | |_________^
note: ...which requires type-checking `applications::activate_locking::activate_locking::{closure#0}::{closure#0}::{closure#0}`...
  --> sed_manager\src\applications\activate_locking.rs:33:31
   |
33 |           .with(async |session| {
   |  _______________________________^
34 | |             let life_cycle_state: LifeCycleState = session.get(locking_sp.as_uid(), SP::LIFE_CYCLE_STATE).await?;
35 | |             if life_cycle_state != LifeCycleState::ManufacturedInactive {
36 | |                 return Err(Error::AlreadyActivated);
...  |
39 | |             Ok::<(), Error>(())
40 | |         })
   | |_________^
note: ...which requires type-checking `applications::activate_locking::activate_locking`...
  --> sed_manager\src\spec\column_types\reference_types.rs:19:28
   |
19 | pub type SPRef = ObjectUID<{ SP.mask() }>;
   |                            ^^^^^^^^^^^^^
   = note: ...which again requires evaluating type-level constant, completing the cycle
note: cycle used when checking that `applications::change_password::change_password` is well-formed
  --> sed_manager\src\spec\column_types\reference_types.rs:19:28
   |
19 | pub type SPRef = ObjectUID<{ SP.mask() }>;
   |                            ^^^^^^^^^^^^^
   = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
```

### Rustc versions
<!--
If you're using the stable version of the compiler, you should also check if the
bug also exists in the beta or nightly versions.
-->

The following compiler version produces the error:
```
rustc 1.93.0 (254b59607 2026-01-19)
binary: rustc
commit-hash: 254b59607d4417e9dffbc307138ae5c86280fe4c
commit-date: 2026-01-19
host: x86_64-pc-windows-msvc
release: 1.93.0
LLVM version: 21.1.8
```

The following compiler version produces compiles successfully:
```
rustc 1.92.0 (ded5c06cf 2025-12-08)
binary: rustc
commit-hash: ded5c06cf21d2b93bffd5d884aa6e96934ee4234
commit-date: 2025-12-08
host: x86_64-pc-windows-msvc
release: 1.92.0
LLVM version: 21.1.3
```

</p>
</details>

### PR DESCRIPTION
**Pull request by eggyal**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/151842)*

Ever since rust-lang/rust#103172, `fn_abi_of_instance` might look at a function's body to deduce certain codegen optimization attributes for its indirectly-passed parameters beyond what can be determined purely from its signature (namely today `ArgAttribute::ReadOnly` and `ArgAttribute::CapturesNone`). Since rust-lang/rust#130201, looking at a function's body in this way entails generating, for any coroutine-closures, additional by-move MIR bodies (which aren't represented in the HIR)—but this requires knowing the types of their context and consequently cycles can ensue if such bodies are generated before typeck is complete (such as during CTFE).

Since they have no bearing on the evaluation result, this patch breaks a subquery out from `fn_abi_of_instance`, `fn_abi_of_instance_no_deduced_attrs`, which returns the ABI before such parameter attributes are deduced; and that new subquery is used in CTFE instead (however, since parameter attributes are only deduced in optimized builds, as a performance optimization we avoid calling the original query unless we are performing such a build).

Fixes rust-lang/rust#151748
Fixes rust-lang/rust#152497

### CODE REVIEW

**Comment by RalfJung** [comment]
Note that ABI "adjustments" typically do more than just deducing parameter attributes. So if "unadjusted" just refers to the attributes, that's confusing naming.

Also, having the full signature might be relevant for the UB checking that const-eval and Miri are doing. So it's at least slightly concerning that we shouldn't be able to access some of that info any more. What *exactly* is the difference between the signatures we obtain this way?

**Comment by RalfJung** [comment]
Looking at https://github.com/rust-lang/rust/issues/151748, it seems like the underlying issue is that fn_sig_of_instance looks at the *body* of the function. That is indeed somewhat sus -- at least all the UB-relevant information should be deducible without the body. Please extend the PR description to explain this; it currently takes a bit of digging to fiure out what problem you're actually solving.

If we end up resolving this by splitting the query, it is very important that the queries have good documentation explaining their relationship. We want to avoid someone changing this code in the future in a way that removes too much information from the "unadjusted" signature.

**Comment by eggyal** [comment]
I've updated the PR description—hopefully it's now clearer?

Re documentation, the "unadjusted" query (to be renamed `fn_abi_of_instance_no_deduced_attrs`) is currently documented as follows:

> Compute a `FnAbi` suitable for declaring/defining an `fn` instance, and for direct calls to an `fn`. This ABI does not have deduced parameter attributes set, and therefore may produce less optimal codegen than `fn_abi_of_instance` (which should be preferred instead). However, CTFE may wish to avoid such parameter attribute deduction, as it can otherwise result in loops during typeck.

Happy to clarify it further if required.

File: compiler/rustc_middle/src/query/mod.rs [hunk 1]
```diff
@@ -1811,11 +1811,32 @@ rustc_queries! {
         desc { "computing call ABI of `{}` function pointers", key.value.0 }
     }
 
-    /// Compute a `FnAbi` suitable for declaring/defining an `fn` instance, and for
-    /// direct calls to an `fn`.
+    /// Compute a `FnAbi` suitable for declaring/defining an `fn` instance, and for direct calls*
+    /// to an `fn`. Indirectly-passed parameters in the returned ABI might not include all possible
+    /// codegen optimization attributes (such as `ReadOnly` or `CapturesNone`), as deducing these
+    /// requires inspection of function bodies that can lead to cycles when performed during typeck.
+    /// Post typeck, you should prefer the optimized ABI returned by `fn_abi_of_instance`.
```
Comment (RalfJung) [inline compiler/rustc_middle/src/query/mod.rs]:
```suggestion
    /// to an `fn`. This query does *not* look at the function body to deduce further
    /// attributes for function arguments as doing so can lead to cycles during typeck.
    /// Post typeck, you should prefer the optimized ABI returned by `fn_abi_of_instance`.
```
Let's not list what exactly gets put into "deduced attrs" as that will inevitably expand in the future.

File: compiler/rustc_middle/src/query/mod.rs [hunk 2]
```diff
@@ -1811,11 +1811,32 @@ rustc_queries! {
...
+    ) -> Result<&'tcx rustc_target::callconv::FnAbi<'tcx, Ty<'tcx>>, &'tcx ty::layout::FnAbiError<'tcx>> {
+        desc { "computing unadjusted call ABI of `{}`", key.value.0 }
+    }
+
+    /// Compute a `FnAbi` suitable for declaring/defining an `fn` instance, and for direct calls*
+    /// to an `fn`. Indirectly-passed parameters in the returned ABI will include applicable
+    /// codegen optimization attributes, including `ReadOnly` and `CapturesNone` -- deduction of
+    /// which requires inspection of function bodies that can lead to cycles when performed during
+    /// typeck. During typeck, you should therefore use instead the unoptimized ABI returned by
+    /// `fn_abi_of_instance_no_deduced_attrs`.
```
Comment (RalfJung) [inline compiler/rustc_middle/src/query/mod.rs]:
```suggestion
    /// Compute a `FnAbi` suitable for declaring/defining an `fn` instance, and for direct calls*
    /// to an `fn`. This query looks at the function body to deduce further attributes, which
    /// can lead to cycles when performed during typeck. During typeck, you should therefore
    /// instead use `fn_abi_of_instance_no_deduced_attrs`.
```

**Comment by eggyal** [comment]
Re the performance regression, it's worth noting that these cycles currently lead to us rejecting valid programs such as can be seen in the linked issue, the simplest minimisation of which is included as a new UI test with this PR:

https://github.com/rust-lang/rust/blob/132a6331f743c03074679da4a7aa5ecdfd454948/tests/ui/coroutine/avoid-query-cycle-in-ctfe.rs#L10-L18

Accordingly I think a 0.4% mean instruction count regression in the primary suite might be acceptable in order not to continue rejecting such programs?  But of course if there's a more performant solution, that would be preferable.

@rustbot label: +perf-regression-triaged

**Comment by RalfJung** [comment]
This is a pretty broad regression, ISTM we should explore other ways of fixing this / ways to improve the performance of this before deciding to go with this approach.

Cc @rust-lang/wg-compiler-performance

**Comment by eggyal** [comment]
Holy moly.

@rustbot author

**Comment by eggyal** [comment]
Actually it should be possible to improve on this a bit, with a HIR visitor that collects the tuple constructors directly into the result set without calling (the non-memoized) `hir_crate_items`, which creates a bunch of intermediate (and mostly discarded) allocations.

@rustbot author

**Comment by eggyal** [comment]
@RalfJung now that this adopts a different approach that doesn't negatively impact perf, are you the right reviewer for this or should we reroll?  No pressure, just wanted to check how this might best move forward now.

**Comment by tmiasko** [comment]
> Annoyingly the fix that I originally proposed (most recently in [132a633](https://github.com/rust-lang/rust/commit/132a6331f743c03074679da4a7aa5ecdfd454948))—that did not perform parameter deduction during CTFE but had a perf regression, would have also fixed the new case in #152497.

I think the compile time impact for debug and incremental is because `tcx.sess.opts.optimize != OptLevel::No && tcx.sess.opts.incremental.is_none()` condition is evaluated too late. That is, the code ends up evaluating both `fn_abi_of_instance` and `fn_abi_of_instance_no_deduced_attrs` queries. I would try to organize the code so that when this condition is false we effectively end up using only one of the queries.

File: compiler/rustc_ty_utils/src/abi.rs [hunk 3]
```diff
@@ -620,30 +660,36 @@ fn fn_abi_adjust_for_abi<'tcx>(
...
-            };
-        if !deduced.is_empty() {
-            apply_deduced_attributes(cx, deduced, 0, &mut fn_abi.ret);
-            for (arg_idx, arg) in fn_abi.args.iter_mut().enumerate() {
-                apply_deduced_attributes(cx, deduced, arg_idx + 1, arg);
-            }
-        }
+    // Look up the deduced parameter attributes for this function, if we have its def ID and
+    // we're optimizing in non-incremental mode. We'll tag its parameters with those attributes
+    // as appropriate.
```
Comment (RalfJung) [inline compiler/rustc_ty_utils/src/abi.rs]: This comment refers to a check that's now in an entirely different file -- seems like it needs updating.

File: compiler/rustc_middle/src/ty/mod.rs [hunk 4]
```diff
@@ -2164,6 +2165,10 @@ impl<'tcx> TyCtxt<'tcx> {
 
         !self.associated_types_for_impl_traits_in_associated_fn(trait_item_def_id).is_empty()
     }
+
+    pub fn will_deduce_param_attrs(self) -> bool {
```
Comment (RalfJung) [inline compiler/rustc_middle/src/ty/mod.rs]: Please add a doc comment explaining the role of this method.

**Review by RalfJung — CHANGES_REQUESTED** [review]
I admit I have a bit of a hard time following the spaghetti of delegations here -- but it looks okay and the tests pass, so I guess it's all working, and I can't immediately think of a less messy way for doing this.

I do have some minor comment nits, though.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/151842/71e00273c0921e1bc850ae8cc4161fbb44cfa848..d3c27f78a2f19f297ab532b6e456bd59aad173f0)*

**Comment by eggyal** [comment]
> I admit I have a bit of a hard time following the spaghetti of delegations here -- but it looks okay and the tests pass, so I guess it's all working, and I can't immediately think of a less messy way for doing this.

A less messy way, albeit perhaps a bit more brittle, could be to instead:

- rename the `fn_abi_of_instance` query to, say, `fn_abi_of_instance_query`

- define instead an inherent `fn_abi_of_instance` method on `TyCtxt<'tcx>` that performs the `will_deduce_param_attrs` test and dispatches to the relevant query (that now named `fn_abi_of_instance_query` in the affirmative case and the `fn_abi_of_instance_no_deduced_attrs` in the negative case)

- Therefore the `fn_abi_of_instance_no_deduced_attrs` query is always invoked, and it's the `fn_abi_of_instance_query` that's bypassed when not required - this allows the rest of the code to be much cleaner/less spaghetti like

- However it relies on downstream code never invoking the `fn_abi_of_instance_query` query directly but rather always going through the `fn_abi_of_instance` dispatch function, or else the performance benefit will be lost

- Perhaps an even more appropriate name for the renamed query might be `fn_abi_of_instance_with_deduced_attrs_do_not_invoke_directly`

> I do have some minor comment nits, though.

Thank you - I'll address those when I'm back at my computer.

File: compiler/rustc_ty_utils/src/abi.rs [hunk 5]
```diff
@@ -250,25 +254,73 @@ fn fn_abi_of_fn_ptr<'tcx>(
...
+        extra_args,
     )
 }
 
-fn fn_abi_of_instance<'tcx>(
+fn instance_params<'tcx>(
     tcx: TyCtxt<'tcx>,
     query: ty::PseudoCanonicalInput<'tcx, (ty::Instance<'tcx>, &'tcx ty::List<Ty<'tcx>>)>,
-) -> Result<&'tcx FnAbi<'tcx, Ty<'tcx>>, &'tcx FnAbiError<'tcx>> {
+) -> (LayoutCx<'tcx>, ty::FnSig<'tcx>, Option<DefId>, Option<Ty<'tcx>>, bool, &'tcx [Ty<'tcx>]) {
```
Comment (RalfJung) [inline compiler/rustc_ty_utils/src/abi.rs]: This is a gigantic tuple... might be worth defining a struct to hold these? That might also make the call site in `fn_abi_of_fn_ptr` look less strange. The `None, None, false` there is not very self-explaining.

File: compiler/rustc_middle/src/ty/mod.rs [hunk 6]
```diff
@@ -2165,6 +2166,33 @@ impl<'tcx> TyCtxt<'tcx> {
...
+    /// unnecessary query system overhead).
+    ///
+    /// * that includes virtual calls, which are represented by "direct calls" to an
+    ///   `InstanceKind::Virtual` instance (of `<dyn Trait as Trait>::fn`).
+    #[inline]
+    pub fn fn_abi_of_instance(
+        self,
+        query: ty::PseudoCanonicalInput<'tcx, (ty::Instance<'tcx>, &'tcx ty::List<Ty<'tcx>>)>,
+    ) -> Result<&'tcx FnAbi<'tcx, Ty<'tcx>>, &'tcx FnAbiError<'tcx>> {
+        // Only deduce attrs in full, optimized builds
```
Comment (RalfJung) [inline compiler/rustc_middle/src/ty/mod.rs]:
```suggestion
        // Only deduce attrs in full, optimized builds. Otherwise, avoid ever calling `fn_abi_of_instance_raw`;
        // that greatly reduces query cache overhead.
```

**Review by RalfJung — CHANGES_REQUESTED** [review]
Yeah that's much better, thank you. :)

Now that I can see through the code better, I did notice two more things.

*[View changes since this review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/151842/d8b2222b11fc03a31d43707c8c9006f025809ece..35a803a1447b6189a648fea2fd9efbbad6f5fd7c)*

File: compiler/rustc_ty_utils/src/abi.rs [hunk 7]
```diff
@@ -243,30 +247,97 @@ fn fn_sig_for_fn_abi<'tcx>(
...
+fn fn_abi_of_instance_raw<'tcx>(
+    tcx: TyCtxt<'tcx>,
+    query: ty::PseudoCanonicalInput<'tcx, (ty::Instance<'tcx>, &'tcx ty::List<Ty<'tcx>>)>,
+) -> Result<&'tcx FnAbi<'tcx, Ty<'tcx>>, &'tcx FnAbiError<'tcx>> {
+    // The `fn_abi_of_instance_no_deduced_attrs` query may have been called during CTFE, so we
+    // delegate to it here in order to reuse (and, if necessary, augment) its result.
+    tcx.fn_abi_of_instance_no_deduced_attrs(query).map(|fn_abi| {
+        let params = FnAbiDesc::for_instance(tcx, query);
+        // If the function's body can be used to deduce parameter attributes, then adjust such
+        // "no deduced attrs" ABI.
```
Comment (RalfJung) [inline compiler/rustc_ty_utils/src/abi.rs]:
```suggestion
        // "no deduced attrs" ABI. Otherwise, leave `fn_abi` unchanged.
```

**Comment by JonathanBrouwer** [comment]
Lmao lets try again then
@bors retry
