### ISSUE TITLE
Regression in derive-more-0.5.0, Rust 1.16

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#40195]
```
brian@ip-10-145-43-250:~/dev/derive_more⟫ git remote -v
origin  https://github.com/JelteF/derive_more (fetch)
origin  https://github.com/JelteF/derive_more (push)
brian@ip-10-145-43-250:~/dev/derive_more⟫ git log -1
commit 0b09cf91a423a39c2f2de11158f4030fbe9f3766
Author: Jelte Fennema <github-tech@jeltef.nl>
Date:   Thu Feb 2 20:02:33 2017 +0100

    Bump version to 0.5.0

```

```

     Running target/debug/deps/not-f8aa6b8c1c9746d1

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests derive_more

running 2 tests
test _0 ... FAILED
test _1 ... FAILED

failures:

---- _0 stdout ----
        error: expected item, found `;`
 --> <anon>:5:34
  |
5 | struct Point2D { x: i32, y: i32 };
  |                                  ^

error: aborting due to previous error(s)

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/session/mod.rs:203
note: Run with `RUST_BACKTRACE=1` for a backtrace.

---- _1 stdout ----
        error[E0468]: an `extern crate` loading macros must be at the crate root
 --> <anon>:3:1
  |
3 | extern crate derive_more;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error(s)

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/beta-dist-rustc-linux/build/src/librustc/session/mod.rs:203


failures:
    _0
    _1

test result: FAILED. 0 passed; 2 failed; 0 ignored; 0 measured

error: test failed

```

```
brian@ip-10-145-43-250:/mnt2/dev⟫ rustc +beta -Vv
rustc 1.16.0-beta.2 (bc15d5281 2017-02-16)
binary: rustc
commit-hash: bc15d5281c07828e7e5ca31af2051347f62629f5
commit-date: 2017-02-16
host: x86_64-unknown-linux-gnu
release: 1.16.0-beta.2
LLVM version: 3.9
```

Not on 1.15.

cc JelteF

**Comment by brson** [comment]
cc @jseyfried

**Comment by jseyfried** [comment]
This appears to be caused by #37890 -- this doc test was always erroneous but wasn't collected and compiled before #37890.
cc @eddyb

**Comment by brson** [comment]
Seems ok to break to me.

**Comment by brson** [comment]
cc @JelteF

**Comment by JelteF** [comment]
Yes, that is correct. I think it was due to this issue though: https://github.com/rust-lang/cargo/pull/3552

If 0.6.0 does build everything is fine.
