### PR TITLE
Leave promoteds untainted by errors when borrowck fails

### LINKED ISSUE #110856: erroneous `note: erroneous constant used` emitted for non-compiling `format_args!` usage
I tried [this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cf1de58f32b3158d7ba97d7fd7363813):

```rust
format_args!("{:?}", { let [_a] = *(&[] as &[Vec<i32>]) else { return }; });
```

I expected to see this happen: an error about not being able to move out of a slice

Instead, this happened: the error and a bunch of `note: erroneous constant used`

```
error[E0508]: cannot move out of type `[Vec<i32>]`, a non-copy slice
 --> src/main.rs:2:35
  |
2 | format_args!("{:?}", { let [_a] = *(&[] as &[Vec<i32>]) else { return }; });
  |                             --    ^^^^^^^^^^^^^^^^^^^^^ cannot move out of here
  |                             |
  |                             data moved here
  |                             move occurs because `_a` has type `Vec<i32>`, which does not implement the `Copy` trait
  |
help: consider borrowing the pattern binding
  |
2 | format_args!("{:?}", { let [ref _a] = *(&[] as &[Vec<i32>]) else { return }; });
  |                             +++

note: erroneous constant used
 --> src/main.rs:2:14
  |
2 | format_args!("{:?}", { let [_a] = *(&[] as &[Vec<i32>]) else { return }; });
  |              ^^^^^^

note: erroneous constant used
 --> src/main.rs:2:37
  |
2 | format_args!("{:?}", { let [_a] = *(&[] as &[Vec<i32>]) else { return }; });
  |                                     ^^^

note: erroneous constant used
 --> src/main.rs:2:22
  |
2 | format_args!("{:?}", { let [_a] = *(&[] as &[Vec<i32>]) else { return }; });
  |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: this note originates in the macro `format_args` (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Meta

Fails on `1.71.0-nightly (2023-04-25 458d4dae845ec155b285)`, works fine on `1.70.0-beta.1 (2023-04-19 1b7dd2252b99671ce5d1)`

### PR DESCRIPTION
**Pull request by tmiasko**
Previously, when borrowck failed it would taint all promoteds within the MIR body. An attempt to evaluated the promoteds would subsequently fail with spurious "note: erroneous constant used". For example:

```console
...
note: erroneous constant used
 --> tests/ui/borrowck/tainted-promoteds.rs:7:9
  |
7 |     a = &0 * &1 * &2 * &3;
  |         ^^

note: erroneous constant used
 --> tests/ui/borrowck/tainted-promoteds.rs:7:14
  |
7 |     a = &0 * &1 * &2 * &3;
  |              ^^

note: erroneous constant used
 --> tests/ui/borrowck/tainted-promoteds.rs:7:19
  |
7 |     a = &0 * &1 * &2 * &3;
  |                   ^^

note: erroneous constant used
 --> tests/ui/borrowck/tainted-promoteds.rs:7:24
  |
7 |     a = &0 * &1 * &2 * &3;
  |                        ^^
```

Borrowck failure doesn't indicate that there is anything wrong with promoteds. Leave them untainted.

Fixes #110856.

### CODE REVIEW

**Comment by compiler-errors** [comment]
Yeah, I have no idea why I made the `tainted_by_errors` propagate into the promoted constant in #93691.

I don't really think there are ways of triggering a (meaningful) borrowck error on a promoted constant anyways, though happy to be disproven by an example...

I checked, it also gets rid of the "erroneous constant" note at the end of:

```rust
fn main() {
    println!("{}", {
        let x: &str;
        x
    });
}
```

```rust
error[E0381]: used binding `x` isn't initialized
 --> /home/gh-compiler-errors/test.rs:4:9
  |
3 |         let x: &str;
  |             - binding declared here but left uninitialized
4 |         x
  |         ^ `x` used here but it isn't initialized
  |
help: consider assigning a value
  |
3 |         let x: &str = todo!();
  |                     +++++++++

note: erroneous constant used
 --> /home/gh-compiler-errors/test.rs:2:14
  |
2 |     println!("{}", {
  |              ^^^^
```

r=me when green

**Comment by matthewjasper** [comment]
There's the error in #71587, not sure if that counts as "meaningful" or not.

**Comment by compiler-errors** [comment]
@matthewjasper: Sorry, by "meaningful", I guess I should've been more clear. What I mean is borrowck errors that are likely to cause spurious const-eval errors or ICEs. It doesn't seem like that's the case with the class of issues you fixed in #71587, though, and it doesn't seem like any other existing UI tests were affected by this change, so I consider this PR to be pretty low-risk. The only possible issue is that we might see are spurious const eval errors or ICEs from no longer tainting these promoteds, thus leading to them being evaluated...

@bors r+
