### ISSUE TITLE
`rustc_skip_array_during_method_dispatch` is bypassed by method calls implemented for any `I: IntoIterator`

### ISSUE THREAD

**Issue by SkiFire13** [rust-lang/rust#87132]
After seeing #84147 I wondered if it applied to any method call that requires `[T; N]: IntoIterator`, but looks like that's not the case. This code compiles fine in rust 1.52, but fails to compile from rust 1.53

```rust
trait IterExt {
    type Iter: Iterator;
    fn it(self) -> Self::Iter;
}

impl<I: IntoIterator> IterExt for I {
    type Iter = I::IntoIter;
    fn it(self) -> Self::Iter {
        self.into_iter()
    }
}

fn main() {
    let a = [1, 2, 3];
    for i in a.it() {
        let _: &i32 = i;
    }
}
```

In rust 1.53 it fails with the following error:

```
error[E0308]: mismatched types
  --> <source>:16:23
   |
16 |         let _: &i32 = i;
   |                ----   ^
   |                |      |
   |                |      expected `&i32`, found integer
   |                |      help: consider borrowing here: `&i`
   |                expected due to this

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
```

**Comment by jyn514** [comment]
Is this an issue in practice? Does it break any crates on crates.io?

**Comment by SkiFire13** [comment]
As previously stated I discovered this by seeing #84147, not due to some crate suddently not compiling anymore, and since the setup needed is pretty niche I don't think this is a big issue in practice.

**Comment by jonas-schievink** [comment]
The workaround was added specifically to fix `array.into_iter()`, which some crates in the crater run were doing. I don't think any crates were found that relied on *this* behavior.

**Comment by apiraino** [comment]
Assigning priority, [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2387132.20.60rustc_skip_array_during_method_dispatch.60.20is.20bypasse.E2.80.A6) of the Prioritization Working Group in case this should be re-evaluated

@rustbot label -I-prioritize +P-low

**Comment by jyn514** [comment]
I don't think this is worth tracking.
