### ISSUE TITLE
Regression: transmuting between raw pointer and Option<NonNull> no longer works

### ISSUE THREAD

**Issue by yshui** [rust-lang/rust#155330]
### Code

I tried this code:

```rust
use std::ptr::NonNull;
pub const fn is_null<'a, T: ?Sized>(ptr: *const T) -> bool {
    unsafe {
        matches!(
            core::mem::transmute::<*const T, Option<NonNull<T>>>(ptr),
            None
        )
    }
}
```

I expected to see this happen: Code compiles

Instead, this happened:

```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
 --> src/lib.rs:5:13
  |
5 |             core::mem::transmute::<*const T, Option<NonNull<T>>>(ptr),
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: source type: `*const T` (pointer to `T`)
  = note: target type: `Option<NonNull<T>>` (size can vary because of <T as Pointee>::Metadata)

For more information about this error, try `rustc --explain E0512`.
```

* * *

Bisected to 338dff3e3a375cb4a3c68be825058c582262655a #136006

**Comment by yshui** [comment]
Code snippet comes from an older version of `konst`.

**Comment by yshui** [comment]
`T: ?Sized` is required. And transmuting `*const T` -> `NonNull<T>` still works, but `Option<NonNull<T>>` is affected.

**Comment by theemathas** [comment]
cc @oli-obk, @wesleywiser (author and reviewer of #136006)
