### ISSUE TITLE
[NLL] loss of span for type outlives errors in closures/async blocks

### ISSUE THREAD

**Issue by aliemjay** [rust-lang/rust#99245]
Given the following code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=aaf294b9353da9ea4ef76206ed0c0a76

```rust
fn test<'a, T>() {
    || {
        None::<&'a T>;
    };
}
```

The current output is:

```
error[E0309]: the parameter type `T` may not live long enough
 --> src/lib.rs:2:5
  |
2 | /     || {
3 | |         None::<&'a T>;
4 | |     };
  | |_____^ ...so that the type `T` will meet its required lifetime bounds
  |
help: consider adding an explicit lifetime bound...
  |
1 | fn test<'a, T: 'a>() {
  |              ++++
```

Ideally the output should look similar to when constraint is generated in the main fn body:

```
error[E0309]: the parameter type `T` may not live long enough
 --> src/lib.rs:3:9
  |
3 |         None::<&'a T>;
  |         ^^^^^^^^^^^^^ ...so that the type `T` will meet its required lifetime bounds
  |
help: consider adding an explicit lifetime bound...
  |
1 | fn test<'a, T: 'a>() {
  |              ++++
```

@rustbot label A-NLL NLL-diagnostics D-terse regression-from-stable-to-beta

**Comment by apiraino** [comment]
Regressed in #95565 cc @jackh726 

searched nightlies: from nightly-2022-01-01 to nightly-2022-07-20
regressed nightly: nightly-2022-06-08
searched commit range: https://github.com/rust-lang/rust/compare/50b00252aeb77b10db04d65dc9e12ce758def4b5...5435ed6916a59e8d5acba2149316a841c3905cbd
regressed commit: https://github.com/rust-lang/rust/commit/bb55bd449e65e611da928560d948982d73e50027

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.3</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2022-01-01 --script=./script.sh 

cat script.sh
#!/bin/sh
cargo check 2>&1 | grep "does not outlive the data it points at"
```
</details>
