### ISSUE TITLE
Nightly regression (expected a path on the left-hand side of `+`)

### ISSUE THREAD

**Issue by dpc** [rust-lang/rust#39169]
```
$ rustc --version
rustc 1.16.0-nightly (c07a6ae77 2017-01-17)
$ cargo --version
cargo 0.17.0-nightly (493abf5 2017-01-18)
```

Daily travis builds of `slog` are failing for todays nightly: https://travis-ci.org/slog-rs/slog/jobs/192913808

```
error[E0178]: expected a path on the left-hand side of `+`, not `(Fn(D::Error) -> E)`
   --> src/_drain.rs:119:17
    |
119 |     map_fn: Box<(Fn(D::Error) -> E) + 'static+ Send+Sync>,
    |                 ^^^^^^^^^^^^^^^^^^^ expected a path
    |
    = help: perhaps you forgot parentheses? (per RFC 438)
```

**Comment by petrochenkov** [comment]
This is a regression from https://github.com/rust-lang/rust/pull/39110

Strictly speaking, the syntax is incorrect - parens are not permitted in bounds.
The correct variant is `Box<Fn(D::Error) -> E + 'static+ Send+Sync>`.
I'll submit a fix ASAP though, so we could start a warning period or something later.

**Comment by dpc** [comment]
Thank you for information. I'll fix it and release patch version ASAP. I don't think many projects could be affected.
