### PR TITLE
Improve suggest construct with literal syntax instead of calling

### LINKED ISSUE #138931: Offer a suggested fix for structs with a single field
### Code

```Rust
struct Person {
    name: String,
}

fn main() {
    Person("Wilfred".to_owned());
}
```

### Current output

```Shell
error[E0423]: expected function, tuple struct or tuple variant, found struct `Person`
 --> src/main.rs:6:5
  |
1 | / struct Person {
2 | |     name: String,
3 | | }
  | |_- `Person` defined here
...
6 |       Person("Wilfred".to_owned());
  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: use struct literal syntax instead: `Person { name: val }`
```

### Desired output

Ideally rustc would offer a fix here of `Person { name: "Wilfred".to_owned() }`.

### Rationale and extra context

When there's only one field in a struct, this is probably what the user meant to write.

### Rust Version

```Shell
$ rustc --version --verbose 
rustc 1.85.0 (4d91de4e4 2025-02-17)
binary: rustc
commit-hash: 4d91de4e48198da2e33413efdcd9cd2cc0c46688
commit-date: 2025-02-17
host: x86_64-unknown-linux-gnu
release: 1.85.0
LLVM version: 19.1.7
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by xizheyin**
Fixes #138931 

When constructing a structure through a format similar to calling a constructor, we can use verbose suggestions to hint at using literal syntax for clearer advice. The case of multiple fields is also considered here, provided that the field has the same number of arguments as CallExpr.

r? compiler

### CODE REVIEW

**Comment by oli-obk** [comment]
Please make your ui test commit pass on its own so the second commit shows the difference. That makes it a bit easier to review

**Comment by xizheyin** [comment]
Ok, I submitted the test in the first commit and got it to pass on the original version of the code. In the second commit I modified the code and submitted the changes to the ui test output.
@oli-obk

File: compiler/rustc_resolve/src/late/diagnostics.rs [hunk 1]
```diff
@@ -1681,41 +1681,81 @@ impl<'ast, 'ra: 'ast, 'tcx> LateResolutionVisitor<'_, 'ast, 'ra, 'tcx> {
...
+                            && let Some(fields) = &fields
+                            && args.len() == fields.len()
+                        // Make sure we have same number of args as fields
+                        {
+                            let path_span = path.span;
+                            let mut parts = Vec::new();
+
+                            // Start with the opening brace
+                            parts.push((
+                                Span::with_root_ctxt(path_span.hi(), path_span.hi() + BytePos(1)),
```
Comment (oli-obk) [inline compiler/rustc_resolve/src/late/diagnostics.rs:1700]: To make sure this doesn't cause problems in the presence of macros or other expansions, please avoid doing manual byte pos math. For this span it would be `path_span.hi().to(args[0].span)` I believe. Similarly for the end you should be able to use the span from the last arg to the end of the full call expr span.

Comment (xizheyin) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Thanks for the heads up. That's what I did the first time I tried it, but the printout was probably not very pretty. So I switched to the arithmetic operation of span. 
```
17 |       let bar = Bar(
   |  _______________^
18 | |         "Wilfred".to_owned(),
19 | |         20,
20 | |         180,
21 | |     );
   | |_____^
   |
help: use struct literal syntax instead of calling
   |
17 ~     let bar = Bar {name: "Wilfred".to_owned(),
18 ~         age: 20,
19 ~         height: 180};
   |
```
I've now modified it as you requested.

Comment (oli-obk) [reply compiler/rustc_resolve/src/late/diagnostics.rs]: Yea, that's a bit unfortunate. We don't have a good span for the exact information you'd need.
