### PR TITLE
Add new Tier-3 targets: `loongarch32-unknown-none*`

### PR DESCRIPTION
**Pull request by heiher**
MCP: https://github.com/rust-lang/compiler-team/issues/865

NOTE: LoongArch32 ELF object support is available starting with object v0.37.0.

### CODE REVIEW

File: src/tools/miri/src/shims/alloc.rs [hunk 1]
```diff
@@ -16,7 +16,8 @@ pub trait EvalContextExt<'tcx>: crate::MiriInterpCxExt<'tcx> {
         // `library/std/src/sys/pal/common/alloc.rs` (where this is called `MIN_ALIGN`) and should
```
Comment (RalfJung) [inline src/tools/miri/src/shims/alloc.rs]:
```suggestion
        // `library/std/src/sys/alloc/mod.rs` (where this is called `MIN_ALIGN`) and should
```

File: compiler/rustc_ast_lowering/src/asm.rs [hunk 2]
```diff
@@ -48,6 +48,7 @@ impl<'a, 'hir> LoweringContext<'a, 'hir> {
                     | asm::InlineAsmArch::Arm64EC
                     | asm::InlineAsmArch::RiscV32
                     | asm::InlineAsmArch::RiscV64
+                    | asm::InlineAsmArch::LoongArch32
```
Comment (taiki-e) [inline compiler/rustc_ast_lowering/src/asm.rs]: This insta-stabilizes inline assembly on LoongArch32. AFAIK it [needs a T-lang FCP](https://github.com/rust-lang/rust/pull/131258#issuecomment-2394110064).

File: src/tools/miri/src/shims/alloc.rs (hunk 1 above)
Comment (heiher) [reply src/tools/miri/src/shims/alloc.rs]: Done.

File: compiler/rustc_ast_lowering/src/asm.rs (hunk 2 above)
Comment (heiher) [reply compiler/rustc_ast_lowering/src/asm.rs]: I've removed it now.

File: src/doc/rustc/src/platform-support/loongarch-none.md [hunk 3]
```diff
@@ -29,13 +31,13 @@ additional CPU features via the `-C target-feature=` codegen options to rustc, o
...
 By default, code generated with the soft-float target should run on any
-LoongArch64 hardware, with the hard-float target additionally requiring an FPU;
+LoongArch hardware, with the hard-float target additionally requiring an FPU;
 enabling additional target features may raise this baseline.
 
 Code generated with the targets will use the `medium` code model by default.
 You can change this using the `-C code-model=` option to rustc.
 
-On `loongarch64-unknown-none*`, `extern "C"` uses the [architecture's standard calling convention][lapcs].
+On `loongarch*-unknown-none*`, `extern "C"` uses the [architecture's standard calling convention][lapcs].
```
Comment (wesleywiser) [inline src/doc/rustc/src/platform-support/loongarch-none.md:38]: I would recommend updating some of the sections below to mention the new targets (for example, the table on lines 56-59, state these new 32-bit targets are Tier 3 in the "Building Rust Programs" section, etc).

Comment (heiher) [reply src/doc/rustc/src/platform-support/loongarch-none.md:38]: Done.

**Review by wesleywiser — APPROVED** [review]

**Comment by wesleywiser** [comment]
Thanks @heiher!

@bors r+ rollup

**Comment by AngelicosPhosphoros** [comment]
Hi!
One of the commits from this PR seems to have broken build of `rustc` on Windows 10.

I got this from `git bisect run python x.py check`.
```
Checking stage1 gcc (x86_64-pc-windows-msvc)
   Compiling libc v0.2.168
    Checking gccjit_sys v0.8.0
    Checking gccjit v2.7.0
    Checking rustc_codegen_gcc v0.1.0 (G:\Projects\Programs\Rust\rust-lang2\compiler\rustc_codegen_gcc)
error[E0464]: multiple candidates for `rmeta` dependency `object` found
  --> compiler\rustc_codegen_gcc\src\lib.rs:28:1
   |
28 | extern crate object;
   | ^^^^^^^^^^^^^^^^^^^^
   |
   = note: candidate #1: G:\Projects\Programs\Rust\rust-lang2\build\x86_64-pc-windows-msvc\stage1\lib\rustlib\x86_64-pc-windows-msvc\lib\libobject-4bedb83f3b66d9f4.rmeta
   = note: candidate #2: G:\Projects\Programs\Rust\rust-lang2\build\x86_64-pc-windows-msvc\stage1\lib\rustlib\x86_64-pc-windows-msvc\lib\libobject-ad6a5626350974c2.rmeta

For more information about this error, try `rustc --explain E0464`.
error: could not compile `rustc_codegen_gcc` (lib) due to 1 previous error
Build completed unsuccessfully in 0:03:24
27f8efbae2bf906ea6f967dd3fe1eb0e7faf3a2e is the first bad commit
commit 27f8efbae2bf906ea6f967dd3fe1eb0e7faf3a2e
Author: WANG Rui <wangrui@loongson.cn>
Date:   Wed Jun 4 20:10:50 2025 +0800

    Bump object

```

See discussion in zulip: [#rustc-codegen-gcc > Cannot compile rustc on Windows 10 @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/386786-rustc-codegen-gcc/topic/Cannot.20compile.20rustc.20on.20Windows.2010/near/524797886)

@heiher @wesleywiser
