### PR TITLE
Fix a regression in import resolution

### LINKED ISSUE #32089: Unresolved import in glob imported modules
The latest nightly broke some imports in [my project](https://travis-ci.org/KyleMayes/easy-plugin/builds/114147602) that were working previously.

Here is a minimal example (spread out over three files):

```rust
// src/lib.rs

mod one;
pub use self::one::*;

mod two;
pub use self::two::*;

pub type Type = i32;
```

```rust
// src/one.rs

use super::{Type};
```

```rust
// src/two.rs

use super::{Type};
```

The issue is only when there is more than one of these types of imports. I'm not sure if this is a bug or I  have been relying on incorrect behavior until now.

### Meta

```
rustc 1.9.0-nightly (52e0bda64 2016-03-05)
binary: rustc
commit-hash: 52e0bda644823089f16795cc9e071cf827b4810b
commit-date: 2016-03-05
host: x86_64-unknown-linux-gnu
release: 1.9.0-nightly
```

### PR DESCRIPTION
**Pull request by jseyfried**
This fixes #32089 (caused by #31726) by deducing that name resolution has failed (as opposed to being indeterminate) in more cases.

r? @nikomatsakis

### CODE REVIEW

**Comment by jseyfried** [comment]
cc @alexcrichton

**Comment by alexcrichton** [comment]
Thanks for the quick fix @jseyfried!

**Comment by nikomatsakis** [comment]
r=me if comment is added

**Comment by jseyfried** [comment]
Fixes #32106
