### ISSUE TITLE
Broken compilation with `&(dyn Trait + '_)`

### ISSUE THREAD

**Issue by Cerber-Ursi** [rust-lang/rust#103762]
### Code

I tried this code:

```rust
pub trait AsStr {
    fn as_str(&self) -> &str;
}

fn foo(bar: &(dyn AsStr + '_)) -> &'_ str {
    bar.as_str()
}
```

I expected to see this happen: code compiles successfully.

Instead, this happened:
```
error[E0106]: missing lifetime specifier
 --> src/main.rs:5:36
  |
5 | fn foo(bar: &(dyn AsStr + '_)) -> &'_ str {
  |             -----------------      ^^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say which one of `bar`'s 2 lifetimes it is borrowed from
help: consider introducing a named lifetime parameter
  |
5 | fn foo<'a>(bar: &'a (dyn AsStr + 'a)) -> &'a str {
  |       ++++       ++              ~~       ~~

For more information about this error, try `rustc --explain E0106`.
```

### Version it worked on

It most recently worked on Rust 1.63.0.

### Version with regression

It is broken on current stable, i.e. 1.64.0.

Here's the output by `cargo-bisect-rustc`:

> searched nightlies: from nightly-2022-06-24 to nightly-2022-08-05
> regressed nightly: nightly-2022-07-15
> searched commit range: https://github.com/rust-lang/rust/compare/87588a2afd9ca903366f0deaf84d805f34469384...c2f428d2f3340a0e7d995f4726223db91b93704c
> regressed commit: https://github.com/rust-lang/rust/commit/f1a8854f9be2e5cad764d630a53d26c7b72f8162
> 
> <details>
> <summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.4</summary>
> 
> 
> Host triple: x86_64-unknown-linux-gnu
> Reproduce with:
> ```bash
> cargo bisect-rustc --end=1.64.0 -- check 
> ```
> </details>
> 

It seems to have been found previously by `gluon` developers and fixed in their own code [in this commit](https://github.com/gluon-lang/gluon/commit/f30127bf5e27520d41a654154381c2e9601d2f3e), and today popped up also [on URLO](https://users.rust-lang.org/t/possible-to-use-cargo-timings-on-a-project-that-uses-gluon/83458).

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

**Comment by csmoe** [comment]
Seems related to https://github.com/rust-lang/rust/pull/97720

**Comment by apiraino** [comment]
I think it's very close to #100615, so I'll close this as duplicate. Please feel free to reopen if it's not the case.

**Comment by apiraino** [comment]
Reverting the decision because I misunderstood the context and assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23103762.20Broken.20compilation.20with.20.60.26.28dyn.20Trait.20.2B.20'_.29.60)).

@rustbot label -I-prioritize +P-high

**Comment by BGR360** [comment]
Indeed, from what I can tell, it seems that https://github.com/rust-lang/rust/pull/97720 regressed this. Specifically, [this change here](https://github.com/rust-lang/rust/pull/97720/files?diff=unified&w=0#diff-809615be77d084b910459cf54c39f25745f5b9f8ad9e50c2a33e7fc2573686f1L761-R764).

My understanding of this change is that it stopped pushing lifetime resolution in function signatures to typeck, and instead made it so that every occurrence of `'_`, `&'_`, or `&` in the function's inputs resulted in a "new" lifetime.

So I guess rustc used to think that the `'_` in `&(dyn AsStr + '_)` was just referring to the same lifetime as the `&`. But now it is being treated the same way as, e.g., the second `&` in `(a: &str, b: &str)` would be treated.

It seems a little unfortunate that we ever accepted this. I say this because having `&(dyn Trait + '_)` doesn't really seem any different than `&Type<'_>` to me. Yet we never accepted the latter in previous versions of Rust:

```rust
struct Type<'a> { a: &'a () }

fn foo(_: &Type<'_>) -> &'_ str { loop {} }

fn main() {}
```

```
$ rustc +1.63.0 test.rs
error[E0106]: missing lifetime specifier
 --> test.rs:3:26
  |
3 | fn foo(_: &Type<'_>) -> &'_ str { loop {} }
  |           ---------      ^^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but the signature does not say which one of argument 1's 2 lifetimes it is borrowed from
help: consider introducing a named lifetime parameter
  |
3 | fn foo<'a>(_: &'a Type<'_>) -> &'a str { loop {} }
  |       ++++     ++               ~~

error: aborting due to previous error
```

I'm interested in trying to undo the regression, so I'll claim this. It seems like what I'd need to do is make the `+ '_` resolve the same way the `-> &'_ str` gets resolved. Unsure how hard that will be yet, I haven't spent much time in rustc_resolve yet.

But perhaps there's someone who thinks we should just let it regress?

@rustbot claim
@rustbot label +A-lifetimes +A-resolve

**Comment by cjgillot** [comment]
Note this other one is also broken:
```rust
pub trait AsStr {
    fn as_str(&self) -> &str;
}

fn foo(bar: &(AsStr + '_)) -> &'_ str {
    bar.as_str()
}
```

Both cases do not appear at the same place in `rustc_resolve::late`. These are not the same construct on the AST, even if they are on HIR.

**Comment by BGR360** [comment]
That's valid syntax?

**Comment by Cerber-Ursi** [comment]
That's deprecated syntax, but it's valid, yes - Rust used to have just `Trait` where it currently has `dyn Trait`.
