### ISSUE TITLE
1.98 beta regression: "cannot deduce the lifetime bound for this trait object type from context"

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#159430]
This regression was found by the 1.98 beta crater run.

```
[INFO] [stdout] error[E0228]: cannot deduce the lifetime bound for this trait object type from context
[INFO] [stdout]    --> src/experiment/mod.rs:255:41
[INFO] [stdout]     |
[INFO] [stdout] 255 |         type IntoIter<'a> = T::Iter<'a, dyn Example>
[INFO] [stdout]     |                                         ^^^^^^^^^^^
[INFO] [stdout]     |
[INFO] [stdout] help: please supply an explicit bound
[INFO] [stdout]     |
[INFO] [stdout] 255 |         type IntoIter<'a> = T::Iter<'a, dyn Example + /* 'a */>
[INFO] [stdout]     |                                                     ++++++++++
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] For more information about this error, try `rustc --explain E0228`.
```

* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/gh/asafigan.impl-iter-tuple-kind-of/log.txt

**Comment by theemathas** [comment]
Minimized:

```rust
pub trait Example {}

pub trait AsIter {
    type Iter<T: ?Sized>;
}

pub trait ExampleList {
    type IntoIter;
}

impl<T: AsIter> ExampleList for T {
    type IntoIter = T::Iter<dyn Example>;
}
```

Error output on beta:
```
error[E0228]: cannot deduce the lifetime bound for this trait object type from context
  --> src/lib.rs:12:29
   |
12 |     type IntoIter = T::Iter<dyn Example>;
   |                             ^^^^^^^^^^^
   |
help: please supply an explicit bound
   |
12 |     type IntoIter = T::Iter<dyn Example + /* 'a */>;
   |                                         ++++++++++

For more information about this error, try `rustc --explain E0228`.
error: could not compile `foo` (lib) due to 1 previous error
```

**Comment by theemathas** [comment]
Bisection result:

```
searched toolchains 3bf5c6d99bc8a0c0d5b2f69826ed4f6d256a0a21 through 7148b31956911d5d5496900bf564ca5212bf199b


********************************************************************************
Regression in d56483a91d6cf5041351a3208b8d08f98f0c8b56
********************************************************************************

Attempting to search unrolled perf builds
ERROR: couldn't find perf build comment
```

Regressed in #129543. cc @fmease, @lcnr

**Comment by fmease** [comment]
This breakage is intentional, see item 2 in section *Changes Made* in RUST-129543. I'm looking into sending a downstream patch later.

**Comment by fmease** [comment]
Although I'm very surprised that this wasn't caught by the many crater runs I issued in that PR...

**Comment by fmease** [comment]
Handled downstream in https://github.com/asafigan/impl-iter-tuple-kind-of/pull/1. Closing as completed.
