### ISSUE TITLE
Unable to compile syntex_syntax using Rust 1.41

### ISSUE THREAD

**Issue by yaa110** [rust-lang/rust#68729]
Unfortunately, syntex_syntax is not maintained and is not compiled using rust 1.41:

```rust
   Compiling syntex_syntax v0.58.1
error[E0423]: expected function, tuple struct or tuple variant, found struct `ast::Name`
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/syntex_syntax-0.58.1/src/symbol.rs:146:27
    |
146 |                       name: ast::Name($index),
    |                             ^^^^^^^^^
...
165 | / declare_keywords! {
166 | |     // Invalid identifier
167 | |     (0,  Invalid,        "")
168 | |
...   |
231 | |     (56, CrateRoot, "{{root}}")
232 | | }
    | |_- in this macro invocation

   Compiling clap v2.33.0
   Compiling nom v3.2.1
   Compiling parking_lot v0.10.0
error: aborting due to previous error

For more information about this error, try `rustc --explain E0423`.
error: could not compile `syntex_syntax`.
warning: build failed, waiting for other jobs to finish...
error: build failed
make[1]: *** [objs/Makefile:1314: cargo] Error 101
```

```
# rustc --version
rustc 1.41.0 (5e1a79984 2020-01-27)

# uname -a
Linux 6b52ecd4014b 5.3.18-1-MANJARO #1 SMP PREEMPT Wed Dec 18 18:34:35 UTC 2019 x86_64 GNU/Linux
```

**Comment by jonas-schievink** [comment]
It builds fine on 1.40.

FWIW this is not the most up to date version, which is 0.59.1 and builds fine on 1.41.

**Comment by pnkfelix** [comment]
Hmm I hadn't noticed that syntex_syntax had been updated in that manner; I just saw that it has not been maintained in three years (see [their readme](https://github.com/serde-deprecated/syntex))

This problem is [expected fallout](https://github.com/rust-lang/rust/pull/65785#issuecomment-546499161) from PR #65785

**Comment by pnkfelix** [comment]
triage: P-low, with intent to close. Leaving nominated because I want to at least discuss 1. whether we need/want to collect data on instances of such breakage, and 2. whether we were too aggressive in deciding that going straight to an error without some mitigating mechanism was too aggressive.

**Comment by yaa110** [comment]
syntex_syntax was used in old versions of bindgen crate and is not maintained. So, this issue could be closed. However, this kind of known breakage should be declared in changelog blog posts of rustlang update.

**Comment by pnkfelix** [comment]
Removing nomination label and closing.

As I wrote on [zulip](https://zulip-archive.rust-lang.org/131828tcompiler/40525premeetingtriage2020030554818.html#189733005): 
>  this was not such a big deal in the end. The main question I would want resolved is whether we actually documented this breaking change somewhere visible (release notes from release blog post or something similar). But that does not need to be a discussion during the synchronous T-compiler meeting.

**Comment by Mawfyy** [comment]
I can reproduce this error in rust 1.73.0, there's any solution to this?

**Comment by ShipmasterKyle** [comment]
This can repoduced on rust 1.76.0 as well. Is there a solution? 

We could attempt syntex_sytntax to an older version but I'm not sure that it'll solve the issue.
