### ISSUE TITLE
artifact-app fails to "cargo install" with nightly

### ISSUE THREAD

**Issue by talios** [rust-lang/rust#47480]
Hi all,

I initially raised this at https://github.com/vitiral/artifact/issues/227 and was redirected to raise as a potential rust-nightly issue.

This is on OSX High Sierra - Installing `artifact` via `cargo +stable install artifact-app` works, whereas `cargo +nightly install artifact-app` fails to build with:

```rust
error[E0283]: type annotations required: cannot resolve `std::path::Component<'_>: std::convert::AsRef<_>`
  --> src/utils.rs:40:38
   |
40 |                     remaining.push(a.as_ref());
   |                                      ^^^^^^

error: aborting due to previous error
```

as the compilation error.

**Comment by sfackler** [comment]
Caused by #46985.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/48716.
