### ISSUE TITLE
Nightly regression for E0619

### ISSUE THREAD

**Issue by Keats** [rust-lang/rust#47451]
This appeared in Travis (stable and beta still work)
```
$ rustc --version
rustc 1.25.0-nightly (3f92e8d89 2018-01-14)
````

The error:
```bash
error[E0619]: the type of this value must be known in this context
  --> components/content/src/file_info.rs:11:42
   |
11 |         let component = section.as_ref().to_string_lossy();
   |                                          ^^^^^^^^^^^^^^^
```

Link to Travis: https://travis-ci.org/Keats/gutenberg/builds/328770657?utm_source=github_status&utm_medium=notification

It does compile fine with `rustc 1.25.0-nightly (b5392f545 2018-01-08)` but I sadly can't download other nightlies atm to pin it down.

**Comment by ExpHP** [comment]
Probably due to https://github.com/rust-lang/rust/pull/46985 ?

**Comment by alexcrichton** [comment]
The libs team discussed this issue today and concluded that we're going to close this. @Keats if you have difficulty updating though please let us know!

We're hoping we can head off errors like this in the future with https://github.com/rust-lang/rust/issues/36443
