### ISSUE TITLE
Combination of try blocks, never type, and rustfmt is broken

### ISSUE THREAD

**Issue by kryptan** [rust-lang/rust#140361]
Consider this code:

```rust
#![feature(never_type, try_blocks)]

fn main() {
    let _: Result<!, ()> = try {
        ();
        return
    };
}
```

It compiles.

Rustfmt adds a semicolon here:

```rust
#![feature(never_type, try_blocks)]

fn main() {
    let _: Result<!, ()> = try {
        ();
        return;
    };
}
```

This causes a compilation error:

```
   Compiling playground v0.0.1 (/playground)
error[E0271]: type mismatch resolving `<Result<!, ()> as Try>::Output == ()`
 --> src/main.rs:7:5
  |
7 |     };
  |     ^ expected `()`, found `!`
  |
  = note: expected unit type `()`
                  found type `!`

For more information about this error, try `rustc --explain E0271`.
error: could not compile `playground` (bin "playground") due to 1 previous error
```

I'm not sure if rustfmt shouldn't add a semicolon here or if rustc should accept a semicolon.

[Playground link](
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=df10b45fe72c85ce80126ed5fbd9130f)

### Meta
```
Nightly channel

Build using the Nightly version: 1.88.0-nightly

(2025-04-26 10fa3c449f6b1613b352)
```

**Comment by moxian** [comment]
This is rustfmt bug, so should be filed under https://github.com/rust-lang/rustfmt/issues
Let me try moving it (i'm not sure i have perms)
@rustbot transfer rustfmt

**Comment by jieyouxu** [comment]
Hi, please file this bug against https://github.com/rust-lang/rustfmt/issues, as rustfmt is developed in a separate repo. Thank you.
