### ISSUE TITLE
Confusing error message with `panic!()` and `impl trait`

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#66523]
[The following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e089ab377a6d1c02fcf034827abec591):

```rust
fn bar() -> Vec<impl Copy> {
    panic!()
}
```

Currently gives the following error:

```
error[E0283]: type annotations required: cannot resolve `_: std::marker::Copy`
 --> src/lib.rs:1:17
  |
1 | fn bar() -> Vec<impl Copy> {
  |                 ^^^^^^^^^
  |
  = note: the return type of a function must have a statically known size
```

This message has a weird span, and doesn't give any clue that the problem lies with the call to `panic!`

**Comment by Centril** [comment]
(Sidenote: "cannot resolve" trips me up every time since it feels like it talking about name resolution, not type checking)

**Comment by estebank** [comment]
Current output is a slight regression introduced by #68195:

```
error[E0720]: opaque type expands to a recursive type
 --> src/lib.rs:1:17
  |
1 | fn bar() -> Vec<impl Copy> {
  |                 ^^^^^^^^^ expands to a recursive type
  |
  = note: type resolves to itself
```

**Comment by estebank** [comment]
> (Sidenote: "cannot resolve" trips me up every time since it feels like it talking about name resolution, not type checking)

Would "cannot fulfill `_: std::marker::Copy`" be a better wording?

**Comment by Centril** [comment]
@estebank Maybe "cannot satisfy `_: Copy`" (we use "satisfy" more commonly I think)?

**Comment by mcgoo** [comment]
Same issue I think but with a different diagnostic: `the trait bound '(): std::future::Future' is not satisfied`

```
fn foo() -> impl std::future::Future<Output = i32> {
    unimplemented!();
}
```
gives
```
error[E0277]: the trait bound `(): std::future::Future` is not satisfied
 --> src/lib.rs:1:13
  |
1 | fn foo() -> impl std::future::Future<Output = i32> {
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::future::Future` is not implemented for `()`
2 |     unimplemented!();
  |     ----------------- consider removing this semicolon
  |
  = note: the return type of a function must have a statically known size
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```
I expected it would do the same with `async fn foo() -> i32 { panic!(); }`  but it works fine.

**Comment by nrxus** [comment]
I just recently hit this, and I don't believe that it is related to the `panic`:
```rust
struct MarkerHolder<T> {
    _marker: std::marker::PhantomData<*const T>
}

fn make_marker() -> MarkerHolder<impl std::fmt::Display> {
    MarkerHolder {
        _marker: std::marker::PhantomData,
    }
}
```

fails with:
```
  |
5 | fn make_marker() -> MarkerHolder<impl std::fmt::Display> {
  |                                  ^^^^^^^^^^^^^^^^^^^^^^ expands to a recursive type
  |
  = note: type resolves to itself
```

Could someone help me understand if this error is intentional just worded weirdly (I don't see how my return type is recursive), or if this kind of code should compile?

**Comment by estebank** [comment]
Current output:

```
error[E0720]: cannot resolve opaque type
 --> src/lib.rs:1:17
  |
1 | fn bar() -> Vec<impl Copy> {
  |                 ^^^^^^^^^ cannot resolve opaque type
2 |     panic!()
  |     -------- this returned value is of `!` type
  |
  = help: this error will resolve once the item's body returns a concrete type

error[E0277]: `()` is not a future
 --> src/lib.rs:1:13
  |
1 | fn foo() -> impl std::future::Future<Output = i32> {
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `()` is not a future
2 |     unimplemented!();
  |     ----------------- consider removing this semicolon
  |
  = help: the trait `Future` is not implemented for `()`

error[E0720]: cannot resolve opaque type
 --> src/lib.rs:5:34
  |
5 |   fn make_marker() -> MarkerHolder<impl std::fmt::Display> {
  |                                    ^^^^^^^^^^^^^^^^^^^^^^ recursive opaque type
6 | /     MarkerHolder {
7 | |         _marker: std::marker::PhantomData,
8 | |     }
  | |_____- returning here with type `MarkerHolder<impl std::fmt::Display>`

```

**Comment by jyn514** [comment]
Triage: the current output is
```
error[E0720]: cannot resolve opaque type
 --> src/lib.rs:1:17
  |
1 | fn bar() -> Vec<impl Copy> {
  |                 ^^^^^^^^^ cannot resolve opaque type
2 |     panic!()
  |     -------- this returned value is of `!` type
  |
  = help: this error will resolve once the item's body returns a concrete type
```
Which seems pretty good to me - should this be closed as a duplicate of https://github.com/rust-lang/rust/issues/69882 ?

**Comment by estebank** [comment]
The only thing I'd change it so change "item's body" with "`bar`'s body" or "the function's body", but otherwise this is good enough to close the ticket.
