### ISSUE TITLE
Using macro 2.0 to generate a module does not allow access to items

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#47797]
I see no reason why the following code shouldn't work on the latest nightly,

```rust
#![feature(decl_macro)]

macro foo($mod_name:ident) {
    pub mod $mod_name {
        pub const BAR: u32 = 1;
    }
}

foo!(FooMod);

fn main() {
	println!("{}", FooMod::BAR);
}
```

yet I get an odd error.

```
error[E0425]: cannot find value `BAR` in module `FooMod`
  --> src/main.rs:12:25
   |
12 |     println!("{}", FooMod::BAR);
   |                            ^^^ not found in `FooMod`
help: possible candidate is found in another module, you can import it into scope
   |
3  | use FooMod::BAR;
   |

error: aborting due to previous error
```

Perhaps I'm missing something about how hygiene works in macros 2.0?

**Comment by dtolnay** [comment]
Thanks! I believe this is a duplicate of #46342. The `BAR` defined in the macro is protected by hygiene 2.0 and cannot be named from the outside the macro. As a workaround, it should work if the name of `BAR` originates from outside the macro.

```rust
macro foo($mod_name:ident, $bar:ident) {
    pub mod $mod_name {
        pub const $bar: u32 = 1;
    }
}

foo!(FooMod, BAR);
```

**Comment by alexreg** [comment]
@dtolnay Ah okay, thanks. Looks like we need hygiene opt-out desperately. Do you know the state of that?

**Comment by dtolnay** [comment]
Yep the hygiene opt-out is tracked in #39412 where it talks about "hygiene bending".
