### PR TITLE
`alloc`: make `vec!` unavailable under `no_global_oom_handling`

### PR DESCRIPTION
**Pull request by ojeda**
`alloc`: make `vec!` unavailable under `no_global_oom_handling`

The `vec!` macro has 3 rules, but two are not usable under
`no_global_oom_handling` builds of the standard library
(even with a zero size):

```rust
let _ = vec![42];    // Error: requires `exchange_malloc` lang_item.
let _ = vec![42; 0]; // Error: cannot find function `from_elem`.
```

Thus those two rules should not be available to begin with.

The remaining one, with an empty matcher, is just a shorthand for
`new()` and may not make as much sense to have alone, since the
idea behind `vec!` is to enable `Vec`s to be defined with the same
syntax as array expressions. Furthermore, the documentation can be
confusing since it shows the other rules.

Thus perhaps it is better and simpler to disable `vec!` entirely
under `no_global_oom_handling` environments, and let users call
`new()` instead:

```rust
let _: Vec<i32> = vec![];
let _: Vec<i32> = Vec::new();
```

Notwithstanding this, a `try_vec!` macro would be useful, such as
the one introduced in https://github.com/rust-lang/rust/pull/95051.

If the shorthand for `new()` is deemed worth keeping on its own,
then it may be interesting to have a separate `vec!` macro with
a single rule and different, simpler documentation.

Signed-off-by: Miguel Ojeda <ojeda@kernel.org>

### CODE REVIEW

**Comment by ojeda** [comment]
cc @dpaoliello @Ericson2314 @Xuanwo @joshtriplett

**Comment by Ericson2314** [comment]
A fine lines below there is a 
```rust
#[cfg(test)]
macro_rules! vec {
```
too. I don't think we've bothered to run tests with oom panicking disabled, but for sake of a future where we do, can we modify that cfg too?

**Comment by ojeda** [comment]
If I understand correctly, you want to prevent that somebody writes `vec![]` (the empty one) in a test under `no_global_oom_handling`, right? Makes sense -- pushed!

**Review by Ericson2314 — APPROVED** [review]

**Comment by ojeda** [comment]
Reworded commit message a bit better -- no changes.

**Review by Xuanwo — APPROVED** [review]

File: library/alloc/src/macros.rs [hunk 1]
```diff
@@ -34,7 +34,7 @@
 /// be mindful of side effects.
 ///
 /// [`Vec`]: crate::vec::Vec
-#[cfg(not(test))]
+#[cfg(all(not(no_global_oom_handling), not(test)))]
```
Comment (Mark-Simulacrum) [inline library/alloc/src/macros.rs:37]: Small nit: I might prefer not(any(...)) here, which I think reads a little nicer?

I generally find it faster to digest or'd lists myself, but it probably varies from person to person, so feel free to resolve if you disagree.

**Comment by Mark-Simulacrum** [comment]
r=me, modulo the nit if you agree with it.

File: library/alloc/src/macros.rs (hunk 1 above)
Comment (ojeda) [reply library/alloc/src/macros.rs:37]: I used this one since `not(no_global_oom_handling)` is the one normally found elsewhere on its own (since it is used to disable things) and also makes it a prefix of the other (so perhaps it is easier to see it is the same thing but for `test`/`!test`):

```rust
#[cfg(all(not(no_global_oom_handling), not(test)))]
#[cfg(all(not(no_global_oom_handling), test))]
```

From a quick look, there are currently 2 `not(any(...))`, and 4 `all(not(...))` (for `no_global_oom_handling`/`test`).

I am fine with either, so please let me know which one you prefer given the above.

(Personally, I think multiple `cfg`s would be more readable and easier for diff/VCS purposes; and I hope for `&&`/`and` operators, but... :)

Comment (Mark-Simulacrum) [reply library/alloc/src/macros.rs:37]: Hm, yeah, not sure. Let's leave it as-is for now -- I can see either direction being beneficial. Multiple cfgs would also be fine I think (they don't work when you want an `or` but for `and` I think should work fine).
