### PR TITLE
Crate store cleanup

### PR DESCRIPTION
**Pull request by Mark-Simulacrum**
Each commit mostly stands on its own.

Most of the diff is lifetime-related and uninteresting.

### CODE REVIEW

File: src/Cargo.lock [hunk 1]
```diff
@@ -2115,6 +2115,7 @@ dependencies = [
  "rustc 0.0.0",
  "rustc_data_structures 0.0.0",
  "rustc_incremental 0.0.0",
+ "rustc_metadata 0.0.0",
```
Comment (alexcrichton) [inline src/Cargo.lock]: Could this and the dependency for `rustc_resolve` be avoided? Keeping these crates decoupled keeps incremental compile times down if the crates are being modified and helps parallel builds in general

File: src/librustc_codegen_utils/link.rs [hunk 2]
```diff
@@ -61,7 +62,7 @@ pub fn find_crate_name(sess: Option<&Session>,
                        attrs: &[ast::Attribute],
                        input: &Input) -> String {
     let validate = |s: String, span: Option<Span>| {
-        cstore::validate_crate_name(sess, &s, span);
+        creader::validate_crate_name(sess, &s, span);
```
Comment (alexcrichton) [inline src/librustc_codegen_utils/link.rs]: For example, could this move to `rustc` or to a different crate? The `rustc_metadata` crate is quite heavyweight and pulling it in for one function may not quite be worth it

File: src/Cargo.lock (hunk 1 above)
Comment (Mark-Simulacrum) [reply src/Cargo.lock]: I can, yes -- I'd rather not though. metadata compiles in ~10 seconds for me at least on a non-incremental build IIRC so it's not too heavy weight; generally speaking it feels like optimizing dependency edges between crates like that isn't the right thing to be doing; it's not tenable long-term and generally feels somewhat wrong to me.

But if you think this is a serious hit I can spend some time pulling things back into librustc, though some part of me thinks that we should be actively trying to reduce the size of librustc, syntax, and librustc_mir so that they compile faster as today each takes >100 seconds on clean builds even on good hardware.

Comment (alexcrichton) [reply src/Cargo.lock]: Hm are you sure it compiles that fast? [This travis log](https://travis-ci.org/rust-lang/rust/jobs/411489565) claims 152s for `rustc_metadata` (and 373s for `rustc`), and locally it just took 76s for `rustc_metadata` and and 159s for `rustc`. I think 10s is vastly underestimating how long it takes to build this crate (unless you've got hyper-speed hardware!)

I agree though yeah this shouldn't go in librustc, this could perhaps go in a new utils crate or something like that (not putting things in librustc is good).

Comment (Mark-Simulacrum) [reply src/Cargo.lock]: Sure we can create "utils" crates but ultimately then what it feels like we're going to end up with is librustc_metadata_utils, librustc_target_utils, librustc_typeck_utils etc for those functions which are currently somewhat out of place in librustc/middle (often used by driver and metadata, or typeck and driver, or some other pair of libraries with one always ultimately depending on the other); or at least that's been my impression while trying to do some mild cleanup to middle.

I'll see if it makes sense to have a util crate that essentially just depends on librustc and then put this and some similar functions in there (for now probably adding a comment that if you find yourself wanting to add a dependency other than rustc/syntax to it you probably shouldn't; the timing results below do seem to indicate that metadata is a bit more hefty than I had expected.

----

Looking at a build I just did it's actually quite painful that metadata takes so long to build on Travis: as a loose statistic, metadata is ~10k lines of code and librustc is ~100k, but on Travis they build in around a 2.6x difference (400s for librustc and 150s for metadata in stage1).

Locally in stage 1 I see librustc build in 270 seconds and metadata in 60 seconds -- it does look like it's a little heavier than I thought; I might've been recalling a check build.

It's also rather surprising that metadata builds in 114 seconds in stage0 but 150 seconds in stage 1. That's a rather significant disparity!

Comment (varkor) [reply src/Cargo.lock]: Ah, I didn't even consider this. I'll pay more careful attention to the dependencies next time.

r? @alexcrichton

**Comment by Mark-Simulacrum** [comment]
I've removed the dependency on metadata from codegen utils but the resolve dependency is more deeply rooted; fundamentally that's because resolve is actually guiding metadata loading/crate registration. The previous way of avoiding the dep was to have a trait in librustc and then resolve would store a trait object which I can return to but doesn't feel quite right.

**Comment by kennytm** [comment]
```
[01:09:28] error[E0053]: method `late_callback` has an incompatible type for trait
[01:09:28]   --> /cargo/registry/src/github.com-1ecc6299db9ec823/rls-rustc-0.4.0/src/lib.rs:56:5
[01:09:28]    |
[01:09:28] 56 | /     fn late_callback(&mut self,
[01:09:28] 57 | |                      a: &CodegenBackend,
[01:09:28] 58 | |                      b: &getopts::Matches,
[01:09:28] 59 | |                      c: &Session,
[01:09:28] ...  |
[01:09:28] 65 | |         RustcDefaultCalls.late_callback(a, b, c, d, e, f, g)
[01:09:28] 66 | |     }
[01:09:28]    | |_____^ expected struct `rustc_metadata::cstore::CStore`, found trait rustc::middle::cstore::CrateStore
[01:09:28]    |
[01:09:28]    = note: expected type `fn(&mut ShimCalls, &dyn rustc_codegen_utils::codegen_backend::CodegenBackend, &getopts::Matches, &rustc::session::Session, &rustc_metadata::cstore::CStore, &rustc::session::config::Input, &std::option::Option<std::path::PathBuf>, &std::option::Option<std::path::PathBuf>) -> rustc_driver::Compilation`
[01:09:28]               found type `fn(&mut ShimCalls, &dyn rustc_codegen_utils::codegen_backend::CodegenBackend, &getopts::Matches, &rustc::session::Session, &dyn rustc::middle::cstore::CrateStore, &rustc::session::config::Input, &std::option::Option<std::path::PathBuf>, &std::option::Option<std::path::PathBuf>) -> rustc_driver::Compilation`
[01:09:28]
[01:09:28] error: aborting due to previous error
[01:09:28]
[01:09:28] For more information about this error, try `rustc --explain E0053`.
[01:09:28] [RUSTC-TIMING] rls_rustc test:false 1.737
[01:09:28] error: Could not compile `rls-rustc`.
```
