### ISSUE TITLE
Rust 1.18 regression, size of Self cannot be statically determined

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#41805]
https://github.com/AskePit/note_gen

```
101 brian@ip-10-145-43-250:~/dev/note_gen⟫ git log -1
commit 9cb62bd28f5bfe919ed27b267500e596af3d290b
Author: Shalakin Nikolay <askepit@gmail.com>
Date:   Wed Mar 1 22:02:16 2017 +0300

    Update README.md
```

```
brian@ip-10-145-43-250:/mnt2/dev⟫ rustc +beta -Vv
rustc 1.18.0-beta.1 (4dce67253 2017-04-25)
binary: rustc
commit-hash: 4dce67253d67785c74c8d270c38d774edd0deed8
commit-date: 2017-04-25
host: x86_64-unknown-linux-gnu
release: 1.18.0-beta.1
LLVM version: 3.9
```

```
brian@ip-10-145-43-250:~/dev/note_gen⟫ cargo +beta test
   Compiling libc v0.2.20
   Compiling rand v0.3.15
   Compiling note_gen v0.1.0 (file:///mnt2/dev/note_gen)
error[E0161]: cannot move a value of type Self: the size of Self cannot be statically determined
  --> src/main.rs:12:16
   |
12 |            String::from(Self::rand().to_str())
   |                         ^^^^^^^^^^^^

error: aborting due to previous error

error: Could not compile `note_gen`.

To learn more, run the command again with --verbose.
```

cc @AskePit

**Comment by Mark-Simulacrum** [comment]
Introduced in 910c4816fdee01a1299d11a5e85ebb4aceee6d1a -- rollup PR #41246. Most likely caused by #41232, cc @arielb1

**Comment by arielb1** [comment]
This looks correct. After all, this variant does not work on stable too:

```Rust
trait Item {
	fn to_str(&self) -> &str;
	fn count() -> i32;
	fn rand() -> Self;
	fn rand_str() -> String {
		let x = Self::rand(); //~ ERROR the trait bound `Self: std::marker::Sized` is not satisfied
		String::from(x.to_str())
	}
}
```

I don't think you can actually *implement* this on an unsized type, however.

**Comment by nikomatsakis** [comment]
I agree that the new error seems correct.

**Comment by nagisa** [comment]
It seems like the behaviour is intended. If this is indeed a regression we should document it in the release notes.

**Comment by brson** [comment]
I noted it on the relnotes thread. Thanks for investigating.
