### ISSUE TITLE
Unsized extern statics no longer compile

### ISSUE THREAD

**Issue by mjbshaw** [rust-lang/rust#55239]
This is likely due to #55004. Consider the following code:

```rust
#![feature(extern_types)]

extern "C" {
    pub type StartFn;
    pub static start: StartFn;
}
```

This code compiles with `rustc 1.31.0-nightly (e7f5d4805 2018-10-18)`, but fails with `rustc 1.31.0-nightly (78ff609d7 2018-10-19)`. Error message from `rustc`:

```
error[E0277]: the size for values of type `StartFn` cannot be known at compilation time
 --> t.rs:5:23
  |
5 |     pub static start: StartFn;
  |                       ^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `StartFn`
  = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

I think this code should still be accepted, and I believe #55004 accidentally broke this. One of the purposes of the `extern_types` feature is to better interact with C code like this:

```c
struct SomeOpaqueType;
extern struct SomeOpaqueType SomeGlobal;
```

I think Rust should accept unsized extern statics that use an extern type (possibly wrapped in a transparent newtype).

cc @oli-obk

**Comment by oli-obk** [comment]
I don't see how this is a regression from stable as you need a feature gate to replicate the regression.

That said, I do think we should fix this for extern types. Should be doable by using the `struct_tail` method on the type and checking the final type for `is_extern() || is_sized()` instead of doing the current check

**Comment by mjbshaw** [comment]
Thanks for the quick feedback and guidance on how to fix! If you don't mind, I'd like to take a stab at fixing this.

**Comment by mjbshaw** [comment]
[I've created a pull request (#55257)](https://github.com/rust-lang/rust/issues/55257) that should fix this, but [GitHub is reporting a 404](https://user-images.githubusercontent.com/1204698/47276706-eed6b480-d56d-11e8-9b1d-c704cc60e9d5.png) when I attempt to view the pull request. [Attempting to create a new pull request fails because GitHub tells me I've already done that](https://user-images.githubusercontent.com/1204698/47276739-2b0a1500-d56e-11e8-90ec-411de6de34b8.png) and can't create a duplicate pull request.

I'm going to create a new branch and a new pull request. Apologies if my original pull request causes any issues.
