### ISSUE TITLE
Incorrectly suggests replacing end characters of function call with double quotes

### ISSUE THREAD

**Issue by berrymot** [rust-lang/rust#125595]
### Code

```Rust
fn example() -> char { 't' }
let mut s = "rus".to_string();
s += example();
```

### Current output

```Shell
error[E0308]: mismatched types
   --> src\tools.rs:100:10
    |
100 |     s += example();
    |          ^^^^^^^^^ expected `&str`, found `char`
    |
help: if you meant to write a string literal, use double quotes
    |
100 |     s += "xample(";
    |          ~       ~
```

### Desired output

```Shell
error[E0308]: mismatched types
   --> src\tools.rs:100:10
    |
100 |     s += example();
    |          ^^^^^^^^^ expected `&str`, found `char`
    |
help: [something better]
    |
100 |     s += &example().to_string();
    |          +         ++++++++++++
```

### Rust Version

```Shell
rustc 1.80.0-nightly (78a775127 2024-05-11)
binary: rustc
commit-hash: 78a77512702ab786f6f9345872d36d852454612c
commit-date: 2024-05-11
host: x86_64-pc-windows-msvc
release: 1.80.0-nightly
LLVM version: 18.1.4
```

**Comment by fmease** [comment]
has to have regressed in #122966
