### ISSUE TITLE
"overflow evaluating the requirement", reaching recursion limit

### ISSUE THREAD

**Issue by elmarco** [rust-lang/rust#113160]
<!--
Thank you for filing a regression report! 🐛 A regression is something that changed between versions of Rust but was not supposed to.

Please provide a short summary of the regression, along with any information you feel is relevant to replicate it.
-->

### Code

I tried this code:

```rust
fn main() {
    let _ = vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
        vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
            vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
                vec![vec![vec![vec![vec![vec![vec![vec![vec![0u8]]]]]]]]],
            ]]]]]]]]]]],
        ]]]]]]]]]]],
    ]]]]]]]]]]];
    let _ = vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
        vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
            vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
                vec![vec![vec![vec![vec![vec![vec![vec![vec![0u8]]]]]]]]],
            ]]]]]]]]]]],
        ]]]]]]]]]]],
    ]]]]]]]]]]];
    let _ = vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
        vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
            vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
                vec![vec![vec![vec![vec![vec![vec![vec![vec![0u8]]]]]]]]],
            ]]]]]]]]]]],
        ]]]]]]]]]]],
    ]]]]]]]]]]];
    let _ = vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
        vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
            vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
                vec![vec![vec![vec![vec![vec![vec![vec![vec![0u8]]]]]]]]],
            ]]]]]]]]]]],
        ]]]]]]]]]]],
    ]]]]]]]]]]];
    let _ = vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
        vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
            vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
                vec![vec![vec![vec![vec![vec![vec![vec![vec![0u8]]]]]]]]],
            ]]]]]]]]]]],
        ]]]]]]]]]]],
    ]]]]]]]]]]];
    // drop the following line to compile succesfully
    let _ = vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
        vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
            vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![vec![
                vec![vec![vec![vec![vec![vec![vec![vec![vec![0u8]]]]]]]]],
            ]]]]]]]]]]],
        ]]]]]]]]]]],
    ]]]]]]]]]]];
}
```

I expected to see this happen: compiles successfully.

Instead, this happened: 

```
error[E0275]: overflow evaluating the requirement `NonNull<Vec<Vec<Vec<Vec<Vec<Vec<...>>>>>>>: Unpin`
    |
    = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`test`)
...
```


### Version it worked on

Stable `rustc 1.70.0 (90c541806 2023-05-31)` compiles succesfully.

### Version with regression

Nightly `rustc 1.72.0-nightly (5ea666864 2023-06-27)` and earlier fails.

After git bisect, the initial commit that fails is: 644818351b9 "ensure !Unpin types do not get noalias"

<!--
If you know when this regression occurred, please add a line like below, replacing `{channel}` with one of stable, beta, or nightly.

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged
-->

**Comment by Nilstrieb** [comment]
The fix here is to increase the recursion limit (as suggested by the error) for deeply nested code like this. We cannot really promise backwards compatibility here as arbitrary changes like the one that regressed here can affect it.
small note: if you really used git bisect, you can use `cargo-bisect-rustc` instead next time, which is a few orders of magnitude faster :)

**Comment by elmarco** [comment]
Hi @Nilstrieb,  I understand reaching recursion limits is not a bug. However, was this really an intended side-effect of the commit https://github.com/rust-lang/rust/commit/644818351b95c7a50eb05d73164cc6f4480ce9e7 ? 

Also did you notice my comment that if any of those line is removed / commented out, it compiles successfully?

Hence it doesn't really look like a recursion issue to me, more like a recursion count leak somehow. But I may be missing something.

cc @GuillaumeGomez  @zeenix

**Comment by GuillaumeGomez** [comment]
Knowing the full context (commenting some code **around** the various `vec![]` allows sometimes to fix the reached limit) makes me think that @elmarco's concern is valid here. I think there is a count leak.

> Also did you notice my comment that if any of those line is removed / commented out, it compiles successfully?

I think you forgot this part in your original comment. ;)
