### ISSUE TITLE
Making `unaligned_references` a hard error broke derives on packed structs without warning

### ISSUE THREAD

**Issue by LegionMammal978** [rust-lang/rust#110645]
I tried this code:

```rust
#[derive(Clone)]
pub struct Foo;

#[derive(Clone)]
#[repr(packed)]
pub struct Bar(Foo);
```

I expected to see this happen: A deny-by-default `unaligned_references` lint (or similar) in Rust 1.68.2, and a hard error in Rust 1.69.0.

Instead, this happened: No lint in Rust 1.68.2, and a hard error in Rust 1.69.0:
```rust
error[E0507]: cannot move out of `self` which is behind a shared reference
 --> src/lib.rs:6:16
  |
4 | #[derive(Clone)]
  |          ----- in this derive macro expansion
5 | #[repr(packed)]
6 | pub struct Bar(Foo);
  |                ^^^ move occurs because `self.0` has type `Foo`, which does not implement the `Copy` trait
  |
  = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)

```

(This issue was originally reported by @UncombedCoconut, who found that the bbchallenge [`decider-finite-automata-reduction`](https://github.com/bbchallenge/bbchallenge-deciders/tree/d0379d3b8f92324097ab964894d78e18abd5f394/decider-finite-automata-reduction) crate no longer compiles in 1.69.0, due to the use of derive macros on a packed struct.)

### Meta
`rustc --version --verbose`:
```
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0
LLVM version: 15.0.7
```

**Comment by apiraino** [comment]
This is something that could be handled in the release notes ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/.23110645.20.28partly.29.20missed.20the.20relnotes.3F)).

@rustbot label -I-prioritize

**Comment by Enselic** [comment]
Triage: It does not seem like this was added to release notes. But at this point, no one is going to such old release notes anyway. Let's close as won't fix. Keeping this issue open won't do any good.
