### PR TITLE
Don't bind hidden types when searching for matching impls

### LINKED ISSUE #93788: ICE: glacier fixed/62529-07.rs
### Code
from glaicer `fixed/62529-07.rs`
```Rust
struct D;

trait Tr {
    type It;
    fn foo(self) -> Option<Self::It>;
}

impl<'a> Tr for &'a D {
    type It = ();
    fn foo(self) -> Option<()> { None }
}

fn run<F>(f: F)
    where for<'a> &'a D: Tr,
          F: Fn(<&D as Tr>::It),
{
    let d = &D;
    while let Some(i) = d.foo() {
        f(i);
    }
}

fn main() {
    run(|_| {});
}
```

### Error output

```
error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:12 ~ 62529_07[da54]::run), const_param_did: None }) (end of phase transition to Optimization) at bb3[2]:
                                encountered `Assign(((_9.0: <&D as Tr>::It), const ()))` with incompatible types:
                                left-hand side has type: <&D as Tr>::It
                                right-hand side has type: ()
  --> ./62529-07.rs:19:9
   |
19 |         f(i);
   |         ^^^^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:120:36

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1176:13
```

````
searched toolchains 734368a200904ef9c21db86c595dc04263c87be0 through 0c292c9667f1b202a9150d58bdd2e89e3e803996


********************************************************************************
Regression in e7cc3bddbe0d0e374d05e7003e662bba1742dbae
********************************************************************************
````
cc @oli-obk   / https://github.com/rust-lang/rust/pull/92007

<details><summary><strong>Backtrace</strong></summary>
<p>

```
error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:12 ~ 62529_07[da54]::run), const_param_did: None }) (end of phase transition to Optimization) at bb3[2]:
                                encountered `Assign(((_9.0: <&D as Tr>::It), const ()))` with incompatible types:
                                left-hand side has type: <&D as Tr>::It
                                right-hand side has type: ()
  --> ./62529-07.rs:19:9
   |
19 |         f(i);
   |         ^^^^
   |
   = note: delayed at compiler/rustc_const_eval/src/transform/validate.rs:120:36

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1176:13
stack backtrace:
   0:     0x7fa5918569fc - std::backtrace_rs::backtrace::libunwind::trace::hef696c91488c46df
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fa5918569fc - std::backtrace_rs::backtrace::trace_unsynchronized::h76c93ef0698d26b2
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fa5918569fc - std::sys_common::backtrace::_print_fmt::h93575aa503bf6e1b
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7fa5918569fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h40967adecfbc037b
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7fa5918b80dc - core::fmt::write::h03044e853df7d223
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/core/src/fmt/mod.rs:1190:17
   5:     0x7fa591846d28 - std::io::Write::write_fmt::h86bffabfad56f13c
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/io/mod.rs:1657:15
   6:     0x7fa59185a977 - std::sys_common::backtrace::_print::hd28d8aed16472cc0
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7fa59185a977 - std::sys_common::backtrace::print::h8f98cdd641cb45a3
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7fa59185a977 - std::panicking::default_hook::{{closure}}::h729dcf0a13bd0685
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/panicking.rs:295:22
   9:     0x7fa59185a63f - std::panicking::default_hook::h5f6c637024d9ad69
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/panicking.rs:314:9
  10:     0x7fa59203c681 - rustc_driver[a83f25a8e01ca780]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fa59185b255 - std::panicking::rust_panic_with_hook::h46cff6766bf99e7c
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/panicking.rs:702:17
  12:     0x7fa59185af07 - std::panicking::begin_panic_handler::{{closure}}::h0e775b2aa2b67693
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/panicking.rs:588:13
  13:     0x7fa591856ea4 - std::sys_common::backtrace::__rust_end_short_backtrace::h1863dd104b065b9d
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x7fa59185ac09 - rust_begin_unwind
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/panicking.rs:584:5
  15:     0x7fa591822b93 - core::panicking::panic_fmt::hfdeb0fcb6ce506f4
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/core/src/panicking.rs:143:14
  16:     0x7fa59312d60c - core[efe43fe86f1c620a]::panicking::panic_display::<&str>
  17:     0x7fa5947a83dd - <rustc_errors[6e799cab4439a167]::HandlerInner>::flush_delayed
  18:     0x7fa5947a689d - <rustc_errors[6e799cab4439a167]::HandlerInner as core[efe43fe86f1c620a]::ops::drop::Drop>::drop
  19:     0x7fa593ece5e6 - core[efe43fe86f1c620a]::ptr::drop_in_place::<rustc_session[3b88a4bcbf196e76]::parse::ParseSess>
  20:     0x7fa593ed0fda - <alloc[61df3a55352cbfc0]::rc::Rc<rustc_session[3b88a4bcbf196e76]::session::Session> as core[efe43fe86f1c620a]::ops::drop::Drop>::drop
  21:     0x7fa593ec12ac - core[efe43fe86f1c620a]::ptr::drop_in_place::<rustc_interface[9582d0c3479cfa46]::interface::Compiler>
  22:     0x7fa593ec1ac1 - rustc_span[20d03c4744d90449]::with_source_map::<core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>, rustc_interface[9582d0c3479cfa46]::interface::create_compiler_and_run<core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>, rustc_driver[a83f25a8e01ca780]::run_compiler::{closure#1}>::{closure#1}>
  23:     0x7fa593ebe2d3 - rustc_interface[9582d0c3479cfa46]::interface::create_compiler_and_run::<core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>, rustc_driver[a83f25a8e01ca780]::run_compiler::{closure#1}>
  24:     0x7fa593ea44e2 - std[3d6e7d7423cf4afe]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[9582d0c3479cfa46]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[9582d0c3479cfa46]::interface::run_compiler<core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>, rustc_driver[a83f25a8e01ca780]::run_compiler::{closure#1}>::{closure#0}, core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>>::{closure#0}, core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>>
  25:     0x7fa593ea1c29 - <<std[3d6e7d7423cf4afe]::thread::Builder>::spawn_unchecked_<rustc_interface[9582d0c3479cfa46]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[9582d0c3479cfa46]::interface::run_compiler<core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>, rustc_driver[a83f25a8e01ca780]::run_compiler::{closure#1}>::{closure#0}, core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>>::{closure#0}, core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>>::{closure#1} as core[efe43fe86f1c620a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  26:     0x7fa591866ca3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf9ab37ec9b510857
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/alloc/src/boxed.rs:1854:9
  27:     0x7fa591866ca3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha1991051ebf83b9d
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/alloc/src/boxed.rs:1854:9
  28:     0x7fa591866ca3 - std::sys::unix::thread::Thread::new::thread_start::h5d1d180c2a38668b
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/sys/unix/thread.rs:108:17
  29:     0x7fa59176c259 - start_thread
  30:     0x7fa5916885e3 - __GI___clone
  31:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0-nightly (0c292c966 2022-02-08) running on x86_64-unknown-linux-gnu

query stack during panic:
end of query stack
```

</p>
</details>

### LINKED ISSUE #93821: #92007 appears to break inference for previously compiling code
PR #92007 e7cc3bddbe0d0e374d05e7003e662bba1742dbae appears to break type inference in code that compiled on previous nightlies. This was found via a build failure in `tracing`'s CI after updating to nightly-2022-02-08: https://github.com/tokio-rs/tracing/runs/5129006951?check_suite_focus=true#step:4:530

### Code

This test (https://github.com/tokio-rs/tracing/blob/0d4acb25b6162fc64c84dbaca9cac7145d394a2a/tracing-subscriber/tests/utils.rs#L6-L20), which builds a `tracing` subscriber and sets it as the default using an extension trait, now fails to compile:
```rust
#[test]
fn init_ext_works() {
    let (subscriber, finished) = collector::mock()
        .event(
            event::mock()
                .at_level(tracing::Level::INFO)
                .with_target("init_works"),
        )
        .done()
        .run_with_handle();

    let _guard = subscriber.set_default();
    tracing::info!(target: "init_works", "it worked!");
    finished.assert_finished();
}
```

The definition of the extension trait looks like this (comments and non-relevant code elided):
```rust
pub trait SubscriberInitExt
where
    Self: Into<Dispatch>,
{
    fn set_default(self) -> dispatch::DefaultGuard {
        dispatch::set_default(&self.into())
    }
}
```
The complete code can be found here: https://github.com/tokio-rs/tracing/blob/0d4acb25b6162fc64c84dbaca9cac7145d394a2a/tracing-subscriber/src/util.rs#L10-L93. But, I'm pretty sure that basically only the trait bounds are relevant.

I expected to see this happen: the code compiles.

Instead, this happened: compilation fails with this error
```
error[E0283]: type annotations needed
  --> tracing-subscriber/tests/utils.rs:17:29
   |
17 |     let _guard = subscriber.set_default();
   |                             ^^^^^^^^^^^ cannot infer type for struct `Dispatch`
   |
   = note: multiple `impl`s satisfying `Dispatch: ~const From<impl Collect>` found in the following crates: `core`, `tracing_core`:
           - impl<C> From<C> for Dispatch
             where C: 'static, C: Collect, C: Send, C: Sync;
           - impl<T> From<T> for T;
   = note: required because of the requirements on the impl of `Into<Dispatch>` for `impl Collect`
note: required by a bound in `tracing_subscriber::util::SubscriberInitExt::set_default`
  --> /home/runner/work/tracing/tracing/tracing-subscriber/src/util.rs:25:11
   |
25 |     Self: Into<Dispatch>,
   |           ^^^^^^^^^^^^^^ required by this bound in `tracing_subscriber::util::SubscriberInitExt::set_default`

For more information about this error, try `rustc --explain E0283`.
```

### Version it worked on

It most recently worked on: `nightly-2022-02-07` (734368a20)

### Version with regression

The regression was introduced in: `nightly-2022-02-07` (0c292c966)

I ran `cargo-bisect-rustc` with `cargo test --all` on a checkout of tokio-rs/tracing@0d4acb25b6162fc64c84dbaca9cac7145d394a2a. The regressed commit appears to be e7cc3bddbe0d0e374d05e7003e662bba1742dbae (PR #92007).

<details> 

<summary>Complete `cargo-bisect-rustc` output:</summary>

```
:; cargo bisect-rustc --start 734368a20 --end 0c292c966 -- test --all
bisecting ci builds
starting at 734368a20, ending at 0c292c966
opening existing repository at "rust.git"
refreshing repository
fetching (via local git) commits from 734368a20 to 0c292c9667f1b202a9150d58bdd2e89e3e803996
opening existing repository at "rust.git"
refreshing repository
looking up first commit
looking up second commit
checking that commits are by bors and thus have ci artifacts...
finding bors merge commits
found 6 bors merge commits in the specified range
  commit[0] 2022-02-07UTC: Auto merge of #87869 - thomcc:skinny-io-error, r=yaahc
  commit[1] 2022-02-07UTC: Auto merge of #92007 - oli-obk:lazy_tait2, r=nikomatsakis
  commit[2] 2022-02-08UTC: Auto merge of #93561 - Amanieu:more-unwind-abi, r=nagisa
  commit[3] 2022-02-08UTC: Auto merge of #93762 - matthiaskrgr:rollup-vdjpfmz, r=matthiaskrgr
  commit[4] 2022-02-08UTC: Auto merge of #93626 - wesleywiser:fix_hashmap_natvis, r=michaelwoerister
  commit[5] 2022-02-08UTC: Auto merge of #93572 - scottmcm:generic-iter-process, r=yaahc
validated commits found, specifying toolchains

installing 734368a200904ef9c21db86c595dc04263c87be0
cargo for x86_64-unknown-linux-gnu: 6.31 MB / 6.31 MB [============================================================================================================] 100.00 % 11.54 MB/s testing...
RESULT: 734368a200904ef9c21db86c595dc04263c87be0, ===> No
uninstalling 734368a200904ef9c21db86c595dc04263c87be0

installing 0c292c9667f1b202a9150d58bdd2e89e3e803996
cargo for x86_64-unknown-linux-gnu: 6.32 MB / 6.32 MB [============================================================================================================] 100.00 % 10.41 MB/s testing...
RESULT: 0c292c9667f1b202a9150d58bdd2e89e3e803996, ===> Yes
uninstalling 0c292c9667f1b202a9150d58bdd2e89e3e803996

installing 2a8dbdb1e2d9f44e7971d9a70b41d4d86db0112f
cargo for x86_64-unknown-linux-gnu: 6.30 MB / 6.30 MB [=============================================================================================================] 100.00 % 8.64 MB/s testing...
RESULT: 2a8dbdb1e2d9f44e7971d9a70b41d4d86db0112f, ===> Yes
uninstalling 2a8dbdb1e2d9f44e7971d9a70b41d4d86db0112f

installing e7cc3bddbe0d0e374d05e7003e662bba1742dbae
cargo for x86_64-unknown-linux-gnu: 6.31 MB / 6.31 MB [============================================================================================================] 100.00 % 10.84 MB/s testing...
RESULT: e7cc3bddbe0d0e374d05e7003e662bba1742dbae, ===> Yes
uninstalling e7cc3bddbe0d0e374d05e7003e662bba1742dbae

searched toolchains 734368a200904ef9c21db86c595dc04263c87be0 through 0c292c9667f1b202a9150d58bdd2e89e3e803996


********************************************************************************
Regression in e7cc3bddbe0d0e374d05e7003e662bba1742dbae
********************************************************************************
```

</details>

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### LINKED ISSUE #93831: Internal Compiler Error when compiling rocket = "0.5.0-rc.1"
### Problem

When trying to build a project containing the rocket web framework, cargo fails with an internal compiler error. Below is the full error written to the console.

```
error: internal compiler error: encountered ambiguity selecting `Binder(<response::stream::reader::ReaderStream<impl futures::Stream<Item = response::stream::raw_sse::RawLinedEvent>> as std::convert::From<impl futures::Stream<Item = response::stream::raw_sse::RawLinedEvent>>>, [])` during codegen, presuming due to overflow or prior type error
  |
  = note: delayed at compiler/rustc_trait_selection/src/traits/codegen.rs:54:32

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1176:13
stack backtrace:
   0:     0x7f63127a59fc - std::backtrace_rs::backtrace::libunwind::trace::hef696c91488c46df
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f63127a59fc - std::backtrace_rs::backtrace::trace_unsynchronized::h76c93ef0698d26b2
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f63127a59fc - std::sys_common::backtrace::_print_fmt::h93575aa503bf6e1b
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x7f63127a59fc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h40967adecfbc037b
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x7f63128070dc - core::fmt::write::h03044e853df7d223
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/core/src/fmt/mod.rs:1190:17
   5:     0x7f6312795d28 - std::io::Write::write_fmt::h86bffabfad56f13c
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/io/mod.rs:1657:15
   6:     0x7f63127a9977 - std::sys_common::backtrace::_print::hd28d8aed16472cc0
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x7f63127a9977 - std::sys_common::backtrace::print::h8f98cdd641cb45a3
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x7f63127a9977 - std::panicking::default_hook::{{closure}}::h729dcf0a13bd0685
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/panicking.rs:295:22
   9:     0x7f63127a963f - std::panicking::default_hook::h5f6c637024d9ad69
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/panicking.rs:314:9
  10:     0x7f6312f8b681 - rustc_driver[a83f25a8e01ca780]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7f62fd852f63 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h15874327c724c4f1
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/alloc/src/boxed.rs:1868:9
  12:     0x7f62fd93048c - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::hf4f8cfaa5a8904e5
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/proc_macro/src/bridge/client.rs:319:21
  13:     0x7f62fd85b740 - std::panicking::update_hook::{{closure}}::hb7d2a3b785fe4df6
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/panicking.rs:258:41
  14:     0x7f63127aa255 - std::panicking::rust_panic_with_hook::h46cff6766bf99e7c
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/panicking.rs:702:17
  15:     0x7f63127a9f07 - std::panicking::begin_panic_handler::{{closure}}::h0e775b2aa2b67693
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/panicking.rs:588:13
  16:     0x7f63127a5ea4 - std::sys_common::backtrace::__rust_end_short_backtrace::h1863dd104b065b9d
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/sys_common/backtrace.rs:138:18
  17:     0x7f63127a9c09 - rust_begin_unwind
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/panicking.rs:584:5
  18:     0x7f6312771b93 - core::panicking::panic_fmt::hfdeb0fcb6ce506f4
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/core/src/panicking.rs:143:14
  19:     0x7f631407c60c - core[efe43fe86f1c620a]::panicking::panic_display::<&str>
  20:     0x7f63156f73dd - <rustc_errors[6e799cab4439a167]::HandlerInner>::flush_delayed
  21:     0x7f63156f589d - <rustc_errors[6e799cab4439a167]::HandlerInner as core[efe43fe86f1c620a]::ops::drop::Drop>::drop
  22:     0x7f6314e1d5e6 - core[efe43fe86f1c620a]::ptr::drop_in_place::<rustc_session[3b88a4bcbf196e76]::parse::ParseSess>
  23:     0x7f6314e1ffda - <alloc[61df3a55352cbfc0]::rc::Rc<rustc_session[3b88a4bcbf196e76]::session::Session> as core[efe43fe86f1c620a]::ops::drop::Drop>::drop
  24:     0x7f6314e102ac - core[efe43fe86f1c620a]::ptr::drop_in_place::<rustc_interface[9582d0c3479cfa46]::interface::Compiler>
  25:     0x7f6314e10ac1 - rustc_span[20d03c4744d90449]::with_source_map::<core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>, rustc_interface[9582d0c3479cfa46]::interface::create_compiler_and_run<core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>, rustc_driver[a83f25a8e01ca780]::run_compiler::{closure#1}>::{closure#1}>
  26:     0x7f6314e0d2d3 - rustc_interface[9582d0c3479cfa46]::interface::create_compiler_and_run::<core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>, rustc_driver[a83f25a8e01ca780]::run_compiler::{closure#1}>
  27:     0x7f6314df34e2 - std[3d6e7d7423cf4afe]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[9582d0c3479cfa46]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[9582d0c3479cfa46]::interface::run_compiler<core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>, rustc_driver[a83f25a8e01ca780]::run_compiler::{closure#1}>::{closure#0}, core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>>::{closure#0}, core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>>
  28:     0x7f6314df0c29 - <<std[3d6e7d7423cf4afe]::thread::Builder>::spawn_unchecked_<rustc_interface[9582d0c3479cfa46]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[9582d0c3479cfa46]::interface::run_compiler<core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>, rustc_driver[a83f25a8e01ca780]::run_compiler::{closure#1}>::{closure#0}, core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>>::{closure#0}, core[efe43fe86f1c620a]::result::Result<(), rustc_errors[6e799cab4439a167]::ErrorReported>>::{closure#1} as core[efe43fe86f1c620a]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  29:     0x7f63127b5ca3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hf9ab37ec9b510857
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/alloc/src/boxed.rs:1854:9
  30:     0x7f63127b5ca3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::ha1991051ebf83b9d
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/alloc/src/boxed.rs:1854:9
  31:     0x7f63127b5ca3 - std::sys::unix::thread::Thread::new::thread_start::h5d1d180c2a38668b
                               at /rustc/0c292c9667f1b202a9150d58bdd2e89e3e803996/library/std/src/sys/unix/thread.rs:108:17
  32:     0x7f6312554927 - start_thread
                               at ./nptl/./nptl/pthread_create.c:435:8
  33:     0x7f63125e49e4 - __clone
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:100
  34:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0-nightly (0c292c966 2022-02-08) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib -C embed-bitcode=no -C debuginfo=2

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `rocket`
```

### Steps

1. Create new cargo project `cargo new random`
2. Add rocket to the dependencies `rocket = "0.5.0-rc.1"`
3. Build the project `cargo build`

### Possible Solution(s)

So far, the only solution I've found is to downgrade my version of nightly rust which'll compile the project just fine

### Notes

_No response_

### Version

```text
cargo 1.60.0-nightly (25fcb13 2022-02-01)
release: 1.60.0-nightly
commit-hash: 25fcb135d02ea897ce894b67ae021f48107d522b
commit-date: 2022-02-01
host: x86_64-unknown-linux-gnu
libgit2: 1.3.0 (sys:0.13.23 vendored)
libcurl: 7.80.0-DEV (sys:0.4.51+curl-7.80.0 vendored ssl:OpenSSL/1.1.1l)
os: Pop!_OS 21.10 (impish) [64-bit]
```

### PR DESCRIPTION
**Pull request by oli-obk**
fixes #93831
fixes #93821
fixes #93788

### CODE REVIEW

**Comment by oli-obk** [comment]
The main lazy TAIT PR has been reverted and these commits will be part of the next attempt
