### PR TITLE
Use proper HirId for async track_caller attribute check

### LINKED ISSUE #105134: `async{}` blocks can no longer be used in functions marked as `#[track_caller]`
### Code

The following code compiles and works as expected on `nightly-2022-11-17` and fails on `nightly-2022-11-18`:

```rust
#[track_caller]
pub fn f() {
    _ = async {};
}
```
```text
error[E0658]: `#[track_caller]` on closures is currently unstable
 --> src/lib.rs:3:9
  |
3 |     _ = async {};
  |         ^^^^^^^^
  |
  = note: see issue #87417 <https://github.com/rust-lang/rust/issues/87417> for more information
  = help: add `#![feature(closure_track_caller)]` to the crate attributes to enable
```
[(play)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5c12d6d61a5a15bd4ce3661b81768b61)

### Version it worked on

It most recently worked on: `nightly-2022-11-17`

### Version with regression

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (c97b539e4 2022-11-30)
binary: rustc
commit-hash: c97b539e408ea353f4fde2f9251d598291fec421
commit-date: 2022-11-30
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

Similarly to https://github.com/rust-lang/rust/issues/104588, this is caused by https://github.com/rust-lang/rust/pull/104219, but this reproduction doesn't even use `#[track_caller]` on `async fn`!
<sub>btw I've found this b/c users of my crate reported that it doesn't compile anymore, good stuff</sub>

----

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged
cc @bryangarza

### PR DESCRIPTION
**Pull request by nbdd0121**
Fix #105134

### CODE REVIEW

File: compiler/rustc_ast_lowering/src/expr.rs [hunk 1]
```diff
@@ -1012,6 +1013,7 @@ impl<'hir> LoweringContext<'_, 'hir> {
 
                 let async_body = this.make_async_expr(
```
Comment (compiler-errors) [inline compiler/rustc_ast_lowering/src/expr.rs:1014]: Async closures should probably also support `#[track_caller]`

**Comment by compiler-errors** [comment]
r? @compiler-errors @bors delegate+

Thanks, r=me with or without my comment.

cc @bryangarza, you will need to rebase your PR.

File: compiler/rustc_ast_lowering/src/expr.rs (hunk 1 above)
Comment (nbdd0121) [reply compiler/rustc_ast_lowering/src/expr.rs:1014]: It currently doesn't, so that's why I haven't changed it in this PR.

It isn't difficult change to make, but it does require lifting the attribute lower up from after `ExprKind` lowering to before it. Do you happen to know why we currently lower ID and attributes after `ExprKind`?

Comment (nbdd0121) [reply compiler/rustc_ast_lowering/src/expr.rs:1018]: Added. I then changed `Option<HirId>` to `HirId` to simplify code. We don't need to special case async blocks as `#[track_caller]` is not legal on async block. But I added a test anyway to avoid accidentally allow this on normal async block.

**Comment by compiler-errors** [comment]
I'll review the changes in a bit

**Comment by nbdd0121** [comment]
Not sure why making this change cause incr-comp test to fail. Maybe different HirId ordering causes the typeck result happens to match? Might need some incr-comp expert to take a look @rust-lang/wg-incr-comp

File: compiler/rustc_ast_lowering/src/expr.rs (hunk 1 above)
Comment (compiler-errors) [reply compiler/rustc_ast_lowering/src/expr.rs:1023]: Given the incremental issues, maybe we can revert the last change and go with `Option<HirId>`? Or are those test failures unrelated to the last change?

**Comment by cjgillot** [comment]
You can just bless the incremental tests. The change is in the right direction: stuff that were dirty are now clean.
In the places there is a reported error, remove the reported query from the `rustc_clean` attribute's `except` list.

**Comment by nbdd0121** [comment]
Thanks, @cjgillot! I thought that they were there to ensure that the results are dirty. So these are more like status-quo checks instead to catch accidental changes?

**Comment by cjgillot** [comment]
Pretty much, yes.

**Comment by compiler-errors** [comment]
Given @cjgillot's comment and the blessed tests, this seems good to go now. Thanks for fixing this @nbdd0121.

@bors r+

**Comment by nbdd0121** [comment]
Given that #105134 is a critical regression and thus we want it to be fixed soon, I think it's best to split the async closure support (with HIR attribute lowering changes) into a separate PR. I have added a FIXME note and reverted the PR to the pre `Option<HirId>` -> `HirId` change state.

@bors r=compiler-errors
