### ISSUE TITLE
NLL: need to decide semantics of move guards

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#47295]
Here is a test that [already exists](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/move-guard-const.rs) in the `run-pass` suite:

```rust

fn main() {
    let x: Box<_> = box 1;

    let v = (1, 2);

    match v {
        (2, 1) if take(x) => (),
        (1, 2) if take(x) => (),
        _ => (),
    }
}

fn take<T>(_: T) -> bool { false }
```

The above is accepted under AST-borrowck. Unfortunately, it is rejected by MIR-borrowck:

```
% ./build/x86_64-unknown-linux-gnu/stage1/bin/rustc -Z borrowck=compare ../src/test/run-pass/move-guard-const.rs
error[E0382]: use of moved value: `x` (Mir)
  --> /home/pnkfelix/Dev/Mozilla/rust.git/src/test/run-pass/move-guard-const.rs:22:24
   |
21 |         (2, 1) if take(x) => (),
   |                        - value moved here
22 |         (1, 2) if take(x) => (),
   |                        ^ value used here after move
   |
   = note: move occurs because `x` has type `std::boxed::Box<i32>`, which does not implement the `Copy` trait

error: aborting due to previous error
```

So here's the issue: We were hoping, in MIR-borrowck, to apply a pretty conservative semantics to model the control-flow of match arms, to maximize freedom in choosing future `match`-desugaring strategies.

But clearly we already allow moves in `match` guards in a way that we cannot just use the current naive "every guard might be executed regardless of its associated pattern"  ... at least, not without marking it as a breaking-change to the language.

It might not be *that* hard to encode some amount of intelligence into the control-flow, in terms of modelling pattern disjointness in the arms. But its not what we're currently doing, so we need to figure out if doing that is a blocker for deploying MIR-borrowck (and thus NLL).

**Comment by nikomatsakis** [comment]
It seems that the reason we accept this program is because of a very narrow exception in the CFG generation that specifically targets "all constant" arms:

https://github.com/rust-lang/rust/blob/619ced057842a25f8700237a9c22a6f5c318a954/src/librustc/cfg/construct.rs#L498-L526

**Comment by petrochenkov** [comment]
The "all constant" rule seems very wrong.

First, the "all the constants are the same" condition is no longer "rejected by `check_match`".
```rust
    match v {
        (1, 2) => (),
        (1, 2) => (), // OK, only a warning
        _ => (),
    }
```

Second, it was *never* (since 1.0) rejected in presence of `if` guards, e.g. this compiles on Rust 1.0
```rust
fn main() {
    let x = Box::new(1);

    let v = (1, 2);

    match v {
        (1, 2) if rand(x) => (),
        (1, 2) if rand(x) => (), // May consume `x` twice
        _ => (),
    }
}

fn rand<T>(_: T) -> bool { false /* or true */}
```
https://godbolt.org/g/5tdLJk

**Comment by nikomatsakis** [comment]
@petrochenkov I'm not a big fan of the rule, but then it may be we need to keep some variant of it for backwards compatibility. Still, that's a pretty interesting example -- is there a bug filed for that? Maybe we can use it as justification to simplify the code and remove this silly rule. It looks to have been put in place just to satisfy a particular run-pass test, and hopefully isn't relied upon much in crater (have to test).

**Comment by nikomatsakis** [comment]
Maybe we should whip up a branch just for cratering purposes that removes that relevant code from the CFG.

**Comment by pnkfelix** [comment]
@nikomatsakis Nice! I say that @petrochenkov 's example lets us file this under "we can issue breaking changes to fix soundness holes", because that certainly is a soundness hole, right?

**Comment by nikomatsakis** [comment]
The main question is how much real-world code relies on this. It's hard to imagine there being much.

**Comment by pnkfelix** [comment]
#49447 got merged, so its possible we may be able to close this once we've confirmed that no one complains about the effect of #49447

**Comment by xfix** [comment]
This issue seems to be solved?
