### PR TITLE
Enable NLL migrate mode on the 2015 edition

### LINKED ISSUE #18330: Slightly incorrect error on mutable borrow of immutable captured variable
Code:

``` rust
fn set(x: &mut usize) { *x = 1; }

fn main() {
    let x = 0;
    || set(&mut x);
}
```

Output:

```
<anon>:7:5: 7:19 error: closure cannot assign to immutable local variable `x`
<anon>:7     || set(&mut x);
             ^~~~~~~~~~~~~~
```

This should actually state that it cannot borrow (rather than assign) the variable.  This has been around since 0.10 at least.

### LINKED ISSUE #22323: dropck: track order of destruction for r-value temporaries
Spawned off of  #21022, #21972; see also #21657.

Tracking order of destruction for r-value temporaries would (probably) allow us to resume writing code like this from [RFC 769](https://github.com/rust-lang/rfcs/blob/master/text/0769-sound-generic-drop.md#some-temporaries-need-to-be-given-names):

``` rust
for line in old_io::stdin().lock().lines() {
    ...
}
```

which is currently disallowed because the region inference system does not know that the temporary yielded by `stdin()` will outlive the temporary from `stdin().lock()`.

(But note that it might also have fallout, potentially worse than that of #21657)

### LINKED ISSUE #23591: Closures cause unnecessary borrows
Simple example:

```
use std::cmp::Ordering;

fn something<T,F>(slice: &mut [T], mut compare: F) where
    F: FnMut(&T,&T) -> Ordering
{
    // This compiles fine:
    if compare(&slice[0], &slice[1]) == Ordering::Less {
        slice.swap(0, 1);
    }

    // But this does not:
    let mut cmp = |a,b| compare(a,b) == Ordering::Less;

    if cmp(&slice[0], &slice[1]) {
        slice.swap(0, 1);
    }
}
```

Playpen: http://is.gd/niaLAa

It seems like it marks the closure return value as a borrowed value from `slice`, even though it is just a bool.

### LINKED ISSUE #26736: cannot move into irrefutable slice patterns with multiple elements
``` rust
let arr = [Box::new(1), Box::new(2), Box::new(3)];
let [a, b, c] = arr;
```

fails with

```
<anon>:5:13: 5:14 error: use of moved value: `arr[..]` [E0382]
<anon>:5     let [a, b, c] = arr;
                     ^
<anon>:5:10: 5:11 note: `arr[..]` moved here because it has type `Box<i32>`, which is moved by default
<anon>:5     let [a, b, c] = arr;
                  ^
<anon>:5:10: 5:11 help: use `ref` to override
```

while the following work fine:

``` rust
let arr = [Box::new(1)];
let [a] = arr;
```

``` rust

enum Dummy<T> {
    Val([T; 2]),
}
let arr = [Box::new(1), Box::new(2)];
let Dummy::Val([a, b]) = Dummy::Val(arr);
```

### LINKED ISSUE #27487: Borrow checker gets confused with a mutable pointer which should be moved
``` rust
pub struct FragmentRepr(Vec<FragmentRepr>);
pub fn accepted(mut entry: &mut FragmentRepr) {
    loop {
        let FragmentRepr(ref mut discrs) = *{entry};
        entry = &mut discrs[0];
    }
}
pub fn rejected(mut entry: &mut FragmentRepr) {
    loop {
        let FragmentRepr(ref mut discrs) = *entry;
        entry = &mut discrs[0];
    }
}
fn main() {}
```

Rust accepts the first function, but rejects the second with "error: cannot borrow `entry.0` as mutable more than once at a time".  It would be nice not to be forced to insert random curly braces to convince the borrow checker that my code is correct.

### LINKED ISSUE #28092: Weird lifetime error with closure and early-bound lifetime
``` rust
struct S;
impl S {
    fn f<'a:'a>(_x:&'a i32) {}
}
fn main() {
    let g1: &Fn(&i32) = &|x| S::f(x);
    g1(&1);
    let g2 = &|x| S::f(x);
    g2(&1);
}
```

```
<anon>:9:9: 9:10 error: borrowed value does not live long enough
<anon>:9     g2(&1);
                 ^
<anon>:8:27: 10:2 note: reference must be valid for the block suffix following statement 2 at 8:26...
<anon>: 8     let g2 = &|x| S::f(x);
<anon>: 9     g2(&1);
<anon>:10 }
<anon>:9:5: 9:12 note: ...but borrowed value is only valid for the statement at 9:4
<anon>:9     g2(&1);
             ^~~~~~~
<anon>:9:5: 9:12 help: consider using a `let` binding to increase its lifetime
<anon>:9     g2(&1);
             ^~~~~~~
error: aborting due to previous error
```

Lifetime inference is doing something weird with the second closure.

### LINKED ISSUE #28970: Compiler gets lifetime scope wrong
Please check the code bellow

https://play.rust-lang.org/?gist=c0dd3d93bde346c4bd4d&version=nightly

```
#![feature(drain)]

use std::sync::{Arc, RwLock};

fn main() {
    let files = RwLock::new(vec![Arc::new(1u32)]);

    // WONT compile
    let a: Vec<_> = files.write().unwrap().drain(..1).collect();

    // WONT compile
    let a: Vec<_> = {
        let mut temp = files.write().unwrap();
        temp.drain(..1).collect()
    };

    // compiles
    let a: Vec<_> = {
        let mut temp = files.write().unwrap();
        let res = temp.drain(..1).collect();
        res
    };

    println!("{:?}", a);
}
```

I suppose all of them should compile as they do the same thing, but only the last one does.

### LINKED ISSUE #29733: Improve "previous borrow" location in borrow error message
Given the following code:

``` rust
use std::collections::HashMap;

fn main() {
    let mut vec = vec![0, 1, 2, 3, 4];
    let mut map = HashMap::<&i32, &str>::new();

    for key in &vec {
        map.insert(key, "value");
    }

    vec.push(5);
}
```

The compiler will complain with the following error message:

```
error[E0502]: cannot borrow `vec` as mutable because it is also borrowed as immutable
  --> /tmp/test_borrow_message.rs:11:5
   |
7  |     for key in &vec {
   |                 --- immutable borrow occurs here
...
11 |     vec.push(5);
   |     ^^^ mutable borrow occurs here
12 | }
   | - immutable borrow ends here

error: aborting due to previous error
```

While the borrow error is expected, the message seems pretty unclear to me. 

Removing/commenting the `map.insert(key, "value");` line will allow rustc to compile the file, which shows the problem isn't really exactly with the borrow happening at line 7 (for loop), but with the fact that the borrow is then extended to the lifetime of the `map` variable.
This can be verified with the following code which works because the `map` variable is gone by the time we need to mutable borrow again:

``` rust
use std::collections::HashMap;

fn main() {
    let mut vec = vec![0, 1, 2, 3, 4];
    {
        let mut map = HashMap::<&i32, &str>::new();
        for key in &vec {
            map.insert(key, "value");
        }
    }
    vec.push(5);
}
```

It feels like the compiler should be clearer as to where the borrow is actually "stored". It's able to show that the borrow ends when `map` goes away, so I feel it should be clearer that the borrow issue stems from the `map.insert(key, "value");` line, which extends the borrow's "lifetime" to the lifetime of `map`

(this error is output by rust 1.4.0)

### LINKED ISSUE #30104: Destructuring boxes into multiple mutable references seems broken
This fails with "cannot mutably borrow more than once" errors

``` rust
fn push(mut node: Box<(i32, i32)>) {
    let (ref mut left, ref mut right) = *node;
}
```

Same here:

``` rust
fn push(mut node: Box<(i32, i32)>) {
    let box (ref mut left, ref mut right) = node;
}
```

This works:

``` rust
fn push(mut node: Box<(i32, i32)>) {
    let (ref mut left, ref mut right) = *&mut *node;
}
```

This also works:

``` rust
fn push(node: &mut (i32, i32)) {
    let (ref mut left, ref mut right) = *node;
}
```

Same behavior with structs instead of tuples. Boxes are weird, destructuring into mutable borrows is weird, so I have no idea what is going on there.

### LINKED ISSUE #38915: Borrow checker false dropped while still borrowed
The following does not compile:
``` rust
use std::ffi::OsString;
use std::io::{Result as IoResult};
use std::path::Path;

fn main() {
    let paths: Vec<OsString> = vec!["filename".into()];
// Switching these two lines appeases our lord and savior the borrow checker
    let f = std::fs::rename;
    let dests = paths.clone();
// ---------------------------
    let pairs = paths.iter().zip(dests.iter());
//                               ----- borrow occurs here
    foo(f, pairs);
}
// `dests` does not live long enough.
// ^ `dests` dropped here while still borrowed

fn foo<P, I>(f: fn(P, P) -> IoResult<()>, pairs: I)
    where P: AsRef<Path>,
          I: Iterator<Item=(P, P)>,
{
    for (src, dest) in pairs {
        let _ = f(src, dest);
    }
}
```

EDIT: simplified code.

### LINKED ISSUE #39908: Extra borrowing?
So for the following code:

```rust
let tmp = if let (Ok(_src_path), Ok(_dest_path)) =
    (Path::new(&src_path).strip_prefix(&cur_dir),
     Path::new(&dest_path).strip_prefix(&cur_dir)) {
    (_src_path.to_path_buf(), _dest_path.to_path_buf())
} else {
    (src_path, dest_path)
};
```

I get the following error:

```
error[E0505]: cannot move out of `src_path` because it is borrowed
    --> src/libsyntax/parse/parser.rs:5249:30
     |
5245 |                             (Path::new(&src_path).strip_prefix(&cur_dir),
     |                                         -------- borrow of `src_path` occurs here
...
5249 |                             (src_path, dest_path)
     |                              ^^^^^^^^ move out of `src_path` occurs here

error[E0505]: cannot move out of `dest_path` because it is borrowed
    --> src/libsyntax/parse/parser.rs:5249:40
     |
5246 |                              Path::new(&dest_path).strip_prefix(&cur_dir)) {
     |                                         --------- borrow of `dest_path` occurs here
...
5249 |                             (src_path, dest_path)
     |                                        ^^^^^^^^^ move out of `dest_path` occurs here

error: aborting due to 2 previous errors
```

However, since we're out of the `if` scope, shouldn't I be able to use `src_path` and `dest_path` again?

### LINKED ISSUE #43407: `if let` keeps borrows too long
Borrows in patterns are kept during the whole `if let` expression, including the `else` branch, which is counterintuitive and annoying.
For example, this doesn't compile.
```rust
let mut x = Some(1);
if let Some(&ref p) = x.as_ref() {
    // do something with p
} else {
    x = Some(2); // error: x is still borrowed
}
```
To pass the borrow check, you have to write ugly code like this.
```rust
let mut x = Some(1);
let mut flag = false;
if let Some(&ref p) = x.as_ref() {
    // do something with p
} else {
    flag = true;
}
if flag {
    x = Some(2);
}
```

### LINKED ISSUE #47524: lifetime inference regression in closure
The owning_ref crate has a couple test failures starting with Rust 1.23, which worked fine on 1.22.  It is fixed by Kimundi/owning-ref-rs#43, but I wanted to see if this is a deliberate compiler change.  The only compatibility note for 1.23 that sounds like it _might_ be related is regarding #45852, but I'm not sure.

Reduced example, [playground](https://play.rust-lang.org/?gist=1a74d20992f1a741beaea8ef971caaff&version=stable):

```rust
fn map<F, T, U>(x: &T, f: F) -> &U
where
    F: FnOnce(&T) -> &U,
{
    f(x)
}

fn borrow<'a>(a: &'a &[i32; 2]) -> &'a i32 {
    &a[0]
}

fn main() {
    let foo = [413, 612];
    let bar = &foo;

    map(&bar, borrow); // OK

    map(&bar, |a: &&[i32; 2]| &a[0]); // does not live long enough
}
```

This example works on 1.22, but fails on 1.23 through nightly:

```
error[E0597]: `a[..]` does not live long enough
  --> src/main.rs:18:32
   |
18 |     map(&bar, |a: &&[i32; 2]| &a[0]); // does not live long enough
   |                                ^^^^- borrowed value only lives until here
   |                                |
   |                                does not live long enough
   |
note: borrowed value must be valid for the anonymous lifetime #2 defined on the body at 18:15...
  --> src/main.rs:18:15
   |
18 |     map(&bar, |a: &&[i32; 2]| &a[0]); // does not live long enough
   |               ^^^^^^^^^^^^^^^^^^^^^
```

xref: https://bugzilla.redhat.com/show_bug.cgi?id=1535396

### LINKED ISSUE #48540: Spurious "does not live long enough" for closure coerced to fn pointer in static item (AST borrowck only)
The test case below is reduced from a [phf map](https://github.com/sfackler/rust-phf). 

rustc 1.26.0-nightly (28a1e4ffe 2018-02-24) with `-Z borrowck=mir`: OK

Without any `-Z` flag: error below, even though I believe the program to be valid. But maybe it’s not worth fixing if MIR-based borrow-checking will become the default soon? CC @nikomatsakis 

A work-around is to have the closure in an intermediate `const` item.

```rust
fn main() {}

struct Static<T: 'static>(&'static [T]);

static FOO: Static<fn(&u32) -> &u32> = Static(&[|x| x]);
```
```rust
error[E0597]: borrowed value does not live long enough
 --> a.rs:5:52
  |
5 | pub static FOO: Static<fn(&u32) -> &u32> = Static(&[|x| x]);
  |                                                    ^^^^^^^- temporary value only lives until here
  |                                                    |
  |                                                    temporary value does not live long enough
  |
  = note: borrowed value must be valid for the static lifetime...

error: aborting due to previous error
```
```rust
fn main() {}

struct Static<T: 'static>(&'static [T]);

static FOO: Static<fn(&u32) -> &u32> = Static(&[
    {
        const F: fn(&u32) -> &u32 = |x| x;  // work around
        F
    },
]);
```

### LINKED ISSUE #49073: Spurious "borrowed value does not live long enough" when calling a function through a function pointer
The following code (edited to an even smaller version provided by occultus):
```rust
use std::string::ToString;

fn main() {
    let to_string = ToString::to_string;
    let i = 1;
    let b = &i;
    assert_eq!("", to_string(&b));
}
```

yields the following compiler output:
```
error[E0597]: `i` does not live long enough
 --> src/main.rs:6:14
  |
6 |     let b = &i;
  |              ^ borrowed value does not live long enough
7 |     assert_eq!("", to_string(&b));
8 | }
  | - `i` dropped here while still borrowed
  |
  = note: values in a scope are dropped in the opposite order they are created
```

Moving `let to_string` down one line "fixes" it. So does `#![feature(nll)]`.

In case you wonder how one ends up with code like this, it's because this is test code, and `to_string` is actually `<Trait as ToString>::to_string`, which is a lot of boilerplate.

### LINKED ISSUE #52614: Warning that variable does not need to be mutable, while in fact, it does
I tried this code:

```rust
struct S<'a> { x: &'a mut u8 }

impl<'a> S<'a> {
	fn f(&self, y: &'a mut u8) -> &'a mut u8 { y }
}

fn main() {
	let mut b = 5;
	let c;
	{
		let mut a = 4;
		let s = S{x: &mut a};
		c = s.f(&mut b);
	}
}
```

The compiler warns that the variable `a` does not need to be mutable:
```
warning: variable does not need to be mutable
  --> test.rs:11:7
   |
11 |         let mut a = 4;
   |             ----^
   |             |
   |             help: remove this `mut`
   |
   = note: #[warn(unused_mut)] on by default

```
I did not expect this warning because a reference as mutable to `a` is taken later on.
(The other errors and warnings are expected.)

## Meta

`rustc --version --verbose`:

```
rustc 1.29.0-nightly (12ed235ad 2018-07-18)
binary: rustc
commit-hash: 12ed235adc62e63b16bb4f715b143c37a5efa00d
commit-date: 2018-07-18
host: x86_64-unknown-linux-gnu
release: 1.29.0-nightly
LLVM version: 7.0
```

### LINKED ISSUE #55085: Two cases of confusing borrow over-extension
Using rustc nightly 2018-10-13 4699283c5b549d1559c1 (from playpen).

I found two cases where lifetimes appear to be extended where they shouldn't:

```rust
use std::cell::RefCell;
use std::collections::binary_heap::PeekMut;
use std::collections::BinaryHeap;

fn main() {
    let heap: RefCell<BinaryHeap<u32>> = RefCell::new(BinaryHeap::new());

    let mut heap_ref = heap.borrow_mut();
    let entry = if let Some(entry) = heap_ref.peek_mut() {
        entry
    } else {
        panic!();
    };
    let task = PeekMut::pop(entry);

    //drop(entry);

    drop(heap_ref);
    println!("We made it {:?}, {:?}", heap.borrow_mut(), task);
}
```
[Playpen link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=3c877efdbff5cb6e4fdcb9ed6bae6c80)

Which gives this error:

```
error[E0505]: cannot move out of `heap_ref` because it is borrowed
  --> src/main.rs:18:10
   |
9  |     let entry = if let Some(entry) = heap_ref.peek_mut() {
   |                                      -------- borrow of `heap_ref` occurs here
...
18 |     drop(heap_ref);
   |          ^^^^^^^^ move out of `heap_ref` occurs here
```

Even though the only thing that could be borrowing `heap_ref` is `entry`, which has already been moved into the `pop()` call.

---

```rust
use std::cell::RefCell;
use std::collections::binary_heap::PeekMut;
use std::collections::BinaryHeap;

fn main() {
    let heap: RefCell<BinaryHeap<u32>> = RefCell::new(BinaryHeap::new());

    let task = {
        let mut heap_ref = heap.borrow_mut();
        if let Some(entry) = heap_ref.peek_mut() {
            PeekMut::pop(entry)
        } else {
            panic!();
        }
    };

    println!("We made it {:?}, {:?}", heap.borrow_mut(), task);
}
```
[Playpen link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=203a340e5b9f9a137b1cef1920efb78f)

Which gives this error:

```
error[E0597]: `heap_ref` does not live long enough
  --> src/main.rs:10:30
   |
10 |         if let Some(entry) = heap_ref.peek_mut() {
   |                              ^^^^^^^^ borrowed value does not live long enough
...
15 |     };
   |     -- borrowed value needs to live until here
   |     |
   |     `heap_ref` dropped here while still borrowed
```

Where it's complaining that a borrow needs to live until the same point where it's dropped.

### LINKED ISSUE #56093: Compiler does not suggest `move` when it would be appropriate
This snippet does not compile with the following error:

```
pub fn main() {
    |i: u32| { || i };
}

error[E0597]: `i` does not live long enough
 --> src/main.rs:2:19
  |
2 |     |i: u32| { || i };
  |                -- ^ - borrowed value dropped before borrower
  |                |  |
  |                |  borrowed value does not live long enough
  |                capture occurs here
  |
  = note: values in a scope are dropped in the opposite order they are created
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=2aa8b97e68b9eba4c1b7c0d3f627c386

But adding a `move` fixes it:

```
pub fn main() {
    |i: u32| { move || i };
}
```

I believe the compiler tries to suggest `move` where appropriate, and it seems that this case has been missed.

### LINKED ISSUE #56496: Misleading error message due to Box causing move of struct
This example causes a misleading error message:

```rust
struct FooInner {
    value1: Option<String>,
    value2: Option<String>,
}

struct Foo(Box<FooInner>);

fn main() {
    let foo = Foo(Box::new(FooInner {
        value1: Some("Hello World".to_string()),
        value2: Some("Hello World".to_string()),
    }));
    let inner = foo.0;
    // uncoment this line to fix the error
    //let inner = *inner;
    let x = inner.value1;
    let y = inner.value2;
    println!("{:?}", x);
    println!("{:?}", y);
}
```

Error message:

```
error[E0382]: use of moved value: `inner`
  --> src/main.rs:16:9
   |
15 |     let x = inner.value1;
   |         - value moved here
16 |     let y = inner.value2;
   |         ^ value used here after move
   |
   = note: move occurs because `inner.value1` has type `std::option::Option<std::string::String>`, which does not implement the `Copy` trait
```

I would have expected the compiler informing me that the entire struct was moved due to the box involved.

### LINKED ISSUE #57804: NLL: turn on borrowck=migrate by default on 2015 edition
As a sub-step towards having NLL produce hard errors (rather than downgrading its errors to warnings) and removing the AST-borrowck code, we want to turn on the NLL migration mode (introduced with the 2018 edition) so that it operates in all editions. Namely, we want to introduce the `-Z borrowck=migrate` (and associated `-Z two-phase-borrows`) on the 2015 edition.

This is a subtask of #43234 

----

On Zulip, @matthewjasper composed the following interesting table summarizing the open issues related to this, which I am transcribing here (with some light editing to replace pronouns with names).

all blocking issues are marked either P-High or NLL-Sound of those issues the current state is:

Issue number | Blocks migrate | Assigned To | Notes
----|----|----|----
~~#46702~~ | ~~Yes~~ | @matthewjasper / @nikomatsakis  | ~~Fixed by #57714~~
#56254 | Yes | @matthewjasper | #58739 
~~#57170~~ | ~~Yes~~ | @matthewjasper | ~~Fixed by #57202~~
~~#57731~~ | ~~Yes~~ | @matthewjasper | ~~Fixed by #57714~~
~~#58127~~ | ~~Yes~~ | @matthewjasper | ~~Fixed by #58347~~
#58178 | ~~Yes~~ No | @matthewjasper | Good enough after #58347
#54105 | No | @nikomatsakis | Needs to be fixed, but not clear what, if any, code this affects
#54940 | No | @nikomatsakis  | Obscure, no easy fix
#46901 | No | @pnkfelix  | need some idea what we're allowing for 2 phase borrows; (note #56254 above)
~~#54943~~ | ~~No~~ | @matthewjasper  | ~~Fixed as part of #57714~~
#56993 | No | @nikomatsakis  | Just a test issue now
#57374 | No | @lqd / @nikomatsakis  | Not an issue in migrate mode

### PR DESCRIPTION
**Pull request by matthewjasper**
## What is in this PR?

* Remove the `-Zborrowck=ast` flag option from rustc.
* The default in the 2015 edition is now `-Zborrowck=migrate`.
* The 2018 edition default is unchanged: it's still `-Zborrowck=migrate`.
* Enable two-phase borrows (currently toggled via the `-Ztwo-phase-borrows` flag) on all editions.
* Remove most dead code that handled these options.
* Update tests for the above changes.

## What is *not* in this PR?

These are left for future PRs

* Use `-Zborrowck=mir` in NLL compare mode tests (#56993)
* Remove the `-Zborrowck=compare` option (#59193)
* Remove the `-Ztwo-phase-borrows` flag. It's kept, as a flag that does nothing so that perf.rlo has time to stop using it (cc @Mark-Simulacrum)
* Remove MIR typeck as its own MIR pass - it's now run by NLL. 
* Enabling `-Zborrowck=mir` by default (#58781)
* Replace `allow_bind_by_move_patterns_with_guards` and `check_for_mutation_in_guard_via_ast_walk` with just using the feature gate. (#59192)

Soundness issues that are fixed by NLL will stay open until full NLL is emitting hard errors. However, these diagnostics and completeness issues can now be closed:

Closes #18330
Closes #22323
Closes #23591
Closes #26736
Closes #27487
Closes #28092
Closes #28970
Closes #29733
Closes #30104
Closes #38915
Closes #39908
Closes #43407
Closes #47524
Closes #48540
Closes #49073
Closes #52614
Closes #55085
Closes #56093
Closes #56496
Closes #57804

cc #43234

r? @pnkfelix 
cc @rust-lang/lang 
cc @rust-lang/wg-compiler-nll

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
I can remove the flag from perf quickly so will do so as soon as this PR lands.

@bors try for perf

**Comment by Mark-Simulacrum** [comment]
@rust-timer build 65cb35a64f33213e74098665538309c57a131aea

**Comment by Mark-Simulacrum** [comment]
Looks like perf results are as expected - just bringing over the regressions from the NLL dashboard.

File: src/librustc/infer/mod.rs [hunk 1]
```diff
@@ -93,7 +93,7 @@ impl SuppressRegionErrors {
     pub fn when_nll_is_enabled(tcx: TyCtxt<'_, '_, '_>) -> Self {
         match tcx.borrowck_mode() {
             // If we're on AST or Migrate mode, report AST region errors
```
Comment (pnkfelix) [inline src/librustc/infer/mod.rs]: might as well fix the comment to not refer to AST mode any more

File: src/librustc/ty/context.rs [hunk 2]
```diff
@@ -1472,21 +1471,13 @@ impl<'a, 'gcx, 'tcx> TyCtxt<'a, 'gcx, 'tcx> {
     /// because that method has a narrower effect that can be toggled
     /// off via a separate `-Z` flag, at least for the short term.
```
Comment (pnkfelix) [inline src/librustc/ty/context.rs]: add this to your to-do list in the description:  get rid of one of the two methods `allow_bind_by_move_patterns_with_guards` vs `check_for_mutation_in_guard_via_ast_walk`. (I used to have a `-Z` flag that toggle check_for_mutation_in_guard_via_ast_walk` but clearly that is not here any more...)

File: src/librustc/ty/context.rs [hunk 3]
```diff
@@ -1517,38 +1502,18 @@ impl<'a, 'gcx, 'tcx> TyCtxt<'a, 'gcx, 'tcx> {
...
-        // 1. An opts.borrowck_mode of `BorrowckMode::Ast` is
+        // 1. An opts.borrowck_mode of `BorrowckMode::Migrate` is
         //    synonymous with no `-Z borrowck=...` flag at all.
-        //    (This is arguably a historical accident.)
-        //
-        // 2. `BorrowckMode::Migrate` is the limited migration to
-        //    NLL that we are deploying with the 2018 edition.
         //
-        // 3. We want to allow developers on the Nightly channel
+        // 2. We want to allow developers on the Nightly channel
```
Comment (pnkfelix) [inline src/librustc/ty/context.rs]: there isn't really much of a precedence list anymore, compared to what we had earlier.

but I guess the comment can stay for now; when we kill off `borrowck=compare`, then that might be a good time to really kill this comment.

File: src/librustc_mir/diagnostics.rs [hunk 4]
```diff
@@ -1220,35 +1227,33 @@ let mut i = 0;
...
 let b = &i; // still ok!
 let c = &i; // still ok!
+b;
+a;
 ```
 "##,
 
 E0500: r##"
-A borrowed variable was used in another closure. Example of erroneous code:
+A borrowed variable was used by a closure. Example of erroneous code:
```
Comment (pnkfelix) [inline src/librustc_mir/diagnostics.rs]: are we supposed to be revising the text associated with error messages in this manner? Was this an expected outcome of this change?

File: src/librustc_mir/diagnostics.rs [hunk 5]
```diff
@@ -1293,26 +1296,27 @@ fn outside_closure(x: &mut i32) {
...
         inside_closure(a)
     };
     outside_closure(a); // error: cannot borrow `*a` as mutable because previous
                         //        closure requires unique access.
+    bar();
 }
 ```
 
-To fix this error, you can place the closure in its own scope:
+To fix this error, you can place finish using the closure in its own scope:
```
Comment (pnkfelix) [inline src/librustc_mir/diagnostics.rs]: are you just trying to show off NLL here? The original suggestion (of putting the closure "in its own scope") would still *work*, right?

**Comment by pnkfelix** [comment]
Ah this is so exciting!

**Comment by pnkfelix** [comment]
r=me once this is unblocked by PR #58739

File: src/librustc_mir/diagnostics.rs (hunk 4 above)
Comment (matthewjasper) [reply src/librustc_mir/diagnostics.rs]: This is a drive by fix since the documentation for this error is very outdated. The current example gives E0524.

File: src/librustc_mir/diagnostics.rs (hunk 5 above)
Comment (matthewjasper) [reply src/librustc_mir/diagnostics.rs]: Well, there's now a usage of the closure. Adding a scope would either be extraneous, or result in a name resolution error depending on how one interprets it.

**Comment by Centril** [comment]
@rfcbot merge

**Comment by pnkfelix** [comment]
Discussed in the T-lang design team meeting. One item that came up was the question of a timeline for going from NLL migrate mode to NLL hard error mode, which is actually tracked in #57895.

I'm going to write a few notes regarding that shift on #57895 itelf.

**Comment by scottmcm** [comment]
The OP implies that this PR includes two-phase borrows only for perf comparison and it won't be included in what gets actually released, but there isn't a bug number tracking it.  Is that the plan?

(Asking because of https://github.com/rust-lang/rust/issues/56254#issuecomment-451243781)

**Comment by matthewjasper** [comment]
No, it keeps a the flag around even though it does nothing so that it doesn't immediately break perf.rlo. Two phase borrows are stabilized because they mitigate some of the breakage due to soundness fixed, and for consistency between editions.

**Comment by pnkfelix** [comment]
(I attempted to clarify the point brought up by @scottmcm by editing the description text.)

**Comment by matthewjasper** [comment]
@Centril this is not making it into 1.35

**Comment by Centril** [comment]
@matthewjasper Ah... oops; I mixed this one with the "restrict..." FCP. =P

**Comment by matthewjasper** [comment]
This is just waiting for the fcp now. cc @aturon @nikomatsakis @scottmcm @withoutboats

**Comment by Mark-Simulacrum** [comment]
The relevant flags have been removed from perf, so we should be safe to remove them from master if you'd like.
