### PR TITLE
Change orphan hint from "only" to "any uncovered type inside..."

### LINKED ISSUE #128390: Error on implementation violating the orphan rules implies all types must be local when one uncovered local type is sufficient.
### Code

```Rust
impl From<()> for () {
    fn from(_: ()) {}
}
```

### Current output

```Shell
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
 --> src/lib.rs:1:1
  |
1 | impl From<()> for () {
  | ^^^^^--------^^^^^--
  | |    |            |
  | |    |            this is not defined in the current crate because tuples are always foreign
  | |    this is not defined in the current crate because this is a foreign trait
  | impl doesn't use only types from inside the current crate
  |
  = note: define and implement a trait or new type instead
```

### Desired output

```Shell
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
 --> src/lib.rs:1:1
  |
1 | impl From<()> for () {
  | ^^^^^--------^^^^^--
  | |    |            |
  | |    |            this is not defined in the current crate because tuples are always foreign
  | |    this is not defined in the current crate because this is a foreign trait
  | impl doesn't use any uncovered types from inside the current crate
  |
  = note: define and implement a trait or new type instead
```

### Rationale and extra context

_No response_

### Other cases

_No response_

### Rust Version

```Shell
Build using the Nightly version: 1.81.0-nightly(2024-07-12 c6727fc9b5c64cefa726) on the playground
```

### Anything else?

The relevant line is here [rustc_hir_analysis/messages.ftl#L354](https://github.com/rust-lang/rust/blob/master/compiler/rustc_hir_analysis/messages.ftl#L354)

### PR DESCRIPTION
**Pull request by cafce25**
Fix #128390

### CODE REVIEW

File: compiler/rustc_hir_analysis/messages.ftl [hunk 1]
```diff
@@ -351,7 +351,7 @@ hir_analysis_only_current_traits_arbitrary = only traits defined in the current
 
 hir_analysis_only_current_traits_foreign = this is not defined in the current crate because this is a foreign trait
 
-hir_analysis_only_current_traits_label = impl doesn't use only types from inside the current crate
+hir_analysis_only_current_traits_label = impl doesn't use any uncovered types from inside the current crate
```
Comment (lcnr) [inline compiler/rustc_hir_analysis/messages.ftl:354]: this is also subtly wrong

the requirement is that given an impl `impl<T0..TN> Trait<P1..Pn> for P0`, there exists an uncovered local type at position `Pi` such that `P0..Pi` does not contain any uncovered generic parameters

`impl<T> Trait<Local> for T {}` also results in this error

Comment (cafce25) [reply compiler/rustc_hir_analysis/messages.ftl:354]: That's correct of course, I didn't want to increase the verbosity too much.

What do you think of appending "before any uncovered generic parameters". This again isn't totally bullet proof as `P0` is only logically before the other `Pn` but is not before them in the source.

Comment (lcnr) [reply compiler/rustc_hir_analysis/messages.ftl:354]: maybe something like:
- "note: impl has uncovered type parameters before any local type"
- "note: for more information see <link to reference>"

Comment (cafce25) [reply compiler/rustc_hir_analysis/messages.ftl:354]: I think it's not so clear that *"no local types"* is also problematic when inverted like thisk. I prefer the original negated version. I do like the shortened *"local type"* instead of *"types from inside the current crate"*, when we link to the reference anyways I think we can get away with it as it expands on what a *"local type"* is: 

- "note: impl doesn't have any local type before any uncovered type parameters"
-  "note: for more information see https://doc.rust-lang.org/reference/items/implementations.html#orphan-rules"

I'm guessing that's the link you meant to add here? Is it ok to link to a fragment of the reference?

I'll see if I can figure out how to add multi line notes (multiple notes?).

Comment (lcnr) [reply compiler/rustc_hir_analysis/messages.ftl:354]: mutliple notes, yeah

your suggestion looks good to me

File: tests/ui/coherence/coherence-cow.re_b.stderr [hunk 2]
```diff
@@ -5,7 +5,8 @@ LL | impl<T> Remote for Pair<Cover<T>,T> { }
    | ^^^^^^^^^^^^^^^^^^^----------------
    | |                  |
    | |                  `Pair` is not defined in the current crate
-   | impl doesn't use any uncovered types from inside the current crate
+   | impl doesn't have any local type before any uncovered type parameters
+   | for more information see https://doc.rust-lang.org/reference/items/implementations.html#orphan-rules
```
Comment (lcnr) [inline tests/ui/coherence/coherence-cow.re_b.stderr:9]: vibe: I feel like these two lines should be notes, not labels

**Comment by lcnr** [comment]
one nit, apart from that r=me

**Comment by lcnr** [comment]
going through my list of active reviews today @rustbot author

**Comment by Dylan-DPC** [comment]
@cafce25 any updates on this? thanks

**Comment by cafce25** [comment]
@Dylan-DPC Thanks for checking in, dropped the ball a bit here. I've tried to just convert the labels to notes, but that leads to the [notes being mixed with repeats of the span](/cafce25/rust/commit/77cabd908138536d98bc31a63900c7d694c93fe7#diff-e6cf810834f644ec5fdaf3f5c424a37d2e885920e4e641beff4cf603aa74ea34R9-R18) which seems suboptimal so I've also moved them to the `note` field which seems a lot cleaner. @rustbot review

**Comment by lcnr** [comment]
@bors r+ rollup

thanks
