### ISSUE TITLE
im beta regression

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#44446]
The tests of the [im](https://crates.io/crates/im) crate version 6.0.0 fail on latest beta 1.21, while they work on stable. The error output (full [log](http://cargobomb-reports.s3.amazonaws.com/stable-1.20-beta-1.21.0-beta.1/beta-2017-09-02/reg/im-6.0.0/log.txt)):

```
error[E0282]: type annotations needed
    --> src/map/mod.rs:1400:18
     |
1400 |         let c1 = Map::singleton(v1, p1);
     |             --   ^^^^^^^^^^^^^^ cannot infer type for `K`
     |             |
     |             consider giving `c1` a type

```

cc @bodil

**Comment by est31** [comment]
Bisected to 560b6ca6c00b1d51aed8ca5b0cf6980b4450e19f -- #42565 cc @murarth @aturon

**Comment by arielb1** [comment]
Relevant excerpts:

https://github.com/bodil/im-rs/blob/5a48a656a67805637b84daa1c9b746c2c531181b/src/map/mod.rs#L98-L104

https://github.com/bodil/im-rs/blob/5a48a656a67805637b84daa1c9b746c2c531181b/src/map/mod.rs#L1392-L1403

https://github.com/rust-lang/rust/blob/8e0d01b432b0683d13429dcce907a2b38f30b9f6/src/liballoc/arc.rs#L1348
https://github.com/rust-lang/rust/blob/8e0d01b432b0683d13429dcce907a2b38f30b9f6/src/liballoc/arc.rs#L1371

Looks like we added a new impl and now `singleton` can't decide whether it should contain `Arc<String>` or `Arc<str>`. Expected inference breakage.

**Comment by alexcrichton** [comment]
The libs team discussed this the other day and the decision was that this indeed falls under expected inference breakage (thanks for the investigation @arielb1!). @KodrAus has [prepared a PR](https://github.com/bodil/im-rs/pull/2) with a fix, so I'll close this in the meantime.
