### ISSUE TITLE
Clang-sys does not build on rust 1.53 Nightly

### ISSUE THREAD

**Issue by ubamrein** [rust-lang/rust#84641]
I was building some library, which depended on `clang-sys` but it fails on `rustc 1.53.0-nightly (d0695c908 2021-04-12)` with a lot of error messages. When looking for the error, old issues from 2017 come up, related to `rustc-serialize`.

A prototypical example of the hundreds of errors:

```
error[E0642]: patterns aren't allowed in methods without bodies
    --> /Users/test/.cargo/registry/src/github.com-1ecc6299db9ec823/clang-sys-1.2.0/src/lib.rs:1966:37
     |
1966 |     pub fn clang_findIncludesInFile(tu: CXTranslationUnit, file: CXFile, cursor: CXCursorAndRangeVisitor) -> CXResult;
     |                                     ^^
     |
help: give this argument a name or use an underscore to ignore it
     |
1966 |     pub fn clang_findIncludesInFile(_: CXTranslationUnit, file: CXFile, cursor: CXCursorAndRangeVisitor) -> CXResult;
```

### Meta

This bug only happens on nightly.

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (d0695c908 2021-04-12)
binary: rustc
commit-hash: d0695c9081b16077d0aed368bccaf437d77ff497
commit-date: 2021-04-12
host: x86_64-apple-darwin
release: 1.53.0-nightly
LLVM version: 12.0.0
```

I also created an issue here  https://github.com/KyleMayes/clang-sys/issues/130, since I'm not sure, where the error is coming from.

**Comment by Urgau** [comment]
cc https://github.com/rust-lang/rust/issues/84162
Fixed by https://github.com/rust-lang/rust/pull/84130
