### PR TITLE
Avoid using imports in thread_local_inner! in static

### LINKED ISSUE #131863: Hygiene issues with use declarations in `thread_local!` implementation
```rust
use std::cell::RefCell;

struct Dom;

type Storage<T> = RefCell<Option<T>>;

thread_local! {
    static CURRENT_DOM: Storage<Dom> = const { RefCell::new(None) };
}
```

The above code worked in 1.80.1 but fails to compile with 1.81.0 on platforms without `cfg(target_thread_local)`. In my case this was `aarch64-linux-android`.

The issue seems to be that the macro expansion contains a use declaration that pulls in another type called `Storage` into the scope:
https://github.com/rust-lang/rust/blob/3ed6e3cc69857129c1d314daec00119ff47986ed/library/std/src/sys/thread_local/os.rs#L24-L25
This changed recently in https://github.com/rust-lang/rust/pull/126953.

A similar change was made to the implementation for platforms with `cfg(target_thread_local)` in https://github.com/rust-lang/rust/pull/125525:
https://github.com/rust-lang/rust/blob/3ed6e3cc69857129c1d314daec00119ff47986ed/library/std/src/sys/thread_local/native/mod.rs#L57-L59
Replacing `Storage` with `EagerStorage` in the example produces a similar regression for 1.79.0 -> 1.80.0.

The example is from [`yakui`](https://github.com/SecondHalfGames/yakui/blob/8e76915c46aa673a5bc9700193171156c24783ae/crates/yakui-core/src/context.rs#L6-L12).

### Version it worked on

It most recently worked on: 1.80.1

### Version with regression

`rustc --version --verbose`:
```
rustc 1.81.0 (eeb90cda1 2024-09-04)
binary: rustc
commit-hash: eeb90cda1969383f56a2637cbd3037bdf598841c
commit-date: 2024-09-04
host: x86_64-pc-windows-msvc
release: 1.81.0
LLVM version: 18.1.7
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
error[E0658]: use of unstable library feature 'thread_local_internals': internal details of the thread_local macro
 --> src\lib.rs:8:25
  |
8 |     static CURRENT_DOM: Storage<Dom> = const { RefCell::new(None) };
  |                         ^^^^^^^^^^^^

error[E0271]: expected `__init` to be a fn item that returns `Storage<Dom>`, but it returns `RefCell<Option<Dom>>`
 --> src\lib.rs:7:1
  |
7 | / thread_local! {
8 | |     static CURRENT_DOM: Storage<Dom> = const { RefCell::new(None) };
9 | | }
  | | ^
  | | |
  | |_expected `Storage<Dom>`, found `RefCell<Option<Dom>>`
  |   required by a bound introduced by this call
  |
  = note: expected struct `std::thread::local_impl::Storage<Dom>`
             found struct `RefCell<Option<Dom>>`
note: required by a bound in `std::thread::local_impl::Storage::<T>::get`
 --> /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/thread_local/os.rs:69:5
  = note: this error originates in the macro `$crate::thread::local_impl::thread_local_inner` which comes from the expansion of the macro `thread_local` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
 --> src\lib.rs:7:1
  |
7 | / thread_local! {
8 | |     static CURRENT_DOM: Storage<Dom> = const { RefCell::new(None) };
9 | | }
  | | ^
  | | |
  | |_expected `Option<&mut Option<Storage<Dom>>>`, found `Option<&mut Option<RefCell<...>>>`
  |   arguments to this method are incorrect
  |
  = note: expected enum `Option<&mut Option<std::thread::local_impl::Storage<Dom>>>`
             found enum `Option<&mut Option<RefCell<Option<Dom>>>>`
note: method defined here
 --> /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/sys/thread_local/os.rs:69:12
  = note: this error originates in the macro `$crate::thread::local_impl::thread_local_inner` which comes from the expansion of the macro `thread_local` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0308]: mismatched types
 --> src\lib.rs:7:1
  |
7 | / thread_local! {
8 | |     static CURRENT_DOM: Storage<Dom> = const { RefCell::new(None) };
9 | | }
  | |_^ expected `*const RefCell<Option<Dom>>`, found `*const Storage<Dom>`
  |
  = note: expected raw pointer `*const RefCell<Option<Dom>>`
             found raw pointer `*const std::thread::local_impl::Storage<Dom>`
  = note: this error originates in the macro `$crate::thread::local_impl::thread_local_inner` which comes from the expansion of the macro `thread_local` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0271, E0308, E0658.
For more information about an error, try `rustc --explain E0271`.
error: could not compile `minimal` (lib) due to 4 previous errors
```

</p>
</details>

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

### PR DESCRIPTION
**Pull request by youknowone**
Fixes #131863 for wasm targets

All other macros were done in #131866, but this sub module is missed.

r? @jieyouxu

### CODE REVIEW

**Comment by jieyouxu** [comment]
r? libs (I'm not a libs reviewer)

@rustbot label +beta-nominated (since #131866 was beta-nominated, but this is at discretion of T-libs)

File: library/std/src/sys/thread_local/statik.rs [hunk 1]
```diff
@@ -14,12 +14,12 @@ pub macro thread_local_inner {
     (@key $t:ty, const $init:expr) => {{
         const __INIT: $t = $init;
 
+        // NOTE: this cannot import `LocalKey` or `Storage` with a `use` because that can shadow
+        // user provided type or type alias with a matching name. Please update the shadowing test
+        // in `tests/thread.rs` if these types are renamed.
```
Comment (tgross35) [inline library/std/src/sys/thread_local/statik.rs:19]: You can probably drop the first sentence, using `$crate` is pretty standard macro procedure.

File: library/std/src/sys/thread_local/statik.rs [hunk 2]
```diff
@@ -14,12 +14,12 @@ pub macro thread_local_inner {
...
         unsafe {
-            use $crate::thread::LocalKey;
-            use $crate::thread::local_impl::EagerStorage;
-
-            LocalKey::new(|_| {
-                static VAL: EagerStorage<$t> = EagerStorage { value: __INIT };
+            $crate::thread::LocalKey::new(|_| {
+                static VAL: $crate::thread::local_impl::EagerStorage<$t> = $crate::thread::local_impl::EagerStorage { value: __INIT };
```
Comment (tgross35) [inline library/std/src/sys/thread_local/statik.rs:22]: Rewrap the long line

```rust
            $crate::thread::LocalKey::new(|_| {
                static VAL: $crate::thread::local_impl::EagerStorage<$t> =
                    $crate::thread::local_impl::EagerStorage { value: __INIT };
```

**Comment by tgross35** [comment]
If https://github.com/rust-lang/rust/pull/131866 is headed to beta then we should probably take this too.

@rustbor label +beta-nominated

File: library/std/src/sys/thread_local/statik.rs (hunk 1 above)
Comment (youknowone) [reply library/std/src/sys/thread_local/statik.rs:19]:
```suggestion
        // NOTE: Please update the shadowing test in `tests/thread.rs` if these types are renamed.
```

File: library/std/src/sys/thread_local/statik.rs (hunk 2 above)
Comment (youknowone) [reply library/std/src/sys/thread_local/statik.rs:22]:
```suggestion
            $crate::thread::LocalKey::new(|_| {
                static VAL: $crate::thread::local_impl::EagerStorage<$t> =
                    $crate::thread::local_impl::EagerStorage { value: __INIT };
```

**Comment by tgross35** [comment]
Please squash then lgtm

**Review by tgross35 — APPROVED** [review]

**Comment by jieyouxu** [comment]
Wait, not you too!
