### ISSUE TITLE
regression: destructor of `[MaybeUninit<T>; N]` cannot be evaluated at compile-time

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#115410]
### Code

I tried this code:

```rust
pub const fn f<T, const N: usize>(_: [std::mem::MaybeUninit<T>; N]) {}
```

I expected it to compile successfully. Instead, this happened:

```
error[E0493]: destructor of `[MaybeUninit<T>; N]` cannot be evaluated at compile-time
 --> x.rs:1:35
  |
1 | pub const fn f<T, const N: usize>(_: [std::mem::MaybeUninit<T>; N]) {}
  |                                   ^                                  - value is dropped here
  |                                   |
  |                                   the destructor for this type cannot be evaluated in constant functions
```

### Version it worked on

It most recently worked on 1.72

### Version with regression

Regressed in aafd75a9c510b0e91746b891eb4ebade43899af5 cc @fee1-dead @oli-obk

Originally reported in https://github.com/rust-lang/rust/issues/115403#issuecomment-1701000117 cc @itsxaos

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23115410.20regression.3A.20destructor.20of.20.60.5BMaybeUninit.3CT.3E.3B.20N.5D.60.20can.E2.80.A6)).

@rustbot label -I-prioritize +P-high
