### PR TITLE
Always create elided lifetimes, even if inferred.

### LINKED ISSUE #99949: Regression with lifetimes when using `Foo as Trait` and `Trait` has an associated lifetime
This code:

```
struct Sqlite {}

trait HasArguments<'q> {
    type Arguments;
}

impl<'q> HasArguments<'q> for Sqlite {
    type Arguments = std::marker::PhantomData<&'q ()>;
}

#[allow(dead_code)]
fn foo() {
    let _ = <Sqlite as HasArguments>::Arguments::default();
}
```

compiles on stable but not on nightly.

Error:
```
error[E0107]: missing generics for trait `HasArguments`
  --> lol.rs:13:24
   |
13 |     let _ = <Sqlite as HasArguments>::Arguments::default();
   |                        ^^^^^^^^^^^^ expected 1 lifetime argument
   |
note: trait defined here, with 1 lifetime parameter: `'q`
  --> lol.rs:3:7
   |
3  | trait HasArguments<'q> {
   |       ^^^^^^^^^^^^ --
help: add missing lifetime argument
   |
13 |     let _ = <Sqlite as HasArguments<'q>>::Arguments::default();
   |                        ~~~~~~~~~~~~~~~~

error: aborting due to previous error

For more information about this error, try `rustc --explain E0107`.
```

I bisected it to 2643b16468fda787470340890212591d8bc832b7 and then refined it; reverting 
a2254d5d7c57be00cc640c0f7a8e21b320e947aa fixes the issue.

This is the cause for https://github.com/launchbadge/sqlx/issues/2004

### PR DESCRIPTION
**Pull request by cjgillot**
`PathSource` gives the context in which a path is encountered.  The same `PathSource` is used for the full path and the `QSelf` part.

Therefore, we can only rely on `PathSource` to know whether typechecking will be able to infer the lifetimes, not whether we need to insert them at all.

Fixes https://github.com/rust-lang/rust/issues/99949

### CODE REVIEW

**Comment by lqd** [comment]
I don't know if @michaelwoerister is available for review, but this PR fixes the nightly regression that `sqlx` is hitting.

Maybe @rust-lang/types could also take a look if they have the time ?

**Comment by michaelwoerister** [comment]
Yeah, I don't really know the code involved here. @cjgillot, do you have a reviewer in mind?

**Comment by lqd** [comment]
Maybe @petrochenkov, but they're busy ? Since they reviewed https://github.com/rust-lang/rust/pull/99728 which introduced the issue, as well as many/all of the initial PRs for AST lifetime resolution.

**Comment by petrochenkov** [comment]
I'll look later today.

**Comment by lqd** [comment]
Fixes a P-critical issue:

@bors p=1

**Comment by lqd** [comment]
`Couldn't resolve host name (Could not resolve host: crates.io)`

@bors retry network issue on dist-aarch64-msvc builder

**Comment by lqd** [comment]
That was the bot taking a while to post the status here after the build failed :)
