### ISSUE TITLE
Miscompilation/regression in nightly-2017-11-21-x86_64-apple-darwin

### ISSUE THREAD

**Issue by pornel** [rust-lang/rust#46458]
The following code reliably crashes when compiled with nightly-2017-11-21-x86_64-apple-darwin (and later), but works with nightly-2017-11-20-x86_64-apple-darwin (and earlier).

```sh
rustup default nightly-2017-11-21-x86_64-apple-darwin
git clone https://github.com/pornel/lodepng-rust.git
cd lodepng-rust
cargo test --all -- test2
```

The crash is [on this line](https://github.com/pornel/lodepng-rust/blob/master/src/rustimpl.rs#L3093) where definitely-not-NULL `&mut State` magically becomes NULL.

>    frame # 2: `lodepng::rustimpl::decodeGeneric(state=0x0000000000000010, inp=(data_ptr = <no value available>, length = 123145508872728)) at rustimpl.rs:2979 [opt]`
>    frame # 3: `lodepng::rustimpl::lodepng_decode(state=0x000070000c4fe5a0, inp=<unavailable>) at rustimpl.rs:3093 [opt]`

(1.23.0-beta.1 (082b0ff02 2017-11-21) miscompiles too, stable is OK)

**Comment by Mark-Simulacrum** [comment]
Can you test with a more recent nightly and see if this still reproduces? Otherwise looks like this is a candidate for beta backport as well.

**Comment by pornel** [comment]
Today's nightly also crashes. I've bisected nightly versions to narrow it down.

**Comment by pornel** [comment]
I've noticed rustup's date are slightly off which can be misleading:

* Last good version: rustc 1.23.0-nightly (5041b3bb3 2017-11-19)
* First broken version: rustc 1.23.0-nightly (33374fa9d 2017-11-20)

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/45225 seems like the most likely culprit, cc @eddyb

**Comment by eddyb** [comment]
I am trying to reduce this and I can't even compile `lodepng-rust`, I'm getting linker errors like these:
```
= note: ./target/debug/deps/liblodepng_unittest-bbdb34f24119ed92.rlib(lodepng_unittest.o):
In function `assertNoPNGError(unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
./lodepng_unittest/vendor/lodepng_unittest.cpp:147: undefined reference to `lodepng_error_text'
```

**Comment by pornel** [comment]
Here's how far I've got with bisect:

<details>
<pre>
git bisect start
# bad: [33374fa9d09e2a790979b31e61100dfed4b44139] Auto merge of #46110 - steveklabnik:update-books, r=steveklabnik
git bisect bad 33374fa9d09e2a790979b31e61100dfed4b44139
# good: [5041b3bb3d953a14f32b15d1e41341c629acae12] Auto merge of #45454 - Aaronepower:master, r=alexcrichton
git bisect good 5041b3bb3d953a14f32b15d1e41341c629acae12
# good: [018323ffc2c38669f594b8f7025a3440ae529d2a] rustc: collapse the remains of Layout into Variants (enums vs everything else).
git bisect good 018323ffc2c38669f594b8f7025a3440ae529d2a
# good: [018323ffc2c38669f594b8f7025a3440ae529d2a] rustc: collapse the remains of Layout into Variants (enums vs everything else).
git bisect good 018323ffc2c38669f594b8f7025a3440ae529d2a
# bad: [f50fd075c2555d8511ccee8a7fe7aee3f2c45e14] Auto merge of #45225 - eddyb:trans-abi, r=arielb1
git bisect bad f50fd075c2555d8511ccee8a7fe7aee3f2c45e14
# skip: [37a7521ef93b2e2d7a4cd04df38929d841b8ffcc] rustc: unpack scalar newtype layout ABIs.
git bisect skip 37a7521ef93b2e2d7a4cd04df38929d841b8ffcc
# bad: [88e4d2c2918428d55e34cd57c11279ea839c8822] rustc_trans: work around i686-pc-windows-msvc byval align LLVM bug.
git bisect bad 88e4d2c2918428d55e34cd57c11279ea839c8822
# skip: [0b8697241f3988bfa55b9f17d60732dab0e3d75d] rustc_trans: be more relaxed with non-lvalue consumes, especially ZSTs.
git bisect skip 0b8697241f3988bfa55b9f17d60732dab0e3d75d
# good: [0190f270c1501ecb7f1b1829dcac16af8b4981e1] rustc_trans: check for layout::I1 instead of TyBool.
git bisect good 0190f270c1501ecb7f1b1829dcac16af8b4981e1
# skip: [c4d9ada70108210a2a2f7d3025a0d693fc3e3e9d] rustc: place ZSTs first during struct field reordering.
git bisect skip c4d9ada70108210a2a2f7d3025a0d693fc3e3e9d
# bad: [95687bfe27d9db705adfa9b7ae9d8e960b813b1b] rustc_trans: (hack) use preferred alignment for atomic loads/stores.
git bisect bad 95687bfe27d9db705adfa9b7ae9d8e960b813b1b
</pre>
</details>

**Comment by eddyb** [comment]
I've reproduced on Linux so I don't think the `O-macos` label is accurate.

**Comment by Mark-Simulacrum** [comment]
I wouldn't use git bisect and build, instead download the CI artifacts using [bisect-rust](https://github.com/Mark-Simulacrum/bisect-rust) and use those to bisect. Or use the bisect tool built in to that, but `git bisect` on the repo itself might be better, it's hard to say.

**Comment by eddyb** [comment]
@Mark-Simulacrum Well, @pornel was bisecting *within* my PR, so no CI artifacts.

**Comment by pornel** [comment]
My bisect narrowed it down to f62e43da2891a65a484a917d84642544ed093ba2

**Comment by eddyb** [comment]
Likely culprit found: [unsound `transmute` from a byte to an `enum`](https://github.com/pornel/lodepng-rust/blob/6e54e41103cdf6dcb2397023cb3dd17fe1e55165/src/rustimpl.rs#L2942).

**Comment by pornel** [comment]
Indeed, my fault. Sorry for wasting your time.
