### PR TITLE
Resolve: Fix an ICE introduced by import resolution error recovery

### PR DESCRIPTION
**Pull request by jseyfried**
This fixes an ICE introduced by #31065 that occurs when a path cannot be resolved because of a certain class of unresolved import (`Indeterminate` imports).
For example, this currently causes an ICE:

``` rust
mod foo { pub use self::*; }
fn main() { foo::f() }
```

r? @nrc

### CODE REVIEW

**Comment by nrc** [comment]
fails due to unused variable lint

**Comment by jseyfried** [comment]
@nrc fixed. Looks like what I removed was the only consequential use of `NameSearchType`.

**Comment by jseyfried** [comment]
@nrc rebased -- there was an implicit conflict with #31105.
