### ISSUE TITLE
regression 1.49: problem with autoderef and trait method

### ISSUE THREAD

**Issue by kodieg** [rust-lang/rust#80816]
A code attached below used to compile with rustc 1.48 (stable) and stopped to work with 1.49 (stable). Two thing help to make the code compile:
1) comment out `use arc_swap::access::Access;` 
2) explicitly deref `(*s).load()`. 

To compile code below one need to add `arc-swap = "1.2"` to Cargo.toml dependencies. Maybe this is due to some conflict between ArcSwap instance method and Access load method?

### Code

I tried this code:

```rust
use arc_swap;
use std::sync::Arc;
use arc_swap::access::Access;

pub fn foo() {
    let s: Arc<arc_swap::ArcSwap<usize>> = Arc::new(arc_swap::ArcSwap::from_pointee(32))
    let guard: arc_swap::Guard<Arc<usize>> = s.load();
}
```

I expected to see this happen: It should compile properly (it worked with rustc version 1.48 and earlier versions as well).

Instead, this happened: I got compilation error
```
error[E0283]: type annotations needed
 --> src/lib.rs:9:50
  |
9 |     let guard: arc_swap::Guard<Arc<usize>> =   s.load();
  |                                                  ^^^^ cannot infer type for type parameter `T`
  |
  = note: cannot satisfy `ArcSwapAny<Arc<usize>>: arc_swap::access::Access<_>`
  = note: required because of the requirements on the impl of `arc_swap::access::Access<_>` for `Arc<ArcSwapAny<Arc<usize>>>`
```

### Version it worked on

It most recently worked on: Rust 1.48

### Version with regression

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0
```

**Comment by SNCPlay42** [comment]
searched nightlies: from nightly-2020-10-01 to nightly-2020-11-14
regressed nightly: nightly-2020-10-07
searched commits: from https://github.com/rust-lang/rust/commit/a1dfd2490a6cb456b92e469fa550dc217e20ad6d to https://github.com/rust-lang/rust/commit/98edd1fbf8a68977a2a7c1312eb1ebff80515a92
regressed commit: https://github.com/rust-lang/rust/commit/08e2d4616613716362b4b49980ff303f2b9ae654 (#73905)

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --preserve --start=2020-10-01 --end=2020-11-14 -- check 
```
</details>

**Comment by apiraino** [comment]
Assigning `P-high` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2380816.20regression.201.2E49.3A.20problem.20with.20autoderef.20and.20trait.20me.E2.80.A6) and removing `I-prioritize`.

**Comment by SNCPlay42** [comment]
Reduced:

```rust
use std::marker::PhantomData;
use std::ops::Deref;
use std::sync::Arc;

pub struct Guard<T> {
    _phantom: PhantomData<T>,
}
impl<T> Deref for Guard<T> {
    type Target = T;
    fn deref(&self) -> &T {
        unimplemented!()
    }
}

pub struct DirectDeref<T>(T);
impl<T> Deref for DirectDeref<Arc<T>> {
    type Target = T;
    fn deref(&self) -> &T {
        unimplemented!()
    }
}

pub trait Access<T> {
    type Guard: Deref<Target = T>;
    fn load(&self) -> Self::Guard {
        unimplemented!()
    }
}
impl<T, A: Access<T>, P: Deref<Target = A>> Access<T> for P {
    type Guard = A::Guard;
}
impl<T> Access<T> for ArcSwapAny<T> {
    type Guard = Guard<T>;
}
impl<T> Access<T> for ArcSwapAny<Arc<T>> {
    type Guard = DirectDeref<Arc<T>>;
}

pub struct ArcSwapAny<T> {
    _phantom_arc: PhantomData<T>,
}

pub fn foo() {
    let s: Arc<ArcSwapAny<Arc<usize>>> = unimplemented!();
    let guard: Guard<Arc<usize>> = s.load();
}
```

**Comment by pnkfelix** [comment]
The examples now print actionable feedback for the user, in the form of errors complaining about multiple applicable impl's.

For example, the [code from the description](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=41dd7aec24086fcd25d61a891609c892) now prints:

```
error[[E0283]](https://doc.rust-lang.org/nightly/error-index.html#E0283): type annotations needed
 --> src/lib.rs:7:48
  |
7 |     let guard: arc_swap::Guard<Arc<usize>> = s.load();
  |                                                ^^^^
  |
  = note: multiple `impl`s satisfying `ArcSwapAny<Arc<usize>>: arc_swap::access::Access<_>` found in the `arc_swap` crate:
          - impl<T, S> arc_swap::access::Access<T> for ArcSwapAny<Arc<T>, S>
            where S: Strategy<Arc<T>>;
          - impl<T, S> arc_swap::access::Access<T> for ArcSwapAny<T, S>
            where T: RefCnt, S: Strategy<T>;
  = note: required for `Arc<ArcSwapAny<Arc<usize>>>` to implement `arc_swap::access::Access<_>`
help: try using a fully qualified path to specify the expected types
  |
7 |     let guard: arc_swap::Guard<Arc<usize>> = <Arc<ArcSwapAny<Arc<usize>>> as arc_swap::access::Access<T>>::load(&s);
  |                                              ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++ ~

For more information about this error, try `rustc --explain E0283`.
```

So I think this might just need a regression test.

@rustbot label: E-needs-test
