### PR TITLE
Fix Pin::set bounds regression

### LINKED ISSUE #129601: Regressions caused by changed of bounds on `Pin::set`
Our CI started failing with the nightly compiler, for a day.

### Code

I tried this code:

```rust
struct Foo {}
impl Foo {
    fn set(&self, _: bool) {}
}

fn main() {
    let foo = Foo {};
    let foo : core::pin::Pin<&Foo> = core::pin::Pin::new(&foo);
    foo.set(true);
}
```

It compiles in stable, but not with the nightly compiler:

```
error[E0277]: the trait bound `&Foo: DerefMut` is not satisfied
    --> src/main.rs:27:9
     |
27   |     foo.set(true);
     |         ^^^ the trait `DerefMut` is not implemented for `&Foo`
     |
note: required by a bound in `Pin::<Ptr>::set`
    --> /home/olivier/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/pin.rs:1478:14
     |
1476 |     pub fn set(&mut self, value: Ptr::Target)
     |            --- required by a bound in this associated function
1477 |     where
1478 |         Ptr: DerefMut,
     |              ^^^^^^^^ required by this bound in `Pin::<Ptr>::set`
help: consider mutably borrowing here
     |
27   |     (&mut foo).set(true);
     |     +++++    +

error[E0308]: mismatched types
    --> src/main.rs:27:13
     |
27   |     foo.set(true);
     |         --- ^^^^ expected `Foo`, found `bool`
     |         |
     |         arguments to this method are incorrect
     |
note: method defined here
    --> /home/olivier/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/pin.rs:1476:12
     |
1476 |     pub fn set(&mut self, value: Ptr::Target)
     |            ^^^

```

### Version it worked on

It works in beta (1.81), it only started failing with nightly very recently (one or two day)

### Version with regression

```
rustc 1.82.0-nightly (c6db1ca3c 2024-08-25)
binary: rustc
commit-hash: c6db1ca3c93ad69692a4c4b5542f26fda4bf3aec
commit-date: 2024-08-25
host: x86_64-unknown-linux-gnu
release: 1.82.0-nightly
LLVM version: 19.1.0
```

Looking at the recent history, I believe the regression is caused by https://github.com/rust-lang/rust/commit/b968b26c03510c80782c4524a334f5fa440cb2d8  (https://github.com/rust-lang/rust/pull/129449)

### PR DESCRIPTION
**Pull request by coolreader18**
Fixes #129601

Fixes the regression from #129449, where changing the bounds of the impl block containing `Pin::set` changed the method resolution behavior.

```rust
struct A;
impl A {
    fn set(&self) {}
}

let a: Pin<&A>;
a.set();
// before:
// - checks <impl<Ptr: DerefMut> Pin<Ptr>>::set(): `&A` doesn't impl `DerefMut`
// - autorefs -> &A: resolves to A::set()
// now:
// - checks <impl<Ptr: Deref> Pin<Ptr>>::set(): `&A` impls `Deref`! resolves to Pin::set()
// - check method bounds: `&A` doesn't impl DerefMut: error
```

r? @dtolnay

### CODE REVIEW

**Comment by coolreader18** [comment]
This is kinda subtle - I guess theoretically, this could be deemed an acceptable breaking change, but I don't think it's worth it given it's already demonstrated breakage.

**Comment by coolreader18** [comment]
Theoretically the same could happen with `as_mut()`, though it's much less likely that there would be a method named `as_mut` that takes `&self`

**Comment by coolreader18** [comment]
Moved all methods back to their original block, just to be safe. I still kept the order of the methods, which means that `new_unchecked` and `into_inner_unchecked` are in separate impl blocks that both have `Ptr: Deref` bounds.

**Review by dtolnay — APPROVED** [review]
Thanks!
