### ISSUE TITLE
Mismatched type error: type of crate instead of std is displayed

### ISSUE THREAD

**Issue by SWW13** [rust-lang/rust#46112]
On nightly rustc (cargo) I get misleading expected type errors. If a crate has the same(?) type it is displayed instead of the std type.

I tried this code:
```rust
extern crate bitflags;
fn test(r: Result<Option<()>, &'static str>) { }
fn main() { test(Ok(())); }
```

I expected to see this happen: (stable rust)
```
$ rustup default stable
$ cargo build
   Compiling rust-sample v0.1.0 (file:///[...]/rust-sample)
error[E0308]: mismatched types
 --> src/main.rs:3:21
  |
3 | fn main() { test(Ok(())); }
  |                     ^^
  |                     |
  |                     expected enum `std::option::Option`, found ()
  |                     help: try using a variant of the expected type: `Some(())`
  |
  = note: expected type `std::option::Option<()>`
             found type `()`
```

Instead, this happened: (nightly)
```
$ rustup default nightly
$ cargo build
   Compiling rust-sample v0.1.0 (file:///[...]/rust-sample)
error[E0308]: mismatched types
 --> src/main.rs:3:21
  |
3 | fn main() { test(Ok(())); }
  |                     ^^
  |                     |
  |                     expected enum `bitflags::<unnamed>::option::Option`, found ()
  |                     help: try using a variant of the expected type: `bitflags::<unnamed>::prelude::v1::Some(())`
  |
  = note: expected type `bitflags::<unnamed>::option::Option<()>`
             found type `()`
```

## Meta

`rustc --version --verbose`:
```
rustc 1.23.0-nightly (5041b3bb3 2017-11-19)
binary: rustc
commit-hash: 5041b3bb3d953a14f32b15d1e41341c629acae12
commit-date: 2017-11-19
host: x86_64-unknown-linux-gnu
release: 1.23.0-nightly
LLVM version: 4.0

```

**Comment by arielb1** [comment]
Confirming - broken on nightly (1.23), good on beta.

**Comment by pnkfelix** [comment]
bisected across nightlys: bug was injected between `rustc 1.23.0-nightly (02004ef78 2017-11-08)` and `rustc 1.23.0-nightly (d6b06c63a 2017-11-09)`

**Comment by pnkfelix** [comment]
Skimming output from ` git log 02004ef78^..d6b06c63a`, there are a number of different potential culprits. Rather than guess and "point fingers" right now, I'll just continue bisecting within that commit range.

**Comment by Mark-Simulacrum** [comment]
This is recent enough that we should be able to run bisect-rust on it (cc @est31).

**Comment by est31** [comment]
```
Searching in 7 commits; about 3 steps
Checking
  |                        expected enum `std::option::Option`, found ()
INFO:bisect: tested fd9ecfdfd from Thu,  9 Nov 2017 04:14:28 +0000: test failed: true
Checking
  |                        expected enum `std::option::Option`, found ()
INFO:bisect: tested da3fbe750 from Wed,  8 Nov 2017 22:27:06 +0000: test failed: true
Checking
  |                        expected enum `std::option::Option`, found ()
INFO:bisect: tested 02004ef78 from Wed,  8 Nov 2017 20:00:41 +0000: test failed: true
searched commits 02004ef78383cb174a41df7735a552823fa10b90 through d6b06c63a0c735fc15c9c704422375c17b7c7e12
regression in 0; Some(Commit { sha: "02004ef78383cb174a41df7735a552823fa10b90", date: 2017-11-08T20:00:41Z, summary: "Auto merge of #45452 - estebank:colon-typo, r=nikomatsakis" })
```

#45452 it is cc @estebank @nikomatsakis .

**Comment by estebank** [comment]
I'm a little surprised that _this_ would be caused by that PR. I can push a revert but would like to first test locally to make sure that revert that PR will fix this.

**Comment by est31** [comment]
I have misread @pnkfelix 's statement. Your PR is not at fault, sorry. I'm doing another search further back to find the causing PR.

**Comment by estebank** [comment]
@est31 I tried it locally in the meantime and I can confirm it is not :)

**Comment by est31** [comment]
Okay so the bug dates as far back as efceda220e92f02f7a29a15e4cf56f5a3cdf1792 from September 2nd which is as close to the limit as I dare to go. So to the people in control, please, prolong the limit :).

**Comment by Mark-Simulacrum** [comment]
@pnkfelix suggests that the bug was introduced much more recently (11-08 to 11-09). Maybe the bisection script was wrong?

**Comment by est31** [comment]
@Mark-Simulacrum I should probably have read the original issue more closely :). @estebank sorry for pinging you!
```
Searching in 7 commits; about 3 steps
Checking
INFO:bisect: tested fd9ecfdfd from Thu,  9 Nov 2017 04:14:28 +0000: test failed: false
Checking
  |                        expected enum `bitflags::<unnamed>::option::Option`, found ()
  |                        help: try using a variant of the expected type: `bitflags::<unnamed>::prelude::v1::Some(())`
  = note: expected type `bitflags::<unnamed>::option::Option<()>`
INFO:bisect: tested f1ea23e2c from Thu,  9 Nov 2017 18:14:48 +0000: test failed: true
Checking
INFO:bisect: tested 98e791e7e from Thu,  9 Nov 2017 15:42:26 +0000: test failed: false
searched commits 02004ef78383cb174a41df7735a552823fa10b90 through d6b06c63a0c735fc15c9c704422375c17b7c7e12
regression in 5; Some(Commit { sha: "f1ea23e2cc72cafad1dc25a06c09ec2de8e323eb", date: 2017-11-09T18:14:48Z, summary: "Auto merge of #45725 - alexcrichton:std-less-rand, r=dtolnay" })
```

It seems to be #45725 cc @alexcrichton

**Comment by pnkfelix** [comment]
In particular, I have bisected it down to the commit: 6bc8f164b09b9994e6a2d4c4ca60d7d36c09d3fe

I have been trying to further dissect that commit to figure out why it causes the change we observe here.

My current hypothesis (that I have not yet managed to confirm) is that it has to do with how we seed the hashmap's hashers with randomized state. (This commit changes our behavior in certain scenarios.) If this hypothesis is actually true, though, then I would think that this represents either a bug in hashmap itself, or a bug in how the compiler is *using* the hashmap...

**Comment by pnkfelix** [comment]
Hmm. Its something more subtle than a hashmap-related bug.

In particular, I can reproduce the old behavior on master by *just* linking in the old `librand` crate into `libstd` (in addtion to linking in the one from crates.io; doing this requires changing the name of the old `librand`), *without* making any actual calls *into* the old `librand` crate.

That, to me, seems very strange. I'm now trying to reduce down the size of the `librand` crate that I am linking in (while still causing this delta in behavior).

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by SWW13** [comment]
I still get a non std types in erros when the path has the same length. That would be okay if it is somehow deterministic, but I get different type errors within the same file for the same types.

```rust
error[E0308]: mismatched types
   --> src/bus/mod.rs:350:25
    |
350 |                         Err(BusError::ServiceTimeout(elapsed))
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found enum `std::result::Result`
    |
    = note: expected type `std::option::Option<_>`
               found type `std::result::Result<_, bus::BusError>`
```
```rust
error[E0308]: mismatched types
   --> src/bus/mod.rs:339:37
    |
339 |                     .and_then(|len| T::from_bytes(&self.buffer[0..len]))
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `serde::export::Option`, found enum `serde::export::Result`
    |
    = note: expected type `serde::export::Option<_>`
               found type `serde::export::Result<C, services::ServiceError>`
```

**Comment by pnkfelix** [comment]
@SWW13 is that a regression from the stable channel?

While I absolutely agree that a deterministic result would be better (and better stilll, a deterministic result that favored minimal-length paths rooted at `std`), I want to triage this appropriately.

**Comment by pnkfelix** [comment]
Hmm I guess since @SWW13 is the person who filed the original ticket then it is reasonable to infer that they are indeed seeing the described behavior on the stable chanenl.

**Comment by SWW13** [comment]
> @SWW13 is that a regression from the stable channel?

`cargo +stable build` gives me:
``` rust
error[E0308]: mismatched types
   --> src/bus/mod.rs:339:37
    |
339 |                     .and_then(|len| T::from_bytes(&self.buffer[0..len]))
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `serde::export::Option`, found enum `serde::export::Result`
    |
    = note: expected type `serde::export::Option<_>`
               found type `serde::export::Result<C, services::ServiceError>`

error[E0308]: mismatched types
   --> src/bus/mod.rs:350:25
    |
350 |                         Err(BusError::ServiceTimeout(elapsed))
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `serde::export::Option`, found enum `serde::export::Result`
    |
    = note: expected type `serde::export::Option<_>`
               found type `serde::export::Result<_, bus::BusError>`
```

`cargo +nightly build` seems to work now:
```rust
error[E0308]: mismatched types
   --> src/bus/mod.rs:339:37
    |
339 |                     .and_then(|len| T::from_bytes(&self.buffer[0..len]))
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found enum `std::result::Result`
    |
    = note: expected type `std::option::Option<_>`
               found type `std::result::Result<C, services::ServiceError>`

error[E0308]: mismatched types
   --> src/bus/mod.rs:350:25
    |
350 |                         Err(BusError::ServiceTimeout(elapsed))
    |                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `std::option::Option`, found enum `std::result::Result`
    |
    = note: expected type `std::option::Option<_>`
               found type `std::result::Result<_, bus::BusError>`
```

Maybe this was some sort of partial compile cache issue? I haven't found a way to reproduce these mixed errors yet.

**Comment by dtolnay** [comment]
This looks like a duplicate of #45070. That issue has some repro cases that affect the 1.22.1 stable compiler but not 1.21.0.

**Comment by ExpHP** [comment]
When I bisected the nightlies by hand on #45070 I ended up with a range that does not include the `rand` commit identified here.  Is it possible that the nondeterministic nature of the bug is also messing with our attempts to bisect?

```
Expectation: ..........................XXXXXXXXXXXXX
    Reality: ................XXX....X..X..XXXXXXXXXX
             (<-- past)                (present -->)

Legend:
   X: Commit where test fails
   .: Commit where test succeeds
```

I wonder whether merely linking `rand` affects #45070 in the same way as it affected this issue.

**Comment by arielb1** [comment]
@dtolnay 

Any evidence of this problem existing with the newest nightly?

**Comment by dtolnay** [comment]
All the cases I tried seem to have been fixed by #46708 and #46838. Nicely done! I reported one follow-up in #46991.
