### ISSUE TITLE
proc_macro_derive(attributes(path::to)) both does and doesn't work

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#55168]
```rust
// crate `derive`
// lib.proc-macro = true
#[proc_macro_derive(WellThen, attributes(well::then))]
pub fn derive(i: ::proc_macro::TokenStream) -> ::proc_macro::TokenStream {
    i
}

// crate `user`
use derive::WellThen;
#[derive(WellThen)]
#[well::then]
struct A;
```

```
error[E0433]: failed to resolve. Use of undeclared type or module `well`
  --> user\main.rs:3:3
   |
 3 | #[well::then]
   |   ^^^^ Use of undeclared type or module `well`
```

I would expect either for this to work or for `#[proc_macro_derive(attributes(..))]` to reject a path and only accept an ident, as specifying a path here doesn't work.

**Comment by petrochenkov** [comment]
This may be an accidental regression from https://github.com/rust-lang/rust/pull/50030, similarly to https://github.com/rust-lang/rust/issues/53489.

This cannot work without significant work and introducing an entirely new entity into name resolution ("derive helper modules" or something), so `#[proc_macro_derive(attributes(..))]` needs to validate its arguments harder and reject non-identifier paths.

**Comment by shepmaster** [comment]
>  reject non-identifier paths

I don't think you can do this, as these work for attributes within the type on **stable** 1.32:

```rust
use repro_derive::Example;

#[derive(Example)]
#[example::attr]     // Does not work
struct Demo {
    #[example::attr] // Works
    field: i32,
}

fn main() {}
```

```rust
extern crate proc_macro;

use proc_macro::TokenStream;

#[proc_macro_derive(Example, attributes(example::attr))]
pub fn example_derive(_input: TokenStream) -> TokenStream {
    TokenStream::new()
}
```

**Comment by petrochenkov** [comment]
Oh god.
If not reject, then issue a deprecation warning immediately.

Self-assigning, I should be able to fix it this weekend.

**Comment by shepmaster** [comment]
Is there any suggested way to have my desired syntax of

```rust
#[derive(Example)]
#[example::attr]
struct Demo {
    #[example::attr]
    field: i32,
}
```

**Comment by petrochenkov** [comment]
@shepmaster
Not right now, but something like https://github.com/rust-lang/rust/pull/57921 may help.

Actually, the derive macro itself could be able to introduce "tool modules" into scope (like `rustfmt` in `rustfmt::skip`, but not global to the whole crate).
`#[proc_macro_derive(Example, tools(example))]` or something.
Right now this is almost trivial to add for "macro expanded" attribute targets, like the item itself, but some additional work is needed to support it for other targets, e.g. fields (as you can see `#[rustfmt::skip]` doesn't work on fields yet).

**Comment by Centril** [comment]
@petrochenkov  Is there a reason we cannot let `#[proc_macro_derive(Example, attributes(example::attr))]` mean `#[proc_macro_derive(Example, tools(example))]` plus some validation for the `::attr` part? *handwave*

From a user facing perspective at least, @shepmaster's https://github.com/rust-lang/rust/issues/55168#issuecomment-467972346 example seems reasonable and "expected".

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/58899

>Is there a reason we cannot let #[proc_macro_derive(Example, attributes(example::attr))] ...

I'd prefer to see crater results first.
