### ISSUE TITLE
error[E0583]: file not found for module `bswap` - while building Rust beta with stage0 versino 1.88.0

### ISSUE THREAD

**Issue by psumbera** [rust-lang/rust#143576]
I see this when building latest Rust beta on x86_64 Solaris (there is no problem with SPARC Solaris):

```
Building stage1 library artifacts (x86_64-pc-solaris)
   Compiling shlex v1.3.0
   Compiling core v0.0.0 (/builds/psumbera/rust-lang-build/library/core)
   Compiling libc v0.2.174
   Compiling object v0.37.1
   Compiling std v0.0.0 (/builds/psumbera/rust-lang-build/library/std)
   Compiling cc v1.2.0
   Compiling compiler_builtins v0.1.160 (/builds/psumbera/rust-lang-build/library/compiler-builtins/compiler-builtins)
error[E0583]: file not found for module `bswap`
   --> library/core/src/../../stdarch/crates/core_arch/src/x86/mod.rs:613:1
    |
613 | mod bswap;
    | ^^^^^^^^^^
    |
    = help: to create the module `bswap`, create file "library/core/src/../../stdarch/crates/core_arch/src/x86/bswap.rs" or "library/core/src/../../stdarch/crates/core_arch/src/x86/bswap/mod.rs"
    = note: if there is a `mod bswap` elsewhere in the crate already, import it with `use crate::...` instead

error[E0583]: file not found for module `bt`
   --> library/core/src/../../stdarch/crates/core_arch/src/x86/mod.rs:750:1
    |
750 | mod bt;
    | ^^^^^^^
    |
    = help: to create the module `bt`, create file "library/core/src/../../stdarch/crates/core_arch/src/x86/bt.rs" or "library/core/src/../../stdarch/crates/core_arch/src/x86/bt/mod.rs"
    = note: if there is a `mod bt` elsewhere in the crate already, import it with `use crate::...` instead

error[E0583]: file not found for module `macros`
 --> library/core/src/../../stdarch/crates/core_arch/src/x86_64/mod.rs:4:1
  |
4 | mod macros;
  | ^^^^^^^^^^^
  |
  = help: to create the module `macros`, create file "library/core/src/../../stdarch/crates/core_arch/src/x86_64/macros.rs" or "library/core/src/../../stdarch/crates/core_arch/src/x86_64/macros/mod.rs"
  = note: if there is a `mod macros` elsewhere in the crate already, import it with `use crate::...` instead

error[E0583]: file not found for module `bswap`
  --> library/core/src/../../stdarch/crates/core_arch/src/x86_64/mod.rs:57:1
   |
57 | mod bswap;
   | ^^^^^^^^^^
   |
   = help: to create the module `bswap`, create file "library/core/src/../../stdarch/crates/core_arch/src/x86_64/bswap.rs" or "library/core/src/../../stdarch/crates/core_arch/src/x86_64/bswap/mod.rs"
   = note: if there is a `mod bswap` elsewhere in the crate already, import it with `use crate::...` instead

error[E0583]: file not found for module `bt`
  --> library/core/src/../../stdarch/crates/core_arch/src/x86_64/mod.rs:73:1
   |
73 | mod bt;
   | ^^^^^^^
   |
   = help: to create the module `bt`, create file "library/core/src/../../stdarch/crates/core_arch/src/x86_64/bt.rs" or "library/core/src/../../stdarch/crates/core_arch/src/x86_64/bt/mod.rs"
..
```

First bad commit was:
```
0e111a3939d66f554c3a18f0f08922ffc719604b is the first bad commit
commit 0e111a3939d66f554c3a18f0f08922ffc719604b
Author: Josh Stone [<cuviper@gmail.com>](mailto:cuviper@gmail.com)
Date:   Thu Jun 26 11:33:11 2025 -0700

    stage0 bump to 1.88.0
```

**Comment by Kobzol** [comment]
@tgross35 Do you think this can be related to the recent changes to compiler-builtins? It also mentions stdarch, but that was only moved in-tree, otherwise it still works as before.

**Comment by tgross35** [comment]
I don't think there could be any compiler-builtins interaction here since those modules are all stdarch. Maybe some config got changed in `core_arch` that is causing those modules to be missing?

**Comment by tgross35** [comment]
That doesn't seem to be the case however, no special config https://github.com/rust-lang/stdarch/blob/1b4d15df12079504942d0a3f1030b2039b8a776c/crates/core_arch/src/x86/mod.rs#L613-L615 and the module does seem to exist https://github.com/rust-lang/stdarch/blob/1b4d15df12079504942d0a3f1030b2039b8a776c/crates/core_arch/src/x86/bswap.rs

**Comment by psumbera** [comment]
Closing. Seems that there was problem with my github mirror repo I was using. After removing it and cloning again I no linger see the problem. Sorry for the noise!
