### ISSUE TITLE
regression: error[E0277]: the trait bound `Box<dyn OptValueParse<'_>>: From<&mut [char]>` is not satisfied

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#134710]
* https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/reg/app-0.6.5/log.txt

```
[INFO] [stdout] error[E0277]: the trait bound `Box<dyn OptValueParse<'_>>: From<&mut [char]>` is not satisfied
[INFO] [stdout]    --> src/ovp.rs:513:23
[INFO] [stdout]     |
[INFO] [stdout] 513 |         OptValue::new(Box::from(self))
[INFO] [stdout]     |                       ^^^ the trait `From<&mut [char]>` is not implemented for `Box<dyn OptValueParse<'_>>`
[INFO] [stdout]     |
[INFO] [stdout]     = help: the following other types implement trait `From<T>`:
[INFO] [stdout]               `Box<CStr>` implements `From<&CStr>`
[INFO] [stdout]               `Box<CStr>` implements `From<&mut CStr>`
[INFO] [stdout]               `Box<CStr>` implements `From<CString>`
[INFO] [stdout]               `Box<CStr>` implements `From<Cow<'_, CStr>>`
[INFO] [stdout]               `Box<OsStr>` implements `From<&OsStr>`
[INFO] [stdout]               `Box<OsStr>` implements `From<&mut OsStr>`
[INFO] [stdout]               `Box<OsStr>` implements `From<Cow<'_, OsStr>>`
[INFO] [stdout]               `Box<OsStr>` implements `From<OsString>`
[INFO] [stdout]             and 23 others
```

... and many more errors with different `From<_>` types.

### Version it worked on

It most recently worked on: 1.83.0

### Version with regression

Using rustc 1.84.0-beta.4 in crater https://github.com/rust-lang/rust/issues/134138.

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

**Comment by compiler-errors** [comment]
I bisected this to the rollup: https://github.com/rust-lang/rust/commit/7028d9318fadc20e5e3058d52e44d785d31a6aaa / #132555.

I'm suspicious about this PR: https://github.com/rust-lang/rust/pull/129329

**Comment by compiler-errors** [comment]
Hilariously, the implementation was changed after the crater run was performed (https://github.com/rust-lang/rust/pull/129329#issuecomment-2429780845) so the crater results are kinda useless at that point. 

@cuviper @Amanieu: Why wasn't another crater run performed after the impl was changed? 🤔

**Comment by cuviper** [comment]
I didn't pay much attention myself after handing off to libs-api.
