### PR TITLE
`needs_drop`: make more progress when given an array with variable length

### LINKED ISSUE #115410: regression: destructor of `[MaybeUninit<T>; N]` cannot be evaluated at compile-time
### Code

I tried this code:

```rust
pub const fn f<T, const N: usize>(_: [std::mem::MaybeUninit<T>; N]) {}
```

I expected it to compile successfully. Instead, this happened:

```
error[E0493]: destructor of `[MaybeUninit<T>; N]` cannot be evaluated at compile-time
 --> x.rs:1:35
  |
1 | pub const fn f<T, const N: usize>(_: [std::mem::MaybeUninit<T>; N]) {}
  |                                   ^                                  - value is dropped here
  |                                   |
  |                                   the destructor for this type cannot be evaluated in constant functions
```

### Version it worked on

It most recently worked on 1.72

### Version with regression

Regressed in aafd75a9c510b0e91746b891eb4ebade43899af5 cc @fee1-dead @oli-obk

Originally reported in https://github.com/rust-lang/rust/issues/115403#issuecomment-1701000117 cc @itsxaos

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

### PR DESCRIPTION
**Pull request by fee1-dead**
this fixes #115410.

### CODE REVIEW

**Comment by fee1-dead** [comment]
Closing, as #115527 is basically the same and has more tests
