### ISSUE TITLE
[NLL] move-guard-const.rs test use of moved value

### ISSUE THREAD

**Issue by spastorino** [rust-lang/rust#47592]
```
$ RUST_BACKTRACE=full rustc +stage1 src/test/run-pass/move-guard-const.rs -Znll -Zborrowck=mir -Ztwo-phase-borrows
error[E0382]: use of moved value: `x`
  --> src/test/run-pass/move-guard-const.rs:22:24
   |
21 |         (2, 1) if take(x) => (),
   |                        - value moved here
22 |         (1, 2) if take(x) => (),
   |                        ^ value used here after move
   |
   = note: move occurs because `x` has type `std::boxed::Box<i32>`, which does not implement the `Copy` trait

error: aborting due to previous error
```

**Comment by nikomatsakis** [comment]
Ah, this is a known issue actually.

**Comment by nikomatsakis** [comment]
Dup of https://github.com/rust-lang/rust/issues/47295

**Comment by nikomatsakis** [comment]
Well, *related* to https://github.com/rust-lang/rust/issues/47295 anyway. I'm going to keep the issue open.

**Comment by pnkfelix** [comment]
We moved this to a `compile-fail` in PR #49447
