### ISSUE TITLE
Trying to capture a local variable in a const results in an unrelated error

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#51375]
```rust
fn main() {
    let x: u8 = 5;
    const Y: u8 = x;
}
```
results in:
```
error[E0434]: can't capture dynamic environment in a fn item
 --> src/main.rs:3:19
  |
3 |     const Y: u8 = x;
  |                   ^
  |
  = help: use the `|| { ... }` closure form instead

error: aborting due to previous error
```
(which of course doesn't work — actually carrying out the suggestion results in the same suggestion).

**Comment by hellow554** [comment]
I tried to use different stable compilers to see, if there's an regression. Long long time ago, in the dark ages of 2016, there was a good error message.

_the good_

    # rustc --version
    rustc 1.10.0 (cfcb716cf 2016-07-03)
    op@VBOX /t/t/foo> rustc src/main.rs --crate-type bin 
    src/main.rs:3:19: 3:20 error: attempt to use a non-constant value in a constant [E0435]
    src/main.rs:3     const Y: u8 = x;
                                    ^
    src/main.rs:3:19: 3:20 help: run `rustc --explain E0435` to see a detailed explanation
    error: aborting due to previous error
    op@VBOX /t/t/foo> rustc --explain E0435
    A non-constant value was used to initialise a constant. Example of erroneous
    code:

    ```
    let foo = 42u32;
    const FOO : u32 = foo; // error: attempt to use a non-constant value in a
                           //        constant
    ```

    To fix this error, please replace the value with a constant. Example:

    ```
    const FOO : u32 = 42u32; // ok!
    ```

    Or:

    ```
    const OTHER_FOO : u32 = 42u32;
    const FOO : u32 = OTHER_FOO; // ok!
    ```

_the bad_

    # rustc --version
    rustc 1.15.0 (10893a9a3 2017-01-19)
    # rustc src/main.rs --crate-type bin 
    error[E0435]: attempt to use a non-constant value in a constant
     --> src/main.rs:3:19
      |
    3 |     const Y: u8 = x;
      |                   ^ non-constant used with constant

    error: aborting due to previous error

_the ugly_

    # rustc --version
    rustc 1.20.0 (f3d6973f4 2017-08-27)
    # rustc src/main.rs --crate-type bin 
    error[E0434]: can't capture dynamic environment in a fn item; use the || { ... } closure form instead
     --> src/main.rs:3:19
      |
    3 |     const Y: u8 = x;
      |                   ^

    error: aborting due to previous error

**Comment by hellow554** [comment]
Doing a bisect right now. Let's see what happend.

**Comment by hellow554** [comment]
```
fad4f32c3147cca9f2b107d0440065b9e3d6c10f is the first bad commit
commit fad4f32c3147cca9f2b107d0440065b9e3d6c10f
Author: Jonathan Turner <jturner@mozilla.com>
Date:   Fri Aug 5 15:58:31 2016 -0700

    Turn on new errors, json mode. Remove duplicate unicode test
```

**Comment by nikomatsakis** [comment]
This is not a regression. This error message is old as dirt. That said, I've always found it confusing. I think we should brainstorm an improved message for this case (where a nested item captures something from an outer item).

**Comment by nikomatsakis** [comment]
I would suggest a note

```
error[E0425]: cannot find value `x` in this scope
 --> src/main.rs:3:19
  |
3 |     const Y: u8 = x;
  |                   ^ did you mean `Y`?
  |
  | note: the variable `x` defined in the surrounding fn is not in scope within a nested `const`
```

**Comment by nikomatsakis** [comment]
cc @estebank

**Comment by estebank** [comment]
```
error[E0425]: cannot find value `x` in `const` scope
 --> src/main.rs:3:19
  |
2 |     let x: u32 = 22;
  |         - this binding is not in scope for `const` bindings
3 |     const Y: u8 = x;
  |                   ^ not found in `const` scope
  = note: `const` bindings can't access non-`const` bindings, like `x`
```

**Comment by hellow554** [comment]
I don't see, why this is an improvement to the old error message, especially to the explanation E0435 (see my [comment](https://github.com/rust-lang/rust/issues/51375#issuecomment-394964120)).
`binding` and `scope` may be the right technical terms, but sound not intuitive at all.
But I agree, that `attempt to use a non-constant value in a constant ` sounds incomplete and `in a constant scope/environment` sounds better to my (german) ears, but I like the wording "attempt to use".

**Comment by estebank** [comment]
I believe the current output is good enough:

```
error[E0435]: attempt to use a non-constant value in a constant
 --> src/main.rs:3:19
  |
3 |     const Y: u8 = x;
  |                   ^ non-constant value
```
