### PR TITLE
LLVM 16: Switch to using MemoryEffects

### LINKED ISSUE #103961: [LLVM HEAD] Build fails due to memory attribute changes
Building the compiler fails at LLVM head due to the changes introduced by https://github.com/llvm/llvm-project/commit/304f1d59ca41872c094def3aee0a8689df6aa398 ("[IR] Switch everything to use memory attribute"):

```
cargo:warning=llvm-wrapper/RustWrapper.cpp:217:12: error: no member named 'InaccessibleMemOnly' in 'llvm::Attribute'; did you mean simply 'InaccessibleMemOnly'?
--
  | cargo:warning=    return Attribute::InaccessibleMemOnly;
  | cargo:warning=           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | cargo:warning=           InaccessibleMemOnly
```

Based on my (limited) understanding the fix will not be entirely trivial, so opening an issue to track.

Found via our experimental rust + llvm at HEAD bot: https://buildkite.com/llvm-project/rust-llvm-integrate-prototype/builds/14694#01844218-71d4-4b0c-85a3-bf643a088de1

cc @nikic

### PR DESCRIPTION
**Pull request by TimNN**
This adapts the compiler to the changes required by https://github.com/llvm/llvm-project/commit/304f1d59ca41872c094def3aee0a8689df6aa398. 

AFAICT, `WriteOnly` isn't used by the compiler, all `ReadNone` uses were migrated and the remaining use of `ReadOnly` is only for function parameters.

To simplify the FFI, this PR uses an enum to represent `MemoryEffects` across the FFI boundary, which then gets mapped to the matching static factory method when constructing the attribute.

Fixes #103961.

@rustbot label +llvm-main

r? @nikic

### CODE REVIEW

File: compiler/rustc_codegen_llvm/src/llvm/ffi.rs [hunk 1]
```diff
@@ -1175,6 +1183,7 @@ extern "C" {
     pub fn LLVMRustCreateUWTableAttr(C: &Context, async_: bool) -> &Attribute;
     pub fn LLVMRustCreateAllocSizeAttr(C: &Context, size_arg: u32) -> &Attribute;
     pub fn LLVMRustCreateAllocKindAttr(C: &Context, size_arg: u64) -> &Attribute;
+    pub fn LLVMRustCreatMemoryEffectsAttr(C: &Context, effects: MemoryEffects) -> &Attribute;
```
Comment (durin42) [inline compiler/rustc_codegen_llvm/src/llvm/ffi.rs:1186]: Typo: s/Creat/Create/

(presumably elsewhere, since this compiles)

**Review by durin42 — COMMENTED** [review]
LGTM modulo the typo I spotted

File: compiler/rustc_codegen_llvm/src/llvm/ffi.rs (hunk 1 above)
Comment (TimNN) [reply compiler/rustc_codegen_llvm/src/llvm/ffi.rs]: Fixed.
