### PR TITLE
Remove a workaround for a bug

### PR DESCRIPTION
**Pull request by bjorn3**
I don't think it is necessary anymore. As I understand it from issue 39504 the original problem was that rustbuild changed a hardlink in the cargo build dir to point to copy in the sysroot while cargo may have hardlinked it to the original first. I don't think this happens anymore and as such this workaround is no longer necessary.

Split out of https://github.com/rust-lang/rust/pull/120855

### CODE REVIEW

**Comment by matthiaskrgr** [comment]
@bors rollup=iffy
I wonder if this causes the failure in https://github.com/rust-lang/rust/pull/122236#issuecomment-1986879578

**Comment by erikdesjardins** [comment]
This almost certainly causes the failure in #122229, as it's the only change that touches crate loading. And the error about multiple candidates is very similar to the code comment about two candidates.
```
   ---- library/core/src/primitive_docs.rs - prim_pointer (line 539) stdout ----
  error[E0464]: multiple candidates for `rmeta` dependency `libc` found
  Error:  --> library/core/src/primitive_docs.rs:542:1
    |
  6 | extern crate libc;
    | ^^^^^^^^^^^^^^^^^^
    |
    = note: candidate #1: /checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-7d0ebf382fa70bdc.rmeta
    = note: candidate #2: /checkout/obj/build/tmp/distcheck/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-d0cdd8731e50da55.rlib
  
  error: aborting due to 1 previous error
  
  For more information about this error, try `rustc --explain E0464`.
  Couldn't compile the test.
  
  failures:
      library/core/src/primitive_docs.rs - prim_pointer (line 539)
```

**Comment by bjorn3** [comment]
> And the error about multiple candidates is very similar to the code comment about two candidates.

The code comment talks about two possible locations for identical files, while the error here is about two different versions of the same crate. So either the comment is incorrect or the error here is not caused by this PR.

**Comment by erikdesjardins** [comment]
The comment describes itself as a super gross hack, it's probably inaccurate 😁 

At this point, all of the PRs which are common to #122229 and #122236 have landed separately except this one, so the hack does appear to be load-bearing in some way.

**Comment by RalfJung** [comment]
@bors r-
(bors sync fixup)
