### ISSUE TITLE
failure to normalize associated types in supertraits

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#61083]
This example does not compile, but I believe it ought to ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=93dea30abcab62e4116dbec77ff37b81)):

```rust
use std::vec::Vec;

trait Foo<T> { }

trait Bar<T: Iterator>: Foo<T::Item> { }

fn a(x: &(impl Foo<u32> + ?Sized)) {
    
}

fn b(y: &dyn Bar<std::vec::IntoIter<u32>>) {
    a(y)
}

fn main() {
    
}
```

we get the error:

```
error[E0277]: the trait bound `dyn Bar<std::vec::IntoIter<u32>>: Foo<u32>` is not satisfied
  --> src/main.rs:12:5
   |
12 |     a(y)
   |     ^ the trait `Foo<u32>` is not implemented for `dyn Bar<std::vec::IntoIter<u32>>`
   |
note: required by `a`
  --> src/main.rs:7:1
   |
7  | fn a(x: &(impl Foo<u32> + ?Sized)) {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Note that changing `b` like so compiles ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7a50b8a49862872b76c18ddd41e89587)):

```rust
fn b(y: &(impl Bar<std::vec::IntoIter<u32>> + ?Sized)) { }
```

**Comment by nikomatsakis** [comment]
The problem seems to be here:

https://github.com/rust-lang/rust/blob/f688ba608923bdbf6b46ec65af2f6464b6233a75/src/librustc/traits/select.rs#L2163-L2171

`util::supertraits` yields up unnormalized trait references, in particular.

**Comment by istankovic** [comment]
The example compiles with 1.73.

**Comment by fmease** [comment]
Might or might not need a regression test. Bisecting to the PR that fixed it might clear that up.
