### PR TITLE
Update bootstrap to edition 2024

### PR DESCRIPTION
**Pull request by Kobzol**
The stage0 compiler now supports edition 2024, so we can update bootstrap to it. I manually reviewed all the changes from `cargo fix --edition` and reverted most of them (`if let` -> `matches` changes and two unneeded usages of `use <>`).

r? @onur-ozkan

try-job: dist-x86_64-msvc

### CODE REVIEW

**Review by onur-ozkan — APPROVED** [review]
Looks good, thanks!

**Comment by onur-ozkan** [comment]
Waiting for CI to be green.

File: src/bootstrap/src/bin/sccache-plus-cl.rs [hunk 1]
```diff
@@ -4,8 +4,10 @@ use std::process::{self, Command};
 fn main() {
     let target = env::var("SCCACHE_TARGET").unwrap();
     // Locate the actual compiler that we're invoking
-    env::set_var("CC", env::var_os("SCCACHE_CC").unwrap());
-    env::set_var("CXX", env::var_os("SCCACHE_CXX").unwrap());
+    // SAFETY: we're in main, there are no other threads
+    unsafe { env::set_var("CC", env::var_os("SCCACHE_CC").unwrap()) };
+    // SAFETY: we're in main, there are no other threads
+    unsafe { env::set_var("CXX", env::var_os("SCCACHE_CXX").unwrap()) };
```
Comment (bjorn3) [inline src/bootstrap/src/bin/sccache-plus-cl.rs:10]: A single unsafe block with a single safety comment would be nicer IMHO.

File: src/bootstrap/src/utils/job.rs [hunk 2]
```diff
@@ -6,8 +6,10 @@ pub unsafe fn setup(_build: &mut crate::Build) {}
 
 #[cfg(all(unix, not(target_os = "haiku")))]
 pub unsafe fn setup(build: &mut crate::Build) {
-    if build.config.low_priority {
-        libc::setpriority(libc::PRIO_PGRP as _, 0, 10);
+    unsafe {
+        if build.config.low_priority {
+            libc::setpriority(libc::PRIO_PGRP as _, 0, 10);
```
Comment (bjorn3) [inline src/bootstrap/src/utils/job.rs:11]: Only the setpriority call needs to be unsafe, right?

Comment (Kobzol) [reply src/bootstrap/src/utils/job.rs:11]: Good point, this was automated by `cargo fix`, I'll reduce the scope.

**Comment by antoyo** [comment]
The GCC failure can probably fixed by updating [this file](https://github.com/rust-lang/rust/blob/master/compiler/rustc_codegen_gcc/libgccjit.version) to [this commit](https://github.com/rust-lang/gcc/commit/48664a6cab29d48138ffa004b7978d52ef73e3ac) which contains the fix for the x87 error.

**Comment by Kobzol** [comment]
I probably won't update the GCC version yet, because https://github.com/rust-lang/rust/pull/136921 is in the queue, and it would conflict with that change.

**Comment by Kobzol** [comment]
Rebased.

**Comment by onur-ozkan** [comment]
> Waiting for CI to be green.

I forgot that, sorry.

**Comment by klensy** [comment]
Failed build, rollup https://github.com/rust-lang/rust/pull/138044 will fail too.
```
2025-03-05T08:38:30.8289112Z [0m[1m[38;5;9merror[E0133][0m[0m[1m: call to unsafe function `remove_var` is unsafe and requires unsafe block[0m
2025-03-05T08:38:30.8289911Z [0m   [0m[0m[1m[38;5;12m--> [0m[0msrc/bootstrap/src/utils/cc_detect/tests.rs:210:5[0m
2025-03-05T08:38:30.8290587Z [0m    [0m[0m[1m[38;5;12m|[0m
2025-03-05T08:38:30.8294165Z [0m[1m[38;5;12m210[0m[0m [0m[0m[1m[38;5;12m|[0m[0m [0m[0m    env::remove_var("WASI_SDK_PATH");[0m
2025-03-05T08:38:30.8294898Z [0m    [0m[0m[1m[38;5;12m|[0m[0m     [0m[0m[1m[38;5;9m^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^[0m[0m [0m[0m[1m[38;5;9mcall to unsafe function[0m
2025-03-05T08:38:30.8295661Z [0m    [0m[0m[1m[38;5;12m|[0m
2025-03-05T08:38:30.8296334Z [0m    [0m[0m[1m[38;5;12m= [0m[0m[1mnote[0m[0m: consult the function's documentation for information on how to avoid undefined behavior[0m
```

**Comment by Kobzol** [comment]
Ah, this had to be added here after a rebase. Would be a nice use-case for https://github.com/rust-lang/bors/issues/60 :( Thanks for letting me know.

**Comment by jieyouxu** [comment]
To avoid confusing bors,
@bors r=@onur-ozkan

**Comment by jieyouxu** [comment]
There's probably a `cfg(windows)`'d `unsafe_op_in_unsafe_fn` in `job.rs`.
@bors r-

**Comment by Kobzol** [comment]
Ok that whole function is pretty much one giant unsafe block, I'm not sure if it makes sense to deal with the individual function calls separately.

@rustbot ready

**Comment by onur-ozkan** [comment]
> Ok that whole function is pretty much one giant unsafe block, I'm not sure if it makes sense to deal with the individual function calls separately.
> 
> @rustbot ready

It's fine I think. You can r=me.

**Comment by matthiaskrgr** [comment]
@bors r-
https://github.com/rust-lang/rust/actions/runs/13725811332/job/38391904614#step:28:22852

**Comment by Kobzol** [comment]
I'm a doofus :man_facepalming: I already fixed this before, but probably the change got lost because I rebased and force pushed from a second PC.

**Comment by jieyouxu** [comment]
My condolences. Failed in https://github.com/rust-lang/rust/pull/138326 on `dist-x86_64-msvc`:

```
 error[E0133]: call to unsafe function `windows::Win32::System::Diagnostics::Debug::SetErrorMode` is unsafe and requires unsafe block
  Error:   --> src\bootstrap\src\utils\job.rs:66:20
     |
  66 |         let mode = SetErrorMode(THREAD_ERROR_MODE::default());
     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call to unsafe function
     |
     = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2024/unsafe-op-in-unsafe-fn.html>
     = note: consult the function's documentation for information on how to avoid undefined behavior
  note: an unsafe function restricts its caller, but its body is safe by default
    --> src\bootstrap\src\utils\job.rs:63:5
     |
  63 |     pub unsafe fn setup(build: &mut Build) {
     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     = note: `-D unsafe-op-in-unsafe-fn` implied by `-D warnings`
     = help: to override `-D warnings` add `#[allow(unsafe_op_in_unsafe_fn)]`
```

@bors r-

**Comment by ChrisDenton** [comment]
Aside: We could probably add an `x check --target` step to PR CI, at least for the majority targets.

**Comment by jieyouxu** [comment]
True.

**Comment by Kobzol** [comment]
I tries crosscompiling it locally for Windowy, but it failed on building some C stuff, unexpectedly. Is there an easy way to compile it for Windows on Linux? :thinking:

**Comment by ChrisDenton** [comment]
I mean, there's not an easy way but `./x check bootstrap --target x86_64-pc-windows-msvc` should work without needing to actually build for the target. Or if it does then that seems like a bug.

**Comment by Kobzol** [comment]
> I mean, there's not an easy way but `./x check bootstrap --target x86_64-pc-windows-msvc` should work without needing to actually build for the target. Or if it doesn't then that seems like a bug.

Huh, that seems to do something, but it succeeds (not sure if the target is even taken into account, although it did print some warnings). I simply tried `cargo check --target=<msvc>` in bootstrap's directory, but that fails because it tries to run some build scripts that can't compile C code.

**Comment by onur-ozkan** [comment]
The failure doesn't seem relevant to this PR.

@bors retry
