### PR TITLE
Fix issue 85435 by restricting Fake Read precision

### LINKED ISSUE #85561: Under feature(capture_disjoint_fields), unsafe-checking has false positives under unsafe blocks
Spawned off of issue #85435 

I tried this code on nightly:

```rust
#![allow(incomplete_features)] // narrow diagnostic output
#![feature(capture_disjoint_fields)] // need this to witness the bug consistently in rustc's git history.

fn main() {
    let val: u8 = 5;
    let u8_ptr: *const u8 = &val;
    let _closure = || {
        unsafe {
            // Fails compilation with:                                                                                                                                                                                            
            // error[E0133]: dereference of raw pointer is unsafe and                                                                                                                                                             
            //               requires unsafe function or block                                                                                                                                                                    
            let tmp = *u8_ptr;
            tmp

            // Just dereferencing and returning directly compiles fine:                                                                                                                                                           
            // *u8_ptr
        }
    };
}
```

I expected to see this happen: Code accepted by compiler

Instead, this happened: 


```
error[E0133]: dereference of raw pointer is unsafe and requires unsafe function or block
  --> src/main.rs:12:23
   |
12 |             let tmp = *u8_ptr;
   |                       ^^^^^^^ dereference of raw pointer
   |
   = note: raw pointers may be null, dangling or unaligned; they can violate aliasing rules and cause data races: all of these are undefined behavior

error: aborting due to previous error

For more information about this error, try `rustc --explain E0133`.
```

Note: This has same root cause as #85435. But, we're going to address #85435 with a targeted short-term fix (namely PR #85564), so that it won't hit stable. So I'm filing this bug to track fixing the root cause.

<!-- TRIAGEBOT_START -->

<!-- TRIAGEBOT_ASSIGN_START -->

<!-- TRIAGEBOT_ASSIGN_DATA_START$${"user":"roxelo"}$$TRIAGEBOT_ASSIGN_DATA_END -->

<!-- TRIAGEBOT_ASSIGN_END -->
<!-- TRIAGEBOT_END -->

### PR DESCRIPTION
**Pull request by roxelo**
This PR fixes the root bug of issue #85435 by restricting Fake Read precision in closures and removing the feature gate introduced in PR #85564. More info [here](https://github.com/rust-lang/rust/issues/85561#issuecomment-846223784) and [here](https://github.com/rust-lang/rust/issues/85561#issuecomment-847270533).

Closes #85561

r? @nikomatsakis

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
@roxelo #85564 has landed :)

**Comment by nikomatsakis** [comment]
Do you need to update this PR, then?

**Comment by roxelo** [comment]
@nikomatsakis Yes, I need to update it so we can test it on nightly. Do I need to do something specific so the changes are available on nightly but not backported (I am not sure I fully understood how the backporting works)?

**Comment by roxelo** [comment]
Ok, I have removed the re-added feature gate so this PR should be good to merge.
