### PR TITLE
Implement optimization fuel and re-enable struct field reordering

### PR DESCRIPTION
**Pull request by ahicks92**
See [this discussion](https://internals.rust-lang.org/t/rolling-out-or-unrolling-struct-field-reorderings/4485) for background.

This pull request adds two new compilation options: `-Z print-fuel=crate` prints the optimization fuel used by a crate and `-Z fuel=crate=n` sets the optimization fuel for a crate.

It also turns field reordering back on.  There is no way to test this feature without something consuming fuel.  We can roll this back if we want, but then the optimization fuel bits will be dead code.

The one notable absence from this PR is a test case.  I'm not sure how to do one that's worth having.  The only thing I can think of to test is `-Z fuel=foo=0`.  The problem with other tests is that either (1) they're so big that future optimizations will apply, thus breaking them or (2) we don't know which order the optimizations will be applied in, so we can't guess the message that will be printed.  If someone has a useful proposal for a good test, I certainly want to add one.

### CODE REVIEW

**Comment by camlorn** [comment]
To be honest, we probably want:


r? @eddyb

**Review by eddyb — APPROVED** [review]
LGTM, except for the (accidental) submodule changes.

File: src/librustc/session/mod.rs [hunk 1]
```diff
@@ -504,6 +518,33 @@ impl Session {
         println!("Total time spent decoding DefPath tables:      {}",
                  duration_to_secs_str(self.perf_stats.decode_def_path_tables_time.get()));
     }
+
+    /// We want to know if we're allowed to do an optimization for crate crate.
```
Comment (retep998) [inline src/librustc/session/mod.rs]: Is "crate crate" intentional?

Comment (camlorn) [inline src/librustc/session/mod.rs]: Weirdly I'm going to go with yes, though crate foo might be a better choice for this phrasing.  It's something I would write, though, with the intent that the redundant crate is a variable.

**Comment by eddyb** [comment]
I was going to cc @rust-lang/compiler, but I think I'll also nominate it for discussion tomorrow.

File: src/librustc/ty/layout.rs [hunk 2]
```diff
@@ -573,12 +572,8 @@ impl<'a, 'gcx, 'tcx> Struct {
...
         // In addition, code in trans assume that 2-element structs can become pairs.
         // It's easier to just short-circuit here.
-        let mut can_optimize = (fields.len() > 2 || StructKind::EnumVariant == kind)
-            && ! (repr.c || repr.packed);
-
-        // Disable field reordering until we can decide what to do.
-        // The odd pattern here avoids a warning about the value never being read.
-        if can_optimize { can_optimize = false; }
+        let can_optimize = (fields.len() > 2 || StructKind::EnumVariant == kind)
+            && ! (repr.c || repr.packed || repr.linear || repr.simd);
```
Comment (Mark-Simulacrum) [inline src/librustc/ty/layout.rs]: This seems to be a change in behavior (and though seemingly correct, I want to make sure): before we didn't optimize for `repr(c)` and `repr(packed)`, now `repr(linear)` and `repr(simd)` are presumably added.

Comment (camlorn) [inline src/librustc/ty/layout.rs]: We didn't optimize for `repr(simd)` before.  There might be a case for removing it from the condition.  Simd vectors (used to?) go through `Layout::Vector`.  I'm not as familiar with the details as I used to be: I had to leave this for a month in the middle.  But I think leaving it for clarity is fine.

`repr(linear)` is not a thing externally.  It exists because we need to be able to remember which structs reordering was disabled for when using optimization fuel.  It is so named because there has been talk of making an RFC that adds it, and at this point it would just be exposing it via the parser.

Comment (eddyb) [inline src/librustc/ty/layout.rs]: `Layout::Vector` is still unchanged, so `repr.simd` shouldn't be a thing here.

Comment (camlorn) [inline src/librustc/ty/layout.rs]: Do you want me to kill it? I can, but it seems like the kind of thing where we might get rid of `Layout::Vector` and get mysterious breakage and I don't think it's doing any harm.

Comment (eddyb) [inline src/librustc/ty/layout.rs]: Nah it's fine like this.

**Comment by nikomatsakis** [comment]
Discussed in @rust-lang/compiler -- let's land this thing! It'd be nice to have *some* sort of tests. We talked about having a test that checks that we disabled reordering on one out of two structs (by supplying one unit of fuel). We might have to adjust the test in the future but for now it's ok.

**Comment by camlorn** [comment]
I hope to do the tests this evening when I get back.  Should they be under `run-pass`?  Going to hit the no fuel and 1 fuel cases.

**Comment by eddyb** [comment]
@camlorn Maybe an `ui` test for the layout of the structs? i.e. like the existing ones you updated here.

**Comment by camlorn** [comment]
@eddyb 
that would require knowing which one is being optimized.  @nikomatsakis's idea is better: get the size of 2 structs and assert that only one of them is right.

But this means it won't have a UI.

**Comment by eddyb** [comment]
@camlorn It's in AST order, i.e. `struct Foo; struct Bar;` will need `1` for the first and `2` for both.
That's ignoring on-demand but on-demand should only kick in if you mention that type elsewhere.

**Comment by camlorn** [comment]
@eddyb 
I will do  a UI test if that is what you really really want.  But it's kind of overkill.  All we have to do is ask if the size is right, because a bunch of other tests already cover the optimization itself.

I can't get to this tonight, it's going to have to be the morning.  It will *not* be some morning in a month from now, it will be tomorrow morning.

**Comment by camlorn** [comment]
Okay. There we go.  100% test coverage.  And I don't think any of them are even fragile.

**Comment by camlorn** [comment]
Wait, what happened here?

**Comment by alexcrichton** [comment]
bors is getting confused nowadays due to submodule updates and such, so it'll think there's a merge conflict when there isn't one. I rebased the branch and r+'d it.

**Comment by alexcrichton** [comment]
@bors: retry

* network failure https://github.com/rust-lang/rust/issues/40474

**Comment by camlorn** [comment]
Okay. This looks spurious again.  Why are all my builds cancelled by user?

**Comment by alexcrichton** [comment]
@bors: retry

* spurious sccache failure https://github.com/rust-lang/rust/issues/40240

Oh we cancel builds that are still running when one fails, but this is the failing one: https://ci.appveyor.com/project/rust-lang/rust/build/1.0.2397/job/xmn5g0alr50n86uv

**Comment by camlorn** [comment]
@alexcrichton 
I have seen this sort of thing in my C++ project that does very simple CI things.  Sometimes make just dies on Appveyor.  Has anyone inquired as to whether or not it's an Appveyor bug?

For me it's something like 1 in 10 or 1 in 20, and then I just reexecute the build manually.  not sure it's the same issue.  But on the scale of Rust 1 in 10 or 1 in 20 is obviously bad.

**Comment by alexcrichton** [comment]
Yeah this definitely seems suspicious. Googling "mingw ar.exe permission denied" gives the [first result](http://stackoverflow.com/questions/10847106/get-error-while-building-libav-on-windows-using-mingw-and-msys) claiming line endings in makefiles is at fault.

We eventually want to move the MSVC build over to Ninja (to get sccache support) so I'm thinking that we may wish to move the MinGW build over to that as well as it may help this issue.

I do think that upon closer investigation this isn't sccache related, I think it's mingw make related.

**Comment by camlorn** [comment]
@alexcrichton 
My failures aren't using MinGW.

I haven't looked into these logs closely.  But in my case it ends up feeling like something on Appveyor is touching files that shouldn't be touched while the build is going.  I just commented because a superficial glance at this looked similar to mine, and thus I'm not entirely convinced this is going to turn out  to be a Rust bug.

**Comment by alexcrichton** [comment]
Yeah I have no idea where the bug actually is, but I don't believe that AppVeyor has processes running around in the background touching files. In general they also try to make sure that we run builds in a "clean slate" with as little running on the VM except what we ourselves run as possible.

**Comment by camlorn** [comment]
@alexcrichton 
I know.  I'm just saying that I've got a fairly typical C++ project that does fairly typical things using MSVC and CMake that builds everywhere it's supposed to build without issue, except that on Appveyor it will fail nondeterministically, and always in a CMake-generated makefile.

Anecdotal, yeah.  Useful for you guys? I don't know, probably not.  But everyone is running around trying to find it and everyone else is going "O god, not again" (or at least I am).  So throw it out there.

**Comment by TimNN** [comment]
I think this failed as part of the rollup #40669, on a 32bit test:

```
---- [run-pass] run-pass/type-sizes.rs stdout ----

error: test run failed!
status: exit code: 101
command: /checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/type-sizes.stage2-i686-unknown-linux-musl 
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread 'main' panicked at 'assertion failed: `(left == right)` (left: `12`, right: `16`)', /checkout/src/test/run-pass/type-sizes.rs:68
note: Run with `RUST_BACKTRACE=1` for a backtrace.

------------------------------------------

thread '[run-pass] run-pass/type-sizes.rs' panicked at 'explicit panic', /checkout/src/tools/compiletest/src/runtest.rs:2621
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [run-pass] run-pass/type-sizes.rs

test result: FAILED. 2638 passed; 1 failed; 7 ignored; 0 measured
```

**Comment by camlorn** [comment]
yeah. This crept in last time with the same problem.  Basically `u64` has a different alignment depending on if it's 32-bit or 64-bit and therefore such tests need to always use `u16`, which doesn't.

Fix shortly.

**Comment by camlorn** [comment]
That should do it.

**Comment by camlorn** [comment]
Should the CI build have failed?  I'm seeing only passed and cancelled jobs, and there's only one that ran for longer than a minute (which is normal, also it looks good) unless I'm being very oblivious.

Does starting Buildbot kill it?

**Comment by alexcrichton** [comment]
Ah yeah the [relevant build](https://travis-ci.org/rust-lang/rust/jobs/213101187) passed, we've been having other CI troubles recently unfortunately :(

**Comment by frewsxcv** [comment]
@bors r-

Travis found some test failures

https://travis-ci.org/rust-lang/rust/jobs/213564992

**Comment by camlorn** [comment]
After a whole lot of work, I've narrowed it down to something in #39628.  I haevn't had a chance to look at it yet.

**Comment by camlorn** [comment]
I think we may need @arielb1 to comment here.  Do you know if anything in #39628 may not be accounting for field reordering?

I don't have enough understanding of the high-level architecture to track this down.  It looks like #39628 may be uncovering a problem somewhere else, say an edge case in trans that got introduced earlier.  How likely is this?  I don't think I can narrow down the diff further.

All stage 1 run-pass tests pass.  This means that whatever it is is likely to be an edge case not covered by stage 1 run-pass but found somewhere in the compiler.  I'm pretty sure that the stage 2 compiler is being mis compiled (and I think @eddyb concurs).  I'll add another run-pass test if we can track it down.

But I'm kind of at a loss, so...help?

**Comment by arielb1** [comment]
#39628 should be fairly independent of field reordering.

If you are willing to engage in brute force - all the individual commits in #39628 should compile and work, so you can bisect that.

**Comment by camlorn** [comment]
@arielb1 
Interestingly, with my patch applied on top, everything after aac5ba5dab758803b06add74457eba03bbbd9930 doesn't compile, until we get to the full PR.  It took this long to occur to me that the obvious next step is to see if it will compile on its own.  I'm doing that now.

@eddyb also thought it should be independent of field reordering.  We tried to do a thing to determine if that PR is the cause or the victim, but the procedure failed because of something with the build system.  I don't know what and may come back to it in a bit.

**Comment by arielb1** [comment]
@camlorn 

I rebased it a few times, so there might be small compilation errors.

**Comment by camlorn** [comment]
@arielb1 
Without my patch, I get the following. No one knows the cause:

```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-li
nux-gnu/lib" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/std-808b43050bfc90b4.0.o" "/mnt/c/projec
ts/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/std-808b43050bfc90b4.1.o" "/mnt/c/projects/in_progress/rust/build/x
86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/std-808b43050bfc90b4.10.o" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/st
age1-std/x86_64-unknown-linux-gnu/release/deps/std-808b43050bfc90b4.11.o" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-li
nux-gnu/release/deps/std-808b43050bfc90b4.2.o" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/std-80
8b43050bfc90b4.3.o" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/std-808b43050bfc90b4.4.o" "/mnt/c
/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/std-808b43050bfc90b4.5.o" "/mnt/c/projects/in_progress/rust/
build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/std-808b43050bfc90b4.6.o" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-
gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/std-808b43050bfc90b4.7.o" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unkno
wn-linux-gnu/release/deps/std-808b43050bfc90b4.8.o" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/s
td-808b43050bfc90b4.9.o" "-o" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/libstd-808b43050bfc90b4
.so" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps/std-808b43050bfc90b4.crate.metadata.o" "-Wl,-O1"
 "-nodefaultlibs" "-L" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1-std/x86_64-unknown-linux-gnu/release/deps" "-L" "/mnt/c/projects/in_prog
ress/rust/build/x86_64-unknown-linux-gnu/stage1-std/release/deps" "-L" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/native/libbacktrace/.libs" "-L"
 "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/native/jemalloc/lib" "-L" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/native/com
piler-rt/." "-L" "/mnt/c/projects/in_progress/rust/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,--whole-archive"
 "-l" "backtrace" "-Wl,--no-whole-archive" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-Wl,--whole-archive" "/tmp/rustc.RHhk3d4qZ0yx/libpanic_unwind-07364a3eb7
f04f75.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.RHhk3d4qZ0yx/libunwind-0766326905051606.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/
tmp/rustc.RHhk3d4qZ0yx/libcollections-24c7ce94e5ff15c6.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.RHhk3d4qZ0yx/liballoc-0916ab4b82efacbb.rlib" "-
Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.RHhk3d4qZ0yx/liballoc_jemalloc-2f651b63030214e2.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rus
tc.RHhk3d4qZ0yx/liblibc-9d136388cc16735d.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.RHhk3d4qZ0yx/libstd_unicode-75262f2f4d83e4b7.rlib" "-Wl,--no-
whole-archive" "-Wl,--whole-archive" "/tmp/rustc.RHhk3d4qZ0yx/librand-859a15715e4155e8.rlib" "-Wl,--no-whole-archive" "-Wl,--whole-archive" "/tmp/rustc.RHhk3d4qZ0yx/li
bcore-b939073f27e2de0d.rlib" "-Wl,--no-whole-archive" "/tmp/rustc.RHhk3d4qZ0yx/libcompiler_builtins-b6a59e4822710201.rlib" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m
" "-l" "rt" "-l" "util" "-shared" "-Wl,-rpath,$ORIGIN/../lib"
  = note: /tmp/rustc.RHhk3d4qZ0yx/libcollections-24c7ce94e5ff15c6.rlib(collections-24c7ce94e5ff15c6.7.o): In function `core::iter::{{impl}}::fold::{{closure}}<usize,co
re::slice::Iter<&str>,closure,usize,fn(usize, usize) -> usize>':
          /mnt/c/projects/in_progress/rust/src/libcore/iter/mod.rs:1011: undefined reference to `_$LT$usize$u20$as$u20$core..ops..Add$GT$::add::h7a78e4a0123b2b0c'
          /tmp/rustc.RHhk3d4qZ0yx/libcore-b939073f27e2de0d.rlib(core-b939073f27e2de0d.4.o): In function `core::iter::{{impl}}::fold::{{closure}}<usize,core::slice::Ite
r<&str>,closure,usize,fn(usize, usize) -> usize>':
          /mnt/c/projects/in_progress/rust/src/libcore/iter/mod.rs:1011: undefined reference to `_$LT$usize$u20$as$u20$core..ops..Add$GT$::add::h7a78e4a0123b2b0c'
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

error: Could not compile `std`.
```

If I can figure out why, I can check the rest of these commits.

**Comment by camlorn** [comment]
Also, a debugger is probably not going to be super helpful.  It may be a memory leak, but at any rate the compiler is crashing differently depending on the test according to Travis, and the bug we're trying to track down is in stage 1.

**Comment by camlorn** [comment]
@eddyb 
I tested to see if reordering a simple struct could cause Drop impls to execute on the wrong fields; this appears not to be the case.  Also, all `libcore` tests pass.  So does `libstd`, I think, but some of the network ones got stuck locally probably because of bugs in WSL (I really should stop using WSL for this).

I see two possible paths forward.  Someone tells me how to fix the linker error I keep getting stuck on and we brute force the commits, or I go turn off optimization crate-by-crate in the compiler and we hope that it's not some sort of incredibly weird inter-crate interaction (which it might be, because I'm really surprised none of our tests fail).  I'll investigate the latter when I can deal with the computer being basically unusable for a while.

I just don't know.  This is a weird one.

**Comment by nagisa** [comment]
I will try to see if this reproduces on Linux on weekend. If i can repro i will help figuring it out.

**Comment by camlorn** [comment]
thanks.

I am still here.  Short of another strategy this is going to take a very fiddly manual procedure that's going to render my development machine unusable for at least a day for anything but casual internet browsing, and I'm currently dragged into another time-sensitive project so I can't have that at the moment.

But it's not forgotten and I still want to finish it.

**Comment by nagisa** [comment]
Thanks for the ping. Trying to repro right meow.

File: src/librustc/session/mod.rs [hunk 3]
```diff
@@ -507,6 +521,33 @@ impl Session {
...
+        let mut ret = true;
+        match self.optimization_fuel_crate {
+            Some(ref c) if c == crate_name => {
+                let fuel = self.optimization_fuel_limit.get();
+                ret = fuel != 0;
+                if fuel == 0 && !self.out_of_fuel.get(){
+                    println!("optimization-fuel-exhausted: {}", msg());
+                    self.out_of_fuel.set(true);
+                }
+                else if fuel > 0{
```
Comment (eddyb) [inline src/librustc/session/mod.rs]: This should be on the previous line and have a space before `{`.

File: src/librustc/session/mod.rs [hunk 4]
```diff
@@ -507,6 +521,33 @@ impl Session {
...
+
+    /// We want to know if we're allowed to do an optimization for crate foo from -z fuel=foo=n.
+    /// This expends fuel if applicable, and records fuel if applicable.
+    pub fn consider_optimizing<T: Fn() -> String>(&self, crate_name: &str, msg: T) -> bool {
+        let mut ret = true;
+        match self.optimization_fuel_crate {
+            Some(ref c) if c == crate_name => {
+                let fuel = self.optimization_fuel_limit.get();
+                ret = fuel != 0;
+                if fuel == 0 && !self.out_of_fuel.get(){
```
Comment (eddyb) [inline src/librustc/session/mod.rs]: Missing space before `{`.

File: src/librustc_driver/lib.rs [hunk 5]
```diff
@@ -517,6 +517,14 @@ impl<'a> CompilerCalls<'a> for RustcDefaultCalls {
             control.make_glob_map = resolve::MakeGlobMap::Yes;
         }
 
+        if sess.print_fuel_crate.is_some() {
+            control.compilation_done.callback = box |state| {
```
Comment (eddyb) [inline src/librustc_driver/lib.rs]: This may be a bad idea, because it could override something else. Not sure though.

File: src/librustc_trans/intrinsic.rs [hunk 6]
```diff
@@ -622,7 +620,10 @@ pub fn trans_intrinsic_call<'a, 'tcx>(bcx: &Builder<'a, 'tcx>,
 
                     for i in 0..elems.len() {
                         let val = bcx.extract_value(val, i);
-                        bcx.store(val, bcx.struct_gep(llresult, i), None);
+                        let lval = LvalueRef::new_sized_ty(llresult, ret_ty,
+                                                           Alignment::AbiAligned);
+                        let (dest, _) = lval.trans_field_ptr(bcx, i);
```
Comment (eddyb) [inline src/librustc_trans/intrinsic.rs]: I think you're supposed to pass the second value to `store`.

File: src/librustc_trans/mir/mod.rs [hunk 7]
```diff
@@ -386,7 +386,7 @@ fn arg_local_refs<'a, 'tcx>(bcx: &Builder<'a, 'tcx>,
 
             let lvalue = LvalueRef::alloca(bcx, arg_ty, &format!("arg{}", arg_index));
             for (i, &tupled_arg_ty) in tupled_arg_tys.iter().enumerate() {
-                let dst = bcx.struct_gep(lvalue.llval, i);
+                let (dst, _) = lvalue.trans_field_ptr(bcx, i);
```
Comment (eddyb) [inline src/librustc_trans/mir/mod.rs]: Same but here it's less worrying because we *know* it can't be anything other than a tuple, and those don't get packed or anything like that, and `store_fn_arg` doesn't take such an argument.

**Review by eddyb — APPROVED** [review]
r=me with nits fixed (@nagisa, feel free to do them on your branch and I'll push here)

**Comment by TimNN** [comment]
@bors retry

* #40417

**Comment by camlorn** [comment]
@nagisa 
Thanks.

Closure arguments. Figures.  This was the weird bug last time.

Hoping this merges.

**Comment by eddyb** [comment]
@camlorn I'm really sorry I forgot about it, I thought it got fixed and never checked.

**Comment by TimNN** [comment]
@bors retry

* #40417

**Comment by camlorn** [comment]
@eddyb 
Just to repeat what got said on IRC for anyone else following, we did fix stuff related to this already.

No one is really sure how in the world the compiler passed all the tests in January at this point, but, well, it did.

**Comment by eddyb** [comment]
I figured out what was happening: in `rustc_trans` we used to have a few shims that proxied their arguments *irrespective of their types* - that means that `extern "rust-call" fn` shims (e.g. `Fn` trait objects) only saw the expanded tuples, and never had a value of the tuple type.

*However*, @arielb1's #39628 resulted in the shims in those cases (e.g. again, `Fn` trait object) being translated *the same way* as functions defined `extern "rust-call" fn`, which involved the incorrect code storing arguments to tuple fields, never have been fixed until today.

The only reason it didn't break before is because such functions are rare and require unstable Rust to write - the only semi-common example I can think of is `FnBox` which isn't usually used with multiple arguments.

**Comment by frewsxcv** [comment]
@bors retry

prioritizing https://github.com/rust-lang/rust/pull/41231 since everything in the queue will fail without it
