### ISSUE TITLE
libcore no longer builds for AVR

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#130818]
When building libcore for a custom target with [this](https://github.com/rust-lang/miri/blob/5ec5e2b2859feeba26faa3ea06fa5df6fd78aba3/tests/avr.json) target spec, I am getting a build error:

```
  warning: unused import: `insertion_sort_shift_left`
   --> /Users/runner/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/slice/sort/stable/mod.rs:9:62
    |
  9 |     SMALL_SORT_GENERAL_SCRATCH_LEN, StableSmallSortTypeImpl, insertion_sort_shift_left,
    |                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unused_imports)]` on by default
  
  warning: unused import: `crate::slice::sort::shared::smallsort::insertion_sort_shift_left`
   --> /Users/runner/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/slice/sort/unstable/mod.rs:8:5
    |
  8 | use crate::slice::sort::shared::smallsort::insertion_sort_shift_left;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  error[E0433]: failed to resolve: use of undeclared crate or module `tiny`
    --> /Users/runner/.rustup/toolchains/miri/lib/rustlib/src/rust/library/core/src/slice/sort/stable/mod.rs:65:13
     |
  65 |             tiny::mergesort(v, scratch, is_less);
     |             ^^^^ use of undeclared crate or module `tiny`
```

Last known-to-work commit: 6ce376774c0bc46ac8be247bca93ff5a1287a8fc
First known-to-not-work commit: 1b5aa96d6016bafe50e071b45d4d2e3c90fd766f

**Comment by RalfJung** [comment]
Probably caused by https://github.com/rust-lang/rust/pull/129587
Cc @Voultapher (but you're not expected to fix this since this is a tier 3 target)
