### ISSUE TITLE
Rustdoc regression (overflow evaluating the requirement …)

### ISSUE THREAD

**Issue by weiznich** [rust-lang/rust#79459]
### Code

I tried this code:

```rust
pub trait Query {}

pub trait AsQuery {
    type Query;
}

impl<T: Query> AsQuery for T {
    type Query = T;
}

pub trait SelectDsl<Selection> {
    type Output;
}

impl<T, Selection> SelectDsl<Selection> for T
where
    T: AsQuery,
    T::Query: SelectDsl<Selection>,
{
    type Output = <T::Query as SelectDsl<Selection>>::Output;
}

pub type Select<Source, Selection> = <Source as SelectDsl<Selection>>::Output;

```

I expected to see this happen: `cargo doc --no-deps` succeeds

Instead, this happened: Running `cargo doc --no-deps` failed with the following error message:

```
error[E0275]: overflow evaluating the requirement `<Source as SelectDsl<Selection>>::Output == _`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0275`.
error: could not document `rustdoc_regression`
```

(Note that compiling/checking that code via `cargo run`/`cargo check` will just work fine)

### Version it worked on

It most recently worked on: `rustdoc 1.50.0-nightly (b48cafd9e 2020-11-25)`

### Version with regression

`rustdoc --version`: 
```
rustdoc 1.50.0-nightly (72da5a9d8 2020-11-26)
binary: rustdoc
commit-hash: 72da5a9d85a522b11e80d0fdd1fd95247d442604
commit-date: 2020-11-26
host: x86_64-unknown-linux-gnu
```

If you know when this regression occurred, please add a line like below, replacing `{channel}` with one of stable, beta, or nightly.

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by weiznich** [comment]
Probably caused by https://github.com/rust-lang/rust/pull/77467, so cc @jyn514

**Comment by pksunkara** [comment]
Side question: Can we add diesel to rust test suite?

**Comment by Aaron1011** [comment]
This also happens when documenting a crate with `typenum` as a dependency.

It's caused by this code in rustdoc:

https://github.com/rust-lang/rust/blob/361543d776d832b42f022f5b3aa1ab77263bc4a9/src/librustdoc/clean/mod.rs#L1511-L1518

When we call `infcx.at(...).normalize`, trait overflow errors result in an error being reported and compilation being aborted, instead of being propagated back to the caller.

**Comment by jyn514** [comment]
<details><summary>Backtrace</summary>

```
thread 'rustc' panicked at 'aborting due to `-Z treat-err-as-bug=1`', compiler/rustc_errors/src/lib.rs:990:27
stack backtrace:
   0: std::panicking::begin_panic
   1: rustc_errors::HandlerInner::emit_diagnostic
   2: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
   3: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_overflow_error
   4: <rustc_infer::infer::InferCtxt as rustc_trait_selection::traits::error_reporting::InferCtxtExt>::report_overflow_error_cycle
   5: rustc_data_structures::obligation_forest::ObligationForest<O>::find_cycles_from_node
   6: rustc_data_structures::obligation_forest::ObligationForest<O>::find_cycles_from_node
   7: <rustc_trait_selection::traits::fulfill::FulfillmentContext as rustc_infer::traits::engine::TraitEngine>::select_where_possible
   8: <rustc_infer::infer::InferCtxtBuilder as rustc_trait_selection::infer::InferCtxtBuilderExt>::enter_canonical_trait_query
   9: rustc_traits::normalize_projection_ty::normalize_projection_ty
  10: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::normalize_projection_ty>::compute
  11: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  12: rustc_data_structures::stack::ensure_sufficient_stack
  13: rustc_query_system::query::plumbing::get_query_impl
  14: <rustc_trait_selection::traits::query::normalize::QueryNormalizer as rustc_middle::ty::fold::TypeFolder>::fold_ty
  15: <rustc_infer::infer::at::At as rustc_trait_selection::traits::query::normalize::AtExt>::normalize
  16: rustc_infer::infer::InferCtxtBuilder::enter
  17: rustdoc::clean::clean_qpath
  18: <rustc_hir::hir::Ty as rustdoc::clean::Clean<rustdoc::clean::types::Type>>::clean
  19: rustdoc::core::DocContext::with_param_env
  20: <(&rustc_hir::hir::Item,core::option::Option<rustc_span::symbol::Ident>) as rustdoc::clean::Clean<alloc::vec::Vec<rustdoc::clean::types::Item>>>::clean
  21: <alloc::vec::Vec<T,A> as alloc::vec::SpecExtend<T,I>>::spec_extend
  22: <rustdoc::doctree::Module as rustdoc::clean::Clean<rustdoc::clean::types::Item>>::clean
  23: rustdoc::clean::utils::krate
  24: rustdoc::core::run_global_ctxt
  25: rustc_interface::passes::QueryContext::enter
  26: rustc_interface::interface::create_compiler_and_run
  27: rustdoc::main_options
  28: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</details>

So we need to change https://github.com/rust-lang/rust/blob/361543d776d832b42f022f5b3aa1ab77263bc4a9/compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs#L208
not to abort.

This comment was added in 8bd8466e812e7c5acb99a50493e45aeb1bb81e93: https://github.com/rust-lang/rust/blob/361543d776d832b42f022f5b3aa1ab77263bc4a9/compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs#L171-L176
@nikomatsakis would it maybe be possible for the caller to say whether it wants to abort or not?

**Comment by jyn514** [comment]
Actually I guess the issue is that the type length limit code shouldn't be called at all, otherwise it will still emit an error even if it doesn't abort.

**Comment by jyn514** [comment]
I guess in the meantime #77467 should probably be reverted :(

**Comment by Aaron1011** [comment]
As a side note, this ended up putting the CI workflow for https://github.com/rust-lang/cargo in a broken state, as this overflow occurs when trying to document `cargo` on the latest nightly. See https://github.com/rust-lang/cargo/pull/8906 for an example of this.

If we have the CI budget, I think it would be a good idea to generate (but not upload) the docs for tools, to ensure that this kind of problem can't happen again.

**Comment by camelid** [comment]
Assigning `P-critical` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2379459.20Rustdoc.20regression.20(overflow.20evaluating.E2.80.A6) in the prioritization working group.

**Comment by jyn514** [comment]
> I think one solution would be to run the normalization in TraitQueryMode::Canonical, which propagates overflow error to the caller instead of reporting a user-facing error. Unfortunately, the normalization code creates a SelectionContext behind several layers of indirection, so passing along a TraitQueryMode could be fairly ugly.

@Aaron1011 it looks like it's already run in canonical mode:

```
query stack during panic:
#0 [normalize_projection_ty] normalizing `Canonical { max_universe: U0, variables: [], value: ParamEnvAnd { param_env: ParamEnv { caller_bounds: [TraitPredicate(<Selection as std::marker::Sized>), TraitPredicate(<Source as std::marker::Sized>)], reveal: UserFacing }, value: ProjectionTy { substs: [Source, Selection], item_def_id: DefId(0:11 ~ normalize_type_length_limit[8787]::SelectDsl::Output) } } }`
end of query stack
```

**Comment by Aaron1011** [comment]
Confusing, there are two kinds of 'canonical' involved here. One is 'query canonicalization', which involve the wrapping `Canonical` struct in the query stack you posted.

In this case, what we need is `TraitQueryMode::Canonical`. The `normalize_projection_ty` query calls `SelectionContext::new`:

https://github.com/rust-lang/rust/blob/774bce7f5e9d0cc99a30cf37be5d175a3b530beb/compiler/rustc_traits/src/normalize_projection_ty.rs#L27

which sets the mode to `TraitQueryMode::Standard`

**Comment by jyn514** [comment]
@Aaron1011 unfortunately, that didn't help, this still fails with the same error:

```diff
diff --git a/compiler/rustc_trait_selection/src/traits/select/mod.rs b/compiler/rustc_trait_selection/src/traits/select/mod.rs
index 5b31998b7d3..8a78fa96d53 100644
--- a/compiler/rustc_trait_selection/src/traits/select/mod.rs
+++ b/compiler/rustc_trait_selection/src/traits/select/mod.rs
@@ -218,7 +218,7 @@ pub fn new(infcx: &'cx InferCtxt<'cx, 'tcx>) -> SelectionContext<'cx, 'tcx> {
             intercrate: false,
             intercrate_ambiguity_causes: None,
             allow_negative_impls: false,
-            query_mode: TraitQueryMode::Standard,
+            query_mode: TraitQueryMode::Canonical,
         }
     }
 
```

**Comment by jyn514** [comment]
A slightly smaller reproduction ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=94f1c00cfd195ca1addcee2f30ad71ec)):
```
#![feature(no_core)]
#![no_core]

pub trait AsQuery {
    type Query;
}

impl<T> AsQuery for T {
    type Query = usize;
}

pub trait SelectDsl {
    type Output;
}

impl<T> SelectDsl for T
where
    T: AsQuery,
    // comment this out to get the same error in rustc ...
    T::Query: SelectDsl,
{
    type Output = <T::Query as SelectDsl>::Output;
}

pub type Select<Source> = <Source as SelectDsl>::Output;
// ... or uncomment this to get the same error
//pub struct S(Select<usize>);
```

**Comment by jyn514** [comment]
This was fixed by https://github.com/rust-lang/rust/pull/79469.
