### ISSUE TITLE
[1.30 beta] Multiple applicable items in scope

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54474]
Multiple crates are failing to build in 1.30 beta because multiple applicable items are in scope.

```
 error[E0034]: multiple applicable items in scope
     --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/petgraph-0.4.9/src/graph_impl/stable_graph/mod.rs:1172:19
      |
 1172 |         self.iter.find_map(|(i, node)| {
      |                   ^^^^^^^^ multiple `find_map` found
      |
```

* [Jengamon/Mister](https://github.com/Jengamon/Mister) regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/gh/Jengamon.Mister/log.txt)) cc @Jengamon
* [YaLTeR/aoc2017](https://github.com/YaLTeR/aoc2017) regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/gh/YaLTeR.aoc2017/log.txt)) cc @YaLTeR 
* [anderejd/cargo-geiger](https://github.com/anderejd/cargo-geiger) regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/gh/anderejd.cargo-geiger/log.txt)) cc @anderejd
* [danieldk/conllx-utils](https://github.com/danieldk/conllx-utils) regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/gh/danieldk.conllx-utils/log.txt)) cc @danieldk
* [pkgw/stund](https://github.com/pkgw/stund) regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/gh/pkgw.stund/log.txt)) cc @pkgw

cc @petrochenkov

**Comment by withoutboats** [comment]
All of these are binaries with checked in lockfiles that depend on a petgraph version `^0.4.0`, because of their lockfiles they aren't getting `0.4.13`, which fixes this regression in petgraph. Not sure what our protocol here is (in terms of following up with impacted crates) but this is expected breakage.

**Comment by YaLTeR** [comment]
As the author of one of the impacted repositories I appreciate this protocol a lot too. Although in this particular case my repo contains some unimportant stuff so I don't mind it breaking.

**Comment by alexcrichton** [comment]
This was added in https://github.com/rust-lang/rust/pull/49098 and stabilized in https://github.com/rust-lang/rust/pull/53385. Unfortunately we didn't do crater runs at the time, but that's why we do it for beta!

I'll put this on the libs team triage agenda, but given that this is fixed in the most recent versions and only locked projects are getting this it's probably unlikely we'll decide to revert. That being said if anyone has difficulty upgrading please let us know!
