### PR TITLE
rustbuild: Move compiler-builtins build logic to manifest

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit moves the compiler-builtins-specific build logic from
`src/bootstrap/bin/rustc.rs` into the workspace `Cargo.toml`'s
`[profile]` configuration. Now that rust-lang/cargo#7253 is fixed we can
ensure that Cargo knows about debug assertions settings, and it can also
be configured to specifically disable debug assertions unconditionally
for compiler-builtins. This should improve rebuild logic when
debug-assertions settings change and also improve build-std integration
where Cargo externally now has an avenue to learn how to build
compiler-builtins as well.

### CODE REVIEW

**Comment by ehuss** [comment]
There will be a few more steps before this can help build-std.  The root manifest is not included in the src distribution (https://github.com/rust-lang/wg-cargo-std-aware/issues/27).  Even if it was, Cargo would need to merge the profiles somehow (possibly just the overrides?) (cc https://github.com/rust-lang/wg-cargo-std-aware/issues/28).

**Comment by alexcrichton** [comment]
Oh it's true yeah I don't expect this to "simply by default" help build-std, but at least in this form the information is encoded in a way that build-std has any hope of reading one day!

**Comment by Mark-Simulacrum** [comment]
@bors r+

One thing I've been thinking about is that more broadly, removing support for configuring these values in config.toml may make some sense. On the other hand, it does seem true that it's nice to have the .gitignore'd nature of config.toml which you can't readily get with Cargo.toml today (due to lack of cargo.toml inheritance) as far as I know.

**Comment by Manishearth** [comment]
Seeing a failure in https://github.com/rust-lang/rust/pull/73768#issuecomment-650253965 , might be y'all, but it might also be a bad interaction with a different PR

```
Caused by:
  could not parse input as TOML

Caused by:
  redefinition of table `profile.release.package.compiler_builtins` for key `profile.release.package.compiler_builtins` at line 46 column 1
```
