### PR TITLE
do not reverse the expected type and found type for ObligationCauseCo…

### LINKED ISSUE #102397: "`if` may be missing an `else` clause" sometimes reverses expectations
Given the following code:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5a939f14b1d92d9d4b3a3edbbb46f5c0

```rust
fn missing_else(x: i32) -> i32 {
    if true {
        return 1
    }
}

fn missing_else_nested(x: i32) -> i32 {
    if x < 0 {
        0
    } else {
        if true {
            return 1
        }
    }
}
```

The current output is:

```
error[E0317]: `if` may be missing an `else` clause
 --> src/lib.rs:2:5
  |
1 |   fn missing_else(x: i32) -> i32 {
  |                              --- expected `i32` because of this return type
2 | /     if true {
3 | |         return 1
4 | |     }
  | |_____^ expected `i32`, found `()`
  |
  = note: `if` expressions without `else` evaluate to `()`
  = help: consider adding an `else` block that evaluates to the expected type

error[E0317]: `if` may be missing an `else` clause
  --> src/lib.rs:11:9
   |
11 | /         if true {
12 | |             return 1
   | |             -------- found here
13 | |         }
   | |_________^ expected `()`, found `i32`
   |
   = note: `if` expressions without `else` evaluate to `()`
   = help: consider adding an `else` block that evaluates to the expected type
```

Note how the expected and found types are reversed for the `missing_else_nested` error and how the note about the function's return type is gone, compared to the `missing_else` error.

Ideally the output for the `missing_else_nested` error should be similar to the error for `missing_else`:

```
error[E0317]: `if` may be missing an `else` clause
  --> src/lib.rs:11:9
  |
7 |   fn missing_else_nested(x: i32) -> i32 {
  |                                     --- expected `i32` because of this return type
   |
11 | /         if true {
12 | |             return 1
   | |             -------- found here
13 | |         }
   | |_________^ expected `i32`, found `()`
   |
   = note: `if` expressions without `else` evaluate to `()`
   = help: consider adding an `else` block that evaluates to the expected type
```

This kinda duplicates #78656, but @estebank asked me to file a new issue on [Twitter](https://twitter.com/nokusu/status/1573317380897443840).

### PR DESCRIPTION
**Pull request by lyming2007**
…de of IfExpressionWithNoElse

this will fix #102397

### CODE REVIEW

File: compiler/rustc_hir_analysis/src/check/_match.rs [hunk 1]
```diff
@@ -259,7 +259,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
                 err.help("consider adding an `else` block that evaluates to the expected type");
                 error = true;
             },
-            ret_reason.is_none(),
```
Comment (compiler-errors) [inline compiler/rustc_hir_analysis/src/check/_match.rs:262]: For reference, this was originally introduced in ffa40cb45c195e317602437d8a40178e72807d46.

Comment (lyming2007) [reply compiler/rustc_hir_analysis/src/check/_match.rs:262]: I've noticed that commit. 
But the actual parameter of my fix will affect `label_expression_as_expected` in function `fn coerce_inner` which will reverse the expected type and found type when `label_expression_as_expected`  being true.
Before my fix, `label_expression_as_expected` being `false `when the parent of the `if `statement is function, which was wrong. Because we can't reverse the expected type and found type no matter what the parent of the `if` statement is.
I can't think of any cases of `if` statement without an `else` branch that needs to reverse the expected type and found type. If you can think of one, please let me know, I would investigate more.
The expected result of following test cases were wrong as you can tell from my fix.
```
src/test/ui/expr/if/if-without-else-result.rs
src/test/ui/expr/if/issue-4201.rs
src/test/ui/issues/issue-19991.rs
src/test/ui/async-await/issue-66387-if-without-else.rs
```
For example `src/test/ui/expr/if/issue-4201.rs`
apparently, the compiler should emit 
`expected integer, found `()``  but we emit `expected `()`, found integer`, which was reversed by mistake.

**Comment by compiler-errors** [comment]
I guess this is fine.

@bors r+ rollup
