### ISSUE TITLE
Confusing diagnostic when argument type in impl FnOnce() is not found

### ISSUE THREAD

**Issue by GoldsteinE** [rust-lang/rust#113566]
### Code

```Rust
type Foo = Bar;

fn check(f: impl FnOnce(Foo), val: Foo) {
    f(val);
}
```

### Current output

```
Compiling playground v0.0.1 (/playground)
error[E0412]: cannot find type `Bar` in this scope
 --> src/lib.rs:1:12
  |
1 | type Foo = Bar;
  |            ^^^ not found in this scope

error[E0618]: expected function, found `impl FnOnce(Foo)`
 --> src/lib.rs:4:5
  |
3 | fn check(f: impl FnOnce(Foo), val: Foo) {
  |          - `f` has type `impl FnOnce(Foo)`
4 |     f(val);
  |     ^-----
  |     |
  |     call expression requires function

Some errors have detailed explanations: E0412, E0618.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `playground` (lib) due to 2 previous errors
```

### Desired output

```
Compiling playground v0.0.1 (/playground)
error[E0412]: cannot find type `Bar` in this scope
 --> src/lib.rs:1:12
  |
1 | type Foo = Bar;
  |            ^^^ not found in this scope


Some errors have detailed explanations: E0412, E0618.
For more information about an error, try `rustc --explain E0412`.
error: could not compile `playground` (lib) due to 2 previous errors
```

### Rationale and extra context

Saying that `impl FnOnce()` is not a function is confusing and distracts from the real issue. I think compiler should either report nothing on the line with the call or say something about unknown types in function signature.

### Other cases

```Rust
type Foo = Bar;

// Doesn’t exhibit this issue
fn check(f: impl FnOnce() -> Foo) {
    f();
}
```

**Comment by compiler-errors** [comment]
I think this regressed in #106309. I still think that PR is worthwhile, even though this regression makes this error a bit more confusing -- let me see if I can suppress it via other means.

**Comment by chriskrycho** [comment]
I ran into this today, and the current status is *extremely* non-obvious when the actual underlying issue is a mismatch in the argument types for a closure passed vs. what is expected. The "expected function, found…" is difficult for an end user to understand; I figured out that it was actually a mismatched argument type only because I could connect it to the kind of refactor I was in the middle of and thinking through what other errors happened to be "in scope".
