### ISSUE TITLE
Regression with lifetimes when using `Foo as Trait` and `Trait` has an associated lifetime

### ISSUE THREAD

**Issue by Eijebong** [rust-lang/rust#99949]
This code:

```
struct Sqlite {}

trait HasArguments<'q> {
    type Arguments;
}

impl<'q> HasArguments<'q> for Sqlite {
    type Arguments = std::marker::PhantomData<&'q ()>;
}

#[allow(dead_code)]
fn foo() {
    let _ = <Sqlite as HasArguments>::Arguments::default();
}
```

compiles on stable but not on nightly.

Error:
```
error[E0107]: missing generics for trait `HasArguments`
  --> lol.rs:13:24
   |
13 |     let _ = <Sqlite as HasArguments>::Arguments::default();
   |                        ^^^^^^^^^^^^ expected 1 lifetime argument
   |
note: trait defined here, with 1 lifetime parameter: `'q`
  --> lol.rs:3:7
   |
3  | trait HasArguments<'q> {
   |       ^^^^^^^^^^^^ --
help: add missing lifetime argument
   |
13 |     let _ = <Sqlite as HasArguments<'q>>::Arguments::default();
   |                        ~~~~~~~~~~~~~~~~

error: aborting due to previous error

For more information about this error, try `rustc --explain E0107`.
```

I bisected it to 2643b16468fda787470340890212591d8bc832b7 and then refined it; reverting 
a2254d5d7c57be00cc640c0f7a8e21b320e947aa fixes the issue.

This is the cause for https://github.com/launchbadge/sqlx/issues/2004

**Comment by Eijebong** [comment]
ping @cjgillot since you're the author of the commit

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2399949.20Regression.20with.20lifetimes.20when.20using.20.60Foo.20as.20Trait.60.20.E2.80.A6)).

@rustbot label -I-prioritize +P-critical

**Comment by lqd** [comment]
note: there's a fix in https://github.com/rust-lang/rust/pull/99953 ready for review
