### ISSUE TITLE
cannot resolve `std::borrow::Cow<'_, str>: std::borrow::Borrow<_>`

### ISSUE THREAD

**Issue by jebrosen** [rust-lang/rust#50954]
This code fails to compile on nightly 2018-05-20 ([playground](https://play.rust-lang.org/?gist=f150a7d94f6d933d302d30844d30971a&version=nightly&mode=debug)):

```
use std::borrow::{Borrow, Cow};

fn takes_into_cow<'a, T: Into<Cow<'a, str>>>(x: T) {
    let s = x.into();
    println!("{}", s);
}

fn forward_cow<'a>(x: Cow<'a, str>) {
    takes_into_cow(x.borrow())
}

fn main() {
    forward_cow("test".into());
}
```

With this error:

```
error[E0283]: type annotations required: cannot resolve `std::borrow::Cow<'_, str>: std::borrow::Borrow<_>`
 --> src/main.rs:9:22
  |
9 |     takes_into_cow(x.borrow())
  |                      ^^^^^^
```

This compiles fine on stable and beta, and probably on nightly as well until some time in the last week or so.

This is a simplified version of the code involved in SergioBenitez/Rocket#643.

**Comment by leodasvacas** [comment]
probably caused by #50170, we didn't do a crater run for that one. In that PR we added:
```rust
impl<'a> From<&'a String> for Cow<'a, str>
```
But we already have:
```rust
impl<'a> From<&'a str> for Cow<'a, str>
```
This makes the following `Borrow` impl ambiguous in this case:
```rust
impl<'a, B> Borrow<B> for Cow<'a, B> where B: ToOwned
```

I think we should revert the new impl, it looks very redundant with the existing one anyways.

**Comment by pietroalbini** [comment]
Scheduled a check-only crater run. Should start in a few days.

**Comment by jebrosen** [comment]
I think the only problematic impls added were `impl From<&'a T::Owned> for Cow<'a, T>`. This is the last one in each "chunk" of https://github.com/rust-lang/rust/pull/50170#issuecomment-385820578.

The same error occurs with this CString case: 
```
use std::borrow::{Borrow, Cow};
use std::ffi::{CStr, CString};

fn main() {
    let x = CString::new("x").unwrap();
    let y: Cow<CStr> = x.borrow().into();
}
```

No code should be doing this one already, but it appears that the existence of `impl From<&'a CString> for Cow<'a, CStr>` makes `impl From<&'a CStr> for Cow<'a, CStr>` less useful, so I would argue against those ones.

**Comment by pietroalbini** [comment]
Hi @leodasvacas  (crater requester)! Crater results are at: http://cargobomb-reports.s3.amazonaws.com/issue-50954/index.html. 'Blacklisted' crates (spurious failures etc) can be found [here](https://github.com/rust-lang-nursery/crater/blob/master/config.toml). If you see any spurious failures not on the list, please make a PR against that file.

(interested observers: Crater is a tool for testing the impact of changes on the crates.io ecosystem. You can find out more at the [repo](https://github.com/rust-lang-nursery/crater/) if you're curious)

**Comment by kennytm** [comment]
ogrep-0.2.1:

```
May 25 11:49:29.066 INFO kablam! error[E0283]: type annotations required: cannot resolve `std::borrow::Cow<'_, str>: std::convert::From<&_>`
May 25 11:49:29.066 INFO kablam!    --> src/main.rs:541:17
May 25 11:49:29.066 INFO kablam!     |
May 25 11:49:29.066 INFO kablam! 541 |                 Cow::from(options.pattern.as_ref())
May 25 11:49:29.066 INFO kablam!     |                 ^^^^^^^^^
May 25 11:49:29.066 INFO kablam!     |
May 25 11:49:29.066 INFO kablam!     = note: required by `std::convert::From::from`
```

screen-api-0.4.1:

```
May 25 17:33:44.418 INFO kablam! error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
May 25 17:33:44.418 INFO kablam!    --> src/websocket/types/mod.rs:163:76
May 25 17:33:44.419 INFO kablam!     |
May 25 17:33:44.419 INFO kablam! 163 |             } => Channel::room_map_view(room_name, shard_name.as_ref().map(AsRef::as_ref)),
May 25 17:33:44.419 INFO kablam!     |                                                                            ^^^^^^^^^^^^^
May 25 17:33:44.419 INFO kablam!     |
May 25 17:33:44.419 INFO kablam!     = note: required by `std::convert::AsRef::as_ref`
```

travis-0.1.1:

```
May 25 22:28:02.573 INFO kablam! error[E0283]: type annotations required: cannot resolve `std::string::String: std::convert::AsRef<_>`
May 25 22:28:02.573 INFO kablam!   --> examples/demo.rs:60:50
May 25 22:28:02.573 INFO kablam!    |
May 25 22:28:02.573 INFO kablam! 60 |             let builds = travis.builds(repo.slug.as_ref());
May 25 22:28:02.573 INFO kablam!    |                                                  ^^^^^^
```

**Comment by leodasvacas** [comment]
This also happens with `AsRef`, I think it's because of the following impl:
```rust
impl<'a, T: ?Sized + ToOwned> AsRef<T> for Cow<'a, T>
```
I'm not sure what the motivation for the problematic impls was, but if it was to improve functions that take `T: Into<Cow<_>>` then it might have backfired. Though the set of regressions is small enough that we could consider it acceptable, if we want the impls.

**Comment by jebrosen** [comment]
All three of those look like a case of `String -> AsRef::as_ref() -> Cow::from()` failing to resolve, so I don't see how `impl<'a, T: ?Sized + ToOwned> AsRef<T> for Cow<'a, T>` could come into it. I thought there was some blanket `impl <T> AsRef<T> for T` but that's not the case, so I can't tell what the ambiguity is here.

**Comment by alexander-irbis** [comment]
http://play.rust-lang.org/?gist=d540658d847fed9d6bcd5ca5c74828b8&version=nightly&mode=debug

```rust
// #![feature(type_ascription)]

use std::borrow::Cow;

fn get_cow(string: &String) -> Cow<str> {
    // Fails on nightly with "type annotations required: 
    // cannot resolve `std::borrow::Cow<'_, str>: std::convert::From<&_>`"
    // https://github.com/rust-lang/rust/issues/50954
    // This works fine in rust 1.27 and earlier
    Cow::from(string.as_ref())
    
    // In rust nightly-1.28 It is easy to fix as in examples below
    // Cow::from(string.as_ref(): &str)
    // Cow::from(string)
    
    // But I found only these are acceptable in both cases
    // Cow::from(string.as_str())
    // Cow::Borrowed(string.as_ref())
    // Cow::Borrowed(string)
}

fn main() {
    let owned = String::from("Hello, world!");
    let _cow = get_cow(&owned);
}
```

This is a kind of breaking change, that form of `from` cannot co-exist in the old and the new stable rust.
However in my case (rsmorphy) I can painlessly replace it with `Cow::from(string.as_str())`.

**Comment by aturon** [comment]
cc @rust-lang/libs

**Comment by Mark-Simulacrum** [comment]
closing in favor of https://github.com/rust-lang/rust/issues/51844
