### ISSUE TITLE
Error on implementation violating the orphan rules implies all types must be local when one uncovered local type is sufficient.

### ISSUE THREAD

**Issue by cafce25** [rust-lang/rust#128390]
### Code

```Rust
impl From<()> for () {
    fn from(_: ()) {}
}
```

### Current output

```Shell
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
 --> src/lib.rs:1:1
  |
1 | impl From<()> for () {
  | ^^^^^--------^^^^^--
  | |    |            |
  | |    |            this is not defined in the current crate because tuples are always foreign
  | |    this is not defined in the current crate because this is a foreign trait
  | impl doesn't use only types from inside the current crate
  |
  = note: define and implement a trait or new type instead
```

### Desired output

```Shell
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
 --> src/lib.rs:1:1
  |
1 | impl From<()> for () {
  | ^^^^^--------^^^^^--
  | |    |            |
  | |    |            this is not defined in the current crate because tuples are always foreign
  | |    this is not defined in the current crate because this is a foreign trait
  | impl doesn't use any uncovered types from inside the current crate
  |
  = note: define and implement a trait or new type instead
```

### Rust Version

```Shell
Build using the Nightly version: 1.81.0-nightly(2024-07-12 c6727fc9b5c64cefa726) on the playground
```

### Anything else?

The relevant line is here [rustc_hir_analysis/messages.ftl#L354](https://github.com/rust-lang/rust/blob/master/compiler/rustc_hir_analysis/messages.ftl#L354)
