### PR TITLE
Remove *MetricFn

### LINKED ISSUE #44808: `test::TestFn::(Static|Dyn)MetricFn` seems to be unused
https://github.com/rust-lang/rust/blob/master/src/libtest/lib.rs#L152

introduced in https://github.com/rust-lang/rust/commit/f2f7fb3ae1f64517c0b30371e2457cac2e2c1248

### PR DESCRIPTION
**Pull request by bjorn3**
fixes #44808

### CODE REVIEW

**Comment by kennytm** [comment]
CI is failing.

```
[00:04:17] error: unused import: `std::collections::BTreeMap`
[00:04:17]   --> /checkout/src/libtest/lib.rs:60:5
[00:04:17]    |
[00:04:17] 60 | use std::collections::BTreeMap;
[00:04:17]    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^
[00:04:17]    |
[00:04:17] note: lint level defined here
[00:04:17]   --> /checkout/src/libtest/lib.rs:35:9
[00:04:17]    |
[00:04:17] 35 | #![deny(warnings)]
[00:04:17]    |         ^^^^^^^^
[00:04:17]    = note: #[deny(unused_imports)] implied by #[deny(warnings)]
[00:04:17] 
[00:04:17] error[E0609]: no field `metrics` on type `&mut ConsoleTestState<T>`
[00:04:17]    --> /checkout/src/libtest/lib.rs:892:28
[00:04:17]     |
[00:04:17] 892 |                         st.metrics.insert_metric(test.name.as_slice(),
[00:04:17]     |                            ^^^^^^^
[00:04:17] 
[00:04:17] error: aborting due to 2 previous errors
[00:04:17] 
[00:04:17] error: Could not compile `test`.
```

**Comment by kennytm** [comment]
@bors r+ rollup

cc #19145.
