### ISSUE TITLE
Rocket fails to build on latest nightly

### ISSUE THREAD

**Issue by lambda-fairy** [rust-lang/rust#89935]
### Code

I created a project with the following `Cargo.toml`:

```toml
[package]
name = "ducks"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "=0.4.10"
```

[`Cargo.lock`](https://github.com/rust-lang/rust/files/7356901/Cargo.lock.txt)

On the latest nightly, this fails to build with:

```
error[E0277]: the trait bound `(dyn handler::Handler + 'static): handler::Handler` is not satisfied
   --> /Users/wongchris/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.10/src/rocket.rs:299:41
    |
299 |             let outcome = route.handler.handle(request, data);
    |                                         ^^^^^^ the trait `handler::Handler` is not implemented for `(dyn handler::Handler + 'static)`
```

There is no such error with `+nightly-2021-10-14`.

### Version it worked on

`rustc +nightly-2021-10-14 --version --verbose`:
```
rustc 1.57.0-nightly (dfc5add91 2021-10-13)
binary: rustc
commit-hash: dfc5add915e8bf4accbb7cf4de00351a7c6126a1
commit-date: 2021-10-13
host: x86_64-apple-darwin
release: 1.57.0-nightly
LLVM version: 13.0.0
```

### Version with regression

`rustc +nightly-2021-10-16 --version --verbose`:
```
rustc 1.57.0-nightly (c1026539b 2021-10-15)
binary: rustc
commit-hash: c1026539bd22e9d070988deaa47b1360cbc76436
commit-date: 2021-10-15
host: x86_64-apple-darwin
release: 1.57.0-nightly
LLVM version: 13.0.0
```

**Comment by Aaron1011** [comment]
Bisected to https://github.com/rust-lang/rust/pull/86011

**Comment by nbdd0121** [comment]
Minimised:
```rust
trait Foo: Baz {}
trait Bar {}
trait Baz: Bar {
    fn bar(&self);
}

impl<T: Foo> Bar for T {}
impl<T: Foo> Baz for T {
    fn bar(&self) {}
}

fn accept_foo(x: Box<dyn Foo>) {
    x.bar();
}
```

**Comment by JohnTitor** [comment]
> Bisected to #86011

cc @estebank and @tlyu for awareness.

> [..], because in theory, the ordering of trait bounds should be irrelevant to type checking results, right?

Uhm, seems actually not?

**Comment by emirhg** [comment]
> Bisected to #86011

Based on this I downgraded my Rust version and it worked. I'm using Rocket v0.4.9 `rustup default nightly-2021-10-05` did the trick.
