### PR TITLE
improve lifetime annotation diagnostics

### LINKED ISSUE #62185: Self::call constrains lifetime covariance and/or inference unexpectedly under NLL
Spawned off of #60914, namely the [regression][vc regression] of the version-compare crate

[vc regression]: https://crater-reports.s3.amazonaws.com/pr-60914/try%23f45cc3094ee337acd688771b9234318046b0572d/gh/timvisee.version-compare/log.txt

Look at this ([play](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fd8854c0740e05659404819920bd0474)):

```rust
use std::slice::Iter;

pub struct Version<'a> {
    parts: Vec<&'a str>,
}

impl<'a> Version<'a> {
    pub fn compare(&self, other: &Version) {
        Self::compare_iter(self.parts.iter(),  other.parts.iter())
    }
    
    fn compare_iter(_: Iter<&'a str>, _: Iter<&'a str>) { }
}
```

we get an NLL migration error for it.

Why? I'm not sure; at first I thought it made sense, since I assumed that the call to `Self::compare_iter` would force the two arguments to have the same lifetime `'a` that is also attached to the `self` parameter.

But after reflecting on the matter further, I do not understand why we would not have a reborrow here that would allow the call to `compare_iter` to use a shorter lifetime that both inputs can satisfy.
 * (Or, wait: Is `std::slice::Iter<T>` not covariant with respect to `T`? I guess I'll need to check that.)

Anyway, this is either a soundness fix of AST borrow-check (which would be great news), or it is an NLL-complete bug for MIR borrow-check.

I just didn't want it to get lost in the shuffle of a blog post I am currently working on.

### LINKED ISSUE #69224: Confusing errors when using `Self` variants with lifetimes
Minimal example, imagine that we have the following type:

```rust
enum MyCow<'a> {
    Owned(String),
    Borrowed(&'a str),
}
```

If the user returns `Self` variants, this fails:

```
impl<'a> MyCow<'a> {
    fn borrow(&self) -> MyCow<'_> {
        match self {
            Self::Owned(s) => Self::Borrowed(s),
            Self::Borrowed(s) => Self::Borrowed(s),
        }
    }
    fn own(&self) -> MyCow<'_> {
        match self {
            Self::Owned(s) => Self::Owned(s.clone()),
            Self::Borrowed(s) => Self::Owned(s.to_string()),
        }
    }
}
```

But the same code works when you change `Self` to `MyCow`!
```
impl<'a> MyCow<'a> {
    fn borrow(&self) -> MyCow<'_> {
        match self {
            Self::Owned(s) => MyCow::Borrowed(s),
            Self::Borrowed(s) => MyCow::Borrowed(s),
        }
    }
    fn own(&self) -> MyCow<'_> {
        match self {
            Self::Owned(s) => MyCow::Owned(s.clone()),
            Self::Borrowed(s) => MyCow::Owned(s.to_string()),
        }
    }
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=90362d182ee2b37724d73ab7576cdf24))

The real error here is that `Self` really represents `MyCow<'a>` and not just `MyCow`, but the errors don't really relay this. Potentially linked issue: #30904 (has been fixed).

### LINKED ISSUE #100572: Detect cases of lifetime errors caused by closures using a lifetime of its enclosing item and suggest anon lifetime
```rust
fn test<'a>()
where
    'a: 'a, // <- makes sure `'a` is early-bound; late-bound lifetimes are already rejected
{
    let f = |_: &'a str| {};
    f(&String::new());
}
```

compiles on 1.63 but [will stop compiling in 1.64](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=7cf9ce98fd64f1bf3d680c5bc9325534) with the following error because of https://github.com/rust-lang/rust/pull/98835#issuecomment-1177391852 (https://github.com/rust-lang/rust/issues/100544):

```
error[E0716]: temporary value dropped while borrowed
 --> src/lib.rs:6:8
  |
1 | fn test<'a>()
  |         -- lifetime `'a` defined here
...
6 |     f(&String::new());
  |     ---^^^^^^^^^^^^^-- temporary value is freed at the end of this statement
  |     |  |
  |     |  creates a temporary which is freed while still in use
  |     argument requires that borrow lasts for `'a`
```

We should detect cases of lifetime errors caused by closures using a lifetime of its enclosing item and [suggest using an anonymous lifetime when appropriate](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=ee62dde9823aca7a569f545f4260696a) to make the code compile.

### LINKED ISSUE #101393: Suggest `Struct::<'_>` instead of `Self` when lifetime does not match
Heads-up: [PR 100976](https://github.com/rust-lang/rust/pull/100976) probably fixes this but I still felt its own issue was warranted (and didn't find an existing one).

---

[Given the following code:](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0bf33196179908c605f448226b34ea53)

```rust
pub struct Path<'a> {
    string: &'a mut String,
}

impl<'a> Path<'a> {
    pub fn sub(&mut self) -> Path/*<'_>*/ {
        Self {
            string: self.string,
        }
    }
}
```

The current output is:

```
error: lifetime may not live long enough
 --> src/lib.rs:8:21
  |
5 | impl<'a> Path<'a> {
  |      -- lifetime `'a` defined here
6 |     pub fn sub(&mut self) -> Path/*<'_>*/ {
  |                - let's call the lifetime of this reference `'1`
7 |         Self {
8 |             string: self.string,
  |                     ^^^^^^^^^^^ this usage requires that `'1` must outlive `'a`
```
Ideally the output should look like:

```
7 |         Self {
   |         ^^^^ help: Consider replacing `Self` with `Path`
```

Programmers not-infrequently [expect `Self` to act as a type constructor](https://users.rust-lang.org/t/rewrite-generics-parameter-of-self/80347/6) and not fully aliased type (including lifetimes).  Using `Path` in this context infers the lifetime, whereas using `Self` make the lifetime exactly `'a`.

Though I haven't included it in my example, consider also the case when `Self` is used as the return type.

[Another recent URLO example which inspired this report.](https://users.rust-lang.org/t/implement-a-stack-of-path-component-with-a-shared-buffer/80666)

The same error appears on stable, nightly, and beta.  But see [PR 100976](https://github.com/rust-lang/rust/pull/100976) which may resolve this issue.

@rustbot label +A-lifetimes +A-suggestion-diagnostics +D-newcomer-roadblock

### PR DESCRIPTION
**Pull request by aliemjay**
- register the lifetime annotations in closure signature and function calls under the category `ConstraintCategory::TypeAnnotation`.
- when searching for the "best blame constraint", make sure we report type annotation constraints only if there is no other constraint to blame. Now  whenever we get `TypeAnnotation` error, we can be sure that the lifetime annotation is unnecessarily restrictive and we can safely suggest removing it.
- handle the subtle cases of `Self` where it forces unnecessary constraints and suggest a proper fix.

TODO:

- [ ] Use of type aliases may impose additional region constraints even when neither the definition nor the use site has an explicit lifetime annotation:
```rust
type Same<X> = (X, X);
type Inv<'x> = *mut &'x ();
fn test(s1: Inv<'_>, s2: Inv<'_>) {
    let _: Same<_> = (s1, s2);
}
```

cc #100725, not closing it though.
resolves #100572
resolves #101393
resolves #69224
resolves #62185

r? @estebank

### CODE REVIEW

File: compiler/rustc_borrowck/src/diagnostics/region_errors.rs [hunk 1]
```diff
@@ -902,3 +945,40 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, 'tcx> {
...
+/// One subtle case is the use of `Self` which can impose unnecessary region constraints. Here we
+/// suggest replacing `Self` with `MyStruct<'_>`.
+pub(crate) fn suggest_relax_annotation<'tcx>(
+    tcx: TyCtxt<'tcx>,
+    err: &mut Diagnostic,
+    body_did: DefId,
+    span: Span,
+) {
+    use rustc_lexer as lex;
+    fn tokenize(mut input: &str) -> impl Iterator<Item = (lex::TokenKind, &str)> {
```
Comment (compiler-errors) [inline compiler/rustc_borrowck/src/diagnostics/region_errors.rs:961]: This makes me somewhat uncomfortable..

Comment (aliemjay) [reply compiler/rustc_borrowck/src/diagnostics/region_errors.rs:961]: Does it really matter? I mean it's only in the error path.

Comment (compiler-errors) [reply compiler/rustc_borrowck/src/diagnostics/region_errors.rs:961]: Yeah, I think it does. There are lots of ways you can get spans to point at random things that aren't paths, like macro expansions, parser error recovery paths, etc. A lot of the error handling logic we have in borrowck is super fragile, and I think invoking the lexer of all things in borrowck is suspicious. How much effort would it be to pass down something like a hir id? or a rustc_middle Ty?

Comment (aliemjay) [reply compiler/rustc_borrowck/src/diagnostics/region_errors.rs:967]: I don't think passing Ty makes a difference, I'm trying to detect the use of `Self` here.
About the HirId, I'm more worried about the correctness of such approach, the mir/thir would reference hir and that's an abstraction leakage IMO.

Probably a better thing can be done here is to compute `uses_self: bool` field for each type annotation when building thir/mir. Bu this may be out of scope for this PR because I'm targeting a beta-backport. Is it ok to try this in a followup PR? or is there a chance that this gets backported anyway?

**Comment by aliemjay** [comment]
It should be ready now. Maybe best reviewed commit-by-commit. The output needs some bikeshedding though.

File: compiler/rustc_borrowck/src/diagnostics/region_errors.rs [hunk 2]
```diff
@@ -902,3 +945,46 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, 'tcx> {
...
+    let snippet = tcx.sess.source_map().span_to_snippet(span).unwrap_or_default();
+    let has_self = tokenize(&snippet)
+        .find(|(tok, s)| *tok == lex::TokenKind::Ident && *s == "Self")
+        .and_then(|_| tcx.opt_parent(tcx.typeck_root_def_id(body_did)))
+        .filter(|parent_did| tcx.def_kind(parent_did) == DefKind::Impl);
+
+    if let Some(impl_did) = has_self {
+        let suggested_ty =
+            tcx.fold_regions(tcx.type_of(impl_did), |_, _| tcx.mk_region(ty::ReErased));
+        err.help(format!("consider replacing `Self` with `{suggested_ty}`"));
```
Comment (aliemjay) [inline compiler/rustc_borrowck/src/diagnostics/region_errors.rs:988]: Is there a way to format the ty with turbofish? it currently suggests `MyStruct<T>` instead of `MyStruct::<T>`.

Also is better to replace regions with dummy ReVar instead so that it is formatted `MyStruct<'_, T>` instead `MyStruct<T>`? but the maybe too erbose for the common case.

File: src/test/ui/wf/wf-static-method.stderr [hunk 3]
```diff
@@ -20,8 +20,9 @@ LL | impl<'a, 'b> Foo<'a, 'b, ()> for IndirectEvil<'a, 'b> {
    |      lifetime `'a` defined here
 ...
 LL |         let me = Self::make_me();
-   |                  ^^^^^^^^^^^^^ requires that `'b` must outlive `'a`
+   |                  ^^^^^^^^^^^^^ type annotation requires that `'b` must outlive `'a`
```
Comment (jackh726) [inline src/test/ui/wf/wf-static-method.stderr:23]: There is really no type annotation here :)

Comment (aliemjay) [reply src/test/ui/wf/wf-static-method.stderr:23]: My reasoning is that `Self` is considered a type annotation, and the subsequent help note should make it clear.

Comment (aliemjay) [reply src/test/ui/wf/wf-static-method.stderr:23]: I can change it to `use of Self requires ...` but this may produce false positives/negatives in some edge cases because the heuristics this relies on is not 100% reliable. This might not be ok given that this is the primary label of the error, but I'm not sure.

Comment (jackh726) [reply src/test/ui/wf/wf-static-method.stderr:23]: I think calling Self a type annotation is a bit of a stretch. I'd like to see what the diagnostics look like with the change.

File: compiler/rustc_borrowck/src/diagnostics/region_errors.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_borrowck/src/diagnostics/region_errors.rs:988]: I think you need something like

```rust
        let mut printer = ty::print::FmtPrinter::new(self.infcx.tcx, Namespace::ValueNS); // The default is `Namespace::TypeNS
        ty.print(printer).unwrap().into_buffer()
```

File: compiler/rustc_borrowck/src/diagnostics/region_errors.rs [hunk 4]
```diff
@@ -902,3 +945,46 @@ impl<'a, 'tcx> MirBorrowckCtxt<'a, 'tcx> {
...
+            input = &input[(token.len as usize)..];
+            Some((token.kind, token_str))
+        })
+    }
+
+    let snippet = tcx.sess.source_map().span_to_snippet(span).unwrap_or_default();
+    let has_self = tokenize(&snippet)
+        .find(|(tok, s)| *tok == lex::TokenKind::Ident && *s == "Self")
+        .and_then(|_| tcx.opt_parent(tcx.typeck_root_def_id(body_did)))
+        .filter(|parent_did| tcx.def_kind(parent_did) == DefKind::Impl);
```
Comment (estebank) [inline compiler/rustc_borrowck/src/diagnostics/region_errors.rs:983]: I was going to suggest try to get the hir id somehow, but that's not available in borrowck. *But* you can use the `body_did` and the span to find the right expr by creating a new `Visitor`:

https://github.com/rust-lang/rust/pull/101002/files#diff-23edf23f7466b97eb3154b82f7b324983287c327937fd66e854b3df6759926ceR645-R751

**Comment by apiraino** [comment]
@aliemjay is `s-waiting-on-review` still the correct label? Or is there progress on parallel tracks (I notice the linked PRs)? Thanks for an update (feel free to use `rustbot @author` if this is not ready for review)

**Comment by aliemjay** [comment]
rustbot @author

**Comment by JohnCSimon** [comment]
@aliemjay 
ping from triage - can you post your status on this PR? Thanks


FYI: when a PR is ready for review, send a message containing 
`@rustbot ready` to switch to `S-waiting-on-review` so the PR is in the reviewer's backlog.

**Comment by Dylan-DPC** [comment]
Closing this as inactive. Feel free to reöpen this pr or create a new pr if you get the time to work on this. Thanks
