### ISSUE TITLE
`async{}` blocks can no longer be used in functions marked as `#[track_caller]`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#105134]
### Code

The following code compiles and works as expected on `nightly-2022-11-17` and fails on `nightly-2022-11-18`:

```rust
#[track_caller]
pub fn f() {
    _ = async {};
}
```
```text
error[E0658]: `#[track_caller]` on closures is currently unstable
 --> src/lib.rs:3:9
  |
3 |     _ = async {};
  |         ^^^^^^^^
  |
  = note: see issue #87417 <https://github.com/rust-lang/rust/issues/87417> for more information
  = help: add `#![feature(closure_track_caller)]` to the crate attributes to enable
```
[(play)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5c12d6d61a5a15bd4ce3661b81768b61)

### Version it worked on

It most recently worked on: `nightly-2022-11-17`

### Version with regression

`rustc --version --verbose`:
```
rustc 1.67.0-nightly (c97b539e4 2022-11-30)
binary: rustc
commit-hash: c97b539e408ea353f4fde2f9251d598291fec421
commit-date: 2022-11-30
host: x86_64-unknown-linux-gnu
release: 1.67.0-nightly
LLVM version: 15.0.4
```

Similarly to https://github.com/rust-lang/rust/issues/104588, this is caused by https://github.com/rust-lang/rust/pull/104219, but this reproduction doesn't even use `#[track_caller]` on `async fn`!
<sub>btw I've found this b/c users of my crate reported that it doesn't compile anymore, good stuff</sub>

----

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged
cc @bryangarza
