### ISSUE TITLE
[1.30 beta] Regression and bad diagnostics about macros

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54473]
A crate is failing to build on 1.30 beta with a macro resolution error with funny diagnostics:

```
 error[E0433]: failed to resolve. Maybe a missing `extern crate assert_eq;`?
    --> src/lib.rs:123:13
     |
 123 |               assert_eq!(sl, vl, "line {}: value length ({}) is invalid, excepted: {}", LINE, vl, sl);
     |               ^^^^^^^^^ Maybe a missing `extern crate assert_eq;`?
```

* [set_slice](https://crates.io/crates/set_slice) `0.3.0` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/set_slice-0.3.0/log.txt)) cc @KrishnaSannasi

cc @petrochenkov

**Comment by petrochenkov** [comment]
This error is caused by incorrect use of `#[macro_export(local_inner_macros)]` (same situation as in https://github.com/rust-lang/rust/issues/53464, i.e. `local_inner_macros` was added, but not tested.)

**Comment by pnkfelix** [comment]
closing as duplicate of #53464.

(The only potential T-compiler thing is to improve the diagnostics as alluded to here: https://github.com/rust-lang/rust/issues/53464#issuecomment-414049856 )
