### PR TITLE
Add `libLLVM.so` to the target libdir when download-rustc is enabled

### LINKED ISSUE #110225: `run-pass` tests in `tests/ui-fulldeps/` fall when download-rustc is enabled
I tried this code: `./configure  --set profile=compiler --set rust.download-rustc && x test ui-fulldeps`

I expected to see this happen: All tests pass.

Instead, this happened:

```
failures:
    [ui] tests/ui-fulldeps/deriving-encodable-decodable-cell-refcell.rs
    [ui] tests/ui-fulldeps/compiler-calls.rs
    [ui] tests/ui-fulldeps/issue-14021.rs
    [ui] tests/ui-fulldeps/deriving-encodable-decodable-box.rs
    [ui] tests/ui-fulldeps/stable-mir/crate-info.rs
    [ui] tests/ui-fulldeps/mod_dir_path_canonicalized.rs
    [ui] tests/ui-fulldeps/pprust-expr-roundtrip.rs

test result: FAILED. 63 passed; 7 failed; 1 ignored; 0 measured; 0 filtered out; finished in 3.14s
```

The failures all look like this:
```
---- [ui] tests/ui-fulldeps/pprust-expr-roundtrip.rs stdout ----

error: test run failed!
status: exit status: 127
command: cd "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/pprust-expr-roundtrip" && RUST_TEST_THREADS="16" "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/pprust-expr-roundtrip/a"
stdout: none
--- stderr -------------------------------
/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/pprust-expr-roundtrip/a: error while loading shared libraries: libLLVM-16-rust-1.70.0-nightly.so: cannot open shared object file: No such file or directory
------------------------------------------
```

I see the following llvm .so files in the build directory:
```
; fd libLLVM build/host/ci-rustc*
build/host/ci-rustc/lib/libLLVM-16-rust-1.70.0-nightly.so
build/host/ci-rustc-sysroot/lib/libLLVM-16-rust-1.70.0-nightly.so
```
but with the `rustc-dev` component added, it should also be in the `rustlib` target folder:
```
; ls $(rustc --print sysroot)/lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM*
/home/jyn/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libLLVM-16-rust-1.70.0-nightly.so
```

### Meta

HEAD is f2d9a3d0771504f1ae776226a5799dcb4408a91a

### LINKED ISSUE #110226: `build-pass` tests in `tests/ui-fulldeps` fail when cross-compiling and download-rustc is enabled
I tried this code: `./configure --set profile=compiler --set rust.download-rustc=true && x t tests/ui-fulldeps/ --target i686-unknown-linux-gnu --run never` (`--run never` is to avoid #110225).
I expected to see this happen: All tests pass.

Instead, this happened: Some tests fail (the same ones as in #110225):

```
failures:
    [ui] tests/ui-fulldeps/deriving-encodable-decodable-box.rs
    [ui] tests/ui-fulldeps/deriving-encodable-decodable-cell-refcell.rs
    [ui] tests/ui-fulldeps/issue-14021.rs
    [ui] tests/ui-fulldeps/compiler-calls.rs
    [ui] tests/ui-fulldeps/stable-mir/crate-info.rs
    [ui] tests/ui-fulldeps/mod_dir_path_canonicalized.rs
    [ui] tests/ui-fulldeps/pprust-expr-roundtrip.rs

test result: FAILED. 63 passed; 7 failed; 1 ignored; 0 measured; 0 filtered out; finished in 3.86s
```

The failures look like
```
---- [ui] tests/ui-fulldeps/pprust-expr-roundtrip.rs stdout ----

error: test compilation failed although it shouldn't!
status: exit status: 1
command: "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/home/jyn/src/rust2/tests/ui-fulldeps/pprust-expr-roundtrip.rs" "-Zthreads=1" "--target=x86_64-unknown-linux-gnu" "-O" "--error-format" "json" "--json" "future-incompat" "-Ccodegen-units=1" "-Zui-testing" "-Zsimulate-remapped-rust-src-base=/rustc/FAKE_PREFIX" "-Ztranslate-remapped-path-to-local-path=no" "-Zdeduplicate-diagnostics=no" "-Cstrip=debuginfo" "-C" "prefer-dynamic" "--out-dir" "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/pprust-expr-roundtrip" "-Crpath" "-Cdebuginfo=0" "-Lnative=/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/pprust-expr-roundtrip/auxiliary"
stdout: none
--- stderr -------------------------------
error: linking with `cc` failed: exit status: 1
   |
   = note: LC_ALL="C" PATH="/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/jyn/.local/bin:/home/jyn/.local/lib/cargo/bin:/home/jyn/src/dotfiles/bin:/home/jyn/.local/bin:/home/jyn/.local/bin:/home/jyn/.local/lib/cargo/bin:/home/jyn/src/dotfiles/bin:/home/jyn/.local/bin:/home/jyn/.local/bin:/home/jyn/.local/lib/cargo/bin:/home/jyn/src/dotfiles/bin:/home/jyn/.local/bin:/home/jyn/.local/bin:/home/jyn/.local/lib/cargo/bin:/home/jyn/src/dotfiles/bin:/home/jyn/.local/bin:/home/jyn/.local/bin:/home/jyn/.local/lib/cargo/bin:/home/jyn/src/dotfiles/bin:/home/jyn/.local/bin:/home/jyn/.local/bin:/home/jyn/.local/lib/cargo/bin:/home/jyn/src/dotfiles/bin:/home/jyn/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin" VSLANG="1033" "cc" "-m64" "/tmp/rustcdeJQFz/symbols.o" "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/pprust-expr-roundtrip/pprust-expr-roundtrip.pprust_expr_roundtrip.f72f72b5-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-L" "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/pprust-expr-roundtrip/auxiliary" "-L" "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-L" "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-lrustc_driver-678dead588f20b29" "-L" "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-lstd-b5096806ff948049" "-Wl,-Bstatic" "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-35b8a4bd2de4e62e.rlib" "-Wl,-Bdynamic" "-lLLVM-16-rust-1.70.0-nightly" "-ldl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-o" "/home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/test/ui-fulldeps/pprust-expr-roundtrip/pprust-expr-roundtrip" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-debug" "-nodefaultlibs" "-Wl,-rpath,$ORIGIN/../../../stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--enable-new-dtags" "-Wl,-z,origin"
   = note: /usr/bin/ld: /home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-678dead588f20b29.so: undefined reference to `LLVMInitializeLoongArchAsmPrinter@LLVM_16'
           /usr/bin/ld: /home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-678dead588f20b29.so: undefined reference to `LLVMInitializeLoongArchAsmParser@LLVM_16'
           /usr/bin/ld: /home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-678dead588f20b29.so: undefined reference to `LLVMInitializeLoongArchTargetInfo@LLVM_16'
           /usr/bin/ld: /home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-678dead588f20b29.so: undefined reference to `LLVMInitializeLoongArchTarget@LLVM_16'
           /usr/bin/ld: /home/jyn/src/rust2/build/x86_64-unknown-linux-gnu/stage2/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-678dead588f20b29.so: undefined reference to `LLVMInitializeLoongArchTargetMC@LLVM_16'
           collect2: error: ld returned 1 exit status
           
   = note: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
   = note: use the `-l` flag to specify native libraries to link
   = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-libkindname)

error: aborting due to previous error
------------------------------------------
```

I think we need to rebuild LLVM from source when cross-compiling, we can't use the downloaded version.

I'm unsure if this is related specifically to `download-rustc` or whether `download-ci-llvm` affects it too; I had both enabled.

### Meta

HEAD is branched from 9be9b5e09ad834e2ba9f2571ca17059e18f89b71.

### PR DESCRIPTION
**Pull request by jyn514**
Previously, we would only add it to the host libdir, which meant it couldn't be loaded by `ui-fulldeps` tests that used rustc_private.

Fixes https://github.com/rust-lang/rust/issues/110225, fixes https://github.com/rust-lang/rust/issues/110226.

### CODE REVIEW

**Comment by albertlarsan68** [comment]
LGTM
Thanks for the PR!
@bors r+

**Comment by jyn514** [comment]
This fixes a regression from #110121:

```
  = note: /usr/bin/ld: /home/alona/dev/rust/rust/build/x86_64-unknown-linux-gnu/ci-rustc-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_driver-a330ea589693868f.so: undefined reference to `LLVMInitializeLoongArchAsmPrinter@LLVM_16'
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

@bors p=1
