### PR TITLE
Handle rustc_const_stable attribute in library feature collector

### PR DESCRIPTION
**Pull request by dtolnay**
The library feature collector in [compiler/rustc_passes/src/lib_features.rs](https://github.com/rust-lang/rust/blob/551b4fa395fa588d91cbecfb0cdfe1baa02670cf/compiler/rustc_passes/src/lib_features.rs) has only been looking at `#[stable(…)]`, `#[unstable(…)]`, and `#[rustc_const_unstable(…)]` attributes, while ignoring `#[rustc_const_stable(…)]`. The consequences of this were:

- When any const feature got stabilized (changing one or more `rustc_const_unstable` to `rustc_const_stable`), users who had previously enabled that unstable feature using `#![feature(…)]` would get told "unknown feature", rather than rustc's nicer "the feature … has been stable since … and no longer requires an attribute to enable".

    This can be seen in the way that https://github.com/rust-lang/rust/pull/93957#issuecomment-1079794660 failed after rebase:

    ```console
    error[E0635]: unknown feature `const_ptr_offset`
      --> $DIR/offset_from_ub.rs:1:35
       |
    LL | #![feature(const_ptr_offset_from, const_ptr_offset)]
       |                                   ^^^^^^^^^^^^^^^^
    ```

- We weren't enforcing that a particular feature is either stable everywhere or unstable everywhere, and that a feature that has been stabilized has the same stabilization version everywhere, both of which we enforce for the other stability attributes.

This PR updates the library feature collector to handle `rustc_const_stable`, and fixes places in the standard library and test suite where `rustc_const_stable` was being used in a way that does not meet the rules for a stability attribute.

### CODE REVIEW

**Comment by oli-obk** [comment]
cc @jhpratt you've been working on related changes

**Comment by m-ou-se** [comment]
r? rust-lang/compiler

**Comment by jhpratt** [comment]
While I'm not on the list of reviewers, I'll still take a look later today.

File: src/test/ui/consts/const-eval/simd/insert_extract.rs [hunk 1]
```diff
@@ -2,7 +2,7 @@
 #![feature(repr_simd)]
 #![feature(platform_intrinsics)]
 #![feature(staged_api)]
-#![stable(feature = "foo", since = "1.33.7")]
+#![stable(feature = "foo", since = "1.3.37")]
```
Comment (jhpratt) [inline src/test/ui/consts/const-eval/simd/insert_extract.rs:5]: Any particular reason for this change?

File: library/core/src/mem/maybe_uninit.rs [hunk 2]
```diff
@@ -905,7 +905,7 @@ impl<T> MaybeUninit<T> {
     /// };
     /// ```
     #[stable(feature = "maybe_uninit_ref", since = "1.55.0")]
-    #[rustc_const_unstable(feature = "const_maybe_uninit_assume_init", issue = "none")]
+    #[rustc_const_unstable(feature = "const_maybe_uninit_assume_init_mut", issue = "none")]
```
Comment (jhpratt) [inline library/core/src/mem/maybe_uninit.rs:908]: The two changes in this file are the only ones where an unstable feature gate is being changed. Is there a reason this is the case, as opposed to changing the gate for the already-stabilized part of this feature?

**Review by jhpratt — CHANGES_REQUESTED** [review]
Change the the compiler looks good as-is. There's two places where I do have questions, though.

File: src/test/ui/consts/const-eval/simd/insert_extract.rs (hunk 1 above)
Comment (dtolnay) [reply src/test/ui/consts/const-eval/simd/insert_extract.rs:5]:
```console
error[E0711]: feature `foo` is declared stable since 1.3.37, but was previously declared stable since 1.33.7
  --> /git/rust/src/test/ui/consts/const-eval/simd/insert_extract.rs:15:5
   |
LL |     #[rustc_const_stable(feature = "foo", since = "1.3.37")]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0711]: feature `foo` is declared stable since 1.3.37, but was previously declared stable since 1.33.7
  --> /git/rust/src/test/ui/consts/const-eval/simd/insert_extract.rs:17:5
   |
LL |     #[rustc_const_stable(feature = "foo", since = "1.3.37")]
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors
```

File: library/core/src/mem/maybe_uninit.rs (hunk 2 above)
Comment (dtolnay) [reply library/core/src/mem/maybe_uninit.rs:908]: No reason. I didn't put a lot of thought into the required name changes but I would be happy to consider suggestions.

Comment (jhpratt) [reply library/core/src/mem/maybe_uninit.rs:908]: I think it would make more sense to change the gate that's already stabilized, as that would avoid unnecessary breakage on Rust's end.

Comment (dtolnay) [reply library/core/src/mem/maybe_uninit.rs]: Fixed in 9479358dda11c677064b89d676a8b67d0181be3b

**Comment by dtolnay** [comment]
- Rebased to fix feature naming problems introduced by #95241

**Review by jhpratt — APPROVED** [review]

File: src/test/ui/consts/const-eval/simd/insert_extract.rs (hunk 1 above)
Comment (jhpratt) [reply src/test/ui/consts/const-eval/simd/insert_extract.rs:5]: Ah, didn't look at the full context.

**Comment by lcnr** [comment]
thanks @jhpratt for your review

@bors r+ rollup
