### ISSUE TITLE
Borrow checker on beta rejects code accepted on stable.

### ISSUE THREAD

**Issue by khuey** [rust-lang/rust#60927]
See the repo at https://github.com/khuey/rust-nightly-borrow-checker-failure

This repository builds on 1.34.2. It fails on 1.35.0-beta.8 with

```
error[E0597]: `global_lock` does not live long enough
  --> src/lib.rs:24:26
   |
24 |             let locked = global_lock.as_ref().lock().unwrap();
   |                          ^^^^^^^^^^^ borrowed value does not live long enough
25 |             ptr::write(&mut self.global_lock, Some(locked));
   |                        --------------------- cast requires that `global_lock` is borrowed for `'static`
26 |         }
27 |     }
   |     - `global_lock` dropped here while still borrowed

error: aborting due to previous error
```

**Comment by Manishearth** [comment]
cc @nikomatsakis

**Comment by Manishearth** [comment]
We're cutting off a new stable next week, we should prioritize investigating and fixing this.

**Comment by Centril** [comment]
Self contained initial reduction:
```rust
use std::sync::{Mutex, MutexGuard};
use std::ptr;

struct _Foo {
    _alpha: Mutex<()>,
    _beta: Option<MutexGuard<'static, ()>>,
}

impl _Foo {
    fn _bar(self: &mut Self) {
        assert!(self._beta.is_none());

        let beta = ptr::NonNull::from(&self._alpha);

        unsafe {
            let locked = beta.as_ref().lock().unwrap();
            ptr::write(&mut self._beta, Some(locked));
        }
    }
}
```

**Comment by matthewjasper** [comment]
Probably #58673, which fixed pointer casts being able to launder lifetimes with NLL.

**Comment by Manishearth** [comment]
@matthewjasper any idea on how we'd be able to fix this in time for the release? Either by backporting or by fixing the actual bug?

**Comment by matthewjasper** [comment]
The example provided should be using `let locked = (*global_lock.as_ptr()).lock().unwrap();`.

**Comment by khuey** [comment]
Yeah that works.

**Comment by pnkfelix** [comment]
Hmm. Was I wrong about PR #58673 only affecting code opting in via `#![feature(nll)]`? I had thought when I reviewed that PR that it did not affect NLL migrate mode, and therefore could not be breaking stable/beta ...

**Comment by pietroalbini** [comment]
Me and @pnkfelix discussed this on Discord. The beta to stable promotion is happening today so there is no time for the compiler team to decide what's the best fix for this issue, and we don't want to rush things.

I'm going to **back out** PR #58673 from the 1.35.0 release, but it will still be present on beta 1.36.0 and nightly, giving the teams more breathing room to reach a decision.

**Comment by pietroalbini** [comment]
An update: backing out the change doesn't seem to be trivial so I'm going to do the initial stable PR without it (aka with the regression).

When I tried doing the revert I got a bunch of ICEs both in the test suite and while compiling stage1 rustc, so the backout seems risky enough not to do it right before 1.35.0 goes out.

cc @rust-lang/release

**Comment by Manishearth** [comment]
Can we mention this in the release blog post so people are warned?

**Comment by Centril** [comment]
Assigning myself as a reminder re. blog post (but not for anything else).

**Comment by pnkfelix** [comment]
triage: I don't think we're going to try to "fix" the regression here. From the investigation documented above, it seems like acceptable fallout from a soundness fix; a warning-cycle would have been nice, but its not a necessity, and its not going to block the release.

Removing I-nominated tag, and not going to add a priority label. Leaving assigned to @Centril regarding messaging.

**Comment by Centril** [comment]
Decided not to include in blogpost or relnotes. Closing therefore.
