### ISSUE TITLE
regression: overflow evaluating the requirement `&_ well-formed`

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#123278]
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/DeMille.paint/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/reg/paint-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/Siroj42.heinzelmann/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/reg/steel-doc-0.5.0/log.txt

```
[INFO] [stdout] error[E0275]: overflow evaluating the requirement `&_ well-formed`
[INFO] [stdout]    --> src/main.rs:155:23
[INFO] [stdout]     |
[INFO] [stdout] 155 |             let end = ns.get(1).unwrap_or(&start);
[INFO] [stdout]     |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

And probably the same for https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/reg/zvariant-3.15.0/log.txt:

```
[INFO] [stdout] error[E0275]: overflow evaluating the requirement `NonNull<Vec<u8>>: Unpin`
[INFO] [stdout]   |
[INFO] [stdout]   = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`zvariant`)
[INFO] [stdout] note: required because it appears within the type `Unique<Vec<u8>>`
[INFO] [stdout]  --> /rustc/c1195518c8ad7f37d15ecb82f39dec3da97f9c2f/library/core/src/ptr/unique.rs:36:12
[INFO] [stdout] note: required because it appears within the type `alloc::raw_vec::RawVec<Vec<u8>>`
[INFO] [stdout]  --> /rustc/c1195518c8ad7f37d15ecb82f39dec3da97f9c2f/library/alloc/src/raw_vec.rs:69:19
[INFO] [stdout] note: required because it appears within the type `Vec<Vec<u8>>`
[INFO] [stdout]  --> /rustc/c1195518c8ad7f37d15ecb82f39dec3da97f9c2f/library/alloc/src/vec/mod.rs:398:12
[INFO] [stdout] note: required because it appears within the type `PhantomData<Vec<Vec<u8>>>`
[INFO] [stdout]  --> /rustc/c1195518c8ad7f37d15ecb82f39dec3da97f9c2f/library/core/src/marker.rs:740:12
[...]
```

**Comment by compiler-errors** [comment]
searched nightlies: from nightly-2024-01-01 to nightly-2024-03-18
regressed nightly: nightly-2024-02-23
searched commit range: https://github.com/rust-lang/rust/compare/3406ada96f8e16e49e947a91db3eba0db45245fa...397937d812852f9bbeb671005cb399dbcb357cde
regressed commit: https://github.com/rust-lang/rust/commit/397937d812852f9bbeb671005cb399dbcb357cde

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.8</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2024-01-01 --end=2024-03-18 
```
</details>

Regressed in #119989 - cc @lcnr

**Comment by PatchMixolydic** [comment]
`paint` regression was previously noted in https://github.com/rust-lang/rust/pull/119989#issuecomment-1903652023 and considered acceptable breakage as part of [that PR's FCP](https://github.com/rust-lang/rust/pull/119989#issuecomment-1912103911).

**Comment by compiler-errors** [comment]
Cool, thanks for checking!

**Comment by compiler-errors** [comment]
Looks like steel-doc is also a case of the lasso regression in that PR.

**Comment by compiler-errors** [comment]
Regarding the `zvariant` regression, I seem to be able to make `cargo test` fail with:

```
error[E0275]: overflow evaluating the requirement `NonNull<Vec<u8>>: Unpin`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`zvariant`)
note: required because it appears within the type `Unique<Vec<u8>>
```

since 2024-01-01?

**Comment by VorpalBlade** [comment]
So I'm not sure how this will be handled.

* Lasso breaks with this change. A PR was made to fix this.
* The last activity on github from the author of lasso is from November 2023.
* According to lib.rs the crate has 40k downloads per month and is a dependency of 63 crates (15 directly).

That is a fairly large break that doesn't appear like it will get fixed. (I'm fortunate in that I don't use the serialization feature that appears to be problematic, and I will start looking for a maintained alternative thread safe string interning library, with similar or better performance.)

But this does raise the question of how to handle regressions of more or less popular crates where the crate is (apparently) unmaintained.

**Comment by lcnr** [comment]
Given that this breakage was expected and accepted as part of our stability policy, being both an inference change and a cleanup of underspecified language semantics, I don't think this is much more we should do here.

Closing but going to cc the rest of @rust-lang/types for their thoughts and input here. We cannot land this as a future compat lint first, so the only other alternative is to not land it at all.

**Comment by apiraino** [comment]
More context on the rationale of #119989 at [this comment](https://github.com/rust-lang/rust/pull/119989#issuecomment-1912103911). @lcnr also fixed the breaking changes downstream ([comment](https://github.com/rust-lang/rust/pull/119989#issuecomment-1946902067)). Another crate (`nalgebra`) fixed that themself ([comment](https://github.com/rust-lang/rust/pull/119989#issuecomment-2015694084)).

Does this change should be mentioned in the release notes?

**Comment by lcnr** [comment]
yeah, it's a small change to our type inference with the intent to cleanup the type system and to simplify future development.
