### PR TITLE
WIP: Remove `ResumeTy` from async lowering

### PR DESCRIPTION
**Pull request by Swatinem**
Instead of using the stdlib supported `ResumeTy`, which is being converting to a `&mut Context<'_>` during the Generator MIR pass, this will use `&mut Context<'_>` directly in HIR lowering.

It pretty much reverts #105977 and re-applies an updated version of #105250.

This still fails the testcase added in #106264 however, for reasons I don’t understand.

Is blocked on:
- [ ] #110338
  (https://github.com/rust-lang/rust/issues/102211)

### CODE REVIEW

**Comment by compiler-errors** [comment]
I'm gonna mark this as blocked for now

@rustbot blocked

**Comment by Swatinem** [comment]
Now that https://github.com/rust-lang/rust/pull/107421 has landed, I rebased this, but it is still failing on the testcase in https://github.com/rust-lang/rust/pull/106264 :-(

**Comment by Swatinem** [comment]
I rebased this again after all the changes to coroutines and gen blocks.

The failing test in `tests/ui/async-await/issue-105501.rs` yields a wildly different`error[E0308]: mismatched types` now.
Running this with `-Znext-solver` outputs a much more readable ``error[E0277]: `{async block@…}` cannot be sent between threads safely``.
Though it would obviously be better if it did not error at all :-)
