### ISSUE TITLE
mipsel-unknown-linux-uc libc encounters compilation errors in nightly-2022-08-11

### ISSUE THREAD

**Issue by carlos-yuan** [rust-lang/rust#145035]
I have been using nightly-2022-08-11-x86_64-unknown-linux-gnu, but after upgrading from 1.80.0 to 1.88.0, I encountered compilation errors. Furthermore, the mipsel-unknown-linux-uc libc toolchain that was previously listed in rustup target list is no longer available. Is there any way to resolve this issue? My current system environment is ubuntu2204 in WSL.
/usr/bin/ld: /mnt/d/carlos/wh_gateway/target/mipsel-unknown-linux-uclibc/debug/deps/external_guard-43a2fc9a41711d0a.12pfq9m2mfo8662m.rcgu.o: relocations in generic ELF (EM: 8)
          /usr/bin/ld: /mnt/d/carlos/wh_gateway/target/mipsel-unknown-linux-uclibc/debug/deps/external_guard-43a2fc9a41711d0a.12pfq9m2mfo8662m.rcgu.o: error adding symbols: file in wrong format
          collect2: error: ld returned 1 exit status
