### PR TITLE
Resolve inconsistency in error messages between "parameter" and "variable".

### PR DESCRIPTION
**Pull request by eddyb**
The inconsistency was introduced in 104fe1c4db24f860b890dfd25577f23ee111279a (#33619), when a label saying `type variable` was added to an error with a message talking about `type parameters`.
Given that `parameter` is far more prevalent when referring to generics in the context of Rust, IMO it should be that in both the message and the label.

r? @nikomatsakis or @estebank

### CODE REVIEW

File: src/test/ui/resolve/resolve-type-param-in-item-in-trait.stderr [hunk 1]
```diff
@@ -23,7 +23,7 @@ error[E0401]: can't use generic parameters from outer function
   --> $DIR/resolve-type-param-in-item-in-trait.rs:23:28
    |
 LL | trait TraitC<A> {
-   |              - type variable from outer function
+   |              - type parameter from outer function
```
Comment (Centril) [inline src/test/ui/resolve/resolve-type-param-in-item-in-trait.stderr]: The diagnostic makes no sense here as there's no outer function, just an outer trait.

**Comment by Centril** [comment]
Niko is too busy with other things... ;)

r? @estebank

File: src/test/ui/resolve/resolve-type-param-in-item-in-trait.stderr (hunk 1 above)
Comment (estebank) [reply src/test/ui/resolve/resolve-type-param-in-item-in-trait.stderr]: I believe there's already a ticket for this case.

Comment (Centril) [reply src/test/ui/resolve/resolve-type-param-in-item-in-trait.stderr]: @estebank can you cc it perhaps?

Comment (estebank) [reply src/test/ui/resolve/resolve-type-param-in-item-in-trait.stderr]: CC #37892, #56794, #53241

Comment (Centril) [reply src/test/ui/resolve/resolve-type-param-in-item-in-trait.stderr]: Thanks; I skimmed those issues and they all seem a bit different. I think the fix for this one is to customize the diagnostic based on what the parent def_id refers to... e.g. say "function" if it is one, and "trait" if it is one...
