### PR TITLE
don't leak internal temporaries from `dbg!`, even on false unwind paths

### LINKED ISSUE #155902: 1.96 beta regression: "lua does not live long enough", take 2
Turns out that the #154988 regression wasn't completely fixed by the #154994 PR. (That regression was in turn caused by #154074, which fixes the #153850 regression).

Regression found by the 1.96 beta crater run.

```
[INFO] [stdout] error[E0597]: `lua` does not live long enough
[INFO] [stdout]   --> src/transpile/lua.rs:51:30
[INFO] [stdout]    |
[INFO] [stdout] 18 |         #[tracing::instrument(level = "debug", name = "eval_lua", skip_all, ret)]
[INFO] [stdout]    |                                                                                 -
[INFO] [stdout]    |                                                                                 |
[INFO] [stdout]    |                                                                                 `lua` dropped here while still borrowed
[INFO] [stdout]    |                                                                                 ... and the borrow might be used here, when that temporary is dropped and runs the destructor for type `(LuaValue<'_>,)`
[INFO] [stdout] ...
[INFO] [stdout] 25 |             let lua = Lua::new();
[INFO] [stdout]    |                 --- binding `lua` declared here
[INFO] [stdout] ...
[INFO] [stdout] 51 |             let lua_result = lua
[INFO] [stdout]    |                              ^^^ borrowed value does not live long enough
[INFO] [stdout] ...
[INFO] [stdout] 62 |             self.handle_lua_result(dbg!(lua_result)).map_err(|err| {
[INFO] [stdout]    |                                    ---------------- a temporary with access to the borrow is created here ...
[INFO] [stdout]    |
[INFO] [stdout]    = note: the temporary is part of an expression at the end of a block;
[INFO] [stdout]            consider forcing this temporary to be dropped sooner, before the block's local variables are dropped
[INFO] [stdout] help: for example, you could save the expression's value in a new local variable `x` and then make `x` be the expression at the end of the block
[INFO] [stdout]    |
[INFO] [stdout] 62 ~             let x = self.handle_lua_result(dbg!(lua_result)).map_err(|err| {
[INFO] [stdout] 63 |                 handler.receive(err.clone());
[INFO] [stdout] 64 |                 err
[INFO] [stdout] 65 ~             }); x
[INFO] [stdout]    |
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] For more information about this error, try `rustc --explain E0597`.
```
* https://crater-reports.s3.amazonaws.com/beta-1.96-2/beta-2026-04-21/reg/shulkerscript-0.1.0/log.txt

cc @dianne

### PR DESCRIPTION
**Pull request by dianne**
*[View all comments](https://triagebot.infra.rust-lang.org/gh-comments/rust-lang/rust/pull/155915)*

Hopefully fixes rust-lang/rust#155902 for real this time! See https://github.com/rust-lang/rust/issues/155902#issuecomment-4332648618 and the following comments for why I think `match`ing on a tuple of `dbg!`'s arguments seems not to be a viable implementation strategy. Instead, this uses `super let` to get better control over scoping, which unfortunately makes for pretty awkward code with the current version of `super let`.

One alternative to this would be reverting all the recent changes to `dbg!` for now and re-landing them once `super let`'s replacement is usable. That will probably be the go-to answer for these tricky scoping problems.

Another alternative would be to change Rust's static semantics to (hopefully) make the `match`-based `dbg!` not a problem.

I also noticed `std::macros::dbg_internal!` seems to be stable in beta [(playground)](https://play.rust-lang.org/?version=beta&mode=debug&edition=2024&gist=081dde8000ab0c187cd0200a213f1b36), so I've taken the liberty of de-stabilizing it. I can pull that out into a separate PR later if that'd be better, but I figure if we revert the recent changes to `dbg!`, we'd also be reverting the addition of `dbg_internal!`, so for now that's here.

This may also need clippy and compiler review, but let's start with r? libs

### CODE REVIEW

File: library/std/src/lib.rs [hunk 1]
```diff
@@ -303,6 +303,7 @@
 #![feature(staged_api)]
 #![feature(stmt_expr_attributes)]
 #![feature(strict_provenance_lints)]
+#![feature(super_let)]
```
Comment (dianne) [inline library/std/src/lib.rs]: This is for the unit test. Maybe it should be an integration test or a ui test instead so this isn't needed. Not sure what the norm is there.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/155915/4ddb0b7f8ecda9dbdbcbc0519c9988badbd65d1c..d0ae98f82d1b40a989313df2731bffdf5b7ec007)*

Comment (Amanieu) [reply library/std/src/lib.rs]: You can put the feature flag under `cfg_attr(test, feature(XXX))`.

Comment (dianne) [reply library/std/src/lib.rs]: Ah, thanks! I'd missed that.

**Comment by apiraino** [comment]
t-compiler will defer backport decision to t-libs since this is almost entirely in their purview

**Comment by cuviper** [comment]
Maybe it's worth a crater run compared to stable?

**Comment by dianne** [comment]
I guess for a crater run against stable, we'd need a branch with the commits from this, #154994, #154074, and #149869 cherry-picked? I'll try setting that up as a draft PR against stable.

**Comment by cuviper** [comment]
I just meant stable vs. this nightly -- which will include other changes, but that's true if we beta-backport too. I think we can just do this:

@craterbot check start=1.95.0

**Comment by cuviper** [comment]
@craterbot check start=1.95.0 end=try#012cd62c9add58ab3910e44c137d87db3ab70f61

**Comment by cuviper** [comment]
Bumping priority since this is release-relevant for 1.96-beta.

@craterbot name=pr-155915 p=1

**Comment by dianne** [comment]
that's a whole lotta errors from unstable features being removed or changed. in particular, lots from old versions of proc-macro2 using `proc_macro_span_shrink` when compiled with a nightly toolchain and old versions of ahash using `stdsimd`. of course, since we're comparing against stable, anything that only breaks when using nightly is going to show up as a "regression"

looks like no E0597 (value dropped while borrowed) at least? and searching for `dbg!` didn't turn up anything actually related to `dbg!`, as far as I could tell. the mentions of `dbg!` in regressed crates' build logs were all in warnings; the regressions were in deps (specifically proc-macro2 or ahash).

**Comment by theemathas** [comment]
I'm not in the libs team, but I personally think the simplest way to resolve this is:

1. Revert all the `dbg!()` changes (maybe except for tests).
2. Backport that revert to beta.
3. Open a new PR with this PR's contents (using `super let`) (against the `main` branch, not `beta`.)
4. Run a normal crater with that new PR.
5. If there are no issues, merge that PR, and have it ride the release train normally, starting from nightly.

**Comment by workingjubilee** [comment]
That honestly seems like the most reasonable approach. We can't keep throwing good money (or effort, I suppose) after bad like this. "Starting over" would let us at least scavenge some value from the work without a threat that regressions, which we probably don't actually understand the full scope of yet, hit stable any time soon.

**Comment by nia-e** [comment]
We discussed this in the libs meeting; we agree with @theemathas' suggestion of reverting everything (incl. on nightly) and re-landing the dbg changes

**Comment by cuviper** [comment]
See #156589 for a full revert.

**Comment by Mark-Simulacrum** [comment]
Coming back to this... I think this is not in its current state needed, because we fully removed the dbg! no tearing implementation, right? Should we close it and then it (or an alternative) can be incorporated into a future PR changing dbg! again, if we go ahead with that?

**Comment by dianne** [comment]
yeah. I've opened a clean PR for this approach to avoiding tearing in `dbg!` in case we still want to go ahead with it: #157576. closing this in favor of that.
