### ISSUE TITLE
On Debian using llvm 3.9 upstream packages fails to link

### ISSUE THREAD

**Issue by sylvestre** [rust-lang/rust#37303]
```
info: now are following matches for librustc_driver-*.so libraries:
x86_64-unknown-linux-gnu/stage1/lib/librustc_driver-40393716.so
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/rustc.0.o" "-o" "x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/rustc" "-Wl,--gc-sections" "-pie" "-Wl,-O1" "-nodefaultlibs" "-L" "/usr/lib/llvm-3.9/lib" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_driver-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "syntax_ext-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_typeck-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_trans-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_save_analysis-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_resolve-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_privacy-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_plugin-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_metadata-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_passes-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_borrowck-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_mir-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_platform_intrinsics-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_lint-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_const_eval-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_incremental-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_const_math-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_data_structures-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_back-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_llvm-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rbml-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "graphviz-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "getopts-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "fmt_macros-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "flate-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "arena-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "syntax-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "rustc_errors-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "syntax_pos-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "term-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "serialize-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "log-40393716" "-L" "/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "std-40393716" "-l" "LLVM-3.8" "-l" "stdc++" "-l" "dl" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util" "-Wl,-rpath,$ORIGIN/../lib" "-Wl,-rpath,/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--enable-new-dtags" "-Wl,-z,relro" "-l" "compiler-rt"
  = note: /build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::object::Archive::child_begin(llvm::Error&, bool) const'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `vtable for llvm::ErrorList'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::DIBuilder::createCompileUnit(unsigned int, llvm::StringRef, llvm::StringRef, llvm::StringRef, bool, llvm::StringRef, unsigned int, llvm::StringRef, llvm::DICompileUnit::DebugEmissionKind, unsigned long)'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::Type::print(llvm::raw_ostream&, bool, bool) const'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::DIBuilder::createSubroutineType(llvm::DITypeRefArray, unsigned int, unsigned int)'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::NewArchiveMember::getOldMember(llvm::object::Archive::Child const&, bool)'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::NewArchiveMember::getFile(llvm::StringRef, bool)'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::ErrorInfoBase::ID'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::cl::ParseCommandLineOptions(int, char const* const*, char const*, bool)'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::errorCodeToError(std::error_code)'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::createInternalizePass(std::function<bool (llvm::GlobalValue const&)>)'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::writeArchive(llvm::StringRef, std::vector<llvm::NewArchiveMember, std::allocator<llvm::NewArchiveMember> >&, bool, llvm::object::Archive::Kind, bool, bool, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer> >)'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::ErrorList::ID'
/build/rustc-1.12.0+dfsg1/x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_llvm-40393716.so: undefined reference to `llvm::Module::setPIELevel(llvm::PIELevel::Level)'
collect2: error: ld returned 1 exit status


error: aborting due to previous error

/build/rustc-1.12.0+dfsg1/mk/target.mk:220: recipe for target 'x86_64-unknown-linux-gnu/stage0/lib/rustlib/x86_64-unknown-linux-gnu/bin/rustc' failed
```

Working with LLVM 3.8 but fails with 3.9

**Comment by alexcrichton** [comment]
Hm this sort of error makes me wonder if this was perhaps compiled against LLVM 3.8 but then linked with 3.9 by accident? These sorts of linker errors should crop up as C++ compile failures rather than link failures...

**Comment by sylvestre** [comment]
This is built in a chroot in which only LLVM 3.9 is available.
However, I see -l" "LLVM-3.8 in the command line. maybe it is a problem with llvm-config in 3.9.

**Comment by sylvestre** [comment]
Sorry, this was a problem between the chair and the keyboard: a patch wasn't correctly updated :(
