### PR TITLE
`#[naked]`: report incompatible attributes

### PR DESCRIPTION
**Pull request by folkertdev**
tracking issue: https://github.com/rust-lang/rust/issues/90957

this is a re-implementation of https://github.com/rust-lang/rust/pull/93809 by @bstrie which was closed 2 years ago due to inactivity.

This PR takes some of the final comments into account, specifically providing a little more context in error messages, and using an allow list to determine which attributes are compatible with `#[naked]`.

Notable attributes that are incompatible with `#[naked]` are:

  * `#[inline]`
  * `#[track_caller]`
  * ~~`#[target_feature]`~~ (this is now allowed, see PR discussion)
  * `#[test]`, `#[ignore]`, `#[should_panic]`

These attributes just directly conflict with what `#[naked]` should do. 

Naked functions are still important for systems programming, embedded, and operating systems, so I'd like to move them forward.

### CODE REVIEW

File: compiler/rustc_passes/src/check_attr.rs [hunk 1]
```diff
@@ -410,12 +410,67 @@ impl<'tcx> CheckAttrVisitor<'tcx> {
...
+        span: Span,
+        target: Target,
+        attrs: &[Attribute],
+    ) -> bool {
+        // many attributes don't make sense in combination with #[naked].
+        // Notable attributes that are incompatible with `#[naked]` are:
+        //
+        // * `#[inline]`
+        // * `#[track_caller]`
+        // * `#[target_feature]`
```
Comment (bjorn3) [inline compiler/rustc_passes/src/check_attr.rs:426]: `#[target_feature]` affects the set of instructions allowed inside inline assembly as well as the exact encoding of certain instructions.

Comment (folkertdev) [reply compiler/rustc_passes/src/check_attr.rs:426]: yes, I'm going off of https://github.com/rust-lang/rust/issues/90957#issuecomment-1029483354 where @joshtriplett suggests to exclude `#[target_feature]` initially.

that was 2 years ago though so maybe that should be re-evaluated. Do you have concerns with allowing `#[target_feature]` now?

Comment (Nilstrieb) [reply compiler/rustc_passes/src/check_attr.rs:426]: I don't know what a reason for forbidding it would be, and why @joshtriplett thought it would be hard to get right

Comment (folkertdev) [reply compiler/rustc_passes/src/check_attr.rs:426]: well a reason to be cautious is that I think to most (me included) it's not 100% clear what `#[target_feature]` could do. Are we absolutely sure that on no platform, present or future, a target feature would insert additional instructions that violate the assumptions of `#[naked]`?

Comment (joshtriplett) [reply compiler/rustc_passes/src/check_attr.rs:426]: What I said at the time was that it might take some care to get right. If we take that care, and commit to avoiding any potential issues that might arise (e.g. locking down what a given `target_feature` means for a naked function and never inserting any instructions for it), then supporting the combination seems fine.

Comment (folkertdev) [reply compiler/rustc_passes/src/check_attr.rs]: With the implementation strategy in https://github.com/rust-lang/rust/pull/128004 I don't think there is any risk of `#[target_feature]` inserting instructions. The user's inline assembly block is hoisted to a top-level global asm block, and the function itself becomes effectively an `extern fn`.

So I've now added `target_feature` to the allow list in a separate commit that can be reverted if there are any concerns.

File: tests/ui/rfcs/rfc-2091-track-caller/error-with-naked.stderr [hunk 2]
```diff
@@ -1,14 +1,20 @@
...
+LL | #[naked]
+   | -------- function marked with `#[naked]` here
 
-error[E0736]: cannot use `#[track_caller]` with `#[naked]`
+error[E0736]: attribute incompatible with `#[naked]`
   --> $DIR/error-with-naked.rs:18:5
    |
 LL |     #[track_caller]
-   |     ^^^^^^^^^^^^^^^
+   |     ^^^^^^^^^^^^^^^ this attribute is incompatible with `#[naked]`
```
Comment (bjorn3) [inline tests/ui/rfcs/rfc-2091-track-caller/error-with-naked.stderr:14]: When macros are involved, relying just on the shown source snippet may sometimes not be enough to figure out which attribute is incompatible. Maybe keep the name of the attribute in either the error message or the label for the primary span?

Comment (folkertdev) [reply tests/ui/rfcs/rfc-2091-track-caller/error-with-naked.stderr]: good call, the message is now "the `track_caller` attribute is incompatible with `#[naked]`"

**Comment by tgross35** [comment]
@bors r-

It looks like the changes here are breaking the compiler_builtins build https://github.com/rust-lang/rust/pull/128248#issuecomment-2253615219. It seems like link-related attributes (`linkage` here) shouldn't be incompatible?

**Comment by folkertdev** [comment]
right, that's a (perma-unstable, apparently) unstable attribute and only `external` linkage makes sense, but it makes sense to add to the allowlist I think.

**Comment by folkertdev** [comment]
@rustbot ready

though are there other unstable attributes that may be missing from that list? is there a comprehensive list of such attributes?

**Comment by tgross35** [comment]
I don't know of any list specific for attributes unfortunately, just the huge list in `compiler/rustc_span/src/symbol.rs`. `link_ordinal` seems to make sense too, maybe worth double checking the other `link_*` symbols to see if they are applicable.

Does this correctly flag on `#[cfg_attr(foo, invalid_attribute)]` when `foo` is true? Could probably use a test if so. (Also probably a squash).

**Comment by folkertdev** [comment]
this list is based on `compiler/rustc_codegen_ssa/src/codegen_attrs.rs`. It doesn't cover everything (e.g. doc, test) but I think this should be pretty complete. 

already accepted

- `sym::cold`
- `sym::naked`
- `sym::no_mangle`
- `sym::export_name`
- `sym::linkage`
- `sym::target_feature`
- `sym::link_section`

already disallowed

- `sym::track_caller`

does not make sense on a function

- `sym::thread_local` // only for statics
- `sym::used` // only for statics
- `sym::link_name` // only on extern functions (defined externally)
- `sym::link_ordinal` // only on extern functions (defined externally)

does not seem relevant 

- `sym::rustc_nounwind`
- `sym::rustc_reallocator`
- `sym::rustc_deallocator`
- `sym::rustc_allocator_zeroed`
- `sym::rustc_std_internal_symbol`
- `sym::rustc_allocator`

unclear. Whether these make sense really depends on the outcome of https://github.com/rust-lang/rust/pull/128004

- `sym::repr` 
- `sym::patchable_function_entry`
- `sym::no_sanitize`

probably not needed

- [`sym::ffi_pure`](https://github.com/rust-lang/rust/issues/58329) not sure this makes sense, we have asm `options` already
- [`sym::ffi_const`](https://github.com/rust-lang/rust/issues/58328) like above
- `sym::cmse_nonsecure_entry` will disappear soon (replaced by a custom ABI)
- `sym::instruction_set` switches between arm and thumb instructions. does not seem relevant when the user controls the assembly anyway

---

So I think for now the allow list is correct and complete. There are a couple of unstable (but very stalled) attributes that may still be relevant once a different codegen technique is used for naked functions, but that will have to be assessed then.

> Does this correctly flag on #[cfg_attr(foo, invalid_attribute)] when foo is true? Could probably use a test if so

yes that does work. A test has been added.

**Comment by bjorn3** [comment]
> * [`sym::ffi_pure`](https://github.com/rust-lang/rust/issues/58329) not sure this makes sense, we have asm `options` already
> 
> * [`sym::ffi_const`](https://github.com/rust-lang/rust/issues/58328) like above

The asm `options` is entirely irrelevant for this. These attributes affect the callers of the function (allowing calls to be optimized out in certain cases depending on which attribute is used), not the way the function itself is codegened.

> `sym::instruction_set` switches between arm and thumb instructions. does not seem relevant when the user controls the assembly anyway

Without this attribute you can't always be sure of which instruction set you enter the asm block with and thus which instruction set you need to exit it with if you changed it internally. Also for arm32 I believe the linker needs to know if you are an arm or thumb function so you can't just switch it in the middle of the asm block I think.

**Comment by folkertdev** [comment]
allright, `instruction_set` is now on the allow list. `ffi_pure` and `ffi_const` are only allowed on foreign functions, so not relevant for naked functions.

**Comment by folkertdev** [comment]
I'm pretty sure bors will fail when running aarch64 tests. The last commit fixes those issues. Not sure what should happen but because the bors thing is tied to a commit I think some action is needed

**Comment by tgross35** [comment]
Bors bumps you out of the queue when you push, just doesn't update the labels for some reason.

Your last change switched from `att_syntax` to `raw`, why wouldn't at&t syntax work on aarch64?

**Comment by folkertdev** [comment]
well, "the `att_syntax` option is only supported on x86" is an error that is given. I guess it is just the default on any non-x86 system, and you cannot be explicit about that. Now that you bring it up that does seem a little weird, but not something that this PR should change I think.

**Comment by tgross35** [comment]
Ah weird, yeah seems reasonable.

@bors r=bjorn3

**Comment by hsanzg** [comment]
I'm currently [running into](https://github.com/hsanzg/coro/actions/runs/10154724488/job/28080311498) "error[E0736]: attribute incompatible with `#[naked]`" when compiling [this function](https://github.com/hsanzg/coro/blob/32639c387682625a70c2f38f794cc54b7378b6c6/src/arch/x86_64.rs#L14) with rustc 1.82.0-nightly (612a33f20 2024-07-29). The `x86_64` module is under a `target_arch` cfg attribute, but this code used to work fine in 1.81.0-nightly. It seems like `target_feature` is not the only `target_*` cfg flag that needs allowlisting.

**Comment by portasynthinca3** [comment]
Having the [same issue](https://github.com/rust-lang/rust/pull/127853#issuecomment-2257323333) over here.

**Comment by tgross35** [comment]
The fix is in https://github.com/rust-lang/rust/pull/128380, unless your case is different @portasynthinca3. It will probably be in either today or tomorrow's nightly.

**Comment by Freax13** [comment]
> unclear. Whether these make sense really depends on the outcome of #128004
> 
>   * `sym::repr`
> 
>   * `sym::patchable_function_entry`
> 
>   * `sym::no_sanitize`

Before this PR was merged, I was able to use `#[no_sanitize(address)]` on a `#[naked]` function with the calling convention `"x86-interrupt"`. Omitting `#[no_sanitize(address)]` leads to a [compiler crash](https://godbolt.org/z/j1T6W4ex8). I tried looking at the generated LLVM IR and the function prologue contains a bunch of other KASAN-related stuff which I wouldn't expect for naked function. I'm not sure whether the right solution here is to stop sanitizing naked functions in the first place or to allow `#[no_sanitize(...)]` on them.

**Comment by folkertdev** [comment]
The idea of the linked PR is to implement naked functions like this 

```rust
core::arch::global_asm!(".globl page_fault_handler","page_fault_handler:", "ud2");

extern "x86-interrupt" { 
    fn page_fault_handler(_: u64, _: u64);
}
```

but with support for (const) generics and with being able to export the symbol (which is tricky with extern function declarations in user space). I think in that world, the `no_sanitize` is no longer needed? At least on godbolt the above codegens fine.

However, in the meantime, we probably should not break anyone? @bjorn3 do you have thoughts on what to do?

**Comment by tgross35** [comment]
> Before this PR was merged, I was able to use `#[no_sanitize(address)]` on a `#[naked]` function with the calling convention `"x86-interrupt"`. Omitting `#[no_sanitize(address)]` leads to a [compiler crash](https://godbolt.org/z/j1T6W4ex8). I tried looking at the generated LLVM IR and the function prologue contains a bunch of other KASAN-related stuff which I wouldn't expect for naked function. I'm not sure whether the right solution here is to stop sanitizing naked functions in the first place or to allow `#[no_sanitize(...)]` on them.

@Freax13 could you open a new bug for this crash? It seems like that very specific combination of `extern "x86-interrupt"`, sanitizers, and naked functions is required to reproduce. And it's been around since before this PR, https://godbolt.org/z/EnhsWxejT (using RUSTC_BOOTSTRAP for the demo). Naked functions should probably just never get sanitizer annotations, but we can ping project-exploit-mitigations on the issue to confirm.
