### ISSUE TITLE
rust 1.44.0 fails to build in miri v0.1.0 on NetBSD/i386 8.0

### ISSUE THREAD

**Issue by he32** [rust-lang/rust#73117]
I have already successfully built rust 1.44.0 on NetBSD/amd64 8.0.
Next I'm tackling NetBSD/i386 8.0, but that is not going as expected, the build
errors out after hours of apparent successful building with

```
   Compiling miri v0.1.0 (/usr/pkgsrc/lang/rust/work/rustc-1.44.0-src/src/tools/miri)
error[E0478]: lifetime bound not satisfied
   --> src/tools/miri/src/diagnostics.rs:182:18
    |
182 | impl<'mir, 'tcx> EvalContextExt<'mir, 'tcx> for crate::MiriEvalContext<'mir, 'tcx> {}
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: lifetime parameter instantiated with the lifetime `'tcx` as defined on the impl at 182:12
   --> src/tools/miri/src/diagnostics.rs:182:12
    |
182 | impl<'mir, 'tcx> EvalContextExt<'mir, 'tcx> for crate::MiriEvalContext<'mir, 'tcx> {}
    |            ^^^^
note: but lifetime parameter must outlive the lifetime `'mir` as defined on the impl at 182:6
   --> src/tools/miri/src/diagnostics.rs:182:6
    |
182 | impl<'mir, 'tcx> EvalContextExt<'mir, 'tcx> for crate::MiriEvalContext<'mir, 'tcx> {}
    |      ^^^^

```

and several more instances of a similar error, and

```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'tcx` due to conflicting requirements
   --> src/tools/miri/src/helpers.rs:267:35
    |
267 |         impl<'ecx, 'mir, 'tcx, F> ValueVisitor<'mir, 'tcx, Evaluator<'tcx>>
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: first, the lifetime cannot outlive the lifetime `'tcx` as defined on the impl at 267:26...
   --> src/tools/miri/src/helpers.rs:267:26
    |
267 |         impl<'ecx, 'mir, 'tcx, F> ValueVisitor<'mir, 'tcx, Evaluator<'tcx>>
    |                          ^^^^
note: ...so that the types are compatible
   --> src/tools/miri/src/helpers.rs:267:35
    |
267 |         impl<'ecx, 'mir, 'tcx, F> ValueVisitor<'mir, 'tcx, Evaluator<'tcx>>
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: expected  `rustc_mir::interpret::ValueVisitor<'mir, 'tcx, machine::Evaluator<'tcx>>`
               found  `rustc_mir::interpret::ValueVisitor<'_, '_, machine::Evaluator<'_>>`
note: but, the lifetime must be valid for the lifetime `'mir` as defined on the impl at 267:20...
   --> src/tools/miri/src/helpers.rs:267:20
    |
267 |         impl<'ecx, 'mir, 'tcx, F> ValueVisitor<'mir, 'tcx, Evaluator<'tcx>>
    |                    ^^^^
note: ...so that the types are compatible
   --> src/tools/miri/src/helpers.rs:272:22
    |
272 |             type V = MPlaceTy<'tcx, Tag>;
    |                      ^^^^^^^^^^^^^^^^^^^
    = note: expected  `rustc_mir::interpret::visitor::Value<'mir, 'tcx, machine::Evaluator<'tcx>>`
               found  `rustc_mir::interpret::visitor::Value<'_, '_, machine::Evaluator<'tcx>>`
```

I'm confused.  Why would the amd64 build succeed and the i386 build fail when
building the same sources, with what appears to be a rust language issue??

I expected the build on NetBSD/i386 8.0 to succeed.

Instead, this happened: (see above).

The bootstrap compiler is rust 1.43.1.

### Meta

`rustc --version --verbose`:
```
rustc 1.43.1
binary: rustc
commit-hash: unknown
commit-date: unknown
host: i686-unknown-netbsd
release: 1.43.1
LLVM version: 9.0
```

**Comment by he32** [comment]
BTW, I have also now received reports that 1.44.0 also fails to build on NetBSD/amd64 versions 9.99.64 and 9.99.65 ("-current" development versions), so this isn't just an i386 issue, apparently.

**Comment by jperkin** [comment]
I see this on `x86_64-sun-solaris` too, using 1.43.1 as bootstrap.

**Comment by he32** [comment]
Actually...  @jperkin informed me that this build error is in fact non-fatal for the build as a whole, and now that I do a double take, that appears indeed to be the case -- the build completed despite the errors in this apparently-optional module.  Still, the principle of general tidyness would dictate that this should be dealt with one way or the other.

**Comment by mati865** [comment]
@RalfJung should Miri even build for stable releases?

**Comment by RalfJung** [comment]
No, Miri is not expected to build on beta/stable.  It's a nightly-only tool.

**Comment by RalfJung** [comment]
@he32 why are you even trying to build Miri? Distro packages for stable Rust should not do that.

**Comment by jperkin** [comment]
We aren't specifically building it, or at least not that we're aware of, it's just being automatically built as part of `python x.py -v build`.

At least I don't see anything in our build target or configure arguments that appear out of the ordinary.  The pkgsrc Makefile for rust is here: <https://github.com/NetBSD/pkgsrc/blob/trunk/lang/rust/Makefile>, it has a bunch of bits you can ignore but the `CONFIGURE_ARGS` and `do-build` target seem reasonably standard to me, but perhaps there's some flag there that is causing it to be included.

**Comment by he32** [comment]
> > Besides, the above statement looks really strange to an outsider like me.
> 
> What is odd about the statement of a tool being nightly-only and experimental?

I read it as "Miri is never expected to build in stable / releases, but (mostly?) builds fine in the current development version." which struck me as really strange.  Now it just looks like a "bad time" was encountered between cutting the release and the ability to build "Miri" which is more understandable once I understood it's experimental and optional.

However, I'm a proponent of "sane defaults".  If "Miri" is not expected to be built as part of a release, I would have expected its build to be disabled by default in a release.

The suggestion to un-comment the `tools` array setting in `config.toml` is "not a default, more knowledge you need to possess and work you have to do to do a normal release build".  There's also the issue of whether that list of tools is actively maintained...  I would rather rely on "sane defaults" than having to do even more tinkering -- there's certainly more than enough of that already to get `rust` off the ground.

**Comment by RalfJung** [comment]
> I would have expected its build to be disabled by default in a release.

So would I. I didn't know we build it by default. I submitted https://github.com/rust-lang/rust/pull/73232 to fix that, but unfortunately this touches barely documented parts of `x.py` that I do not understand (like the `DEFAULT` associated const).
