### PR TITLE
Explicitly deny elided lifetimes in associated consts

### PR DESCRIPTION
**Pull request by compiler-errors**
This seems to have regressed in #97313, after which we have begun resolving elided lifetimes in impls to anonymous early-bound lifetimes.

This PR applies an `AnonymousReportError` lifetime binder to both impl and trait const items to avoid this behavior. Only the former needs it, but also doing the latter for diagnostic consistency.

r? @cjgillot or @petrochenkov
Please review with whitespace changes disabled, the real diff is like 4 lines.

This probably requires a crater run anyways, but this is clearly a bug. I personally think we should use an `Elided(LifetimeRes::Static)` rib here, but that would require a T-lang FCP (or an RFC? idk).

cc #114706

### CODE REVIEW

File: tests/ui/suggestions/missing-lifetime-in-assoc-const-type.generic_const_items.stderr [hunk 1]
```diff
@@ -20,16 +15,11 @@ help: consider introducing a named lifetime parameter
...
+error[E0637]: `'_` cannot be used here
   --> $DIR/missing-lifetime-in-assoc-const-type.rs:8:15
    |
 LL |     const C: &'_ str = "";
-   |               ^^ expected named lifetime parameter
-   |
-help: consider introducing a named lifetime parameter
-   |
-LL |     const C<'a>: &'a str = "";
-   |            ++++   ~~
```
Comment (compiler-errors) [inline tests/ui/suggestions/missing-lifetime-in-assoc-const-type.generic_const_items.stderr:32]: I guess I could probably recover this suggestion by inverting the order of the lifetime ribs... Doesn't seem particularly useful, though.

Comment (fmease) [reply tests/ui/suggestions/missing-lifetime-in-assoc-const-type.generic_const_items.stderr:32]: If we end up deciding on dropping those suggestion diagnostics (personally I'm fine either way, also don't know how useful they are, mainly they're consistent with other diagnostics), then you can get rid of the revisions of this test as well as `LifetimeBinderKind::ConstItem` (→ `Item`) in `late/diagnostics.rs` since it will become unreachable.

**Comment by compiler-errors** [comment]
Blocked on a cargo sync for now.

@rustbot blocked

**Comment by compiler-errors** [comment]
@craterbot check

**Comment by compiler-errors** [comment]
Well of course people have begun to rely on this faulty behavior :/

**Comment by compiler-errors** [comment]
Closing in favor of a future-compat lint: #115011
