### ISSUE TITLE
Move after burrow when returning a tuple

### ISSUE THREAD

**Issue by xixixao** [rust-lang/rust#79720]
This errors:

```rust
fn hit2() -> HitResult {
    if let Some((hit_info, _)) = hit1() {
        return Some((hit_info, scatter(&hit_info)));
    }
    return None;
}
```
<details><summary><i>Full code, plug into Playground</i></summary>
<p>

```rust
struct HitInfo {}

struct ScatterInfo {}

type HitResult = Option<(HitInfo, Option<ScatterInfo>)>;

fn hit1() -> HitResult {
    None
}

fn hit2() -> HitResult {
    if let Some((hit_info, _)) = hit1() {
        return Some((hit_info, scatter(&hit_info)));
    }
    return None;
}

fn scatter(_hit_info: &HitInfo) -> Option<ScatterInfo> {
    None
}

```

</p>
</details>

with this error:
```
error[E0382]: borrow of moved value: `hit_info`
  --> src/lib.rs:13:40
   |
12 |     if let Some((hit_info, _)) = hit1() {
   |                  -------- move occurs because `hit_info` has type `HitInfo`, which does not implement the `Copy` trait
13 |         return Some((hit_info, scatter(&hit_info)));
   |                      --------          ^^^^^^^^^ value borrowed here after move
   |                      |
   |                      value moved here
```

but this doesn't:

```rust
fn hit2() -> HitResult {
    if let Some((hit_info, _)) = hit1() {
        let good = scatter(&hit_info);
        return Some((hit_info, good));
    }
    return None;
}
```

<details><summary><i>Full code, plug into Playground</i></summary>
<p>

```rust
struct HitInfo {}

struct ScatterInfo {}

type HitResult = Option<(HitInfo, Option<ScatterInfo>)>;

fn hit1() -> HitResult {
    None
}

fn hit2() -> HitResult {
    if let Some((hit_info, _)) = hit1() {
        let good = scatter(&hit_info);
        return Some((hit_info, good));
    }
    return None;
}

fn scatter(_hit_info: &HitInfo) -> Option<ScatterInfo> {
    None
}

```

</p>
</details>

I guess there could be some explanation why this doesn't act in a referentially transparent way, but it seems pretty confusing.

### Meta

`rustc --version --verbose`:
```
Build using the Nightly version: 1.50.0-nightly
(2020-12-03 5be3f9f10e9fd59ea038)
```

**Comment by jonas-schievink** [comment]
This is working as expected due to the order of evaluation being left-to-right
