### PR TITLE
Use the correct lifetime binder for elided lifetimes in path.

### LINKED ISSUE #96540: regression from error on elided lifetime in path in `-> impl Trait<...>`
### Code

I tried this code:

```rust
use std::marker::PhantomData;

struct Foo<'a>(PhantomData<&'a ()>);

fn foo() -> impl Fn(Foo) {
    |_| ()
}

fn main() {}
```

I expected to see this happen: it compile

Instead, this happened: it didnt

```
error[E0106]: missing lifetime specifier
 --> src/main.rs:5:21
  |
5 | fn foo() -> impl Fn(Foo) {
  |                     ^^^ expected named lifetime parameter
  |
  = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
help: consider using the `'static` lifetime
  |
5 | fn foo() -> impl Fn(Foo<'static>) {
  |                     ~~~~~~~~~~~~

For more information about this error, try `rustc --explain E0106`.
```

### Version it worked on

It most recently worked on Rust 1.60 and this nighty:
```
rustc 1.62.0-nightly (69a5d2481 2022-04-27)
binary: rustc
commit-hash: 69a5d2481e856a5a18885390b8cf6950b9ff8dd3
commit-date: 2022-04-27
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

### Version with regression

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (e85edd9a8 2022-04-28)
binary: rustc
commit-hash: e85edd9a844b523a02dbd89f3c02cd13e4c9fe46
commit-date: 2022-04-28
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

### cargo bisect
searched nightlies: from nightly-2022-04-26 to nightly-2022-04-29
regressed nightly: nightly-2022-04-29
searched commit range: https://github.com/rust-lang/rust/compare/69a5d2481e856a5a18885390b8cf6950b9ff8dd3...e85edd9a844b523a02dbd89f3c02cd13e4c9fe46
regressed commit: https://github.com/rust-lang/rust/commit/c95346b8ac8f10927b4aec31e61d45c75b10ba74

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.3</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2022-04-26 
```
</details>

### PR DESCRIPTION
**Pull request by cjgillot**
Fixes https://github.com/rust-lang/rust/issues/96540

### CODE REVIEW

File: compiler/rustc_resolve/src/late.rs [hunk 1]
```diff
@@ -1319,7 +1319,8 @@ impl<'a: 'ast, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
                 | PathSource::Struct
                 | PathSource::TupleStruct(..) => false,
             };
-            let mut error = false;
+            let mut error = true;
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/late.rs:1322]: `error` is redundant here, no?
It's always equivalent to `res == LifetimeRes::Error`.

File: compiler/rustc_resolve/src/late.rs [hunk 2]
```diff
@@ -1338,19 +1338,22 @@ impl<'a: 'ast, 'b, 'ast> LateResolutionVisitor<'a, 'b, 'ast> {
...
-                    | LifetimeRibKind::AnonymousReportError
-                    | LifetimeRibKind::Item => break,
+                    LifetimeRibKind::AnonymousPassThrough(binder) => {
+                        error = false;
+                        res = LifetimeRes::Anonymous { binder, elided: true };
+                        break;
+                    }
+                    LifetimeRibKind::AnonymousReportError | LifetimeRibKind::Item => {
+                        // FIXME(cjgillot) This resolution is wrong, but this does not matter
+                        // since these cases are erroneous anyway.
```
Comment (petrochenkov) [inline compiler/rustc_resolve/src/late.rs:1348]: What makes it erroneous? Does HIR lifetime resolution report the error? Could you mention it in the comment?
