### PR TITLE
Use BCryptGenRandom instead of RtlGenRandom on Windows.

### PR DESCRIPTION
**Pull request by m-ou-se**
This removes usage of RtlGenRandom on Windows, in favour of BCryptGenRandom.

BCryptGenRandom isn't available on XP, but we dropped XP support a while ago.

### CODE REVIEW

**Review by Xanewok — APPROVED** [review]

**Review by dtolnay — APPROVED** [review]
Looks good to me. https://github.com/rust-random/getrandom/issues/65#issuecomment-753634074 was a helpful summary of the situation and justification for BCryptGenRandom.

Equivalent change removing RtlGenRandom in the `getrandom` crate after dropping XP support: https://github.com/rust-random/getrandom/pull/177.

**Comment by m-ou-se** [comment]
@bors r- 

Failed in #84405:
```
 nonclike.lib(std-7b1ea478f8120585.std.9x5dan1p-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol BCryptGenRandom referenced in function _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17hb431615f775d47a7E
 ```
https://github.com/rust-lang-ci/rust/runs/2403918836

**Comment by josephlr** [comment]
> Failed in #84405:
> 
> ```
>  nonclike.lib(std-7b1ea478f8120585.std.9x5dan1p-cgu.0.rcgu.o) : error LNK2019: unresolved external symbol BCryptGenRandom referenced in function _ZN3std6thread5local4fast12Key$LT$T$GT$14try_initialize17hb431615f775d47a7E
> ```

I think we just need to add the appropriate bcrypt flags here: https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/src/test/run-make-fulldeps/tools.mk#L104

File: library/std/src/sys/windows/mod.rs [hunk 1]
```diff
@@ -275,13 +275,13 @@ pub fn abort_internal() -> ! {
...
     if #[cfg(target_vendor = "uwp")] {
         #[link(name = "ws2_32")]
-        // For BCryptGenRandom
-        #[link(name = "bcrypt")]
+        #[link(name = "bcrypt")] // For BCryptGenRandom
         extern "C" {}
     } else {
         #[link(name = "advapi32")]
         #[link(name = "ws2_32")]
         #[link(name = "userenv")]
```
Comment (josephlr) [inline library/std/src/sys/windows/mod.rs:283]: We should add `// For GetUserProfileDirectoryW` (as that's the only reason we need `Userenv.lib`)

File: library/std/src/sys/windows/mod.rs [hunk 2]
```diff
@@ -275,13 +275,13 @@ pub fn abort_internal() -> ! {
 cfg_if::cfg_if! {
     if #[cfg(target_vendor = "uwp")] {
         #[link(name = "ws2_32")]
-        // For BCryptGenRandom
-        #[link(name = "bcrypt")]
+        #[link(name = "bcrypt")] // For BCryptGenRandom
         extern "C" {}
     } else {
         #[link(name = "advapi32")]
```
Comment (josephlr) [inline library/std/src/sys/windows/mod.rs:281]: Now that we aren't using `RtlGenRandom`, we should add `// For OpenProcessToken` (as that's then only function left from `Advapi32.lib`).

**Review by josephlr — APPROVED** [review]

**Comment by JohnCSimon** [comment]
Ping from triage
@m-ou-se - this PR has had merge conflicts since May 23, but already has two approvals.

**Comment by camelid** [comment]
triage: @m-ou-se it looks like this may just need a rebase and a change to the linking config?
