### ISSUE TITLE
1.99 beta crater regression due to `Vec::from_parts` name collision

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#162239]
This regression was found by the 1.99 crater run.

```
[INFO] [stdout] error[E0061]: this function takes 3 arguments but 1 argument was supplied
[INFO] [stdout]   --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/kittycad-execution-plan-traits-0.1.15/src/containers.rs:99:9
[INFO] [stdout]    |
[INFO] [stdout] 99 |         Vec::from_parts(values)
[INFO] [stdout]    |         ^^^^^^^^^^^^^^^-------- two arguments of type `usize` and `usize` are missing
[INFO] [stdout]    |
[INFO] [stdout] note: expected `NonNull<_>`, found `&mut I`
[INFO] [stdout]   --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/kittycad-execution-plan-traits-0.1.15/src/containers.rs:99:25
[INFO] [stdout]    |
[INFO] [stdout] 99 |         Vec::from_parts(values)
[INFO] [stdout]    |                         ^^^^^^
[INFO] [stdout]    = note:         expected struct `NonNull<_>`
[INFO] [stdout]            found mutable reference `&mut I`
[INFO] [stdout] note: associated function defined here
[INFO] [stdout]   --> /rustc/f47d5bb13648d5c859f5b438eb7dc834b9729961/library/alloc/src/vec/mod.rs:741:24
[INFO] [stdout] help: call `Into::into` on this expression to convert `&mut I` into `NonNull<_>`
[INFO] [stdout]    |
[INFO] [stdout] 99 |         Vec::from_parts(values.into())
[INFO] [stdout]    |                               +++++++
[INFO] [stdout] help: provide the arguments
[INFO] [stdout]    |
[INFO] [stdout] 99 -         Vec::from_parts(values)
[INFO] [stdout] 99 +         Vec::from_parts(/* ptr */, /* usize */, /* usize */)
[INFO] [stdout]    |
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] error[E0599]: `Vec<_>` is not an iterator
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/kittycad-execution-plan-traits-0.1.15/src/containers.rs:101:14
[INFO] [stdout]     |
[INFO] [stdout]  99 | /         Vec::from_parts(values)
[INFO] [stdout] 100 | |             // Then convert the vec into a hashmap.
[INFO] [stdout] 101 | |             .map(|(v, count)| (v.into_iter().collect(), count))
[INFO] [stdout]     | |             -^^^ `Vec<_>` is not an iterator
[INFO] [stdout]     | |_____________|
[INFO] [stdout]     |
[INFO] [stdout]     |
[INFO] [stdout]     = note: the following trait bounds were not satisfied:
[INFO] [stdout]             `Vec<_>: Iterator`
[INFO] [stdout]             which is required by `&mut Vec<_>: Iterator`
[INFO] [stdout]             `[_]: Iterator`
[INFO] [stdout]             which is required by `&mut [_]: Iterator`
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] Some errors have detailed explanations: E0061, E0599.
[INFO] [stdout] 
[INFO] [stdout] For more information about an error, try `rustc --explain E0061`.
```

https://crater-reports.s3.amazonaws.com/beta-1.99-5/1.99.0-beta.1/reg/kittycad-execution-plan-macros-0.1.9/log.txt

Presumably regressed in #157226, due to a name collision with [a trait method](https://docs.rs/crate/kittycad-execution-plan-traits/latest/source/src/containers.rs#62).

**Comment by theemathas** [comment]
The crate's last version was published in 2024. The repo link for this crate points to https://github.com/KittyCAD/modeling-api, which seems to have no trace of this crate. I assume that this crate is no longer used, and was at some point deleted from github.

Closing this issue, as there's no practical breakage.
