### PR TITLE
rustc_resolve: allow only core, std, meta and --extern in Rust 2018 paths.

### LINKED ISSUE #54006: unstable `alloc` crate can be used without feature gates on the 2018 edition
### STR

This compiles when `edition = "2018"`

``` rust
// crate-type: lib
#![no_std]

use alloc::vec;

fn foo() {
    let mut xs = vec![];
    xs.push(0);
}
```

This doesn't compile when `edition = "2015"` because it needs a feature gate.

``` rust
// crate-type: lib
#![no_std]

extern crate alloc; //~ ERROR use of unstable library feature `alloc`

use alloc::vec;

fn foo() {
    let mut xs = vec![];
    xs.push(0);
}
```

### Meta

```console
$ rustc -V
rustc 1.30.0-nightly (6e0f1cc15 2018-09-05)
```

### LINKED ISSUE #54253: Interaction with uniform_paths canaries can hide import errors and lead to strange ICEs.
Reduced from RLS' source (on the Rust 2018 edition):
```rust
// Dummy import to introduce `uniform_paths` canaries.
use std;

// fn version() -> &'static str {""}

mod foo {
    // Error *not* reported, despite `version` being commented out above!
    use crate::version; 
    
    fn bar() {
        version();
    }
}

fn main() {}
```

The `use std;` import is the one introducing the canaries - if it's changed to `use ::std;`, the error for `version` is emitted. With no import errors, various parts of the compiler can ICE.
(currently `attempted .def_id() on invalid def: Err`, triggered by lints trying to run on `foo::bar`)

I'll try to fix it during #54116, as it was discovered during my attempt to fix RLS for that PR.

### PR DESCRIPTION
**Pull request by eddyb**
As per https://github.com/rust-lang/rust/issues/53166#issuecomment-419265401:
* Rust 2018 imports can no longer refer to crates not in "extern prelude"
  * `::foo` won't load a crate named `foo` unless `foo` is in the "extern prelude"
  * `extern crate foo;`, however, remains unchanged (can load arbitrary crates)
* `--extern crate_name` is added (note the lack of `=path`) as an unstable option
  * adds `crate_name` to the "extern prelude" (see above)
  * crate is searched in sysroot & library paths, just like `extern crate crate_name`.
  * `Cargo` support will be added later
* `core`, `std` and ~~`proc_macro`~~ `meta` are *always* available in the extern prelude
  * warning for interaction with `no_std` / `no_core` will be added later
  * **EDIT**: `proc_macro` was replaced by `meta`, see https://github.com/rust-lang/rust/issues/53166#issuecomment-421137230
    * note that there is no crate named `meta` being added, so `use meta::...;` will fail, we're only whitelisting it so we can start producing `uniform_paths` compatibility errors

Fixes #54006 (as the example now requires `--extern alloc`, which is unstable).
Fixes #54253 (hit during fixing RLS).

r? @petrochenkov cc @aturon @alexcrichton @Centril @joshtriplett

### CODE REVIEW

**Comment by petrochenkov** [comment]
@bors r+

I'm [still unhappy](https://github.com/rust-lang/rust/issues/53130#issuecomment-415485208) about forever hardcoding `proc_macro`, which can't be off-loaded to the library prelude unlike `core`/`std`, in the compiler, but at least it's already hardcoded for other reasons.

**Comment by eddyb** [comment]
Hang on, [Travis build](https://travis-ci.org/rust-lang/rust/jobs/426994388) appears to have failed, while documenting `libstd`.
I don't understand why the PR's status is not updated.

@bors r-

**Comment by eddyb** [comment]
The failure is from the crate number used for indexing `providers` being out of bounds:
https://github.com/rust-lang/rust/blob/7ee72070bdb789f58f272fab50d49bd48dd9c11f/src/librustc/ty/query/plumbing.rs#L819-L824

This means that a crate has been loaded after the query engine was created.
Long-term this should "just work", but it's not integrated with the query engine yet.
`rustc_resolve` *usually* runs before the query engine, *except* for `rustdoc`, which creates a resolver after, to handle `[Foo]` doc links.
I'll try to make creating the query engine disable loading crates, if I can at all.

**Comment by aturon** [comment]
LGTM

**Comment by eddyb** [comment]
I thought the failure was from suggestion code, but it turns out it's from doc comment paths that happen to start with `std`, despite being in a crate with `#![no_std]` (in this case, `std` itself).
So I think I should instead try to make this work, in the query engine.

**Comment by eddyb** [comment]
Oh. `clippy` and `rls` need their `extern crate rustc_foo;` back, that makes sense.

**Comment by eddyb** [comment]
@kennytm I fixed it already but now I'm trying to get RLS to work, and hitting a weird ICE.

**Comment by eddyb** [comment]
```rust
error[E0308]: mismatched types
   --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\compiletest_rs-0.3.13\src\lib.rs:100:22
    |
100 |         run_ignored: config.run_ignored,
    |                      ^^^^^^^^^^^^^^^^^^ expected enum `test::RunIgnored`, found bool
    |
    = note: expected type `test::RunIgnored`
               found type `bool`
error: aborting due to previous error
```
This might be from a change that's between master's `src/tools/clippy` and this PR's.

**Comment by eddyb** [comment]
I decided to revert #53527 - we can reapply it later, it requires fixing too many moving parts.

@bors r=petrochenkov

**Comment by eddyb** [comment]
cc @rust-lang/release I believe this was the last blocker for RC.

**Comment by Nemo157** [comment]
This change (I assume) affects benchmarks as [`use test::Bencher;` no longer finds the test crate](https://travis-ci.org/rust-lang-nursery/futures-rs/jobs/429819447). Presumable any test using `test::black_box` is similarly affected. Should the `test` crate also be included for test targets, or should these still use `extern crate test;`? (I’m not sure which tracking issue actually covers the extern prelude stuff, so I’ll just leave this here).
