### ISSUE TITLE
Add parenthesis around suggestions to use `.into()` on cast expr

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#47699]
[Given the following code](https://play.rust-lang.org/?gist=e697723431394a15eaaba4681653f1d1&version=nightly):

```
fn main() {
    let array = [1, 2, 3];
    test(array.len() as u8);
}

fn test(length: u32) {
    println!("{}", length);
}
```

rustc suggests

```
error[E0308]: mismatched types
 --> src/main.rs:3:10
  |
3 |     test(array.len() as u8);
  |          ^^^^^^^^^^^^^^^^^ expected u32, found u8
help: you can cast an `u8` to `u32`, which will zero-extend the source value
  |
3 |     test(array.len() as u8.into());
  |          ^^^^^^^^^^^^^^^^^^^^^^^^
```

The suggestion should be enclosing the entire expression in parenthesis.

This was introduced in #47247. The solution is to change [`needs_paren`](https://github.com/rust-lang/rust/pull/47247/files#diff-124df07081a1185b5a4d40cdcf0cf4ffR339) to be inclusive of the precedence of `as`, in other words, change the `<` with `<=` and add a test for the behavior.

**Comment by petrochenkov** [comment]
Unary prefix operators should be parenthesized as well in general case.
https://play.rust-lang.org/?gist=010eb251f1e518d682fcf7a70ba0a1db&version=undefined

As I [said](https://github.com/rust-lang/rust/pull/47247#discussion_r160623280) in https://github.com/rust-lang/rust/pull/47247 `AssocOp::As.precedence()` needs to be replaced with `PREC_POSTFIX`.
