### ISSUE TITLE
Don't point to `Fn::call` when the arguments passed to a closure are incorrect

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#98308]
Given the following code: 

```rust
fn takes_callback(callback: impl Fn(i32)) {
    callback(&0);
}
```

The current output is dependent on whether you have the `rust-src` component installed. With it installed:

```
error[E0308]: mismatched types
  --> src/main.rs:2:14
   |
2  |     callback(&0);
   |     -------- ^^ expected `i32`, found `&{integer}`
   |     |
   |     arguments to this function are incorrect
   |
note: associated function defined here
  --> /home/jnelson/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:77:27
   |
77 |     extern "rust-call" fn call(&self, args: Args)...
   |                           ^^^^
help: consider removing the borrow
   |
2  -     callback(&0);
2  +     callback(0);
```

without it (e.g. on playground), the same except the note looks very strange because it doesn't actually point anywhere:
```
note: associated function defined here
help: consider removing the borrow
```

Ideally the output should look like:

```
error[E0308]: mismatched types
  --> src/main.rs:2:14
   |
2  |     callback(&0);
   |     -------- ^^ expected `i32`, found `&{integer}`
   |     |
   |     arguments to this function are incorrect
   |
note: function defined here:
  --> src/main.rs:1:x
   |
1 |     fn takes_callback(callback: impl Fn(i32)) {
   |                                ^^^^^^^^^^^^
help: consider removing the borrow
   |
2  -     callback(&0);
2  +     callback(0);
```

**Comment by jyn514** [comment]
regression from https://github.com/rust-lang/rust/commit/15495767324ec173a01b6ff0197b5c4fceb61d21 maybe? cc @jackh726
https://github.com/rust-lang/rust/blob/15495767324ec173a01b6ff0197b5c4fceb61d21/compiler/rustc_typeck/src/check/fn_ctxt/checks.rs#L1751

**Comment by inquisitivecrystal** [comment]
Tagging as `P-medium`, as [discussed by the prioritization working group](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2398308.20Don't.20point.20to.20.60Fn.3A.3Acall.60.20when.20the.20arguments.20passed.20.E2.80.A6).
