### PR TITLE
Point at `'static` obligations from an fn being called

### PR DESCRIPTION
**Pull request by estebank**
Add this note to lifetime errors:

```text
error[E0521]: borrowed data escapes outside of function
  --> $DIR/static-impl-obligation.rs:163:9
   |
LL |     fn bar<'a>(x: &'a &'a u32) {
   |            --  - `x` is only valid in the function body
   |            |
   |            lifetime `'a` defined here
LL |         let y: &dyn Foo = x;
LL |         y.hello();
   |         ^^^^^^^^^
   |         |
   |         `x` escapes the function body here
   |         argument requires that `'a` must outlive `'static`
   |
note: `'static` lifetime requirement from `<(dyn o::Foo + 'static)>::hello` introduced here
  --> $DIR/static-impl-obligation.rs:158:20
   |
LL |     impl dyn Foo + 'static where Self: 'static {
   |                    ^^^^^^^             ^^^^^^^ lifetime requirement introduced here
   |                    |
   |                    lifetime requirement introduced here
LL |         fn hello(&'static self) where Self: 'static {}
   |                  ^^^^^^^^^^^^^              ^^^^^^^ lifetime requirement introduced here
   |                  |
   |                  lifetime requirement introduced here

```

Follow up to https://github.com/rust-lang/rust/pull/121274, taking only a subset of that unmerged PR's functionality.

### CODE REVIEW

File: compiler/rustc_borrowck/src/diagnostics/region_errors.rs [hunk 1]
```diff
@@ -391,6 +392,89 @@ impl<'diag, 'tcx> MirBorrowckCtxt<'_, 'diag, 'tcx> {
...
     }
 
+    /// Point at `'static` obligations from the item being called.
+    ///
+    /// ```text
+    /// error[E0521]: borrowed data escapes outside of function
+    ///   --> $DIR/static-impl-obligation.rs:163:9
+    ///    |
+    /// LL |     fn bar<'a>(x: &'a &'a u32) {
+    ///    |            --  - `x` is a reference that is only valid in the function body
```
Comment (maxdexh) [inline compiler/rustc_borrowck/src/diagnostics/region_errors.rs]: This will fail due to #163016

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/163115/56fad885ebfb0447660870715da4dfa75deae93d..e478abb6124a09fa44d093bed1ad127a74ed4c43)*

Comment (maxdexh) [reply compiler/rustc_borrowck/src/diagnostics/region_errors.rs]: Oh wait I thought this was a test when I wrote that comment on my phone, but it's a source file, sry ^^

I that case, that is not the error messag as it will be shown, due to said PR (the "is a reference that" is too much)

Comment (estebank) [reply compiler/rustc_borrowck/src/diagnostics/region_errors.rs]: Yeah, I had to rebase already but didn't modify the comment.

File: tests/ui/lifetimes/static-impl-obligation.stderr [hunk 2]
```diff
@@ -0,0 +1,614 @@
...
+   |
+LL |     impl MyTrait for dyn ObjectTrait + '_ {}
+   |          ^^^^^^^
+   |
+note: lifetime parameter instantiated with the anonymous lifetime as defined here
+  --> $DIR/static-impl-obligation.rs:221:40
+   |
+LL |     impl MyTrait for dyn ObjectTrait + '_ {}
+   |                                        ^^
+   = note: but lifetime parameter must outlive the static lifetime
```
Comment (estebank) [inline tests/ui/lifetimes/static-impl-obligation.stderr:18]: Future work: This diagnostic should be pointing at 214 `trait MyTrait where Self: 'static {` as the reason why it must outlive `'static`.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/163115/56fad885ebfb0447660870715da4dfa75deae93d..a91d256934cc9d62cd65972323246d243e8d7730)*

File: tests/ui/lifetimes/static-impl-obligation.stderr [hunk 3]
```diff
@@ -0,0 +1,614 @@
...
+LL |     impl MyTrait for dyn ObjectTrait + '_ {}
+   |                      ^^^^^^^^^^^^^^^^^^^^
+   = note: expected `<dyn t::ObjectTrait as t::MyTrait>`
+              found `<dyn t::ObjectTrait as t::MyTrait>`
+   = note: but, the lifetime must be valid for the static lifetime...
+note: ...so that the declared lifetime parameter bounds are satisfied
+  --> $DIR/static-impl-obligation.rs:221:22
+   |
+LL |     impl MyTrait for dyn ObjectTrait + '_ {}
+   |                      ^^^^^^^^^^^^^^^^^^^^
```
Comment (estebank) [inline tests/ui/lifetimes/static-impl-obligation.stderr:43]: The second to last note should be pointing at 214.

*[View changes since the review](https://triagebot.infra.rust-lang.org/gh-changes-since/rust-lang/rust/163115/56fad885ebfb0447660870715da4dfa75deae93d..a91d256934cc9d62cd65972323246d243e8d7730)*

**Review by davidtwco — APPROVED** [review]
