### ISSUE TITLE
Generic patterns and generic array lengths can call const fn with impossible generics

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#147721]
```rust
// No type implements this trait
unsafe trait NotImplemented {}

const fn lol<T: NotImplemented>() -> usize {
    panic!("This should not be callable");
}

struct Dummy<T>(T);
impl<T: NotImplemented> Dummy<T> {
    const C: usize = lol::<T>();
}

fn foo<T: NotImplemented>() {
    if let Dummy::<T>::C = 1 {}
}
```

I expected the above code to not execute the panic, either at compile time or run time, since there is no `T` that implements `NotImplemented`. Instead, I got the following compiler error:

```
error[E0080]: evaluation panicked: This should not be callable
  --> src/lib.rs:10:22
   |
10 |     const C: usize = lol::<T>();
   |                      ^^^^^^^^^^ evaluation of `Dummy::<T>::C` failed inside this call
   |
note: inside `lol::<T>`
  --> src/lib.rs:5:5
   |
 5 |     panic!("This should not be callable");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the failure occurred here

For more information about this error, try `rustc --explain E0080`.
```

Note that the code compiles fine if I make `fn lol` return a value normally instead of panicking.

Also note that the code gives a reasonable compile error if I make `fn lol` return `size_of::<T>()`

<details>
<summary>Error with `size_of::<T>()`</summary>

```
error[E0158]: constant pattern cannot depend on generic parameters
  --> src/lib.rs:14:12
   |
 9 | impl<T: NotImplemented> Dummy<T> {
   | --------------------------------
10 |     const C: usize = lol::<T>();
   |     -------------- constant defined here
...
13 | fn foo<T: NotImplemented>() {
   |        - constant depends on this generic parameter
14 |     if let Dummy::<T>::C = 1 {}
   |            ^^^^^^^^^^^^^ `const` depends on a generic parameter

For more information about this error, try `rustc --explain E0158`.
```

</details>

Using an array length instead of a pattern also runs into a similar issue:

<details>
<summary>Code and error using array length</summary>

```rust
// No type implements this trait
unsafe trait NotImplemented {}

const fn lol<T: NotImplemented>() -> usize {
    panic!("This should not be callable");
}

struct Dummy<T>(T);
impl<T: NotImplemented> Dummy<T> {
    const C: usize = lol::<T>();
}

fn foo<T: NotImplemented>() {
    let _x = [0u8; Dummy::<T>::C];
}
```

```
error[E0080]: evaluation panicked: This should not be callable
  --> src/lib.rs:10:22
   |
10 |     const C: usize = lol::<T>();
   |                      ^^^^^^^^^^ evaluation of `Dummy::<T>::C` failed inside this call
   |
note: inside `lol::<T>`
  --> src/lib.rs:5:5
   |
 5 |     panic!("This should not be callable");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the failure occurred here

note: erroneous constant encountered
  --> src/lib.rs:14:20
   |
14 |     let _x = [0u8; Dummy::<T>::C];
   |                    ^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0080`.
```

</details>

### Meta

Reproducible on the playground with version `1.92.0-nightly (2025-10-13 4b94758d2ba7d0ef71cc)`

**Comment by theemathas** [comment]
This can also cause strange behavior with impossible bounds:

```rust
struct Thing;
trait Trait {
    type Assoc;
}

const fn lol() where for<'a> Thing: Trait {
    let _x = None::<<Thing as Trait>::Assoc>;
}

struct Dummy;
impl Dummy where for<'a> Thing: Trait {
    const C: () = lol();
}

fn foo() where for<'a> Thing: Trait {
    if let Dummy::C = () {}
}
```

```
error[E0080]: entering unreachable code
  --> src/lib.rs:12:19
   |
12 |     const C: () = lol();
   |                   ^^^^^ evaluation of `Dummy::C` failed here

For more information about this error, try `rustc --explain E0080`.
```

**Comment by RalfJung** [comment]
Cc @Nadrieril @lcnr @BoxyUwU

**Comment by BoxyUwU** [comment]
this was something I was kind of working on at some point but wound up down a rabbithole 🤔 I think probably we want the "const patterns cant depend on generics" check to be syntactic (i.e. how it works for const generics) rather than based on CTFE returning `TooGeneric`, and then CTFE just only evaluates stuff that doesnt name any generic parameters

This is almost certainly a breaking change and I'm not sure exactly how breaking it would be. Array lengths will be solved at some point when `const_evaluatable_unchecked` becomes a hard error- that code is FCW'd already.

There are probably follow on things we'd need to do after this to make all cases work properly:tm: but I think not running const eval on generic code is likely to be a necessary first step

**Comment by BoxyUwU** [comment]
(cc [#t-compiler/const-eval > Evaluating non-wf constants](https://rust-lang.zulipchat.com/#narrow/channel/146212-t-compiler.2Fconst-eval/topic/Evaluating.20non-wf.20constants/with/512329990))

**Comment by theemathas** [comment]
@purplesyringa found that this code compiles on nightly (`1.93.0-nightly (2025-11-18 3d461af2a23456a2676a)`), but not on beta (`1.92.0-beta.3 (2025-11-09 f3f12444a017add0468f)`). Is that a problem?

```rust
struct Dummy;
impl Dummy where for<'a> &'a mut i32: Copy {
    const C: usize = 1;
}

fn foo() where for<'a> &'a mut i32: Copy {
    if let Dummy::C = 1 {}
}
```

**Comment by theemathas** [comment]
Currently, this code (copied from https://github.com/rust-lang/rust/issues/147721#issuecomment-3553360408) compiles:

```rust
struct Dummy;
impl Dummy where for<'a> &'a mut i32: Copy {
    const C: usize = 1;
}

fn foo() where for<'a> &'a mut i32: Copy {
    if let Dummy::C = 1 {}
}
```

However, this code does not compile:

```rust
struct Dummy;
impl Dummy where for<'a> &'a mut i32: Copy {
    const C: usize = { let x = 1; x };
}

fn foo() where for<'a> &'a mut i32: Copy {
    if let Dummy::C = 1 {}
}
```

This discrepancy started happening in Rust 1.93.0.

I'm guessing that this probably happened due to #148040. CC @saethlin.

**Comment by saethlin** [comment]
I won't pretend to understand the type system shenanigans going on here, but https://github.com/rust-lang/rust/pull/156934 is a potential fix.
