### ISSUE TITLE
Build error with extern crates after upgrading to 2018 edition

### ISSUE THREAD

**Issue by elliottslaughter** [rust-lang/rust#56398]
I took my project here and converted it to the 2018 edition: https://github.com/elliottslaughter/integrity-checker

The flow I used was:

```
git clone https://github.com/elliottslaughter/integrity-checker
cd integrity-checker
cargo +beta fix --edition # no warnings on first try, one change
git commit -a -m 'Prep for edition.'
# go to Cargo.toml and set edition keyword
cargo +beta build
```

But even though `cargo fix` completes without warnings, the build is giving me:

```
   Compiling integrity-checker v0.1.0 (/Users/elliott/Programming/Rust/integrity-checker)                                                   
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)                      
 --> src/error.rs:2:5                                                                                                                       
  |                                                                                                                                         
2 | use ignore;                                                                                                                             
  |     ^^^^^^ not an extern crate passed with `--extern`                                                                                   
  |                                                                                                                                         
note: this import refers to the built-in attribute imported here                                                                            
 --> src/error.rs:2:5                                                                                                                       
  |                                                                                                                                         
2 | use ignore;                                                                                                                             
  |     ^^^^^^                                                                                                                              
                                                                                                                                            
error: aborting due to previous error                                                                                                       
                                                                                                                                            
For more information about this error, try `rustc --explain E0658`.                                                                         
error: Could not compile `integrity-checker`.                                                                                               

To learn more, run the command again with --verbose.
```

For posterity I've saved the result of having applied cargo fix here:

https://github.com/elliottslaughter/integrity-checker/tree/rust-2018

```
$ rustc +beta --version
rustc 1.31.0-beta.20 (8940af3ce 2018-11-30)
$ cargo +beta --version
cargo 1.31.0-beta (339d9f9c8 2018-11-16)
```

**Comment by petrochenkov** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/56326

**Comment by ehuss** [comment]
@petrochenkov This issue seems a little different because it does not involve edition idioms or migration lints.  A smaller example, assume you are writing new code in 2018 from scratch: 

```
cargo +beta new foo --lib
cd foo
cargo +beta new ignore --lib
echo 'ignore = {path = "ignore"}' >> Cargo.toml
echo 'use ignore;' >> src/lib.rs
cargo +beta check
```

The error message (as shown above) on current beta is somewhat confusing.  If you're not aware that `use ignore` is attempting to import both an extern crate and an attribute from the standard prelude, as a user I would be thoroughly flummoxed.  It doesn't help that `ignore` *is* passed in with `--extern` and the word "only" may not be clear enough.

Perhaps the fix for this and #56326 is the same, but that issue is currently marked as an idiom lint, but this affects "normal" code.

**Comment by petrochenkov** [comment]
Ultimately, the fix is to stabilize uniform paths (https://github.com/rust-lang/rust/issues/56417), so that the feature gate error is no longer reported.
