### ISSUE TITLE
1.98 beta regression due to name collision with `splat`

### ISSUE THREAD

**Issue by theemathas** [rust-lang/rust#159428]
This regression was found by the 1.98 beta crater run.

```
[INFO] [stdout] error[E0659]: `splat` is ambiguous
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/finite-wasm-0.4.0/src/instruction_categories.rs:450:78
[INFO] [stdout]     |
[INFO] [stdout] 450 |     cvtop_partial, extractlane, load, loadlane, r#const, relop, replacelane, splat, store,
[INFO] [stdout]     |                                                                              ^^^^^ ambiguous name
[INFO] [stdout]     |
[INFO] [stdout]     = note: ambiguous because of a name conflict with a builtin attribute
[INFO] [stdout]     = note: `splat` could refer to a built-in attribute
[INFO] [stdout] note: `splat` could also refer to the macro defined here
[INFO] [stdout]    --> /opt/rustwide/cargo-home/registry/src/index.crates.io-1949cf8c6b5b557f/finite-wasm-0.4.0/src/instruction_categories.rs:394:1
[INFO] [stdout]     |
[INFO] [stdout] 394 | / macro_rules! splat {
[INFO] [stdout] 395 | |     ($generator:ident) => {
[INFO] [stdout] 396 | |         $generator! {
[INFO] [stdout] 397 | |             V128.splat = visit_i8x16_splat | visit_i16x8_splat | visit_i32x4_splat
[INFO] [stdout] ...   |
[INFO] [stdout] 400 | |     };
[INFO] [stdout] 401 | | }
[INFO] [stdout]     | |_^
[INFO] [stdout] 
[INFO] [stdout] 
[INFO] [stdout] For more information about this error, try `rustc --explain E0659`.
```

* https://crater-reports.s3.amazonaws.com/beta-1.98-4/1.98.0-beta.1/reg/near-vm-engine-universal-0.17.0/log.txt

Presumably regressed by #157605, which implemented the `#[splat]` syntax. cc @teor2345, @JonathanBrouwer 

See also #159429, which is a similar regression.

**Comment by JonathanBrouwer** [comment]
Also here, has been fixed upstream in the only affected crate: https://github.com/near/finite-wasm/commit/132f5bc79da054ba56c4d6dba899ca6eccac0cd3
We can either decide to accept this, or to rename this attribute to `#[rustc_splat]`. What is the preferred solution?
I'm happy to make a rename PR if needed, should be trivial

**Comment by teor2345** [comment]
Until we decide, we'll need to hold off on publishing an upcoming "call for experiment" blog post that uses `#[splat]`.

I have a weak preference for keeping the current spelling. If we rename it, we'll need to update a bunch of examples and macro code for splat and the blog post, wait for the rename to merge to rustc, and then wait for the rename nightly to be deployed to the playground.

But nothing has been published yet. So if it is the convention to rename, we'll do the work to rename it across those repositories and blog draft, and hold off on the blog post until after deployment to the playground.

**Comment by jieyouxu** [comment]
I think this is https://github.com/rust-lang/rust/issues/134963 again?

**Comment by teor2345** [comment]
Note that this rename will also require updates to:
- [x] https://github.com/rust-lang/rustc-demangle/blob/f36e2988643d7db47a6aa6e328cc7ffd61343651/src/v0.rs#L909
  - https://github.com/rust-lang/rustc-demangle/pull/93
- [x] https://github.com/rustfoundation/overloading-macros
- [x] https://github.com/rustfoundation/overloading-examples
- [x] an unpublished "call for experimentation" blog post

I'm happy to do the rename if that's the decision, I'd just like to wait for #159629 and #158890 to clear the merge queue first.

**Comment by workingjubilee** [comment]
Typically we do indeed rename to reduce collisions as a first step to mitigation when something is going to only be usable on nightly anyways, or if not that, then we do a revert on beta to let updates get more time to propagate, etc. We're more assertive about picking our desired names and saying "damn the consequences" when shipping a feature to stable.

I've only been hesitant here to pipe up and say as much because it's Literally 1 Crate for each case, so on some level I'm inclined towards your reluctance. On the other hand it's Literally 2 Crates for... something that won't affect stable. It's not like they get something in exchange when Rust 1.98 lands, as they'd have to use nightly to benefit. And for `vers-vecs`, it actually has reverse-dependents that aren't "basically the same thing".

**Comment by workingjubilee** [comment]
T-compiler discussed this today and the inclination amongst those attending was indeed towards a rename: [#t-compiler/meetings > &#91;weekly&#93; 2026-07-23 @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202026-07-23/near/612372766)

**Comment by teor2345** [comment]
Thanks! I am considering alternatives like `rustc_splat`, `splat_v1`, and ~~`splat_arg`~~. I'm hoping to work on this today.

@rustbot claim

Edit:
- [splat_arg](https://github.com/search?q=splat_arg+language%3ARust+&type=code) is a reasonably common function name in Rust code, so it seems risky
- arg_splat could be ok, if rustc suggests arg_splat for splat

**Comment by JonathanBrouwer** [comment]
I'd prefer rustc_splat as other names have a higher risk of conflicting with users. This also matches what we did with #[align]

**Comment by jieyouxu** [comment]
If we are going to do the rename, please use reserved `#[rustc*]`-prefix attribute names which cannot regress stable code. `#[splat_v1]` or `#[arg_splat]` or `#[splat_arg]` still regresses *new* user code if they re-export a `splat_v1` macro etc.

**Comment by teor2345** [comment]
Thanks for clarifying, that wasn't clear to me from the ticket and some of the [earlier discussions](https://rust-lang.zulipchat.com/#narrow/channel/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202026-07-23/near/612380593).

I'll fix the PR on Monday, it's mostly automated so it's not a lot of work.

**Comment by jieyouxu** [comment]
More specifically, see #134963, which describes this (unfortuately) current quirk

**Comment by jieyouxu** [comment]
> If we are going to do the rename, please use reserved `#[rustc*]`-prefix attribute names which cannot regress stable code. `#[splat_v1]` or `#[arg_splat]` or `#[splat_arg]` still regresses _new_ user code if they re-export a `splat_v1` macro etc.

And just to be clear: *deliberate* FCP on accepting breakage from name collisions from adding `#[splat]` is okay, we just don't want to unintentionally regress stable code ~~while splat is still an unstable attribute. [^1]~~

[^1]: Well, basically, just make sure it's deliberate not accidental

**Comment by jieyouxu** [comment]
> Note that this rename will also require updates to:

Also `src/doc/rustc/src/symbol-mangling/v0.md` but that can go after the main rename.

**Comment by teor2345** [comment]
I missed a renaming in an error message, no backport needed because the error message only appears on nightly #160244

**Comment by apiraino** [comment]
closing since #159817 has been merged
