### PR TITLE
Don't byteswap Fingerprints when encoding

### LINKED ISSUE #42239: Mips (big endian) gives "undefined reference to `std::rt::lang_start'"
Attempting to compile this example program `foo.rs` using a nightly compiler:
```rust
fn main() {}
```

On a native mips big endian machine gives me this:
```
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-L" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib" "foo.0.o" "-o" "foo" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib/libstd-8bd0331885bb8f82.rlib" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib/librand-c59b047c329fc869.rlib" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib/libpanic_unwind-8b5a5d5d9b47b90e.rlib" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib/libcollections-940fff481f9db1f7.rlib" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib/liballoc-00bc69f25a7886ed.rlib" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib/liballoc_system-8a70e0fa55025ef9.rlib" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib/libunwind-6f736b1bf227d828.rlib" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib/liblibc-0d4b94d34314ddab.rlib" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib/libstd_unicode-27c6703fdb4bd5ba.rlib" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib/libcore-f7c6aa272ea55579.rlib" "/usr/local/lib/rustlib/mips-unknown-linux-gnu/lib/libcompiler_builtins-93f6c14c48cd2162.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util"
  = note: foo.0.o: In function `main':
          foo.cgu-0.rs:(.text.main+0x34): undefined reference to `std::rt::lang_start'
          collect2: error: ld returned 1 exit status


error: aborting due to previous error(s)
```

If I compile `foo.rs` to an object and dump the symbols, I see that the hash for `lang_start` is different between the object and the rlib file:
```
$ objdump -t foo.o | grep lang_start
00000000         *UND*  00000000 _ZN3std2rt10lang_start17h826655afc17b8ea3E

$ objdump -t /usr/local/lib/rustlib/mips-unknown-linux-gnu/lib/libstd-8bd0331885bb8f82.rlib | grep lang_start
00000000 l    d  .text._ZN3std2rt10lang_start17h5492aeb665e2d414E       00000000 .text._ZN3std2rt10lang_start17h5492aeb665e2d414E
00000000 g     F .text._ZN3std2rt10lang_start17h5492aeb665e2d414E       00000aec _ZN3std2rt10lang_start17h5492aeb665e2d414E
```

After some debugging, I managed to work out that the value of `tcx.def_path_hash(def_id)` for `lang_start` passed to the `TypeIdHasher` in `rustc_trans::back::symbol_names::get_symbol_hash` is byteswapped when run natively compared to running on an x86 -> mips cross compiler. I couldn't work out where this value originally comes from, but hopefully someone here knows. :)

I also tried using a stable compiler, but it failed with the issue #41471 before getting to this stage.

### PR DESCRIPTION
**Pull request by jcowgill**
Byteswapping Fingerprints when encoding is unnessesary and breaks if the Fingerprint is later decoded on a machine with different endianness to the one it was encoded on.

Fixes #42239

This PR fixes a regression caused by #42082. @michaelwoerister

### CODE REVIEW

File: src/librustc/ich/fingerprint.rs [hunk 1]
```diff
@@ -40,16 +40,16 @@ impl Fingerprint {
...
 }
 
 impl Decodable for Fingerprint {
     #[inline]
     fn decode<D: Decoder>(d: &mut D) -> Result<Fingerprint, D::Error> {
-        let _0 = u64::from_le(d.read_u64()?);
-        let _1 = u64::from_le(d.read_u64()?);
+        let _0 = d.read_u64()?;
+        let _1 = d.read_u64()?;
         Ok(Fingerprint(_0, _1))
```
Comment (eddyb) [inline src/librustc/ich/fingerprint.rs]: Can you move it to use `#[derive]`? Looks like it's what deriving would produce, now.

**Comment by michaelwoerister** [comment]
Thanks for the PR! I'll review it as soon as I find the time.

**Comment by nagisa** [comment]
> Byteswapping Fingerprints when encoding is unnessesary and breaks if the Fingerprint is later decoded on a machine with different endianness to the one it was encoded on.

This explanation doesn’t exactly make any sense to me. It seems to me like going from machine specific to low endian in encoded form to machine specific after decoding is in fact the correct way to do this.

Maybe instead it is a problem with the comment just below that says:

> The bytes returned bytes the Blake2B hasher are always little-endian.

or something like that?

**Comment by est31** [comment]
> This explanation doesn’t exactly make any sense to me. It seems to me like going from machine specific to low endian in encoded form to machine specific after decoding is in fact the correct way to do this.

Not if `Decoder::read_u64` and `Encoder::emit_u64` already do the host to network conversion themselves. And apparently they [do precisely that](https://github.com/rust-lang/rust/blob/e0cc22b4bae8007c59fbe58f2c104ecd743d746a/src/libserialize/leb128.rs#L54-L69) (that function is used by a macro in [the implementation](https://github.com/rust-lang/rust/blob/e0cc22b4bae8007c59fbe58f2c104ecd743d746a/src/libserialize/opaque.rs#L201-L203) of read_u64).

So if you are doing a superfluous conversion host <-> little endian, it won't mean any problems if you serialize and deserialize on the same host, but if you serialize on a host with one byte order, and serialize on a host with another, you will get the order mixed up.

> Maybe instead it is a problem with the comment just below that says:

Nope, thats a different thing. The comment is correct, [we actually encode](https://github.com/rust-lang/rust/blob/e0cc22b4bae8007c59fbe58f2c104ecd743d746a/src/librustc_data_structures/blake2b.rs#L235-L242) to little endian. But the code smells bad, it shouldn't have to use unsafe, but rather something safe with (hopefully) equivalent performance.

**Comment by michaelwoerister** [comment]
Thanks again, @jcowgill!

Some comments:
* In general it is definitely better to not do any endianess conversion in these encode/decode methods. The `Encoder` implementation should take care of that (and the `OpaqueEncoder` does by storing numbers in the endian-independent leb128 format). I overlooked that when introducing this change.
* @eddyb is right, we could just add `RustcEncodable, RustcDecodable` to `Fingerprint` at this point.
* It's a bit strange that byte-swapping should break anything here, but here is what's going on (using `291u16` as an example):
  * If `HOST` is big-endian we encode `291 == 0x01 0x23` to `8961 = 0x23 0x01` and that to `leb128(8961)`.
    * If decoding on big-endian again we convert `leb128(8961)` to `8961 = 0x23 0x01` and then to `291 = 0x01 0x23` by swapping the bytes again.
    * If decoding on little-endian, we convert `leb128(8961)` to `8961 = 0x01 0x23` (!) and then we are not swapping bytes, ending up with the wrong value.

Little- to big-endian host is analogous.

So this gets an r+ from me once @eddyb's suggestion is implemented.

**Comment by jcowgill** [comment]
Hi, I've now changed the fix to use `RustcEncodable` and `RustcDecodable`. I just had to make sure things were still working :)

**Comment by michaelwoerister** [comment]
:tada:

**Comment by Mark-Simulacrum** [comment]
@bors retry
 - #40474

```
[00:09:29] curl: (56) SSLRead() return error -36
```
