### PR TITLE
Update to fix regression 90319 and correctly emit overflow errors when not inside an error reporting context

### LINKED ISSUE #90319: regression: ICE ErrorReporting Overflow should not reach report_selection_err call
* https://crater-reports.s3.amazonaws.com/beta-1.57-1/beta-2021-10-22/reg/syn-next-1.0.0-rc4/log.txt

```
[INFO] [stdout] error: internal compiler error: compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs:846:17: ErrorReporting Overflow should not reach `report_selection_err` call
```

This crate already failed to [build on 1.56](https://crater-reports.s3.amazonaws.com/beta-1.57-1/1.56.0/reg/syn-next-1.0.0-rc4/log.txt), but it seems worth trying to fix the ICE in case it affects other code as well.

### PR DESCRIPTION
**Pull request by tom7980**
This fixes #90319 to correctly report overflow errors instead of an ICE while also keeping the functionality of not reporting excess overflow errors during error reporting and method suggestions.

cc: @Mark-Simulacrum @estebank @dtolnay

### CODE REVIEW

**Comment by tom7980** [comment]
Note that this fixes the regression only but I think perhaps we could do with a better error message for when we implement a trait on a wrapper holding an `&T` which has a trait bound for a wrapper holding a `T` as this is valid as long as you implement the trait for the wrapper type holding a T I believe. 

Unfortunately I'm not sure I'm well versed enough in the type inference engine to understand where the best place to check this is.

**Comment by tom7980** [comment]
r? @Mark-Simulacrum 

Not sure if Matt is reviewing PR's but this one keeps hitting merge conflicts so would like to merge it before I have to rebase it again haha

**Comment by jackh726** [comment]
I remember seeing #89576, but not thinking too much about it.

Thinking about this a bit, I'm wondering if the fix applied there and here are not the best fix. I'm wondering if a *better* fix would be to delay omitting *all* overflow errors. As shown in #91430, there are cases where we don't really need to emit overflow errors — though, we need to be really careful that we don't accidently *not* emit them when we should.

I'll look a little bit closer at this PR to think about if this really a band-aid fix we want to pursue right now.

**Comment by tom7980** [comment]
I think you're right that we still want to emit overflow errors when we should, perhaps it should be a delay_span_bug instead so that we still emit overflow if we get to the end of typechecking however I'm not sure if the reason we emit overflow errors unconditionally at the moment is that there are times where if we don't then the compiler hangs. 

Currently I know of the two paths to get to this error and it's during a `probe_op` to suggest conversion methods where all errors are ignored because we're only interested in whether the method does the conversion for an error suggestion. 

Then there is the second path here which happens during typechecking trait bounds where honestly we do want to emit the overflow error because the trait is overflowing without a concrete implementation for the trait on the type you're calling the method on so it'll never compile anyway. 

Let me know what you think, you could well be right that we're being over eager on overflow errors but I think they are one error that perhaps we should be due to the nature of them making code hit infinite loops

File: compiler/rustc_typeck/src/check/demand.rs [hunk 1]
```diff
@@ -143,7 +143,6 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             Err(e) => e,
         };
 
-        self.set_tainted_by_errors();
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/demand.rs:146]: Why is this removed?

File: compiler/rustc_typeck/src/check/method/probe.rs [hunk 2]
```diff
@@ -1469,7 +1470,7 @@ impl<'a, 'tcx> ProbeContext<'a, 'tcx> {
         let cause = traits::ObligationCause::misc(self.span, self.body_id);
         let predicate = ty::Binder::dummy(trait_ref).to_poly_trait_predicate();
         let obligation = traits::Obligation::new(cause, self.param_env, predicate);
-        traits::SelectionContext::new(self).select(&obligation)
+        traits::SelectionContext::with_suggestion(self, self.is_suggestion.0).select(&obligation)
```
Comment (estebank) [inline compiler/rustc_typeck/src/check/method/probe.rs:1473]: Wouldn't modifying the selection context before `select`ing to be `tainted_by_errors` also work instead of adding a new field?

**Review by estebank — COMMENTED** [review]
Great on fixing the ICE! But I have a couple of nitpicks :)

File: compiler/rustc_typeck/src/check/demand.rs (hunk 1 above)
Comment (tom7980) [reply compiler/rustc_typeck/src/check/demand.rs:146]: I actually moved it to the top of `probe_for_return` in the probe module as having it in this location meant that it was being hit when we weren't in an error context during trait bound fulfillment. 

Moving it to the new location meant it only got set when we were actively looking for a method suggestion in an error.

File: compiler/rustc_typeck/src/check/method/probe.rs (hunk 2 above)
Comment (tom7980) [reply compiler/rustc_typeck/src/check/method/probe.rs:1473]: Yea so looking back at it I'm not sure I even need this new field I think I actually just needed to move where I set that we were tainted by errors. I'll see if I can change it this evening so we don't need the new selection context field.

Comment (tom7980) [reply compiler/rustc_typeck/src/check/method/probe.rs:1473]: I think what's happen is I wanted a way to distinguish inside the selection context itself whether we were creating a suggestion but forgetting that it derefs down into the function context that spawned it which already has the `tainted_by_errors` flag

File: compiler/rustc_typeck/src/check/method/probe.rs [hunk 3]
```diff
@@ -262,6 +262,7 @@ impl<'a, 'tcx> FnCtxt<'a, 'tcx> {
             "probe(self_ty={:?}, return_type={}, scope_expr_id={})",
             self_ty, return_type, scope_expr_id
         );
+        self.set_tainted_by_errors();
```
Comment (tom7980) [inline compiler/rustc_typeck/src/check/method/probe.rs:265]: @estebank I moved it here because we only hit it when we're in an error reporting context here as `probe_for_return_type` is only used to generate suggestions whereas in the old location we could hit the `set_tainted_by_errors` call when we weren't doing error reporting

File: compiler/rustc_typeck/src/check/method/probe.rs (hunk 2 above)
Comment (tom7980) [reply compiler/rustc_typeck/src/check/method/probe.rs:1473]: Had a look at it this evening - it starts ICEing again if I rely on `is_tainted_by_errors()` check in the overflow check I expect that the function context is set as `tainted_by_errors` elsewhere in the typechecking stage before reporting fulfilment errors so it reports an incorrect overflow error. 

I need to confirm this first however so will do some more digging.

File: compiler/rustc_typeck/src/check/demand.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_typeck/src/check/demand.rs:146]: Does *keeping* this call to `set_tainted_by_errors` cause any undesired effect?

File: compiler/rustc_typeck/src/check/method/probe.rs (hunk 3 above)
Comment (estebank) [reply compiler/rustc_typeck/src/check/method/probe.rs:265]: If you look at the code in `demand_coerce_diag` once we move after the `try_coerce` we are always in an error reporting pathway.

File: compiler/rustc_typeck/src/check/demand.rs (hunk 1 above)
Comment (tom7980) [reply compiler/rustc_typeck/src/check/demand.rs:146]: I haven't tried it but can test it out - I think you're right that it can be kept there, I'm fairly sure that both spot I've tried it in are in error reporting pathways anyway. 

I think the bigger issue is that `set_tainted_by_errors` is being called elsewhere before this point due to name resolution being unable to resolve `Thing`

**Comment by tom7980** [comment]
Is there a good way to push a commit as a second option for a change? I did some work on this tonight as I don't really like having to rely on `is_tainted_by_errors()` due to it being set between passes (resolution then type checking) and I would like to push the changes so people can decide which option work better.

**Comment by estebank** [comment]
You can push to another branch and I think there's a way to see a diff between two branches on GH's ui.

**Comment by tom7980** [comment]
Okay I've created a new branch with the changes I'd prefer to make the compare is here - I would prefer to make the changes to the InferCtx because `set_tainted_by_errors` is likely to be set earlier between passes i.e. in this case name resolution and type checking, whereas I want to be able to set a flag when we error in the middle of a pass and need to supress new ones. 

Let me know what you think, I personally believe this is more robust & can be easily lifted out if we decide to change how we handle overflow errors in type checking.

https://github.com/tom7980/rust/compare/issue-90319-fix...tom7980:issue-90319-fix-2

**Comment by jackh726** [comment]
Going to go ahead and r? @estebank, since they reviewed the previous PR and have done a partial review here.

I do think changing how we propagate overflow errors is something work experimenting with, but that's probably a bigger task and not worth blocking this.

File: compiler/rustc_typeck/src/check/demand.rs (hunk 1 above)
Comment (estebank) [reply compiler/rustc_typeck/src/check/demand.rs:146]: Can we try getting this back in to see the effect?

File: compiler/rustc_typeck/src/check/method/probe.rs (hunk 2 above)
Comment (estebank) [reply compiler/rustc_typeck/src/check/method/probe.rs:1473]: That sounds like a reasonable avenue.

Comment (tom7980) [reply compiler/rustc_typeck/src/check/method/probe.rs:1473]: I can put it back however in my other implementation of this I don't rely on it anymore instead preferring to use a flag in the inferctx, I've linked my other implementation in the PR at the bottom which I think is more robust

Comment (tom7980) [reply compiler/rustc_typeck/src/check/method/probe.rs:1473]: ^ this was meant to be in reply to the other comment - will push some different changes tomorrow to review

File: compiler/rustc_typeck/src/check/demand.rs (hunk 1 above)
Comment (tom7980) [reply compiler/rustc_typeck/src/check/demand.rs:146]: Replied in the wrong place - see my comment on the other review but I'm going to push a change tomorrow that I think works better

**Comment by Dylan-DPC** [comment]
closing this based on comment by author https://github.com/rust-lang/rust/pull/94391#issuecomment-1051947057
