### PR TITLE
Add support for storing code model to LLVM module IR

### PR DESCRIPTION
**Pull request by kubo39**
This patch avoids undefined behavior by linking different object files.
Also this would it could be propagated properly to LTO.

See https://reviews.llvm.org/D52322 and https://reviews.llvm.org/D52323.

### CODE REVIEW

File: src/librustc_codegen_llvm/context.rs [hunk 1]
```diff
@@ -99,6 +99,16 @@ fn to_llvm_tls_model(tls_model: TlsModel) -> llvm::ThreadLocalMode {
     }
 }
 
+fn to_llvm_code_model(code_model: CodeModel) -> llvm::CodeModel {
```
Comment (petrochenkov) [inline src/librustc_codegen_llvm/context.rs:102]: `fn to_llvm_code_model` already exists in `src\librustc_codegen_llvm\back\write.rs`.

File: src/librustc_codegen_llvm/back/write.rs [hunk 2]
```diff
@@ -108,7 +108,7 @@ fn to_llvm_relocation_model(relocation_model: RelocModel) -> llvm::RelocModel {
     }
 }
 
-fn to_llvm_code_model(code_model: Option<CodeModel>) -> llvm::CodeModel {
+pub fn to_llvm_code_model(code_model: Option<CodeModel>) -> llvm::CodeModel {
```
Comment (nagisa) [inline src/librustc_codegen_llvm/back/write.rs:111]: Consider `pub(crate)` or just `crate`.

File: src/rustllvm/PassWrapper.cpp [hunk 3]
```diff
@@ -1163,6 +1163,20 @@ extern "C" void LLVMRustSetModulePIELevel(LLVMModuleRef M) {
   unwrap(M)->setPIELevel(PIELevel::Level::Large);
 }
 
+//  Linking object files with different code models is undefined behavior
+//  because the compiler would have to generate additional code (to span
+//  longer jumps) if a larger code model is used with a smaller one.
+//  Therefore we will treat attempts to mix code models as an error.
```
Comment (nagisa) [inline src/rustllvm/PassWrapper.cpp:1169]: This last sentence is super interesting, but it is not super clear where the "error" comes from. Does it happen at LTO time? Quick skim of the linked differentials does not answer it, you need to read the comments, so it would be great if more about this was said here.

I would also probably move it to this function’s call location as people are way more likely to read it in `librustc_codegen_llvm` than here.

**Review by nagisa — COMMENTED** [review]
r? @nagisa 

r=me after `pub` → `crate`

File: src/rustllvm/PassWrapper.cpp (hunk 3 above)
Comment (kubo39) [reply src/rustllvm/PassWrapper.cpp:1169]: > This last sentence is super interesting, but it is not super clear where the "error" comes from. Does it happen at LTO time? Quick skim of the linked differentials does not answer it, you need to read the comments, so it would be great if more about this was said here.

Thank you for having a look, and sorry for not clear that.
I checked LLVM and IRMover works both link time and LTO time, so this happends either.However, this error won't happen at rustc comiple time, so I would just remove this line.

**Comment by JohnTitor** [comment]
Failed in https://github.com/rust-lang/rust/pull/74054#issuecomment-653875675, @bors r-

**Comment by kubo39** [comment]
CI shows:

```
failures:

---- [codegen] codegen/codemodels.rs#MODEL-KERNEL stdout ----

error in revision `MODEL-KERNEL`: compilation failed!
status: exit code: 1
command: "/checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/codegen/codemodels.rs" "-Zthreads=1" "--cfg" "model_kernel" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/i686-unknown-linux-gnu/test/codegen/codemodels.MODEL-KERNEL" "-Crpath" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/i686-unknown-linux-gnu/native/rust-test-helpers" "--target=x86_64-unknown-linux-gnu" "-C" "code-model=kernel" "-L" "/checkout/obj/build/i686-unknown-linux-gnu/test/codegen/codemodels.MODEL-KERNEL/auxiliary" "--emit=llvm-ir"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-gnu` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.

------------------------------------------

error in revision `MODEL-MEDIUM`: compilation failed!
status: exit code: 1
command: "/checkout/obj/build/i686-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/codegen/codemodels.rs" "-Zthreads=1" "--cfg" "model_medium" "-C" "prefer-dynamic" "--out-dir" "/checkout/obj/build/i686-unknown-linux-gnu/test/codegen/codemodels.MODEL-MEDIUM" "-Crpath" "-Cdebuginfo=0" "-Zunstable-options" "-Lnative=/checkout/obj/build/i686-unknown-linux-gnu/native/rust-test-helpers" "--target=x86_64-unknown-linux-gnu" "-C" "code-model=medium" "-L" "/checkout/obj/build/i686-unknown-linux-gnu/test/codegen/codemodels.MODEL-MEDIUM/auxiliary" "--emit=llvm-ir"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-linux-gnu` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.

------------------------------------------


failures:
    [codegen] codegen/codemodels.rs#MODEL-KERNEL
    [codegen] codegen/codemodels.rs#MODEL-MEDIUM

test result: FAILED. 165 passed; 2 failed; 42 ignored; 0 measured; 0 filtered out
```

**Comment by kubo39** [comment]
What should I do next?

**Comment by nagisa** [comment]
@bors r+ rollup=never

@kubo39 Sorry, I’ve been busy with work stuff and couldn't dedicate any time to look at this again until now.

**Comment by Manishearth** [comment]
Is this rollup=never because it has to be or because we expect it to perhaps fail a rollup? There's a new rollup=iffy for that

**Comment by nagisa** [comment]
Yeah it was `rollup=never` before iffy existed :)

@bors rollup=iffy

**Comment by Manishearth** [comment]
Expected so, wanted to confirm. Thanks!

**Comment by Manishearth** [comment]
@bors r-

https://github.com/rust-lang/rust/pull/74243#issuecomment-657084736

**Comment by Dylan-DPC** [comment]
@kubo39 thanks for the effort but unfortunately I've to close this pr due to inactivity. If you wish and have figured out the failure pasted earlier, you can submit a new PR with the fix and we can get it reviewed. Thanks for taking the time to contribute.
