### ISSUE TITLE
E0621 Dataflow can point to wrong location causing lifetime obligation

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#98470]
[Given the following code:](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=df287459c190ec33a3039f27809383b8) 

```rust
struct HasLife<'a>(&'a str);
struct Store<'a>(Vec<&'a HasLife<'a>>);

impl<'a> Store<'a> {
    pub fn run(x: &HasLife<'a>) -> &'a str {
        let mut store = Store(Vec::new());
        store.add_inner(x);
        store.0[0].0
    }
    
    fn add_inner(&mut self, x: &'a HasLife<'a>) {
        self.0.push(x);
    }
}
```

The current output is:

```
error[E0621]: explicit lifetime required in the type of `x`
 --> src/lib.rs:8:9
  |
5 |     pub fn run(x: &HasLife<'a>) -> &'a str {
  |                   ------------ help: add explicit lifetime `'a` to the type of `x`: `&'a HasLife<'a>`
...
8 |         store.0[0].0
  |         ^^^^^^^^^^^^ lifetime `'a` required
```

Ideally the output should look like:

```
error[E0621]: explicit lifetime required in the type of `x`
 --> src/lib.rs:8:9
  |
5 |     pub fn run(x: &HasLife<'a>) -> &'a str {
  |                   ------------ help: add explicit lifetime `'a` to the type of `x`: `&'a HasLife<'a>`
...
7 |         store.add_inner(x);
  |         ^^^^^^^^^^^^^^^^^^^ lifetime `'a` required
...
11|     fn add_inner(&mut self, x: &'a HasLife<'a>) 
  |                                ^^^^^^^^^^^^^^^^ help, because `Store::add_inner` requires `&'a HasLife<'a>`
```

[- If you remove the return from `Store::run` then it just works](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9aaceefe329b4d48519f13548e6b9e53)
[- If you make `pub fn run(&mut self, x: &HasLife<'a>) {self.add_inner(x)}`, you get a good E0621 Error](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=f83dfd1e3ae633d5573933542c96d8a7)

Build using the Nightly version: 1.63.0-nightly (2022-06-23 43347397f7c5ca9a670a)
