### ISSUE TITLE
Unresolved import in glob imported modules

### ISSUE THREAD

**Issue by KyleMayes** [rust-lang/rust#32089]
The latest nightly broke some imports in [my project](https://travis-ci.org/KyleMayes/easy-plugin/builds/114147602) that were working previously.

Here is a minimal example (spread out over three files):

```rust
// src/lib.rs

mod one;
pub use self::one::*;

mod two;
pub use self::two::*;

pub type Type = i32;
```

```rust
// src/one.rs

use super::{Type};
```

```rust
// src/two.rs

use super::{Type};
```

The issue is only when there is more than one of these types of imports. I'm not sure if this is a bug or I  have been relying on incorrect behavior until now.

### Meta

```
rustc 1.9.0-nightly (52e0bda64 2016-03-05)
binary: rustc
commit-hash: 52e0bda644823089f16795cc9e071cf827b4810b
commit-date: 2016-03-05
host: x86_64-unknown-linux-gnu
release: 1.9.0-nightly
```

**Comment by retep998** [comment]
This may be due to https://github.com/rust-lang/rust/pull/31726

**Comment by alexcrichton** [comment]
Indeed looks [broken on nightly](https://play.rust-lang.org/?gist=1b65c40a810f3d03b42c&version=nightly)!

cc @jseyfried

**Comment by jseyfried** [comment]
@KyleMayes Thanks for the report and minimal example. This is a bug.

This was caused by #31726. I diagnosed the problem and will fix it ASAP (<1 hr).
