### PR TITLE
Correctly deny late-bound lifetimes from parent in anon consts and TAITs

### LINKED ISSUE #115474: ice `Not enough bound vars: BoundRegion `
### Code

```Rust
pub trait Trait {}

pub type Foo = impl for<'a> Trait<'a, Assoc = impl Copy + 'a>;
```

### Meta

`rustc --version --verbose`:
```
361f8ba847af0288b1beb3b84f6b7b4d3850bb43
```

### Error output

```
error[E0658]: `impl Trait` in type aliases is unstable
 --> D4EEC737DBC306A9873DFECBC855175357C17FC8247010DD5EE8279A9AEE7023.rs:3:16
  |
3 | pub type Foo = impl for<'a> Trait<'a, Assoc = impl Copy + 'a>;
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information
  = help: add `#![feature(type_alias_impl_trait)]` to the crate attributes to enable

error[E0658]: `impl Trait` in type aliases is unstable
 --> D4EEC737DBC306A9873DFECBC855175357C17FC8247010DD5EE8279A9AEE7023.rs:3:47
  |
3 | pub type Foo = impl for<'a> Trait<'a, Assoc = impl Copy + 'a>;
  |                                               ^^^^^^^^^^^^^^
  |
  = note: see issue #63063 <https://github.com/rust-lang/rust/issues/63063> for more information
  = help: add `#![feature(type_alias_impl_trait)]` to the crate attributes to enable

error[E0601]: `main` function not found in crate `D4EEC737DBC306A9873DFECBC855175357C17FC8247010DD5EE8279A9AEE7023`
 --> D4EEC737DBC306A9873DFECBC855175357C17FC8247010DD5EE8279A9AEE7023.rs:3:63
  |
3 | pub type Foo = impl for<'a> Trait<'a, Assoc = impl Copy + 'a>;
  |                                                               ^ consider adding a `main` function to `D4EEC737DBC306A9873DFECBC855175357C17FC8247010DD5EE8279A9AEE7023.rs`

error[E0107]: trait takes 0 lifetime arguments but 1 lifetime argument was supplied
 --> D4EEC737DBC306A9873DFECBC855175357C17FC8247010DD5EE8279A9AEE7023.rs:3:29
  |
3 | pub type Foo = impl for<'a> Trait<'a, Assoc = impl Copy + 'a>;
  |                             ^^^^^---------------------------- help: remove these generics
  |                             |
  |                             expected 0 lifetime arguments
  |
note: trait defined here, with 0 lifetime parameters
 --> D4EEC737DBC306A9873DFECBC855175357C17FC8247010DD5EE8279A9AEE7023.rs:1:11
  |
1 | pub trait Trait {}
  |           ^^^^^

error[E0220]: associated type `Assoc` not found for `Trait`
 --> D4EEC737DBC306A9873DFECBC855175357C17FC8247010DD5EE8279A9AEE7023.rs:3:39
  |
3 | pub type Foo = impl for<'a> Trait<'a, Assoc = impl Copy + 'a>;
  |                                       ^^^^^ associated type `Assoc` not found
```

### PR DESCRIPTION
**Pull request by compiler-errors**
Reuse the `AnonConstBoundary` scope (introduced in #108553, renamed in this PR to `LateBoundary`) to deny late-bound vars of *all* kinds (ty/const/lifetime) in anon consts and TAITs.

Side-note, but I would like to consolidate this with the error reporting for RPITs (E0657):
https://github.com/rust-lang/rust/blob/c4f25777a08cd64b710e8a9a6159e67cbb35e6f5/compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs#L733-L754 but the semantics about what we're allowed to capture there are slightly different, so I'm leaving that untouched.

Fixes #115474

### CODE REVIEW

File: tests/ui/const-generics/late-bound-vars/in_closure.rs [hunk 1]
```diff
@@ -1,23 +1,13 @@
...
-// this should run-pass
+
+// If we want this to compile, then we'd need to do something like RPITs do,
+// where nested associated constants have early-bound versions of their captured
+// late-bound vars inserted into their generics. This gives us substitutable
+// lifetimes to actually use when borrow-checking the associated const, which is
+// lowered as a totally separate body from its parent. Since this doesn't exist,
+// so we should just error rather than resolving this late-bound var with no
+// binder to actually attach it to, or worse, as a free region that can't even be
+// substituted correctly, and ICEing. - @compiler-errors
```
Comment (compiler-errors) [inline tests/ui/const-generics/late-bound-vars/in_closure.rs:10]: The purpose of this comment is to record a more general solution than what would be needed to fix just this test and its related test (`in_closure.rs` and `simple.rs`) -- the simplest fix for just those tests would be to just go restore behavior of resolving late-bound region captured by anon consts as free regions in the parent function's body, and fix NLL to do the free region -> vid mapping correctly again (#111215 discusses this regression in the way that NLL maps free regions, cc @BoxyUwU).

But, for the record, #79298 never really correctly supported late-bound vars in general positions (i.e. other positions where the const wasn't just referencing a free region in the scope of a body), e.g.:

```rust
// ICEs even on 1.51 after #79298

#![feature(const_generics)] // `generic_const_exprs` after it was renamed.
#![allow(incomplete_features)]

const fn inner<'a: 'a>() -> usize {
    3
}

fn test<'a>() -> [u8; { inner::<'a>() }] {
    [1, 2, 3]
}

fn main() {
    test();
}
```

or in other binders, like:

```
fn test() {
    let x: dyn for<'a> Assoc<Output = [u8; { inner::<'a>() }]>;
}
```

File: tests/ui/type-alias-impl-trait/variance.rs [hunk 2]
```diff
@@ -9,42 +9,36 @@ type NotCapturedEarly<'a> = impl Sized; //~ [o]
 
 type CapturedEarly<'a> = impl Sized + Captures<'a>; //~ [o]
 
+// TAIT does *not* capture `'b`
 type NotCapturedLate<'a> = dyn for<'b> Iterator<Item = impl Sized>; //~ [o]
 
-type CapturedLate<'a> = dyn for<'b> Iterator<Item = impl Sized + Captures<'b>>; //~ [o]
```
[the remark this answers is not in the document]
Comment (oli-obk) [reply tests/ui/type-alias-impl-trait/variance.rs:14]: yea, but I wanted to show that there's only one lifetime in the opaque type, not two.

[the remark this answers is not in the document]
Comment (compiler-errors) [reply tests/ui/type-alias-impl-trait/variance.rs:14]: Well, I think the opaque is just faulty, but errors suppress lints (`rustc_variances_of_opaque`) later on so I have to remove it. I could add it back in a revision or a separate test, with some comment saying "if we ever do support this, then it needs to be `[o, o]`" or something?

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs [hunk 3]
```diff
@@ -216,7 +217,9 @@ impl<'a> fmt::Debug for TruncatedScopeDebug<'a> {
                 .field("s", &"..")
                 .finish(),
             Scope::TraitRefBoundary { s: _ } => f.debug_struct("TraitRefBoundary").finish(),
-            Scope::AnonConstBoundary { s: _ } => f.debug_struct("AnonConstBoundary").finish(),
+            Scope::LateBoundary { s: _, what } => {
+                f.debug_struct("AnonConstBoundary").field("what", what).finish()
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:221]:
```suggestion
                f.debug_struct("LateBoundary").field("what", what).finish()
```

File: compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs [hunk 4]
```diff
@@ -1259,6 +1270,22 @@ impl<'a, 'tcx> BoundVarContext<'a, 'tcx> {
         if let Some(mut def) = result {
             if let ResolvedArg::EarlyBound(..) = def {
                 // Do not free early-bound regions, only late-bound ones.
+            } else if let ResolvedArg::LateBound(_, _, param_def_id) = def
```
Comment (cjgillot) [inline compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:1273]: Both this branch and the next (`if let Some(body_id) = outermost_body`) should only be executed for late-bound variables. Should they both be in an `if let ResolvedArg::LateBound(_, _, param_def_id) = def` to make it clearer?

For my curiosity, what would happen if we made lifetimes in anon-consts `ResolvedArg::Free`?

Comment (compiler-errors) [reply compiler/rustc_hir_analysis/src/collect/resolve_bound_vars.rs:1273]: > For my curiosity [...]

See my comment here https://github.com/rust-lang/rust/pull/115486#discussion_r1314015308, I kinda went into it there -- this idea would, in fact, fix at least tests like `const-generics/late-bound-vars/in_closure.rs` and `const-generics/late-bound-vars/simple.rs`, and was how #79298 worked, afaict.

It doesn't seem like a general solution, though, since when it comes to, e.g., a binder on a where clause like `where for<'a> [(); { /* const that uses 'a */ }]: ...`, it doesn't really make sense to use `ReFree` for that usage of `'a`, since the late-bound region does not originate from the function's generics (and therefore the `fn_sig`'s binder).

This also doesn't lead us towards a correct solution for handling things like `for<const C: usize> [(); C]: ...`, since there's no equivalent notion of a "free" type or const var (nor does it make sense, since they must be substitutable).

**Comment by compiler-errors** [comment]
Another spurious failure? lmao

@bors retry

**Comment by matthiaskrgr** [comment]
Neat, this might have fixed a ton of ices :D
ices
