### PR TITLE
Better closure error message

### LINKED ISSUE #26046: Opaque error message when typechecking closure
**UPDATE:** Mentoring instructions found [in this comment below](https://github.com/rust-lang/rust/issues/26046#issuecomment-305868200).

----

The following code fails because the closure moves out of `vec`, and anything implementing `Fn` only gets a reference to its environment (i.e can't move `self`)

``` rust
fn get_closure() -> Box<Fn() -> Vec<u8>> {
    let vec = vec![1u8, 2u8];

    let closure = move || {
        vec
    };

    Box::new(closure)
}
```

A simple fix that would allow the closure to properly implement `Fn` is to replace `vec` with `vec.clone()` inside the closure. The error message, however, is of no help:

```
error: the trait `core::ops::Fn<()>` is not implemented for the type `[closure <anon>:6:24: 8:6]` [E0277]
<line #> Box::new(closure)
         ^~~~~~~~~~~~~~~~~
```

In cases where the closure is more complex than this trivial example, the error message is no more descriptive than above, making it much more difficult to debug.

I would like to see something more along the lines of:

```
error: the trait `core::ops::Fn<()>` is not implemented for the type `[closure <anon>:6:24: 8:6]`
<line #> note: closure moves out of environment: vec
                                                 ^~~
```

### PR DESCRIPTION
**Pull request by tommyip**
Use tracked data introduced in #42196 to provide a better closure
error message by showing why a closure implements `FnOnce`.

```
error[E0525]: expected a closure that implements the `Fn` trait, but
this closure only implements `FnOnce`
 --> $DIR/issue_26046.rs:4:19
  |
4 |       let closure = move || {
  |  ___________________^
5 | |         vec
6 | |     };
  | |_____^
  |
note: closure is `FnOnce` because it moves the variable `vec` out of
its environment
 --> $DIR/issue_26046.rs:5:9
  |
5 |         vec
  |         ^^^

error: aborting due to previous error(s)
```

Fixes #26046 

r? @nikomatsakis 
cc @doomrobo

### CODE REVIEW

File: src/librustc/traits/error_reporting.rs [hunk 1]
```diff
@@ -640,16 +640,38 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
+                        let infer_tables = match self.tables {
+                            InferTables::Interned(tables) =>
+                                Some(InferTablesRef::Interned(tables)),
+                            InferTables::InProgress(tables) =>
+                                Some(InferTablesRef::InProgress(tables.borrow())),
+                            InferTables::Missing => None,
+                        };
+
+                        if let Some(tables) = infer_tables {
+                            if let Some(&(ty::ClosureKind::FnOnce, Some((span, name)))) =
```
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: This message is specific to `FnOnce`, but similar scenarios can arise in other situations. For example, we could highlight the `x += 1` here and say something like "mutating this variable":

```rust
fn foo<F: Fn()>(f: F) { }
fn main() {
    let mut x = 0;
    foo(|| x += 1); // Error
}
```

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc/traits/error_reporting.rs (hunk 1 above)
Comment (tommyip) [inline src/librustc/traits/error_reporting.rs]: Should we match more cases here or make the error more generic?

Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: Good question. I think it'd be better to match more cases, and keep the message fairly tailored -- there are really only two cases. The closure might be `FnOnce` (in which case we can talk about something being moved) or it might be `FnMut` (in which case we can talk about something being written to).

**Comment by tommyip** [comment]
Updated

File: src/test/ui/closure_context/issue-26046-fn-mut.stderr [hunk 2]
```diff
@@ -0,0 +1,17 @@
+error[E0525]: expected a closure that implements the `Fn` trait, but this closure only implements `FnMut`
+  --> $DIR/issue-26046-fn-mut.rs:14:19
+   |
+14 |       let closure = || {
+   |  ___________________^
+15 | |         num += 1;
+16 | |     };
+   | |_____^
+   |
+note: closure is `FnMut` because it mutates the variable `num` here
```
Comment (nikomatsakis) [inline src/test/ui/closure_context/issue-26046-fn-mut.stderr]: slick

File: src/librustc/traits/error_reporting.rs [hunk 3]
```diff
@@ -640,16 +640,43 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
+                                    err.span_note(span, &format!(
+                                        "closure is `FnOnce` because it moves the \
+                                         variable `{}` out of its environment", name));
+                                },
+                                Some(&(ty::ClosureKind::FnMut, Some((span, name)))) => {
+                                    err.span_note(span, &format!(
+                                        "closure is `FnMut` because it mutates the \
+                                         variable `{}` here", name));
+                                },
+                                _ => {}
```
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: One minor point -- in this arm, we emit *neither* the new note nor the old one. Seems like the old one might still be helpful?

Actually, maybe we should *always* emit the old note -- but instead of a note, just make it a `span_label`? Seems like it's useful information either way.  In other words, the old note tells you "why it has to be `Fn`", and the new note tells you why it cannot be...

If you agree, maybe move the body of the `else` below out and above this `if`, and convert `span_note` to `span_label` (so that it prints within one code snippet)

**Review by nikomatsakis — CHANGES_REQUESTED** [review]

File: src/librustc/traits/error_reporting.rs (hunk 3 above)
Comment (tommyip) [inline src/librustc/traits/error_reporting.rs]: Good point, I didn't thought of that!

**Comment by tommyip** [comment]
For some reason `span_label` is producing a trailing whitespace:
```
  --> src/test/ui/closure_context/issue-26046-fn-once.rs:14:19
   |
14 |       let closure = move || {
   |  ___________________^
15 | |         vec
16 | |     };
   | |_____^
17 | 
18 |       Box::new(closure)
   |       ----------------- the requirement to implement `Fn` derives from here
   |
note: closure is `FnOnce` because it moves the variable `vec` out of its environment
  --> src/test/ui/closure_context/issue-26046-fn-once.rs:15:9
   |
15 |         vec
   |         ^^^

error: aborting due to previous error(s)
```
Next to `17 |`.
I checked my changes and couldn't find anything that would cause this:
```diff
diff --git a/src/librustc/traits/error_reporting.rs b/src/librustc/traits/error_reporting.rs
index 7375338..c8e99c0 100644
--- a/src/librustc/traits/error_reporting.rs
+++ b/src/librustc/traits/error_reporting.rs
@@ -648,6 +648,10 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
                             kind,
                             found_kind);
 
+                        err.span_label(
+                            obligation.cause.span,
+                            format!("the requirement to implement `{}` derives from here", kind));
+
                         let infer_tables = match self.tables {
                             InferTables::Interned(tables) =>
                                 Some(InferTablesRef::Interned(tables)),
@@ -656,6 +660,8 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
                             InferTables::Missing => None,
                         };
 
+                        // Additional context information explaining why the closure only implements
+                        // a particular trait.
                         if let Some(tables) = infer_tables {
                             match tables.closure_kinds.get(&node_id) {
                                 Some(&(ty::ClosureKind::FnOnce, Some((span, name)))) => {
@@ -670,11 +676,6 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
                                 },
                                 _ => {}
                             }
-                        } else {
-                            err.span_note(
-                                obligation.cause.span,
-                                &format!("the requirement to implement `{}` \
-                                          derives from here", kind));
                         }
 
                         err.emit();
```

**Comment by nikomatsakis** [comment]
@tommyip perhaps we just *always* print a trailing space in that scenario? Is that really a *problem*?

**Review by nikomatsakis — APPROVED** [review]

**Comment by nikomatsakis** [comment]
Er, I guess you didn't push the commits that implement that part yet?

**Comment by tommyip** [comment]
I'll push them now

**Comment by tommyip** [comment]
Pushed

File: src/test/ui/closure_context/issue-26046-fn-mut.stderr [hunk 4]
```diff
@@ -6,6 +6,9 @@ error[E0525]: expected a closure that implements the `Fn` trait, but this closur
 15 | |         num += 1;
 16 | |     };
    | |_____^
+17 |
```
Comment (nikomatsakis) [inline src/test/ui/closure_context/issue-26046-fn-mut.stderr]: cc @estebank -- @tommyip mentioned that there is a trailing space after this `17 | ` -- this doesn't bother me per se, but is that just how the diagnostics output works in general?

Comment (estebank) [inline src/test/ui/closure_context/issue-26046-fn-mut.stderr]: @nikomatsakis that space is to pad to compensate for the multiline markers. We can add a check for empty lines and avoid it.

**Comment by nikomatsakis** [comment]
this is really cool :)
