### ISSUE TITLE
`let` expressions in this position are unstable

### ISSUE THREAD

**Issue by kakserpom** [rust-lang/rust#142111]
Stable Rust:

```
error[E0658]: `let` expressions in this position are unstable
   --> src/lib.rs:331:24
    |
331 |                     if let Some(&n1) = transitions.get(b.as_ref()) && let Some(&n2) = self.nodes[n1].transitions.get(a.as_ref())
    |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

error[E0658]: `let` expressions in this position are unstable
   --> src/lib.rs:331:71
    |
331 |                     if let Some(&n1) = transitions.get(b.as_ref()) && let Some(&n2) = self.nodes[n1].transitions.get(a.as_ref())
    |                                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information

```

Of course I've rewritten this as: 
```
if let Some(&node) = transitions.get(b.as_ref()).and_then(|&x| self.nodes[x].transitions.get(a.as_ref()))
```

But it still looks like a bug to me, because https://github.com/rust-lang/rust/issues/53667 is marked as completed and closed.

### Meta

`rustc --version --verbose`:
```
rustc 1.87.0 (17067e9ac 2025-05-09)
binary: rustc
commit-hash: 17067e9ac6d7ecb70e50f92c1944e545188d2359
commit-date: 2025-05-09
host: aarch64-apple-darwin
release: 1.87.0
LLVM version: 20.1.1
```

</p>
</details>

**Comment by hanna-kruppe** [comment]
The PR that stabilized let chains (https://github.com/rust-lang/rust/pull/132833) will be in Rust 1.88, so you’re one version too early.

**Comment by coredoesdev** [comment]
I'm still getting this error (in an unrelated codebase) even after updating to 1.88; what am I missing?
```
error[E0658]: `let` expressions in this position are unstable
   --> crates/xtask/src/main.rs:219:20
    |
219 |                 if let Some(extension) = path.extension() && extension == "svg" {
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
```
```
rustc 1.88.0 (6b00bc388 2025-06-23)
binary: rustc
commit-hash: 6b00bc3880198600130e1cf62b8f8a93494488cc
commit-date: 2025-06-23
host: x86_64-unknown-linux-gnu
release: 1.88.0
LLVM version: 20.1.5
```

**Comment by Scripter17** [comment]
> I'm still getting this error (in an unrelated codebase) even after updating to 1.88; what am I missing?
> ```
> error[E0658]: `let` expressions in this position are unstable
>    --> crates/xtask/src/main.rs:219:20
>     |
> 219 |                 if let Some(extension) = path.extension() && extension == "svg" {
>     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     |
>     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
> ```
> ```
> rustc 1.88.0 (6b00bc388 2025-06-23)
> binary: rustc
> commit-hash: 6b00bc3880198600130e1cf62b8f8a93494488cc
> commit-date: 2025-06-23
> host: x86_64-unknown-linux-gnu
> release: 1.88.0
> LLVM version: 20.1.5
> ```

Is your crate in edition 2024? Let chains were only stabilized for edition 2024 due to ergonomics issues with having them in 2021 and below.

If that's the cause, the error should definitely say so.

**Comment by coredoesdev** [comment]
Right.. forgot I never upgraded this particular codebase. That was all :P
Agreed, that error can be improved. I remember seeing another PR somewhere about improving the message that hasn't made it's way in yet... maybe something can be put in the body of #53667 to note this for the inevitable confused people (like me!) that end up there

**Comment by kpreid** [comment]
#143214 should clean up the confusing error message.
