### ISSUE TITLE
regression: f16 + f128 is unstable

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#123282]
```
[INFO] [stdout] error[E0658]: the type `f16` is unstable
[INFO] [stdout]  --> src/float.rs:5:9
[INFO] [stdout]   |
[INFO] [stdout] 5 | pub use f16::*;
[INFO] [stdout]   |         ^^^
[INFO] [stdout]   |
[INFO] [stdout]   = note: see issue #116909 <https://github.com/rust-lang/rust/issues/116909> for more information
```

* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/Cyborus04.more_nums/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.78-3/beta-2024-03-30/gh/jthomme1.gen_smooth/log.txt

**Comment by fmease** [comment]
cc @tgross35

**Comment by Nilstrieb** [comment]
MCVE:
```rust
mod f16 { pub fn a() {} }

pub use f16::a;
```

**Comment by Nilstrieb** [comment]
It compiles if I add `#![feature(f16)]`. Somehow feature gating and name resolution disagree whether it refers to the type or the module.
```rust
mod f32 { pub fn a() {} }

pub use f32::a;
```
also compiles

**Comment by Nilstrieb** [comment]
I think this was fixed recently? It reproduces on the playground nightly, but does not reproduce on the latest nightly and on master.

**Comment by Nilstrieb** [comment]
Ah no, I can reproduce it with cargo build, just not with rustc directly (?????????).

**Comment by Nilstrieb** [comment]
cc @petrochenkov @compiler-errors, it was probably regressed by https://github.com/rust-lang/rust/commit/e782d27ec6456a6080a5bfe8b2f189fa9f1b1d0f

**Comment by fmease** [comment]
> Ah no, I can reproduce it with cargo build, just not with rustc directly (?????????).

`rustc` defaults to Rust 2015 and `cargo new; cargo b` to Rust 2021. And the MCVE only fails for >=2018

**Comment by tgross35** [comment]
I am looking at this but it may take me a bit to have a solution. What is the timeline like to have a candidate fix vs. reverting?

**Comment by Mark-Simulacrum** [comment]
We will want a backportable (i.e. relatively small, limited impact) fix in the next 2-3 weeks. We're about [a month out from the 1.78 release](https://forge.rust-lang.org/index.html).

**Comment by compiler-errors** [comment]
Well given that f16/f128 is nightly-only, I don't see why we would want to fix this over reverting. @tgross35: Let's just revert it on beta, and try to fix it on nightly.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23123282.20regression.3A.20f16.20is.20unstable)).

@rustbot label -I-prioritize +P-high

**Comment by petrochenkov** [comment]
Something wrong is going on here.
In the [reproduction](https://github.com/rust-lang/rust/issues/123282#issuecomment-2028843253) the resolution should never touch primitive `f16` with `finalize` enabled.
I'll check.

**Comment by petrochenkov** [comment]
Fix:
```patch
--- a/compiler/rustc_resolve/src/ident.rs
+++ b/compiler/rustc_resolve/src/ident.rs
@@ -605,6 +605,7 @@ struct Flags: u8 {
                                 && !this.tcx.features().f16
                                 && !ident.span.allows_unstable(sym::f16)
                                 && finalize.is_some()
+                                && innermost_result.is_none()
                             {
                                 feature_err(
                                     this.tcx.sess,
@@ -618,6 +619,7 @@ struct Flags: u8 {
                                 && !this.tcx.features().f128
                                 && !ident.span.allows_unstable(sym::f128)
                                 && finalize.is_some()
+                                && innermost_result.is_none()
                             {
                                 feature_err(
                                     this.tcx.sess,
```

**Comment by tgross35** [comment]
Ah I shouldn't have included a `fixes:` tag, this needs to be reopened.

Since the fix is small, I'll put up a beta PR with the cherry pick as long as that seems reasonable in favor of reverting.

**Comment by tgross35** [comment]
Up at https://github.com/rust-lang/rust/pull/123445

**Comment by fmease** [comment]
> Ah I shouldn't have included a fixes: tag, this needs to be reopened.

**Comment by tgross35** [comment]
> Ah I shouldn't have included a `fixes:` tag, this needs to be reopened.

Well, now it can be closed again 😄 https://github.com/rust-lang/rust/pull/123466 should hopefully fix this.
