### PR TITLE
Revert "Allow dynamic linking for iOS/tvOS targets."

### PR DESCRIPTION
**Pull request by francesca64**
This reverts PR #73516.

On macOS I compile static libs for iOS, automated using [cargo-mobile](https://github.com/BrainiumLLC/cargo-mobile), which has worked smoothly for the past 2 years. However, upon updating to Rust 1.46.0, I was no longer able to use Rust on iOS. I've bisected this to the PR referenced above.

For most projects tested, apps now immediately crash with a message like this:
```
dyld: Library not loaded: /Users/francesca/Projects/example/target/aarch64-apple-ios/debug/deps/libexample.dylib
  Referenced from: /private/var/containers/Bundle/Application/745912AF-A928-465C-B340-872BD1C9F368/example.app/example
  Reason: image not found
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/usr/lib/system/introspection
DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib
```

This can be reproduced by using cargo-mobile to generate a winit example project, and then attempting to run it on an iOS device (`cargo mobile init && cargo apple open`).

In our projects that depend on DisplayLink, the build instead fails with a linker error:
```
= note: Undefined symbols for architecture arm64:
            "_CACurrentMediaTime", referenced from:
                display_link::ios::run_callback_ios10::hda81197ff46aedbd in libapp-4f0abc1d7684103f.rlib(app-4f0abc1d7684103f.40d4iro0yz1iy487.rcgu.o)
                display_link::ios::run_callback_pre_ios10::h91f085da19374320 in libapp-4f0abc1d7684103f.rlib(app-4f0abc1d7684103f.40d4iro0yz1iy487.rcgu.o)
          ld: symbol(s) not found for architecture arm64
```

After reverting the change to enable dynamic linking on iOS, everything works the same as it did on Rust 1.45.2 for me.

In the future, would it be possible for me to be pinged when iOS-related PRs are made? I work for a company that intends on using Rust on iOS in production, so I'd gladly provide testing.

cc @aspenluxxxy

### CODE REVIEW

**Comment by aspenluxxxy** [comment]
I'd rather this be a rustc flag rather than being completely disabled.

**Comment by jonas-schievink** [comment]
Hmm, I think `-C prefer-dynamic` is supposed to handle this, but it should be off by default

**Comment by jonas-schievink** [comment]
I'm probably not the best person to review this, but also don't know who would be.

@francesca64 Can you check if your build setup passes `-C prefer-dynamic` or you're using `--crate-type dylib` or `#![crate_type = "dylib"]` anywhere? I would expect that removing those should avoid this issue.

**Comment by francesca64** [comment]
@jonas-schievink mm, actually, I know what's happening now. In my Cargo.toml, I have:

```toml
[lib]
crate-type = ["staticlib", "cdylib", "rlib"]
```

`staticlib` for iOS, `cdylib` for Android, and `rlib` for desktop. I've been relying on `cdylib` being ignored on iOS (and accepting the build time hit elsewhere), so it seems pretty obvious why I'm having problems now. My solution definitely wasn't ideal to begin with.

`crate-type` can't be specified per-target (rust-lang/cargo#4881), which is what originally led me down that road. You mentioned a `--crate-type` argument; do you think that would work for my use case?

**Comment by jonas-schievink** [comment]
Ah, I see, that explains why this is causing problem now.

`--crate-type` is what Cargo already passes for your `crate-type` config. The crate type can also be configured using a `#![crate_type = "cdylib"]` argument in the crate root, but I'm not sure how well Cargo copes with that. Maybe you could combine that with `#![cfg_attr]` with the right `target_os` checks to get what you want?

**Comment by aspenluxxxy** [comment]
@francesca64 couldn't something like this be used?
```rs
#[cfg(target_os = "android")]
#![crate_type = "cdylib"]
#[cfg(target_os = "ios")]
#![crate_type = "staticlib"]
#[cfg(not(any(target_os = "android", target_os = "ios")))]
#![crate_type = "rlib"]
```

**Comment by jonas-schievink** [comment]
You'd have to use `cfg_attr`, but yeah, that was my idea

**Comment by cutsoy** [comment]
```#![crate_type = "cdylib"]``` does not work with Cargo, unfortunately. I also thought about using two different manifests and passing them with ```cargo build --manifest-path=Cargo.a.toml``` and ```cargo build --manifest-path=Cargo.b.toml```, but that's currently blocked by https://github.com/rust-lang/cargo/issues/6690.

**Comment by aspenluxxxy** [comment]
I still don't feel "my project doesn't work as a cdylib" is a valid reason to re-add a meaningless limitation

**Comment by cutsoy** [comment]
I don't think "adding a meaningless limitation" is the end-goal here. It's simply the fastest fix for a number of issues that are more difficult to address:

1. Crate-type cannot be set depending on target. https://github.com/rust-lang/cargo/issues/4881
2. Crate-type cannot be overridden with `--crate-type`. https://github.com/rust-lang/cargo/issues/6160
3. Using multiple `Cargo.*.toml` files is currently rejected (this might be a meaningless limitation too). https://github.com/rust-lang/cargo/issues/6690
4. `#![crate_type = "*"]` does not work with Cargo.

**Comment by aspenluxxxy** [comment]
Temporary fixes are sadly rarely temporary. And this "temporary fix" would impede actual functionality.

**Comment by jonas-schievink** [comment]
If we don't find a workaround for those Cargo bugs that you can use, I think we should go ahead with the revert, since this is a stable regression affecting production users.

**Comment by cutsoy** [comment]
If there is any interest, I can file a PR that fixes rust-lang/cargo#4881.

This commit cutsoy/cargo@ebfc65c would allow multiple `Cargo.*.toml` manifests. For example, one can be named `Cargo.android.toml`, another `Cargo.ios.toml`. To build with a specific manifest, run `cargo build --manifest-path=./Cargo.ios.toml`. Any name is valid as long as it starts with `Cargo.` and ends with `.toml`.

Alternatively, rust-lang/cargo#6160, is also relatively easy to fix with an implementation that looks at the `--crate-type` flag in [here](https://github.com/rust-lang/cargo/blob/79b397d72c557eb6444a2ba0dc00a211a226a35a/src/cargo/util/command_prelude.rs#L298) and (if present) updates the manifest's library target to override its crate type(s). In this case, `--crate-type` would be passed directly to `cargo build` instead of passed along to rustc.

Although admittedly, neither fix would be as elegant as fixing https://github.com/rust-lang/cargo/issues/4881 (which would allow `target.cfg(...).crate-type`), but I honestly have no idea where to start with that. 😞

Any thoughts?

**Comment by aspenluxxxy** [comment]
@cutsoy An actual fix would be much better than this PR, yes, and would be appreciated very much.

**Comment by francesca64** [comment]
@aspenluxxxy 
> Temporary fixes are sadly rarely temporary. And this "temporary fix" would impede actual functionality.

I know this situation must be frustrating, but I believe your PR was merged on the basis that it wasn't known to have any downsides: https://github.com/rust-lang/rust/pull/73516#issuecomment-648414445

cc @nikomatsakis 

@cutsoy 

Thanks for doing such a heroic amount of legwork! And I'm always happy to see someone else using Rust for mobile development.

I'm sure people would appreciate a fix for rust-lang/cargo#6690, though I wonder if it'd be contentious to be less opinionated about the file name than that. I don't have much of a hat in this particular issue either way, since for my use case I could just shove each Cargo.toml in a different temp dir (my build process is abstracted away from end-users, so I can get away with doing arbitrary work behind the scenes).

A fix for rust-lang/cargo#6160 would make me ecstatic! As I mentioned above, I'm hiding all the build complexity anyway, so just being able to override the crate-type via a flag would be super elegant for me.

rust-lang/cargo#4881 definitely seems like the hardest one... it'd actually be less elegant for my use case anyway, but I imagine people who are building things more manually would prefer that.

**Comment by aspenluxxxy** [comment]
> I know this situation must be frustrating, but I believe your PR was merged on the basis that it wasn't known to have any downsides: #73516 (comment)

Pretty sure it was also because ***nobody knew why it was even set that way in the first place.***

**Comment by cutsoy** [comment]
@aspenluxxxy I agree with you that your PR is useful. I have no first-hand knowledge but I am guessing the dynamic linking restriction stems from pre-iOS 8.0, when Apple didn't allow dynamic libraries/frameworks on iOS. Regardless, it's good to have this now. This should indeed be possible.

Unfortunately, several issues that were previously easy to ignore (like @francesca64, I too simply ignored the warning before) are now resurfacing (i.e. the list that I compiled earlier).

But, to summarize:

- If I am not mistaken, @francesca64 has a work-around now.
- I too have a work-around as well (I am dynamically replacing the crate type within Cargo) and I will file a PR tomorrow. It might be useful for people who are compiling for wasm too.

So I don't think the PR needs to be reverted unless more people are affected.

**Comment by cutsoy** [comment]
I implemented a fix that allows `--crate-type` to be passed to Cargo build and check in cutsoy/cargo@ca833bf.

It's quite simple but still effective: if you run `cargo build`, it will build according to your `Cargo.toml`. If you run `cargo build --crate-type cdylib`, it will build a shared library (e.g. for Android). If you run `cargo build --crate-type staticlib`, it will build a static library (e.g. for iOS). In both cases, the provided crate type will override the crate type of all library targets in de "root" manifest (i.e. it doesn't modify the manifests of dependencies), and the modification is not persisted to disk (it is applied "ad-hoc").

**Comment by francesca64** [comment]
My idea to generate a Cargo.toml in a temp dir for each crate type isn't as easy as I expected, since paths in Cargo.toml (for bins, libs, deps, etc.) are all relative to the manifest dir. It's possible to implement, but it's very fiddly and brittle.

Fortunately, rust-lang/cargo#8789 works fabulously for me!

**Comment by nikomatsakis** [comment]
I'm just catching up here -- can someone confirm whether there is a known workaround that works for @francesca64 and @cutsoy?

I realize there are also pending cargo PRs, though I suspect they will take some time to land.

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/47683weeklymeeting2020102254818.html#214193506) in T-compiler meeting, declined to backport.

@rustbot modify labels: -beta-nominated

**Comment by francesca64** [comment]
@nikomatsakis the only viable workaround seems to be doing something like [cargo-crate-type](https://crates.io/crates/cargo-crate-type). I've tried using my own implementation of that workaround, and it definitely works, but I'm unsurprisingly concerned about the UX of that approach. My end-users would have to know not to perform other builds, modify their Cargo.toml, `git add`, etc. while a build is ongoing. When performing builds from within Xcode, simply pressing the Stop button would prevent me from reverting the user's Cargo.toml to its original state. Reentrant use of my tool would also become problematic.

I've explored a related approach where I generate multiple variants of the user's Cargo.toml, which doesn't have any of the issues I listed. However, due to rust-lang/cargo#6690, each Cargo.toml must be in a different directory (since I can't name them anything other than Cargo.toml). That small wrinkle has proven quite problematic, as very many things are defined relative to the manifest directory. All of the paths in the user's Cargo.toml must be translated, which is already quite difficult to do correctly, but worse still, there's nothing I can do if the user has paths in their metadata section. After creating a mostly working implementation, build scripts now seem to have the wrong working directory, so I'm beginning to think this approach isn't realistic. Even if it's viable, I'm worried about how many assumptions I'd be violating.

rust-lang/cargo#8789 is a real solution, solves this problem elegantly, and is more or less my only hope. Judging from the current prognosis, my company and users would have to use nightly for the foreseeable future, but that's probably fine.

**Comment by jonas-schievink** [comment]
That does sound like we ought to revert this until a better solution is found. Requiring you and your users to use nightly (or even a patched Cargo) certainly isn't ideal.

To prevent breakage like this in the future, consider setting up automated testing against nightly Rust releases, and report any issues you run into. That way we could have caught this issue before it made its way to the stable channel. Filing an issue instead of a PR would also work better with our processes.

Regarding the Cargo issues you ran into, it sounds like https://github.com/rust-lang/cargo/issues/6690 would be fairly easy to fix, and that should at least give you a usable workaround if we land the original PR again (which we do want to do).

@bors r+

**Comment by francesca64** [comment]
@jonas-schievink thanks so much for all the help!

> To prevent breakage like this in the future, consider setting up automated testing against nightly Rust releases, and report any issues you run into

Will do! I apologize for not having thought to do that sooner.

> Filing an issue instead of a PR would also work better with our processes.

Understood!

**Comment by nikomatsakis** [comment]
I agree with the conclusion to revert, but I also agree with @aspenluxxxy that we don't have the "right fix" here long term and it'd be good to pursue something better. It sounds like this is likely more on the cargo side, however.

**Comment by aspenluxxxy** [comment]
Yeah, I feel like this should be re-merged as soon as something that can be used to avoid this issue is merged into Cargo.

**Comment by spastorino** [comment]
[discussed](https://zulip-archive.rust-lang.org/238009tcompilermeetings/34116weeklymeeting2020120354818.html#218707488) in T-compiler meeting.

@rustbot modify labels: stable-accepted

**Comment by Diatrus** [comment]
I would like to note that the merging of this pull request into upstream has been more than an extreme inconvenience for me, as I maintain a distribution of *nix tools for iOS. Imagine my surprise updating rust and seeing I can no longer build dynamic libraries. 

The merging of this improper solution has all but destroyed my workflow when compiling dynamic libraries using the latest Rust.

**Comment by jonas-schievink** [comment]
Sorry for the inconvenience, but this should be expected when relying on tier 2 targets that don't see much testing.

**Comment by dcow** [comment]
> Sorry for the inconvenience, but this should be expected when relying on tier 2 targets that don't see much testing.

No, it shouldn't. It's lazy.

**Comment by jonas-schievink** [comment]
"guaranteed to build" means that the target is guaranteed to successfully build the contained rustup components, not that it'll be able to build *your* application

**Comment by Torrekie** [comment]
we should revert this pr since t2 targets were guaranteed to be successfully built, this was definitely not a proper solution for what francesca64 mentioned.
there's no reason to prevent iOS dylib building as it is actually working in iOS Apps or jailbroken iOS environments, also, Apple LLVM supported building iOS dynamic libraries for quite a long time.

**Comment by nyuszika7h** [comment]
> I don't think "adding a meaningless limitation" is the end-goal here. It's simply the fastest fix for a number of issues that are more difficult to address:
> 
> 
> 
> 1. Crate-type cannot be set depending on target. https://github.com/rust-lang/cargo/issues/4881
> 
> 2. Crate-type cannot be overridden with `--crate-type`. https://github.com/rust-lang/cargo/issues/6160
> 
> 3. Using multiple `Cargo.*.toml` files is currently rejected (this might be a meaningless limitation too). https://github.com/rust-lang/cargo/issues/6690
> 
> 4. `#![crate_type = "*"]` does not work with Cargo.

#3 is hardly "difficult to address". It's literally just removing three lines of code that cause yet another pointless limitation.

**Comment by awakecoding** [comment]
This reverted pull request got mentioned in https://github.com/rust-lang/rust/issues/21727

I've got a growing number of Rust libraries that I build for Windows, macOS, Linux, Android and iOS as *shared libraries* packaged in nuget packages with C# bindings on top. I am blocked on this for iOS support and just build static libraries for now to ensure the code builds, but I discard the output. I have a line in my build scripts to edit the Cargo.toml and change the crate type to staticlib just for iOS, as I think cargo still doesn't have a way to specify platform-specific crate types.

Here's my question: I see there's been a lot of back and forth on this, and my understanding is that the fix is fairly minimal, as it consists of removing the block for dynamic linking on iOS. How do we get this issue moved forward from here? I don't expect all crates to build as cdylib, but then it's not any worse than the current state where cdylib is hard blocked anyway. Once the block is removed, we can start just fixing build issues on crates that need them.

Did I miss anything?

**Comment by bjorn3** [comment]
> as I think cargo still doesn't have a way to specify platform-specific crate types.

If you specify multiple crate types cargo will drop all unsupported types with a warning. Only linking and/or assembling a staticlib happens multiple times. The rest of the compilation process doesn't get duplicated when using multiple crate types.

**Comment by awakecoding** [comment]
> > as I think cargo still doesn't have a way to specify platform-specific crate types.
> 
> If you specify multiple crate types cargo will drop all unsupported types with a warning. Only linking and/or assembling a staticlib happens multiple times. The rest of the compilation process doesn't get duplicated when using multiple crate types.

Is that the reason why some people report that simply allowing dynamic linking would break stuff for them? I assume it's because it would actually trying building cdylib crate types when it would just skip over it with a warning before? What if your only crate type is cdylib, doesn't it fail the whole build? I'm not sure it's such a good idea to "warn" when what you've requested to build, can't be built at all.

**Comment by dvc94ch** [comment]
while in most cases it shouldn't cause breakages it is conceivable that there are some cases where such breakage. one such issue if I remember this conversation correctly was that you can't build both a static lib and a dynamic lib due to name conflicts. so you can't choose to build a dylib on all platforms and a staticlib on ios. the crate would need to be split into two crates. one that builds the dylib and one for ios or update the ios code to be a dylib.

In general the rust team is pedantic about not breaking thing. I guess it's a good stance overall. This means that we get stuck with some edge cases like this one. I think another example of this would be Default can't be implemented with const generics because there is some weirdness around empty arrays which I forgot.

**Comment by awakecoding** [comment]
@dvc94ch I'm trying to figure out what the best approach to finding an acceptable solution is, because right now, the least painful approach would likely be to patch Rust and roll my own custom distribution, just to change a bool to true. It's an insane amount of work just for something that at a bare minimum could be overridden with an environment variable, or command-line argument to cargo?

This issue has been open since 2015 - I suggest that if it's not possible to find a default solution that would satisfy everyone, then we should look into make it possible to override the default behavior, such that we could at least unblock those of us who really need to build shared libraries on iOS, without causing breaking changes for everybody else.

image

**Comment by cutsoy** [comment]
It has been almost two years so my memory is a bit foggy on this, but I think this comment by someone else on another issue explains why the revert was necessary: https://github.com/rust-lang/cargo/issues/4881#issuecomment-732751642.

> This issue becomes critical after merging [rust-lang/rust#73516](https://github.com/rust-lang/rust/pull/73516) that added support of cdylib on iOS.
> 
> This new feature in Rust 1.46 added a lot of headache for iOS builds with `cdylib` targets. `cdylib` target is near impossible to build if you are using any crate with native dependencies (ex. openssl, libsodium, zmq). You can't just find .so files for all architectures to perform correct linking. Usual workflow is the following:
> 
> 1. You build `staticlib` and rely that native dependencies will be linked as frameworks later
> 2. You setup right cocoapods in ObjectiveC/Swift wrapper.
> 
> As cargo doesn't support platform-dependent crate types #4881 as a result a lot of projects now broken on Rust 1.46

Before the original PR was merged, Cargo/Rustc would ignore the `cdylib` target for iOS and only build the `static` target. This behavior might not have been intentional, but it worked really well for iOS libraries with native dependencies.

After that PR was merged (and before it was reverted), it would always try to build the `cdylib` too and fail because of missing symbols of native dependencies.

I think this was the issue, but please correct me if I'm wrong. 😁

**Comment by dvc94ch** [comment]
well, I'm sure that we can find a solution thats ok for everyone. should be a non-issue for a new edition (but still requires someone to actually bring it up when the next edition occurs), and if someone on the rust team had some interest in ios I'm sure they could get it done before that. if your company is interested in this @awakecoding you could ask on the zulip chat if someone on the core team willing to push this through.

> I think this was the issue, but please correct me if I'm wrong.

I believe the naming conflict example is slightly easier to understand.

**Comment by cutsoy** [comment]
I agree that it's easier to understand but I don't think that was the issue. On other platforms (e.g. macOS) it has always been possible to compile both `.a` and `.dylib` with the same name and it doesn't cause a conflict.

Having said that, I see that this got merged recently: https://github.com/rust-lang/cargo/issues/10083. The `--crate-type` flag will get stabilized in 1.64. If I'm not mistaken, this solves the problem too so this PR could be reverted in 1.64 with relatively little headache. In 1.64, you could still get a successful iOS staticlib with `cargo build --crate-type=statclib` even if the crate has `cdylib` targets too.

So summing up, I think this PR can be reverted in 1.64. 🤞

**Comment by dvc94ch** [comment]
> On other platforms (e.g. macOS) it has always been possible to compile both .a and .dylib with the same name and it doesn't cause a conflict.

and I'm pretty sure that if they were linking native libraries, they added the correct dylibs to the search path. actually agree that is even easier to understand.

I'm pretty sure I've seen warnings and errors about naming conflicts before from cargo, so it's not unheard of.

**Comment by lu-zero** [comment]
> This reverts PR #73516.
> 
> On macOS I compile static libs for iOS, automated using [cargo-mobile](https://github.com/BrainiumLLC/cargo-mobile), which has worked smoothly for the past 2 years. However, upon updating to Rust 1.46.0, I was no longer able to use Rust on iOS. I've bisected this to the PR referenced above.
> 
> For most projects tested, apps now immediately crash with a message like this:
> 
> ```
> dyld: Library not loaded: /Users/francesca/Projects/example/target/aarch64-apple-ios/debug/deps/libexample.dylib
>   Referenced from: /private/var/containers/Bundle/Application/745912AF-A928-465C-B340-872BD1C9F368/example.app/example
>   Reason: image not found
> dyld: launch, loading dependent libraries
> DYLD_LIBRARY_PATH=/usr/lib/system/introspection
> DYLD_INSERT_LIBRARIES=/Developer/usr/lib/libBacktraceRecording.dylib:/Developer/usr/lib/libMainThreadChecker.dylib:/Developer/Library/PrivateFrameworks/DTDDISupport.framework/libViewDebuggerSupport.dylib:/Developer/Library/PrivateFrameworks/GPUTools.framework/libglInterpose.dylib:/usr/lib/libMTLCapture.dylib
> ```
> 
> This can be reproduced by using cargo-mobile to generate a winit example project, and then attempting to run it on an iOS device (`cargo mobile init && cargo apple open`).

The problem is in cargo-mobile not passing the correct linking information (and generally cargo knowing nothing about how to make platform-correct dylibs), you may copy the logic that I put in cargo-c to avoid this issue.

**Comment by awakecoding** [comment]
For anybody still hard-blocked on this, I have rolled my own prebuilt Rust distribution with a patch to enable iOS shared libraries. The ideal solution is an upstream fix, but this will do until the matter is finally resolved. I detailed my instructions here: https://github.com/rust-lang/rust/issues/21727#issuecomment-1258598083
