### ISSUE TITLE
On stable channels, suggest removing `#![feature]`s that have already been stabilized

### ISSUE THREAD

**Issue by Zapeth** [rust-lang/rust#83715]
I was under the impression that `min_const_generics` should work on stable channel with version 1.51, however using the example code from https://github.com/rust-lang/rust/pull/79135 I get
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src\main.rs:5:1
  |
5 | #![feature(min_const_generics)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
```

rustc -Vv output (its the [mingw package](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-rust)):
```
rustc 1.51.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-pc-windows-gnu
release: 1.51.0
LLVM version: 11.0.0
```
```

**Comment by eggyal** [comment]
`#[feature]` attributes are used to enable unstable/gated features in the nightly compiler.  Once a feature stabilizes, the attribute is no longer required.

**Comment by jyn514** [comment]
I think the compiler should suggest removing the feature gate if it's been stabilized.

**Comment by Zapeth** [comment]
I see, I was unsure whether the error message was referring to the referred feature or the feature flag itself (since the example code of the stabilize PR was using it too I was assuming the former).

And yes, removing the feature line from the example code makes it comile, thanks.

Is there any way to make rustc ignore the feature flag and still try to compile it? The library I want to use still has it included and I'd prefer it not to remove it manually until it gets removed upstream.

**Comment by jyn514** [comment]
> Is there any way to make rustc ignore the feature flag and try to compile it anyway? The library I want to use still has it included and I'd prefer not having to remove it manually until it gets removed upstream.

No, you'll need to either patch the crate or fix it upstream.
