### PR TITLE
back out bogus `Ok`-wrapping suggestion on `?` arm type mismatch

### LINKED ISSUE #52537: [ui] Incorrect hint: Ok(wrap) instead *Deref
Reproduced on versions:
- `rustc 1.29.0-nightly (12ed235ad 2018-07-18)`
- `rustc 1.29.0-nightly (9fd3d7899 2018-07-07)`
- `rustc 1.27.0 (3eda71b00 2018-06-19)`

Isolated example to reproduce:
```rust
use std::ops::Deref;

struct Error {}
struct State {}
struct StateDeref { inner: State }

impl Deref for StateDeref {
	type Target = State;
	fn deref(&self) -> &Self::Target { &self.inner }
}

fn get_state() -> Result<StateDeref, Error> { Err(Error {}) }

fn need_ref_state_from(state: &State) -> bool { true }

fn state_info() -> Result<bool, Error> { Ok(need_ref_state_from(&get_state()?)) }
```

Actual error:
```txt
error[E0308]: try expression alternatives have incompatible types
   --> src/main.rs:16:66
    |
16  | fn state_info() -> Result<bool, Error> { Ok(need_ref_state_from(&get_state()?)) }
    |                                                                  ^^^^^^^^^^^^
    |                                                                  |
    |                                                                  expected struct `State`, found struct `StateDeref`
    |                                                                  help: try wrapping with a success variant: `Ok(get_state()?)`
    |
    = note: expected type `State`
               found type `StateDeref`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
```

Mentioned suggestion about "wrap into `Ok`" is incorrect at all. There we should deref the value from the `get_state()?`.

- - -

Expected error:   (something like this)
```txt
...
expected struct `State`, found struct `StateDeref`
help: try re-dereference(?) with a success variant: `&*get_state()?`
```

### LINKED ISSUE #54578: Rust claims that `Ok(T)` is the same as `&T`
Steps to reproduce:

- Have a function that takes a reference
- Call that function passing an expression using `?`
- Forget an `&`

Example code: https://play.rust-lang.org/?gist=c75cddbb4c5d8a1b63ec11dc3c5bca43&version=stable&mode=debug&edition=2015

Output:

```
error[E0308]: try expression alternatives have incompatible types
 --> src/main.rs:5:9
  |
5 |     foo(bar()?);
  |         ^^^^^^
  |         |
  |         expected &i32, found i32
  |         help: try wrapping with a success variant: `Ok(bar()?)`
  |
  = note: expected type `&i32`
             found type `i32`
```

Expected output:

```
error[E0308]: mismatched types
 --> src/main.rs:5:9
  |
5 |     foo(bar()?);
  |         ^^^^^^
  |         |
  |         expected &i32, found i32
  |         help: consider borrowing here: `&bar()?`
  |
  = note: expected type `&i32`
             found type `i32`
```

### PR DESCRIPTION
**Pull request by zackmdavis**
This suggestion was introduced in #51938 / 6cc78bf8d7 (while introducing different language for type errors coming from `?` rather than a `match`), but it has a lot of false-positives, and incorrect suggestions carry more badness than marginal good suggestions do goodness. I regret not doing this earlier. :disappointed: 

Resolves #52537, resolves #54578.

r? @estebank

### CODE REVIEW

**Comment by zackmdavis** [comment]
I could see a case for beta-backporting if we think that 1.31 will get a lot of new users coming to check out the edition, and we don't want to make a bad impression with a bad suggestion, but maybe backports should only be for higher-priority edition-critical things? On the other hand, this is a very low-risk patch (straightforwardly removes an `if let` and updates tests).

**Comment by zackmdavis** [comment]
> Did you find it impossible to restrict the suggestion any further instead of removing it?

Not impossible, just not a prioritized use of my time right now. (Whereas getting rid of the false positive _is_ a priority, because it's been independently reported four times.) I've now filed a separate issue so that the opportunity isn't forgotten: #55429

**Comment by Mark-Simulacrum** [comment]
Accepting for beta promotion. I agree that a faulty diagnostic isn't good to ship, and the edition only reinforces that. Code changes are minimal enough that I feel comfortable with a backport.
