### PR TITLE
Never consider int and float vars for `FnPtr` candidates

### LINKED ISSUE #109892: `FnPtr` blanket impls cause "multiple applicable items in scope" for unrelated types.
*Note: the below reduction originally came from a `use num_traits::Float;` + `0.0.max(x)` **in the wild**.*

I haven't found a way to demonstrate this outside of the "float inference vars + `Ord` method" combo, but:
```rust
trait MyCmp {
    fn cmp(&self) {}
}
impl MyCmp for f32 {}

fn main() {
    0.0.cmp();
}
```
works on stable (`1.68.2`) and beta (`1.69.0-beta.6`), and errors on nightly with:
```
error[E0034]: multiple applicable items in scope
 --> src/main.rs:7:9
  |
7 |     0.0.cmp();
  |         ^^^ multiple `cmp` found
  |
note: candidate #1 is defined in an impl of the trait `MyCmp` for the type `f32`
 --> src/main.rs:2:5
  |
2 |     fn cmp(&self) {}
  |     ^^^^^^^^^^^^^
  = note: candidate #2 is defined in an impl of the trait `Ord` for the type `F`
note: candidate #3 is defined in the trait `Iterator`
 --> /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/iter/traits/iterator.rs:3533:5
help: disambiguate the method for candidate #1
  |
7 |     MyCmp::cmp(&0.0);
  |     ~~~~~~~~~~~~~~~~
help: disambiguate the method for candidate #2
  |
7 |     Ord::cmp(&0.0);
  |     ~~~~~~~~~~~~~~
help: disambiguate the method for candidate #3
  |
7 |     Iterator::cmp(0.0);
  |     ~~~~~~~~~~~~~~~~~~
```

Even though it doesn't show the source for candidate `#2`, I'm almost certain it's this:
https://github.com/rust-lang/rust/blob/f13ccefb5b35af3dbb40a7bbdd64a3216d949664/library/core/src/ptr/mod.rs#L2064-L2070
from (cc @lcnr @oli-obk):
* https://github.com/rust-lang/rust/pull/99531
* https://github.com/rust-lang/rust/pull/108080

On the original PR I left comments like https://github.com/rust-lang/rust/pull/99531#issuecomment-1194688090, trying to rectify the issues with the original approach, but they didn't go anywhere and the version that one in the end is the (arguably) more fragile original one, that uses blanket `impl`s and works around their unwanted interactions.

It's possible in this case all it takes is checking for "float inference vars" and making sure they can never be considered to implement `FnPtr`, but I'm worried there might be other edge cases lurking in the shadows.

Also, did both of those PRs skip crater? I feel like this shouldn't be that hard to hit in the wild.

### PR DESCRIPTION
**Pull request by Noratrieb**
This solves a regression where `0.0.cmp()` was ambiguous when a custom trait with a `cmp` method was in scope.

For integers it shouldn't be a problem in practice so I wasn't able to add a test.

I'm not sure whether there could be more issues hidden in the shadows as mentioned in the issue, but this should at least fix the problematic regression immediately.

fixes #109892

r? oli-obk

### CODE REVIEW

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs [hunk 1]
```diff
@@ -998,8 +998,14 @@ impl<'cx, 'tcx> SelectionContext<'cx, 'tcx> {
...
-            ty::Infer(_) => {
+            | ty::Error(_)
+            | ty::Infer(
+                ty::InferTy::IntVar(_)
+                | ty::InferTy::FloatVar(_)
+                | ty::InferTy::FreshIntTy(_)
+                | ty::InferTy::FreshFloatTy(_),
+            ) => {}
+            ty::Infer(ty::InferTy::TyVar(_) | ty::InferTy::FreshTy(_)) => {
                 candidates.ambiguous = true;
```
Comment (eddyb) [inline compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:1009]: This is the only case I can think of that could still cause issues, I just hope this was already always ambiguous anyway :crossed_fingers:.

**Comment by compiler-errors** [comment]
Thanks @Nilstrieb.

r? @compiler-errors @bors r+ rollup

**Review by eddyb — APPROVED** [review]
Thanks for fixing this so quickly! ~~I won't approve this myself because I'm not 100% sure I have all the background on the version of `FnPtr` that landed~~, but the change makes sense to me.

**EDIT**: heh, I raced with @compiler-errors's r+, so it all worked out nicely.

File: compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs (hunk 1 above)
Comment (Nilstrieb) [reply compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:1009]: I tried to call a method on a ty infer var but that caused errors on typeck about not being able to do that

Comment (eddyb) [reply compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs:1009]: Yeah, that's what I ran into as well, when trying to reproduce it w/o floats.

AFAIK you can't get it to pick a trait based on method name alone, without something like `Default::default().method()` or `<_>::method` but those give up too early because of how ambiguous they are, only int/float inference vars go farther (because they represent an unresolved choice in a small finite set of types etc.).

The fuzzier ideas I've had would involve guiding inference, but `_: FnPtr` will never succeed early enough to taint inference, and blocking inference would likely require associated types etc. - and the moment you pin down a trait, `FnPtr` can only affect it through a blanket impl of your choice, which would also apply to all the existing types too (before `FnPtr` was added).
