### PR TITLE
Do not promote &mut of a non-ZST ever

### LINKED ISSUE #75556: Promotion of non-ZST mutable references is incompatible with const_mut_refs
Consider the following code:
```rust
#![feature(const_mut_refs)]

static mut TEST: () = {
    let x = &mut [1,2,3];
    x[0] += 1;
};
```
This should just work. But instead it throws an error:
```
error[E0080]: could not evaluate static initializer
 --> src/lib.rs:5:5
  |
5 |     x[0] += 1;
  |     ^^^^^^^^^ modifying a static's initial value from another static's initializer
```
The reason for this is that `&mut [1,2,3]` gets lifetime extended via promotion, so this reference now points to a separate mutable static -- but mutable statics cannot be mutated during CTFE.

I see no way to fix this, other than stopping to promote mutable references -- which we should IMO do anyway, they are a very strange and unprincipled special case. Just imagine doing this in a loop, suddenly all these *different* and mutable allocations share the same address...

Cc @rust-lang/wg-const-eval

### PR DESCRIPTION
**Pull request by RalfJung**
Since ~pre-1.0~ 1.36, we have accepted code like this:
```rust
static mut TEST: &'static mut [i32] = {
    let x = &mut [1,2,3];
    x
};
```
I tracked it back to https://github.com/rust-lang/rust/pull/21744, but unfortunately could not find any discussion or RFC that would explain why we thought this was a good idea. And it's not, it breaks all sorts of things -- see https://github.com/rust-lang/rust/issues/75556.

To fix https://github.com/rust-lang/rust/issues/75556, we have to stop promoting non-ZST mutable references no matter the context, which is what this PR does. It's a breaking change.

Notice that this still works, since it does not rely on promotion:
```rust
static mut TEST: &'static mut [i32] = &mut [0,1,2];
```

Cc @rust-lang/wg-const-eval

### CODE REVIEW

File: src/librustc_mir/transform/mod.rs [hunk 1]
```diff
@@ -321,6 +321,7 @@ fn mir_validated(
 
     // Ensure that we compute the `mir_const_qualif` for constants at
     // this point, before we steal the mir-const result.
+    // Also this means promotion can rely on all `const` checks having been done.
```
Comment (RalfJung) [inline src/librustc_mir/transform/mod.rs:324]: At least I think this comment is true -- please double-check.

**Comment by lqd** [comment]
Just to be sure, are the two failing mir-opt tests
- mir-opt/issue-41697.rs
- mir-opt/loop_test.rs
expected to fail because this is a breaking change ? (It was not immediately obvious to me that is was so I preferred asking just in case)

**Comment by RalfJung** [comment]
The mir-opt tests are failing due to an unrelated fix of a MIR pass name that I just spotted, I'll move that to a separate PR.

File: src/librustc_mir/transform/mod.rs (hunk 1 above)
Comment (RalfJung) [reply src/librustc_mir/transform/mod.rs]: Moved to separate PR: https://github.com/rust-lang/rust/pull/75587.

**Comment by RalfJung** [comment]
@craterbot check

**Comment by eddyb** [comment]
Left a comment on the issue (https://github.com/rust-lang/rust/issues/75556#issuecomment-674539678):
> Ugh, that's an ancient rule (believe it or not, it's a workaround for not being able to write `static mut Foo: [T; _] = ...;` and have the length be inferred!) and it was never meant to get this far, I guess I didn't think it through properly when adding the "outermost scope" rule, which is the only position where allowing it makes sense.
>
> In the current implementation, it should've never been promoted, only *allowed*, my bad!

Also, you write:
> Since pre-1.0, we have accepted code like this:

But aren't `let` in CTFE a modern addition?

**Review by eddyb — APPROVED** [review]
Implementation seems fine, but can you add a test that compiled before and now doesn't?
E.g.: `static mut FOO: Option<&mut [i32]> = Some(&mut [1, 2, 3]);`

**Comment by RalfJung** [comment]
> But aren't let in CTFE a modern addition?

Oh, that's a good point. I was just going by this already existing in https://github.com/rust-lang/rust/pull/21744, but it seems that same analysis was doing something else back then.

Interestingly, in Rust 1.35 this actually fails, even though the analysis already carried this exception:
```
    #1 with rustc 1.35.0
error[E0597]: borrowed value does not live long enough
 --> <source>:2:18
  |
2 |     let x = &mut [1,2,3];
  |                  ^^^^^^^ temporary value does not live long enough
3 |     x
4 | };
  | - temporary value only lives until here
```

Rust 1.36 seems to be the first version where this is accepted.

**Comment by eddyb** [comment]
> I was just going by this already existing in #21744, but it seems that same analysis was doing something else back then.

Keep in mind that only recently (last year?), did we actually uncouple promotion from const-*checking*.
So most of the time, the logic was there to *prevent* `static mut X: &mut [i32] = &mut [0];` from erroring.

Also, promotion was in the compiler for a long time (predating MIR itself) but it wasn't exposed to the user (i.e. borrow-checking didn't know about it) until the RFC was accepted, much later.

**Comment by RalfJung** [comment]
This one is even more interesting:
```rust
pub static mut FOO: Option<&mut [i32]> = Some(&mut [1, 2, 3]);
```
It works in Rust 1.21, fails with 1.21 - 1.35, and then works since 1.36. Wtf.

**Comment by eddyb** [comment]
> It works in Rust 1.21, fails with 1.22 - 1.35, and then works again since 1.36. Wtf.

Hmm, if it broke in between, that means we weren't promoting it, and it should've stayed that way (hopefully that means crater won't find anything. What did 1.36 do to start promoting it again? Sounds like a bug.

> Well it did also accept something, until 1.21, it seems?

No, I think 1.21 must've been when I introduced the "outermost scope" rule, i.e. these two started being different:
* `const X: &i32 = &0;` (inherently `&'static`, even without promotion)
* `const Y: Option<&i32> = Some(&0);` (requires promotion)

**Comment by RalfJung** [comment]
Rust 1.36 is when we got "NLL for Rust 2015", not sure if that would have an effect? Maybe this indicates a difference between HIR and MIR promotion / borrowck?

**Comment by RalfJung** [comment]
> can you add a test that compiled before and now doesn't?
> E.g.: `static mut FOO: Option<&mut [i32]> = Some(&mut [1, 2, 3]);`

Done.

**Comment by eddyb** [comment]
> Rust 1.36 is when we got "NLL for Rust 2015", not sure if that would have an effect? Maybe this indicates a difference between HIR and MIR promotion / borrowck?

Were you testing with `--edition=2018` or not? You can also add `#![feature(nll)]` to force it but if you're trying on stable... at least on godbolt there's no way to set `RUSTC_BOOTSTRAP=1` I don't think.

Anyway I was expecting a change to MIR promotion, but maybe MIR promotion was wrong all along?
<hr/>

Okay I went and checked, and indeed it looks like MIR borrowck is the culprit here, which explains why we ended up with this bug: the MIR version of the code was just never 100% correct, so if we were trying to maintain its behavior, we were keeping original bugs around.

**Comment by RalfJung** [comment]
> it looks like MIR borrowck is the culprit here, which explains why we ended up with this bug: the MIR version of the code was just never 100% correct, so if we were trying to maintain its behavior, we were keeping original bugs around.

That makes sense.
Now I wonder if there are more such bugs...

**Comment by RalfJung** [comment]
That's great, there wasn't a single actual regression. :)
@oli-obk @eddyb how do we go on here?

**Comment by oli-obk** [comment]
@bors r+

Bugfix, simpler compiler code and no regressions, I see no reason to not merge this.

**Comment by RalfJung** [comment]
I marked this as relnotes but I am not fully sure -- I'll leave it up to the release team if they think this should be mentioned or not.
