### ISSUE TITLE
Build fails against LLVM 3.7.0

### ISSUE THREAD

**Issue by wthrowe** [rust-lang/rust#28830]
Broken by 27dd6dd3dbe92debaac7d54c8405a3d3af1c4daf in #28500.

```
/home/wthrowe/computing/rust/src/rustllvm/RustWrapper.cpp: In function ‘LLVMOpaqueValue* LLVMRustBuildLandingPad(LLVMBuilderRef, LLVMTypeRef, LLVMValueRef, unsigned int, const char*, LLVMValueRef)’:
/home/wthrowe/computing/rust/src/rustllvm/RustWrapper.cpp:954:69: error: invalid conversion from ‘LLVMValueRef {aka LLVMOpaqueValue*}’ to ‘unsigned int’ [-fpermissive]
     return LLVMBuildLandingPad(Builder, Ty, PersFn, NumClauses, Name);
                                                                     ^
/home/wthrowe/computing/rust/src/rustllvm/RustWrapper.cpp:954:69: error: invalid conversion from ‘unsigned int’ to ‘const char*’ [-fpermissive]
/home/wthrowe/computing/rust/src/rustllvm/RustWrapper.cpp:954:69: error: too many arguments to function ‘LLVMOpaqueValue* LLVMBuildLandingPad(LLVMBuilderRef, LLVMTypeRef, unsigned int, const char*)’
In file included from /usr/include/llvm/IR/Value.h:17:0,
                 from /usr/include/llvm/IR/User.h:24,
                 from /usr/include/llvm/IR/Instruction.h:22,
                 from /usr/include/llvm/IR/BasicBlock.h:19,
                 from /usr/include/llvm/IR/IRBuilder.h:21,
                 from /home/wthrowe/computing/rust/src/rustllvm/rustllvm.h:11,
                 from /home/wthrowe/computing/rust/src/rustllvm/RustWrapper.cpp:11:
/usr/include/llvm-c/Core.h:2677:14: note: declared here
 LLVMValueRef LLVMBuildLandingPad(LLVMBuilderRef B, LLVMTypeRef Ty,
              ^
```

**Comment by dotdash** [comment]
The C API for LLVM was accidentally changed in 3.7.0, this is/will be fixed in 3.7.1 and we already have that fix in our LLVM fork.

@alexcrichton do we want to add a check for 3.7.0 or just close this and pretend 3.7.0 never happened?

**Comment by wthrowe** [comment]
Feel free to close this if you decide you don't care.  I already have to apply a patch to build against my system LLVM, so it's not a big deal to me to make that patch slightly larger until 3.7.1 is released.

**Comment by alexcrichton** [comment]
Hm, so now I think I'm a little confused! This was indeed breakage that snuck into LLVM at some point which then snuck back out [around the time of the release](https://github.com/llvm-mirror/llvm/commit/41585aa62adf581f4ce31d670ae516f813736db3). I made this change in the source because our Travis builder is now installing LLVM from their apt repos which have this change. Now those repos also report that the LLVM version is 3.7.0, so I thought that this actually made its way into the 3.7.0 release and I forgot to include it.

If they update their repos every night, though, and don't bump the version just yet, that may also explain it! I'm all for supporting as many versions of LLVM as possible, but I'm not sure how to detect at compile-time the "true 3.7.0 release" vs "what's in LLVM's apt repos" now...

**Comment by dotdash** [comment]
@alexcrichton according to http://llvm.org/apt/ the packages are indeed built from the latest commit on the respective branches (see `Technical aspects` down at the bottom).

So I see three options:

1) Don't support the true 3.7.0 and move on.
2) Wait for the packages to get their patch level bumped and then add support for true 3.7.0 and accept build failures with the intermediate versions.
3) Add a test to do a compile check to see which version we have.

3 seems like overkill. And 2 is probably not really worth it, because I expect distros not to pick up 3.7.0 for their stable releases because of this API breakage. And users should really use 3.7.1 instead once that comes out.

So I'd say let's close this for now, and maybe do 2 later, if any distro does indeed package 3.7.0 in a stable release.

**Comment by alexcrichton** [comment]
Aha, that does indeed explain everything, thanks @dotdash! I agree that going with option (2) as well, and if distros haven't picked up LLVM 3.7.0 yet it may not be so bad. Closing for now and we can reevaluate in the future if 3.7.0 vs 3.7.1 comes up!
