### ISSUE TITLE
Failure of upvar inference

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust#37148]
Nested variable captures can cause a `FnMut` closure to be inferred as a `Fn` closure.

``` rust
fn main() {
    let mut x = 0;
    for u in vec![vec![]].into_iter().flat_map(|e| {
        let r = [
            (&mut |e: Vec<usize>| {
                x += 1;
                // toggling the code below makes it compile

                // let r = vec![];
                let r = vec![e].into_iter().flat_map(|e| {
                    e.into_iter().filter(|ev| true).collect::<Vec<_>>()
                }).collect();

                r
            }) as &mut FnMut(Vec<usize>) -> Vec<usize>,
        ][0](e);
        r
    }).collect::<Vec<_>>() {
    }
}

```

```
error: cannot assign to captured outer variable in an `Fn` closure
 --> <anon>:6:8
  |
6 |                 x += 1;
  |                 ^^^^^^
  |
help: consider changing this closure to take self by mutable reference
 --> <anon>:5:10
  |
5 |             (&mut |e: Vec<usize>| {
  |                   ^
```

**Comment by Kimundi** [comment]
cc @nikomatsakis

**Comment by steveklabnik** [comment]
Today's error message is slightly different:

```
error[E0594]: cannot assign to `x` which is behind a `&` reference
 --> src/main.rs:6:17
  |
6 |                 x += 1;
  |                 ^^^^^^ cannot assign

```

**Comment by Spoonbender** [comment]
Triage: resolved

Compiles on stable `rustc 1.59.0 (9d1b2106e 2022-02-23)`
I think we can close this issue.
