### ISSUE TITLE
regression: cannot borrow ... as immutable because it is also borrowed as mutable

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#135671]
- https://crater-reports.s3.amazonaws.com/beta-1.85-1/beta-2025-01-12/gh/LP-Finance-Inc.twamm/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.85-1/beta-2025-01-12/gh/Mokosha.pbrt_rust/log.txt
- https://crater-reports.s3.amazonaws.com/beta-1.85-1/beta-2025-01-12/gh/jw1912.diffable/log.txt

```
[INFO] [stdout] error[E0502]: cannot borrow `*inputs` as immutable because it is also borrowed as mutable
[INFO] [stdout]    --> examples/basic.rs:267:27
[INFO] [stdout]     |
[INFO] [stdout] 263 |           if let Some(grd) = inputs[0].grad.as_mut() {
[INFO] [stdout]     |                              -------------- mutable borrow occurs here
[INFO] [stdout] 264 | /             *grd += output_grad
[INFO] [stdout] 265 | |                 * if inputs[0].val > 0.0 {
[INFO] [stdout] 266 | |                     1.0
[INFO] [stdout] 267 | |                 } else if inputs[0].val == 0.0 {
[INFO] [stdout]     | |                           ^^^^^^^^^ immutable borrow occurs here
[INFO] [stdout] ...   |
[INFO] [stdout] 270 | |                     -1.0
[INFO] [stdout] 271 | |                 };
[INFO] [stdout]     | |_________________- mutable borrow later used here
```

**Comment by compiler-errors** [comment]
This regressed in https://github.com/rust-lang/rust/pull/133734 cc @scottmcm 

> instead -- with some asterisks for arrays and &mut that need it to be done slightly differently.

I assume that maybe there was something missing here 🤔

**Comment by compiler-errors** [comment]
Minimal:

```rust
struct Test {
    a: i32,
    b: i32,
}

fn main() {
    let mut inputs = [Test { a: 0, b: 0 }];
    
    let a = &mut inputs[0].a;
    let b = &mut inputs[0].b;

    *a = 0;
    *b = 1;
}
```

**Comment by compiler-errors** [comment]
I think we should probably revert #133734 (and the follow-up PR that fully removed the `Len` operand), and spend some more time on a solution that is both resilient to borrowck and also [to miri](https://github.com/rust-lang/rust/pull/133734#discussion_r1920948355). 

Specifically, the problem here is that the borrow-checker treated the `Len` operand specially (as a kind of fake borrow) which allowed it to be interleaved with mutable live mutable references pointing into the slice. The same does not apply to the `RawPtr` operand (`&raw const`) that we emit as part of the new lowering (all of this happens because we must read the slice length to emit a bounds check before slice accesses). Instead, in MIR borrowck, we currently treat `RawPtr` operands like borrows, so the metadata access for `let b = ...` is treated like an access conflict with the mutable reference of `let a = ...`.

After this revert, we could either think about:
* Changing the semantics of `&raw (const|mut)` operand in borrowck to not act like an access
* Emitting a new kind of special copy operand (much like `CopyForDeref`) that allows us to treat the access of an array for length access as disjoint.
* Some other solution...

However, in the mean time, I'd rather we not crunch trying to find and more importantly validate the soundness of a solution 🤔

**Comment by steffahn** [comment]
Oh wow, that minimal repro is … just normal code very deliberately supported by borrow checking for a long time!? There was no UI test for that? I’ve even shared code examples like this in the forums before … multiple times o.O

*(One example [is here](https://users.rust-lang.org/t/how-do-i-avoid-double-borrow-in-this-loop-in-a-loop/105117/4?u=steffahn), e.g. the very first code block is broken on beta. And [here’s another one](https://users.rust-lang.org/t/for-an-array-is-a-i-using-a-trait/109637/5?u=steffahn), the example `bar2` in the playground behind the last paragraph’s link.)*

I suppose, this means I should write down some of this stuff as UI tests, right?

---

By the way, tuples could be used, too… e.g. for a different minimal repro:
```rust
fn main() {
    let slice = &mut [(0, 0)][..];
    std::mem::swap(&mut slice[0].0, &mut slice[0].1);
}
```

And here’s an example similar to the last one linked above
```rust
fn foo(a: &mut [(i32, i32)], i: usize, j: usize) -> (&mut i32, &mut i32) {
    (&mut a[i].0, &mut a[j].1)
}
```

**Comment by compiler-errors** [comment]
> I suppose, this means I should write down some of this stuff as UI tests, right?

@steffahn: If you want to contribute some tests that exercise disjoint borrows, feel free to. I'll review them.

**Comment by lqd** [comment]
Fixed on nightly. Reopening to track beta backport.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/channel/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23135671.20regression.3A.20cannot.20borrow.20.2E.2E.2E.20as.20immutable.20because.20.E2.80.A6)).

@rustbot label -I-prioritize +P-critical

**Comment by apiraino** [comment]
closing since #135709 was merged

**Comment by lqd** [comment]
Reopening as https://github.com/rust-lang/rust/pull/135709 wasn't merged.

**Comment by lqd** [comment]
This was already fixed on nightly. #136352 unblocked fixing it on beta. Reopening to track beta backport of #135709.

**Comment by cuviper** [comment]
#136650 backported the fix to beta.
