### ISSUE TITLE
E0207 occurs even though the generic type is bound as an associated type

### ISSUE THREAD

**Issue by trrk** [rust-lang/rust#96339]
I tried this code:

```rust
struct Struct<T>(T);

trait Trait1<'a> {
    type Item;
}

impl<'a, T, U> Struct<T> where T: Trait1<'a, Item=U> {}
```

I expected to see this happen: Compilation completes without error.

Instead, this happened: E0207 occurs.
```
Compiling playground v0.0.1 (/playground)
error[E0207]: the type parameter `U` is not constrained by the impl trait, self type, or predicates
 --> src/lib.rs:7:13
  |
7 | impl<'a, T, U> Struct<T> where T: Trait1<'a, Item=U> {}
  |             ^ unconstrained type parameter

For more information about this error, try `rustc --explain E0207`.
error: could not compile `playground` due to previous error
```
Since U is bound as an associated type of T, it appears to be compilable code. As shown below, E0207 does not seem to occur when the trait T has no lifetime parameter
```
impl<T, U> Struct<T> where T: Iterator<Item=U> {}
```

This may be related to #67623. The intent of the post seems to be different than mine.

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-pc-windows-msvc
release: 1.60.0
LLVM version: 14.0.0
```

This also occurs in rust playground
```
Stable channel
Build using the Stable version: 1.60.0

Beta channel
Build using the Beta version: 1.61.0-beta.3
(2022-04-17 2431a974c2dcf82ba513)

Nightly channel
Build using the Nightly version: 1.62.0-nightly
(2022-04-22 f4ec0e7cff545e932ce3)
```

### Backtrace
Not provided

**Comment by ezracelli** [comment]
@trrk did you find a solution or a way around this (or if this is intentional)?

**Comment by trrk** [comment]
@ezracelli No, not really.

**Comment by estebank** [comment]
Triage: no change.

I believe this is intentional, but the diagnostic should be helping you with an alternative design :-/

**Comment by littlebenlittle** [comment]
Adding phantom data to the struct solves the issue. Is this solution general enough to be the suggested alternative? For types external to current crate, creating a wrapper with the phantom data would to it.

```rs
trait Trait1<'a> {
    type Item;
}

struct StructB<T, U> {
    t: T,
    _pd: PhantomData<U>,
}

impl<'a, T, U> StructB<T, U> where T: Trait1<'a, Item = U> {}
```
