### PR TITLE
Fix MIR typeck soundness holes

### LINKED ISSUE #69114: Static lifetimes checking regression in rustc 1.41.0
I tried [this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=551de68b1179d7eb692e6c286b0979da):

```rust
static FOO: u8 = 42;
static mut BAR: &'static u8 = &FOO;

fn main() {
    unsafe {
        println!("{}", BAR);
        foo();
        println!("{}", BAR);
    }
}

fn foo() {
    let n = 42;
    unsafe {
        BAR = &n;
    }
}
```

I expected to see this:

```
error[E0597]: `n` does not live long enough
  --> src/main.rs:15:15
   |
15 |         BAR = &n;
   |         ------^^
   |         |     |
   |         |     borrowed value does not live long enough
   |         assignment requires that `n` is borrowed for `'static`
16 |     }
17 | }
   | - `n` dropped here while still borrowed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0597`.
```

Instead, happens **undefined behavior**. Program successfully compiles in the Rust `stable 1.41.0` but fails to compile in `stable 1.40.0` (thats what I want).

### PR DESCRIPTION
**Pull request by matthewjasper**
* Check types of static items
* Always check lifetime bounds of `Copy` impls

r? @nikomatsakis 
closes #69114

### CODE REVIEW

**Comment by pnkfelix** [comment]
stealing review from niko

File: src/librustc_mir/borrow_check/type_check/mod.rs [hunk 1]
```diff
@@ -503,6 +490,31 @@ impl<'a, 'b, 'tcx> TypeVerifier<'a, 'b, 'tcx> {
             place_ty = self.sanitize_projection(place_ty, elem, place, location)
         }
 
+        if let PlaceContext::NonMutatingUse(NonMutatingUseContext::Copy) = context {
```
Comment (nikomatsakis) [inline src/librustc_mir/borrow_check/type_check/mod.rs]: The main change here is that we now do this for *all* places, right? I wonder why we didn't before? That just seems like a silly oversight to me.

**Review by nikomatsakis — APPROVED** [review]
r=me

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/131828tcompiler/74090weeklymeeting2020022054818.html#188647496) in T-compiler meeting.

accepted for beta and stable backport.

however, please do wait until this lands in nighty before initiating such a backport...

File: src/librustc_mir/borrow_check/type_check/mod.rs [hunk 2]
```diff
@@ -358,10 +359,23 @@ impl<'a, 'b, 'tcx> Visitor<'tcx> for TypeVerifier<'a, 'b, 'tcx> {
...
+                let literal_ty = constant.literal.ty.builtin_deref(true).unwrap().ty;
+
+                if let Err(terr) = self.cx.eq_types(
+                    normalized_ty,
+                    literal_ty,
+                    locations,
+                    ConstraintCategory::Boring,
+                ) {
+                    span_mirbug!(self, constant, "bad static type {:?} ({:?})", constant, terr);
+                }
```
Comment (eddyb) [inline src/librustc_mir/borrow_check/type_check/mod.rs]: This is another thing where I don't understand why the new `static` representation doesn't result in correctness by default.

Comment (eddyb) [reply src/librustc_mir/borrow_check/type_check/mod.rs]: Could MIR building inject a `UserTypeAnnotation` for `static` references/pointers? (note that I don't want to block this PR, any fix here should be equivalent, so we can clean it up later)

File: src/librustc_mir/borrow_check/type_check/mod.rs (hunk 1 above)
Comment (matthewjasper) [reply src/librustc_mir/borrow_check/type_check/mod.rs]: yes
