### ISSUE TITLE
 `#[target_feature(enable = "simd128")]` does not work properly on 1.73, but work fine on 1.72.1

### ISSUE THREAD

**Issue by mrDIMAS** [rust-lang/rust#116516]
### Code

I tried this code on 1.73:

```rust
use std::arch::wasm32::*;

#[target_feature(enable = "simd128")]
fn foo() {
	const FOO: v128 = i8x16(0, 1, -1, -1, -1, -1, -1, -1, 2, 3, -1, -1, -1, -1, -1, -1);
	println!("{:?}", FOO);
}

fn main() {
    foo();
}
```

Compiled it with `cargo build --target=wasm32-unknown-unknown`, I expected it to compile fine as on previous 1.72.1, but it gave me these errors:

```shell
$ cargo build --target=wasm32-unknown-unknown
   Compiling regression_test v0.1.0 (C:\Users\123\Desktop\regression_test)
error[E0080]: evaluation of constant value failed
 --> src\main.rs:5:20
  |
5 |     const FOO: v128 = i8x16(0, 1, -1, -1, -1, -1, -1, -1, 2, 3, -1, -1, -1, -1, -1, -1);
  |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ calling a function that requires unavailable target features: simd128

note: erroneous constant used
 --> src\main.rs:6:19
  |
6 |     println!("{:?}", FOO);
  |                      ^^^

note: erroneous constant used
 --> src\main.rs:6:19
  |
6 |     println!("{:?}", FOO);
  |                      ^^^
  |
  = note: this note originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0080`.
error: could not compile `regression_test` (bin "regression_test") due to previous error

```

### Version it worked on

It most recently worked on: 1.72.1

Output:

```shell
$ cargo build --target=wasm32-unknown-unknown
Compiling regression_test v0.1.0 (C:\Users\123\Desktop\regression_test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
```

### Version with regression

`rustc --version --verbose`:
```shell
$ rustc --version --verbose
rustc 1.73.0 (cc66ad468 2023-10-03)
binary: rustc
commit-hash: cc66ad468955717ab92600c770da8c1601a4ff33
commit-date: 2023-10-03
host: x86_64-pc-windows-msvc
release: 1.73.0
LLVM version: 17.0.2
```

### Other

I read release notes for 1.73 and couldn't find anything that could be related to this, also tried to search for an existing issue about this - no luck. This issue also broke compilation of [fast_image_resize](https://crates.io/crates/fast_image_resize) crate and transitively, Fyrox game engine.

**Comment by ehuss** [comment]
Bisected to #113720.  cc @RalfJung

**Comment by saethlin** [comment]
And then this was fixed by https://github.com/rust-lang/rust/pull/115580

**Comment by RalfJung** [comment]
Hm, why does it think that the `i8x16` function requires that target feature? That function doesn't have any `target_feature` attribute...

Cc @eduardosm

**Comment by RalfJung** [comment]
Ah, that's what changed in #115580 -- that [attribute got removed](https://github.com/rust-lang/stdarch/compare/d77878b7299dd7e286799a6e8447048b65d2a861...6100854c4b360f84da5ab25e7c75cb2080667ddc#diff-dc1b06b76cec13b102409527b8c1fc5764f721b3da84d2f97070c37816b45d1a) from a bunch of functions.

This was changed in https://github.com/rust-lang/stdarch/pull/1448. Cc @Amanieu

**Comment by Amanieu** [comment]
That was changed in stdarch specifically in response to https://github.com/rust-lang/rust/pull/113720, to avoid breaking users who were using the `const fn` already.

**Comment by RalfJung** [comment]
In principle we could probably silence this check on wasm, since we document wasm to be a target where calling functions with unsupported target features is safe.

**Comment by eduardosm** [comment]
What happens in wasm when you call a function that requires an unavailable target feature?

**Comment by RalfJung** [comment]
I am told that what happens is that the wasm runtime will refuse to even load a module that contains invalid operations, so there are two options:
- the generated code makes no use of the target feature, and so everything just works
- the generated code makes use of the target feature, and we don't even ever get to the function call since loading the wasm module already failed

**Comment by apiraino** [comment]
@mrDIMAS can you check on of the latest nightlies to verify if its works for you? (ref. [comment](https://github.com/rust-lang/rust/issues/116516#issuecomment-1751728897))

**Comment by RalfJung** [comment]
We have a special exception for wasm that allows target_feature functions to not be marked unsafe:

https://github.com/rust-lang/rust/blob/8fa7bdf191d8658e5ab670766ac0b2d40c7d83c2/compiler/rustc_codegen_ssa/src/codegen_attrs.rs#L279-L309

We should probably have the same exception in the target-feature check in the interpreter. @eduardosm do you have the time for a follow-up PR implementing that?

**Comment by mrDIMAS** [comment]
@apiraino I re-checked on latest nightly and seems to work fine:

```shell
$ rustup default nightly
info: using existing install for 'nightly-x86_64-pc-windows-msvc'
info: default toolchain set to 'nightly-x86_64-pc-windows-msvc'

  nightly-x86_64-pc-windows-msvc unchanged - rustc 1.75.0-nightly (bf9a1c8a1 2023-10-08)

$ rustup target add wasm32-unknown-unknown
info: downloading component 'rust-std' for 'wasm32-unknown-unknown'
info: installing component 'rust-std' for 'wasm32-unknown-unknown'

$ cargo build --target=wasm32-unknown-unknown
   Compiling fail v0.1.0 (C:\Users\123\Desktop\regression_test)
    Finished dev [unoptimized + debuginfo] target(s) in 0.18s
```

**Comment by eduardosm** [comment]
> do you have the time for a follow-up PR implementing that?

I will do that

**Comment by mrDIMAS** [comment]
In which version this fix will be included?

**Comment by apiraino** [comment]
> In which version this fix will be included?

Should land in stable 1.74 (around mid November), iiuc.
 
See [release cycle](https://forge.rust-lang.org/#current-release-versions) or an [easier to read calendar](https://www.whatrustisit.com/)
