### ISSUE TITLE
latest nightly won't compile old versions of winapi

### ISSUE THREAD

**Issue by dimbleby** [rust-lang/rust#49765]
As reported at carllerche/mio#832 (where I proposed having `mio` just sidestep this): old versions of `winapi` fail to build with the nightly compiler.

But @carllerche points out that this seems like a compiler regression, so let's report it here.

Various failures, different in different `winapi` releases:

2.4:
```
   Compiling winapi v0.2.4
error[E0391]: cyclic dependency detected
    --> C:\Users\dch\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.4\src\sapi.rs:1653:9
     |
1653 | /         SPGO_SRGS as i32 | SPGO_SRGS_MS_SCRIPT as i32 | SPGO_SRGS_W3C_SCRIPT as i32 |
1654 | |         SPGO_SRGS_STG_SCRIPT as i32,
     | |___________________________________^ cyclic reference
     |
note: the cycle begins when const-evaluating `sapi::SPGRAMMAROPTIONS::SPGO_SRGS_SCRIPT::{{initializer}}`...
    --> C:\Users\dch\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.4\src\sapi.rs:1653:9
     |
1653 | /         SPGO_SRGS as i32 | SPGO_SRGS_MS_SCRIPT as i32 | SPGO_SRGS_W3C_SCRIPT as i32 |
1654 | |         SPGO_SRGS_STG_SCRIPT as i32,
     | |___________________________________^
note: ...which then requires computing layout of `sapi::SPGRAMMAROPTIONS`...
    --> C:\Users\dch\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.4\src\sapi.rs:1653:9
     |
1653 |         SPGO_SRGS as i32 | SPGO_SRGS_MS_SCRIPT as i32 | SPGO_SRGS_W3C_SCRIPT as i32 |
     |         ^^^^^^^^^
     = note: ...which then again requires const-evaluating `sapi::SPGRAMMAROPTIONS::SPGO_SRGS_SCRIPT::{{initializer}}`, completing the cycle.

error: aborting due to previous error

For more information about this error, try `rustc --explain E0391`.
error: Could not compile `winapi`.

To learn more, run the command again with --verbose.
```

2.5:
```
   Compiling winapi v0.2.5
error[E0592]: duplicate definitions with name `item`
    --> C:\Users\dch\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.5\src\macros.rs:148:13
     |
148  |                pub unsafe fn $variant(&self) -> &$fieldtype {
     |   _____________-
     |  |_____________|
     | ||
149  | ||                 ::std::mem::transmute(&self.$field)
150  | ||             }
     | ||             -
     | ||_____________|
     | |______________duplicate definitions for `item`
     |                other definition for `item`
     |
    ::: C:\Users\dch\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.5\src\commctrl.rs:2496:1
     |
2496 |    UNION!(TVINSERTSTRUCTA, itemex, item, item_mut, TV_ITEMA);
     |    ---------------------------------------------------------- in this macro invocation

error[E0592]: duplicate definitions with name `item_mut`
    --> C:\Users\dch\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.5\src\macros.rs:152:13
     |
152  |                pub unsafe fn $variantmut(&mut self) -> &mut $fieldtype {
     |   _____________-
     |  |_____________|
     | ||
153  | ||                 ::std::mem::transmute(&mut self.$field)
154  | ||             }
     | ||             -
     | ||_____________|
     | |______________duplicate definitions for `item_mut`
     |                other definition for `item_mut`
     |
    ::: C:\Users\dch\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.5\src\commctrl.rs:2496:1
     |
2496 |    UNION!(TVINSERTSTRUCTA, itemex, item, item_mut, TV_ITEMA);
     |    ---------------------------------------------------------- in this macro invocation

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0592`.
```

2.6:
```
   Compiling winapi v0.2.6
error[E0080]: constant evaluation error
   --> C:\Users\dch\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.6\src\commctrl.rs:162:31
    |
162 | pub const BCN_FIRST: ::UINT = 0 - 1250;
    |                               ^^^^^^^^ attempt to subtract with overflow

error[E0080]: constant evaluation error
   --> C:\Users\dch\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.6\src\commctrl.rs:130:31
    |
130 | pub const HDN_FIRST: ::UINT = 0 - 300;
    |                               ^^^^^^^ attempt to subtract with overflow

error[E0080]: constant evaluation error
   --> C:\Users\dch\.cargo\registry\src\github.com-1ecc6299db9ec823\winapi-0.2.6\src\commctrl.rs:140:31
    |
140 | pub const TBN_FIRST: ::UINT = 0 - 700;
    |                               ^^^^^^^ attempt to subtract with overflow

... etc.
```

Compiler is `rustc 1.27.0-nightly (eeea94c11 2018-04-06)`

**Comment by retep998** [comment]
>Also noone on crater depended on this version, otherwise I would've caught it and opened a PR.

Crater would never catch it because crater does not test Windows.

**Comment by dimbleby** [comment]
Checking further, the middle breakage has made it into the stable compiler but the others have not (yet):

* `winapi` 2.4 and 2.5 fail to compile with Rust 1.25, both for that macro-y reason
* `winapi` 2.6 compiles fine

So for two of these three regressions there's still opportunity to decide - or not - that stability is more important than whatever introduced the breakage.

**Comment by retep998** [comment]
For the record that 2.5 failure is https://github.com/rust-lang/rust/issues/32247

**Comment by dimbleby** [comment]
re splitting this up:

* per @retep998 "the 2.5 breakage" was #32247.  That was fully two years ago.  I see little value in re-opening discussion on that one at this point.  
* Looks as though @oli-obk has an open pull request #49779 for "the 2.6 breakage".  So since that's where we've seen activity so far I suggest that we say that this issue covers that, at least.
* I don't yet see any movement on "the 2.4 breakage".  So if it would be helpful for you to split that off into a separate issue - fine by me.

**Comment by oli-obk** [comment]
#49779 does not address this, but I have opened #49791 to discuss it

**Comment by dimbleby** [comment]
OK. then I guess the opposite of what I said!  You already have split out "the 2.6 breakage", so what's left to track here is only "the 2.4 breakage".

**Comment by durka** [comment]
The "0.2.4 breakage" hit my (unpublished) crate which has been working since 1.0: https://github.com/haptics-nri/nri/blob/f6347ff03feb51157558d1620078beb2a2862c88/sys/bluefox-sys/src/lib.rs#L234-L245

A warning cycle would have been nice.

This kind of enum comes up all the time in native bindings, so how are we supposed to work around it?

**Comment by eddyb** [comment]
@durka The cyclical enum definitions only worked by accident / hackily (under very odd conditions), if only @nikomatsakis had gotten the chance to remove them before 1.0...
But @oli-obk has come up with a slightly more general hack to keep it working (#50072).
