### ISSUE TITLE
Trait implementations error message confusing when taking a reference of a reference

### ISSUE THREAD

**Issue by x3ro** [rust-lang/rust#146031]
### Code

```Rust
trait GenericImage {}
trait Canvas {}

impl<I> Canvas for I
where
    I: GenericImage,
{}


pub fn draw<C>(canvas: &mut C)
where
    C: Canvas,
{
    draw_filled_rect_mut(&mut canvas);
}

pub fn draw_filled_rect_mut<C>(_canvas: &mut C)
where
    C: Canvas,
{
    todo!()
}
```

### Current output

```Shell
error[E0277]: the trait bound `&mut C: Canvas` is not satisfied
  --> src/lib.rs:14:26
   |
14 |     draw_filled_rect_mut(&mut canvas);
   |     -------------------- ^^^^^^^^^^^ the trait `GenericImage` is not implemented for `&mut C`
   |     |
   |     required by a bound introduced by this call
   |
help: this trait has no implementations, consider adding one
  --> src/lib.rs:1:1
   |
1  | trait GenericImage {}
   | ^^^^^^^^^^^^^^^^^^
note: required for `&mut C` to implement `Canvas`
  --> src/lib.rs:4:9
   |
4  | impl<I> Canvas for I
   |         ^^^^^^     ^
5  | where
6  |     I: GenericImage,
   |        ------------ unsatisfied trait bound introduced here
note: required by a bound in `draw_filled_rect_mut`
  --> src/lib.rs:19:8
   |
17 | pub fn draw_filled_rect_mut<C>(_canvas: &mut C)
   |        -------------------- required by a bound in this function
18 | where
19 |     C: Canvas,
   |        ^^^^^^ required by this bound in `draw_filled_rect_mut`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` (lib) due to 1 previous error
```

### Desired output

```Shell
error[E0277]: the trait bound `&mut C: Canvas` is not satisfied
  --> src/lib.rs:14:26
   |
14 |     draw_filled_rect_mut(&mut canvas);
   |     -------------------- ^^^^^^^^^^^ the trait `GenericImage` is not implemented for `&mut C`
   |     |
   |     required by a bound introduced by this call
   |
help: The trait is implemented for `canvas`, but not `&mut canvas`.
```

### Other cases

```Rust

```

### Rust Version

```Shell
Tested in playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2024&gist=beb18623866b4914d0da0fce16a2e4f0

Build using the Nightly version: 1.91.0-nightly
(2025-08-29 fe55364329579d361b1a)
```
