### ISSUE TITLE
Change "A non-empty glob must import something with the glob's visibility" to be a lint?

### ISSUE THREAD

**Issue by fpoli** [rust-lang/rust#62334]
Consider the following three examples: A and C are accepted and B has a compilation error. However, the message reported in B looks more like a lint than a compilation error.

A consequence of this error is that adding a non-public function to a module (e.g. the `bar` in B) may break code that imports from that module. This causes surprises when refactoring.

Shouldn't "A non-empty glob must import something with the glob's visibility" be a lint?

The original discussion is here: https://users.rust-lang.org/t/a-non-empty-glob-must-import-something-with-the-globs-visibility-uhhh-okay-but-why

### A
```
pub use self::a::*;
mod a {
    fn foo() {}
}
```

### B
```
// ERROR: A non-empty glob must import something with the glob's visibility
pub use self::b::*;
mod b {
    fn foo() {}
    pub(super) fn bar() {}
}
```

### C
```
// okay: there's a pub item
pub use self::c::*;
mod c {
    fn foo() {}
    pub(super) fn bar() {}
    pub fn baz() {}
}
```

**Comment by petrochenkov** [comment]
The error was introduced in https://github.com/rust-lang/rust/pull/35894 as a part of import modularization, and discussed in one of the related issues, but I can't find where exactly.

The error was introduced by analogy with errors for single imports (and just to be conservative):
```rust
mod m {
    fn f() {}
}

use m::f; // Doesn't import anything and therefore reports an error.
use m::*; // Doesn't import anything and therefore reports an error.
```

The error is not technically necessary, and we should be able to report it as a lint for glob imports while keeping it an error for single imports.

**Comment by fpoli** [comment]
Would this be a "good first issue", or is it complex to fix?

**Comment by petrochenkov** [comment]
No, not complex.
- Find where "non-empty glob must import something" is reported.
- Replace `span_err` with `buffer_lint(UNUSED_IMPORTS, ...)`.

**Comment by traxys** [comment]
I want to do this issue but the problem I have is with a test (ui/imports/reexports) that checks for this error, I don't know the compiler structure so I don't know when compiling this file the lint will not be reported because of the other errors or not. Else I changed the `span_err` to `buffer_lint`
