### ISSUE TITLE
Regression in `rgb` with `as_mut_slice`

### ISSUE THREAD

**Issue by JonathanBrouwer** [rust-lang/rust#152961]
### Code

Cargo.toml
```toml
[package]
name = "rust-test"
version = "0.1.0"
edition = "2024"

[dependencies]
resvg = "=0.34.1"
```

main.rs
```rust
extern crate resvg;
fn main() { }
```

I'll try to make a smaller reproducer

### Regression

This compiles on nightly 2026-02-21, but fails on nightly 2026-02-22.

```
error[E0308]: mismatched types
  --> /home/jonathan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/resvg-0.34.1/src/filter/iir_blur.rs:63:22
   |
63 |     gaussian_channel(data, &d, 0, buf);
   |     ---------------- ^^^^ expected `&mut [u8]`, found `&mut [RGBA<u8>]`
   |     |
   |     arguments to this function are incorrect
   |
   = note: expected mutable reference `&mut [u8]`
              found mutable reference `&mut [rgb::RGBA<u8>]`
note: function defined here
  --> /home/jonathan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/resvg-0.34.1/src/filter/iir_blur.rs:69:4
   |
69 | fn gaussian_channel(data: &mut [u8], d: &BlurData, channel: usize, buf: &mut Vec<f64>) {
   |    ^^^^^^^^^^^^^^^^ ---------------

```

### Cause

Found because rust-timer failed in https://github.com/rust-lang/rust/pull/152934, so this has serious impact.
Locally bisected to PR https://github.com/rust-lang/rust/pull/151603

CC @jhpratt @GrigorenkoPV

**Comment by JonathanBrouwer** [comment]
Smaller reproducer, using the latest version of the popular `rgb` crate:
```rust
use rgb::RGBA8;
use rgb::ComponentSlice;

pub fn a(data: &mut [RGBA8]) {
    b(data.as_mut_slice());
}

fn b(_b: &mut [u8]) { }
```
Before the PR, this produces:
```
warning: a method with this name may be added to the standard library in the future
 --> src/lib.rs:5:12
  |
5 |     b(data.as_mut_slice());
  |            ^^^^^^^^^^^^
  |
  = warning: once this associated item is added to the standard library, the ambiguity may cause an error or change in behavior!
  = note: for more information, see issue #48919 <https://github.com/rust-lang/rust/issues/48919>
  = help: call with fully qualified syntax `as_mut_slice(...)` to keep using the current method
  = note: `#[warn(unstable_name_collisions)]` (part of `#[warn(future_incompatible)]`) on by default
help: add `#![feature(str_as_str)]` to the crate attributes to enable `rgb::bytemuck::core::slice::<impl [T]>::as_mut_slice`
  |
1 + #![feature(str_as_str)]
  |
```

After the PR, this produces:
```
error[E0308]: mismatched types
 --> src/lib.rs:5:7
  |
5 |     b(data.as_mut_slice());
  |     - ^^^^^^^^^^^^^^^^^^^ expected `&mut [u8]`, found `&mut [Rgba<u8>]`
  |     |
  |     arguments to this function are incorrect
  |
  = note: expected mutable reference `&mut [u8]`
             found mutable reference `&mut [RGBA<u8>]`
note: function defined here
 --> src/lib.rs:8:4
  |
8 | fn b(_b: &mut [u8]) { }
  |    ^ -------------
```

**Comment by JonathanBrouwer** [comment]
@theemathas This is a regression from nightly-to-nightly, but there is no label for that, how do we label that?

**Comment by theemathas** [comment]
@JonathanBrouwer The code used to compile on stable, and it doesn't compile on nightly. So regression-from-stable-to-nightly is the correct label, I think. Not sure what you mean by "regression from nightly-to-nightly".
