### PR TITLE
Rollup of 16 pull requests

### PR DESCRIPTION
**Pull request by Manishearth**
Successful merges:

 - #61871 (Don't use lift to detect local types)
 - #61883 (`non_ascii_idents` lint (part of RFC 2457))
 - #61922 (Don't store locals that have been moved from in generators)
 - #61995 (rustc: use a separate copy of P for HIR than for AST.)
 - #62026 (Final nail in `rand 0.4` coffin)
 - #62039 (Remove needless lifetimes (rustc))
 - #62099 (Remove io::Result from syntax::print)
 - #62103 (Add debug assertions to write_bytes and copy*)
 - #62133 (Feature gate `rustc` attributes harder)
 - #62161 (Add missing links for TryFrom docs)
 - #62177 (Move some tests in src/test/compile-fail -> src/test/ui)
 - #62183 (std: Move a process test out of libstd)
 - #62186 (Add missing type urls in Into trait)
 - #62196 (Add Vec::leak)
 - #62199 (import gdb for explicit access to gdb.current_objfile())
 - #62244 (Update rustfmt to 1.3.1)

Failed merges:

 - #62243 (Improve documentation for built-in macros)

r? @ghost

### CODE REVIEW

**Comment by mati865** [comment]
```
1	error: extern location for std does not exist: 
2	
3	error[E0463]: can't find crate for `std`
+	   |
+	   = note: the `i586-unknown-linux-gnu` target may not be installed
4	
5	error: aborting due to 2 previous errors
6	
```

Looks like introduced by https://github.com/rust-lang/rust/pull/62177
