### ISSUE TITLE
`FnPtr` blanket impls cause "multiple applicable items in scope" for unrelated types.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#109892]
*Note: the below reduction originally came from a `use num_traits::Float;` + `0.0.max(x)` **in the wild**.*

I haven't found a way to demonstrate this outside of the "float inference vars + `Ord` method" combo, but:
```rust
trait MyCmp {
    fn cmp(&self) {}
}
impl MyCmp for f32 {}

fn main() {
    0.0.cmp();
}
```
works on stable (`1.68.2`) and beta (`1.69.0-beta.6`), and errors on nightly with:
```
error[E0034]: multiple applicable items in scope
 --> src/main.rs:7:9
  |
7 |     0.0.cmp();
  |         ^^^ multiple `cmp` found
  |
note: candidate #1 is defined in an impl of the trait `MyCmp` for the type `f32`
 --> src/main.rs:2:5
  |
2 |     fn cmp(&self) {}
  |     ^^^^^^^^^^^^^
  = note: candidate #2 is defined in an impl of the trait `Ord` for the type `F`
note: candidate #3 is defined in the trait `Iterator`
 --> /rustc/3a8a131e9509c478ece1c58fe0ea2d49463d2300/library/core/src/iter/traits/iterator.rs:3533:5
help: disambiguate the method for candidate #1
  |
7 |     MyCmp::cmp(&0.0);
  |     ~~~~~~~~~~~~~~~~
help: disambiguate the method for candidate #2
  |
7 |     Ord::cmp(&0.0);
  |     ~~~~~~~~~~~~~~
help: disambiguate the method for candidate #3
  |
7 |     Iterator::cmp(0.0);
  |     ~~~~~~~~~~~~~~~~~~
```

Even though it doesn't show the source for candidate `#2`, I'm almost certain it's this:
https://github.com/rust-lang/rust/blob/f13ccefb5b35af3dbb40a7bbdd64a3216d949664/library/core/src/ptr/mod.rs#L2064-L2070
from (cc @lcnr @oli-obk):
* https://github.com/rust-lang/rust/pull/99531
* https://github.com/rust-lang/rust/pull/108080

On the original PR I left comments like https://github.com/rust-lang/rust/pull/99531#issuecomment-1194688090, trying to rectify the issues with the original approach, but they didn't go anywhere and the version that one in the end is the (arguably) more fragile original one, that uses blanket `impl`s and works around their unwanted interactions.

It's possible in this case all it takes is checking for "float inference vars" and making sure they can never be considered to implement `FnPtr`, but I'm worried there might be other edge cases lurking in the shadows.

Also, did both of those PRs skip crater? I feel like this shouldn't be that hard to hit in the wild.

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.23109892.20.60FnPtr.60.20blanket.20impls.20cause.20.22multiple.20applicable.20it.E2.80.A6)).

@rustbot label -I-prioritize +P-high
