### ISSUE TITLE
Cell::swap(&cell_t, &mut t) should suggest Cell::from_mut not Cell::replace(...)

### ISSUE THREAD

**Issue by QuineDot** [rust-lang/rust#128587]
### Code

```Rust
use std::cell::Cell;

fn example<T>(cell: &Cell<T>, other: &mut T) {
    cell.swap(other);
}
```

### Current output

```Shell
error[E0308]: mismatched types
   --> src/lib.rs:4:15
    |
3   | fn example<T>(cell: &Cell<T>, other: &mut T) {
    |            - found this type parameter
4   |     cell.swap(other);
    |          ---- ^^^^^ expected `&Cell<T>`, found `&mut T`
    |          |
    |          arguments to this method are incorrect
    |
    = note:      expected reference `&Cell<T>`
            found mutable reference `&mut T`
note: method defined here
   --> /playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cell.rs:451:12
    |
451 |     pub fn swap(&self, other: &Self) {
    |            ^^^^
note: you might have meant to use method `replace`
   --> /playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cell.rs:494:5
    |
494 |     pub fn replace(&self, val: T) -> T {
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

### Desired output

```Shell
error[E0308]: mismatched types
   --> src/lib.rs:4:15
    |
3   | fn example<T>(cell: &Cell<T>, other: &mut T) {
    |            - found this type parameter
4   |     cell.swap(other);
    |          ---- ^^^^^ expected `&Cell<T>`, found `&mut T`
    |          |
    |          arguments to this method are incorrect
    |
    = note:      expected reference `&Cell<T>`
            found mutable reference `&mut T`
note: method defined here
   --> /playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/cell.rs:451:12
    |
451 |     pub fn swap(&self, other: &Self) {
    |            ^^^^
help: consider calling `Cell::from_mut` here:
    |
4   -     cell.swap(other);
4   +     cell.swap(Cell::from_mut(other));
```

### Rationale and extra context

The desired update is what the programmer intended to do:
```
use std::cell::Cell;

fn example<T>(cell: &Cell<T>, other: &mut T) {
    cell.swap(Cell::from_mut(other));
}
```
Moreover, you can't move the `T` from behind the `&mut T`, so the current help is not actionable.

[Motivating URLO topic.](https://users.rust-lang.org/t/any-way-to-safely-swap-cell-t-with-t/115349)

### Rust Version

```Shell
Rust playground

Stable channel
Build using the Stable version: 1.80.0

Beta channel
Build using the Beta version: 1.81.0-beta.2
(2024-07-25 08328a323ecd80b443a8)

Nightly channel
Build using the Nightly version: 1.82.0-nightly
(2024-08-02 fd8d6fbe505ecf913f5e)
```

### Anything else?

This could be generalized to suggest `Cell::from_mut` wherever a `&mut T` is passed and a `&Cell<T>` would work.
