### ISSUE TITLE
regression: error[E0570]: `"stdcall"`/`"fastcall"` is not a supported ABI for the current target

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#134712]
1. https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/gh/ChlorideCull.chcl_now_playing/log.txt
2. https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/gh/PocketRelay.me3-offline-plugin/log.txt
3. https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/gh/Sgeo.rwg_to_rwx/log.txt
4. https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/gh/plegat.RLaminateAnalysis/log.txt
5. https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/gh/sergemalo.sm-checkers-engine/log.txt
6. https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/gh/weslenng-labs.visual-basic-rs/log.txt
7. https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/reg/dx_core-0.3.0/log.txt
8. https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/reg/miniblink-0.3.0/log.txt

```
error[E0570]: `"stdcall"` is not a supported ABI for the current target
```

and presumably related:

1. https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/reg/vtable_gen-1.1.0/log.txt
2. https://crater-reports.s3.amazonaws.com/beta-1.84.0-4-retry2/beta-2024-12-08/gh/MrElectrify.vtable_gen/log.txt

```
error[E0570]: `"fastcall"` is not a supported ABI for the current target
```

### Version it worked on

It most recently worked on: 1.83.0

### Version with regression

Using rustc 1.84.0-beta.4 in crater https://github.com/rust-lang/rust/issues/134138.

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

**Comment by compiler-errors** [comment]
This regressed in #129935. 

This crater run may have missed some crates due to a recently discovered regression in crater which was reporting a large number of "unknown" results (https://rust-lang.zulipchat.com/#narrow/channel/242791-t-infra/topic/crater.20returning.20unknown).

cc @RalfJung. I assume the decision shouldn't really change (I still think we should make this FCW a hard error), but perhaps we should announce to more people that their crates are gonna break.

**Comment by cuviper** [comment]
If you're looking for people to notify, a few more showed up in the rustdoc run:

1. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/IDragnev.oppa/log.txt
2. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/K0enM.sup/log.txt
3. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/Zerx0r.rs_ppid_spoof_hollow/log.txt
4. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/bondTM.shogi/log.txt
5. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/chuckries.rust-com/log.txt
6. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/den-mentiei.prima/log.txt
7. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/dev-nolant.Rust-Command-Line-Tool/log.txt
8. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/elipmoc.rust_dxlib/log.txt
9. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/iamtyler.iocp.rs/log.txt
10. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/loctranbao.ownping/log.txt
11. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/lumenian.ping/log.txt
12. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/shirshak55.ping/log.txt
13. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/snf.rust_crashes/log.txt
14. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/tspivey.tdsr-server/log.txt
15. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/vassjozsef.nvapi-rust/log.txt
16. https://crater-reports.s3.amazonaws.com/beta-rustdoc-1.84.0-4-retry/beta-2024-12-08/gh/vrnvu.pong/log.txt

**Comment by RalfJung** [comment]
Looking at the crates.io regressions, the only new ones are
- dx_core: hasn't been updated in 9 years
- webview2: bindings for "Microsoft Edge WebView2 control", so anyway Windows-only

**Comment by apiraino** [comment]
> So no action necessary here. I don't usually file issues for things not on crates.io;

just mention if you want to add something in the release notes as a "FIY" in the compat notes

**Comment by RalfJung** [comment]
This should of course be listed in the compatibility notes, but I assume that is already planned anyway.

**Comment by ChrisDenton** [comment]
I'd guess most of the real world failures will be on Windows. Having `stdcall` and `fastcall` mean `C` on x64 is the C/C++ behaviour.

**Comment by RalfJung** [comment]
There's no behavior change on Windows. Only targets that are neither Windows nor 32bit-x86 are affected by this.

**Comment by Mark-Simulacrum** [comment]
Closing as won't fix in favor of existing relnotes item.
