### ISSUE TITLE
error[E0599]: no method named `write_all` found for struct `File` in the current scope

### ISSUE THREAD

**Issue by psumbera** [rust-lang/rust#118862]
While building latest Rust it fails like this:

```
error[E0599]: no method named `write_all` found for struct `File` in the current scope
   --> src/bin/main.rs:134:21
    |
134 |             t!(file.write_all(lines.join("\n").as_bytes()));
    |                     ^^^^^^^^^ method not found in `File`
   --> /builds2/psumbera/rust-lang-build/library/std/src/io/mod.rs:1620:8
    |
    = note: the method is available for `File` here
    |
    = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
    |
8   + use std::io::Write;
    |

For more information about this error, try `rustc --explain E0599`.
error: could not compile `bootstrap` (bin "bootstrap") due to previous error
warning: build failed, waiting for other jobs to finish...

```

419b26931b73209bfafdb9938c09e12b9d650613 is the first bad commit
commit 419b26931b73209bfafdb9938c09e12b9d650613
Author: David Tolnay [<dtolnay@gmail.com>](mailto:dtolnay@gmail.com)
Date:   Wed Nov 29 23:02:05 2023 -0800

    Add if_let_guard and let_chains pretty printer tests

 tests/ui/macros/stringify.rs | 21 ++++++++++++++++++++-
 1 file changed, 20 insertions(+), 1 deletion(-)

**Comment by psumbera** [comment]
@dtolnay do you have any idea about this? Thank you!

**Comment by dtolnay** [comment]
I am skeptical about that bisect. That commit is _only adding tests_. I do not see any way that it could cause bootstrap to fail to build.
