### ISSUE TITLE
rustc -o /dev/null attempts to create a temporary directory in /dev

### ISSUE THREAD

**Issue by pdebelak** [rust-lang/rust#111157]
Compiling with `-o /dev/null` in order to see any compilation errors fails with a permissions error:

```
error:` couldn't create a temp dir: Permission denied (os error 13) at path "/dev/rmetaXXXXXX
```

I'm trying to use emacs to edit rust code following the examples in the rust book and flycheck (which is a linter) runs `rustc` with `-o /dev/null --emit=mir` to avoid creating any binary (see [the flycheck code here](https://github.com/flycheck/flycheck/blob/master/flycheck.el#L11648)). This works fine in rustc versions between 1.18.0 and 1.63.0 but breaks in versions 1.64.0 or later.

```
$ cat main.rs 
fn main() {
    println!("Hello, world!");
}
$ rustup run 1.63.0 rustc -o /dev/null --emit=mir main.rs 
$ rustup run 1.64.0 rustc -o /dev/null --emit=mir main.rs 
error: couldn't create a temp dir: Permission denied (os error 13) at path "/dev/rmeta4bBAfw"

error: aborting due to previous error

$ rustup run nightly rustc -o /dev/null --emit=mir main.rs 
error: couldn't create a temp dir: Permission denied (os error 13) at path "/dev/rmetajHRil9"

error: aborting due to previous error

$ rustup run stable rustc -o /dev/null --emit=mir main.rs 
error: couldn't create a temp dir: Permission denied (os error 13) at path "/dev/rmetaimL43B"

error: aborting due to previous error

$ rustup run stable rustc --version --verbose
rustc 1.69.0 (84c898d65 2023-04-16)
binary: rustc
commit-hash: 84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc
commit-date: 2023-04-16
host: x86_64-unknown-linux-gnu
release: 1.69.0
LLVM version: 15.0.7
$ rustup run nightly rustc --version --verbose
rustc 1.71.0-nightly (a368898de 2023-05-02)
binary: rustc
commit-hash: a368898de758e1b8def6c9060044a5b40eb79e84
commit-date: 2023-05-02
host: x86_64-unknown-linux-gnu
release: 1.71.0-nightly
LLVM version: 16.0.2
```

I expected to see this happen: I'd expect compiling to `/dev/null` to either not attempt to create a temporary directory or to create it in `/tmp` instead of `/dev`.

Instead, this happened: Compiling to `/dev/null` attempts to create a directory in `/dev` but lacks the permissions to do so.

**Comment by pdebelak** [comment]
If there's a different command that `flycheck` should be running for newer versions of `rustc` instead let me know and I can open an issue over there.

**Comment by albertlarsan68** [comment]
It is because you are asking to emit mir, that is not available in a single file.

**Comment by pdebelak** [comment]
@albertlarsan68 I get the same result for all options of `--emit` except `dep-info`:

```
$ emits="asm llvm-bc llvm-ir obj metadata link dep-info mir"
$ for emit in $emits; do
> rustc -o /dev/null --emit "$emit" main.rs && echo "Successfully emitted $emit" || echo "Failed to emit $emit"
> done
error: couldn't create a temp dir: Operation not permitted (os error 1) at path "/dev/rmeta9vkboa"

error: aborting due to previous error

Failed to emit asm
error: couldn't create a temp dir: Operation not permitted (os error 1) at path "/dev/rmetayrfxZD"

error: aborting due to previous error

Failed to emit llvm-bc
error: couldn't create a temp dir: Operation not permitted (os error 1) at path "/dev/rmetaZ9nLU5"

error: aborting due to previous error

Failed to emit llvm-ir
error: couldn't create a temp dir: Operation not permitted (os error 1) at path "/dev/rmetaksTXms"

error: aborting due to previous error

Failed to emit obj
error: couldn't create a temp dir: Operation not permitted (os error 1) at path "/dev/rmetaM31JYS"

error: aborting due to previous error

Failed to emit metadata
error: couldn't create a temp dir: Operation not permitted (os error 1) at path "/dev/rmeta1PPnSR"

error: aborting due to previous error

Failed to emit link
Successfully emitted dep-info
error: couldn't create a temp dir: Operation not permitted (os error 1) at path "/dev/rmetajaS5Hc"

error: aborting due to previous error

Failed to emit mir
```

**Comment by bjorn3** [comment]
We try to write our temporary files to a temporary subdirectory of the output dir to ensure that we can atomically rename temporary files to their final name. If we created them in `/tmp`, it may be possible that this is on a different filesystem from the destination (in this case devfs) and thus doesn't allow atomic renames. Without atomic renames it is possible that another rustc would attempt to read the file while it is partially written and would crash as a result.

**Comment by pdebelak** [comment]
@bjorn3 - Okay, so if flycheck wants to collect compilation errors without creating any artifacts is there a way to do that using `rustc`? It seems like the answer is that this is no longer possible, is that correct?

**Comment by bjorn3** [comment]
Looks like it. In any case note that `cargo check` does `--emit metadata` which for libraries emits a `.rmeta` file with all information necessary to check any crate that depends on this library and for executables produces an empty `.rmeta` file. Unlike `--emit mir`, `--emit metadata` it doesn't do any codegen, making it a lot faster. As such I did recommend using `--emit metadata` with a temporary `.rmeta` file somewhere as output and then deleting the temporary file.

**Comment by Enselic** [comment]
Triage: Let's close as works as designed/wont fix.
