### PR TITLE
Fixed E0529's label and unit test

### LINKED ISSUE #36195: E0529 needs to be updated to new format
From: src/test/compile-fail/E0529.rs

E0529 needs a span_label, updating it from:

```
error[E0529]: expected an array or slice, found `f32`
  --> src/test/compile-fail/E0529.rs:16:9
   |
16 |         [a, b] => { //~ ERROR E0529
   |         ^^^^^^
```

To:

```
error[E0529]: expected an array or slice, found `f32`
  --> src/test/compile-fail/E0529.rs:16:9
   |
16 |         [a, b] => { //~ ERROR E0529
   |         ^^^^^^ pattern cannot match `f32` type
``

### PR DESCRIPTION
**Pull request by EugeneGonzalez**
Fixes #36195 part of #35233.

This is ready for review, but will likely fail Travis due to #36138. I changed the wording of the label, so feedback on that would be appreciated.

r? @jonathandturner

### CODE REVIEW

**Comment by jonathandturner** [comment]
Thanks for the PR!

@bors r+ rollup
