### PR TITLE
rustbuild: Update LLVM and enable ThinLTO

### LINKED ISSUE #45511: ThinLTO generates bad DWARF for libtest
nightly-2017-10-24 contains a libtest with bad DWARF:

```
$ /usr/bin/dwarfdump -i ~/.rustup/toolchains/nightly-2017-10-24-x86_64-unknown-linux-gnu/lib/libtest-f00235123717627d.so > /dev/null

/usr/bin/dwarfdump ERROR:  reference form with no valid local ref?!, offset=<0x00003085>:  DW_DLE_ATTR_FORM_OFFSET_BAD (119)
```

I can reproduce this if I recompile libtest locally:
```
$ cd src/libtest
$ RUSTFLAGS="-g -Ccodegen-units=16 -Zthinlto" cargo +nightly-2017-10-24 build --release
   Compiling term v0.0.0
   Compiling getopts v0.2.15
   Compiling test v0.0.0
    Finished release [optimized] target(s) in 8.77 secs
$ /usr/bin/dwarfdump -i ../target/release/libtest.so > /dev/null

/usr/bin/dwarfdump ERROR:  reference form with no valid local ref?!, offset=<0x0001b758>:  DW_DLE_ATTR_FORM_OFFSET_BAD (119)
```

The problem can be fixed by disabling thinlto (and keeping the codegen units is ok).

I noticed this with nightly-2017-10-24 because it is the first nightly compiled with thinlto, but the problem also occurs if I compile libtest with thinlto enabled using earlier compilers (eg nightly-2017-10-17).

Inspecting the DWARF, a DIE at that local ref offset does exist in another codegen unit, so the problem seems to be that we should be using a global ref instead.

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit updates LLVM to fix #45511 (https://reviews.llvm.org/D39981) and
also reenables ThinLTO for libtest now that we shouldn't hit #45768. This also
opportunistically enables ThinLTO for libstd which was previously blocked
(#45661) on test failures related to debuginfo with a presumed cause of #45511.

Closes #45511

### CODE REVIEW

**Comment by kennytm** [comment]
`dist-arm-linux`, cannot link `stage1-rustc` (libsyntax) due to multiple definitions of `__aeabi_fdiv`, legit.

<details>

```
[01:01:20] [1m[31merror(B[m[1m: linking with `arm-unknown-linux-gnueabi-gcc` failed: exit code: 1(B[m
[01:01:20]   (B[m[1m[34m|(B[m
[01:01:20]   (B[m[1m[34m= (B[m[1mnote(B[m: "arm-unknown-linux-gnueabi-gcc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/arm-unknown-linux-gnueabi/lib" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax0-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax1-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax10-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax11-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax12-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax13-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax14-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax15-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax2-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax3-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax4-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax5-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax6-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax7-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax8-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.syntax9-c38c37e60f6bc02ccbfb3c47153244d8.rs.rcgu.o" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/libsyntax-da324b40dbd1707b.so" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.crate.metadata.rcgu.o" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps/syntax-da324b40dbd1707b.crate.allocator.rcgu.o" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-nodefaultlibs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/release/deps" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/arm-unknown-linux-gnueabi/lib" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps" "-l" "rustc_errors-38dc6f56c6f3e470" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps" "-l" "syntax_pos-e1b64a531751f08f" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/arm-unknown-linux-gnueabi/lib" "-l" "term-73d4291f5f301774" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps" "-l" "rustc_cratesio_shim-d04f99081b870673" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps" "-l" "rustc_data_structures-1f05fe4a3e3866a7" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1-rustc/arm-unknown-linux-gnueabi/release/deps" "-l" "serialize-7e0f7d3708829388" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/stage1/lib/rustlib/arm-unknown-linux-gnueabi/lib" "-l" "std-9a578f4fbc9ae048" "-Wl,-Bstatic" "/tmp/rustc.x1VvxgXhooxy/libcompiler_builtins-bbd71924f060874e.rlib" "-Wl,-Bdynamic" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "pthread" "-l" "gcc_s" "-l" "c" "-l" "m" "-l" "rt" "-l" "pthread" "-l" "util" "-l" "util" "-shared" "-Wl,-rpath,$ORIGIN/../lib"(B[m
[01:01:21]   (B[m[1m[34m= (B[m[1mnote(B[m: /tmp/rustc.x1VvxgXhooxy/libcompiler_builtins-bbd71924f060874e.rlib(compiler_builtins-bbd71924f060874e.compiler_builtins10-579b32a8609b6b5b1087dd35d80b481e.rs.rcgu.o): In function `compiler_builtins::float::div::__divsf3::__aeabi_fdiv':(B[m
[01:01:21]           /checkout/src/rustc/compiler_builtins_shim/../../libcompiler_builtins/src/float/div.rs:446: multiple definition of `__aeabi_fdiv'(B[m
[01:01:21]           /tmp/rustc.x1VvxgXhooxy/libcompiler_builtins-bbd71924f060874e.rlib(divsf3.o):divsf3.c:(.text.__divsf3+0x0): first defined here(B[m
[01:01:21]           collect2: error: ld returned 1 exit status(B[m
[01:01:21]           (B[m
[01:01:21] 
[01:01:21] [1m[31merror(B[m[1m: aborting due to previous error(B[m
[01:01:21] 
[01:01:21] [m[m[31m[1merror:[m Could not compile `syntax`.
```

</details>

**Comment by kennytm** [comment]
cc #44899 — This PR should contain the fix for that issue as well.

**Comment by alexcrichton** [comment]
Looks like that was accidentally caused by https://github.com/rust-lang-nursery/compiler-builtins/pull/206

**Comment by alexcrichton** [comment]
in that we forgot this commit -- https://github.com/rust-lang-nursery/compiler-builtins/commit/02b3734a5ba6de984eb5a02c50860cc014e58d56

**Comment by alexcrichton** [comment]
@bors: retry

@kennytm I think that's the second (hopefully) spurious failure related to sanitizers, right?

**Comment by kennytm** [comment]
@alexcrichton  Given that ThinLTO also affects sanitizers (#45220), I'm not so sure it is spurious or not. Let's see what bors says.

**Comment by kennytm** [comment]
Same error, should be legit @alexcrichton

**Comment by alexcrichton** [comment]
Looks like this isn't precisely the previous issue, I'm going to open a new issue and ignore the test.

**Comment by kennytm** [comment]
@bors retry 3 hour timeout

I feel that the build time is getting slower again recently.

**Comment by alexcrichton** [comment]
Turns out [this symbol](https://github.com/rust-lang/rust/blob/71da1c21ebc79f19e749344c8b4e2c13f533872e/src/libstd/sys/windows/thread_local.rs#L202-L207) is getting internalized when testing. If that's gone tls dtors don't run, and it looks like tls dtors aren't running! Now to figure out why it's being internalized...

**Comment by alexcrichton** [comment]
Turns out using LTO on Windows means you currently don't run any thread local destructors at all. Using ThinLTO just exposed this. Let's try again!

@bors: r=Mark-Simulacrum

**Comment by kennytm** [comment]
The `-C lto` flag in the new test conflicts with `-C prefer-dynamic`.

<details>

```
[00:50:01] ---- [run-pass] run-pass/lto-still-runs-thread-dtors.rs stdout ----
[00:50:01] 	
[00:50:01] error: compilation failed!
[00:50:01] status: exit code: 101
[00:50:01] command: "/checkout/obj/build/x86_64-unknown-linux-gnu/stage2/bin/rustc" "/checkout/src/test/run-pass/lto-still-runs-thread-dtors.rs" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass" "--target=x86_64-unknown-linux-gnu" "-C" "prefer-dynamic" "-o" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/lto-still-runs-thread-dtors.stage2-x86_64-unknown-linux-gnu" "-Crpath" "-O" "-Lnative=/checkout/obj/build/x86_64-unknown-linux-gnu/native/rust-test-helpers" "-C" "lto" "-L" "/checkout/obj/build/x86_64-unknown-linux-gnu/test/run-pass/lto-still-runs-thread-dtors.stage2-x86_64-unknown-linux-gnu.aux"
[00:50:01] stdout:
[00:50:01] ------------------------------------------
[00:50:01] 
[00:50:01] ------------------------------------------
[00:50:01] stderr:
[00:50:01] ------------------------------------------
[00:50:01] thread '<unnamed>' panicked at 'Box<Any>', /checkout/src/librustc_trans/back/write.rs:585:28
[00:50:01] note: Run with `RUST_BACKTRACE=1` for a backtrace.
[00:50:01] error: cannot prefer dynamic linking when performing LTO
[00:50:01] 
[00:50:01] note: only 'staticlib', 'bin', and 'cdylib' outputs are supported with LTO
[00:50:01] 
[00:50:01] error: aborting due to previous error
```

</details>

**Comment by alexcrichton** [comment]
@bors: r=Mark-Simulacrum

Woe unto thee who decides to add a test
