### ISSUE TITLE
bad suggestion line for `use` statements with a derive

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#44995]
```Rust
#[derive(Debug)]
pub struct X;

impl Add for X {} // trigger unused import

fn main() {}
```

After #44215, this gives the following error message:
```
error[E0405]: cannot find trait `Add` in this scope
 --> x.rs:4:6
  |
4 | impl Add for X {} // trigger unused import
  |      ^^^ not found in this scope
  |
help: possible candidate is found in another module, you can import it into scope
  |
2 | use std::ops::Add; // <--- LINE 2 HERE
  |

error: cannot continue compilation due to previous error
```

This suggests placing the `use`-statement at line 2, which is between the `#[derive]` and the `pub struct X;` line, while we want to place the `use` statement before the `#[derive]`.

cc @oli-obk

**Comment by arielb1** [comment]
This remains after the regression in #44566 was fixed.

**Comment by oli-obk** [comment]
As mentioned in #44566, this is impossible to fix right now, because these attributes do not exist anymore at the lint stage. Solutions are noted in https://github.com/rust-lang/rust/pull/44215#issuecomment-326986760

**Comment by euclio** [comment]
cc #45216.

**Comment by programmerjake** [comment]
Can this be given a higher priority, it seems to me like a big gotcha for beginners.

An additional way to fix this might be to track the location where `use` and similar statements should be inserted in blocks, rather than taking the first token of the first post-expansion item. This avoids the need to keep attributes post-expansion.

**Comment by compiler-errors** [comment]
This now suggests the right span.

```
error[[E0405]](https://doc.rust-lang.org/stable/error-index.html#E0405): cannot find trait `Add` in this scope
 --> src/main.rs:4:6
  |
4 | impl Add for X {} // trigger unused import
  |      ^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 | [use core::ops::Add;](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018#)
  |
1 | [use nom::lib::std::ops::Add;](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018#)
  |
1 | [use pin_utils::core_reexport::ops::Add;](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018#)
  |
1 | [use std::ops::Add;](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018#)
  |
```
