### ISSUE TITLE
where bounds regression in beta+nightly

### ISSUE THREAD

**Issue by mejrs** [rust-lang/rust#143992]
### Code

```rust
pub trait Trait {
    type Assoc<G>: OtherTrait<G>;
}

pub trait OtherTrait<R> {
    fn new(r: R) -> R {
        r
    }
}

pub fn function<T: Trait>()
where
    T::Assoc<[u32; 1]>: Clone, // comment out to let it compile
{
    let _x = T::Assoc::new(());
}

```

### Version it worked on

It most recently worked on:  Stable (1.88)

### Version with regression

Beta (1.89), nightly (1.90) produces 
```
   Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
  --> src/lib.rs:15:28
   |
15 |     let _x = T::Assoc::new(());
   |              ------------- ^^ expected `[u32; 1]`, found `()`
   |              |
   |              arguments to this function are incorrect
   |
note: associated function defined here
  --> src/lib.rs:6:8
   |
6  |     fn new(r: R) -> R {
   |        ^^^ ----

For more information about this error, try `rustc --explain E0308`.
```

Originally found in https://github.com/phimuemue/openschafkopf/blob/dacfecc50338443955998a074c0901d989b7a553/lib/src/game_analysis/determine_best_card_table.rs#L51 

```
error[E0308]: mismatched types
  --> lib/src/game_analysis/determine_best_card_table.rs:70:9
   |
70 | /         SFormatInfo {
71 | |             f_min: f32::MAX,
72 | |             f_max: f32::MIN,
73 | |             n_width: 0,
74 | |         };
   | |_________^ expected `(String, f32)`, found `SFormatInfo`
   |
   = note: expected tuple `(std::string::String, f32)`
             found struct `SFormatInfo`
```

@rustbot modify labels: +regression-from-stable-to-beta +regression-from-stable-to-nightly -regression-untriaged

**Comment by fmease** [comment]
ig you raced with the original author? https://github.com/rust-lang/rust/issues/143991

**Comment by fmease** [comment]
we should close one or the other

**Comment by fmease** [comment]
(I wager it's due to #137944 — Sized Hierarchy — which came with brittle elaboration optimizations but I could be wrong)

**Comment by fmease** [comment]
searched nightlies: from nightly-2025-05-09 to nightly-2025-07-15
regressed nightly: nightly-2025-06-18
searched commit range: https://github.com/rust-lang/rust/compare/45acf54eea118ed27927282b5e0bfdcd80b7987c...f3db63916e541ff039ac3cd7364c2d612749b61b
regressed commit: https://github.com/rust-lang/rust/commit/86d0aef80403f095d8bbabf44d9fdecfcd45f076

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.9</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 1.88.0
```
</details>

**Comment by fmease** [comment]
cc @davidtwco (#137944)

**Comment by apiraino** [comment]
Assigning priority (discussion on [Zulip](https://rust-lang.zulipchat.com/#narrow/channel/245100-t-compiler.2Fprioritization.2Falerts/topic/.23143992.20where.20bounds.20regression.20in.20beta.2Bnightly/near/528929748)).

@rustbot label -I-prioritize +P-high

**Comment by lcnr** [comment]
Without `MetaSized`:
```rust
trait IncompleteGuidance {}
trait Trait {
    type Assoc<G>: OtherTrait<G>;
}

trait OtherTrait<R>: /* IncompleteGuidance */ {
    fn constrain_param(_: R) {}
}

fn function<T: Trait>()
where
    T::Assoc<u32>: IncompleteGuidance,
{
    T::Assoc::<_>::constrain_param(1i32);
}
```
We constrain the `G` arg of `T::Assoc::<_>` in the call to `constrain_param`. However, because of the newly introduced `MetaSized`(`IncompleteGuidance` in this example) super trait bound we have to prove `T::Assoc<_>: IncompleteGuidance` before checking the `constrain_param` arguments. This causes us to eagerly constrain the infer var to `u32` by using the where-bound.

This sort of incompleteness is generally undesirable and I feel pretty certain we can avoid this issue. Gonna nominate for T-types to discuss this a bit. My initial vibe is that we should just consider `MetaSized` goals to always hold unless the `sized_hierarchy` feature is enabled until we limit this incomplete candidate preference to avoid this breakage.

**Comment by lcnr** [comment]
fixed by #144016 which needs a beta-backport

**Comment by wesleywiser** [comment]
Backport completed in #144087.
