### ISSUE TITLE
Barely noticeable compiler suggestion

### ISSUE THREAD

**Issue by In-line** [rust-lang/rust#62597]
```
fn main() {
    let new_service = {
        hyper::service::service_fn_ok(unimplemented!())
    };
    hyper::Server::bind(unimplemented!())
        .serve(new_service);
}
```

Compiler error:
```
error[E0277]: expected a `std::ops::Fn<()>` closure, found `hyper::service::service::ServiceFnOk<_, _>`
 --> src/main.rs:6:10
  |
6 |         .serve(new_service);
  |          ^^^^^ expected an `Fn<()>` closure, found `hyper::service::service::ServiceFnOk<_, _>`
  |
  = help: the trait `std::ops::Fn<()>` is not implemented for `hyper::service::service::ServiceFnOk<_, _>`
  = note: wrap the `hyper::service::service::ServiceFnOk<_, _>` in a closure with no arguments: `|| { /* code */ }
  = note: required because of the requirements on the impl of `hyper::service::new_service::NewService` for `hyper::service::service::ServiceFnOk<_, _>`
  = note: required because of the requirements on the impl of `hyper::service::make_service::MakeServiceRef<hyper::server::tcp::addr_stream::AddrStream>` for `hyper::service::service::ServiceFnOk<_, _>`
```

I think it's better to improve this note
```
  = note: wrap the `hyper::service::service::ServiceFnOk<_, _>` in a closure with no arguments: `|| { /* code */ }
```
So it's more noticeable and readable.

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7384234185f560e9c2e27f9566918f57)

**Comment by estebank** [comment]
`rustc_on_unimplemented` should have a flag to hide the default `E0277` `note`s.

**Comment by rylev** [comment]
Triage: the example code still produces the error but it no longer works in the playground as `hyper` 0.12 needs to be used.
