### PR TITLE
Fix tuple struct field spans

### LINKED ISSUE #50578: Incorrect spans for tuple struct fields
As [identified in a recent PR](https://github.com/rust-lang/rust/pull/50536/files/d19039129ad1ca1fb80606b06968ae87234ce392#r186876378), tuple [struct fields have spans including trailing characters](https://play.rust-lang.org/?gist=d187ee724dace804a779268d43a483e6&version=nightly&mode=debug) (`,` and `)`):

```
error[E0204]: the trait `Copy` may not be implemented for this type
 --> src/main.rs:1:17
  |
1 | #[derive(Clone, Copy)]
  |                 ^^^^
2 | struct Foo(NotDefined, <i32 as Iterator>::Item, Vec<i32>, String);
  |            ----------- this field does not implement `Copy`
```

### PR DESCRIPTION
**Pull request by estebank**
Fix #50578. Will have a merge conflict with #50536.

### CODE REVIEW

**Review by nikomatsakis — APPROVED** [review]

**Comment by estebank** [comment]
@bors r=nikomatsakis

Fixed failed test.
