### PR TITLE
Revert "Do not check privacy for RPITIT."

### LINKED ISSUE #71043: Lint exported_private_dependencies misses public dependency via trait impl
Tracking issue: #44663, RFC: rust-lang/rfcs#1977

Cargo.toml:

```toml
cargo-features = ["public-dependency"]

[package]
name = "playground"
version = "0.0.0"
edition = "2018"

[dependencies]
num-traits = "0.2"
```

lib.rs:

```rust
pub struct S;

impl std::ops::Add for S {
    type Output = S;

    fn add(self, _: Self) -> Self::Output {
        unimplemented!()
    }
}

impl num_traits::Zero for S {
    fn zero() -> Self {
        unimplemented!()
    }
    fn is_zero(&self) -> bool {
        unimplemented!()
    }
}
```

Also, a plain `pub use` seems to be missed as well.

### LINKED ISSUE #143531: `private_interfaces` not linting RPITIT
### Code

```Rust
trait Bar {}

pub trait Foo {
    fn foo() -> impl Bar;
}

fn main() {}
```

### Current output

```Shell
<empty>
```

### Desired output

```Shell
warning: trait `Bar` is more private than the item `Foo::foo`
 --> foo.rs:4:1
  |
4 |     fn foo() -> impl Bar;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^ associated function `Foo::foo` is reachable at visibility `pub`
  |
note: but trait `Bar` is only usable at visibility `pub(crate)`
 --> foo.rs:1:1
  |
1 | trait Bar {}
  | ^^^^^^^^^
  = note: `#[warn(private_interfaces)]` on by default

warning: 1 warning emitted
```

### Rationale and extra context

_No response_

### Other cases

```Rust
Both using a concrete type or using RPIT in a method outside traits produce correct lints:


struct X;

pub trait Foo {
    fn foo() -> X;
}


produces

warning: type `X` is more private than the item `Foo::foo`




trait Bar {}
impl Bar for () {}

fn foo() -> impl Bar {}


Produces

warning: trait `Bar` is more private than the item `foo`
```

### Rust Version

```Shell
rustc 1.90.0-nightly (5adb489a8 2025-07-05)
binary: rustc
commit-hash: 5adb489a8034f7b56b29f3b28af0813c866f679c
commit-date: 2025-07-05
host: x86_64-unknown-linux-gnu
release: 1.90.0-nightly
LLVM version: 20.1.7
```

### Anything else?

_No response_

### LINKED ISSUE #144139: (re-)Fix private-in-public for RPITIT
#143357 fixed a latent bug where we weren't detecting private-in-public errors for RPITITs. In order to not break any existing code, @cjgillot temporarily reenabled the previous behavior in #144098.

This issue tracks the crater run to determine if that change had any real-world fallout. Ideally we fix the fallout and re-enable the intended behavior, which is to actually detect private-in-public errors in RPITITs just like RPITs and normal associated items. I'm opening an issue just to make sure the crater run doesn't get forgotten on a closed PR. I probably should've started the crater run here, but oh well! :^)

cc @cjgillot @petrochenkov

---

> You can check out [the queue](https://crater.rust-lang.org) and [this experiment's details](https://crater.rust-lang.org/ex/pr-144098).

_Originally posted by @craterbot in https://github.com/rust-lang/rust/issues/144098#issuecomment-3090004901_

### PR DESCRIPTION
**Pull request by mladedav**
The changes here were first merged in rust-lang/rust#143357 and later reverted in rust-lang/rust#144098 as it introduces new hard errors. There was a crater run tracked in rust-lang/rust#144139 to see how much projects would be broken (not that many, a few repositories on github are affected).

This reenables hard errors for privacy in RPITIT.

Fixes rust-lang/rust#143531
Closes rust-lang/rust#144139
Hopefully closes rust-lang/rust#71043

### CODE REVIEW

**Comment by mladedav** [comment]
Gentle ping @cjgillot

**Comment by traviscross** [comment]
Today, this warns:

```rust
trait PrivTr {}
impl PrivTr for () {}
pub trait PubTr {
    fn f1() -> impl PrivTr;
}
impl<T> PubTr for T {
    fn f1() -> impl PrivTr {}
    //~^ warning: trait `PrivTr` is more private than the item `<T as PubTr>::f1`
    //~| note: `#[warn(private_interfaces)]` on by default
}
```

With the PR, it warns additionally at the def-site and errors at the impl-site:

```rust
trait PrivTr {}
impl PrivTr for () {}
pub trait PubTr {
    fn f1() -> impl PrivTr;
    //~^ warning: trait `PrivTr` is more private than the item `PubTr::f1::{anon_assoc#0}`
    //~| note: `#[warn(private_bounds)]` on by default
}
impl<T> PubTr for T {
    fn f1() -> impl PrivTr {}
    //~^ warning: trait `PrivTr` is more private than the item `<T as PubTr>::f1`
    //~| note: `#[warn(private_interfaces)]` on by default
    //~^ error[E0446]: private trait `PrivTr` in public interface
    //~| help: can't leak private trait
}
```

The comparable desugaring, both today and under this PR, only warns at the def-site:

```rust
trait PrivTr {}
impl PrivTr for () {}
pub trait PubTr {
    type F1: PrivTr;
    fn f1() -> Self::F1;
    //~^ warning: trait `PrivTr` is more private than the item `PubTr::f1::{anon_assoc#0}`
    //~| note: `#[warn(private_bounds)]` on by default
}
impl<T> PubTr for T {
    type F1 = ();
    fn f1() -> Self::F1 {}
}
```

**Comment by traviscross** [comment]
@mladedav: I'm having trouble working out the reason why we'd give a hard error for the RPIT-in-trait-impl,

```rust
trait PrivTr {}
impl PrivTr for () {}
#[expect(private_bounds)]
pub trait PubTr {
    fn f1() -> impl PrivTr;
}
impl<T> PubTr for T {
    #[expect(private_interfaces)]
    fn f1() -> impl PrivTr {}
    //~^ error[E0446]: private trait `PrivTr` in public interface
    //~| help: can't leak private trait
}
```

given that we don't give an error for an RPIT-in-free-function,

```rust
trait PrivTr {}
impl PrivTr for () {}

#[expect(private_interfaces)]
pub fn f2() -> impl PrivTr {} //~ OK
```

and given that we allow the comparable associated type desugaring of the RPITIT:

```rust
trait PrivTr {}
impl PrivTr for () {}
pub trait PubTr {
    #[expect(private_bounds)]
    type F1: PrivTr; //~ OK
    fn f1() -> Self::F1;
}
impl<T> PubTr for T {
    type F1 = ();
    fn f1() -> Self::F1 {}
}
```

What's the rationale here?

cc @petrochenkov

---

Also, on the PR, I notice that placing the `expect` over the trait item doesn't work.

```rust
trait PrivTr {}
impl PrivTr for () {}
pub trait PubTr {
    #[expect(private_bounds)] //~ warning: this lint expectation is unfulfilled
    fn f1() -> impl PrivTr;
    //~^ warning: trait `PrivTr` is more private than the item `PubTr::f1::{anon_assoc#0}`
}
```

Should it?

**Comment by mladedav** [comment]
> @mladedav: I'm having trouble working out the reason why we'd give a hard error for the RPIT-in-trait-impl, [...] What's the rationale here?

I have to say that I don't completely understand the code in question.

From my understanding of the history, @cjgillot first wrote these changes in #143357 to clean up the code and the addition of the error [was accidental](https://github.com/rust-lang/rust/pull/144020#issuecomment-3081600839). But the error itself [is desirable](https://github.com/rust-lang/rust/pull/144098#issuecomment-3089285606).

This is a follow up since the last [crater run has finished](https://github.com/rust-lang/rust/pull/144098#issuecomment-3103652648) and when I looked through it, while there was a little breakage in some github repositories, it did not seem like a major issue. So I wanted to drive this forward so that the errors are added rather earlier than later.

So I don't think there was anyone who explicitly decided that one of the forms should be rejected while the other should be allowed. I think we can all agree that all of them should be at least warnings, but according to [this comment](https://github.com/rust-lang/rust/issues/144139#issuecomment-3092041863), they should all be errors. Therefore, I see this as an incremental step towards the end goal while I see that there are issues with this.

But it's completely fair if you think that the rules as they would be with this would be arbitrary or that it shouldn't lint twice on the same issue and that the errors should be improved to not mention things like `PubTr::f1::{anon_assoc#0}` and therefore we should not merge this and have someone build a more complete solution.

**Comment by petrochenkov** [comment]
>What's the rationale here?

I'll recall the details and look at this this week.

**Comment by traviscross** [comment]
@craterbot check p=1 crates=https://crater-reports.s3.amazonaws.com/pr-146470-1/retry-regressed-list.txt

**Comment by petrochenkov** [comment]
>Also, on the PR, I notice that placing the expect over the trait item doesn't work.

The associated type item newly added for the RPITIT is used as a lint node, which is a different node from `fn f1` to which the `expect` attribute is attached.

**Comment by petrochenkov** [comment]
> It makes sense why we can't leak a private type in this way -- we'd then be allowing a private type to be named. Why does this rise to the level of a hard error for a private trait in an impl trait bound?

So, an associated type's interface can contain
- Generics
- Predicates
- Default type
- Bounds

```rust
type Type<T: PrivTrait /*predicates*/ = PrivTy /*generics*/>: PrivTrait /*bounds*/
    where Something: PrivTrait /*predicates*/
    = PrivTy /*default type*/;
```

And we just don't differentiate and check all of them when reporting the hard error version of the priv-in-pub check.
Originally that was simply a conservative choice allowing to avoid thinking too much about which of those can actually leak something private.
Maybe predicates and bounds cannot actually leak anything, then they can be demoted to a lint, we just need to have some more or less convincing proof of that written.

Why this is a hard error in the first place?
During post-factum type privacy checks when we see `<Type as Trait>::Assoc` we cannot see and check its underlying type (that's the technical limitation mentioned in the RFC), we can only check that `Type` and `Trait` are not private.
So at definition site we must ensure (not just lint) that `impl Trait for Type` cannot define an `Assoc` that is more private than any of them.

**Comment by traviscross** [comment]
Worth noting too is that while we don't give a def-site error for this,

```rust
trait Priv {}
impl Priv for () {}
#[expect(private_interfaces)]
pub fn f() -> impl Priv {}
```

we do give a use-site error if you try to make that call:

```rust
mod m1 {
    trait Priv {}
    impl Priv for () {}
    #[expect(private_interfaces)]
    pub fn f() -> impl Priv {}
}

fn main() {
    let _x = crate::m1::f(); //~ error: trait `Priv` is private
}
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&code=mod+m1+%7B%0A++++trait+Priv+%7B%7D%0A++++impl+Priv+for+%28%29+%7B%7D%0A++++%23%5Bexpect%28private_interfaces%29%5D%0A++++pub+fn+f%28%29+-%3E+impl+Priv+%7B%7D%0A%7D%0A%0Afn+main%28%29+%7B%0A++++let+_x+%3D+crate%3A%3Am1%3A%3Af%28%29%3B+%2F%2F~+error%3A+trait+%60Priv%60+is+private%0A%7D%0A)

**Comment by traviscross** [comment]
In fact, we even give a use-site error just for naming that public item, even if not called:

```rust
mod m1 {
    trait Priv {}
    impl Priv for () {}
    #[expect(private_interfaces)]
    pub fn f() -> impl Priv {}
}

fn main() {
    let _x = crate::m1::f; //~ error: trait `Priv` is private
}
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&code=mod+m1+%7B%0A++++trait+Priv+%7B%7D%0A++++impl+Priv+for+%28%29+%7B%7D%0A++++%23%5Bexpect%28private_interfaces%29%5D%0A++++pub+fn+f%28%29+-%3E+impl+Priv+%7B%7D%0A%7D%0A%0Afn+main%28%29+%7B%0A++++let+_x+%3D+crate%3A%3Am1%3A%3Af%3B+%2F%2F~+error%3A+trait+%60Priv%60+is+private%0A%7D%0A)

**Comment by petrochenkov** [comment]
>Has a crater run ever been done for https://github.com/rust-lang/rust/commit/c5221ebdf9387f8d33cf5165c72f828cb284fe43?

No

**Comment by tmandry** [comment]
@rfcbot resolve is my understanding correct

I think I understand this now and am comfortable with moving forward conservatively, pending crater results.

@rfcbot reviewed
@rfcbot concern crater run results

**Comment by petrochenkov** [comment]
@craterbot check

**Comment by traviscross** [comment]
> Someone needs to try and break it...

cc @theemathas

**Comment by traviscross** [comment]
Please renominate when this is ready for the lang team to consider next steps.

**Comment by petrochenkov** [comment]
> I could not construct anything similar from private Generics, Predicates and Bounds so far.

I think I'm convinced that you cannot leak anything private into the associated type RHS through Bounds and Predicates, if the RHS itself is checked (https://github.com/rust-lang/rust/pull/146470#issuecomment-3755229532).
Most of the regressions in https://github.com/rust-lang/rust/pull/146470#issuecomment-3723249721 are from the bounds.

After https://github.com/rust-lang/rust/pull/151168 is merged I'll make my version of the fix and run it through crater.
@rustbot blocked

**Comment by theemathas** [comment]
I found a privacy-related bug, filed as #151284. I have not tested it with this PR, since this PR does not compile on my computer.

<details>
<summary>Error from compiling this PR</summary>

```
error[E0432]: unresolved import `rustc_middle::ty::AssocContainer`
  --> compiler\rustc_privacy\src\lib.rs:36:11
   |
36 |     self, AssocContainer, Const, GenericParamDefKind, TraitRef, Ty, TyCtxt, TypeSuperVisitable,
   |           ^^^^^^^^^^^^^^
   |           |
   |           no `AssocContainer` in `ty`
   |           help: a similar name exists in the module: `AssocItemContainer`

For more information about this error, try `rustc --explain E0432`.
error: could not compile `rustc_privacy` (lib) due to 1 previous error
```

</details>
