### ISSUE TITLE
ui test suite fails on stage 1

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#53380]
With current master (81cfaad030435aae447d73c66123b3df856c09cb), the UI stage 1 test suite fails for me. `./x.py --stage 1 test src/test/ui --bless` introduces the following diff:
```diff
--- a/src/test/ui/macros/macros-nonfatal-errors.stderr
+++ b/src/test/ui/macros/macros-nonfatal-errors.stderr
@@ -1,4 +1,4 @@
-error[E0665]: `Default` cannot be derived for enums, only structs
+error: `Default` cannot be derived for enums, only structs
   --> $DIR/macros-nonfatal-errors.rs:20:10
    |
 LL | #[derive(Default)] //~ ERROR
@@ -96,5 +96,4 @@ LL |     trace_macros!(invalid); //~ ERROR
 
 error: aborting due to 15 previous errors
 
-Some errors occurred: E0658, E0665.
-For more information about an error, try `rustc --explain E0658`.
+For more information about this error, try `rustc --explain E0658`.
```
Stage 1 used to work fine, so this is a regression, likely introduced by https://github.com/rust-lang/rust/pull/53196 (cc @davidtwco).

Stage 2 build is still running.

**Comment by varkor** [comment]
Fixed by https://github.com/rust-lang/rust/pull/53368.

**Comment by RalfJung** [comment]
FWIW, stage 2 works. I am surprised that such a difference is possible between stages...

**Comment by varkor** [comment]
It's explicitly gated on stage 2 (i.e. being compiled by stage 1 or greater):
https://github.com/rust-lang/rust/blob/bc8cead070a44a9ebc7cd559479e0266c45c7c72/src/libsyntax_ext/deriving/default.rs#L78-L80
I'm not quite sure why the only difference is emitting the error code or not, though:
https://github.com/rust-lang/rust/blob/bc8cead070a44a9ebc7cd559479e0266c45c7c72/src/libsyntax_ext/deriving/mod.rs#L22-L31

**Comment by davidtwco** [comment]
Huh, that's interesting. I was always testing against stage 2 locally when working on #53196 and Travis didn't seem to pick that up either.

**Comment by varkor** [comment]
Fixed by https://github.com/rust-lang/rust/pull/53368#event-1791084129.
