### ISSUE TITLE
rustc thinks a lifetime bound is necessary when passing an associated type into a nested call

### ISSUE THREAD

**Issue by BGR360** [rust-lang/rust#101601]
No idea how to more effectively describe this problem in the title. Open to suggestions.

The following code fails to compile on stable (1.63.0) and nightly ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5db2d15b51d423f1053a9d570db4a654)):

```rust
trait Trait {
    type Associated;
}

struct Type<'a, T> {
    field: &'a T,
}

impl<'a, T> Type<'a, T>
where
    T: Trait,
{
    fn foo(param: T::Associated) {
        Self::bar(param);
    }

    fn bar(_: T::Associated) {}
}
```

```
error[E0309]: the parameter type `T` may not live long enough
  --> src/lib.rs:15:9
   |
15 |         Self::bar(param);
   |         ^^^^^^^^^ ...so that the type `T` will meet its required lifetime bounds
   |
help: consider adding an explicit lifetime bound...
   |
11 |     T: Trait + 'a,
   |              ++++
```

Removing the call to `Self::bar` makes the code compile just fine. It only fails when you try to call `bar` from inside `foo`.

This is really baffling to me. How is `'a` even involved here?

**Hint 1**: It compiles if `Type` instead owns the `T` ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=76366844bcfd9376541fd93468bfea67)):

```rust
struct Type<'a, T> {
    field: T,
    extra: &'a str
}
```

**Hint 2**: It compiles if `foo` and `bar` are methods instead of associated functions ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=67e27b553cb377ffe040bf94a89138b1)).

**Hint 3**: It compiles if you do `Type::<'_, T>::bar` instead of `Self::bar` ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=5db2d15b51d423f1053a9d570db4a654)).

I suppose it's possible that this *isn't* a bug, but if that's the case, then it's a corner of the language I have never hit before, and the diagnostics need a *lot* of work.

@rustbot label +A-associated-items +A-traits +A-lifetimes

**Comment by BGR360** [comment]
And it gets even weirder! Let's say you do what rustc asks and add the `T: 'a` bound. Then if you add another field to the type that normally implies certain lifetime bounds (like `field: &'b &'a ()` normally implies that `'a: 'b`), the compiler suddenly can't infer those relationships / makes the user specify them manually! ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=59d2225fe316037f0a45ab3a27851e76))

```rust
trait Trait {
    type Associated;
}

struct Type<'a, 'b, T> {
    a: &'a T,
    b: &'b &'a (),
}

impl<'a, 'b, T> Type<'a, 'b, T>
where
    T: Trait + 'a,
{
    fn foo(param: T::Associated) {
        Self::bar(param);
    }

    fn bar(_: T::Associated) {}
}
```

```
error: lifetime may not live long enough
  --> src/lib.rs:15:9
   |
10 | impl<'a, 'b, T> Type<'a, 'b, T>
   |      --  -- lifetime `'b` defined here
   |      |
   |      lifetime `'a` defined here
...
15 |         Self::bar(param);
   |         ^^^^^^^^^ requires that `'a` must outlive `'b`
   |
   = help: consider adding the following bound: `'a: 'b`
```

That one fails to compile even when `Type` owns `T`:

```rust
struct Type<'a, 'b, T> {
    a: T,
    b: &'b &'a (),
}
```

**And???????? It fails to compile even if there's no trait or associated type involved at all!** ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8372db4995a5dbdd5dfad31de111150b))

```rust
struct Type<'a, 'b> {
    field: &'b &'a (),
}

impl<'a, 'b> Type<'a, 'b> {
    fn foo() {
        Self::bar()
    }
    
    fn bar() {}
}
```

In all of those cases, removing the call to `Self::bar` or using an explict, turbofished `Type` makes it compile.

What is going on here?

**Comment by aliemjay** [comment]
This root cause #98852. #100976 will improve the diagnostics  by suggesting replacing `Self` with the the type name.

Consider closing it as a duplicate of either #98852 or #101393.

**Comment by BGR360** [comment]
Awesome, thank you for working on the fix!
