### PR TITLE
report duplicate symbols added by the driver

### PR DESCRIPTION
**Pull request by folkertdev**
The panic message did not mention what symbols were duplicates, which made the panic hard to debug. This came up in [#t-compiler/help > Easiest way to find offending duplicate symbols](https://rust-lang.zulipchat.com/#narrow/channel/182449-t-compiler.2Fhelp/topic/Easiest.20way.20to.20find.20offending.20duplicate.20symbols/with/538295740).

This behavior was introduced in https://github.com/rust-lang/rust/pull/138682.

r? @fee1-dead

### CODE REVIEW

**Comment by fee1-dead** [comment]
This looks good to me.

@bors r+ rollup
