### ISSUE TITLE
Conflicting implementation of trait with `generic_const_exprs` feature

### ISSUE THREAD

**Issue by minseongg** [rust-lang/rust#92186]
I tried this code:

```rust
#![allow(incomplete_features)]
#![feature(adt_const_params)]
#![feature(generic_const_exprs)]

use std::marker::PhantomData;

pub struct Foo<const P: Protocol, T> {
    _marker: PhantomData<T>,
}

impl<const P: Protocol, T> Foo<P, T> {
    pub fn new() -> Self {
        Foo {
            _marker: PhantomData,
        }
    }
}

#[derive(PartialEq, Eq)]
pub enum Protocol {
    Variant1,
    Variant2,
}

pub trait Bar {}

impl<T> Bar for Foo<{ Protocol::Variant1 }, T> {}
impl<T> Bar for Foo<{ Protocol::Variant2 }, T> {}
```

I expected to see this happen: This is the result when I commented `generic_const_exprs` feature.

```
$ cargo build
   Compiling test-nightly v0.1.0
    Finished dev [unoptimized + debuginfo] target(s) in 0.22s
```

Instead, this happened:

```
$ cargo build
   Compiling test-nightly v0.1.0
error[E0119]: conflicting implementations of trait `Bar` for type `Foo<{ Protocol::Variant1 }, _>`
  --> src/lib.rs:28:1
   |
27 | impl<T> Bar for Foo<{ Protocol::Variant1 }, T> {}
   | -------------------- first implementation here
28 | impl<T> Bar for Foo<{ Protocol::Variant2 }, T> {}
   | ^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `Foo<{ Protocol::Variant1 }, _>`

For more information about this error, try `rustc --explain E0119`.
error: could not compile `test-nightly` due to previous error
```

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (23f69235a 2021-12-20)
binary: rustc
commit-hash: 23f69235ad2eb9b44ac1a55eeaa3f9b484d9de4a
commit-date: 2021-12-20
host: x86_64-unknown-linux-gnu
release: 1.59.0-nightly
LLVM version: 13.0.0
```

<details><summary>Backtrace</summary>
<p>

```
   Compiling test-nightly v0.1.0
error[E0119]: conflicting implementations of trait `Bar` for type `Foo<{ Protocol::Variant1 }, _>`
  --> src/lib.rs:28:1
   |
27 | impl<T> Bar for Foo<{ Protocol::Variant1 }, T> {}
   | -------------------- first implementation here
28 | impl<T> Bar for Foo<{ Protocol::Variant2 }, T> {}
   | ^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `Foo<{ Protocol::Variant1 }, _>`

For more information about this error, try `rustc --explain E0119`.
error: could not compile `test-nightly` due to previous error
```

</p>
</details>

**Comment by BoxyUwU** [comment]
caused by #90023 because during coherence we try to equate `Foo<{ 1 }>` with `Foo<{ 2 }>` to see if the impls overlap, which tries to equate the anon consts: `{ 1 }` with `{ 2 }` which have substs of `_` and with that PR we now bail with `EvaluatedToAmbig` whereas before we were able to say they dont unify.

I don't think there's any easy solution to this rn

more minimal repro:
```rust
#![feature(generic_const_exprs)]
#![allow(incomplete_features)]

pub struct Foo<const N: usize>;
pub trait Bar<T> {}

impl<T> Bar<T> for Foo<{ 1 }> {}
impl<T> Bar<T> for Foo<{ 2 }> {}
```

**Comment by lcnr** [comment]
this also affects inherent impls
```rust
const ONE : i32 = 1;
const TWO : i32 = 2;

struct Foo<const i: i32, const j: i32> {}

impl<const i: i32> Foo<i, ONE> {
    pub fn foo() {}
}

impl<const i: i32> Foo<i, TWO> {
    pub fn foo() {}
}
```
