### ISSUE TITLE
E0596 explanation points to return type, not the argument type of called function

### ISSUE THREAD

**Issue by danjl1100** [rust-lang/rust#119985]
### Code

```Rust
struct MyVec<T>(T);

impl<T> MyVec<T> {
    fn replace_with<U>(&self, mut f: impl FnMut() -> U) -> MyVec<U> {
        // reports correct error E0596,
        // but with odd explanation in the rustc output:   -------- ""change this to return `FnMut` instead of `Fn`""
        self.map(|_| f())
    }
    fn map<U>(&self, _: impl Fn(&T) -> U) -> MyVec<U> {
        todo!()
    }
}
```

### Current output

```Shell
error[E0596]: cannot borrow `f` as mutable, as it is a captured variable in a `Fn` closure
 --> src/lib.rs:7:22
  |
4 |     fn replace_with<U>(&self, mut f: impl FnMut() -> U) -> MyVec<U> {
  |        ------------                                        -------- change this to return `FnMut` instead of `Fn`
...
7 |         self.map(|_| f())
  |                  --- ^ cannot borrow as mutable
  |                  |
  |                  in this closure

For more information about this error, try `rustc --explain E0596`.
```

### Desired output

```Shell
error[E0596]: cannot borrow `f` as mutable, as it is a captured variable in a `Fn` closure
 --> src/lib.rs:7:22
  |
7 |         self.map(|_| f())
  |         -------- --- ^ cannot borrow as mutable
  |         |        |
  |         |        in this closure
  |         expects `Fn` instead of `FnMut`
8 |     }
9 |     fn map<U>(&self, _: impl Fn(&T) -> U) -> MyVec<U> {
  |                         ---------------- change this to accept `FnMut` instead of `Fn`

For more information about this error, try `rustc --explain E0596`.
```

### Rationale and extra context

Affected [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c19c261cfcae764bdba9e7d6f2c249c3), with correct error but misleading explanation.

Removing `impl` block and `self` parameters shows the correct/expected diagnostic explanation,
demonstrated in this [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6d7d3f34d6cd56d183311a097d961174)

### Rust Version

```Shell
Duplicated on playground with both "Stable 1.75.0", and on playground selecting nightly:

Build using the Nightly version: 1.77.0-nightly
(2024-01-13 d78329b92e8d141d1950)
```
```


### Anything else?

Overall, not a huge issue - the actual error indication is correct.
The small oddity is where it points to the function return type as the location of the `Fn`. This took me a bit to actually figure out what I was doing wrong :slightly_smiling_face:

**Comment by compiler-errors** [comment]
Yeah, this suggestion is bogus.

This suggestion was tailored for the case where we return `-> impl FnMut`, but that's not the only place we can have mismatched closure kinds -- this example shows where it's a consequence of an *argument* expectation.
