### ISSUE TITLE
failed Send inference resulting in "one type is more general than the other" E0308

### ISSUE THREAD

**Issue by pcmehlitz** [rust-lang/rust#162558]
this might be related to #90656 but since that is open since 2021 I document my case.
I'm running into E0308's when trying to compile an async fn that uses 

- rust 1.98.1 (48a229cea 2026-09-01)
- uom v0.38 
- ndarray v0.17.2  (*NOTE* - v0.16 seems to work)

The problem can be isolated into the following minimal code, which I would expect to compile. Please note it works with ndarray v0.16 so I will also report it there but at least the error message is not helpful

```rust
use uom::si::f64::Length;
use uom::ConstZero;
use ndarray::Array2;

fn assert_send<T: Send>(_t: T) {}

fn main() {
    assert_send(check());
}

async fn check() {
    let lengths: Array2<Length> = Array2::from_elem((2, 3), Length::ZERO);
    std::future::pending::<()>().await;
    println!("{}", lengths[(0, 0)].get::<uom::si::length::meter>());
}
```

The compiler error message is:

```
error[E0308]: mismatched types
 --> src/main.rs:8:5
  |
8 |     assert_send(check());
  |     ^^^^^^^^^^^^^^^^^^^^ one type is more general than the other
  |
  = note: expected struct `Quantity<..., ..., f64>`
             found struct `Quantity<..., ..., f64>`
note: the lifetime requirement is introduced here
 --> src/main.rs:5:19
  |
5 | fn assert_send<T: Send>(_t: T) {}
  |                   ^^^^
```

If you are interested I have a workaround wrapping the Array2<Length> into a newtype with a `at(&self,usize,usize)->Length` fn and using that to obtain Length quantities inside the async fn. This comes from a bigger project though (https://github.com/ODIN-fire/odin-rs) where such workarounds are clearly suboptimal since it is highly async.

**Comment by pcmehlitz** [comment]
since it might explain what happens here is the workaround. If I understand it correctly it moves the monomorphization into its own non-async fn so that `async_fn_check` only sees simple type constraints

```rust
use uom::si::f64::Length;
use uom::ConstZero;
use ndarray::Array2;

fn assert_send<T: Send>(_t: T) {}

fn main() {
    assert_send(check());
}

async fn check() {
    let lengths: Grid<Length> = Grid(Array2::from_elem((2, 3), Length::ZERO));
    std::future::pending::<()>().await;
    println!("{}", lengths.at(0, 0).get::<uom::si::length::meter>());
}

struct Grid<T>(Array2<T>);
impl <T: Clone> Grid<T> {
    fn at (&self, row: usize, col: usize)->T { self.0[(row,col)].clone() }
}
```
