### PR TITLE
Revert #86011 to fix an incorrect bound check

### LINKED ISSUE #89935: Rocket fails to build on latest nightly
### Code

I created a project with the following `Cargo.toml`:

```toml
[package]
name = "ducks"
version = "0.1.0"
edition = "2018"

[dependencies]
rocket = "=0.4.10"
```

[`Cargo.lock`](https://github.com/rust-lang/rust/files/7356901/Cargo.lock.txt)

On the latest nightly, this fails to build with:

```
error[E0277]: the trait bound `(dyn handler::Handler + 'static): handler::Handler` is not satisfied
   --> /Users/wongchris/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.10/src/rocket.rs:299:41
    |
299 |             let outcome = route.handler.handle(request, data);
    |                                         ^^^^^^ the trait `handler::Handler` is not implemented for `(dyn handler::Handler + 'static)`
```

There is no such error with `+nightly-2021-10-14`.

### Version it worked on

`rustc +nightly-2021-10-14 --version --verbose`:
```
rustc 1.57.0-nightly (dfc5add91 2021-10-13)
binary: rustc
commit-hash: dfc5add915e8bf4accbb7cf4de00351a7c6126a1
commit-date: 2021-10-13
host: x86_64-apple-darwin
release: 1.57.0-nightly
LLVM version: 13.0.0
```

### Version with regression

`rustc +nightly-2021-10-16 --version --verbose`:
```
rustc 1.57.0-nightly (c1026539b 2021-10-15)
binary: rustc
commit-hash: c1026539bd22e9d070988deaa47b1360cbc76436
commit-date: 2021-10-15
host: x86_64-apple-darwin
release: 1.57.0-nightly
LLVM version: 13.0.0
```

### PR DESCRIPTION
**Pull request by JohnTitor**
This reverts commit 36a1076d24697621a3bb67ef654b4eb79647aa54, reversing
changes made to e1e9319d93aea755c444c8f8ff863b0936d7a4b6.

Fixes #89935
r? @estebank

### CODE REVIEW

**Comment by JohnTitor** [comment]
Since this slipped from beta (1.57), I think it's worth beta-nominating, WDYT @estebank?
