### ISSUE TITLE
Invalid Program with `tokio::fs::File` creates Type Dependency Cycle (E0391)

### ISSUE THREAD

**Issue by bengsparks** [rust-lang/rust#125867]
I tried this code:

```rust
#[tokio::main]
async fn main() {
    let file = tokio::fs::File("commands.pixelflut").await;
    //                      ^^^^ missing File::open
}
```

with

```toml
[package]
name = "tokio-file-bug"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["fs", "macros", "rt-multi-thread"] }
```

I expected to see this happen: 
```
error[E0423]: expected function, tuple struct or tuple variant, found struct `tokio::fs::File`.
```

Instead, this happened: 
```shell
$ cargo r 
   Compiling tokio-file-bug v0.1.0 (/Users/ben/coding/mre/tokio-file-bug)
error[E0391]: cycle detected when getting the resolver for lowering
  |
  = note: ...which requires normalizing `tokio::fs::file::File::open::{opaque#0}`...
  = note: ...which requires looking up limits...
  = note: ...which requires getting the crate HIR...
  = note: ...which again requires getting the resolver for lowering, completing the cycle
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

For more information about this error, try `rustc --explain E0391`.
error: could not compile `tokio-file-bug` (bin "tokio-file-bug") due to 1 previous error
```

The process also commonly hangs until it is killed.

### Meta

`rustc --version --verbose`:
```
rustc 1.76.0 (07dca489a 2024-02-04)
binary: rustc
commit-hash: 07dca489ac2d933c78d3c5158e3f43beefeb02ce
commit-date: 2024-02-04
host: aarch64-apple-darwin
release: 1.76.0
LLVM version: 17.0.6
```

<details><summary>Backtrace (is identical, but included for completion's sake)</summary>
<p>

```shell
$ RUST_BACKTRACE=1 cargo build
   Compiling tokio-file-bug v0.1.0 (/Users/ben/coding/mre/tokio-file-bug)
error[E0391]: cycle detected when getting the resolver for lowering
  |
  = note: ...which requires normalizing `tokio::fs::file::File::open::{opaque#0}`...
  = note: ...which requires looking up limits...
  = note: ...which requires getting the crate HIR...
  = note: ...which again requires getting the resolver for lowering, completing the cycle
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information
  
For more information about this error, try `rustc --explain E0391`.
error: could not compile `tokio-file-bug` (bin "tokio-file-bug") due to 1 previous error
```

</p>
</details>

**Comment by bengsparks** [comment]
Compiles on Rust 1.77 and 1.85, so presumably this has been rectified.
