### ISSUE TITLE
Can't compile brotli with rustc 1.27.0-nightly (2f2a11dfc 2018-05-16)

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#50825]
```
error[E0277]: the trait bound `u64: core::slice::SliceIndex<[HistogramType]>` is not satisfied
   --> /Users/nox/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.2/src/enc/block_splitter.rs:271:26
    |
271 |   let data_size: usize = histograms[0].slice().len();
    |                          ^^^^^^^^^^^^^ slice indices are of type `usize` or ranges of `usize`
    |
    = help: the trait `core::slice::SliceIndex<[HistogramType]>` is not implemented for `u64`
    = note: required because of the requirements on the impl of `core::ops::Index<u64>` for `[HistogramType]`

error[E0277]: the trait bound `u64: core::slice::SliceIndex<[f32]>` is not satisfied
   --> /Users/nox/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.2/src/enc/block_splitter.rs:341:13
    |
341 |             (*cost_iter).0[sub_index] += local_insert_cost[sub_index];
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^ slice indices are of type `usize` or ranges of `usize`
    |
    = help: the trait `core::slice::SliceIndex<[f32]>` is not implemented for `u64`
    = note: required because of the requirements on the impl of `core::ops::Index<u64>` for `[f32]`

error[E0277]: the trait bound `u64: core::slice::SliceIndex<[f32]>` is not satisfied
   --> /Users/nox/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.2/src/enc/block_splitter.rs:341:42
    |
341 |             (*cost_iter).0[sub_index] += local_insert_cost[sub_index];
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ slice indices are of type `usize` or ranges of `usize`
    |
    = help: the trait `core::slice::SliceIndex<[f32]>` is not implemented for `u64`
    = note: required because of the requirements on the impl of `core::ops::Index<u64>` for `[f32]`

error[E0277]: the trait bound `u64: core::slice::SliceIndex<[f32]>` is not satisfied
   --> /Users/nox/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.2/src/enc/block_splitter.rs:342:30
    |
342 |             let final_cost = (*cost_iter).0[sub_index];
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^ slice indices are of type `usize` or ranges of `usize`
    |
    = help: the trait `core::slice::SliceIndex<[f32]>` is not implemented for `u64`
    = note: required because of the requirements on the impl of `core::ops::Index<u64>` for `[f32]`

error[E0308]: mismatched types
   --> /Users/nox/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.2/src/enc/block_splitter.rs:345:45
    |
345 |               *block_id_ptr = (base_index + sub_index) as u8;
    |                                             ^^^^^^^^^ expected usize, found u64

error[E0277]: cannot add `u64` to `usize`
   --> /Users/nox/.cargo/registry/src/github.com-1ecc6299db9ec823/brotli-1.1.2/src/enc/block_splitter.rs:345:43
    |
345 |               *block_id_ptr = (base_index + sub_index) as u8;
    |                                           ^ no implementation for `usize + u64`
    |
    = help: the trait `core::ops::Add<u64>` is not implemented for `usize`
```

Cc @rust-lang/compiler

**Comment by kennytm** [comment]
This seems to be caused by #47832.

**Comment by Eijebong** [comment]
Diesel is affected too

```
error[E0053]: method `metadata` has an incompatible type for trait
   --> diesel/src/pg/types/array.rs:14:25
    |
14  |     fn metadata(lookup: &PgMetadataLookup) -> PgTypeMetadata {
    |                         ^^^^^^^^^^^^^^^^^ expected associated type, found struct `pg::metadata_lookup::PgMetadataLookup`
    | 
   ::: diesel/src/sql_types/mod.rs:402:25
    |
402 |     fn metadata(lookup: &Self::MetadataLookup) -> Self::TypeMetadata;
    |                         --------------------- type in trait
    |
    = note: expected type `fn(&<pg::backend::Pg as sql_types::TypeMetadata>::MetadataLookup) -> <pg::backend::Pg as sql_types::TypeMetadata>::TypeMetadata`
               found type `fn(&pg::metadata_lookup::PgMetadataLookup) -> pg::backend::PgTypeMetadata`
```

**Comment by kennytm** [comment]
Bisection gives #48557 as the regression PR cc @matthewjasper @nikomatsakis

**Comment by nagisa** [comment]
Diesel issue seems unrelated.

**Comment by nikomatsakis** [comment]
Can we verify if the Diesel regression is related or not? cc @sgrif

**Comment by matthewjasper** [comment]
I'm looking at this.

Minified brotli issue:

```rust
fn foo(y: &[()]) where u64: Copy // or From<u64>
{
    let x = y[0]; // u64: std::slice::SliceIndex<[()]>` is not satisfied
}
```

**Comment by matthewjasper** [comment]
Minified diesel issue:

```rust
trait X {
    type T;
}

trait Y<U>: X {
    fn foo(x: &Self::T);
}

impl X for () {
    type T = ();
}

impl<T> Y<Vec<T>> for () where (): Y<T> {
    fn foo(_x: &()) {}
}
```

I'll try to get a patch to either fix this or roll back some of the changes in #48557 (more likely) ready tomorrow.

**Comment by nikomatsakis** [comment]
Reclassifying bug as P-medium since we reverted the PR and hence breakage should be fixed (right @matthewjasper @nox ?)

**Comment by Diggsey** [comment]
I'm still unable to build diesel as of `nightly-2018-05-30` - shouldn't the breaking change be reverted now?

**Comment by SimonSapin** [comment]
`brotli` v1.1.2 does compile in recent nightlies (presumably since https://github.com/rust-lang/rust/pull/50876), so it looks like the diesel failure is different. Has it been bisected to one Rust PR?

**Comment by RalfJung** [comment]
Diesel v1.2.2 compiles fine for me on `rustc 1.28.0-nightly (990d8aa74 2018-05-25)`, so seems a new issues has crept in?

**Comment by pnkfelix** [comment]
assigning to self to determine what status is for each of `brotli` and `diesel`, and to potentially file distinct issue for `diesel` if necessary.

**Comment by matthewjasper** [comment]
There is still #51044 which is fixed in #51042.

**Comment by RalfJung** [comment]
Diesel v1.2.2 still works fine with latest nightly but v1.3.0 is indeed broken.

**Comment by nikomatsakis** [comment]
Can somebody (@RalfJung?) file an issue describing the problem with diesel v1.3.0? (cc @sgrif)

Evidently the minimization from @matthewjasper [here] is not correct, because that [seems to work].

[here]: https://github.com/rust-lang/rust/issues/50825#issuecomment-390023746
[seems to work]: https://play.rust-lang.org/?gist=4968d144ba4966a18be94507e0952169&version=nightly&mode=debug

**Comment by matthewjasper** [comment]
The issue with 1.3.0 looks like #51044 

<details>

```text
error[E0277]: the trait bound `<expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Add` is not satisfied
  --> /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.3.0/src/expression/count.rs:58:39
   |
58 | #[derive(Debug, Clone, Copy, QueryId, DieselNumericOps)]
   |                                       ^^^^^^^^^^^^^^^^ the trait `sql_types::ops::Add` is not implemented for `<expression::count::CountStar as expression::Expression>::SqlType`
   |
   = help: consider adding a `where <expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Add` bound
   = help: see issue #48214
   = help: add #![feature(trivial_bounds)] to the crate attributes to enable

error[E0277]: the trait bound `<expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Sub` is not satisfied
  --> /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.3.0/src/expression/count.rs:58:39
   |
58 | #[derive(Debug, Clone, Copy, QueryId, DieselNumericOps)]
   |                                       ^^^^^^^^^^^^^^^^ the trait `sql_types::ops::Sub` is not implemented for `<expression::count::CountStar as expression::Expression>::SqlType`
   |
   = help: consider adding a `where <expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Sub` bound
   = help: see issue #48214
   = help: add #![feature(trivial_bounds)] to the crate attributes to enable

error[E0277]: the trait bound `<expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Mul` is not satisfied
  --> /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.3.0/src/expression/count.rs:58:39
   |
58 | #[derive(Debug, Clone, Copy, QueryId, DieselNumericOps)]
   |                                       ^^^^^^^^^^^^^^^^ the trait `sql_types::ops::Mul` is not implemented for `<expression::count::CountStar as expression::Expression>::SqlType`
   |
   = help: consider adding a `where <expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Mul` bound
   = help: see issue #48214
   = help: add #![feature(trivial_bounds)] to the crate attributes to enable

error[E0277]: the trait bound `<expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Div` is not satisfied
  --> /home/matthew/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.3.0/src/expression/count.rs:58:39
   |
58 | #[derive(Debug, Clone, Copy, QueryId, DieselNumericOps)]
   |                                       ^^^^^^^^^^^^^^^^ the trait `sql_types::ops::Div` is not implemented for `<expression::count::CountStar as expression::Expression>::SqlType`
   |
   = help: consider adding a `where <expression::count::CountStar as expression::Expression>::SqlType: sql_types::ops::Div` bound
   = help: see issue #48214
   = help: add #![feature(trivial_bounds)] to the crate attributes to enable

error: aborting due to 4 previous errors
```

</details>

**Comment by matthewjasper** [comment]
Brotli (1.2.0 and 1.1.2) and diesel (1.3.0 and 1.2.2) both compile on the latest nightly (as of #51042). Closing.
