### PR TITLE
Do not use effective_visibilities query for Adt types of a local trait while proving a where-clause

### LINKED ISSUE #145611: selection error diagnostics results in a query cycle
when fetching `effective_visibilities` for `Adt` self types of a local trait while proving a where-clause.

https://github.com/rust-lang/rust/blob/8c32e313cccf7df531e2d49ffb8227bb92304aee/compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs#L2871-L2889

This query fetches the hidden type of all opaque types https://github.com/rust-lang/rust/blob/8c32e313cccf7df531e2d49ffb8227bb92304aee/compiler/rustc_privacy/src/lib.rs#L1841-L1846

introduced in #143431, cc @xizheyin @compiler-errors

```rust
trait LocalTrait {}
struct SomeType;
fn impls_trait<T: LocalTrait>() {}
fn foo() -> impl Sized {
    impls_trait::<SomeType>();
}
```

results in
```
error[E0391]: cycle detected when computing type of `foo::{opaque#0}`
 --> src/lib.rs:4:13
  |
4 | fn foo() -> impl Sized {
  |             ^^^^^^^^^^
  |
note: ...which requires computing type of opaque `foo::{opaque#0}`...
 --> src/lib.rs:4:13
  |
4 | fn foo() -> impl Sized {
  |             ^^^^^^^^^^
note: ...which requires borrow-checking `foo`...
 --> src/lib.rs:4:1
  |
4 | fn foo() -> impl Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires promoting constants in MIR for `foo`...
 --> src/lib.rs:4:1
  |
4 | fn foo() -> impl Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires checking if `foo` contains FFI-unwind calls...
 --> src/lib.rs:4:1
  |
4 | fn foo() -> impl Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires building MIR for `foo`...
 --> src/lib.rs:4:1
  |
4 | fn foo() -> impl Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires match-checking `foo`...
 --> src/lib.rs:4:1
  |
4 | fn foo() -> impl Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
note: ...which requires type-checking `foo`...
 --> src/lib.rs:4:1
  |
4 | fn foo() -> impl Sized {
  | ^^^^^^^^^^^^^^^^^^^^^^
  = note: ...which requires checking effective visibilities...
  = note: ...which again requires computing type of `foo::{opaque#0}`, completing the cycle
note: cycle used when checking that `foo::{opaque#0}` is well-formed
 --> src/lib.rs:4:13
  |
4 | fn foo() -> impl Sized {
  |             ^^^^^^^^^^
  = note: see https://rustc-dev-guide.rust-lang.org/overview.html#queries and https://rustc-dev-guide.rust-lang.org/query.html for more information

error[E0277]: the trait bound `SomeType: LocalTrait` is not satisfied
 --> src/lib.rs:5:19
  |
5 |     impls_trait::<SomeType>();
  |                   ^^^^^^^^ the trait `LocalTrait` is not implemented for `SomeType`
  |
help: this trait has no implementations, consider adding one
 --> src/lib.rs:1:1
  |
1 | trait LocalTrait {}
  | ^^^^^^^^^^^^^^^^
note: required by a bound in `impls_trait`
 --> src/lib.rs:3:19
  |
3 | fn impls_trait<T: LocalTrait>() {}
  |                   ^^^^^^^^^^ required by this bound in `impls_trait`
```
note the query cycle before the actually desired error

### PR DESCRIPTION
**Pull request by xizheyin**
Partially fix rust-lang/rust#145611, but we should do something make cycle in this situation ICE.

Instead of using a query, call `&tcx.resolutions(()).effective_visibilities`.

r? @lcnr 

cc @compiler-errors

### CODE REVIEW

File: tests/ui/trait-bounds/trait-bound-adt-issue-145611.rs [hunk 1]
```diff
@@ -0,0 +1,8 @@
+trait LocalTrait {}
```
Comment (lcnr) [inline tests/ui/trait-bounds/trait-bound-adt-issue-145611.rs:4]: please add a quick comment to explain this test. I would have to otherwise lookup the issue to figure out what it is testing

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs [hunk 2]
```diff
@@ -2878,7 +2878,7 @@ impl<'a, 'tcx> TypeErrCtxt<'a, 'tcx> {
                                 // we check if `TraitB` can be reachable from `S`
                                 // to determine whether to note `TraitA` is sealed trait.
                                 if let ty::Adt(adt, _) = ty.kind() {
-                                    let visibilities = tcx.effective_visibilities(());
+                                    let visibilities = &tcx.resolutions(()).effective_visibilities;
```
Comment (lcnr) [inline compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs:2881]: okay :thinking: what does the `effective_visibilities` query actually do with the `effective_visibilities` computed by by nameres? I generally feel like it should have some more comments somewhere.

cc @petrochenkov maybe?

**Comment by lcnr** [comment]
@bors r- (forgot I've had a nit)

r=me after nit @bors delegate+

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs (hunk 2 above)
Comment (xizheyin) [reply compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs:2881]: I noticed that in versions prior to #143431, `&tcx.resolutions(()).effective_visibilities` was used in this way. As for what exactly it does, I'm not quite sure. At the time, I used this API as suggested.🤔

https://github.com/rust-lang/rust/pull/143431/files#diff-c712eee556d0df70dfc5c8c66c34fa13fc94a30853854f632f5dd84acfd9c973L2778

**Comment by xizheyin** [comment]
Added some comments for the test, waiting for CI green...
```
// This test is for regression of issue #145611
// There should not be cycle error in effective_visibilities query.
```

File: compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs (hunk 2 above)
Comment (petrochenkov) [reply compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs:2881]: > okay 🤔 what does the `effective_visibilities` query actually do with the `effective_visibilities` computed by by nameres?

Actually calculates them.
Name resolutions can only fill the "directly public" and "exported" levels, based on modules, reexports and nominal visibility.
The query uses type information and calculates the remaining "reachable" levels too.

Comment (petrochenkov) [reply compiler/rustc_trait_selection/src/error_reporting/traits/suggestions.rs:2881]: Here we are only checking Level::Reexported so it's ok to use the incomplete effective visibilities from name resolver.
