### ISSUE TITLE
rust-1.88.0 fails to build with glibc 2.42

### ISSUE THREAD

**Issue by tgurr** [rust-lang/rust#144904]
rust 1.88.0 fails to build with glibc 2.42 due to compiler-rt errors:

```
FAILED: [code=1] lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/sanitizer_platform_limits_posix.cpp.o 
/usr/host/bin/x86_64-pc-linux-gnu-c++ -DHAVE_RPC_XDR_H=0 -I/var/tmp/paludis/build/dev-lang-rust-1.88.0/work/rustc-1.88.0-src/src/llvm-project/compiler-rt/lib/sanitizer_common/.. -ffunction-sections -fdata-sections -fPIC -m64 -march=native -pipe -march=native -O2 -pipe -Wall -Wno-unused-parameter -O3 -DNDEBUG -std=c++17 -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fvisibility=hidden -fno-lto -O3 -g -Wno-variadic-macros -ftrivial-auto-var-init=pattern -nostdinc++ -Wno-format -fno-rtti -Wframe-larger-than=570 -MD -MT lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/sanitizer_platform_limits_posix.cpp.o -MF lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/sanitizer_platform_limits_posix.cpp.o.d -o lib/sanitizer_common/CMakeFiles/RTSanitizerCommon.x86_64.dir/sanitizer_platform_limits_posix.cpp.o -c /var/tmp/paludis/build/dev-lang-rust-1.88.0/work/rustc-1.88.0-src/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp
/var/tmp/paludis/build/dev-lang-rust-1.88.0/work/rustc-1.88.0-src/src/llvm-project/compiler-rt/lib/sanitizer_common/sanitizer_platform_limits_posix.cpp:489:31: error: invalid application of 'sizeof' to incomplete type '__sanitizer::termio'
  489 |   unsigned struct_termio_sz = sizeof(struct termio);
      |                               ^~~~~~~~~~~~~~~~~~~~~
```
Relevant part of build log: [rust-1.88.0-build-glibc-2.42.log](https://github.com/user-attachments/files/21578129/rust-1.88.0-build-glibc-2.42.log)

### Meta
The bundled compiler-rt is missing following recent upstream commits:

https://github.com/llvm/llvm-project/commit/59978b21ad9c65276ee8e14f26759691b8a65763
https://github.com/llvm/llvm-project/commit/0a17483c481d82eace3b36aee9cacb619eb027af
https://github.com/llvm/llvm-project/commit/c99b1bcd505064f2e086e6b1034ce0b0c91ea5b9

Applying them allows the build of rust 1.88.0 with glibc 2.42 to succeed.

**Comment by mati865** [comment]
1.89 beta probably fails the same way, which would be unfortunate because the release is imminent.

**Comment by heftig** [comment]
Never mind, the patch we had for this still applied but the build seems to be going through without it. Sorry for the noise.
