### ISSUE TITLE
Regression in 5 crates in 1.26: the trait bound is not satisfied

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#49932]
There are a few crates that are failing to build on Rust 1.26 with the error `the trait bound '###' is not satisfied`. A lot of those errors seems to be related with `!`.

* [bismuth](https://crates.io/crates/bismuth) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/bismuth-0.0.3/log.txt)) cc @olson-sean-k
* [cucumber](https://crates.io/crates/cucumber) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/cucumber-0.3.1/log.txt)) cc @acmcarther
* [plexus 0.0.1](https://crates.io/crates/plexus/0.1.1) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/plexus-0.0.1/log.txt)) - already fixed in plexus 0.0.9
* [rspec](https://crates.io/crates/rspec) regressed from stable to beta ([build log](http://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/rspec-1.0.0-beta.4/log.txt)) cc @mackwic
* [td_rredis](https://crates.io/crates/td_rredis) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.26.0-beta.2/beta-2018-04-06/reg/td_rredis-0.1.2/log.txt)) cc @tickbh

**Comment by mackwic** [comment]
thansk for the notification @pietroalbini ! Can I have the error log for rspec ?

**Comment by pietroalbini** [comment]
Woops! Forgot to add the link for that crate. Thanks for pointing that out!

**Comment by mackwic** [comment]
What is even `!` ? I don't understand this error 😕

**Comment by pietroalbini** [comment]
> What is even ! ? I don't understand this error :confused:

The `!` type is the "never" type, specified in [RFC 1216](https://github.com/rust-lang/rfcs/blob/master/text/1216-bang-type.md) and stabilized in 1.26. It basically means "this return value is unreachable". In your case, that's the value returned by `panic!`.

**Comment by Mark-Simulacrum** [comment]
Errors related to `!` might not be worth fixing just yet as I believe we're planning to revert that stabilization.

**Comment by acmcarther** [comment]
cucumber crate author here:

I wasn't able to replicate this from what I gleamed in the linked logs:
```
$ git clone git@github.com:acmcarther/cucumber && cd cucumber
$ rustup toolchain install beta-2018-04-06-x86_64-unknown-linux-gnu 
$ rustup default beta-2018-04-06-x86_64-unknown-linux-gnu
$ CARGO_INCREMENTAL=0 RUST_BACKTRACE=full RUSTFLAGS=--cap-lints=warn cargo test --no-run --frozen
# Build succeeds
```

Absent an actual reproduction though, I suspect dropping `return` from my `return panic` will probably resolve the issue in my crate.

**Comment by hawkw** [comment]
We're also seeing this when buillding `h2` against nightly: carllerche/h2#257.

**Comment by pietroalbini** [comment]
This will be fixed after #50121 (reverting the stabilization) is merged and backported into beta.

**Comment by pietroalbini** [comment]
The stabilization of `!` is now reverted both on beta and nightly. Sorry for the trouble!

**Comment by pietroalbini** [comment]
> A lot of those errors seems to be related with `!`.

Well, apparently not **all** of the errors in this issue were related to the never type. `plexus` is still failing on the latest beta (with the stabilization rollback backported):

```
 error[E0277]: the trait bound `u64: graph::geometry::Geometry` is not satisfied
   --> /.../plexus-0.0.1/src/graph/mesh.rs:90:1
    |
 90 | / pub struct Mesh<G = u64>
 91 | | where
 92 | |     G: Geometry,
 93 | | {
 ...  |
 96 | |     pub(super) faces: Storage<FaceKey, Face<G::Face>>,
 97 | | }
    | |_^ the trait `graph::geometry::Geometry` is not implemented for `u64`
    |
 note: required by `graph::geometry::Geometry`
   --> /.../plexus-0.0.1/src/graph/geometry/mod.rs:8:1
    |
 8  | pub trait Geometry: Sized {
    | ^^^^^^^^^^^^^^^^^^^^^^^^^
```

[Build log](http://cargobomb-reports.s3.amazonaws.com/1.26.0-beta-11/reg/plexus-0.0.1/log.txt)

**Comment by pietroalbini** [comment]
Bisected the plexus thing, the regression is caused by #46785, cc @leodasvacas @nikomatsakis

**Comment by leodasvacas** [comment]
That's intended, `G` can never be `u64` making the default unusable so we error. Given that crater was clean at the time of the change and that `plexus`, the only known affected crate, is only affected on a very old version I see no action to be taken.

**Comment by nikomatsakis** [comment]
That version of plexus seems to have no dependencies:

https://crates.io/crates/plexus/reverse_dependencies

There is a dependency on 0.0.1 from the bismuth crate -- cc @olson-sean-k, you may want to update to a newer version of plexus. =)

**Comment by pietroalbini** [comment]
Ok, I'll close this issue back.

**Comment by nikomatsakis** [comment]
@olson-sean-k <3
