### PR TITLE
Add a note describing the type of the non-Copy moved variable

### LINKED ISSUE #56654: NLL Diagnostic Review 3: missing a note describing the type of the non-Copy moved variable
The following note is missing on the output of the NLL borrow checker for `ui/use/use-after-move-self.nll.stderr`:

       |
       = note: move occurs because `self` has type `S`, which does not implement the `Copy` trait

### PR DESCRIPTION
**Pull request by csmoe**
Closes #56654
r?@davidtwco

### CODE REVIEW

**Review by bjorn3 — CHANGES_REQUESTED** [review]

File: src/test/ui/use/use-after-move-self.rs [hunk 1]
```diff
@@ -17,7 +18,7 @@ struct S {
 impl S {
     pub fn foo(self) -> isize {
         self.bar();
-        return *self.x;  //~ ERROR use of moved value: `*self.x`
+        return *self.x;  //~ ERROR use of moved value: `self`
```
[the remark this answers is not in the document]
Comment (csmoe) [reply src/test/ui/use/use-after-move-self.rs]: @bjorn3 I'd like the new one since it's more precise as you can see the earlier labeling of `value moved here` with `self`.

File: src/test/ui/borrowck/borrowck-move-out-from-array.mir.stderr [hunk 2]
```diff
@@ -5,6 +5,8 @@ LL |     let [_, _x] = a;
    |             -- value moved here
 LL |     let [.., _y] = a; //[ast]~ ERROR [E0382]
    |              ^^ value used here after move
+   |
+   = note: move occurs because `a[..]` has type `std::boxed::Box<i32>`, which does not implement the `Copy` trait
```
[the remark this answers is not in the document]
Comment (csmoe) [reply src/test/ui/borrowck/borrowck-move-out-from-array.mir.stderr]: @bjorn3 `ProjectionElem::Index` is described [here](https://github.com/rust-lang/rust/blob/0a1b2267e45ed0a5bdbfcbe522024729c8bd1387/src/librustc_mir/borrow_check/error_reporting.rs#L1560), then `a[..]` is kind of "generic" indexing(same as `a[1]`, `a[42]` etc), so `a` has type `[box i32]`, while `a[..]` is `box`.

[the remark this answers is not in the document]
Comment (csmoe) [reply src/test/ui/borrowck/borrowck-move-out-from-array.mir.stderr]: yep, `a[_]` should be better.

File: src/test/ui/use/use-after-move-self.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/test/ui/use/use-after-move-self.rs]: I also prefer the new message here. I think it is clearer that `self` is what has moved, not `*self.x`.

File: src/test/ui/borrowck/borrowck-move-out-from-array.mir.stderr (hunk 2 above)
[the remark this answers is not in the document]
Comment (davidtwco) [reply src/test/ui/borrowck/borrowck-move-out-from-array.mir.stderr]: I agree that `a[_]` seems more accurate here. Looks like this was introduced by #46041 and I can't see any comments in that PR or corresponding issue that specifically asked for this to be `a[..]` over `a[_]` - could you change this @csmoe?

**Comment by davidtwco** [comment]
Looks good to me, can merge this once existing review comments are resolved.

**Comment by csmoe** [comment]
@davidtwco oops, my fault, the .nll.stderr still unchanged, but while compiling with `-Z borrowck=mir` locally, the `note` was added indeed, how to trigger the diff in nll mode?

File: src/test/ui/borrowck/borrowck-move-out-from-array.mir.stderr (hunk 2 above)
[the remark this answers is not in the document]
Comment (csmoe) [reply src/test/ui/borrowck/borrowck-move-out-from-array.mir.stderr]: @davidtwco okay, testing locally.

**Comment by davidtwco** [comment]
> 
> 
> @davidtwco oops, my fault, the .nll.stderr still unchanged, but while compiling with `-Z borrowck=mir` locally, the `note` was added indeed, how to trigger the diff in nll mode?

I'm not exactly sure what you're asking - but if you want to run the tests with both compare modes, you'll need to change [your config.toml](https://github.com/rust-lang/rust/blob/7fb479c92b6358590a0180b00a416bb055b6548e/config.toml.example#L406). After that, running the UI tests with bless will update the NLL stderr files.

**Comment by csmoe** [comment]
@davidtwco I mean `note=` was not append to `ui/use/use-after-move-self.nll.stderr` as this PR wanna fix. while compiling the single test case locally: `./build/.../rustc src/test/ui/use/use-after-move-self.rs -Z borrowck=mir`, the `note=` was outputted indeed. but `./x.py test src/test/ui` didn't complain about diff between stderr and stdout.

**Comment by davidtwco** [comment]
> 
> 
> @davidtwco I mean `note=` was not append to `ui/use/use-after-move-self.nll.stderr` as this PR wanna fix. while compiling the single test case locally: `./build/.../rustc src/test/ui/use/use-after-move-self.rs -Z borrowck=mir`, the `note=` was outputted indeed. but `./x.py test src/test/ui` didn't complain about diff between stderr and stdout.

If there is no difference between the AST and NLL output then there is only a `.stderr` file, does this explain what you are seeing?

**Comment by davidtwco** [comment]
@csmoe could you rebase this PR on top of master (a PR gets merged with master before running any tests but that means that some new tests that this might apply to won’t have had their output updated - hence the need to rebase) and make sure you are running and updating the test output for the NLL compare mode too?

**Comment by csmoe** [comment]
@davidtwco soon.

File: src/test/ui/use/use-after-move-self.rs [hunk 3]
```diff
@@ -1,3 +1,4 @@
+//compile-flast: -Z borrowck=mir
```
Comment (matthewjasper) [inline src/test/ui/use/use-after-move-self.rs]:
```suggestion
//compile-flags: -Z borrowck=mir
```

Comment (davidtwco) [reply src/test/ui/use/use-after-move-self.rs]: Oops, didn't notice this. I think I'd prefer either removing the `// compile-flags` and letting the compare mode handle it (as it is currently with the misspelt comment) or adding an explicit `#![feature(nll)]`.
