### ISSUE TITLE
Rust beta: "cannot infer type" when compiling `bottom` crate

### ISSUE THREAD

**Issue by kamulos** [rust-lang/rust#96074]
Not sure who is correct here, or if this is expected: I just compiled the bottom crate version 0.6.8. This worked with the stable compiler, but failed with the current beta. The error message is the following:

```
error[E0283]: type annotations needed
   --> src/canvas/dialogs/dd_dialog.rs:385:22
    |
380 | /                     if app_state.dd_err.is_some() {
381 | |                         vec![Constraint::Percentage(100)]
382 | |                     } else {
383 | |                         vec![Constraint::Min(3), Constraint::Length(btn_height)]
384 | |                     }
385 | |                     .as_ref(),
    | |______________________^^^^^^_- this method call resolves to `&T`
    |                        |
    |                        cannot infer type for type parameter `T` declared on the trait `AsRef`
    |
    = note: multiple `impl`s satisfying `Vec<Constraint>: AsRef<_>` found in the `alloc` crate:
            - impl<T, A> AsRef<Vec<T, A>> for Vec<T, A>
              where A: Allocator;
            - impl<T, A> AsRef<[T]> for Vec<T, A>
              where A: Allocator;

error[E0283]: type annotations needed
   --> src/canvas.rs:630:59
    |
630 |                         .constraints(self.row_constraints.as_ref())
    |                                      ---------------------^^^^^^--
    |                                      |                    |
    |                                      |                    cannot infer type for type parameter `T` declared on the trait `AsRef`
    |                                      this method call resolves to `&T`
    |
    = note: multiple `impl`s satisfying `Vec<Constraint>: AsRef<_>` found in the `alloc` crate:
            - impl<T, A> AsRef<Vec<T, A>> for Vec<T, A>
              where A: Allocator;
            - impl<T, A> AsRef<[T]> for Vec<T, A>
              where A: Allocator;

For more information about this error, try `rustc --explain E0283`.
error: could not compile `bottom` due to 2 previous errors
```

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0-beta.2 (7c13df853 2022-04-09)
binary: rustc
commit-hash: 7c13df853721b60a03e7c0bb084d2eb1e27a9caa
commit-date: 2022-04-09
host: x86_64-unknown-linux-gnu
release: 1.61.0-beta.2
LLVM version: 14.0.0
```

**Comment by ehuss** [comment]
This is almost certainly caused by #95098.  cc @shepmaster 

A smaller repro:

```rust
#[derive(Clone)]
struct Constraint;

fn constraints<C>(constraints: C)
where C: Into<Vec<Constraint>>
{
    let _: Vec<Constraint> = constraints.into();
}

fn main() {
    constraints(vec![Constraint].as_ref());
}
```

**Comment by dtolnay** [comment]
This bisects to https://github.com/rust-lang/rust/commit/93313d108fb7aa209b6ed1ae64d7c05e425d69ad, so indeed #95098.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2396074.20Rust.20beta.3A.20.22cannot.20infer.20type.22.20when.20compiling.20.60botto.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high

**Comment by pnkfelix** [comment]
based on the injection point being #95098, isn't this a T-libs-api issue, not a T-compiler issue?

Switching tags under that assumption.

@rustbot label: -T-compiler +T-libs-api

**Comment by dtolnay** [comment]
For T-libs-api: I don't expect that we would choose to revert this. @rust-lang/libs-api

However it's not clear to me what type inference limitation makes the type unable to be inferred. Using the minimal repro from @ehuss, we have:

```rust
constraints(vec.as_ref());
```

Rustc can see that `.as_ref()` refers to `core::convert::AsRef<T>::as_ref` because there is no `as_ref` inherent method on `Vec` or any of the types it transitively derefs to, and `AsRef` is the only trait in scope with an `as_ref` method. The signature of `AsRef::as_ref` is `fn as_ref(&self) -> &T` and therefore the type of `vec.as_ref()` is `&T` for some `T`, as long as `Vec<Constraint>: AsRef<T>`.

The possibilities for `Vec<Constraint>: AsRef<T>` are `T = [Constraint]` and `T = Vec<Constraint>`.

Then it sees calling `constraints::<&T>` requires `&T: Into<Vec<Constraint>>` due to the `where`-clause. Previously this was satisfiable only by `T = [Constraint]` whereas after #95098 it's also satisfiable by `T = [Constraint; N]`.

Is it computationally hard to deduce from this that `T = [Constraint]`? As someone who doesn't know the type inference implementation in detail, my impression is this seems in line with inference that rustc is able to do successfully in other situations.

**Comment by yaahc** [comment]
> However it's not clear to me what type inference limitation makes the type unable to be inferred. Using the minimal repro from @ehuss, we have:

I recall some special cases in candidate assembly for allowing inference to continue when there is only one unambiguous impl, if I had to guess I'd say this is the same issue as https://github.com/rust-lang/rust/issues/90904.

I'm trying to find the special case, I think this might be it but I'm not sure:

https://github.com/rust-lang/rust/blob/b04c5329e1e145fb2fb46c5a7e775638712b03aa/compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs#L140-L156

Sadly I don't understand this well enough either to really understand whats going on. I think there's some rule in the compiler (maybe the bit above) that lets the ambiguous type parameter for `AsRef` to be inferred off of the type of the single candidate for `From` when there's only one, but as soon as you have two, even if only one of them is actually applicable, it ends up erroring out earlier and never uses the `From` impls to attempt to select an `AsRef` impl.

**Comment by shepmaster** [comment]
> (even so far as constraints being the method, but it looks like copy/paste code, maybe, not dependencies)

Perhaps copy-paste from the [tui crate's docs](https://docs.rs/tui/0.18.0/tui/index.html#layout):

```rust
let chunks = Layout::default()
    .direction(Direction::Vertical)
    .margin(1)
    .constraints(
        [
            Constraint::Percentage(10),
            Constraint::Percentage(80),
            Constraint::Percentage(10)
        ].as_ref()
    )
    .split(f.size());
```

[`constraints`](https://docs.rs/tui/latest/tui/layout/struct.Layout.html#method.constraints) is 

```rust
pub fn constraints<C>(mut self, constraints: C) -> Layout
where
    C: Into<Vec<Constraint>>,
```

**Comment by shepmaster** [comment]
> justification for these impls beyond just uniformity

My original justification was not uniformity, but to allow passing byte strings to `impl Into<Vec<u8>>` arguments which is somewhat common with FFI code.

Amusingly, the TUI example code is _improved_ by this change (IMO):

```rust
// doesn't compile
.constraints(vec![Constraint::Percentage(10)].as_ref())
// compiles
.constraints(vec![Constraint::Percentage(10)].as_slice())
.constraints(vec![Constraint::Percentage(10)])
.constraints([Constraint::Percentage(10)].as_ref())
.constraints(&[Constraint::Percentage(10)])
.constraints([Constraint::Percentage(10)])
```

**Comment by joshtriplett** [comment]
If we think we can improve inference in the compiler to avoid this, then this does seem worth reverting on beta.

cc @rust-lang/wg-traits @rust-lang/compiler; does this seem fixable through better inference?

**Comment by estebank** [comment]
> If we think we can improve inference in the compiler to avoid this

The only problem I see is that *changing* inference to get these to work might be doable, but not necessarily in the right way, which scares me because it would necessarily mean having a more lenient version of [`evaluate_candidate`](https://github.com/rust-lang/rust/blob/b04c5329e1e145fb2fb46c5a7e775638712b03aa/compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs#L162) or [`candidate_should_be_dropped_in_favor_of`](https://github.com/rust-lang/rust/blob/b04c5329e1e145fb2fb46c5a7e775638712b03aa/compiler/rustc_trait_selection/src/traits/select/candidate_assembly.rs#L188) (which introduces the possibility of more mistakes) and could necessitate an increase in the number of evaluation passes (slowing down compilation for everyone).

I'd still be on favor of delaying landing this until 1.62 to buy us time to evaluate (but t-libs-api has jurisdiction).

**Comment by yaahc** [comment]
:+1: for revert and re-evaluate, @shepmaster correct me if I'm wrong but there's no urgency here, correct?

I do think this might fall within the set of changes that we'd potentially just allow breakage on, similar to https://github.com/rust-lang/rust/pull/75180 where we manually updated all the crates identified by crater.

Additionally, I'm wondering if https://github.com/rust-lang/rfcs/pull/3240 could be extended to cover this case so we could move the breakage to an edition boundary. I'm hoping that might allow for a simpler solution.

**Comment by estebank** [comment]
Looking at [`candidate_should_be_dropped_in_favor_of`](https://github.com/rust-lang/rust//blob/ec667fbcfcd29e2b5080f6be04e229356b27e600/compiler/rustc_trait_selection/src/traits/select/mod.rs#L1710-L1775), it seems like right place for https://github.com/rust-lang/rfcs/pull/3240 (or similar) mechanism to be implemented.

**Comment by jackh726** [comment]
(fair warning, I've only skimmed this thread)

Interestingly, I think this might be a similar "problem" to the one that gets discussed with Chalk with the SLG vs recursive solver (some background: https://rust-lang.github.io/chalk/book/recursive.html#recursion-and-completeness). Without going into specific details, I think committing to a "smarter" inference here has practical effects in an eventual more-formal solver.

I wouldn't want to apply an ad-hoc solution to this problem to the trait solver without thinking about how we implement this in the future. Also given that there are ongoing efforts to define that, I think reverting for now is a good option.

**Comment by shepmaster** [comment]
> there's no urgency here for landing this asap

None that I know of. 

The only downside is that I used the original PR as a way to show someone "look how easy it is to submit changes to Rust" 😉

**Comment by estebank** [comment]
I came up with the following unprincipled hack: https://github.com/rust-lang/rust/pull/96446

Doing anything like this would in effect turn both `Vec` and `AsRef` into `lang_items`. I didn't see the mechanism that https://github.com/rust-lang/rfcs/pull/3240 proposes for setting the edition on the `impl`, but whatever does that (an attribute?) would be something that'd have to be able to [express this kind of check](https://github.com/rust-lang/rust/pull/96446/files#diff-34d5893dd95fe09f9a0fd3341efacd1c21853bb34ba29d9d79bb9af26bb8a0a0R1771-R1779).

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/libs meeting.

Could we get a revert PR, please? We can then mark that as beta-nominated/beta-accepted.

**Comment by shepmaster** [comment]
Opened #96489

**Comment by jplatte** [comment]
I think making inference even 'smarter' is just going to lead to more code that implicitly relies on certain impls *not* existing, which will ultimately prohibit more impls from being added because some ambiguities just cannot be resolved cleanly.

I would much rather see existing code that relies on there's-only-one-impl-for cleverness start raising future-incompat errors. Maybe we could even have `impl Add<char> for String` and friends at some point then.

**Comment by pnkfelix** [comment]
Visiting this issue during T-compiler triage meeting.

We believe the beta backport of PR #96489 addresses the issue this was nominated for.

@rustbot label: -I-nominated-compiler

**Comment by apiraino** [comment]
:) 

@rustbot label -I-compiler-nominated

**Comment by Mark-Simulacrum** [comment]
Clearing milestone as we have landed https://github.com/rust-lang/rust/pull/96489 on master (1.62+) and backported it to 1.61, so this is no longer a regression.

**Comment by Enselic** [comment]
Triage: The revert is done and consensus seems to be to not change inference. Closing.
