### PR TITLE
Stabilize `#[cfg(version(...))]`

### PR DESCRIPTION
**Pull request by est31**
## Stabilization report

This proposes the stabilization of `cfg_version` ([tracking issue](https://github.com/rust-lang/rust/issues/64796), [RFC 2523](https://github.com/rust-lang/rfcs/pull/2523)).

### What is being stabilized

Permit users to `cfg` gate code sections based on the currently present rust version.

```Rust
#[cfg(version("1.87"))]
pub fn from_utf8_unwrap(buf: &[u8]) -> &str {
    str::from_utf8(buf).unwrap()
}

#[cfg(not(version("1.87")))]
pub fn from_utf8_unwrap(buf: &[u8]) -> &str {
    std::str::from_utf8(buf).unwrap()
}
```

### Tests

The first test was added by the original implementation PR https://github.com/rust-lang/rust/pull/71314 , and is mostly a test for the allowed and not allowed ways to specify the version as part of the attribute. It has seen some changes as the implementation of `cfg_version` has been changed. As of this PR, the test ensures:

* `#[cfg(version(1.20.0))]` is not allowed, deviating from the RFC
* The expected syntax is `#[cfg(version("1.20.0"))]`
* small shortenings like `#[cfg(version("1.20"))]` are allowed, but `#[cfg(version("1"))]` is not
* postfixes to the version, like `#[cfg(version("1.20.0-stable"))]` are not allowed
* `#[cfg(version = "1.20.0")]` is not supported, and there is a warning of the `unexpected_cfgs` lint (but no compilation error)

The stabilization PR also adds a functional test, which ensures that `cfg_version` actually works.

* `#[cfg(version = "1.20.0")]` acts as if the cfg was false due to the wrong syntax, even if the compiler version is above the specified version
* `cfg!(version("1.50.4"))` evals as false on `1.50.3`, and `cfg!(version("1.50.3"))` evals as true.

Lastly, there is [assume-incomplete.rs](https://github.com/rust-lang/rust/blob/107896c32d5dda4db508968ff34997a39d286966/src/test/ui/cfg/assume-incomplete-release/assume-incomplete.rs) using macros instead of `RUSTC_OVERRIDE_VERSION_STRING`.

This PR makes `cfg(version)` respect `RUSTC_OVERRIDE_VERSION_STRING`, to make it easier to test things, and adds a test based on that.

### Development of the implementation

The initial implementation was added by PR https://github.com/rust-lang/rust/pull/71314 which used the `version_check` crate.

PR https://github.com/rust-lang/rust/pull/72001 made `cfg(version(1.20))` eval to false on `nightly` builds with version `1.20.0`, upon [request from the lang team](https://github.com/rust-lang/rust/issues/64796#issuecomment-625474439). This decision was pushed back on by `dtolnay` in [this](https://github.com/rust-lang/rust/issues/64796#issuecomment-634546711) comment, leading to `nikomatsakis` [reversing his decision](https://github.com/rust-lang/rust/issues/64796#issuecomment-640804196).

Ultimately, a compromise was agreed upon, in which nightly releases are treated as "complete" i.e. `cfg(version(1.20))` evals to true on `nightly` builds with version `1.20.0`, but there is a nightly flag `-Z assume-incomplete-release` to opt into the behaviour that doesn't do this assumption. This compromise was implemented in PR https://github.com/rust-lang/rust/pull/81468.

PR https://github.com/rust-lang/rust/pull/81259 made us adopt our own parsing code instead of using the `version_check` crate.

### Unresolved questions

Should we lint for `cfg(version)` probing for a compiler version below the specified MSRV? Part of a larger discussion on [MSRV specific behaviour](https://github.com/rust-lang/rust/issues/129445) in the Rust compiler. It feels like it should be a rustc lint though instead of a clippy lint.

### Future work

The stabilization doesn't close the tracking issue, as the `#[cfg(accessible(...))]` part of the work is still not stabilized, currently requiring an implementation (if an implementation is something we'd want to merge in the first place).

### See also

[Earlier stabilization report](https://github.com/rust-lang/rust/issues/64796#issuecomment-799847092)

### TODOs before stabilization

- [ ] https://github.com/rust-lang/rust-clippy/issues/14827 . Not a hard blocker, but the lint is warning by default and people will probably hit it in fairly common combinations.
- [ ] should we sync up with the cargo implementation? There is currently nothing implemented in cargo yet. https://github.com/rust-lang/cargo/issues/15531
- [x] reference PR: https://github.com/rust-lang/reference/pull/1828

### CODE REVIEW

File: compiler/rustc_feature/src/accepted.rs [hunk 1]
```diff
@@ -107,6 +107,8 @@ declare_features! (
     (accepted, cfg_target_feature, "1.27.0", Some(29717)),
     /// Allows `cfg(target_vendor = "...")`.
     (accepted, cfg_target_vendor, "1.33.0", Some(29718)),
+    /// Allow conditional compilation depending on rust version
```
Comment (traviscross) [inline compiler/rustc_feature/src/accepted.rs:110]:
```suggestion
    /// Allow conditional compilation depending on Rust version.
```

**Comment by traviscross** [comment]
This looks right to me.  Thanks to @est31 for putting this together and for the careful stabilization report.  I propose that we do this.

@rfcbot fcp merge

**Comment by traviscross** [comment]
Thanks also to @epage for perhaps prodding us along here, in his recent talk, by pointing out the cost to ecosystem compile time performance of not doing this.

File: compiler/rustc_attr_data_structures/src/version.rs
Comment (Noratrieb) [inline compiler/rustc_attr_data_structures/src/version.rs:1]: I think the example of the stabilization report, let chains, are a particularly bad example here because they're *syntax*, and syntax is, except for some old legacy stuff, gated pre-expansion, so cfg(version) won't actually help there. It would probably make sense to mention this in the reference that this can't really be used for conditionally making use of syntax, or rather that such uses requires going through an intermediary macro_rules to avoid parsing it on the old version.

Comment (est31) [reply compiler/rustc_attr_data_structures/src/version.rs:1]: Updated the example to use a libs function instead. The example still fails compilation on the old release, because `#[cfg(version(...))]` errors on compilers that don't have the stabilization yet, so it's only useful when your MSRV is >= the release that `#[cfg(version(...))]` stabilized in.

It's actually maybe something that one can discuss, whether to support `#[cfg(version = "...")]` as well. This syntax does not error on older compilers, or on current ones. The disadvantage is two different ways of doing things and possible breakage because it might activate some blocks within `#[cfg(version = "...")]`, but I'd say that breakage is rather theoretical.

In the long term, `#[cfg(version = "...")]` is not neccessary: it's only helpful for the transitory period.

Comment (traviscross) [reply compiler/rustc_attr_data_structures/src/version.rs:1]: If we were to take the breakage here, I'm not sure why we wouldn't just make `#[cfg(version = "..")]` the one way to write this.

The concern I recall hearing was the worry that people might think this was a version equality constraint rather than a `^` or `>=` constraint, but that doesn't seem to be a problem for Cargo dependencies, where e.g. `time = "0.1.12"` means `time = "^0.1.12"`, or for the MSRV field itself, e.g. `rust-version = "1.89"`.

If we were still concerned, we could require people to write, e.g. `#[cfg(version = "^1.89")]` explicitly.

Comment (traviscross) [reply compiler/rustc_attr_data_structures/src/version.rs:1]: Looking at the RFC, the question was considered in the context of `cfg(accessible(..))` vs `cfg(accessible = ..))`, where yes, the former is definitely seems better.

File: tests/ui/cfg/cfg-version/cfg-version.rs [hunk 2]
```diff
@@ -1,49 +1,35 @@
 #[cfg(version(42))] //~ ERROR: expected a version literal
-//~^ ERROR `cfg(version)` is experimental and subject to change
 fn foo() {}
 #[cfg(version(1.20))] //~ ERROR: expected a version literal
```
Comment (madsmtm) [inline tests/ui/cfg/cfg-version/cfg-version.rs:3]: What's the reasoning we don't use this syntax again?

From reading https://github.com/rust-lang/rust/pull/71314, it seems like [it was punted on for later because of implementation difficulty](https://github.com/rust-lang/rust/pull/71314#discussion_r414877674). Maybe that's not true any more? I'd prefer writing `#[cfg(version(1.87.1))]` than `#[cfg(version("1.87.1"))]`.

File: compiler/rustc_attr_data_structures/src/version.rs
Comment (madsmtm) [reply compiler/rustc_attr_data_structures/src/version.rs:1]: Re `cfg(version = "...")`, see [the RFC text](https://rust-lang.github.io/rfcs/2523-cfg-path-version.html#the-bikeshed---argument-syntax). This is actually also [listed in the unresolved questions in the tracking issue](https://github.com/rust-lang/rust/issues/64796), and was discussed briefly [on the tracking issue](https://github.com/rust-lang/rust/issues/64796#issuecomment-939364992).

---

IMO, I think we should only support `cfg(version = "...")` if we emitted all the (hundreds of) valid `version="1.0"`, `version="1.0.0"`, `version="1.1"`, `version="1.1.0"`, etc. as part of `rustc --print cfg` too.

**Comment by jieyouxu** [comment]
I'll hold off on reviewing the impl until some of the design questions are settled (looks like there are unresolved design concerns), please ping me if it's ready for impl review.

File: tests/ui/cfg/cfg-version/cfg-version.rs (hunk 2 above)
Comment (traviscross) [reply tests/ui/cfg/cfg-version/cfg-version.rs:3]: It makes a certain sense to me to quote it as it is a "version string".  In attributes, we generally still try to match the general grammar of Rust, and we wouldn't accept an unquoted `1.87.1` as an argument anywhere else.

File: compiler/rustc_attr_data_structures/src/version.rs
Comment (traviscross) [reply compiler/rustc_attr_data_structures/src/version.rs:1]: It does seem at this point that we should just stabilize `cfg(version(".."))`.  We could always decide later about doing more.

File: tests/ui/cfg/cfg-version/cfg-version.rs (hunk 2 above)
Comment (madsmtm) [reply tests/ui/cfg/cfg-version/cfg-version.rs:3]: > we wouldn't accept an unquoted `1.87.1` as an argument anywhere else.

I can see the argument, though I don't see why that should necessarily be an absolute? Syntactically, you can write `let x = 1.87.1`, though that's of course parsed as "literal 1.87" + "field access 1" (which then fails because floats don't have any fields).

Idk., I just think it's unfortunate that we limit ourselves here, since I suspect the vast majority of cases where `cfg(version(...))` is useful, you wouldn't need to specify the patch version - looking at the changelog, I actually cannot find a single use-case where you'd want `cfg(version(major.minor.patch))` where `patch` wouldn't just be `0`?

If we wanted this syntax, an option could be to disallow patch versions to begin with?

---

A difficulty with `major.minor.patch` is on the macro-side, I see a few ways to solve this:
1. The heavy-weight: Introduce a new token literal `LitKind::Version` and change `$x:literal` over an edition to contain this as well.
2. Define that the token parsing is `cfg(version($major_minor:literal $(. $patch:tt)?))`.
3. Specialize parsing of this as one token, but try to hide it from the language. Though that has unclear interactions with macros such as:
    ```rust
    macro_rules! split {
        ($x:tt) => { cfg!(version(1.87 . $x)) };
    }

    macro_rules! split {
        ($x:tt) => { cfg!(version($x . 87 . 1)) };
    }
    ```
    
    Maybe we can disallow those? But we'd want a stable way for `proc-macro`s to create the required `TokenTree::Literal`.

Regardless, I think what I'm saying with this is that while this doesn't have an immediately clean solution, the solution space isn't empty, and I think it's worthwhile it to choose one of these options to get the cleaner syntax. But I guess I'm also motivated here by [future attributes with versions in them](https://github.com/rust-lang/rfcs/pull/3750).

Comment (madsmtm) [reply tests/ui/cfg/cfg-version/cfg-version.rs:3]: CC @petrochenkov who reviewed the implementation PR that did `cfg(version("major.minor.patch"))` (with the quotes).

**Comment by joshtriplett** [comment]
The proposal as originally reviewed and approved was for `cfg(version(...))`, and adding `cfg(version = "...")` was considered and rejected, in part because of the potential confusion of "equals".

It's already not going to be *functional* in any version older than the version that stabilizes `cfg(version(...))`. It doesn't seem worth re-adding or changing the syntax just to make it always-false in older versions, particularly since code that still *supports* those older versions may need to do version detection that distinguishes some of those older versions (e.g. "is this 1.70 or newer").

I would argue that it's a **bug** to silently ignore it in older versions, precisely because it'll be non-functional: `cfg(version = "1.70")` will be silently false in 1.70, 1.71, 1.72, up through whatever version stabilizes version checks.

Pieces of the ecosystem can switch to `cfg(version(...))` as their MSRVs become sufficiently new that it works.

**Comment by traviscross** [comment]
> I would argue that it's a **bug** to silently ignore it in older versions, precisely because it'll be non-functional: `cfg(version = "1.70")` will be silently false in 1.70, 1.71, 1.72, up through whatever version stabilizes version checks.
> 
> Pieces of the ecosystem can switch to `cfg(version(...))` as their MSRVs become sufficiently new that it works.

Agreed.

File: compiler/rustc_attr_data_structures/src/version.rs
Comment (joshtriplett) [reply compiler/rustc_attr_data_structures/src/version.rs:1]: Regarding `cfg(version = "...")`, see https://github.com/rust-lang/rust/pull/141137#issuecomment-2892091613 .

File: tests/ui/cfg/cfg-version/cfg-version.rs (hunk 2 above)
Comment (epage) [reply tests/ui/cfg/cfg-version/cfg-version.rs:3]: From a tokenization perspective, a string fits best. A major/minor version could look like a float which we don't have now but I do want to explore bools, ints, and floats for `--cfg` for cargo "globals" though I don't have use cases for `#[cfg]` operators for these at this time

File: compiler/rustc_attr_data_structures/src/version.rs
Comment (epage) [inline compiler/rustc_attr_data_structures/src/version.rs:1]: > small shortenings like #[cfg(version("1.20"))] are allowed, but #[cfg(version("1"))] is not

This is a bit inconsistent with other places where a Cargo user puts in a version/version range.
- `package.version` requires all fields
- `package.rust-version` has 1-3 fields
- `dependencies.*.version` has 1-3 fields

I know `version("1")` is pretty meaningless (which so is the same for `package.rust-version`).

I guess the question for me is whether `package.rust-version` should be
- the same syntax with the same parser implementation
- a different syntax in which we want to make sure our parser is unique to avoid changes in one affecting the other

**Comment by ehuss** [comment]
> I'm curious to hear from the @rust-lang/cargo team their thoughts and any particular reasons for why we might want to hold off merging the lang-side change here pending the Cargo-side work.

We think it would be best if we can make sure the change lands in both cargo and rustc in the same release. There is already someone working on it, and I think we are pretty comfortable that we will be able to get that merged in time, so I don't think there is a strong reason to block. I'll try and make sure that everything is ready, though we should be careful about the scheduling in mid-june if the stabilization process here takes a long time.

**Comment by tmandry** [comment]
@rfcbot concern has_cfg_version

I do want to stabilize this, but in its current form I think it's too limited in its usefulness. It requires bumping an MSRV past the version where this lands before you can _use_ the feature, whose entire purpose is improving portability across compiler versions. The problem is that any use of `#[cfg(version(..)]` in an old compiler results in a compiler error, and you would need a cfg-version-like build script to gate your use of `#[cfg(version)]`.

@scottmcm came up with the idea to include a `#[cfg(has_cfg_version)]` that is enabled along with this feature. I really like this and think we should include it along with the stabilization of `#[cfg(version(..))]`, so you can start using the feature right away without breaking your support for older compiler versions. This allows us to "bootstrap" the use of `#[cfg(version)]` without bumping MSRV, and will get phased out as compilers bump their MSRV past the version where `#[cfg(version)]` gets introduced.

I would like to see us stabilize these together; otherwise you would have a window of time where `#[cfg(version(..))]` exists but `#[cfg(has_cfg_version)]` does not. I think this would add further confusion and historical noise.

I don't want to block this feature for much longer, so I'm holding out hope for a quick consensus and resolution. Otherwise, if the rest of the team agrees we should move forward to stabilize without the extra cfg (whether or not we add it later), I'll withdraw my concern. (If I'm not around, you can resolve it for me by restarting fcp.)

**Comment by epage** [comment]
If I'm understanding correctly, the use case of ` #[cfg(has_cfg_version)]` is
- Your MSRV is below 1.89
- You don't have any version checks from before 1.89
- You need a version check for something after 1.89

If you need version checks before 1.89, then you'll still need `rustversion` or one of its variants.  That seems fairly limited for the "now".  Then there is the "future" when MSRVs are hovering close to 1.89.  As a potential alternative,. I wonder if we could encourage major projects to wait for 1.89 due to the impact on long-term support (the previous one I would consider recommending is 1.84 due to MSRV-aware resolver).

For completeness, Cargo would not be able to support something like `#[cfg(has_cfg_version)]`.  The bias of my use cases says that Cargo without `has_cfg_version` wouldn't provide much value *but* I assume there are enough use cases left since `rustversion` and related crates show the need for this. I tried looking at crates to see how they were using `rustversion` but I didn't find the ones I was looking at before and the top dependents by download count are instead using this for dev-dependencies.  I know at least macros do this to control the version of diagnostics they snapshot, so I didn't dig too much deeper.

**Comment by epage** [comment]
> I could also see myself using #[cfg(has_cfg_version)] to toggle on less important things like small runtime optimizations that require a version between my MSRV and 1.89, but that are not worth the compile-time hit of #[rustversion] or a build script.

I'm not quite following.  `has_cfg_version` just lets you know whether you can use `#[cfg(version())]`.  You have no idea what version between your MSRV and 1.89 it is.  This would help for any small runtime optimizations you could perform for 1.89+.

**Comment by jplatte** [comment]
I guess I should have included this in my quote:

> If you need version checks before 1.89, then you'll still need `rustversion` or one of its variants.

My point was, if one is considering a version check for a feature that was introduced in 1.87.0, but it's only a small perf optimization, one might opt to use `#[cfg(has_cfg_version)]` even though that means users on 1.87 and 1.88 don't get the optimization when they could.

**Comment by tmandry** [comment]
> If I'm understanding correctly, the use case of ` #[cfg(has_cfg_version)]` is
> 
> * Your MSRV is below 1.89
> * You don't have any version checks from before 1.89
> * You need a version check for something after 1.89

Exactly. It seems common enough to need to pin a crate on a low MSRV that I think we should support it. And those crates are sometimes the crates at the root of every build tree, so we want them to be able to use this feature rather than a build script.

> The bias of my use cases says that Cargo without `has_cfg_version` wouldn't provide much value _but_ I assume there are enough use cases left since `rustversion` and related crates show the need for this.

It's a good point; I don't have a good mental model of the use cases here. One is the diagnostics support in proc macros you mentioned. Another I've heard is working around compiler bugs. I know I've definitely heard a steady drip of people saying they need this feature, but I don't remember all the reasons.

The most obvious use case is supporting new traits and code paths in std or new features in the language. But this can already be controlled with feature gates, so I don't think we should design the feature around that. We might want to go as far as discouraging its use for that, because of how rustc-centric the feature is.

**Comment by est31** [comment]
> in its current form I think it's too limited in its usefulness. It requires bumping an MSRV past the version where this lands before you can use the feature, whose entire purpose is improving portability across compiler versions.

Immediately when `#[cfg(version(...))]` stabilizes, the feature (without a `cfg_has_cfg_version`) is definitely not useful, yes. But in the longer term, thinking of years, ecosystem will adopt `#[cfg(version(...))]` as the MSRV is being increased. For example, [`serde` is on 1.56](https://github.com/serde-rs/serde/blob/da3998acfb80a8e4ea60c8cd9caa0dc83f8bb518/.github/workflows/ci.yml#L87), since https://github.com/serde-rs/serde/pull/2901, and that PR indicates future MSRV increases. But `has_cfg_version` can get the change out faster, definitely.
 
Even with `has_cfg_version`, we won't be able to immediately dry up the market for running rustc to figure out its version: there will still be crates with:
* MSRVs below the 1.89, and
* wanting to provide additional features to users of compilers between MSRV and 1.89.

They will need to keep their build scripts. They might even be forced by their semver guarantees.

With all of this being said, I think it still makes sense to add `cfg_has_cfg_version` though, as an unconditionally present cfg. There will be crates that adopt *new* features coming after 1.89, or ones that are fine with not having the most optimal experience on versions before 1.89, which have an older MSRV. Those will benefit from `cfg_has_cfg_version`.

I have added the `cfg_has_cfg_version` cfg to this PR.

**Comment by tmandry** [comment]
Thanks for the quick response @est31! I agree that it's not a silver bullet, but I do think it will be useful in a lot of cases.

With that I will resolve my concern.

@rfcbot resolve has_cfg_version

Leaving nominated to make sure lang members who already checked their boxes are aware of the change. I discussed it in the last meeting and no one expressed opposition to the idea of has_cfg_version, so I don't think we need to restart fcp.

**Comment by joshtriplett** [comment]
Regardless of whether we want `has_cfg_version` or not, I'd like to flag the process problem of making last-minute changes *as part of stabilization*, in the last day of FCP, within 24 hours of proposing them, and then having that FCP conclude. FCP isn't just for team members, it's meant to be a comment period for the community as well, and the 10-day period ensures that people have time to see it.

**Comment by traviscross** [comment]
In the spec call, @joshtriplett and I briefly discussed the existence of the `has_cfg_version` change.  Probably, though, it's still best process to just restart to give him the opportunity to review and recheck the box, and that also signals to others watching that the proposal has changed.

@rfcbot cancel

**Comment by traviscross** [comment]
Proposing for merge with the inclusion of `cfg(has_cfg_version)`.

@rfcbot fcp merge

**Comment by traviscross** [comment]
@est31, if you would, please update the stabilization report to include `cfg(has_cfg_version)`.

**Comment by RalfJung** [comment]
Yeah I think we should still do that (i.e. split up this PR), also to make it easier to revert just the stabilization should that be needed.

**Comment by traviscross** [comment]
Yes, agreed.  The `has_cfg_version` change should definitely go in its own PR.  It's convenient on the lang side too if these stabilization PRs are mechanical in the way that you say.

Having talked with others, though, about similar observations and concerns about it being clear to everyone what the proposal is and what's being stabilized, let's actually go further and just close this PR and ask for a new v2 stabilization PR to be opened after `has_cfg_version` has landed in nightly and a new stabilization report is ready that includes it.

@rfcbot cancel

**Comment by joshtriplett** [comment]
@traviscross Though, if we decide to go ahead and stabilize `cfg(version(...))` *without* `has_cfg_version` we don't need to jump through those hoops.

**Comment by traviscross** [comment]
Yes, agreed.  The PR author accepted the change, though, and made it part of the proposal.  That's why I'd say it deserves a new PR at this point.

**Comment by joshtriplett** [comment]
Leaving aside the procedural concern about last-minute changes...

Regarding `has_cfg_version` itself: while this is not a blocking objection if everyone else is in favor, I do think it would have been reasonable to simply let people continue using build-script-based detection if they're not willing to upgrade their MSRV, since they'll still have to do so if they actually want to distinguish between older versions.

`has_cfg_version` would prove rather challenging to use correctly. In versions of Rust that don't support it, it'll produce:
> warning: unexpected `cfg` condition name: `has_cfg_version`

If you want your code to build warning-free, you'll have to make sure rustc is aware of it, which requires adding a `lints.rust.unexpected_cfgs` stanza `Cargo.toml`, or similar.

And you also *have* to write `cfg(has_cfg_version)` as a separate `#[cfg(...)]` attribute. If you write, for instance, `#[cfg(all(has_cfg_version, version("...")))]`, compilers that don't have `version` available to stable code will error, because `version` is "experimental and subject to change". You have to write, instead, `#[cfg(has_cfg_version)]` followed by `#[cfg(version(...))]`.

For people using *current* Rust, nothing will catch either of those problems; you'll only see them if you go back and build with older Rust. And once you do, you'll have to take the additional step of adding the `Cargo.toml` stanza to solve the first problem.

And for the especially common case of "add this dependency if building on older Rust", it's not obvious whether it'd be feasible to make that work in older Cargo. AFAICT, `has_cfg_version` doesn't solve the problem of `cfg(not(version(...)))`.

I think the net result is added complexity that users have to deal with for simple version detection, and several easy ways to get it wrong.

**Comment by jplatte** [comment]
> `has_cfg_version` would prove rather challenging to use correctly. In versions of Rust that don't support it, it'll produce:
> 
> > warning: unexpected `cfg` condition name: `has_cfg_version`
> 
> If you want your code to build warning-free, you'll have to make sure rustc is aware of it, which requires adding a `lints.rust.unexpected_cfgs` stanza to `Cargo.toml`, or similar.

Since dependencies are built with cap-warnings, I don't think it would be important to do this usually. I don't remember seeing projects have a deny-warnings CI job _for their MSRV_, it tends to always be stable or nightly.

> And you also _have_ to write `cfg(has_cfg_version)` as a separate `#[cfg(...)]` attribute. If you write, for instance, `#[cfg(all(has_cfg_version, version("...")))]`, compilers that don't have `version` available to stable code will error, because `version` is "experimental and subject to change". You have to write, instead, `#[cfg(has_cfg_version)]` followed by `#[cfg(version(...))]`.
>
> For people using _current_ Rust, nothing will catch either of those problems; you'll only see them if you go back and build with older Rust. And once you do, you'll have to take the additional step of adding the `Cargo.toml` stanza to solve the first problem.

Yeah, it's a bit ugly but many projects that set an MSRV have a CI job that tests that things compile with that MSRV, right?

**Comment by jieyouxu** [comment]
> @tmandry wrote:
> 
> > I would like to see us stabilize these together; otherwise you would have a window of time where `#[cfg(version(..))]` exists but `#[cfg(has_cfg_version)]` does not. I think this would add further confusion and historical noise.
> 
> I don't think this is inherently the case. Anyone who was prepared to use `cfg(version(...))` as it was 24 hours ago would be able to immediately use it. Anyone who doesn't mind jumping through additional hoops in order to use `cfg(has_cfg_version)` to support pre-cfg-version compilers could do that hoop-jumping once `cfg(has_cfg_version)` ships.
> 
> In other words: it seems like a feature that should make its own case, and ship on its own timeline (namely, not 24 hours, or even 10 days, after being first proposed), rather than being inherently tied to `cfg(version(...))`.

FTR, if cargo support for these aren't a stabilization blocker, if we land `cfg(has_cfg_version)` unstably *separately* first, then it's mechanically possible to have a joint stabilization PR of `cfg(has_cfg_version)` + `cfg(version(..))`, if those are the current design consensus as a *joint language feature* (i.e. collectively forms the concept of the `cfg(version(..))` language feature).

**Comment by traviscross** [comment]
> I think the net result is added complexity that users have to deal with for simple version detection, and several easy ways to get it wrong.

You make a compelling case about this being rather hard to use.  Both @scottmcm  and I were OK with stabilizing `cfg(version(".."))` without `has_cfg_version`.  Let's take a poll to see where we all fall here.  I'll check your box and scottmcm's box based on what he said in the meeting.

The question is, "would you stabilize `cfg(version(".."))` without `has_cfg_version`?"  We could of course address `has_cfg_version` separately and later.

@rfcbot poll

**Comment by joshtriplett** [comment]
@jplatte wrote:
> Since dependencies are built with cap-warnings, I don't think it would be important to do this usually.

That doesn't help binaries. And even for libraries, sometimes people work on the library itself, or vendor the library into their workspace, or use it via path dependency, at which point you'll see those warnings.

Also, the issue of handling this in Cargo, and the issue of handling the `cfg(not(version(...)))` case without code duplication, still remain.

**Comment by traviscross** [comment]
> @rfcbot poll

The bot doesn't like closed issues, so I've opened this question for us here:

- https://github.com/rust-lang/rust/issues/141401

**Comment by est31** [comment]
@traviscross 

> let's [...] ask for a new v2 stabilization PR to be opened after `has_cfg_version` has landed in nightly and a new stabilization report is ready that includes it.

Sorry for the large diff caused by `has_cfg_version`, most of it is noise from tests as I didn't find a way to reorganize the diagnostics. Already finding a way to make that diagnostic optional took me around an hour (before the "AST for errors" work this would have been less than a minute).

In any case, back to the topic, I don't think we should implement `has_cfg_version` before a `cfg(version(...))` stabilization: because then there would be releases (nightlies) that contain `has_cfg_version` but still give the error for `cfg(version(...))`. People might encounter those during bisection etc.

If we split up the two, we should merge the PRs in opposite order: `cfg(version(...))` first, then `has_cfg_version`.

But I see that order (`has_cfg_version` second) is the vibe of https://github.com/rust-lang/rust/issues/141401#issuecomment-2901908718 as well.

However, I can split the `RUSTC_OVERRIDE_VERSION_STRING` into a separate PR, and re-do a stabilization PR.

**Comment by tmandry** [comment]
> I'd like to flag the process problem of making last-minute changes _as part of stabilization_, in the last day of FCP, within 24 hours of proposing them, and then having that FCP conclude. FCP isn't just for team members, it's meant to be a comment period for the community as well, and the 10-day period ensures that people have time to see it.

Sorry, I'm completely lost here. It feels like you're insinuating some kind of bad faith procedural gamesmanship, except none of the facts you cite line up with my reality.

I agree that everyone in the project and community should have a 10-day comment period. That's why the FCP clock, as I've understood it, always starts over after all concerns are resolved. And we were not in the last day of FCP ever; the first time this PR even began FCP was yesterday.

I think it's fine to push back on combining these decisions, and to ask to make them separately. I was obviously way too optimistic that everyone would just agree to the change. Surfacing that kind of disagreement during the final comment period – which is _always_ 10 days – is the process "working as intended" in my view.

---

What's definitely _not working as intended_ is that we are here, 6 years after the RFC was accepted, privileging design decisions from 2018 when Rust has changed a lot in that time, as has our design experience.

We are discussing the urgency of stabilizing this feature _now_ to enable it in the ecosystem when it could have stabilized in 2021, but the implementation sat blocked for four years. And while the stars align and no lang member sits opposed, any disagreement on the details becomes something that might scuttle our chances to finally ship something.

_That_ is a broken process, and one I severely want to fix.

**Comment by traviscross** [comment]
It's correct this was the first day of the FCP.  We were only in FCP for about 8 minutes today (and were in FCP yesterday for about two hours).

**Comment by joshtriplett** [comment]
> It feels like you're insinuating some kind of bad faith procedural gamesmanship

I was not at *all* suggesting there was any bad faith or any other fault here whatsoever; that was not my intention at all, to the point that I'm genuinely surprised and dismayed to hear that. I was attempting to quickly flag what appeared to be a suboptimal situation of design changes happening at what seemed like the last minute, and thus those design changes inevitably having less review than the original design, leading to potential issues (which, separately, I wrote up in detail).

There was a combination of naming confusion, process confusion, and misunderstanding here. The naming confusion: the term "FCP" regularly (sloppily) gets used to convey both the overall rfcbot process and the actual "final comment period". e.g. we often talk about "starting an FCP", rather than "proposing an FCP" or similar, which conflates the two.

The process confusion: in another meeting, @traviscross mentioned offhand to me that there were some new changes on this feature that I hadn't seen, and made the suggestion to me that he wasn't sure if I had time to see them yet. He also talked about that he was thinking of restarting the FCP. I misinterpreted that as restarting the "FCP" so that the *clock* restarted, rather than restarting the "proposed FCP" because the thing being agreed-to by the checkboxes had changed since some boxes were checked. That then led to me forgetting that the 10-day period does indeed start *after* the last concern is resolved rather than *concurrently* with that, and then responding accordingly based on that misunderstanding.

(10 days is still less design review time for a new design than is ideal, but is significantly less urgent than 24 hours.)

My apologies both for that misinterpretation/confusion and for the resulting unnecessary urgency.

I'm nonetheless genuinely surprised that that misunderstanding would lead to the thought that I would ever assume *bad faith* or *gamesmanship*, rather than flagging what looked like a potential process issue that might need improvement.

**Comment by tmandry** [comment]
Thanks for clarifying Josh. I know this was a misunderstanding, and I think my comment may have come off harsher than intended. To be clear, my frustration is not with you, it's with the failures of our process on display here and the overall difficulty people have of working within it.

**Comment by joshtriplett** [comment]
@tmandry Thank you, I appreciate that clarification. I know this was a misunderstanding as well, and I appreciate that it wasn't intended by either of us. The process conversations are something ongoing that we need to resolve, and I think we're all frustrated with both the process and the process conversations, at both an object-level and meta-level.

**Comment by est31** [comment]
I suppose I'll make a new stabilization PR once the lang team has had the opportunity to discuss #141401 in a meeting, i.e. the `lang-nominated` label gets removed. Hopefully it can be a 1:1 copy of this one, maybe with a section about `cfg_has_version`.
