### PR TITLE
Make conflicting_repr_hints a deny-by-default c-future-compat lint

### LINKED ISSUE #68428: "Conflicting representations" warning became an error
```rust
#[repr(u32)]
#[repr(C)]
enum X {
    A, B, C
}
```

([playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=d0da9540c434927dd1a1c23a2596c709))

This used to be a warning but now is a hard error. This is a breaking change.

This was introduced in https://github.com/rust-lang/rust/commit/2c3e5d3de023c0bfbf4a4c4d3b0d7a9844e96ffe#diff-9e711d5c109e022cbb94049be8c4ca17 , cc @Centril

### PR DESCRIPTION
**Pull request by Centril**
Closes https://github.com/rust-lang/rust/issues/68428.
cc https://github.com/rust-lang/rust/issues/68585.

r? @petrochenkov @pnkfelix

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Re-adding beta-nomination, AFAICT this didn't get into beta.


### error[E0566]: conflicting representation hints
Number of crates regressed: 2
<details>

- [`enum-utils v0.1.2`](https://crater-reports.s3.amazonaws.com/beta-1.42-1/beta-2020-02-05/reg/enum-utils-0.1.2/log.txt)
- [`ovr-mobile-sys v0.4.0`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/reg/ovr-mobile-sys-0.4.0/log.txt)

</details>

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/131828tcompiler/74090weeklymeeting2020022054818.html#188648227) at T-compiler meeting. Approved for beta backport.
