### PR TITLE
update Miri

### LINKED ISSUE #66862: `miri` no longer builds after rust-lang/rust#66547
Hello, this is your friendly neighborhood mergebot.
After merging PR rust-lang/rust#66547, I observed that the tool miri has failing tests.
A follow-up PR to the repository https://github.com/rust-lang/miri is needed to fix the fallout.

cc @leo60228, do you think you would have time to do the follow-up work?
If so, that would be great!

cc @dtolnay, the PR reviewer, and nominating for compiler team prioritization.

### PR DESCRIPTION
**Pull request by RalfJung**
Fixes https://github.com/rust-lang/rust/issues/66862

r? @ghost

### CODE REVIEW

**Comment by RalfJung** [comment]
Submodule-only, fix-toolstate

@bors r+ p=1
Cc @oli-obk

**Comment by RalfJung** [comment]
Conflicting PRs have landed.

@bors r- retry

**Comment by RalfJung** [comment]
Looks like something landed that broke Miri (agian...)
```
2019-12-02T20:57:19.8288172Z error[E0308]: try expression alternatives have incompatible types
2019-12-02T20:57:19.8289330Z --> src/tools/miri/src/shims/mod.rs:52:17
2019-12-02T20:57:19.8289702Z |
2019-12-02T20:57:19.8290135Z 52 | Ok(Some(this.load_mir(instance.def, None)?))
2019-12-02T20:57:19.8290620Z | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&rustc::mir::Body<'_>`, found struct `rustc::mir::ReadOnlyBodyCache`
2019-12-02T20:57:19.8290800Z
2019-12-02T20:57:19.9292737Z error[E0308]: try expression alternatives have incompatible types
2019-12-02T20:57:19.9293073Z --> src/tools/miri/src/shims/foreign_items.rs:144:32
2019-12-02T20:57:19.9293295Z |
2019-12-02T20:57:19.9293549Z 144 | return Ok(Some(this.load_mir(start_panic_instance.def, None)?));
2019-12-02T20:57:19.9295202Z | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&rustc::mir::Body<'_>`, found struct `rustc::mir::ReadOnlyBodyCache`
2019-12-02T20:57:19.9295256Z
2019-12-02T20:57:19.9370379Z error[E0308]: try expression alternatives have incompatible types
2019-12-02T20:57:19.9370643Z --> src/tools/miri/src/shims/foreign_items.rs:151:32
2019-12-02T20:57:19.9370844Z |
2019-12-02T20:57:19.9371125Z 151 | return Ok(Some(this.load_mir(panic_impl_instance.def, None)?));
2019-12-02T20:57:19.9371471Z | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&rustc::mir::Body<'_>`, found struct `rustc::mir::ReadOnlyBodyCache`
2019-12-02T20:57:19.9371528Z
2019-12-02T20:57:21.0463739Z error[E0308]: mismatched types
2019-12-02T20:57:21.0464067Z --> src/tools/miri/src/helpers.rs:142:13
2019-12-02T20:57:21.0464484Z |
2019-12-02T20:57:21.0464717Z 142 | mir,
2019-12-02T20:57:21.0464943Z | ^^^
2019-12-02T20:57:21.0465179Z | |
2019-12-02T20:57:21.0465513Z | expected `&rustc::mir::Body<'_>`, found struct `rustc::mir::ReadOnlyBodyCache`
2019-12-02T20:57:21.0465772Z | help: consider borrowing here: `&mir`
```
@bors r- retry

**Comment by RalfJung** [comment]
@pietroalbini  bors seems very confused with its tags? This is the second time recently that I did @bors r- and the tag remains "S-waiting-on-bors". GH also seems confused

> added S-waiting-on-author S-waiting-on-bors and removed S-waiting-on-bors S-waiting-on-author 

Not sure how it could even remove a tag that wasn't there... or add one that already was there...

**Comment by RalfJung** [comment]
Hm, doing it a second time seems to work? Or a fix landed in the mean time.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/66148 changed a Miri test output.

@bors r- retry
