### ISSUE TITLE
Wrapping type in Result<> requires it to be Sized

### ISSUE THREAD

**Issue by MichaelBurge** [rust-lang/rust#71371]
In the following code, `foo` is accepted but `bar` is rejected:
```rust
pub trait Foo {
    // Accepted
    fn foo() -> Self;
    // error[E0277]: the size for values of type `Self` cannot be known at compilation time
    fn bar() -> std::result::Result<Self, ()>;
}
```
I would expect either both `foo` and `bar` to be rejected, or both to be accepted. Wrapping a type in `Result` shouldn't change whether it must be `Sized`.

### Meta
Tested on Stable and Nightly on the [Rust Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=906be1d3a7454bad484b4d91e5b99b83)
```
Build using the Nightly version: 1.44.0-nightly
(2020-04-20 20fc02f836f3035b86b5)
```

**Comment by stephaneyfx** [comment]
I think this is due to the definition of `Result` which is `enum Result<T, E> { ... }`. Generic type parameters have an implicit `Sized` bound, so there is an implicit `T: Sized` for `Result`.

See how this compiles if we opt out with `T: ?Sized`: [[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=92e36330fc24468472f17b62b41b56b3)]

```rust
trait Foo {
    fn foo() -> Bar<Self>;
}

struct Bar<T: ?Sized>(T);
```

**Comment by MichaelBurge** [comment]
Since it's not possible to add a `?Sized` constraint to `Result` due to methods like `unwrap`, it seems like this is expected and there's nothing to be changed here. I'll close this.

**Comment by rodrimati1992** [comment]
What about `foo` though, why would the compiler allow returning an unsized Self in the trait definition?
