### PR TITLE
Create fresh lifetime parameters for bare fn trait too

### LINKED ISSUE #98616: Nightly regression: ndarray 0.9.1 stops compiling: temporary value dropped while borrowed
ndarray 0.9.1 compiles with rustc 1.61.0 but not with rustc 1.64.0-nightly (2f3ddd9f5 2022-06-27).

### Code

Put this into a `Cargo.toml` of a new project:

```toml
[package]
name = "test-ndarray"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.9.1"
```

rustc stable <= 1.61.0 compiles the crate fine, rustc nightly gives the following error:
```
error[E0716]: temporary value dropped while borrowed
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.9.1/src/layout/layoutfmt.rs:29:24
   |
25 |                        .format_with(" | ", |i, f| {
   |                                                - has type `&mut dyn FnMut(&'1 (dyn std::fmt::Display + '1)) -> Result<(), std::fmt::Error>`
...
29 |                     f(&format_args!("0x{:x}", i))
   |                     ---^^^^^^^^^^^^^^^^^^^^^^^^^-
   |                     |  |
   |                     |  creates a temporary which is freed while still in use
   |                     argument requires that borrow lasts for `'1`
30 |                 }
   |                 - temporary value is freed at the end of this statement
   |
   = note: this error originates in the macro `format_args` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0597]: `i` does not live long enough
  --> .cargo/registry/src/github.com-1ecc6299db9ec823/ndarray-0.9.1/src/layout/layoutfmt.rs:29:47
   |
25 |                        .format_with(" | ", |i, f| {
   |                                                - has type `&mut dyn FnMut(&'1 (dyn std::fmt::Display + '1)) -> Result<(), std::fmt::Error>`
...
29 |                     f(&format_args!("0x{:x}", i))
   |                     --------------------------^--
   |                     |                         |
   |                     |                         borrowed value does not live long enough
   |                     argument requires that `i` is borrowed for `'1`
30 |                 }
31 |             }))
   |             - `i` dropped here while still borrowed
   |
   = note: this error originates in the macro `format_args` (in Nightly builds, run with -Z macro-backtrace for more info)

Some errors have detailed explanations: E0597, E0716.
For more information about an error, try `rustc --explain E0597`.
error: could not compile `ndarray` due to 2 previous errors
```

### Version it worked on

```
$ rustc --version --verbose
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-unknown-linux-gnu
release: 1.61.0
LLVM version: 14.0.0
```

### Version with regression

```
$ rustc +nightly --version --verbose
rustc 1.64.0-nightly (2f3ddd9f5 2022-06-27)
binary: rustc
commit-hash: 2f3ddd9f594adf9773547aa7cedb43c4ac8ffd2f
commit-date: 2022-06-27
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

### LINKED ISSUE #98726: Missing dyn keyword in bare_trait_objects with Rust 2015 edition produces faulty error instead of warnings
### Code
I tried this code with `edition = "2015"`:
```rust
fn a<F>(_f: F) where F: FnMut(&i32) {}

fn b<F>(_f: F) where F: FnMut(&mut FnMut(&i32)) {}

fn main()
{
    b(|f| {
        a(|v| f(v))
    });
}
```
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=40892217ad5a83b67570be18e19a43c4

I expected to see only warning without error, like this:
```
warning: trait objects without an explicit `dyn` are deprecated
 --> src/main.rs:3:36
  |
3 | fn b<F>(_f: F) where F: FnMut(&mut FnMut(&i32)) {}
  |                                    ^^^^^^^^^^^
  |
  = note: `#[warn(bare_trait_objects)]` on by default
  = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2021!
  = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>
help: use `dyn`
  |
3 - fn b<F>(_f: F) where F: FnMut(&mut FnMut(&i32)) {}
3 + fn b<F>(_f: F) where F: FnMut(&mut dyn FnMut(&i32)) {}
  | 

warning: `playground` (bin "playground") generated 1 warning
```
Instead, this happened (extra error E0521 emitted, which is incorrect):
```
warning: trait objects without an explicit `dyn` are deprecated
 --> src/main.rs:3:36
  |
3 | fn b<F>(_f: F) where F: FnMut(&mut FnMut(&i32)) {}
  |                                    ^^^^^^^^^^^
  |
  = note: `#[warn(bare_trait_objects)]` on by default
  = warning: this is accepted in the current edition (Rust 2015) but is a hard error in Rust 2021!
  = note: for more information, see <https://doc.rust-lang.org/nightly/edition-guide/rust-2021/warnings-promoted-to-error.html>
help: use `dyn`
  |
3 - fn b<F>(_f: F) where F: FnMut(&mut FnMut(&i32)) {}
3 + fn b<F>(_f: F) where F: FnMut(&mut dyn FnMut(&i32)) {}
  |

error[[E0521]](https://doc.rust-lang.org/nightly/error-index.html#E0521): borrowed data escapes outside of closure
 --> src/main.rs:8:15
  |
7 |     b(|f| {
  |        - `f` declared here, outside of the closure body
8 |         a(|v| f(v))
  |            -  ^^^^ `v` escapes the closure body here
  |            |
  |            `v` is a reference that is only valid in the closure body

For more information about this error, try `rustc --explain E0521`.
warning: `playground` (bin "playground") generated 1 warning
error: could not compile `playground` due to previous error; 1 warning emitted
```
If I add `dyn` in line 3, it compiles without any error or warning:
```
fn b<F>(_f: F) where F: FnMut(&mut dyn FnMut(&i32)) {}
```
So the E0521 error emitted by the compiler is incorrect. The test code using `Rust=2015` should only produce warnings without an error.

### Version it worked on
It most recently worked on: 1.63.0-nightly (a4c1cd0eb 2022-05-18)

### Version with regression
```
rustc 1.64.0-nightly (830880640 2022-06-28)
binary: rustc
commit-hash: 830880640304ba8699c5f9a0c4665c38a3271963
commit-date: 2022-06-28
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

</p>
</details>

### PR DESCRIPTION
**Pull request by cjgillot**
The current code fails to account for the equivalence between `dyn FnMut(&mut u8)` and bare `FnMut(&mut u8)`, and treated them differently.

This PR introduces a special case for `Fn` traits, which are always fully resolved.

Fixes #98616 
Fixes #98726
This will require a beta-backport, as beta contains that bug.

r? @petrochenkov

### CODE REVIEW

**Comment by apiraino** [comment]
Beta backport approved as per compiler team [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.5D.202022-07-07/near/288812277)

@rustbot label +beta-accepted
