### ISSUE TITLE
Trait not imported with super::*;

### ISSUE THREAD

**Issue by octavonce** [rust-lang/rust#112831]
With the latest nightly, the bytemuck crate fails to compile. This was compiling yesterday and the issue seems to be traits are not imported with super::*. Please see the issue in the bytemuck repository: https://github.com/Lokathor/bytemuck/issues/197

### Meta

`rustc --version --verbose`:
```
rustc 1.72.0-nightly (fe7454bf4 2023-06-19)
binary: rustc
commit-hash: fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2
commit-date: 2023-06-19
host: x86_64-apple-darwin
release: 1.72.0-nightly
LLVM version: 16.0.5
```

### Error output

```
error[E0404]: expected trait, found derive macro `NoUninit`
  --> /Users/octavonce/Projects/purple_coin/vendor/crates/bytemuck-1.13.1/src/allocation.rs:25:20
   |
25 | pub fn cast_box<A: NoUninit, B: AnyBitPattern>(input: Box<A>) -> Box<B> {
   |                    ^^^^^^^^ not a trait
   |
help: consider importing this trait instead
   |
12 + use crate::NoUninit;
```

</p>
</details>

**Comment by Nilstrieb** [comment]
Regression in https://github.com/rust-lang-ci/rust/commit/bede4c277fbf4c050b2fbd9d9e22f0e4eba8c268
searched nightlies: from nightly-2023-06-10 to nightly-2023-06-20
regressed nightly: nightly-2023-06-20
searched commit range: https://github.com/rust-lang/rust/compare/2d0aa57684e10f7b3d3fe740ee18d431181583ad...fe7454bf439c93cbe9ac8a8f7fcfacd5a40244c2
regressed commit: https://github.com/rust-lang/rust/commit/f217411bacbe943ead9dfca93a91dff0753c2a96

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.6</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 2023-06-10 --access github
```
</details>

https://github.com/rust-lang/rust/pull/112758

cc @bvanjoi @petrochenkov

**Comment by bvanjoi** [comment]
It may not caused by https://github.com/rust-lang/rust/pull/112758, I had checkout to a ealry commit(6fc50dacd4a), and it still throw an Error...

![image](https://github.com/rust-lang/rust/assets/30187863/afe95bdf-1580-4c59-8984-ed5221bc5701)

![image](https://github.com/rust-lang/rust/assets/30187863/28e284d5-dc30-4320-90ad-cf8c4faf56e8)

**Comment by Nilstrieb** [comment]
hm, maybe your change simply exposed an existing bug in more cases

**Comment by bvanjoi** [comment]
I will check it later @rustbot claim

**Comment by Nilstrieb** [comment]
ah no, I made a stupid mistake, i should have used `pub use` :D, my example only got `Debug` from the prelude which only contains the macro.

**Comment by workingjubilee** [comment]
This is resolved, of course. Only tagging this with Nilstrieb's estimated priority for historical analysis later.

**Comment by Pr0methean** [comment]
Now that this fix is merged, what time tonight should we expect a new nightly release?

**Comment by workingjubilee** [comment]
0:00 according to a server somewhere. In practice, usually UTC 0:00. So it should be being cut sometime soon. Or 24 hours from now. Either one.
