### PR TITLE
Forward the ABI of the non-zero sized fields of an union if they have the same ABI

### PR DESCRIPTION
**Pull request by ogoffart**
This is supposed to fix the performence regression of using MaybeUninit in
https://github.com/rust-lang/rust/pull/54668

### CODE REVIEW

File: src/librustc/ty/layout.rs [hunk 1]
```diff
@@ -706,13 +707,35 @@ impl<'a, 'tcx> LayoutCx<'tcx, TyCtxt<'a, 'tcx, 'tcx>> {
                         } else {
                             align = align.max(field.align);
                         }
+
+                        if field.abi != Abi::Uninhabited {
+                            if abi == Abi::Uninhabited || size == Size::ZERO {
+                                abi = field.abi.clone();
+                            } else if field.size != Size::ZERO && abi != field.abi  {
+                                abi = Abi::Aggregate{ sized: true };
```
Comment (eddyb) [inline src/librustc/ty/layout.rs]: Missing space before `{`.

File: src/librustc/ty/layout.rs [hunk 2]
```diff
@@ -706,13 +707,35 @@ impl<'a, 'tcx> LayoutCx<'tcx, TyCtxt<'a, 'tcx, 'tcx>> {
...
+                            }
+                        }
+
                         size = cmp::max(size, field.size);
                     }
 
+                    // Use scalar_unit to reset the valid range to the maximal one
+                    // since an union might not be initialised
```
Comment (eddyb) [inline src/librustc/ty/layout.rs]: Need to do this before comparing `field.abi` above with `abi`, so we never compare ranges.

**Comment by eddyb** [comment]
cc @rkruppe @nagisa @RalfJung

File: src/librustc/ty/layout.rs [hunk 3]
```diff
@@ -697,6 +697,7 @@ impl<'a, 'tcx> LayoutCx<'tcx, TyCtxt<'a, 'tcx, 'tcx>> {
                     }
 
                     let mut size = Size::ZERO;
+                    let mut abi = Abi::Uninhabited;
```
Comment (RalfJung) [inline src/librustc/ty/layout.rs]: What is the meaining of this initial value?

Notice that a union should NOT be uninhabited even if all of its fields are! That would also be a form of "propagating ranges".

File: src/librustc/ty/layout.rs [hunk 4]
```diff
@@ -706,13 +707,34 @@ impl<'a, 'tcx> LayoutCx<'tcx, TyCtxt<'a, 'tcx, 'tcx>> {
...
+                                Abi::ScalarPair(x, y) => {
+                                    Abi::ScalarPair(
+                                        scalar_unit(x.value),
+                                        scalar_unit(y.value),
+                                    )
+                                }
+                                _ => field.abi.clone(),
+                            };
+
+                            if abi == Abi::Uninhabited || size == Size::ZERO {
```
Comment (RalfJung) [inline src/librustc/ty/layout.rs]: Why is this checking for the size of the entire thing?

File: src/librustc/ty/layout.rs [hunk 5]
```diff
@@ -706,13 +707,34 @@ impl<'a, 'tcx> LayoutCx<'tcx, TyCtxt<'a, 'tcx, 'tcx>> {
...
+                            // Normalize scalar_unit to the maximal valid range
+                            let field_abi = match &field.abi {
+                                Abi::Scalar(x) => Abi::Scalar(scalar_unit(x.value)),
+                                Abi::ScalarPair(x, y) => {
+                                    Abi::ScalarPair(
+                                        scalar_unit(x.value),
+                                        scalar_unit(y.value),
+                                    )
+                                }
+                                _ => field.abi.clone(),
```
Comment (RalfJung) [inline src/librustc/ty/layout.rs]: After this normalization, the ABI is sure to permit all bit patterns, right? There are no restrictions about what can be stored e.g. in a vector ABI type?

File: src/librustc/ty/layout.rs (hunk 4 above)
Comment (RalfJung) [reply src/librustc/ty/layout.rs]: Ah, size seems to be the size of the largest field so far. That's worth a comment.
I also do not understand why we need two conditions here, shouldn't this simply be "if we have not set an abi yet"? So, shouldn't the `Uninhabited` test be enough?

Generally, all this new code needs a comment explaining its purpose.

File: src/librustc/ty/layout.rs (hunk 3 above)
Comment (RalfJung) [reply src/librustc/ty/layout.rs]: Ah, you are using it as a sentinel value for "nothing found yet". This warrants a comment. However, we should also *never* use the `Uninhabited` layout on unions. So maybe better use an `Option` here, initialized to `None`?

File: src/librustc/ty/layout.rs [hunk 6]
```diff
@@ -706,13 +707,34 @@ impl<'a, 'tcx> LayoutCx<'tcx, TyCtxt<'a, 'tcx, 'tcx>> {
...
+                            };
+
+                            if abi == Abi::Uninhabited || size == Size::ZERO {
+                                abi = field_abi;
+                            } else if field.size != Size::ZERO && abi != field_abi  {
```
Comment (RalfJung) [inline src/librustc/ty/layout.rs]: `!field.is_zst()` is a better test because it takes DST into account. I know we don't allow these in unions, but still, no reason not to use that.

**Comment by ogoffart** [comment]
@RalfJung thanks for your review. I fixed the uninhabited case, and added some comments.

File: src/librustc/ty/layout.rs [hunk 7]
```diff
@@ -706,13 +707,44 @@ impl<'a, 'tcx> LayoutCx<'tcx, TyCtxt<'a, 'tcx, 'tcx>> {
...
+                                        element: scalar_unit(x.value),
+                                        count: *count,
+                                    }
+                                }
+                                Abi::Uninhabited |
+                                Abi::Aggregate { .. }  => Abi::Aggregate { sized: true },
+                            };
+
+                            if size == Size::ZERO {
+                                // first non nzt: initialize 'abi'
```
Comment (RalfJung) [inline src/librustc/ty/layout.rs]:
```suggestion
                                // first non ZST: initialize 'abi'
```

File: src/librustc/ty/layout.rs [hunk 8]
```diff
@@ -706,13 +707,44 @@ impl<'a, 'tcx> LayoutCx<'tcx, TyCtxt<'a, 'tcx, 'tcx>> {
...
+                                abi = field_abi;
+                            } else if abi != field_abi  {
+                                // different field have different ABI: reset to Aggregate
```
Comment (RalfJung) [inline src/librustc/ty/layout.rs]:
```suggestion
                                // different fields have different ABI: reset to Aggregate
```

**Comment by RalfJung** [comment]
Looks good to me now, but I also have hardly any knowledge about layout computation.

File: src/librustc/ty/layout.rs (hunk 4 above)
Comment (ogoffart) [reply src/librustc/ty/layout.rs]: >  I think we can remove the Uninhabited test, since no fields means size is 0 anyway.

Is  `(u32,  UninhabitedEnum)`  Uninhabited?   What's its size?

**Review by eddyb — APPROVED** [review]

File: src/librustc/ty/layout.rs (hunk 4 above)
Comment (RalfJung) [reply src/librustc/ty/layout.rs]: It is uninhabited at has size 4. Also see https://github.com/rust-lang/rust/issues/49298.

**Review by RalfJung — APPROVED** [review]
Fine for me, though I think using `Option` would be clearer.

File: src/test/codegen/union-abi.rs [hunk 9]
```diff
@@ -0,0 +1,69 @@
...
+
+pub union UnionI64x4_{ a: i64x4, b: (), c:i64x4, d: Unhab, e: ((),()), f: UnionI64x4 }
+
+// CHECK: define <4 x i64> @test_UnionI64x4_(<4 x i64> %arg0)
+#[no_mangle]
+pub extern fn test_UnionI64x4_(_: UnionI64x4_) -> UnionI64x4_ { loop {} }
+
+pub union UnionI64x4I64{ a: i64x4, b: i64 }
+
+// CHECK: define void @test_UnionI64x4I64(%UnionI64x4I64* {{.*}}, %UnionI64x4I64* {{.*}} %arg0)
```
[the remark this answers is not in the document]
Comment (eddyb) [reply src/test/codegen/union-abi.rs]: Ironically, the Rust default "ABI" (i.e. `fn` instead of `extern fn`) would be more consistent, in that we always pass the inner scalars for `Scalar` / `ScalarPair`.

[the remark this answers is not in the document]
Comment (ogoffart) [reply src/test/codegen/union-abi.rs]: Right, I only tested on x86_64, because that's the only arch i have. (and the test is based of the repr-transparent.rs test.)  I  guess this check and the next one are architecture specific.  What should i do?  Just remove them?  Or move them somewhere else?

[the remark this answers is not in the document]
Comment (ogoffart) [reply src/test/codegen/union-abi.rs]: I used the rust ABI and removed the return value for these tests.

[the remark this answers is not in the document]
Comment (rkruppe) [reply src/test/codegen/union-abi.rs]: What the repr(transparent) tests do is separate tests for each variation of how the C ABI encodes aggregates in LLVM signatures. But that's because for repr(transparent) it's important that it matches the C ABI. This PR, by contrast, is mostly about the Rust ABI and mostly about unions that *shouldn't* be passed as aggregates. So I don't think it needs as comprehensive coverage of extern "C" as the repr(transparent) tests, as long as we have tests somewhere that ensure that repr(C) unions are passed correctly in extern "C" calls. As long as that is true (@eddyb do you know?) I think it doesn't matter very much.

**Comment by eddyb** [comment]
Hang on, are we checking whether the `repr` is `C` or not?
I don't think we can do this optimization for `repr(C)` unions.

**Comment by ogoffart** [comment]
I just disabled the optimisation for repr(C) union. (but i don't know how i can test them: simd are not repr(c), what else would make a difference?)

**Comment by eddyb** [comment]
An `union` with a large scalar (e.g. `u128`) should be passed as an `u32` in the Rust ABI, but if you add `#[repr(C)]` to it, it should be passed by indirection.

**Comment by eddyb** [comment]
@RalfJung There's a method about "are optimizations allowed" on `AdtDef` that we could check.

**Comment by ogoffart** [comment]
I found `ReprOptions::inhibit_enum_layout_opt` and `ReprOptions::inhibit_struct_field_reordering_opt` . I could use inhibit_enum_layout_opt, since the second condition does not matter for unions, but that's not really a good name.  Or I could add in impl ReprOptions

```rust
    pub fn inhibit_union_opt(&self) -> bool {
        self.c()
    }
```
if we want to have all the inhibit options at the same place.  Should I do that?

**Comment by eddyb** [comment]
@ogoffart I think that's good. Kind of surprised there's not a more general method in there.

All struct-related optimizations (including the newtype ABI ones!) appear to use:
```rust
let mut optimize = !repr.inhibit_struct_field_reordering_opt();
```

Maybe the name should be `inhibit_field_abi_opt`?

**Comment by ogoffart** [comment]
> Please resolve the merge conflicts

Should I rebase, or merge?

**Comment by nagisa** [comment]
Rebase.

**Comment by ogoffart** [comment]
The change was rebased.
What is left to do?

**Review by eddyb — APPROVED** [review]

**Comment by kennytm** [comment]
@bors r-

The test failed in https://github.com/rust-lang/rust/pull/55943#issuecomment-438717309 on 32-bit MSVC (full log: https://ci.appveyor.com/project/rust-lang/rust/builds/20297438/job/u664hm25e8ec6kt2)

```
------------------------------------------
C:\projects\rust\src/test\codegen\union-abi.rs:66:11: error: CHECK: expected string not found in input
// CHECK: define i32 @test_UnionF32U32(i32)
          ^
C:\projects\rust\build\i686-pc-windows-msvc\test\codegen\union-abi\union-abi.ll:57:45: note: scanning from here
define float @test_UnionF32F32(float %arg0) unnamed_addr #0 {
                                            ^
C:\projects\rust\build\i686-pc-windows-msvc\test\codegen\union-abi\union-abi.ll:66:1: note: possible intended match here
define i32 @test_UnionF32U32(%UnionF32U32* byval noalias nocapture dereferenceable(4) %arg0) unnamed_addr #0 {
^
------------------------------------------
```

**Comment by ogoffart** [comment]
I removed the `extern` from the test, and the return value, in an attempt to get the test passing everywhere.
However, I did not try on all architectures.

**Comment by ogoffart** [comment]
@eddyb What should be done now? should there be a test run by bors?
