### PR TITLE
On stable, suggest removing `#![feature]` for features that have been stabilized

### LINKED ISSUE #83715: On stable channels, suggest removing `#![feature]`s that have already been stabilized
I was under the impression that `min_const_generics` should work on stable channel with version 1.51, however using the example code from https://github.com/rust-lang/rust/pull/79135 I get
```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src\main.rs:5:1
  |
5 | #![feature(min_const_generics)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
```

rustc -Vv output (its the [mingw package](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-rust)):
```
rustc 1.51.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-pc-windows-gnu
release: 1.51.0
LLVM version: 11.0.0
```
```

### PR DESCRIPTION
**Pull request by jyn514**
I don't know how to test this (https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Run.20tests.20without.20enabling.20nightly.20features.3F). I confirmed locally that this gives the
appropriate help with `channel = "beta"`:

```
error[E0554]: `#![feature]` may not be used on the beta release channel
 --> src/lib.rs:2:1
  |
2 | #![feature(min_const_generics)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: remove the attribute
  |
  = help: the feature `min_const_generics` has been stable since 1.51.0 and no longer requires an attribute to enable

error[E0554]: `#![feature]` may not be used on the beta release channel
 --> src/lib.rs:3:1
  |
3 | #![feature(min_const_generics, min_specialization)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: the feature `min_const_generics` has been stable since 1.51.0 and no longer requires an attribute to enable

error[E0554]: `#![feature]` may not be used on the beta release channel
 --> src/lib.rs:4:1
  |
4 | #![feature(box_patterns)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
```

Closes https://github.com/rust-lang/rust/issues/83715.

### CODE REVIEW

**Comment by GuillaumeGomez** [comment]
I think it shouldn't make this check only on stable. If you are using a feature in nightly which is now stable, I think it's definitely worth it to show a warning there as well (and this case is simpler to test too :wink: ).

**Comment by jyn514** [comment]
@GuillaumeGomez it already warns on nightly. It's a lint and feature gates are rejected during parsing, which is why it doesn't already show up. That's the main reason I wanted to add a test, because I think whoever added the lint originally expected it to work on all channels.

**Comment by GuillaumeGomez** [comment]
Oh I see, my bad, I misunderstood the context from your comment.

**Comment by joshtriplett** [comment]
@jyn514 This seems like a great idea.

Would it be possible to also provide a rustfix suggestion that deletes the line?

**Comment by jyn514** [comment]
> Would it be possible to also provide a rustfix suggestion that deletes the line?

Hmm, I could only do that if all features in the attribute are stable (consider `#![feature(min_const_generics, min_specialization)]`). But other than that it seems doable.

**Comment by jyn514** [comment]
> Would it be possible to also provide a rustfix suggestion that deletes the line?

Done.

**Comment by joshtriplett** [comment]
@jyn514 In theory, if you get `#![feature(stable_feature, unstable_feature)]`, it'd be possible to give a rustfix suggestion to delete just `stable_feature, `, but since the resulting code still won't compile on stable, I don't know if that's worth the extra effort.

This LGTM, and thanks for implementing the rustfix!

**Comment by jyn514** [comment]
@estebank will you have time to look at this sometime soon?

**Comment by jyn514** [comment]
:confused: lots of failures without logs - this doesn't affect the nightly channel at all so it shouldn't be possible for tests to fail unless it doesn't compile at all.

@bors retry
