### PR TITLE
Fix star handling in block doc comments

### LINKED ISSUE #92872: regression: rustdoc interprets the `*` in `/** */` doc comments as literal Markdown
### Code

I tried this code:

```rust
/**
 *     a
 */
pub fn foo() {}
```
When I run `cargo test`, I get
```
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s


running 1 test
test src/lib.rs - foo (line 1) ... FAILED

failures:

---- src/lib.rs - foo (line 1) stdout ----
error[E0425]: cannot find value `a` in this scope
 --> src/lib.rs:2:1
  |
3 | a
  | ^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
Couldn't compile the test.

failures:
    src/lib.rs - foo (line 1)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.41s
```
Oddly it doesn't fail with `/**` replaced by `///`.

This worked on `rust version 1.60.0-nightly (092e1c9d2 2022-01-09)` but failed on `rust version 1.60.0-nightly (1409c015b 2022-01-11)`

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Fixes #92872.

Some extra explanation about this PR and why https://github.com/rust-lang/rust/pull/92357 created this regression: when we merge doc comment kinds for example in:

```rust
/// he
/**
* hello
*/
#[doc = "boom"]
```

We don't want to remove the empty lines between them. However, to correctly compute the "horizontal trim", we still need it, so instead, I put back a part of the "vertical trim" directly in the "horizontal trim" computation so it doesn't impact the output buffer but allows us to correctly handle the stars.

r? @camelid

### CODE REVIEW

File: src/test/rustdoc/strip-block-doc-comments-stars.rs [hunk 1]
```diff
@@ -0,0 +1,11 @@
+#![crate_name = "foo"]
+
+// The goal of this test is to answer that it won't be generated as a list because
+// block doc comments can have their lines starting with a star.
+
+// @has foo/fn.foo.html
+// @snapshot docblock - '//*[@class="rustdoc-toggle top-doc"]//*[@class="docblock"]'
+/**
+ *     a
```
Comment (camelid) [inline src/test/rustdoc/strip-block-doc-comments-stars.rs:9]: I think this is actually supposed to be interpreted as a code block though?

**Comment by camelid** [comment]
Sorry, I don't think I'll have time to review this. I already have a lot of PRs to review.

r? @notriddle

File: src/test/rustdoc/strip-block-doc-comments-stars.rs (hunk 1 above)
Comment (GuillaumeGomez) [reply src/test/rustdoc/strip-block-doc-comments-stars.rs:9]: Based on the previous behaviour, it's not apparently (I was surprised too).

Comment (camelid) [reply src/test/rustdoc/strip-block-doc-comments-stars.rs:9]: Oh right... I got mixed up. It was incorrectly treated as a code block because the `*` was interpreted as Markdown text. So it's correct to not treat it as a code block.

File: compiler/rustc_ast/src/util/comments.rs [hunk 2]
```diff
@@ -42,10 +43,27 @@ pub fn beautify_doc_string(data: Symbol) -> Symbol {
         if i != 0 || j != lines.len() { Some((i, j)) } else { None }
     }
 
-    fn get_horizontal_trim(lines: &[&str]) -> Option<usize> {
+    fn get_horizontal_trim(lines: &[&str], kind: CommentKind) -> Option<usize> {
         let mut i = usize::MAX;
         let mut first = true;
 
+        // In case we have doc comments like `/**` or `/*!`, we want to remove stars if they are
```
Comment (notriddle) [inline compiler/rustc_ast/src/util/comments.rs:50]: This isn't really removing stars, though. It's removing blank lines.

The for loop below this conditional removes stars, as well as spaces and tabs.

What you really do here is removing blank lines, so that the code below will actually remove the stars.

File: compiler/rustc_ast/src/util/comments.rs [hunk 3]
```diff
@@ -42,10 +43,27 @@ pub fn beautify_doc_string(data: Symbol) -> Symbol {
...
+            let mut i = 0;
+            let mut j = lines.len();
+
+            while i < j && lines[i].trim().is_empty() {
+                i += 1;
+            }
+            while j > i && lines[j - 1].trim().is_empty() {
+                j -= 1;
+            }
+            if i != 0 || j != lines.len() { &lines[i..j] } else { lines }
```
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply compiler/rustc_ast/src/util/comments.rs:62]: This is a very good point!

File: compiler/rustc_ast/src/util/comments.rs (hunk 2 above)
Comment (GuillaumeGomez) [reply compiler/rustc_ast/src/util/comments.rs:50]: I badly worded it. Good catch!

Comment (GuillaumeGomez) [reply compiler/rustc_ast/src/util/comments.rs:50]: I extended the comment a bit.

File: compiler/rustc_ast/src/util/comments.rs (hunk 3 above)
[the remark this answers is not in the document]
Comment (GuillaumeGomez) [reply compiler/rustc_ast/src/util/comments.rs]: Done!

**Review by notriddle — APPROVED** [review]
@bors r+

**Comment by camelid** [comment]
@notriddle you need to write the r+ in a regular comment for bors to notice it.

**Comment by notriddle** [comment]
@bors r+

Thanks…

**Comment by GuillaumeGomez** [comment]
I'll put it in the rollup. :)

@bors: p=rollup
