### ISSUE TITLE
doctest errors are no longer colored

### ISSUE THREAD

**Issue by ShE3py** [rust-lang/rust#148749]
```rs
/// ```
/// foo
/// ``` 
fn foo() {}
```
```
$ rustdoc --test lib.rs
---- lib.rs - foo (line 1) stdout ----
error[E0425]: cannot find value `foo` in this scope
 --> lib.rs:2:1
  |
3 | foo
  | ^^^ not found in this scope

error: aborting due to 1 previous error
```
On the `+beta` and `+nightly` channels, the stdout is no longer colored. Using `--color=always` fixes the issue.

Regressed in #147207 cc @Muscraft 

---
@rustbot label +A-doctests +T-rustdoc +regression-from-stable-to-beta

**Comment by fmease** [comment]
Waiting for backport.
