### PR TITLE
Use libtest from crates.io for compiletest

### LINKED ISSUE #58890: compiletest fails to build using local-rebuild=true + rustc 1.34.0-nightly (0ea22717a 2019-03-02)
```
error[E0063]: missing field `exclude_should_panic` in initializer of `test::TestOpts`
   --> src/tools/compiletest/src/main.rs:504:5
    |
504 |     test::TestOpts {
    |     ^^^^^^^^^^^^^^ missing `exclude_should_panic`

error: aborting due to previous error
```

### PR DESCRIPTION
**Pull request by bjorn3**
This fixes using latest nightly + local-rebuild=true for testing

Fixes #58890 and #59264

### CODE REVIEW

**Comment by alexcrichton** [comment]
@bors: r+

cc @gnzlbg

**Comment by gnzlbg** [comment]
LGTM. @alexcrichton would it be possible to give this higher priority ?

**Comment by Mark-Simulacrum** [comment]
@bors r-

Can we remove the `#![feature(test)]` from compiletest, too?

**Comment by bjorn3** [comment]
Done

**Comment by gnzlbg** [comment]
> Can we remove the #![feature(test)] from compiletest, too?

@bjorn3 have you checked that removing the `#[feature(test)]` still lets you to use `libtest` as a dependency ? libtest 0.0.1 on crates.io requires the `test` feature to be enabled.

**Comment by bjorn3** [comment]
Oops didn't test. Force pushed that commit away.

**Comment by bjorn3** [comment]
```
   Compiling rustc_term v0.0.1
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead? (see issue #27812)
 --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc_term-0.0.1\win.rs:5:1
  |
5 | extern crate libc;
  | ^^^^^^^^^^^^^^^^^^
  |
  = help: add #![feature(rustc_private)] to the crate attributes to enable
```

**Comment by Centril** [comment]
^--- @bors r-

**Comment by gnzlbg** [comment]
This should probably wait till #59440 is merged, and then jump directly to using 0.0.2 .

**Comment by gnzlbg** [comment]
I thought about addressing this as part of #59440 , but I think it would be better to just remove compiletest-rs from the tools after that is merged, and use a stable Rust version from crates.io which uses the stable libtest 0.0.2 .

**Comment by Dylan-DPC** [comment]
ping from triage @alexcrichton waiting for your review on the latest change.

**Comment by alexcrichton** [comment]
I'm going to switch this to...

r? @Manishearth 

... who I believe knows more about what's going on around libtest and whatnot

**Comment by Manishearth** [comment]
This looks good to me, but I'd like to hold off on landing this before the clippy fixes land.

**Comment by Xanewok** [comment]
@Manishearth the clippy fix has landed and submodules are updated now

**Comment by Manishearth** [comment]
Okay, we should make sure that this works in rustc CI first (by using a git dep and `try`)

**Comment by Manishearth** [comment]
Oh wait, this is for the internal compiletest. My bad.

**Comment by bjorn3** [comment]
Rebased

**Comment by bjorn3** [comment]
On windows `libtest` seems to use `rustc_term` which doesn't depend on `libc` but uses it on windows. I unfortunately couldn't find its repo, so I had to look in the cargo cache for it. (https://github.com/rust-lang/libtest is linked as repo but that doesn't contain its source)

**Comment by gnzlbg** [comment]
We should probably close this PR, since the change that motivated it was reverted. 

What we'd probably want to do, is update compiletest-rs to contain the latest upstream changes, remove `compiletest` from rust-lang Rust, and make it use the one from crates.io . Then it will be one thing less we'd have to update when we try to split libtest again.

**Comment by bjorn3** [comment]
Okay

**Comment by Manishearth** [comment]
@gnzlbg given the weird build system errors we were experiencing it may be worth testing out libtest as a part of compiletest first. But works either way, really.

**Comment by gnzlbg** [comment]
@manish compiletest-rs would just continue to just use the “test” crate on
nightly. That should work both in and out of tree (for stable Rust a
different crate is used).

**Comment by Manishearth** [comment]
I mean, ideally, as a part of this compiletest-rs becomes stable-only, since libtest is stable

**Comment by gnzlbg** [comment]
libtest on crates.io does not work on stable Rust.

**Comment by Manishearth** [comment]
What's the reason behind that? Can we fix that first?

**Comment by gnzlbg** [comment]
We could, There is a PR open to libtest that does that, but it’s unclear
whether that libtest can be used in tree.

**Comment by Manishearth** [comment]
Ah.
