### PR TITLE
Move E0101 and E0102 logic into new E0282 mechanism #40013

### LINKED ISSUE #40013: use the new "unconstrained type parameter" callbacks more often
https://github.com/rust-lang/rust/pull/39361 improved our error messages around uninferable types, but there is still room to do better. For one thing, as @arielb1 pointed out, we currently detect these errors in a kind of odd place (when a `Sized` obligation is not matchable). ~~We could generalize this to **any** obligation that includes an unresolved inference variable, I suspect.~~ Moreover, there are cases where we don't encounter the error about an unconstrained inference variable until writeback:

```rust
fn main() {
    let x = [];
}
```

Therefore, the [error reporting for unknown types in writeback](https://github.com/rust-lang/rust/blob/a7f63d12a701f8d2c7b975ef605a50bb83318b90/src/librustc_typeck/check/writeback.rs#L585) ought to use the new helpers introduced in #39361

cc @cengizIO -- would you like to keep on working on this?

UPDATE: I was wrong to say this behavior applies any time we have an unresolved obligation. Sometimes it does, but not always.

### PR DESCRIPTION
**Pull request by cengiz-io**
Hello there!

## What's this?
Previously, me and @nikomatsakis worked on error messages of uninferred locals. (#38812)

This aims to build up on that by moving certain type checks from `writeback`.

With this, `E0101` and `E0102` errors are getting obsoleted and no longer thrown.

They're replaced with customized versions of `E0282`s instead.

#### `E0101` is getting converted into:
```rust
error[E0282]: type annotations needed
 --> test.rs:2:14
  |
2 |     let x = |_| {};
  |              ^ consider giving this closure parameter a type

error: aborting due to previous error
```

#### `E0102` is getting converted into:
```rust
error[E0282]: type annotations needed
 --> test.rs:2:9
  |
2 |     let x = [];
  |         ^
  |         |
  |         consider giving `x` a type
  |         cannot infer type for `[_; 0]`

error: aborting due to previous error
```

## Annoyances
- I think we need to change our way of type name resolving in relevant places, because that `[_; 0]` looks horrible IMHO.
- I'm not terribly happy with the note ordering of errors. So please do point to code that might help me accomplish this.

## Tests
Tests of `E0101` and `E0102` are getting converted from `compile-fail` to `ui` tests. 

## Documentation
Please help me with documentation update. There are some confusing places that needed an update but I'm not sure if I did the right ones.

Please do comment on messages, layouts and other details.

## Appreciation
Huge thanks goes to @nikomatsakis for being a patient and humble mentor along this long journey. 🍻

### CODE REVIEW

File: src/librustc/traits/error_reporting.rs [hunk 1]
```diff
@@ -65,24 +65,41 @@ impl<'a, 'gcx, 'tcx> TraitErrorKey<'tcx> {
 struct FindLocalByTypeVisitor<'a, 'gcx: 'a + 'tcx, 'tcx: 'a> {
     infcx: &'a InferCtxt<'a, 'gcx, 'tcx>,
     target_ty: &'a Ty<'tcx>,
-    found_pattern: Option<&'a Pat>,
+    hir_map: &'a hir::map::Map<'gcx>,
+    found_pattern: Option<&'gcx Pat>,
```
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: maybe we should call this `found_local_pattern`

File: src/librustc/traits/error_reporting.rs [hunk 2]
```diff
@@ -835,42 +854,51 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
         }
     }
 
-    fn need_type_info(&self, obligation: &PredicateObligation<'tcx>, ty: Ty<'tcx>) {
+    pub fn need_type_info(&self, body_id: hir::BodyId, span: Span, ty: Ty<'tcx>) {
```
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: Nit for future PR: feels like this function (and its associated visitor etc) would be ripe for promotion into a sub-module `error_reporting/need_type_info.rs`

File: src/librustc/traits/error_reporting.rs [hunk 3]
```diff
@@ -835,42 +854,51 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
         // Currently, if it's anything other than NodeExpr, we just ignore it
-        match self.tcx.hir.find(cause.body_id) {
+        match self.tcx.hir.find(body_id.node_id) {
             Some(NodeExpr(expr)) => local_visitor.visit_expr(expr),
             _ => ()
         }
 
+        if let Some(pattern) = local_visitor.found_arg_pattern {
+            err_span = pattern.span;
+            labels.clear();
```
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: should comment on why we are calling `clear` here; maybe give before/after example

File: src/librustc_typeck/check/writeback.rs [hunk 4]
```diff
@@ -430,72 +429,47 @@ impl<'cx, 'gcx, 'tcx> WritebackCx<'cx, 'gcx, 'tcx> {
...
-            let ftys = self.resolve(ftys, ResolvingFieldTypes(node_id));
+            let ftys = self.resolve(ftys, node_id.to_span(&self.fcx.tcx));
             self.tables.fru_field_types.insert(node_id, ftys);
         }
     }
 
     fn visit_type_nodes(&self) {
         for (&id, ty) in self.fcx.ast_ty_to_ty_cache.borrow().iter() {
-            let ty = self.resolve(ty, ResolvingTyNode(id));
+            let ty = self.resolve(ty, id.to_span(&self.fcx.tcx));
```
Comment (nikomatsakis) [inline src/librustc_typeck/check/writeback.rs]: I have a vague fear that this will add to compilation times; these spans are only needed if an error occurs. I wonder if we could change `resolve` to take a closure, so that we only evaluate and get the span if an error occurs.

Comment (nikomatsakis) [inline src/librustc_typeck/check/writeback.rs]: This was part of the reason that I suggested the `Locatable` trait; you could e.g. change `resolve` to take an `&Locatable` (i.e., a trait object), in which case the `span` field of `Resolver` would change I think to the type `&'cx Locatable`

**Review by nikomatsakis — CHANGES_REQUESTED** [review]
Let me know what you think. If what I want is unclear, I can also try to do it locally, since I think it *ought* to be fairly simple and I'm not sure if I explained it well.

File: src/librustc/traits/error_reporting.rs (hunk 1 above)
Comment (cengizIO) [inline src/librustc/traits/error_reporting.rs]: ok

File: src/librustc/traits/error_reporting.rs (hunk 2 above)
Comment (cengizIO) [inline src/librustc/traits/error_reporting.rs]: Sounds good Will do as soon as this lands

Comment (cengizIO) [inline src/librustc/traits/error_reporting.rs]: https://github.com/rust-lang/rust/issues/41284

File: src/librustc/traits/error_reporting.rs (hunk 3 above)
Comment (cengizIO) [inline src/librustc/traits/error_reporting.rs]: Ok

**Comment by cengizIO** [comment]
Hello @nikomatsakis 

It took me sometime to merge `upstream` changes and fix `ui` tests.

Only the performance tuning remains now. Will send it tomorrow ASAP.

Thanks!

File: src/librustc/diagnostics.rs [hunk 5]
```diff
@@ -327,6 +327,54 @@ struct ListNode {
 This works because `Box` is a pointer, so its size is well-known.
 "##,
 
+E0101: r##"
```
Comment (arielb1) [inline src/librustc/diagnostics.rs]: You should comment this error out.(see E0211).

File: src/librustc/traits/error_reporting.rs [hunk 6]
```diff
@@ -874,42 +893,66 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
+
+        if let Some(pattern) = local_visitor.found_local_pattern {
             if let Some(simple_name) = pattern.simple_name() {
-                err.span_label(pattern_span,
-                               &format!("consider giving `{}` a type",
-                                        simple_name));
+                labels.push((pattern.span, format!("consider giving `{}` a type", simple_name)));
             } else {
-                err.span_label(pattern_span, &format!("consider giving a type to pattern"));
+                labels.push((pattern.span, format!("consider giving a type to pattern")));
```
Comment (arielb1) [inline src/librustc/traits/error_reporting.rs]: English: consider giving the pattern a type

File: src/librustc/traits/error_reporting.rs [hunk 7]
```diff
@@ -874,42 +893,66 @@ impl<'a, 'gcx, 'tcx> InferCtxt<'a, 'gcx, 'tcx> {
...
-        let ref cause = obligation.cause;
 
-        let mut err = struct_span_err!(self.tcx.sess,
-                                       cause.span,
-                                       E0282,
-                                       "type annotations needed");
-
-        err.span_label(cause.span, &format!("cannot infer type for `{}`", name));
+        let mut err_span = span;
+        let mut labels = vec![(span, format!("cannot infer type for `{}`", name))];
```
Comment (arielb1) [inline src/librustc/traits/error_reporting.rs]: do we ever need this message? I think an unspanned local is always bad enough.

File: src/librustc/diagnostics.rs (hunk 5 above)
Comment (cengizIO) [inline src/librustc/diagnostics.rs]: Done

File: src/librustc/traits/error_reporting.rs [hunk 8]
```diff
@@ -66,37 +66,52 @@ impl<'a, 'gcx, 'tcx> TraitErrorKey<'tcx> {
 struct FindLocalByTypeVisitor<'a, 'gcx: 'a + 'tcx, 'tcx: 'a> {
     infcx: &'a InferCtxt<'a, 'gcx, 'tcx>,
     target_ty: &'a Ty<'tcx>,
-    found_pattern: Option<&'a Pat>,
+    hir_map: &'a hir::map::Map<'gcx>,
+    found_local_pattern: Option<&'gcx Pat>,
```
Comment (arielb1) [inline src/librustc/traits/error_reporting.rs]: Why do you have separate options for `found_local_pattern` and `found_arg_pattern`?

File: src/librustc/traits/error_reporting.rs (hunk 7 above)
Comment (cengizIO) [inline src/librustc/traits/error_reporting.rs]: Yes we do. That was decided long time ago in a different issue + PR.
https://github.com/rust-lang/rust/issues/38812

Comment (arielb1) [inline src/librustc/traits/error_reporting.rs]: Another thing that would be nice is to always use the *type* of the local,
```
E101: cannot completely resolve the type of `x`
let x = vec![];
//   ^ `x` can only be resolved to `Vec<_>`
```

File: src/librustc/traits/error_reporting.rs (hunk 8 above)
Comment (cengizIO) [inline src/librustc/traits/error_reporting.rs]: They're not only holding target patterns, but also changing the flow of the result.

Can you share your suggestion with a concrete example please?

Comment (arielb1) [inline src/librustc/traits/error_reporting.rs]:
```Rust
enum TypeVariableHolder<'gcx> {
    // later, TypeParam(...),
    Argument(&'gcx Pat),
    Local(&'gcx Pat),
}

struct FindLocalByTypeVisitor<'a, 'gcx: 'a + 'tcx, 'tcx: 'a> { 
    found_variable_holder: Option<TypeVariableHolder<'gcx>>
}
```

And find the maximum relevant `TypeVariableHolder`.

**Comment by cengizIO** [comment]
Commits are squashed, and resolving logic has been optimized (relatively).

⏲

File: src/librustc/traits/error_reporting.rs (hunk 8 above)
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: It doesn't seem like it makes much difference either way to me.

File: src/librustc/traits/error_reporting.rs (hunk 7 above)
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: Yeah, I feel like it'd be nice to say what we *do* now of the type, but we never did settle on the precise format we wanted for it. (The discussion was in https://github.com/rust-lang/rust/pull/39361)

File: src/librustc_typeck/diagnostics.rs [hunk 9]
```diff
@@ -4146,8 +4102,6 @@ register_diagnostics! {
 //  E0068,
 //  E0085,
 //  E0086,
-    E0103, // @GuillaumeGomez: I was unable to get this error, try your best!
-    E0104,
```
Comment (nikomatsakis) [inline src/librustc_typeck/diagnostics.rs]: I don't think we usually remove these lints *outright*, but rather leave them commented out.. or at least that's what the surrounding lines seem to suggest. =) 

cc @rust-lang/docs -- what is the policy when an error code is no longer issued? (And what about if a "long-form" error exists, as in the case of E0102 above?) Is this documented somewhere? ([RFC 1567](https://github.com/rust-lang/rfcs/blob/master/text/1567-long-error-codes-explanation-normalization.md) doesn't seem to mention it.)

Comment (jonathandturner) [inline src/librustc_typeck/diagnostics.rs]: The general rule of thumb is "don't reuse error codes".  It's okay to deprecate and just not output that code anymore, but reusing tends to mess with search results.

File: src/librustc/traits/error_reporting.rs (hunk 8 above)
Comment (arielb1) [inline src/librustc/traits/error_reporting.rs]: Actually it's mainly something I want to build on.

File: src/librustc_typeck/diagnostics.rs (hunk 9 above)
Comment (arielb1) [inline src/librustc_typeck/diagnostics.rs]: @cengizIO 

You should leave them commented out, like the previous ones.

Comment (cengizIO) [inline src/librustc_typeck/diagnostics.rs]: @arielb1 commented them out.

Also instead of adding whole documentation as a comment, I've added `// E0101` and `// E0102` to `register_diagnostics!` call. 

If you have both the commented documentation and a `register_diagnostics!` call for an error code, `tidy` complains. Even if they're only comments.

File: src/librustc/traits/error_reporting.rs (hunk 8 above)
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: Makes sense. I would be fine landing as is, but also fine with adopting the single enum approach -- I imagine as we add more cases, we'll probably want a single enum, as you suggest. (Though I was wondering if it may be the case that we can't detect until the end whether certain patterns are met, and hence we wouldn't be able to decide the final state until the end.) Either way, easy to evolve as needed.

File: src/librustc/traits/error_reporting.rs (hunk 6 above)
Comment (nikomatsakis) [inline src/librustc/traits/error_reporting.rs]: Hmm I agree this phrasing isn't the best. "consider giving a type to **the** pattern" or "consider giving the pattern a type" both seem fine to me.

**Review by nikomatsakis — APPROVED** [review]

**Comment by frewsxcv** [comment]
@bors retry

prioritizing rollup which includes this
